# -*- coding: utf-8 -*-
"""Topic 12 — extra problems, appended to lesson_12.py by content/build.py.

Source labels: where the competition is known for certain it is named; the
round labels ("Районный тур · уровень") describe the level a problem is
typical of, not a claim about where it was set.
"""

SCHOOL   = 'Школьный тур · уровень / School-round level'
DISTRICT = 'Районный тур · уровень / District-round level'
REGION   = 'Областной тур · уровень / Regional-round level'
REPUBLIC = 'Республиканский тур · уровень / Republic-round level'
INTL     = 'Международный уровень / International level'
CLASSIC  = 'Классическая задача / Classic'

EXTRA = [

 # ------------------------------------------------------------------ level 1
 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите расстояние между точками $A(1,2)$ и $B(4,6)$.',
        'en': r'Find the distance between $A(1,2)$ and $B(4,6)$.'},
  'hint': {'ru': r'$AB=\sqrt{\left(x_2-x_1\right)^{2}+\left(y_2-y_1\right)^{2}}$.',
           'en': r'$AB=\sqrt{\left(x_2-x_1\right)^{2}+\left(y_2-y_1\right)^{2}}$.'},
  'sol': {'ru': r'$$AB=\sqrt{(4-1)^{2}+(6-2)^{2}}=\sqrt{9+16}=\sqrt{25}=5 .$$\n\n**Ответ:** $5$.\n\n**Откуда формула.** Отрезок $AB$ — гипотенуза прямоугольного треугольника с катетами $\left|x_2-x_1\right|$ и $\left|y_2-y_1\right|$, параллельными осям.',
          'en': r'$$AB=\sqrt{(4-1)^{2}+(6-2)^{2}}=\sqrt{9+16}=\sqrt{25}=5 .$$\n\n**Answer:** $5$.\n\n**Where the formula comes from.** The segment $AB$ is the hypotenuse of a right triangle with legs $\left|x_2-x_1\right|$ and $\left|y_2-y_1\right|$ parallel to the axes.'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите середину отрезка с концами $(-3,7)$ и $(5,1)$.',
        'en': r'Find the midpoint of the segment with endpoints $(-3,7)$ and $(5,1)$.'},
  'hint': {'ru': r'Координаты середины — средние арифметические.',
           'en': r'The midpoint coordinates are the averages.'},
  'sol': {'ru': r'$$x_M=\frac{-3+5}{2}=1,\qquad y_M=\frac{7+1}{2}=4 .$$\n\n**Ответ:** $(1,4)$.\n\n**Проверка:** расстояния от $(1,4)$ до обоих концов равны $\sqrt{16+9}=5$ ✓',
          'en': r'$$x_M=\frac{-3+5}{2}=1,\qquad y_M=\frac{7+1}{2}=4 .$$\n\n**Answer:** $(1,4)$.\n\n**Check:** the distances from $(1,4)$ to both endpoints equal $\sqrt{16+9}=5$ ✓'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите угловой коэффициент прямой, проходящей через точки $(2,3)$ и $(6,11)$.',
        'en': r'Find the slope of the line through $(2,3)$ and $(6,11)$.'},
  'hint': {'ru': r'$k=\dfrac{\Delta y}{\Delta x}$.',
           'en': r'$k=\dfrac{\Delta y}{\Delta x}$.'},
  'sol': {'ru': r'$$k=\frac{11-3}{6-2}=\frac84=2 .$$\n\n**Ответ:** $k=2$.\n\n**Уравнение прямой:** $y-3=2(x-2)$, то есть $y=2x-1$. Проверка: при $x=6$ получаем $y=11$ ✓',
          'en': r'$$k=\frac{11-3}{6-2}=\frac84=2 .$$\n\n**Answer:** $k=2$.\n\n**The line:** $y-3=2(x-2)$, i.e. $y=2x-1$. Check: at $x=6$ we get $y=11$ ✓'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Напишите уравнение прямой, проходящей через точку $(0,5)$ с угловым коэффициентом $-2$.',
        'en': r'Write the equation of the line through $(0,5)$ with slope $-2$.'},
  'hint': {'ru': r'$y=kx+b$, где $b$ — ордината точки пересечения с осью $Oy$.',
           'en': r'$y=kx+b$, where $b$ is the $y$-intercept.'},
  'sol': {'ru': r'Точка $(0,5)$ лежит на оси $Oy$, значит $b=5$. С учётом $k=-2$ получаем $$y=-2x+5 .$$\n\n**Ответ:** $y=-2x+5$.\n\n**Проверка:** при $x=1$ имеем $y=3$; шаг вправо на единицу опускает прямую на две единицы, как и должно быть при $k=-2$ ✓',
          'en': r'The point $(0,5)$ lies on the $y$-axis, so $b=5$. With $k=-2$, $$y=-2x+5 .$$\n\n**Answer:** $y=-2x+5$.\n\n**Check:** at $x=1$ we get $y=3$; a step of one to the right drops the line by two, as $k=-2$ requires ✓'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Лежит ли точка $(3,4)$ на окружности $x^{2}+y^{2}=25$?',
        'en': r'Does the point $(3,4)$ lie on the circle $x^{2}+y^{2}=25$?'},
  'hint': {'ru': r'Подставьте координаты.',
           'en': r'Substitute the coordinates.'},
  'sol': {'ru': r'Подставим: $$3^{2}+4^{2}=9+16=25 \quad\checkmark$$\n\nРавенство выполнено, значит точка лежит на окружности.\n\n**Ответ:** да.\n\n**Замечание.** Если бы получилось меньше $25$, точка лежала бы внутри круга, если больше — вне его.',
          'en': r'Substitute: $$3^{2}+4^{2}=9+16=25 \quad\checkmark$$\n\nThe equation holds, so the point is on the circle.\n\n**Answer:** yes.\n\n**Remark.** A value below $25$ would put the point inside the disc, a value above it outside.'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите точку пересечения прямых $y=2x+1$ и $y=-x+7$.',
        'en': r'Find the intersection point of the lines $y=2x+1$ and $y=-x+7$.'},
  'hint': {'ru': r'Приравняйте правые части.',
           'en': r'Set the right-hand sides equal.'},
  'sol': {'ru': r'Приравняем: $$2x+1=-x+7\quad\Longrightarrow\quad 3x=6\quad\Longrightarrow\quad x=2 .$$\n\nТогда $y=2\cdot2+1=5$.\n\n**Проверка** во втором уравнении: $-2+7=5$ ✓\n\n**Ответ:** $(2,5)$.',
          'en': r'Equate them: $$2x+1=-x+7\quad\Longrightarrow\quad 3x=6\quad\Longrightarrow\quad x=2 .$$\n\nThen $y=2\cdot2+1=5$.\n\n**Check** in the second equation: $-2+7=5$ ✓\n\n**Answer:** $(2,5)$.'}},

 # ------------------------------------------------------------------ level 2
 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Напишите уравнение прямой, проходящей через точки $(1,2)$ и $(5,10)$.',
        'en': r'Write the equation of the line through $(1,2)$ and $(5,10)$.'},
  'hint': {'ru': r'Сначала найдите угловой коэффициент.',
           'en': r'Find the slope first.'},
  'sol': {'ru': r'Угловой коэффициент: $$k=\frac{10-2}{5-1}=\frac84=2 .$$\n\nУравнение через точку $(1,2)$: $$y-2=2(x-1)\quad\Longrightarrow\quad y=2x .$$\n\n**Проверка:** при $x=5$ получаем $y=10$ ✓\n\n**Ответ:** $y=2x$ (прямая проходит через начало координат).',
          'en': r'The slope is $$k=\frac{10-2}{5-1}=\frac84=2 .$$\n\nThrough the point $(1,2)$: $$y-2=2(x-1)\quad\Longrightarrow\quad y=2x .$$\n\n**Check:** at $x=5$ we get $y=10$ ✓\n\n**Answer:** $y=2x$ — the line passes through the origin.'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Найдите площадь треугольника с вершинами $(1,1)$, $(4,1)$, $(1,5)$.',
        'en': r'Find the area of the triangle with vertices $(1,1)$, $(4,1)$, $(1,5)$.'},
  'hint': {'ru': r'Две стороны параллельны осям.',
           'en': r'Two sides are parallel to the axes.'},
  'sol': {'ru': r'Сторона от $(1,1)$ до $(4,1)$ горизонтальна и имеет длину $3$; сторона от $(1,1)$ до $(1,5)$ вертикальна и имеет длину $4$. Угол между ними прямой, значит $$S=\frac12\cdot3\cdot4=6 .$$\n\n**Ответ:** $6$.\n\n**Проверка формулой площади через координаты:** $$S=\frac12\left|3\cdot4-0\cdot0\right|=6 \quad\checkmark$$',
          'en': r'The side from $(1,1)$ to $(4,1)$ is horizontal of length $3$; the side from $(1,1)$ to $(1,5)$ is vertical of length $4$. They meet at a right angle, so $$S=\frac12\cdot3\cdot4=6 .$$\n\n**Answer:** $6$.\n\n**Check by the coordinate area formula:** $$S=\frac12\left|3\cdot4-0\cdot0\right|=6 \quad\checkmark$$'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Найдите расстояние от начала координат до прямой $3x+4y-10=0$.',
        'en': r'Find the distance from the origin to the line $3x+4y-10=0$.'},
  'hint': {'ru': r'$d=\dfrac{\left|ax_0+by_0+c\right|}{\sqrt{a^{2}+b^{2}}}$.',
           'en': r'$d=\dfrac{\left|ax_0+by_0+c\right|}{\sqrt{a^{2}+b^{2}}}$.'},
  'sol': {'ru': r'Подставим $\left(x_0,y_0\right)=(0,0)$: $$d=\frac{\left|3\cdot0+4\cdot0-10\right|}{\sqrt{3^{2}+4^{2}}}=\frac{10}{5}=2 .$$\n\n**Ответ:** $2$.\n\n**Проверка.** Ближайшая точка прямой к началу координат лежит на перпендикуляре, то есть на прямой $y=\tfrac43x$. Подставив в уравнение: $3x+\tfrac{16}{3}x=10$, откуда $x=1{,}2$ и $y=1{,}6$; расстояние равно $\sqrt{1{,}44+2{,}56}=2$ ✓',
          'en': r'Substitute $\left(x_0,y_0\right)=(0,0)$: $$d=\frac{\left|3\cdot0+4\cdot0-10\right|}{\sqrt{3^{2}+4^{2}}}=\frac{10}{5}=2 .$$\n\n**Answer:** $2$.\n\n**Check.** The nearest point of the line lies on the perpendicular $y=\tfrac43x$. Substituting: $3x+\tfrac{16}{3}x=10$, so $x=1.2$, $y=1.6$, and the distance is $\sqrt{1.44+2.56}=2$ ✓'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Напишите уравнение окружности с центром $(3,4)$, проходящей через начало координат.',
        'en': r'Write the equation of the circle with centre $(3,4)$ passing through the origin.'},
  'hint': {'ru': r'Радиус — это расстояние от центра до начала координат.',
           'en': r'The radius is the distance from the centre to the origin.'},
  'sol': {'ru': r'Радиус равен расстоянию от центра до точки $(0,0)$: $$R=\sqrt{3^{2}+4^{2}}=5 .$$\n\nЗначит уравнение $$(x-3)^{2}+(y-4)^{2}=25 .$$\n\n**Проверка:** подставив $(0,0)$, получаем $9+16=25$ ✓\n\n**В общем виде:** раскрыв скобки, $x^{2}+y^{2}-6x-8y=0$.',
          'en': r'The radius is the distance from the centre to $(0,0)$: $$R=\sqrt{3^{2}+4^{2}}=5 .$$\n\nSo the equation is $$(x-3)^{2}+(y-4)^{2}=25 .$$\n\n**Check:** substituting $(0,0)$ gives $9+16=25$ ✓\n\n**Expanded form:** $x^{2}+y^{2}-6x-8y=0$.'}},

 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Докажите, что четырёхугольник с вершинами $(1,2)$, $(4,3)$, $(5,6)$, $(2,5)$ — параллелограмм.',
        'en': r'Prove that the quadrilateral with vertices $(1,2)$, $(4,3)$, $(5,6)$, $(2,5)$ is a parallelogram.'},
  'hint': {'ru': r'Достаточно проверить, что диагонали делятся пополам.',
           'en': r'It suffices to check that the diagonals bisect each other.'},
  'sol': {'ru': r'Обозначим вершины $A(1,2)$, $B(4,3)$, $C(5,6)$, $D(2,5)$.\n\n**Середина диагонали $AC$:** $$\left(\frac{1+5}{2},\ \frac{2+6}{2}\right)=(3,4).$$\n\n**Середина диагонали $BD$:** $$\left(\frac{4+2}{2},\ \frac{3+5}{2}\right)=(3,4).$$\n\nСередины совпали, значит диагонали делятся точкой пересечения пополам — а это признак параллелограмма. $\blacksquare$\n\n**Проверка через векторы:** $$\overrightarrow{AB}=(3,1),\qquad \overrightarrow{DC}=(3,1) ,$$ векторы равны, значит $AB\parallel DC$ и $AB=DC$ ✓',
          'en': r'Label the vertices $A(1,2)$, $B(4,3)$, $C(5,6)$, $D(2,5)$.\n\n**Midpoint of the diagonal $AC$:** $$\left(\frac{1+5}{2},\ \frac{2+6}{2}\right)=(3,4).$$\n\n**Midpoint of the diagonal $BD$:** $$\left(\frac{4+2}{2},\ \frac{3+5}{2}\right)=(3,4).$$\n\nThe midpoints coincide, so the diagonals bisect each other — the parallelogram test. $\blacksquare$\n\n**Check with vectors:** $$\overrightarrow{AB}=(3,1),\qquad \overrightarrow{DC}=(3,1) ,$$ equal vectors, so $AB\parallel DC$ and $AB=DC$ ✓'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'При каком $k$ точки $(1,2)$, $(3,k)$ и $(5,10)$ лежат на одной прямой?',
        'en': r'For which $k$ are the points $(1,2)$, $(3,k)$ and $(5,10)$ collinear?'},
  'hint': {'ru': r'Угловые коэффициенты должны совпадать.',
           'en': r'The slopes must agree.'},
  'sol': {'ru': r'Прямая через крайние точки имеет угловой коэффициент $$k_0=\frac{10-2}{5-1}=2 ,$$ и её уравнение $y=2x$ (проверка: при $x=1$ выходит $2$ ✓).\n\nТочка $(3,k)$ лежит на ней тогда и только тогда, когда $$k=2\cdot3=6 .$$\n\n**Ответ:** $k=6$.\n\n**Другой путь.** Точки коллинеарны, когда площадь треугольника на них равна нулю: $$\frac12\left|(3-1)(10-2)-(5-1)(k-2)\right|=0\ \Longrightarrow\ 16=4(k-2)\ \Longrightarrow\ k=6 \quad\checkmark$$',
          'en': r'The line through the outer points has slope $$k_0=\frac{10-2}{5-1}=2 ,$$ with equation $y=2x$ (check: at $x=1$ it gives $2$ ✓).\n\nThe point $(3,k)$ lies on it exactly when $$k=2\cdot3=6 .$$\n\n**Answer:** $k=6$.\n\n**Another route.** Points are collinear when the triangle they form has zero area: $$\frac12\left|(3-1)(10-2)-(5-1)(k-2)\right|=0\ \Longrightarrow\ 16=4(k-2)\ \Longrightarrow\ k=6 \quad\checkmark$$'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Найдите точку, симметричную $(2,3)$ относительно оси $Ox$ и относительно прямой $y=x$.',
        'en': r'Find the reflections of $(2,3)$ in the $x$-axis and in the line $y=x$.'},
  'hint': {'ru': r'Отражение относительно $Ox$ меняет знак ординаты.',
           'en': r'Reflecting in the $x$-axis flips the sign of the $y$-coordinate.'},
  'sol': {'ru': r'**Относительно оси $Ox$.** Абсцисса сохраняется, ордината меняет знак: $$(2,3)\ \mapsto\ (2,-3).$$\n\n**Относительно прямой $y=x$.** Координаты меняются местами: $$(2,3)\ \mapsto\ (3,2).$$\n\n**Почему.** Середина отрезка между $(2,3)$ и $(3,2)$ — это $\left(2{,}5;\ 2{,}5\right)$, она лежит на прямой $y=x$; а вектор $(1,-1)$ перпендикулярен направляющему вектору $(1,1)$ этой прямой ✓\n\n**Ответ:** $(2,-3)$ и $(3,2)$.',
          'en': r'**In the $x$-axis.** The abscissa stays, the ordinate flips sign: $$(2,3)\ \mapsto\ (2,-3).$$\n\n**In the line $y=x$.** The coordinates swap: $$(2,3)\ \mapsto\ (3,2).$$\n\n**Why.** The midpoint of the segment from $(2,3)$ to $(3,2)$ is $(2.5,\,2.5)$, which lies on $y=x$; and the vector $(1,-1)$ is perpendicular to the direction $(1,1)$ of that line ✓\n\n**Answer:** $(2,-3)$ and $(3,2)$.'}},

 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Напишите уравнение окружности, для которой отрезок с концами $(1,2)$ и $(7,10)$ — диаметр.',
        'en': r'Write the equation of the circle having the segment from $(1,2)$ to $(7,10)$ as a diameter.'},
  'hint': {'ru': r'Центр — середина диаметра.',
           'en': r'The centre is the midpoint of the diameter.'},
  'sol': {'ru': r'**Центр** — середина отрезка: $$\left(\frac{1+7}{2},\ \frac{2+10}{2}\right)=(4,6).$$\n\n**Радиус** — половина длины диаметра: $$d=\sqrt{6^{2}+8^{2}}=10\quad\Longrightarrow\quad R=5 .$$\n\n**Уравнение:** $$(x-4)^{2}+(y-6)^{2}=25 .$$\n\n**Проверка:** точка $(1,2)$ даёт $9+16=25$ ✓\n\n**Полезный факт.** Точка $M$ лежит на этой окружности тогда и только тогда, когда отрезок виден из неё под прямым углом.',
          'en': r'**The centre** is the midpoint: $$\left(\frac{1+7}{2},\ \frac{2+10}{2}\right)=(4,6).$$\n\n**The radius** is half the diameter: $$d=\sqrt{6^{2}+8^{2}}=10\quad\Longrightarrow\quad R=5 .$$\n\n**The equation:** $$(x-4)^{2}+(y-6)^{2}=25 .$$\n\n**Check:** the point $(1,2)$ gives $9+16=25$ ✓\n\n**A useful fact.** A point $M$ lies on this circle exactly when the segment subtends a right angle at $M$.'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Найдите множество точек, равноудалённых от $A(0,0)$ и $B(4,0)$.',
        'en': r'Find the set of points equidistant from $A(0,0)$ and $B(4,0)$.'},
  'hint': {'ru': r'Приравняйте квадраты расстояний.',
           'en': r'Equate the squared distances.'},
  'sol': {'ru': r'Пусть $M(x,y)$. Условие $MA=MB$ равносильно равенству квадратов: $$x^{2}+y^{2}=(x-4)^{2}+y^{2} .$$\n\nСлагаемые $x^{2}$ и $y^{2}$ сокращаются: $$0=-8x+16\quad\Longrightarrow\quad x=2 .$$\n\n**Ответ:** вертикальная прямая $x=2$ — серединный перпендикуляр к отрезку $AB$.\n\n**Замечание.** Так и получается общий факт: множество точек, равноудалённых от двух данных, — серединный перпендикуляр к соединяющему их отрезку.',
          'en': r'Let $M(x,y)$. The condition $MA=MB$ is equivalent to equal squares: $$x^{2}+y^{2}=(x-4)^{2}+y^{2} .$$\n\nThe $x^{2}$ and $y^{2}$ terms cancel: $$0=-8x+16\quad\Longrightarrow\quad x=2 .$$\n\n**Answer:** the vertical line $x=2$ — the perpendicular bisector of $AB$.\n\n**Remark.** This is the general fact: the points equidistant from two given points form the perpendicular bisector of the segment joining them.'}},

 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Найдите на оси $Ox$ точку, равноудалённую от $(1,2)$ и $(5,4)$.',
        'en': r'Find the point on the $x$-axis equidistant from $(1,2)$ and $(5,4)$.'},
  'hint': {'ru': r'Точка имеет вид $(x,0)$.',
           'en': r'The point has the form $(x,0)$.'},
  'sol': {'ru': r'Пусть искомая точка $M(x,0)$. Приравняем квадраты расстояний: $$(x-1)^{2}+4=(x-5)^{2}+16 .$$\n\nРаскроем: $$x^{2}-2x+1+4=x^{2}-10x+25+16 ,$$ то есть $$-2x+5=-10x+41\quad\Longrightarrow\quad 8x=36\quad\Longrightarrow\quad x=4{,}5 .$$\n\n**Проверка:** $$(4{,}5-1)^{2}+4=12{,}25+4=16{,}25 ,$$ $$(4{,}5-5)^{2}+16=0{,}25+16=16{,}25 \quad\checkmark$$\n\n**Ответ:** $(4{,}5;\ 0)$.',
          'en': r'Let the point be $M(x,0)$. Equate the squared distances: $$(x-1)^{2}+4=(x-5)^{2}+16 .$$\n\nExpanding, $$x^{2}-2x+5=x^{2}-10x+41 ,$$ so $$8x=36\quad\Longrightarrow\quad x=4.5 .$$\n\n**Check:** $$(4.5-1)^{2}+4=16.25 ,\qquad (4.5-5)^{2}+16=16.25 \quad\checkmark$$\n\n**Answer:** $(4.5,\ 0)$.'}},

 # ------------------------------------------------------------------ level 3
 {'src': DISTRICT, 'lvl': 3,
  'q': {'ru': r'Найдите расстояние между параллельными прямыми $3x+4y-5=0$ и $3x+4y+15=0$.',
        'en': r'Find the distance between the parallel lines $3x+4y-5=0$ and $3x+4y+15=0$.'},
  'hint': {'ru': r'Возьмите любую точку одной прямой и посчитайте расстояние до другой.',
           'en': r'Take any point on one line and measure to the other.'},
  'sol': {'ru': r'**Способ 1.** Возьмём точку на первой прямой: при $y=-1$ получаем $3x-4-5=0$, то есть $x=3$; точка $(3,-1)$.\n\nРасстояние до второй прямой: $$d=\frac{\left|3\cdot3+4\cdot(-1)+15\right|}{\sqrt{9+16}}=\frac{\left|9-4+15\right|}{5}=\frac{20}{5}=4 .$$\n\n**Способ 2 (общая формула).** Для прямых $ax+by+c_1=0$ и $ax+by+c_2=0$ $$d=\frac{\left|c_1-c_2\right|}{\sqrt{a^{2}+b^{2}}}=\frac{\left|-5-15\right|}{5}=4 \quad\checkmark$$\n\n**Ответ:** $4$.\n\n**Важно:** перед применением формулы коэффициенты при $x$ и $y$ у обеих прямых должны совпадать — иначе их надо предварительно уравнять.',
          'en': r'**Method 1.** Take a point on the first line: at $y=-1$ we get $3x-9=0$, so $x=3$; the point $(3,-1)$.\n\nIts distance to the second line is $$d=\frac{\left|3\cdot3+4\cdot(-1)+15\right|}{\sqrt{9+16}}=\frac{20}{5}=4 .$$\n\n**Method 2 (general formula).** For lines $ax+by+c_1=0$ and $ax+by+c_2=0$, $$d=\frac{\left|c_1-c_2\right|}{\sqrt{a^{2}+b^{2}}}=\frac{20}{5}=4 \quad\checkmark$$\n\n**Answer:** $4$.\n\n**Important:** before using the formula the coefficients of $x$ and $y$ must match in both equations — otherwise rescale first.'}},

 {'src': CLASSIC, 'lvl': 3,
  'q': {'ru': r'Докажите формулу деления отрезка: точка $M$, делящая отрезок $AB$ в отношении $AM:MB=m:n$, имеет координаты $$M\left(\frac{n\,x_A+m\,x_B}{m+n},\ \frac{n\,y_A+m\,y_B}{m+n}\right).$$',
        'en': r'Prove the section formula: the point $M$ dividing $AB$ in the ratio $AM:MB=m:n$ has coordinates $$M\left(\frac{n\,x_A+m\,x_B}{m+n},\ \frac{n\,y_A+m\,y_B}{m+n}\right).$$'},
  'hint': {'ru': r'Спроецируйте на ось $Ox$ и воспользуйтесь теоремой Фалеса.',
           'en': r'Project onto the $x$-axis and use the intercept theorem.'},
  'sol': {'ru': r'**Через векторы.** Условие $AM:MB=m:n$ означает $$\overrightarrow{AM}=\frac{m}{m+n}\,\overrightarrow{AB} .$$\n\nЗначит радиус-вектор точки $M$ равен $$\vec M=\vec A+\frac{m}{m+n}\left(\vec B-\vec A\right)=\frac{(m+n)\vec A+m\vec B-m\vec A}{m+n}=\frac{n\vec A+m\vec B}{m+n} .$$\n\nПокоординатно это и есть требуемая формула. $\blacksquare$\n\n**Частные случаи.**\n\n$m=n$ даёт середину: среднее арифметическое координат.\n\n$m:n=2:1$ даёт центроид на медиане: $$\frac{1\cdot\vec A+2\cdot\vec M_a}{3} ,$$ откуда и получается знаменитая формула центроида $\vec G=\dfrac{\vec A+\vec B+\vec C}{3}$.\n\n**Мнемоника:** коэффициенты «перекрещиваются» — при $A$ стоит $n$, при $B$ стоит $m$.',
          'en': r'**With vectors.** The condition $AM:MB=m:n$ says $$\overrightarrow{AM}=\frac{m}{m+n}\,\overrightarrow{AB} .$$\n\nSo the position vector of $M$ is $$\vec M=\vec A+\frac{m}{m+n}\left(\vec B-\vec A\right)=\frac{n\vec A+m\vec B}{m+n} .$$\n\nCoordinatewise this is the stated formula. $\blacksquare$\n\n**Special cases.**\n\n$m=n$ gives the midpoint: the average of the coordinates.\n\n$m:n=2:1$ gives the centroid along a median: $$\frac{\vec A+2\vec M_a}{3} ,$$ from which the familiar $\vec G=\dfrac{\vec A+\vec B+\vec C}{3}$ follows.\n\n**Mnemonic:** the coefficients cross over — $A$ carries $n$ and $B$ carries $m$.'}},

 {'src': CLASSIC, 'lvl': 3,
  'q': {'ru': r'Докажите координатным методом, что серединные перпендикуляры к сторонам треугольника пересекаются в одной точке.',
        'en': r'Prove by coordinates that the perpendicular bisectors of the sides of a triangle are concurrent.'},
  'hint': {'ru': r'Запишите условие «равноудалённости» через квадраты расстояний.',
           'en': r'Write "equidistant" through squared distances.'},
  'sol': {'ru': r'Пусть вершины имеют координаты $A\left(x_1,y_1\right)$, $B\left(x_2,y_2\right)$, $C\left(x_3,y_3\right)$, и пусть $$f_A(M)=MA^{2},\quad f_B(M)=MB^{2},\quad f_C(M)=MC^{2} .$$\n\n**Шаг 1: серединный перпендикуляр — это линия уровня.** Уравнение $f_A(M)=f_B(M)$ раскрывается так: $$\left(x-x_1\right)^{2}+\left(y-y_1\right)^{2}=\left(x-x_2\right)^{2}+\left(y-y_2\right)^{2} .$$ Квадраты $x^{2}$ и $y^{2}$ сокращаются, и остаётся **линейное** уравнение — то есть прямая. Это и есть серединный перпендикуляр к $AB$ (он состоит из точек, равноудалённых от $A$ и $B$).\n\n**Шаг 2: две прямые пересекаются.** Серединные перпендикуляры к $AB$ и к $BC$ перпендикулярны непараллельным прямым $AB$ и $BC$ (вершины не лежат на одной прямой), значит сами не параллельны и пересекаются в некоторой точке $O$.\n\n**Шаг 3: третий перпендикуляр проходит через $O$.** В точке $O$ выполнено $$f_A(O)=f_B(O)\quad\text{и}\quad f_B(O)=f_C(O) ,$$ значит $f_A(O)=f_C(O)$, то есть $O$ лежит и на серединном перпендикуляре к $AC$. $\blacksquare$\n\n**Следствие.** Точка $O$ равноудалена от всех трёх вершин, значит она — центр описанной окружности, и такая окружность существует и единственна.',
          'en': r'Let the vertices be $A\left(x_1,y_1\right)$, $B\left(x_2,y_2\right)$, $C\left(x_3,y_3\right)$, and set $$f_A(M)=MA^{2},\quad f_B(M)=MB^{2},\quad f_C(M)=MC^{2} .$$\n\n**Step 1: a perpendicular bisector is a level set.** The equation $f_A(M)=f_B(M)$ reads $$\left(x-x_1\right)^{2}+\left(y-y_1\right)^{2}=\left(x-x_2\right)^{2}+\left(y-y_2\right)^{2} .$$ The $x^{2}$ and $y^{2}$ terms cancel, leaving a **linear** equation — a line. It is the perpendicular bisector of $AB$ (the points equidistant from $A$ and $B$).\n\n**Step 2: two of them meet.** The bisectors of $AB$ and $BC$ are perpendicular to the non-parallel lines $AB$ and $BC$ (the vertices are not collinear), hence are themselves non-parallel and meet at some point $O$.\n\n**Step 3: the third passes through $O$.** At $O$ we have $$f_A(O)=f_B(O)\quad\text{and}\quad f_B(O)=f_C(O) ,$$ so $f_A(O)=f_C(O)$, i.e. $O$ lies on the perpendicular bisector of $AC$ as well. $\blacksquare$\n\n**Corollary.** The point $O$ is equidistant from all three vertices, so it is the circumcentre — the circumcircle exists and is unique.'}},

 {'src': REGION, 'lvl': 3,
  'q': {'ru': r'При каких $k$ прямая $y=kx$ пересекает окружность $(x-5)^{2}+y^{2}=9$ в двух точках?',
        'en': r'For which $k$ does the line $y=kx$ meet the circle $(x-5)^{2}+y^{2}=9$ in two points?'},
  'hint': {'ru': r'Сравните расстояние от центра до прямой с радиусом.',
           'en': r'Compare the distance from the centre to the line with the radius.'},
  'sol': {'ru': r'Центр окружности — точка $(5,0)$, радиус $R=3$. Запишем прямую в общем виде: $kx-y=0$.\n\n**Расстояние от центра до прямой:** $$d=\frac{\left|k\cdot5-0\right|}{\sqrt{k^{2}+1}}=\frac{5|k|}{\sqrt{k^{2}+1}} .$$\n\n**Условие двух точек пересечения:** $d<R$, то есть $$\frac{5|k|}{\sqrt{k^{2}+1}}<3 .$$\n\nОбе части неотрицательны — возведём в квадрат: $$25k^{2}<9\left(k^{2}+1\right)\quad\Longrightarrow\quad 16k^{2}<9\quad\Longrightarrow\quad |k|<\frac34 .$$\n\n**Ответ:** $-\dfrac34<k<\dfrac34$.\n\n**Крайние значения** $k=\pm\tfrac34$ дают касание, а при $|k|>\tfrac34$ общих точек нет.\n\n**Проверка:** при $k=0$ прямая $y=0$ пересекает окружность в точках $(2,0)$ и $(8,0)$ ✓',
          'en': r'The centre is $(5,0)$ and the radius $R=3$. Write the line as $kx-y=0$.\n\n**Distance from the centre:** $$d=\frac{\left|5k\right|}{\sqrt{k^{2}+1}} .$$\n\n**Two intersection points** means $d<R$: $$\frac{5|k|}{\sqrt{k^{2}+1}}<3 .$$\n\nBoth sides are non-negative, so square: $$25k^{2}<9\left(k^{2}+1\right)\quad\Longrightarrow\quad 16k^{2}<9\quad\Longrightarrow\quad |k|<\frac34 .$$\n\n**Answer:** $-\dfrac34<k<\dfrac34$.\n\n**The endpoints** $k=\pm\tfrac34$ give tangency, and for $|k|>\tfrac34$ there are no common points.\n\n**Check:** at $k=0$ the line $y=0$ meets the circle at $(2,0)$ and $(8,0)$ ✓'}},

 {'src': DISTRICT, 'lvl': 3,
  'q': {'ru': r'Найдите площадь четырёхугольника с вершинами $(0,0)$, $(4,0)$, $(5,3)$, $(1,4)$.',
        'en': r'Find the area of the quadrilateral with vertices $(0,0)$, $(4,0)$, $(5,3)$, $(1,4)$.'},
  'hint': {'ru': r'Формула площади по координатам («шнурки»).',
           'en': r'The shoelace formula.'},
  'sol': {'ru': r'Вершины перечислены по обходу против часовой стрелки. Применим формулу «шнурков»: $$2S=\sum_{i}\left(x_iy_{i+1}-x_{i+1}y_i\right).$$\n\nПосчитаем по звеньям:\n\n$(0,0)\to(4,0)$: $\ 0\cdot0-4\cdot0=0$;\n\n$(4,0)\to(5,3)$: $\ 4\cdot3-5\cdot0=12$;\n\n$(5,3)\to(1,4)$: $\ 5\cdot4-1\cdot3=17$;\n\n$(1,4)\to(0,0)$: $\ 1\cdot0-0\cdot4=0$.\n\nСумма равна $29$, значит $$S=\frac{29}{2}=14{,}5 .$$\n\n**Ответ:** $14{,}5$.\n\n**Проверка разбиением.** Диагональ от $(0,0)$ до $(5,3)$ делит четырёхугольник на треугольники площадей $$\frac12\left|4\cdot3-5\cdot0\right|=6\qquad\text{и}\qquad \frac12\left|5\cdot4-1\cdot3\right|=8{,}5 ,$$ в сумме $14{,}5$ ✓',
          'en': r'The vertices are listed counterclockwise. Apply the shoelace formula $$2S=\sum_{i}\left(x_iy_{i+1}-x_{i+1}y_i\right).$$\n\nEdge by edge:\n\n$(0,0)\to(4,0)$: $\ 0\cdot0-4\cdot0=0$;\n\n$(4,0)\to(5,3)$: $\ 4\cdot3-5\cdot0=12$;\n\n$(5,3)\to(1,4)$: $\ 5\cdot4-1\cdot3=17$;\n\n$(1,4)\to(0,0)$: $\ 1\cdot0-0\cdot4=0$.\n\nThe sum is $29$, so $$S=\frac{29}{2}=14.5 .$$\n\n**Answer:** $14.5$.\n\n**Check by splitting.** The diagonal from $(0,0)$ to $(5,3)$ cuts it into triangles of areas $$\frac12\left|4\cdot3-5\cdot0\right|=6\qquad\text{and}\qquad \frac12\left|5\cdot4-1\cdot3\right|=8.5 ,$$ summing to $14.5$ ✓'}},

 {'src': CLASSIC, 'lvl': 3,
  'q': {'ru': r'Докажите координатами, что диагонали ромба перпендикулярны.',
        'en': r'Prove by coordinates that the diagonals of a rhombus are perpendicular.'},
  'hint': {'ru': r'Скалярное произведение диагоналей — разность квадратов сторон.',
           'en': r'The dot product of the diagonals is a difference of squared side lengths.'},
  'sol': {'ru': r'Пусть ромб задан вершинами $A$, $B$, $C$, $D$ и векторами $$\vec u=\overrightarrow{AB},\qquad \vec v=\overrightarrow{AD} ,$$ причём $|\vec u|=|\vec v|$ (все стороны равны).\n\n**Диагонали.** $$\overrightarrow{AC}=\vec u+\vec v,\qquad \overrightarrow{DB}=\vec u-\vec v .$$\n\n**Скалярное произведение.** $$\left(\vec u+\vec v\right)\cdot\left(\vec u-\vec v\right)=|\vec u|^{2}-|\vec v|^{2}=0 ,$$ поскольку длины равны.\n\nСкалярное произведение ненулевых векторов равно нулю ровно тогда, когда они перпендикулярны, значит $$AC\perp BD . \qquad\blacksquare$$\n\n**Обратное тоже верно:** если в параллелограмме диагонали перпендикулярны, то $|\vec u|=|\vec v|$, то есть это ромб.\n\n**Заодно:** для прямоугольника аналогичный подсчёт даёт равенство диагоналей.',
          'en': r'Let the rhombus have vertices $A$, $B$, $C$, $D$ and put $$\vec u=\overrightarrow{AB},\qquad \vec v=\overrightarrow{AD} ,$$ with $|\vec u|=|\vec v|$ (all sides equal).\n\n**The diagonals.** $$\overrightarrow{AC}=\vec u+\vec v,\qquad \overrightarrow{DB}=\vec u-\vec v .$$\n\n**Their dot product.** $$\left(\vec u+\vec v\right)\cdot\left(\vec u-\vec v\right)=|\vec u|^{2}-|\vec v|^{2}=0 ,$$ because the lengths agree.\n\nA dot product of non-zero vectors vanishes exactly when they are perpendicular, so $$AC\perp BD . \qquad\blacksquare$$\n\n**The converse holds too:** perpendicular diagonals in a parallelogram force $|\vec u|=|\vec v|$, i.e. a rhombus.\n\n**Also:** the analogous computation for a rectangle gives equal diagonals.'}},

 {'src': DISTRICT, 'lvl': 3,
  'q': {'ru': r'Напишите уравнение касательной к окружности $x^{2}+y^{2}=25$ в точке $(3,4)$.',
        'en': r'Write the equation of the tangent to the circle $x^{2}+y^{2}=25$ at the point $(3,4)$.'},
  'hint': {'ru': r'Касательная перпендикулярна радиусу.',
           'en': r'The tangent is perpendicular to the radius.'},
  'sol': {'ru': r'Радиус в точку касания — вектор $(3,4)$; касательная ему перпендикулярна.\n\n**Способ 1 (через нормаль).** Прямая с нормальным вектором $(3,4)$, проходящая через $(3,4)$: $$3(x-3)+4(y-4)=0\quad\Longrightarrow\quad 3x+4y=25 .$$\n\n**Способ 2 (через угловой коэффициент).** Радиус имеет наклон $\tfrac43$, значит касательная — наклон $-\tfrac34$: $$y-4=-\frac34(x-3)\quad\Longrightarrow\quad 3x+4y=25 \quad\checkmark$$\n\n**Проверка:** расстояние от центра $(0,0)$ до этой прямой равно $\dfrac{25}{5}=5=R$ ✓\n\n**Ответ:** $3x+4y=25$.\n\n**Общее правило:** касательная к $x^{2}+y^{2}=R^{2}$ в точке $\left(x_0,y_0\right)$ имеет уравнение $x_0x+y_0y=R^{2}$.',
          'en': r'The radius to the contact point is the vector $(3,4)$; the tangent is perpendicular to it.\n\n**Method 1 (normal vector).** The line with normal $(3,4)$ through $(3,4)$: $$3(x-3)+4(y-4)=0\quad\Longrightarrow\quad 3x+4y=25 .$$\n\n**Method 2 (slopes).** The radius has slope $\tfrac43$, so the tangent has slope $-\tfrac34$: $$y-4=-\frac34(x-3)\quad\Longrightarrow\quad 3x+4y=25 \quad\checkmark$$\n\n**Check:** the distance from $(0,0)$ to this line is $\dfrac{25}{5}=5=R$ ✓\n\n**Answer:** $3x+4y=25$.\n\n**General rule:** the tangent to $x^{2}+y^{2}=R^{2}$ at $\left(x_0,y_0\right)$ is $x_0x+y_0y=R^{2}$.'}},

 {'src': CLASSIC, 'lvl': 3,
  'q': {'ru': r'Докажите формулу площади треугольника по координатам вершин: $$S=\frac12\left|\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)\right| .$$',
        'en': r'Prove the coordinate area formula for a triangle: $$S=\frac12\left|\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)\right| .$$'},
  'hint': {'ru': r'Перенесите начало координат в первую вершину и посчитайте через основание и высоту.',
           'en': r'Move the origin to the first vertex and use base times height.'},
  'sol': {'ru': r'Перенесём начало координат в вершину $A$: положим $$\vec u=\left(x_2-x_1,\ y_2-y_1\right),\qquad \vec v=\left(x_3-x_1,\ y_3-y_1\right).$$ Задача сводится к площади треугольника, построенного на векторах $\vec u$ и $\vec v$.\n\n**Основание.** Возьмём за основание вектор $\vec u$; его длина $|\vec u|$, а прямая, на которой он лежит, имеет уравнение $$u_2\,x-u_1\,y=0 .$$\n\n**Высота.** Расстояние от конца вектора $\vec v$ до этой прямой равно $$h=\frac{\left|u_2v_1-u_1v_2\right|}{\sqrt{u_1^{2}+u_2^{2}}}=\frac{\left|u_1v_2-u_2v_1\right|}{|\vec u|} .$$\n\n**Площадь.** $$S=\frac12|\vec u|\,h=\frac12\left|u_1v_2-u_2v_1\right| ,$$ то есть в исходных обозначениях $$S=\frac12\left|\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)\right| . \qquad\blacksquare$$\n\n**Проверка** на треугольнике $(0,0)$, $(4,0)$, $(0,3)$: $$S=\frac12\left|4\cdot3-0\cdot0\right|=6 \quad\checkmark$$\n\n**Замечание.** Выражение под модулем — это ориентированная удвоенная площадь; его знак говорит, обходятся ли вершины против часовой стрелки (плюс) или по часовой (минус).',
          'en': r'Move the origin to $A$: set $$\vec u=\left(x_2-x_1,\ y_2-y_1\right),\qquad \vec v=\left(x_3-x_1,\ y_3-y_1\right),$$ reducing to the area of the triangle on the vectors $\vec u$ and $\vec v$.\n\n**Base.** Take $\vec u$ as base; its length is $|\vec u|$ and the line carrying it is $$u_2\,x-u_1\,y=0 .$$\n\n**Height.** The distance from the tip of $\vec v$ to that line is $$h=\frac{\left|u_1v_2-u_2v_1\right|}{|\vec u|} .$$\n\n**Area.** $$S=\frac12|\vec u|\,h=\frac12\left|u_1v_2-u_2v_1\right| ,$$ i.e. in the original notation $$S=\frac12\left|\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)\right| . \qquad\blacksquare$$\n\n**Check** on $(0,0)$, $(4,0)$, $(0,3)$: $$S=\frac12\left|4\cdot3-0\cdot0\right|=6 \quad\checkmark$$\n\n**Remark.** The expression inside the absolute value is twice the signed area; its sign says whether the vertices are listed counterclockwise (plus) or clockwise (minus).'}},

 {'src': DISTRICT, 'lvl': 3,
  'q': {'ru': r'Найдите множество точек, из которых отрезок с концами $(0,0)$ и $(4,0)$ виден под прямым углом.',
        'en': r'Find the set of points from which the segment with endpoints $(0,0)$ and $(4,0)$ subtends a right angle.'},
  'hint': {'ru': r'Скалярное произведение векторов к концам равно нулю.',
           'en': r'The dot product of the vectors to the endpoints is zero.'},
  'sol': {'ru': r'Пусть $M(x,y)$, $A(0,0)$, $B(4,0)$. Угол $AMB$ прямой тогда и только тогда, когда $$\overrightarrow{MA}\cdot\overrightarrow{MB}=0 .$$\n\n**Считаем.** $$\overrightarrow{MA}=(-x,-y),\qquad \overrightarrow{MB}=(4-x,-y) ,$$ значит $$-x(4-x)+y^{2}=0\quad\Longrightarrow\quad x^{2}-4x+y^{2}=0 .$$\n\n**Выделим квадрат.** $$(x-2)^{2}+y^{2}=4 .$$\n\nЭто окружность с центром $(2,0)$ и радиусом $2$ — то есть окружность, построенная на отрезке $AB$ как на диаметре.\n\n**Ответ:** окружность $(x-2)^{2}+y^{2}=4$ **без двух точек** $(0,0)$ и $(4,0)$ (в них угол не определён).\n\n**Это и есть теорема Фалеса** в координатной записи.',
          'en': r'Let $M(x,y)$, $A(0,0)$, $B(4,0)$. The angle $AMB$ is right exactly when $$\overrightarrow{MA}\cdot\overrightarrow{MB}=0 .$$\n\n**Compute.** $$\overrightarrow{MA}=(-x,-y),\qquad \overrightarrow{MB}=(4-x,-y) ,$$ so $$-x(4-x)+y^{2}=0\quad\Longrightarrow\quad x^{2}-4x+y^{2}=0 .$$\n\n**Complete the square.** $$(x-2)^{2}+y^{2}=4 .$$\n\nThis is the circle with centre $(2,0)$ and radius $2$ — the circle on $AB$ as diameter.\n\n**Answer:** the circle $(x-2)^{2}+y^{2}=4$ **minus the two points** $(0,0)$ and $(4,0)$, where the angle is undefined.\n\n**This is Thales’ theorem** written in coordinates.'}},

 # ------------------------------------------------------------------ level 4
 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите формулу «шнурков» для площади произвольного простого многоугольника с вершинами $\left(x_1,y_1\right),\dots,\left(x_n,y_n\right)$: $$S=\frac12\left|\sum_{i=1}^{n}\left(x_iy_{i+1}-x_{i+1}y_i\right)\right| ,$$ где $\left(x_{n+1},y_{n+1}\right)=\left(x_1,y_1\right)$.',
        'en': r'Prove the shoelace formula for the area of an arbitrary simple polygon with vertices $\left(x_1,y_1\right),\dots,\left(x_n,y_n\right)$: $$S=\frac12\left|\sum_{i=1}^{n}\left(x_iy_{i+1}-x_{i+1}y_i\right)\right| ,$$ where $\left(x_{n+1},y_{n+1}\right)=\left(x_1,y_1\right)$.'},
  'hint': {'ru': r'Индукция по числу вершин: отрежьте «ухо» — треугольник у одной вершины.',
           'en': r'Induct on the number of vertices: cut off an "ear" — a triangle at one vertex.'},
  'sol': {'ru': r'Обозначим через $$T(P)=\frac12\sum_{i=1}^{n}\left(x_iy_{i+1}-x_{i+1}y_i\right)$$ **ориентированную** площадь многоугольника $P$ (со знаком: плюс при обходе против часовой стрелки).\n\n**Шаг 1: база — треугольник.** Для $n=3$ сумма равна $$x_1y_2-x_2y_1+x_2y_3-x_3y_2+x_3y_1-x_1y_3 ,$$ и это в точности $$\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)$$ (проверяется раскрытием скобок), то есть удвоенная площадь треугольника со знаком ✓\n\n**Шаг 2: аддитивность.** Пусть многоугольник $P$ разрезан диагональю $\left(x_a,y_a\right)\!-\!\left(x_b,y_b\right)$ на два многоугольника $P_1$ и $P_2$. При сложении $T(P_1)+T(P_2)$ звенья вдоль разреза входят дважды — по разу в каждом направлении: $$\left(x_ay_b-x_by_a\right)+\left(x_by_a-x_ay_b\right)=0 .$$ Значит эти вклады взаимно уничтожаются, а остальные звенья складываются ровно в обход границы $P$: $$T(P_1)+T(P_2)=T(P) .$$\n\n**Шаг 3: индукция.** Всякий простой многоугольник с $n\ge4$ вершинами имеет «ухо» — вершину, диагональ у которой лежит целиком внутри (теорема о существовании уха). Отрезав его, получаем треугольник и многоугольник с $n-1$ вершиной; по предположению индукции для обоих формула верна, а по шагу 2 она верна и для $P$.\n\nВзяв модуль, получаем обычную (неориентированную) площадь. $\blacksquare$\n\n**Проверка** на единичном квадрате $(0,0),(1,0),(1,1),(0,1)$: $$\frac12\left|0+1+1+0-\left(0+0+0+0\right)\right| ,$$ а по звеньям: $0\cdot0-1\cdot0=0$, $1\cdot1-1\cdot0=1$, $1\cdot1-0\cdot1=1$, $0\cdot0-0\cdot1=0$; сумма $2$, площадь $1$ ✓\n\n**Практично:** формула работает и для невыпуклых многоугольников — важно лишь, чтобы граница не самопересекалась.',
          'en': r'Write $$T(P)=\frac12\sum_{i=1}^{n}\left(x_iy_{i+1}-x_{i+1}y_i\right)$$ for the **signed** area of the polygon $P$ (positive for a counterclockwise traversal).\n\n**Step 1: base case, a triangle.** For $n=3$ the sum is $$x_1y_2-x_2y_1+x_2y_3-x_3y_2+x_3y_1-x_1y_3 ,$$ which expands to exactly $$\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right),$$ twice the signed area of the triangle ✓\n\n**Step 2: additivity.** Suppose $P$ is cut by a diagonal $\left(x_a,y_a\right)\!-\!\left(x_b,y_b\right)$ into $P_1$ and $P_2$. In $T(P_1)+T(P_2)$ the edge along the cut appears twice, once in each direction: $$\left(x_ay_b-x_by_a\right)+\left(x_by_a-x_ay_b\right)=0 .$$ These contributions cancel, and the remaining edges assemble exactly into the boundary of $P$: $$T(P_1)+T(P_2)=T(P) .$$\n\n**Step 3: induction.** Every simple polygon with $n\ge4$ vertices has an "ear" — a vertex whose diagonal lies entirely inside (the two-ears theorem). Cutting it off leaves a triangle and a polygon with $n-1$ vertices; the formula holds for both by induction, hence for $P$ by Step 2.\n\nTaking absolute values gives the ordinary (unsigned) area. $\blacksquare$\n\n**Check** on the unit square $(0,0),(1,0),(1,1),(0,1)$: edge by edge $0$, $1$, $1$, $0$; the sum is $2$ and the area $1$ ✓\n\n**Practical note:** the formula works for non-convex polygons too — all that matters is that the boundary does not cross itself.'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Пусть $A$, $B$, $C$ — фиксированные точки. Докажите, что множество точек $P$ с $$PA^{2}+PB^{2}+PC^{2}=\text{const}$$ — окружность с центром в центроиде треугольника $ABC$ (или пустое множество, или одна точка).',
        'en': r'Let $A$, $B$, $C$ be fixed points. Prove that the set of points $P$ with $$PA^{2}+PB^{2}+PC^{2}=\text{const}$$ is a circle centred at the centroid of $ABC$ (or empty, or a single point).'},
  'hint': {'ru': r'Поместите начало координат в центроид.',
           'en': r'Put the origin at the centroid.'},
  'sol': {'ru': r'Поместим начало координат в центроид $G$. Тогда $$\vec A+\vec B+\vec C=\vec 0 .$$\n\n**Считаем сумму квадратов.** Для произвольной точки $P$ с радиус-вектором $\vec p$ $$PA^{2}=\left|\vec p-\vec A\right|^{2}=|\vec p|^{2}-2\,\vec p\cdot\vec A+\left|\vec A\right|^{2} ,$$ и аналогично для $B$ и $C$. Складывая три равенства, $$PA^{2}+PB^{2}+PC^{2}=3|\vec p|^{2}-2\,\vec p\cdot\underbrace{\left(\vec A+\vec B+\vec C\right)}_{=\vec 0}+\left(\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}\right).$$\n\nСредний член исчезает, и, обозначив $$Q=GA^{2}+GB^{2}+GC^{2}=\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2} ,$$ получаем **формулу Лейбница** $$PA^{2}+PB^{2}+PC^{2}=3\,PG^{2}+Q .$$\n\n**Вывод.** Условие $PA^{2}+PB^{2}+PC^{2}=k$ равносильно $$PG^{2}=\frac{k-Q}{3} .$$\n\nЕсли $k>Q$ — это окружность с центром $G$ и радиусом $\sqrt{\tfrac{k-Q}{3}}$; если $k=Q$ — единственная точка $G$; если $k<Q$ — решений нет. $\blacksquare$\n\n**Следствие.** Минимум суммы $PA^{2}+PB^{2}+PC^{2}$ достигается ровно в центроиде и равен $Q$.\n\n**Проверка** для треугольника $(0,0)$, $(3,0)$, $(0,3)$: центроид $(1,1)$, $$Q=2+ (4+1)+(1+4)=12 ,$$ и, скажем, в точке $(0,0)$ сумма равна $0+9+9=18=3\cdot2+12$ ✓ (ведь $PG^{2}=2$).',
          'en': r'Place the origin at the centroid $G$, so that $$\vec A+\vec B+\vec C=\vec 0 .$$\n\n**Compute the sum of squares.** For a point $P$ with position vector $\vec p$, $$PA^{2}=\left|\vec p-\vec A\right|^{2}=|\vec p|^{2}-2\,\vec p\cdot\vec A+\left|\vec A\right|^{2} ,$$ and likewise for $B$ and $C$. Adding the three, $$PA^{2}+PB^{2}+PC^{2}=3|\vec p|^{2}-2\,\vec p\cdot\underbrace{\left(\vec A+\vec B+\vec C\right)}_{=\vec 0}+\left(\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}\right).$$\n\nThe middle term vanishes, and writing $$Q=GA^{2}+GB^{2}+GC^{2} ,$$ we obtain **Leibniz’s formula** $$PA^{2}+PB^{2}+PC^{2}=3\,PG^{2}+Q .$$\n\n**Conclusion.** The condition $PA^{2}+PB^{2}+PC^{2}=k$ is equivalent to $$PG^{2}=\frac{k-Q}{3} .$$\n\nIf $k>Q$ this is a circle centred at $G$ of radius $\sqrt{\tfrac{k-Q}{3}}$; if $k=Q$ it is the single point $G$; if $k<Q$ it is empty. $\blacksquare$\n\n**Corollary.** The minimum of $PA^{2}+PB^{2}+PC^{2}$ is attained exactly at the centroid and equals $Q$.\n\n**Check** for $(0,0)$, $(3,0)$, $(0,3)$: the centroid is $(1,1)$, $Q=12$, and at $P=(0,0)$ the sum is $0+9+9=18=3\cdot2+12$ ✓ (since $PG^{2}=2$).'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите, что окружность, проходящая через три неколлинеарные точки, задаётся уравнением $$\begin{vmatrix}x^{2}+y^{2}&x&y&1\\ x_1^{2}+y_1^{2}&x_1&y_1&1\\ x_2^{2}+y_2^{2}&x_2&y_2&1\\ x_3^{2}+y_3^{2}&x_3&y_3&1\end{vmatrix}=0 .$$',
        'en': r'Prove that the circle through three non-collinear points is given by $$\begin{vmatrix}x^{2}+y^{2}&x&y&1\\ x_1^{2}+y_1^{2}&x_1&y_1&1\\ x_2^{2}+y_2^{2}&x_2&y_2&1\\ x_3^{2}+y_3^{2}&x_3&y_3&1\end{vmatrix}=0 .$$'},
  'hint': {'ru': r'Разложите определитель по первой строке.',
           'en': r'Expand the determinant along the first row.'},
  'sol': {'ru': r'**Шаг 1: что за уравнение получается.** Разложим определитель по первой строке: $$A\left(x^{2}+y^{2}\right)-Bx+Cy-D=0 ,$$ где $A$, $B$, $C$, $D$ — миноры, зависящие только от трёх данных точек. Это уравнение вида $$A\left(x^{2}+y^{2}\right)+\alpha x+\beta y+\gamma=0 ,$$ то есть уравнение окружности при $A\ne0$ (и прямой при $A=0$).\n\n**Шаг 2: $A\ne0$.** Минор $A$ равен $$\begin{vmatrix}x_1&y_1&1\\ x_2&y_2&1\\ x_3&y_3&1\end{vmatrix} ,$$ а это удвоенная ориентированная площадь треугольника на трёх точках. Точки не лежат на одной прямой, значит площадь ненулевая, и $A\ne0$ ✓\n\n**Шаг 3: три точки удовлетворяют уравнению.** Подставив $\left(x,y\right)=\left(x_1,y_1\right)$, получим определитель с двумя одинаковыми строками — он равен нулю ✓ То же для двух других точек.\n\n**Шаг 4: единственность.** Окружность через три неколлинеарные точки единственна (её центр — точка пересечения серединных перпендикуляров), значит найденное уравнение задаёт именно её. $\blacksquare$\n\n**Пример.** Для точек $(0,0)$, $(4,0)$, $(0,3)$ раскрытие даёт $$x^{2}+y^{2}-4x-3y=0 ,$$ то есть окружность с центром $\left(2;\ 1{,}5\right)$ и радиусом $2{,}5$ — как и должно быть у прямоугольного треугольника с гипотенузой $5$ ✓\n\n**Замечание.** При $A=0$ определитель задаёт прямую через три коллинеарные точки — «окружность бесконечного радиуса».',
          'en': r'**Step 1: what equation this is.** Expand along the first row: $$A\left(x^{2}+y^{2}\right)+\alpha x+\beta y+\gamma=0 ,$$ where $A,\alpha,\beta,\gamma$ are minors depending only on the three given points. For $A\ne0$ this is the equation of a circle (and of a line when $A=0$).\n\n**Step 2: $A\ne0$.** The minor $A$ equals $$\begin{vmatrix}x_1&y_1&1\\ x_2&y_2&1\\ x_3&y_3&1\end{vmatrix} ,$$ twice the signed area of the triangle on the three points. They are not collinear, so the area is non-zero and $A\ne0$ ✓\n\n**Step 3: the three points satisfy it.** Substituting $\left(x,y\right)=\left(x_1,y_1\right)$ produces a determinant with two equal rows, hence zero ✓ Likewise for the other two.\n\n**Step 4: uniqueness.** The circle through three non-collinear points is unique (its centre is the meeting point of the perpendicular bisectors), so this equation describes exactly that circle. $\blacksquare$\n\n**Example.** For $(0,0)$, $(4,0)$, $(0,3)$ the expansion gives $$x^{2}+y^{2}-4x-3y=0 ,$$ the circle with centre $(2,\ 1.5)$ and radius $2.5$ — as it must be for a right triangle with hypotenuse $5$ ✓\n\n**Remark.** When $A=0$ the determinant describes the line through three collinear points — a "circle of infinite radius".'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите координатами, что для медиан треугольника $$m_a^{2}+m_b^{2}+m_c^{2}=\frac34\left(a^{2}+b^{2}+c^{2}\right).$$',
        'en': r'Prove by coordinates that the medians of a triangle satisfy $$m_a^{2}+m_b^{2}+m_c^{2}=\frac34\left(a^{2}+b^{2}+c^{2}\right).$$'},
  'hint': {'ru': r'Поместите начало координат в центроид и воспользуйтесь тем, что $AG=\tfrac23m_a$.',
           'en': r'Put the origin at the centroid and use $AG=\tfrac23m_a$.'},
  'sol': {'ru': r'Поместим начало координат в центроид $G$, так что $$\vec A+\vec B+\vec C=\vec0 .$$\n\n**Медианы через расстояния до центроида.** Центроид делит медиану в отношении $2:1$, поэтому $$\left|\vec A\right|=GA=\frac23m_a ,$$ и аналогично для $B$, $C$. Значит $$m_a^{2}+m_b^{2}+m_c^{2}=\frac94\left(\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}\right).$$\n\n**Стороны через те же векторы.** $$a^{2}=\left|\vec B-\vec C\right|^{2}=\left|\vec B\right|^{2}+\left|\vec C\right|^{2}-2\,\vec B\cdot\vec C ,$$ и аналогично для $b^{2}$, $c^{2}$. Складывая, $$a^{2}+b^{2}+c^{2}=2\left(\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}\right)-2\left(\vec A\cdot\vec B+\vec B\cdot\vec C+\vec C\cdot\vec A\right).$$\n\n**Убираем скалярные произведения.** Возведём равенство $\vec A+\vec B+\vec C=\vec0$ в квадрат: $$\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}+2\left(\vec A\cdot\vec B+\vec B\cdot\vec C+\vec C\cdot\vec A\right)=0 ,$$ откуда $$2\left(\vec A\cdot\vec B+\vec B\cdot\vec C+\vec C\cdot\vec A\right)=-\left(\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}\right).$$\n\nПодставим: обозначив $Q=\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}$, получаем $$a^{2}+b^{2}+c^{2}=2Q+Q=3Q .$$\n\n**Собираем.** $$m_a^{2}+m_b^{2}+m_c^{2}=\frac94Q=\frac94\cdot\frac{a^{2}+b^{2}+c^{2}}{3}=\frac34\left(a^{2}+b^{2}+c^{2}\right). \qquad\blacksquare$$\n\n**Проверка** на равностороннем треугольнике со стороной $1$: медиана равна $\tfrac{\sqrt3}{2}$, слева $3\cdot\tfrac34=\tfrac94$, справа $\tfrac34\cdot3=\tfrac94$ ✓',
          'en': r'Put the origin at the centroid $G$, so that $$\vec A+\vec B+\vec C=\vec0 .$$\n\n**Medians via distances to the centroid.** The centroid divides a median $2:1$, so $$\left|\vec A\right|=GA=\frac23m_a ,$$ and likewise for $B$, $C$. Hence $$m_a^{2}+m_b^{2}+m_c^{2}=\frac94\left(\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2}\right).$$\n\n**Sides via the same vectors.** $$a^{2}=\left|\vec B-\vec C\right|^{2}=\left|\vec B\right|^{2}+\left|\vec C\right|^{2}-2\,\vec B\cdot\vec C ,$$ and similarly for $b^{2}$, $c^{2}$. Adding, $$a^{2}+b^{2}+c^{2}=2Q-2\left(\vec A\cdot\vec B+\vec B\cdot\vec C+\vec C\cdot\vec A\right),\qquad Q=\left|\vec A\right|^{2}+\left|\vec B\right|^{2}+\left|\vec C\right|^{2} .$$\n\n**Remove the dot products.** Squaring $\vec A+\vec B+\vec C=\vec0$: $$Q+2\left(\vec A\cdot\vec B+\vec B\cdot\vec C+\vec C\cdot\vec A\right)=0 ,$$ so $2\left(\vec A\cdot\vec B+\vec B\cdot\vec C+\vec C\cdot\vec A\right)=-Q$ and $$a^{2}+b^{2}+c^{2}=2Q+Q=3Q .$$\n\n**Combine.** $$m_a^{2}+m_b^{2}+m_c^{2}=\frac94Q=\frac94\cdot\frac{a^{2}+b^{2}+c^{2}}{3}=\frac34\left(a^{2}+b^{2}+c^{2}\right). \qquad\blacksquare$$\n\n**Check** on the equilateral triangle of side $1$: each median is $\tfrac{\sqrt3}{2}$, the left side is $\tfrac94$ and the right $\tfrac34\cdot3=\tfrac94$ ✓'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите, что уравнение $$Ax^{2}+Bxy+Cy^{2}+Dx+Ey+F=0$$ задаёт окружность тогда и только тогда, когда $B=0$, $A=C\ne0$ и $D^{2}+E^{2}-4AF>0$; найдите центр и радиус.',
        'en': r'Prove that $$Ax^{2}+Bxy+Cy^{2}+Dx+Ey+F=0$$ describes a circle if and only if $B=0$, $A=C\ne0$ and $D^{2}+E^{2}-4AF>0$; find the centre and radius.'},
  'hint': {'ru': r'Уравнение окружности после раскрытия скобок имеет строго определённый вид.',
           'en': r'Expanding a circle equation produces a very specific shape.'},
  'sol': {'ru': r'**Необходимость.** Окружность с центром $\left(x_0,y_0\right)$ и радиусом $R>0$ задаётся уравнением $$\left(x-x_0\right)^{2}+\left(y-y_0\right)^{2}=R^{2} .$$ Раскрыв скобки и домножив на произвольное $A\ne0$, получаем $$Ax^{2}+Ay^{2}-2Ax_0x-2Ay_0y+A\left(x_0^{2}+y_0^{2}-R^{2}\right)=0 .$$ Здесь коэффициент при $xy$ равен нулю, а коэффициенты при $x^{2}$ и $y^{2}$ совпадают ✓\n\n**Достаточность и формулы.** Пусть $B=0$ и $A=C\ne0$. Поделим на $A$: $$x^{2}+y^{2}+\frac DA x+\frac EA y+\frac FA=0 .$$\n\nВыделим полные квадраты: $$\left(x+\frac{D}{2A}\right)^{2}+\left(y+\frac{E}{2A}\right)^{2}=\frac{D^{2}}{4A^{2}}+\frac{E^{2}}{4A^{2}}-\frac FA=\frac{D^{2}+E^{2}-4AF}{4A^{2}} .$$\n\nПравая часть должна быть положительной — это и есть условие $D^{2}+E^{2}-4AF>0$. Тогда $$\text{центр}\ \left(-\frac{D}{2A},\ -\frac{E}{2A}\right),\qquad R=\frac{\sqrt{D^{2}+E^{2}-4AF}}{2|A|} . \qquad\blacksquare$$\n\n**Вырожденные случаи.** Если $D^{2}+E^{2}-4AF=0$, уравнению удовлетворяет ровно одна точка (окружность нулевого радиуса); если выражение отрицательно — ни одной.\n\n**Пример.** $x^{2}+y^{2}-6x+8y-11=0$: центр $(3,-4)$, $$R=\frac{\sqrt{36+64+44}}{2}=\frac{\sqrt{144}}{2}=6 \quad\checkmark$$',
          'en': r'**Necessity.** The circle with centre $\left(x_0,y_0\right)$ and radius $R>0$ satisfies $$\left(x-x_0\right)^{2}+\left(y-y_0\right)^{2}=R^{2} .$$ Expanding and multiplying by any $A\ne0$, $$Ax^{2}+Ay^{2}-2Ax_0x-2Ay_0y+A\left(x_0^{2}+y_0^{2}-R^{2}\right)=0 ,$$ where the $xy$ coefficient is zero and the $x^{2}$, $y^{2}$ coefficients agree ✓\n\n**Sufficiency and the formulas.** Suppose $B=0$ and $A=C\ne0$. Divide by $A$: $$x^{2}+y^{2}+\frac DA x+\frac EA y+\frac FA=0 .$$\n\nComplete the squares: $$\left(x+\frac{D}{2A}\right)^{2}+\left(y+\frac{E}{2A}\right)^{2}=\frac{D^{2}+E^{2}-4AF}{4A^{2}} .$$\n\nThe right side must be positive — exactly the condition $D^{2}+E^{2}-4AF>0$. Then $$\text{centre}\ \left(-\frac{D}{2A},\ -\frac{E}{2A}\right),\qquad R=\frac{\sqrt{D^{2}+E^{2}-4AF}}{2|A|} . \qquad\blacksquare$$\n\n**Degenerate cases.** If $D^{2}+E^{2}-4AF=0$ exactly one point satisfies the equation (a circle of zero radius); if the expression is negative, none does.\n\n**Example.** $x^{2}+y^{2}-6x+8y-11=0$: centre $(3,-4)$ and $$R=\frac{\sqrt{36+64+44}}{2}=6 \quad\checkmark$$'}},
]
