# -*- coding: utf-8 -*-
"""Topic 3 — extra problems, appended to lesson_03.py by content/build.py.

Source labels: where the competition is known for certain it is named; the
round labels ("Районный тур · уровень") describe the level a problem is
typical of, not a claim about where it was set.
"""

SCHOOL   = 'Школьный тур · уровень / School-round level'
DISTRICT = 'Районный тур · уровень / District-round level'
REGION   = 'Областной тур · уровень / Regional-round level'
REPUBLIC = 'Республиканский тур · уровень / Republic-round level'
INTL     = 'Международный уровень / International level'
CLASSIC  = 'Классическая задача / Classic'

EXTRA = [

 # ------------------------------------------------------------------ level 1
 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите остаток от деления $2^{100}$ на $3$.',
        'en': r'Find the remainder of $2^{100}$ on division by $3$.'},
  'hint': {'ru': r'$2\equiv-1\pmod 3$.',
           'en': r'$2\equiv-1\pmod 3$.'},
  'sol': {'ru': r'Заменим основание на удобное: $$2\equiv-1\pmod 3 .$$\n\nТогда $$2^{100}\equiv(-1)^{100}=1\pmod 3 ,$$ ведь показатель чётный.\n\n**Проверка** на маленьком показателе: $2^{2}=4=3+1$ ✓\n\n**Ответ:** $1$.',
          'en': r'Replace the base by a convenient one: $$2\equiv-1\pmod 3 .$$\n\nThen $$2^{100}\equiv(-1)^{100}=1\pmod 3 ,$$ since the exponent is even.\n\n**Check** on a small exponent: $2^{2}=4=3+1$ ✓\n\n**Answer:** $1$.'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите остаток от деления числа $1234567$ на $9$.',
        'en': r'Find the remainder of $1234567$ on division by $9$.'},
  'hint': {'ru': r'Число сравнимо со своей суммой цифр по модулю $9$.',
           'en': r'A number is congruent to its digit sum modulo $9$.'},
  'sol': {'ru': r'Так как $10\equiv1\pmod 9$, любая степень десятки тоже сравнима с единицей, поэтому число сравнимо с суммой своих цифр: $$1234567\equiv1+2+3+4+5+6+7=28\pmod 9 .$$\n\nПовторим приём: $$28\equiv2+8=10\equiv1+0=1\pmod 9 .$$\n\n**Проверка:** $1234567=9\cdot137174+1$ ✓\n\n**Ответ:** $1$.',
          'en': r'Since $10\equiv1\pmod 9$, every power of ten is congruent to one as well, so a number is congruent to its digit sum: $$1234567\equiv1+2+3+4+5+6+7=28\pmod 9 .$$\n\nRepeat the trick: $$28\equiv2+8=10\equiv1+0=1\pmod 9 .$$\n\n**Check:** $1234567=9\cdot137174+1$ ✓\n\n**Answer:** $1$.'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Какой последней цифрой оканчивается число $3^{100}$?',
        'en': r'What is the last digit of $3^{100}$?'},
  'hint': {'ru': r'Последние цифры степеней тройки повторяются с периодом $4$.',
           'en': r'The last digits of the powers of three repeat with period $4$.'},
  'sol': {'ru': r'Выпишем последние цифры: $$3^{1}\to3,\quad 3^{2}\to9,\quad 3^{3}\to7,\quad 3^{4}\to1,\quad 3^{5}\to3,\ \dots$$ — период равен $4$, потому что $3^{4}=81\equiv1\pmod{10}$.\n\nЗначит $$3^{100}=\left(3^{4}\right)^{25}\equiv1^{25}=1\pmod{10} .$$\n\n**Ответ:** $1$.',
          'en': r'List the last digits: $$3^{1}\to3,\quad 3^{2}\to9,\quad 3^{3}\to7,\quad 3^{4}\to1,\quad 3^{5}\to3,\ \dots$$ — the period is $4$, because $3^{4}=81\equiv1\pmod{10}$.\n\nHence $$3^{100}=\left(3^{4}\right)^{25}\equiv1^{25}=1\pmod{10} .$$\n\n**Answer:** $1$.'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите остаток от деления $3^{2024}$ на $8$.',
        'en': r'Find the remainder of $3^{2024}$ on division by $8$.'},
  'hint': {'ru': r'$3^{2}=9\equiv1\pmod 8$.',
           'en': r'$3^{2}=9\equiv1\pmod 8$.'},
  'sol': {'ru': r'Заметим, что $$3^{2}=9=8+1\equiv1\pmod 8 .$$\n\nПоказатель $2024$ чётный, поэтому $$3^{2024}=\left(3^{2}\right)^{1012}\equiv1^{1012}=1\pmod 8 .$$\n\n**Проверка:** $3^{4}=81=8\cdot10+1$ ✓\n\n**Ответ:** $1$.',
          'en': r'Note that $$3^{2}=9=8+1\equiv1\pmod 8 .$$\n\nThe exponent $2024$ is even, so $$3^{2024}=\left(3^{2}\right)^{1012}\equiv1^{1012}=1\pmod 8 .$$\n\n**Check:** $3^{4}=81=8\cdot10+1$ ✓\n\n**Answer:** $1$.'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Докажите, что $10^{n}\equiv1\pmod 9$ при любом $n\ge0$, и выведите отсюда признак делимости на $9$.',
        'en': r'Prove that $10^{n}\equiv1\pmod 9$ for every $n\ge0$, and deduce the digit-sum test for divisibility by $9$.'},
  'hint': {'ru': r'$10=9+1$.',
           'en': r'$10=9+1$.'},
  'sol': {'ru': r'Так как $10=9+1\equiv1\pmod 9$, возведение в степень даёт $$10^{n}\equiv1^{n}=1\pmod 9 .$$\n\nТеперь пусть число записано цифрами $a_k\ldots a_1a_0$, то есть $$N=a_k10^{k}+\dots+a_110+a_0 .$$ Заменяя каждую степень десятки на единицу, получаем $$N\equiv a_k+\dots+a_1+a_0\pmod 9 .$$\n\nЗначит $N$ и сумма его цифр дают **одинаковые остатки** при делении на $9$; в частности $$9\mid N\quad\Longleftrightarrow\quad 9\mid a_k+\dots+a_0 . \qquad\blacksquare$$\n\n**Пример.** $N=8127$: сумма цифр $18$ делится на $9$, значит и $8127=9\cdot903$ делится ✓',
          'en': r'Since $10=9+1\equiv1\pmod 9$, raising to a power gives $$10^{n}\equiv1^{n}=1\pmod 9 .$$\n\nNow let a number have digits $a_k\ldots a_1a_0$, i.e. $$N=a_k10^{k}+\dots+a_110+a_0 .$$ Replacing every power of ten by one, $$N\equiv a_k+\dots+a_1+a_0\pmod 9 .$$\n\nSo $N$ and its digit sum leave the **same remainder** on division by $9$; in particular $$9\mid N\quad\Longleftrightarrow\quad 9\mid a_k+\dots+a_0 . \qquad\blacksquare$$\n\n**Example.** $N=8127$: the digit sum $18$ is a multiple of $9$, and indeed $8127=9\cdot903$ ✓'}},

 {'src': SCHOOL, 'lvl': 1,
  'q': {'ru': r'Найдите остаток от деления $100!$ на $7$.',
        'en': r'Find the remainder of $100!$ on division by $7$.'},
  'hint': {'ru': r'Посмотрите, входит ли семёрка в произведение.',
           'en': r'Ask whether $7$ appears among the factors.'},
  'sol': {'ru': r'По определению $$100!=1\cdot2\cdot3\cdots7\cdots100 ,$$ и множитель $7$ здесь присутствует.\n\nЗначит $7\mid100!$, то есть остаток равен нулю.\n\n**Замечание.** Точно так же $n!$ делится на любое простое $p\le n$; более того, показатель семёрки в $100!$ равен $$\left\lfloor\frac{100}{7}\right\rfloor+\left\lfloor\frac{100}{49}\right\rfloor=14+2=16 .$$\n\n**Ответ:** $0$.',
          'en': r'By definition $$100!=1\cdot2\cdot3\cdots7\cdots100 ,$$ and the factor $7$ is present.\n\nSo $7\mid100!$, i.e. the remainder is zero.\n\n**Remark.** In the same way $n!$ is divisible by every prime $p\le n$; in fact the exponent of $7$ in $100!$ is $$\left\lfloor\frac{100}{7}\right\rfloor+\left\lfloor\frac{100}{49}\right\rfloor=14+2=16 .$$\n\n**Answer:** $0$.'}},

 # ------------------------------------------------------------------ level 2
 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Докажите, что $9\mid4^{n}+15n-1$ при любом целом $n\ge0$.',
        'en': r'Prove that $9\mid4^{n}+15n-1$ for every integer $n\ge0$.'},
  'hint': {'ru': r'Индукция: посмотрите на разность соседних значений.',
           'en': r'Induct: look at the difference of consecutive values.'},
  'sol': {'ru': r'Обозначим $A_n=4^{n}+15n-1$.\n\n**База.** $A_0=1+0-1=0$ делится на $9$ ✓\n\n**Переход.** Вычтем: $$A_{n+1}-A_n=4^{n+1}-4^{n}+15=3\cdot4^{n}+15=3\left(4^{n}+5\right).$$\n\nОсталось проверить, что $3\mid4^{n}+5$. Действительно, $4\equiv1\pmod 3$, поэтому $$4^{n}+5\equiv1+5=6\equiv0\pmod 3 .$$\n\nЗначит $A_{n+1}-A_n$ делится на $3\cdot3=9$. Если $9\mid A_n$, то и $9\mid A_{n+1}$.\n\nПо индукции $9\mid A_n$ при всех $n\ge0$. $\blacksquare$\n\n**Проверка:** $A_1=4+15-1=18=9\cdot2$ ✓ $A_2=16+30-1=45=9\cdot5$ ✓',
          'en': r'Write $A_n=4^{n}+15n-1$.\n\n**Base.** $A_0=1+0-1=0$ is divisible by $9$ ✓\n\n**Step.** Subtract: $$A_{n+1}-A_n=4^{n+1}-4^{n}+15=3\cdot4^{n}+15=3\left(4^{n}+5\right).$$\n\nIt remains to check $3\mid4^{n}+5$. Indeed $4\equiv1\pmod 3$, so $$4^{n}+5\equiv1+5=6\equiv0\pmod 3 .$$\n\nHence $A_{n+1}-A_n$ is divisible by $3\cdot3=9$. So $9\mid A_n$ implies $9\mid A_{n+1}$.\n\nBy induction $9\mid A_n$ for all $n\ge0$. $\blacksquare$\n\n**Check:** $A_1=4+15-1=18=9\cdot2$ ✓ $A_2=16+30-1=45=9\cdot5$ ✓'}},

 {'src': REGION, 'lvl': 2,
  'q': {'ru': r'Найдите две последние цифры числа $3^{100}$.',
        'en': r'Find the last two digits of $3^{100}$.'},
  'hint': {'ru': r'Посчитайте $3^{10}$, затем $3^{20}$ по модулю $100$.',
           'en': r'Compute $3^{10}$, then $3^{20}$, modulo $100$.'},
  'sol': {'ru': r'Две последние цифры — это остаток по модулю $100$. Будем возводить в квадрат.\n\n$$3^{5}=243\equiv43\pmod{100};$$\n\n$$3^{10}\equiv43^{2}=1849\equiv49\pmod{100};$$\n\n$$3^{20}\equiv49^{2}=2401\equiv1\pmod{100} .$$\n\nПолучили $3^{20}\equiv1$, поэтому $$3^{100}=\left(3^{20}\right)^{5}\equiv1^{5}=1\pmod{100} .$$\n\n**Ответ:** $01$, то есть число оканчивается на $\ldots01$.',
          'en': r'The last two digits are the remainder modulo $100$. Square step by step.\n\n$$3^{5}=243\equiv43\pmod{100};$$\n\n$$3^{10}\equiv43^{2}=1849\equiv49\pmod{100};$$\n\n$$3^{20}\equiv49^{2}=2401\equiv1\pmod{100} .$$\n\nSince $3^{20}\equiv1$, $$3^{100}=\left(3^{20}\right)^{5}\equiv1^{5}=1\pmod{100} .$$\n\n**Answer:** $01$ — the number ends in $\ldots01$.'}},

 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Докажите, что $11\mid10^{n}-(-1)^{n}$, и выведите признак делимости на $11$ по знакопеременной сумме цифр.',
        'en': r'Prove that $11\mid10^{n}-(-1)^{n}$, and deduce the alternating-digit-sum test for divisibility by $11$.'},
  'hint': {'ru': r'$10\equiv-1\pmod{11}$.',
           'en': r'$10\equiv-1\pmod{11}$.'},
  'sol': {'ru': r'Так как $10=11-1\equiv-1\pmod{11}$, возведение в степень даёт $$10^{n}\equiv(-1)^{n}\pmod{11},$$ то есть $11\mid10^{n}-(-1)^{n}$ ✓\n\nТеперь пусть $$N=a_k10^{k}+\dots+a_110+a_0 .$$ Заменяя $10^{j}$ на $(-1)^{j}$, получаем $$N\equiv a_0-a_1+a_2-a_3+\dots\pmod{11} .$$\n\nЗначит $N$ делится на $11$ тогда и только тогда, когда знакопеременная сумма цифр делится на $11$. $\blacksquare$\n\n**Пример.** $N=918082$: $$2-8+0-8+1-9=-22 ,$$ и $11\mid-22$, значит $11\mid918082$ ✓ (действительно $918082=11\cdot83462$).',
          'en': r'Since $10=11-1\equiv-1\pmod{11}$, raising to a power gives $$10^{n}\equiv(-1)^{n}\pmod{11},$$ i.e. $11\mid10^{n}-(-1)^{n}$ ✓\n\nNow let $$N=a_k10^{k}+\dots+a_110+a_0 .$$ Replacing $10^{j}$ by $(-1)^{j}$, $$N\equiv a_0-a_1+a_2-a_3+\dots\pmod{11} .$$\n\nSo $N$ is divisible by $11$ exactly when the alternating digit sum is. $\blacksquare$\n\n**Example.** $N=918082$: $$2-8+0-8+1-9=-22 ,$$ and $11\mid-22$, so $11\mid918082$ ✓ (indeed $918082=11\cdot83462$).'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Найдите все натуральные $n$, для которых $3\mid2^{n}+1$.',
        'en': r'Find all positive integers $n$ for which $3\mid2^{n}+1$.'},
  'hint': {'ru': r'$2\equiv-1\pmod 3$.',
           'en': r'$2\equiv-1\pmod 3$.'},
  'sol': {'ru': r'Так как $2\equiv-1\pmod 3$, имеем $$2^{n}+1\equiv(-1)^{n}+1\pmod 3 .$$\n\n**Если $n$ чётно:** $(-1)^{n}+1=2\not\equiv0$ ✗\n\n**Если $n$ нечётно:** $(-1)^{n}+1=0$ ✓\n\n**Проверка:** $2^{1}+1=3$ ✓, $2^{2}+1=5$ ✗, $2^{3}+1=9$ ✓\n\n**Ответ:** ровно нечётные $n$.',
          'en': r'Since $2\equiv-1\pmod 3$, $$2^{n}+1\equiv(-1)^{n}+1\pmod 3 .$$\n\n**If $n$ is even:** $(-1)^{n}+1=2\not\equiv0$ ✗\n\n**If $n$ is odd:** $(-1)^{n}+1=0$ ✓\n\n**Check:** $2^{1}+1=3$ ✓, $2^{2}+1=5$ ✗, $2^{3}+1=9$ ✓\n\n**Answer:** exactly the odd $n$.'}},

 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Докажите, что квадрат целого числа даёт по модулю $4$ остаток $0$ или $1$, и выведите отсюда, что $2023$ не представимо в виде суммы двух квадратов.',
        'en': r'Prove that a perfect square leaves remainder $0$ or $1$ modulo $4$, and deduce that $2023$ is not a sum of two squares.'},
  'hint': {'ru': r'Разберите чётное и нечётное основание.',
           'en': r'Treat an even and an odd base separately.'},
  'sol': {'ru': r'**Шаг 1.** Если $n=2k$, то $n^{2}=4k^{2}\equiv0\pmod 4$. Если $n=2k+1$, то $$n^{2}=4k^{2}+4k+1=4k(k+1)+1\equiv1\pmod 4 .$$ Значит квадрат сравним с $0$ или с $1$ ✓\n\n**Шаг 2.** Сумма двух квадратов может быть сравнима только с $$0+0=0,\qquad 0+1=1,\qquad 1+1=2 \pmod 4,$$ то есть **никогда не даёт остаток $3$**.\n\n**Шаг 3.** Но $$2023=4\cdot505+3\equiv3\pmod 4 .$$\n\nЗначит $2023$ не является суммой двух квадратов. $\blacksquare$',
          'en': r'**Step 1.** If $n=2k$ then $n^{2}=4k^{2}\equiv0\pmod 4$. If $n=2k+1$ then $$n^{2}=4k^{2}+4k+1=4k(k+1)+1\equiv1\pmod 4 .$$ So a square is congruent to $0$ or $1$ ✓\n\n**Step 2.** A sum of two squares can therefore only be congruent to $$0+0=0,\qquad 0+1=1,\qquad 1+1=2 \pmod 4,$$ i.e. it **never leaves remainder $3$**.\n\n**Step 3.** But $$2023=4\cdot505+3\equiv3\pmod 4 .$$\n\nHence $2023$ is not a sum of two squares. $\blacksquare$'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Найдите остаток от деления $2^{1000}$ на $7$.',
        'en': r'Find the remainder of $2^{1000}$ on division by $7$.'},
  'hint': {'ru': r'$2^{3}=8\equiv1\pmod 7$.',
           'en': r'$2^{3}=8\equiv1\pmod 7$.'},
  'sol': {'ru': r'Ключ: $$2^{3}=8=7+1\equiv1\pmod 7 .$$\n\nПоделим показатель на $3$ с остатком: $$1000=3\cdot333+1 .$$\n\nТогда $$2^{1000}=\left(2^{3}\right)^{333}\cdot2^{1}\equiv1^{333}\cdot2=2\pmod 7 .$$\n\n**Проверка** на маленьком показателе того же вида: $2^{4}=16=7\cdot2+2$ ✓\n\n**Ответ:** $2$.',
          'en': r'The key: $$2^{3}=8=7+1\equiv1\pmod 7 .$$\n\nDivide the exponent by $3$ with remainder: $$1000=3\cdot333+1 .$$\n\nThen $$2^{1000}=\left(2^{3}\right)^{333}\cdot2^{1}\equiv1^{333}\cdot2=2\pmod 7 .$$\n\n**Check** on a small exponent of the same shape: $2^{4}=16=7\cdot2+2$ ✓\n\n**Answer:** $2$.'}},

 {'src': REGION, 'lvl': 2,
  'q': {'ru': r'Найдите все целые $n$, для которых $9\mid n^{2}+n+1$.',
        'en': r'Find all integers $n$ for which $9\mid n^{2}+n+1$.'},
  'hint': {'ru': r'Достаточно перебрать девять остатков.',
           'en': r'Nine residues are enough to check.'},
  'sol': {'ru': r'Остаток $n^{2}+n+1$ по модулю $9$ зависит только от остатка $n$; переберём все девять.\n\n$n\equiv0$: $1$; $\ n\equiv1$: $3$; $\ n\equiv2$: $7$;\n\n$n\equiv3$: $13\equiv4$; $\ n\equiv4$: $21\equiv3$; $\ n\equiv5$: $31\equiv4$;\n\n$n\equiv6$: $43\equiv7$; $\ n\equiv7$: $57\equiv3$; $\ n\equiv8$: $73\equiv1$.\n\nПолучились остатки $$1,\;3,\;7,\;4,\;3,\;4,\;7,\;3,\;1 ,$$ и нуля среди них нет.\n\n**Ответ:** таких $n$ не существует.\n\n**Замечание.** Заметьте: остаток $3$ встречается, то есть на $3$ число делиться может (например, при $n=1$ получаем $3$), а вот на $9$ — никогда.',
          'en': r'The residue of $n^{2}+n+1$ modulo $9$ depends only on that of $n$, so check all nine.\n\n$n\equiv0$: $1$; $\ n\equiv1$: $3$; $\ n\equiv2$: $7$;\n\n$n\equiv3$: $13\equiv4$; $\ n\equiv4$: $21\equiv3$; $\ n\equiv5$: $31\equiv4$;\n\n$n\equiv6$: $43\equiv7$; $\ n\equiv7$: $57\equiv3$; $\ n\equiv8$: $73\equiv1$.\n\nThe residues are $$1,\;3,\;7,\;4,\;3,\;4,\;7,\;3,\;1 ,$$ and $0$ never occurs.\n\n**Answer:** there is no such $n$.\n\n**Remark.** Note the residue $3$ does occur, so the number can be divisible by $3$ (at $n=1$ it equals $3$) — but never by $9$.'}},

 {'src': DISTRICT, 'lvl': 2,
  'q': {'ru': r'Докажите, что $n^{2}+1$ ни при каком целом $n$ не делится на $7$.',
        'en': r'Prove that $n^{2}+1$ is never divisible by $7$, for any integer $n$.'},
  'hint': {'ru': r'Выпишите все квадратичные вычеты по модулю $7$.',
           'en': r'List all quadratic residues modulo $7$.'},
  'sol': {'ru': r'Квадраты по модулю $7$ принимают лишь такие значения: $$0^{2}=0,\ \ (\pm1)^{2}=1,\ \ (\pm2)^{2}=4,\ \ (\pm3)^{2}=9\equiv2 ,$$ то есть $$n^{2}\in\{0,1,2,4\}\pmod 7 .$$\n\nПрибавив единицу, получаем $$n^{2}+1\in\{1,2,3,5\}\pmod 7 ,$$ и нуля здесь нет. Значит $7\nmid n^{2}+1$ ни при каком $n$. $\blacksquare$\n\n**Замечание.** Это частный случай общего факта: нечётное простое $p$ делит $n^{2}+1$ только при $p\equiv1\pmod4$, а $7\equiv3\pmod4$.',
          'en': r'Modulo $7$ the squares take only these values: $$0^{2}=0,\ \ (\pm1)^{2}=1,\ \ (\pm2)^{2}=4,\ \ (\pm3)^{2}=9\equiv2 ,$$ that is $$n^{2}\in\{0,1,2,4\}\pmod 7 .$$\n\nAdding one, $$n^{2}+1\in\{1,2,3,5\}\pmod 7 ,$$ which never contains $0$. Hence $7\nmid n^{2}+1$ for any $n$. $\blacksquare$\n\n**Remark.** This is a special case of a general fact: an odd prime $p$ divides some $n^{2}+1$ only when $p\equiv1\pmod4$, and $7\equiv3\pmod4$.'}},

 {'src': REGION, 'lvl': 2,
  'q': {'ru': r'Найдите остаток от деления суммы $1!+2!+3!+\dots+2025!$ на $15$.',
        'en': r'Find the remainder of $1!+2!+3!+\dots+2025!$ on division by $15$.'},
  'hint': {'ru': r'Начиная с некоторого места факториалы делятся на $15$.',
           'en': r'From some point on the factorials are multiples of $15$.'},
  'sol': {'ru': r'Заметим, что $$5!=120=15\cdot8 ,$$ поэтому $15\mid5!$, а значит $15\mid n!$ при всех $n\ge5$ (ведь $n!$ содержит $5!$ множителем).\n\nЗначит вся «хвостовая» часть суммы даёт нулевой остаток, и остаётся сложить лишь первые четыре слагаемых: $$1!+2!+3!+4!=1+2+6+24=33 .$$\n\nНаконец $$33=15\cdot2+3 .$$\n\n**Ответ:** $3$.',
          'en': r'Note that $$5!=120=15\cdot8 ,$$ so $15\mid5!$, hence $15\mid n!$ for every $n\ge5$ (as $n!$ contains $5!$ as a factor).\n\nThe whole tail therefore contributes nothing, and only the first four terms remain: $$1!+2!+3!+4!=1+2+6+24=33 .$$\n\nFinally $$33=15\cdot2+3 .$$\n\n**Answer:** $3$.'}},

 {'src': SCHOOL, 'lvl': 2,
  'q': {'ru': r'Докажите, что число делится на $8$ тогда и только тогда, когда на $8$ делится число, составленное из трёх его последних цифр.',
        'en': r'Prove that a number is divisible by $8$ if and only if the number formed by its last three digits is.'},
  'hint': {'ru': r'$1000=8\cdot125$.',
           'en': r'$1000=8\cdot125$.'},
  'sol': {'ru': r'Запишем число как $$N=1000\,q+r ,$$ где $r$ — трёхзначный «хвост» (число, образованное последними тремя цифрами, $0\le r<1000$), а $q$ — всё остальное.\n\nТак как $$1000=8\cdot125 ,$$ первое слагаемое всегда делится на $8$, то есть $$N\equiv r\pmod 8 .$$\n\nЗначит $8\mid N$ равносильно $8\mid r$. $\blacksquare$\n\n**Пример.** $N=17\,584$: хвост $584=8\cdot73$ делится на $8$, значит и $17\,584$ делится ✓\n\n**Замечание.** Точно так же признак делимости на $4$ читает две последние цифры ($100=4\cdot25$), а на $16$ — четыре последние ($10000=16\cdot625$).',
          'en': r'Write the number as $$N=1000\,q+r ,$$ where $r$ is the three-digit tail (the number formed by the last three digits, $0\le r<1000$) and $q$ is everything else.\n\nSince $$1000=8\cdot125 ,$$ the first term is always a multiple of $8$, so $$N\equiv r\pmod 8 .$$\n\nHence $8\mid N$ is equivalent to $8\mid r$. $\blacksquare$\n\n**Example.** $N=17\,584$: the tail $584=8\cdot73$ is divisible by $8$, so $17\,584$ is too ✓\n\n**Remark.** In the same way the test for $4$ reads the last two digits ($100=4\cdot25$), and the test for $16$ the last four ($10000=16\cdot625$).'}},

 # ------------------------------------------------------------------ level 3
 {'src': REGION, 'lvl': 3,
  'q': {'ru': r'Найдите наименьшее натуральное $n$, дающее остаток $2$ при делении на $3$, остаток $3$ при делении на $5$ и остаток $2$ при делении на $7$.',
        'en': r'Find the smallest positive integer $n$ leaving remainder $2$ on division by $3$, remainder $3$ on division by $5$, and remainder $2$ on division by $7$.'},
  'hint': {'ru': r'Первое и третье условия объединяются в одно по модулю $21$.',
           'en': r'The first and third conditions merge into one modulo $21$.'},
  'sol': {'ru': r'**Шаг 1.** Условия $n\equiv2\pmod 3$ и $n\equiv2\pmod 7$ означают, что $n-2$ делится и на $3$, и на $7$, а значит на $21$: $$n\equiv2\pmod{21} .$$\n\n**Шаг 2.** Ищем $n$ среди чисел $$2,\;23,\;44,\;65,\;86,\;107,\ \dots$$ и требуем $n\equiv3\pmod 5$.\n\nОстатки по модулю $5$: $2,\ 3,\ 4,\ 0,\ 1,\ 2,\dots$ — подходит второе число, $$n=23 .$$\n\n**Проверка:** $23=3\cdot7+2$ ✓, $23=5\cdot4+3$ ✓, $23=7\cdot3+2$ ✓\n\n**Ответ:** $n=23$ (а все решения — это $n\equiv23\pmod{105}$).',
          'en': r'**Step 1.** The conditions $n\equiv2\pmod 3$ and $n\equiv2\pmod 7$ say that $n-2$ is divisible by both $3$ and $7$, hence by $21$: $$n\equiv2\pmod{21} .$$\n\n**Step 2.** Look among $$2,\;23,\;44,\;65,\;86,\;107,\ \dots$$ for one with $n\equiv3\pmod 5$.\n\nTheir residues mod $5$ are $2,\ 3,\ 4,\ 0,\ 1,\ 2,\dots$ — the second one works: $$n=23 .$$\n\n**Check:** $23=3\cdot7+2$ ✓, $23=5\cdot4+3$ ✓, $23=7\cdot3+2$ ✓\n\n**Answer:** $n=23$ (and all solutions are $n\equiv23\pmod{105}$).'}},

 {'src': REPUBLIC, 'lvl': 3,
  'q': {'ru': r'Докажите, что $23\mid5^{2n+1}+2^{n+4}+2^{n+1}$ при любом целом $n\ge0$.',
        'en': r'Prove that $23\mid5^{2n+1}+2^{n+4}+2^{n+1}$ for every integer $n\ge0$.'},
  'hint': {'ru': r'Вынесите $2^{n}$ из двух последних слагаемых и заметьте, что $25\equiv2\pmod{23}$.',
           'en': r'Factor $2^{n}$ out of the last two terms and note $25\equiv2\pmod{23}$.'},
  'sol': {'ru': r'Преобразуем выражение. Первое слагаемое: $$5^{2n+1}=5\cdot\left(5^{2}\right)^{n}=5\cdot25^{n} .$$ Два последних: $$2^{n+4}+2^{n+1}=2^{n}\left(2^{4}+2\right)=18\cdot2^{n} .$$\n\nЗначит $$5^{2n+1}+2^{n+4}+2^{n+1}=5\cdot25^{n}+18\cdot2^{n} .$$\n\nТеперь работаем по модулю $23$. Так как $25=23+2\equiv2$, получаем $25^{n}\equiv2^{n}$, поэтому $$5\cdot25^{n}+18\cdot2^{n}\equiv5\cdot2^{n}+18\cdot2^{n}=23\cdot2^{n}\equiv0\pmod{23} . \qquad\blacksquare$$\n\n**Проверка** при $n=0$: $5+16+2=23$ ✓ При $n=1$: $125+32+4=161=23\cdot7$ ✓',
          'en': r'Rewrite the expression. The first term: $$5^{2n+1}=5\cdot\left(5^{2}\right)^{n}=5\cdot25^{n} .$$ The last two: $$2^{n+4}+2^{n+1}=2^{n}\left(2^{4}+2\right)=18\cdot2^{n} .$$\n\nSo $$5^{2n+1}+2^{n+4}+2^{n+1}=5\cdot25^{n}+18\cdot2^{n} .$$\n\nNow work modulo $23$. Since $25=23+2\equiv2$, we get $25^{n}\equiv2^{n}$, hence $$5\cdot25^{n}+18\cdot2^{n}\equiv5\cdot2^{n}+18\cdot2^{n}=23\cdot2^{n}\equiv0\pmod{23} . \qquad\blacksquare$$\n\n**Check** at $n=0$: $5+16+2=23$ ✓ At $n=1$: $125+32+4=161=23\cdot7$ ✓'}},

 {'src': INTL, 'lvl': 3,
  'q': {'ru': r'Докажите, что $n^{2}+3n+5$ ни при каком целом $n$ не делится на $121$.',
        'en': r'Prove that $n^{2}+3n+5$ is never divisible by $121$, for any integer $n$.'},
  'hint': {'ru': r'Умножьте на $4$ и выделите полный квадрат: $4\left(n^{2}+3n+5\right)=(2n+3)^{2}+11$.',
           'en': r'Multiply by $4$ and complete the square: $4\left(n^{2}+3n+5\right)=(2n+3)^{2}+11$.'},
  'sol': {'ru': r'Умножение на $4$ ничего не портит, потому что $\gcd(4,121)=1$. Выделим полный квадрат: $$4\left(n^{2}+3n+5\right)=4n^{2}+12n+20=(2n+3)^{2}+11 .$$\n\n**Шаг 1.** Пусть $121\mid n^{2}+3n+5$. Тогда тем более $11\mid(2n+3)^{2}+11$, откуда $$11\mid(2n+3)^{2} .$$ Так как $11$ простое, по лемме Евклида $11\mid2n+3$, то есть $$2n+3=11k$$ для некоторого целого $k$.\n\n**Шаг 2.** Подставим: $$4\left(n^{2}+3n+5\right)=(11k)^{2}+11=121k^{2}+11 .$$\n\nПо предположению левая часть делится на $121$, и $121k^{2}$ тоже, значит $$121\mid11 ,$$ что неверно ✗\n\nПротиворечие. $\blacksquare$\n\n**Замечание.** На $11$ выражение делиться может: при $n=4$ получаем $16+12+5=33=11\cdot3$ — но не на $121$.',
          'en': r'Multiplying by $4$ loses nothing, since $\gcd(4,121)=1$. Complete the square: $$4\left(n^{2}+3n+5\right)=4n^{2}+12n+20=(2n+3)^{2}+11 .$$\n\n**Step 1.** Suppose $121\mid n^{2}+3n+5$. Then in particular $11\mid(2n+3)^{2}+11$, so $$11\mid(2n+3)^{2} .$$ As $11$ is prime, Euclid’s lemma gives $11\mid2n+3$, i.e. $$2n+3=11k$$ for some integer $k$.\n\n**Step 2.** Substitute: $$4\left(n^{2}+3n+5\right)=(11k)^{2}+11=121k^{2}+11 .$$\n\nBy assumption the left side is divisible by $121$, and so is $121k^{2}$, hence $$121\mid11 ,$$ which is false ✗\n\nContradiction. $\blacksquare$\n\n**Remark.** Divisibility by $11$ does happen: at $n=4$ the value is $16+12+5=33=11\cdot3$ — but never by $121$.'}},

 {'src': REGION, 'lvl': 3,
  'q': {'ru': r'Найдите остаток от деления $3^{100}$ на $101$.',
        'en': r'Find the remainder of $3^{100}$ on division by $101$.'},
  'hint': {'ru': r'$101$ — простое; примените малую теорему Ферма.',
           'en': r"$101$ is prime; use Fermat's little theorem."},
  'sol': {'ru': r'Число $101$ простое: оно не делится на $2,3,5,7$, а $11^{2}=121>101$.\n\nОснование $3$ не делится на $101$, поэтому применима малая теорема Ферма: $$a^{p-1}\equiv1\pmod p\quad\text{при}\quad p\nmid a .$$\n\nЗдесь $p=101$, значит $p-1=100$ и $$3^{100}\equiv1\pmod{101} .$$\n\n**Ответ:** $1$.\n\n**Замечание.** Прямое возведение в степень тут было бы утомительным — теорема Ферма заменяет его одной строкой.',
          'en': r'The number $101$ is prime: it is divisible by none of $2,3,5,7$, and $11^{2}=121>101$.\n\nThe base $3$ is not divisible by $101$, so Fermat’s little theorem applies: $$a^{p-1}\equiv1\pmod p\quad\text{whenever}\quad p\nmid a .$$\n\nHere $p=101$, so $p-1=100$ and $$3^{100}\equiv1\pmod{101} .$$\n\n**Answer:** $1$.\n\n**Remark.** Direct exponentiation would be tedious — Fermat’s theorem replaces it by a single line.'}},

 {'src': CLASSIC, 'lvl': 3,
  'q': {'ru': r'Докажите, что $42\mid n^{7}-n$ при любом целом $n$.',
        'en': r'Prove that $42\mid n^{7}-n$ for every integer $n$.'},
  'hint': {'ru': r'$42=2\cdot3\cdot7$; для каждого простого примените малую теорему Ферма.',
           'en': r"$42=2\cdot3\cdot7$; apply Fermat's little theorem for each prime."},
  'sol': {'ru': r'Разложим модуль: $$42=2\cdot3\cdot7 ,$$ и множители попарно взаимно просты, поэтому достаточно доказать делимость на каждый из них.\n\n**Делимость на $7$.** По малой теореме Ферма $n^{7}\equiv n\pmod 7$ при любом $n$ (при $7\mid n$ обе части нули, иначе $n^{6}\equiv1$ и умножаем на $n$). Значит $7\mid n^{7}-n$ ✓\n\n**Делимость на $3$.** По той же теореме $n^{3}\equiv n\pmod 3$. Тогда $$n^{7}=\left(n^{3}\right)^{2}\cdot n\equiv n^{2}\cdot n=n^{3}\equiv n\pmod 3 \quad\checkmark$$\n\n**Делимость на $2$.** Числа $n$ и $n^{7}$ имеют одинаковую чётность, значит их разность чётна ✓\n\nИтак, $n^{7}-n$ делится на $2$, $3$ и $7$, а потому и на их произведение $42$. $\blacksquare$\n\n**Проверка** при $n=2$: $2^{7}-2=126=42\cdot3$ ✓',
          'en': r'Factor the modulus: $$42=2\cdot3\cdot7 ,$$ with pairwise coprime factors, so it suffices to prove divisibility by each.\n\n**By $7$.** Fermat’s little theorem gives $n^{7}\equiv n\pmod 7$ for every $n$ (if $7\mid n$ both sides vanish; otherwise $n^{6}\equiv1$ and multiply by $n$). So $7\mid n^{7}-n$ ✓\n\n**By $3$.** The same theorem gives $n^{3}\equiv n\pmod 3$, hence $$n^{7}=\left(n^{3}\right)^{2}\cdot n\equiv n^{2}\cdot n=n^{3}\equiv n\pmod 3 \quad\checkmark$$\n\n**By $2$.** The numbers $n$ and $n^{7}$ have the same parity, so their difference is even ✓\n\nThus $n^{7}-n$ is divisible by $2$, $3$ and $7$, hence by their product $42$. $\blacksquare$\n\n**Check** at $n=2$: $2^{7}-2=126=42\cdot3$ ✓'}},

 {'src': REPUBLIC, 'lvl': 3,
  'q': {'ru': r'Найдите две последние цифры числа $2^{2024}$.',
        'en': r'Find the last two digits of $2^{2024}$.'},
  'hint': {'ru': r'Считайте отдельно по модулю $4$ и по модулю $25$, затем соберите ответ.',
           'en': r'Work modulo $4$ and modulo $25$ separately, then combine.'},
  'sol': {'ru': r'Нужен остаток по модулю $100=4\cdot25$; посчитаем его отдельно по каждому множителю.\n\n**По модулю $4$.** Показатель большой, поэтому $$2^{2024}\equiv0\pmod 4 .$$\n\n**По модулю $25$.** Числа $2$ и $25$ взаимно просты, и $$2^{10}=1024=25\cdot41-1\equiv-1\pmod{25}\ \Longrightarrow\ 2^{20}\equiv1\pmod{25} .$$ Так как $2024=20\cdot101+4$, получаем $$2^{2024}\equiv2^{4}=16\pmod{25} .$$\n\n**Сборка.** Ищем $x$ с $x\equiv0\pmod 4$ и $x\equiv16\pmod{25}$. Числа вида $16+25k$: $$16,\;41,\;66,\;91,\;116,\dots$$ и первое из них, кратное четырём, — это $16$.\n\nЗначит $2^{2024}\equiv16\pmod{100}$.\n\n**Ответ:** $16$.',
          'en': r'We need the remainder modulo $100=4\cdot25$; compute it modulo each factor.\n\n**Modulo $4$.** The exponent is large, so $$2^{2024}\equiv0\pmod 4 .$$\n\n**Modulo $25$.** Here $2$ and $25$ are coprime, and $$2^{10}=1024=25\cdot41-1\equiv-1\pmod{25}\ \Longrightarrow\ 2^{20}\equiv1\pmod{25} .$$ Since $2024=20\cdot101+4$, $$2^{2024}\equiv2^{4}=16\pmod{25} .$$\n\n**Combining.** We want $x$ with $x\equiv0\pmod 4$ and $x\equiv16\pmod{25}$. The numbers $16+25k$ are $$16,\;41,\;66,\;91,\;116,\dots$$ and the first multiple of four among them is $16$.\n\nHence $2^{2024}\equiv16\pmod{100}$.\n\n**Answer:** $16$.'}},

 {'src': DISTRICT, 'lvl': 3,
  'q': {'ru': r'Решите сравнение $8x\equiv12\pmod{20}$ — найдите все целые $x$.',
        'en': r'Solve the congruence $8x\equiv12\pmod{20}$ — find all integers $x$.'},
  'hint': {'ru': r'Сократите всё сравнение (вместе с модулем) на общий делитель.',
           'en': r'Divide the whole congruence, modulus included, by the common divisor.'},
  'sol': {'ru': r'Сравнение $8x\equiv12\pmod{20}$ означает $$20\mid 8x-12 .$$\n\nВсе три числа $8$, $12$ и $20$ делятся на $4$; сокращая, получаем **равносильное** сравнение с меньшим модулем: $$2x\equiv3\pmod 5 .$$ (Именно так: при сокращении делится и модуль тоже.)\n\nТеперь домножим на обратное к двойке. Так как $2\cdot3=6\equiv1\pmod 5$, обратным служит $3$: $$x\equiv3\cdot3=9\equiv4\pmod 5 .$$\n\n**Проверка:** $x=4$ даёт $8\cdot4=32=20+12$ ✓ $x=9$ даёт $72=20\cdot3+12$ ✓\n\n**Ответ:** $x\equiv4\pmod 5$, то есть $x\in\{\dots,-1,4,9,14,19,\dots\}$; по модулю $20$ это четыре класса $4,9,14,19$.',
          'en': r'The congruence $8x\equiv12\pmod{20}$ means $$20\mid 8x-12 .$$\n\nAll three of $8$, $12$, $20$ are divisible by $4$; cancelling gives an **equivalent** congruence with a smaller modulus: $$2x\equiv3\pmod 5 .$$ (Note that the modulus is divided too.)\n\nNow multiply by the inverse of two. Since $2\cdot3=6\equiv1\pmod 5$, the inverse is $3$: $$x\equiv3\cdot3=9\equiv4\pmod 5 .$$\n\n**Check:** $x=4$ gives $8\cdot4=32=20+12$ ✓ $x=9$ gives $72=20\cdot3+12$ ✓\n\n**Answer:** $x\equiv4\pmod 5$, i.e. $x\in\{\dots,-1,4,9,14,19,\dots\}$; modulo $20$ these are the four classes $4,9,14,19$.'}},

 {'src': REGION, 'lvl': 3,
  'q': {'ru': r'Найдите все простые $p$, для которых $p\mid2^{p}+1$.',
        'en': r'Find all primes $p$ with $p\mid2^{p}+1$.'},
  'hint': {'ru': r'По малой теореме Ферма $2^{p}\equiv2\pmod p$.',
           'en': r"By Fermat's little theorem $2^{p}\equiv2\pmod p$."},
  'sol': {'ru': r'По малой теореме Ферма для любого простого $p$ и любого целого $a$ верно $a^{p}\equiv a\pmod p$. В частности $$2^{p}\equiv2\pmod p ,$$ поэтому $$2^{p}+1\equiv3\pmod p .$$\n\nЗначит условие $p\mid2^{p}+1$ равносильно $p\mid3$, то есть $p=3$.\n\n**Проверка:** $2^{3}+1=9=3\cdot3$ ✓ (а, скажем, $p=5$ даёт $33$, что на $5$ не делится).\n\n**Ответ:** $p=3$.',
          'en': r'Fermat’s little theorem gives $a^{p}\equiv a\pmod p$ for every prime $p$ and every integer $a$. In particular $$2^{p}\equiv2\pmod p ,$$ hence $$2^{p}+1\equiv3\pmod p .$$\n\nSo the condition $p\mid2^{p}+1$ is equivalent to $p\mid3$, i.e. $p=3$.\n\n**Check:** $2^{3}+1=9=3\cdot3$ ✓ (whereas $p=5$ gives $33$, not a multiple of $5$).\n\n**Answer:** $p=3$.'}},

 {'src': CLASSIC, 'lvl': 3,
  'q': {'ru': r'Докажите, что десятичная запись дроби $\dfrac17$ периодична с периодом $6$, и объясните связь длины периода с порядком числа $10$ по модулю $7$.',
        'en': r'Prove that the decimal expansion of $\dfrac17$ is periodic with period $6$, and explain how the period length relates to the order of $10$ modulo $7$.'},
  'hint': {'ru': r'Ищите наименьшее $k$ с $10^{k}\equiv1\pmod 7$.',
           'en': r'Look for the least $k$ with $10^{k}\equiv1\pmod 7$.'},
  'sol': {'ru': r'**Шаг 1: порядок десятки.** Выпишем степени по модулю $7$ (помня, что $10\equiv3$): $$10^{1}\equiv3,\ \ 10^{2}\equiv2,\ \ 10^{3}\equiv6,\ \ 10^{4}\equiv4,\ \ 10^{5}\equiv5,\ \ 10^{6}\equiv1 .$$ Наименьшее $k$ с $10^{k}\equiv1$ равно $6$ — это и есть **порядок** десятки по модулю $7$.\n\n**Шаг 2: откуда период.** Из $10^{6}\equiv1\pmod 7$ следует, что $7$ делит $10^{6}-1=999999$, а именно $$999999=7\cdot142857 .$$ Поэтому $$\frac17=\frac{142857}{999999}=0{,}(142857) ,$$ ведь дробь со знаменателем $\underbrace{9\ldots9}_{k}$ — это в точности чисто периодическая дробь с периодом длины $k$.\n\n**Шаг 3: почему не короче.** Если бы период имел длину $k<6$, то по той же причине $7$ делило бы $10^{k}-1$, то есть $10^{k}\equiv1\pmod 7$ — а мы проверили, что при $k<6$ это неверно ✗\n\nЗначит длина периода ровно $6$. $\blacksquare$\n\n**Общий вывод.** Для знаменателя $n$, взаимно простого с $10$, длина периода дроби $\tfrac1n$ равна порядку числа $10$ по модулю $n$.',
          'en': r'**Step 1: the order of ten.** List the powers modulo $7$ (recall $10\equiv3$): $$10^{1}\equiv3,\ \ 10^{2}\equiv2,\ \ 10^{3}\equiv6,\ \ 10^{4}\equiv4,\ \ 10^{5}\equiv5,\ \ 10^{6}\equiv1 .$$ The least $k$ with $10^{k}\equiv1$ is $6$ — this is the **order** of ten modulo $7$.\n\n**Step 2: where the period comes from.** From $10^{6}\equiv1\pmod 7$ we get that $7$ divides $10^{6}-1=999999$, namely $$999999=7\cdot142857 .$$ Hence $$\frac17=\frac{142857}{999999}=0.\overline{142857} ,$$ because a fraction with denominator $\underbrace{9\ldots9}_{k}$ is exactly a purely periodic decimal of period length $k$.\n\n**Step 3: why not shorter.** If the period had length $k<6$, then by the same reasoning $7$ would divide $10^{k}-1$, i.e. $10^{k}\equiv1\pmod 7$ — and we checked this fails for $k<6$ ✗\n\nSo the period is exactly $6$. $\blacksquare$\n\n**General moral.** For a denominator $n$ coprime to $10$, the period length of $\tfrac1n$ equals the order of $10$ modulo $n$.'}},

 # ------------------------------------------------------------------ level 4
 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите китайскую теорему об остатках для двух взаимно простых модулей: если $\gcd(m,n)=1$, то система $x\equiv a\pmod m$, $x\equiv b\pmod n$ имеет решение, единственное по модулю $mn$.',
        'en': r'Prove the Chinese remainder theorem for two coprime moduli: if $\gcd(m,n)=1$, the system $x\equiv a\pmod m$, $x\equiv b\pmod n$ has a solution, unique modulo $mn$.'},
  'hint': {'ru': r'Возьмите $x=a+m t$ и подберите $t$; для этого нужно обратить $m$ по модулю $n$.',
           'en': r'Set $x=a+m t$ and solve for $t$; this needs the inverse of $m$ modulo $n$.'},
  'sol': {'ru': r'**Существование.** Любое $x$ с $x\equiv a\pmod m$ имеет вид $$x=a+mt,\qquad t\in\mathbb{Z} .$$ Подставим во второе условие: $$a+mt\equiv b\pmod n\quad\Longleftrightarrow\quad mt\equiv b-a\pmod n .$$\n\nТак как $\gcd(m,n)=1$, по соотношению Безу найдутся $u,v$ с $um+vn=1$, то есть $um\equiv1\pmod n$: у числа $m$ есть обратное по модулю $n$. Домножив на $u$, получаем $$t\equiv u(b-a)\pmod n ,$$ и любое такое $t$ подходит. Значит решение существует ✓\n\n**Единственность.** Пусть $x_1$ и $x_2$ — два решения. Тогда $$m\mid x_1-x_2\quad\text{и}\quad n\mid x_1-x_2 .$$ Так как $m$ и $n$ взаимно просты, отсюда $mn\mid x_1-x_2$, то есть $$x_1\equiv x_2\pmod{mn} . \qquad\blacksquare$$\n\n**Пример.** $x\equiv2\pmod 3$, $x\equiv3\pmod 5$: берём $x=2+3t$ и требуем $3t\equiv1\pmod 5$, откуда $t\equiv2$, значит $x=8$ и все решения — $x\equiv8\pmod{15}$ ✓',
          'en': r'**Existence.** Every $x$ with $x\equiv a\pmod m$ has the form $$x=a+mt,\qquad t\in\mathbb{Z} .$$ Substituting into the second condition, $$a+mt\equiv b\pmod n\quad\Longleftrightarrow\quad mt\equiv b-a\pmod n .$$\n\nSince $\gcd(m,n)=1$, Bézout gives $u,v$ with $um+vn=1$, i.e. $um\equiv1\pmod n$: the number $m$ is invertible modulo $n$. Multiplying by $u$, $$t\equiv u(b-a)\pmod n ,$$ and any such $t$ works. So a solution exists ✓\n\n**Uniqueness.** Let $x_1,x_2$ be two solutions. Then $$m\mid x_1-x_2\quad\text{and}\quad n\mid x_1-x_2 .$$ As $m$ and $n$ are coprime, this forces $mn\mid x_1-x_2$, i.e. $$x_1\equiv x_2\pmod{mn} . \qquad\blacksquare$$\n\n**Example.** $x\equiv2\pmod 3$, $x\equiv3\pmod 5$: put $x=2+3t$ and require $3t\equiv1\pmod 5$, so $t\equiv2$, giving $x=8$ and all solutions $x\equiv8\pmod{15}$ ✓'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите теорему Эйлера: если $\gcd(a,n)=1$, то $a^{\varphi(n)}\equiv1\pmod n$, где $\varphi(n)$ — количество чисел от $1$ до $n$, взаимно простых с $n$.',
        'en': r"Prove Euler's theorem: if $\gcd(a,n)=1$ then $a^{\varphi(n)}\equiv1\pmod n$, where $\varphi(n)$ counts the integers from $1$ to $n$ coprime to $n$."},
  'hint': {'ru': r'Умножение на $a$ переставляет обратимые остатки.',
           'en': r'Multiplication by $a$ permutes the invertible residues.'},
  'sol': {'ru': r'Пусть $$r_1,\;r_2,\;\dots,\;r_{\varphi(n)}$$ — все остатки от $1$ до $n$, взаимно простые с $n$.\n\n**Шаг 1: числа $ar_1,\dots,ar_{\varphi(n)}$ — те же остатки, лишь переставленные.**\n\nВо-первых, каждое $ar_i$ взаимно просто с $n$: общий простой делитель $ar_i$ и $n$ делил бы либо $a$, либо $r_i$, что противоречит взаимной простоте.\n\nВо-вторых, они попарно различны по модулю $n$: если $ar_i\equiv ar_j$, то $n\mid a(r_i-r_j)$, а так как $\gcd(a,n)=1$, то $n\mid r_i-r_j$, откуда $r_i=r_j$.\n\nИтак, $\varphi(n)$ попарно различных обратимых остатков — это в точности весь набор $r_1,\dots,r_{\varphi(n)}$.\n\n**Шаг 2.** Перемножим все элементы обоих наборов: $$\prod_{i}\left(ar_i\right)\equiv\prod_i r_i\pmod n\quad\Longleftrightarrow\quad a^{\varphi(n)}\prod_i r_i\equiv\prod_i r_i\pmod n .$$\n\n**Шаг 3.** Произведение $\prod_i r_i$ взаимно просто с $n$, значит на него можно сократить: $$a^{\varphi(n)}\equiv1\pmod n . \qquad\blacksquare$$\n\n**Частный случай.** При простом $n=p$ имеем $\varphi(p)=p-1$, и получается малая теорема Ферма.\n\n**Пример.** $n=10$, $\varphi(10)=4$, $a=3$: $3^{4}=81\equiv1\pmod{10}$ ✓',
          'en': r'Let $$r_1,\;r_2,\;\dots,\;r_{\varphi(n)}$$ be all residues from $1$ to $n$ coprime to $n$.\n\n**Step 1: the numbers $ar_1,\dots,ar_{\varphi(n)}$ are the same residues, permuted.**\n\nFirst, each $ar_i$ is coprime to $n$: a common prime divisor of $ar_i$ and $n$ would divide $a$ or $r_i$, contradicting coprimality.\n\nSecond, they are pairwise distinct modulo $n$: if $ar_i\equiv ar_j$ then $n\mid a(r_i-r_j)$, and since $\gcd(a,n)=1$ we get $n\mid r_i-r_j$, so $r_i=r_j$.\n\nThus $\varphi(n)$ pairwise distinct invertible residues — exactly the whole set $r_1,\dots,r_{\varphi(n)}$.\n\n**Step 2.** Multiply all elements of both sets: $$\prod_{i}\left(ar_i\right)\equiv\prod_i r_i\pmod n\quad\Longleftrightarrow\quad a^{\varphi(n)}\prod_i r_i\equiv\prod_i r_i\pmod n .$$\n\n**Step 3.** The product $\prod_i r_i$ is coprime to $n$, so it may be cancelled: $$a^{\varphi(n)}\equiv1\pmod n . \qquad\blacksquare$$\n\n**Special case.** For a prime $n=p$ we have $\varphi(p)=p-1$, recovering Fermat’s little theorem.\n\n**Example.** $n=10$, $\varphi(10)=4$, $a=3$: $3^{4}=81\equiv1\pmod{10}$ ✓'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Докажите, что для нечётного простого $p$ $$1^{\,p-1}+2^{\,p-1}+\dots+(p-1)^{\,p-1}\equiv-1\pmod p .$$',
        'en': r'Prove that for an odd prime $p$ $$1^{\,p-1}+2^{\,p-1}+\dots+(p-1)^{\,p-1}\equiv-1\pmod p .$$'},
  'hint': {'ru': r'Каждое слагаемое посчитайте по малой теореме Ферма.',
           'en': r"Evaluate each summand by Fermat's little theorem."},
  'sol': {'ru': r'Возьмём любое $k$ с $1\le k\le p-1$. Тогда $p\nmid k$, и по малой теореме Ферма $$k^{\,p-1}\equiv1\pmod p .$$\n\nСлагаемых ровно $p-1$, поэтому вся сумма сравнима с $$\underbrace{1+1+\dots+1}_{p-1}=p-1\equiv-1\pmod p . \qquad\blacksquare$$\n\n**Проверка** при $p=5$: $$1^{4}+2^{4}+3^{4}+4^{4}=1+16+81+256=354=5\cdot71-1\equiv-1\pmod 5 \quad\checkmark$$\n\n**Замечание.** Если показатель заменить на $p-1-1=p-2$ или любой другой, не кратный $p-1$, ответ станет другим — здесь важно именно значение $p-1$.',
          'en': r'Take any $k$ with $1\le k\le p-1$. Then $p\nmid k$, so Fermat’s little theorem gives $$k^{\,p-1}\equiv1\pmod p .$$\n\nThere are exactly $p-1$ summands, so the whole sum is congruent to $$\underbrace{1+1+\dots+1}_{p-1}=p-1\equiv-1\pmod p . \qquad\blacksquare$$\n\n**Check** at $p=5$: $$1^{4}+2^{4}+3^{4}+4^{4}=1+16+81+256=354=5\cdot71-1\equiv-1\pmod 5 \quad\checkmark$$\n\n**Remark.** Replacing the exponent by $p-2$, or by anything not a multiple of $p-1$, changes the answer — the value $p-1$ is what matters here.'}},

 {'src': CLASSIC, 'lvl': 4,
  'q': {'ru': r'Числа Ферма определяются как $F_n=2^{2^{n}}+1$. Докажите, что при $m\ne n$ числа $F_m$ и $F_n$ взаимно просты, и выведите отсюда бесконечность множества простых.',
        'en': r'The Fermat numbers are $F_n=2^{2^{n}}+1$. Prove that $F_m$ and $F_n$ are coprime for $m\ne n$, and deduce that there are infinitely many primes.'},
  'hint': {'ru': r'Докажите тождество $F_0F_1\cdots F_{n-1}=F_n-2$.',
           'en': r'Prove the identity $F_0F_1\cdots F_{n-1}=F_n-2$.'},
  'sol': {'ru': r'**Шаг 1: тождество $F_0F_1\cdots F_{n-1}=F_n-2$.** Индукция по $n$.\n\nБаза $n=1$: слева $F_0=3$, справа $F_1-2=5-2=3$ ✓\n\nПереход: пусть $F_0\cdots F_{n-1}=F_n-2=2^{2^{n}}-1$. Тогда $$F_0\cdots F_{n-1}F_n=\left(2^{2^{n}}-1\right)\left(2^{2^{n}}+1\right)=2^{2^{n+1}}-1=F_{n+1}-2 \quad\checkmark$$\n\n**Шаг 2: взаимная простота.** Пусть $m<n$ и $d\mid F_m$, $d\mid F_n$. По шагу 1 число $F_m$ входит множителем в произведение $F_0\cdots F_{n-1}=F_n-2$, значит $$d\mid F_n-2 .$$ Вместе с $d\mid F_n$ это даёт $d\mid2$. Но все числа $F_k$ нечётны, поэтому $d$ нечётно, откуда $$d=1 . \qquad\checkmark$$\n\n**Шаг 3: бесконечность простых.** У каждого $F_n>1$ есть простой делитель $p_n$. По шагу 2 разные $F_n$ не имеют общих делителей, больших единицы, значит все $p_n$ попарно различны. Получаем бесконечную последовательность различных простых. $\blacksquare$\n\n**Замечание.** Сами числа $F_n$ простыми быть не обязаны: $F_5=4294967297=641\cdot6700417$ — это и обнаружил Эйлер.',
          'en': r'**Step 1: the identity $F_0F_1\cdots F_{n-1}=F_n-2$.** Induct on $n$.\n\nBase $n=1$: the left side is $F_0=3$, the right side $F_1-2=5-2=3$ ✓\n\nStep: suppose $F_0\cdots F_{n-1}=F_n-2=2^{2^{n}}-1$. Then $$F_0\cdots F_{n-1}F_n=\left(2^{2^{n}}-1\right)\left(2^{2^{n}}+1\right)=2^{2^{n+1}}-1=F_{n+1}-2 \quad\checkmark$$\n\n**Step 2: coprimality.** Let $m<n$ and let $d\mid F_m$, $d\mid F_n$. By Step 1 the number $F_m$ is a factor of the product $F_0\cdots F_{n-1}=F_n-2$, so $$d\mid F_n-2 .$$ Together with $d\mid F_n$ this gives $d\mid2$. But every $F_k$ is odd, so $d$ is odd, hence $$d=1 . \qquad\checkmark$$\n\n**Step 3: infinitude of primes.** Each $F_n>1$ has a prime divisor $p_n$. By Step 2 distinct $F_n$ share no divisor greater than one, so all the $p_n$ are pairwise distinct — an infinite supply of distinct primes. $\blacksquare$\n\n**Remark.** The $F_n$ themselves need not be prime: $F_5=4294967297=641\cdot6700417$, as Euler discovered.'}},

 {'src': REPUBLIC, 'lvl': 4,
  'q': {'ru': r'Докажите, что $p^{4}\equiv1\pmod{240}$ для любого простого $p>5$.',
        'en': r'Prove that $p^{4}\equiv1\pmod{240}$ for every prime $p>5$.'},
  'hint': {'ru': r'$240=16\cdot3\cdot5$; разберите каждый множитель отдельно.',
           'en': r'$240=16\cdot3\cdot5$; treat each factor separately.'},
  'sol': {'ru': r'Разложим модуль на попарно взаимно простые множители: $$240=16\cdot3\cdot5 .$$ Достаточно доказать сравнение по каждому из них. Заметим, что $p>5$, поэтому $p$ не делится ни на $2$, ни на $3$, ни на $5$.\n\n**По модулю $16$.** Число $p$ нечётно, значит $p^{2}=8k+1$ для некоторого целого $k$ (мы уже знаем, что квадрат нечётного даёт остаток $1$ по модулю $8$). Тогда $$p^{4}=(8k+1)^{2}=64k^{2}+16k+1\equiv1\pmod{16} \quad\checkmark$$\n\n**По модулю $3$.** По малой теореме Ферма $p^{2}\equiv1\pmod 3$, откуда $p^{4}=\left(p^{2}\right)^{2}\equiv1$ ✓\n\n**По модулю $5$.** По малой теореме Ферма сразу $p^{4}\equiv1\pmod 5$ ✓\n\nЧисло $p^{4}-1$ делится на $16$, $3$ и $5$, а эти числа попарно взаимно просты, значит оно делится на их произведение $240$. $\blacksquare$\n\n**Проверка** при $p=7$: $7^{4}-1=2400=240\cdot10$ ✓ При $p=11$: $11^{4}-1=14640=240\cdot61$ ✓',
          'en': r'Split the modulus into pairwise coprime factors: $$240=16\cdot3\cdot5 .$$ It suffices to prove the congruence modulo each. Note $p>5$, so $p$ is divisible by none of $2$, $3$, $5$.\n\n**Modulo $16$.** As $p$ is odd, $p^{2}=8k+1$ for some integer $k$ (the square of an odd number leaves remainder $1$ modulo $8$). Then $$p^{4}=(8k+1)^{2}=64k^{2}+16k+1\equiv1\pmod{16} \quad\checkmark$$\n\n**Modulo $3$.** Fermat’s little theorem gives $p^{2}\equiv1\pmod 3$, so $p^{4}=\left(p^{2}\right)^{2}\equiv1$ ✓\n\n**Modulo $5$.** Fermat’s little theorem gives $p^{4}\equiv1\pmod 5$ directly ✓\n\nSo $p^{4}-1$ is divisible by $16$, $3$ and $5$, which are pairwise coprime, hence by their product $240$. $\blacksquare$\n\n**Check** at $p=7$: $7^{4}-1=2400=240\cdot10$ ✓ At $p=11$: $11^{4}-1=14640=240\cdot61$ ✓'}},
]
