# -*- coding: utf-8 -*-
"""Topic 1 — deeper theory, woven into lesson_01.py by content/build.py.

INTO     appends blocks to a section the lesson already defines
SECTIONS inserts whole new sections before the given original index
"""

# ---------------------------------------------------------------- new sections

DIOPHANTINE = {
 'h': {'ru': 'Линейные уравнения в целых числах',
       'en': 'Linear equations in integers'},
 'blocks': [

  {'t': 'p',
   'text': {'ru': r'Соотношение Безу — не просто красивый факт: оно полностью решает вопрос о том, когда уравнение $ax+by=c$ имеет целые решения, и позволяет выписать их все.',
            'en': r'Bézout’s identity is not just a pretty fact: it settles completely when the equation $ax+by=c$ has integer solutions, and lets us write down every one of them.'}},

  {'t': 'thm',
   'name': {'ru': 'Критерий разрешимости', 'en': 'When a solution exists'},
   'text': {'ru': r'Пусть $a,b$ — целые, не равные нулю одновременно, и $d=\gcd(a,b)$. Уравнение $$ax+by=c$$ имеет решение в целых числах **тогда и только тогда**, когда $d\mid c$.',
            'en': r'Let $a,b$ be integers, not both zero, and $d=\gcd(a,b)$. The equation $$ax+by=c$$ has a solution in integers **if and only if** $d\mid c$.'}},

  {'t': 'proof',
   'text': {'ru': r'**Необходимость.** Пусть $ax+by=c$ при некоторых целых $x,y$. Число $d$ делит и $a$, и $b$, значит делит любую их целую комбинацию, в частности $ax+by=c$.\n\n**Достаточность.** Пусть $d\mid c$, скажем $c=dk$. По соотношению Безу найдутся $x_0,y_0$ с $ax_0+by_0=d$. Умножив это равенство на $k$, получаем $$a\left(kx_0\right)+b\left(ky_0\right)=dk=c ,$$ то есть пара $\left(kx_0,\ ky_0\right)$ — решение. $\blacksquare$',
            'en': r'**Necessity.** Suppose $ax+by=c$ for some integers $x,y$. The number $d$ divides both $a$ and $b$, hence every integer combination of them, in particular $ax+by=c$.\n\n**Sufficiency.** Suppose $d\mid c$, say $c=dk$. Bézout gives $x_0,y_0$ with $ax_0+by_0=d$. Multiplying by $k$, $$a\left(kx_0\right)+b\left(ky_0\right)=dk=c ,$$ so the pair $\left(kx_0,\ ky_0\right)$ is a solution. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Все решения сразу', 'en': 'The whole family of solutions'},
   'text': {'ru': r'Пусть $d=\gcd(a,b)$ делит $c$ и пусть $\left(x_0,y_0\right)$ — какое-нибудь одно решение уравнения $ax+by=c$. Тогда **все** целые решения задаются формулами $$x=x_0+\frac bd\,t,\qquad y=y_0-\frac ad\,t,\qquad t\in\mathbb{Z},$$ и разным $t$ отвечают разные решения.',
            'en': r'Let $d=\gcd(a,b)$ divide $c$ and let $\left(x_0,y_0\right)$ be one solution of $ax+by=c$. Then **all** integer solutions are given by $$x=x_0+\frac bd\,t,\qquad y=y_0-\frac ad\,t,\qquad t\in\mathbb{Z},$$ and different $t$ give different solutions.'}},

  {'t': 'proof',
   'text': {'ru': r'**Эти пары — решения.** Подставим: $$a\left(x_0+\frac bd t\right)+b\left(y_0-\frac ad t\right)=ax_0+by_0+\frac{ab}{d}t-\frac{ab}{d}t=c \quad\checkmark$$\n\n**Других нет.** Пусть $(x,y)$ — произвольное решение. Вычтем из него исходное: $$a\left(x-x_0\right)+b\left(y-y_0\right)=0\quad\Longrightarrow\quad a\left(x-x_0\right)=-b\left(y-y_0\right).$$\n\nПоделим обе части на $d$ и обозначим $a=d\alpha$, $b=d\beta$, где $\gcd(\alpha,\beta)=1$: $$\alpha\left(x-x_0\right)=-\beta\left(y-y_0\right).$$\n\nЛевая часть делится на $\alpha$, значит и правая; но $\gcd(\alpha,\beta)=1$, поэтому $\alpha\mid y-y_0$ — точнее, из взаимной простоты следует $\beta\mid x-x_0$. Запишем $x-x_0=\beta t$ для некоторого целого $t$; подставив, получаем $\alpha\beta t=-\beta\left(y-y_0\right)$, откуда $y-y_0=-\alpha t$.\n\nЭто в точности объявленные формулы, ведь $\beta=\tfrac bd$ и $\alpha=\tfrac ad$. $\blacksquare$',
            'en': r'**These pairs are solutions.** Substitute: $$a\left(x_0+\frac bd t\right)+b\left(y_0-\frac ad t\right)=ax_0+by_0+\frac{ab}{d}t-\frac{ab}{d}t=c \quad\checkmark$$\n\n**There are no others.** Let $(x,y)$ be any solution and subtract the given one: $$a\left(x-x_0\right)+b\left(y-y_0\right)=0\quad\Longrightarrow\quad a\left(x-x_0\right)=-b\left(y-y_0\right).$$\n\nDivide by $d$ and write $a=d\alpha$, $b=d\beta$ with $\gcd(\alpha,\beta)=1$: $$\alpha\left(x-x_0\right)=-\beta\left(y-y_0\right).$$\n\nThe right side is a multiple of $\beta$, hence so is the left; since $\gcd(\alpha,\beta)=1$, coprimality forces $\beta\mid x-x_0$. Write $x-x_0=\beta t$; substituting gives $\alpha\beta t=-\beta\left(y-y_0\right)$, so $y-y_0=-\alpha t$.\n\nThese are exactly the stated formulas, since $\beta=\tfrac bd$ and $\alpha=\tfrac ad$. $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Решите в целых числах $6x+15y=27$.',
         'en': r'Solve $6x+15y=27$ in integers.'},
   'steps': {'ru': [r'$\gcd(6,15)=3$, и $3\mid27$ — решения есть.',
                    r'Поделим всё уравнение на $3$: $\ 2x+5y=9$.',
                    r'Одно решение видно сразу: $x_0=2$, $y_0=1$ (ведь $4+5=9$).',
                    r'По теореме все решения: $x=2+5t$, $y=1-2t$.',
                    r'Проверка при $t=1$: $x=7$, $y=-1$, и $6\cdot7+15\cdot(-1)=42-15=27$ ✓'],
             'en': [r'$\gcd(6,15)=3$ and $3\mid27$, so solutions exist.',
                    r'Divide the whole equation by $3$: $\ 2x+5y=9$.',
                    r'One solution is visible: $x_0=2$, $y_0=1$ (since $4+5=9$).',
                    r'By the theorem all solutions are $x=2+5t$, $y=1-2t$.',
                    r'Check at $t=1$: $x=7$, $y=-1$, and $6\cdot7+15\cdot(-1)=27$ ✓']},
   'ans': {'ru': r'$x=2+5t$, $y=1-2t$ при $t\in\mathbb{Z}$.',
           'en': r'$x=2+5t$, $y=1-2t$ for $t\in\mathbb{Z}$.'}},

  {'t': 'ex',
   'q': {'ru': r'Сколько решений в **натуральных** числах у уравнения $7x+11y=100$?',
         'en': r'How many solutions in **positive** integers does $7x+11y=100$ have?'},
   'steps': {'ru': [r'$\gcd(7,11)=1$ делит $100$, значит целые решения есть.',
                    r'Подберём одно: $y=4$ даёт $7x=56$, то есть $x=8$.',
                    r'Все целые решения: $x=8+11t$, $y=4-7t$.',
                    r'Условие $x\ge1$ даёт $t\ge-\tfrac{7}{11}$, то есть $t\ge0$; условие $y\ge1$ даёт $t\le\tfrac37$, то есть $t\le0$.',
                    r'Остаётся единственное значение $t=0$.'],
             'en': [r'$\gcd(7,11)=1$ divides $100$, so integer solutions exist.',
                    r'Find one: $y=4$ gives $7x=56$, i.e. $x=8$.',
                    r'All integer solutions: $x=8+11t$, $y=4-7t$.',
                    r'Requiring $x\ge1$ gives $t\ge0$; requiring $y\ge1$ gives $t\le0$.',
                    r'Only $t=0$ survives.']},
   'ans': {'ru': r'Ровно одно решение: $(x,y)=(8,4)$.',
           'en': r'Exactly one solution: $(x,y)=(8,4)$.'}},

  {'t': 'idea',
   'text': {'ru': r'Схема всегда одна и та же: **проверить делимость** $\gcd(a,b)\mid c$, **найти одно** решение (перебором или обратным ходом алгоритма Евклида), **выписать семейство**, и лишь потом накладывать дополнительные условия вроде положительности — они превращаются в неравенства на параметр $t$.',
            'en': r'The routine never changes: **check** that $\gcd(a,b)\mid c$, **find one** solution (by inspection or by running the Euclidean algorithm backwards), **write the family**, and only then impose extra conditions such as positivity — they turn into inequalities on the parameter $t$.'}},
 ],
}


FTA = {
 'h': {'ru': 'Основная теорема арифметики',
       'en': 'The fundamental theorem of arithmetic'},
 'blocks': [

  {'t': 'p',
   'text': {'ru': r'Мы уже пользовались разложением на простые множители — пора доказать, что оно существует и единственно. Именно единственность превращает разложение в инструмент: она позволяет сравнивать показатели и делать выводы о делимости.',
            'en': r'We have already used prime factorisation — it is time to prove that it exists and is unique. Uniqueness is what turns factorisation into a tool: it lets us compare exponents and read off divisibility.'}},

  {'t': 'thm',
   'name': {'ru': 'Лемма Евклида', 'en': 'Euclid’s lemma'},
   'text': {'ru': r'Если простое $p$ делит произведение $ab$, то $p\mid a$ или $p\mid b$.',
            'en': r'If a prime $p$ divides a product $ab$, then $p\mid a$ or $p\mid b$.'}},

  {'t': 'proof',
   'text': {'ru': r'Пусть $p\mid ab$ и $p\nmid a$. Делители простого $p$ — только $1$ и $p$, поэтому $\gcd(p,a)$ равен $1$ или $p$; второе означало бы $p\mid a$, что исключено. Значит $\gcd(p,a)=1$.\n\nПо соотношению Безу найдутся целые $u,v$ с $$up+va=1 .$$ Умножим на $b$: $$upb+v\,ab=b .$$ Первое слагаемое делится на $p$ очевидно, второе — потому что $p\mid ab$. Значит $p$ делит их сумму, то есть $p\mid b$. $\blacksquare$',
            'en': r'Suppose $p\mid ab$ and $p\nmid a$. The only divisors of the prime $p$ are $1$ and $p$, so $\gcd(p,a)$ is $1$ or $p$; the latter would mean $p\mid a$, which is excluded. Hence $\gcd(p,a)=1$.\n\nBézout gives integers $u,v$ with $$up+va=1 .$$ Multiply by $b$: $$upb+v\,ab=b .$$ The first term is visibly a multiple of $p$, the second because $p\mid ab$. So $p$ divides their sum, i.e. $p\mid b$. $\blacksquare$'}},

  {'t': 'warn',
   'text': {'ru': r'Простота здесь необходима. Число $6$ делит $4\cdot9=36$, но не делит ни $4$, ни $9$. Именно поэтому лемма Евклида — утверждение о **простых**, а не о любых делителях.',
            'en': r'Primality is essential here. The number $6$ divides $4\cdot9=36$ but divides neither $4$ nor $9$. That is exactly why Euclid’s lemma is a statement about **primes**, not about divisors in general.'}},

  {'t': 'thm',
   'name': {'ru': 'Основная теорема арифметики', 'en': 'The fundamental theorem of arithmetic'},
   'text': {'ru': r'Каждое целое число $n>1$ раскладывается в произведение простых, и притом **единственным** образом с точностью до порядка сомножителей: $$n=p_1^{\alpha_1}p_2^{\alpha_2}\cdots p_k^{\alpha_k},\qquad p_1<p_2<\dots<p_k,\quad \alpha_i\ge1 .$$',
            'en': r'Every integer $n>1$ is a product of primes, and the factorisation is **unique** up to the order of the factors: $$n=p_1^{\alpha_1}p_2^{\alpha_2}\cdots p_k^{\alpha_k},\qquad p_1<p_2<\dots<p_k,\quad \alpha_i\ge1 .$$'}},

  {'t': 'proof',
   'text': {'ru': r'**Существование (сильная индукция).** Пусть утверждение верно для всех чисел, меньших $n$. Если $n$ простое, разложение состоит из одного множителя. Иначе $n=ab$ с $1<a,b<n$; по предположению индукции $a$ и $b$ раскладываются на простые, и произведение их разложений даёт разложение для $n$ ✓\n\n**Единственность (индукция и лемма Евклида).** Пусть $$n=p_1p_2\cdots p_s=q_1q_2\cdots q_t $$ — два разложения на простые (не обязательно различные). Простое $p_1$ делит правую часть, значит по лемме Евклида делит один из множителей $q_j$; но $q_j$ простое, поэтому $p_1=q_j$. Сократим обе части на $p_1$ и получим два разложения меньшего числа $n/p_1$. По индукции они совпадают с точностью до порядка, а значит совпадают и исходные. $\blacksquare$',
            'en': r'**Existence (strong induction).** Assume the claim for all numbers below $n$. If $n$ is prime, the factorisation is a single factor. Otherwise $n=ab$ with $1<a,b<n$; by the induction hypothesis $a$ and $b$ factor into primes, and multiplying the two factorisations gives one for $n$ ✓\n\n**Uniqueness (induction plus Euclid’s lemma).** Suppose $$n=p_1p_2\cdots p_s=q_1q_2\cdots q_t $$ are two prime factorisations. The prime $p_1$ divides the right-hand side, so by Euclid’s lemma it divides some $q_j$; as $q_j$ is prime, $p_1=q_j$. Cancel $p_1$ from both sides to get two factorisations of the smaller number $n/p_1$. By induction they agree up to order, hence so do the originals. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Делимость на языке показателей', 'en': 'Divisibility in the language of exponents'},
   'text': {'ru': r'Пусть $$a=\prod_i p_i^{\alpha_i},\qquad b=\prod_i p_i^{\beta_i}$$ (по одному и тому же набору простых, нулевые показатели разрешены). Тогда $$a\mid b\quad\Longleftrightarrow\quad \alpha_i\le\beta_i\ \text{для всех } i ,$$ $$\gcd(a,b)=\prod_i p_i^{\min\left(\alpha_i,\beta_i\right)},\qquad \operatorname{lcm}(a,b)=\prod_i p_i^{\max\left(\alpha_i,\beta_i\right)} .$$',
            'en': r'Let $$a=\prod_i p_i^{\alpha_i},\qquad b=\prod_i p_i^{\beta_i}$$ over the same list of primes, zero exponents allowed. Then $$a\mid b\quad\Longleftrightarrow\quad \alpha_i\le\beta_i\ \text{for every } i ,$$ $$\gcd(a,b)=\prod_i p_i^{\min\left(\alpha_i,\beta_i\right)},\qquad \operatorname{lcm}(a,b)=\prod_i p_i^{\max\left(\alpha_i,\beta_i\right)} .$$'}},

  {'t': 'proof',
   'text': {'ru': r'**Критерий делимости.** Если $\alpha_i\le\beta_i$ при всех $i$, то $b=a\cdot\prod_i p_i^{\beta_i-\alpha_i}$, и второй множитель целый — значит $a\mid b$. Обратно, пусть $b=ac$. Разложим $c$ на простые; по единственности разложения показатель простого $p_i$ в правой части равен $\alpha_i+(\text{показатель в } c)\ge\alpha_i$, а слева он равен $\beta_i$. Значит $\beta_i\ge\alpha_i$ ✓\n\n**Формула для НОД.** Число $d=\prod p_i^{\gamma_i}$ делит и $a$, и $b$ тогда и только тогда, когда $\gamma_i\le\alpha_i$ и $\gamma_i\le\beta_i$, то есть $\gamma_i\le\min\left(\alpha_i,\beta_i\right)$. Наибольшее такое $d$ получается при $\gamma_i=\min\left(\alpha_i,\beta_i\right)$ ✓\n\n**Формула для НОК** доказывается симметрично: кратные $a$ и $b$ — это числа с показателями не меньше $\alpha_i$ и не меньше $\beta_i$. $\blacksquare$',
            'en': r'**The divisibility test.** If $\alpha_i\le\beta_i$ for all $i$ then $b=a\cdot\prod_i p_i^{\beta_i-\alpha_i}$ with an integer second factor, so $a\mid b$. Conversely let $b=ac$ and factor $c$; by uniqueness the exponent of $p_i$ on the right is $\alpha_i+(\text{its exponent in } c)\ge\alpha_i$, while on the left it is $\beta_i$. So $\beta_i\ge\alpha_i$ ✓\n\n**The gcd formula.** A number $d=\prod p_i^{\gamma_i}$ divides both $a$ and $b$ exactly when $\gamma_i\le\alpha_i$ and $\gamma_i\le\beta_i$, i.e. $\gamma_i\le\min\left(\alpha_i,\beta_i\right)$. The largest such $d$ takes $\gamma_i=\min\left(\alpha_i,\beta_i\right)$ ✓\n\n**The lcm formula** is symmetric: common multiples are the numbers whose exponents are at least $\alpha_i$ and at least $\beta_i$. $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите $\gcd$ и $\operatorname{lcm}$ чисел $600$ и $540$ через разложения.',
         'en': r'Find the gcd and lcm of $600$ and $540$ from their factorisations.'},
   'steps': {'ru': [r'$600=2^{3}\cdot3\cdot5^{2}$ и $540=2^{2}\cdot3^{3}\cdot5$.',
                    r'Минимумы показателей: $2^{\min(3,2)}=2^{2}$, $3^{\min(1,3)}=3$, $5^{\min(2,1)}=5$.',
                    r'Значит $\gcd=4\cdot3\cdot5=60$.',
                    r'Максимумы: $2^{3}\cdot3^{3}\cdot5^{2}=8\cdot27\cdot25=5400$.',
                    r'Проверка тождеством: $60\cdot5400=324\,000$ и $600\cdot540=324\,000$ ✓'],
             'en': [r'$600=2^{3}\cdot3\cdot5^{2}$ and $540=2^{2}\cdot3^{3}\cdot5$.',
                    r'Minimum exponents: $2^{\min(3,2)}=2^{2}$, $3^{\min(1,3)}=3$, $5^{\min(2,1)}=5$.',
                    r'So $\gcd=4\cdot3\cdot5=60$.',
                    r'Maxima: $2^{3}\cdot3^{3}\cdot5^{2}=8\cdot27\cdot25=5400$.',
                    r'Check against the identity: $60\cdot5400=324\,000=600\cdot540$ ✓']},
   'ans': {'ru': r'$\gcd=60$, $\operatorname{lcm}=5400$.',
           'en': r'$\gcd=60$, $\operatorname{lcm}=5400$.'}},

  {'t': 'thm',
   'name': {'ru': 'Степень делит степень', 'en': 'Powers inherit divisibility'},
   'text': {'ru': r'Если $\gcd(a,b)=1$ и $ab$ — точный $n$-й степень, то каждый из множителей $a$ и $b$ сам является точной $n$-й степенью (с точностью до знака при чётном $n$).',
            'en': r'If $\gcd(a,b)=1$ and $ab$ is a perfect $n$-th power, then each of $a$ and $b$ is itself a perfect $n$-th power (up to sign when $n$ is even).'}},

  {'t': 'proof',
   'text': {'ru': r'Возьмём любое простое $p$ и обозначим через $\alpha$ и $\beta$ его показатели в $a$ и в $b$. Так как $\gcd(a,b)=1$, простое $p$ не может делить оба числа, значит одно из чисел $\alpha,\beta$ равно нулю.\n\nПоказатель $p$ в произведении равен $\alpha+\beta$, а произведение — точная $n$-я степень, поэтому $n\mid\alpha+\beta$. Но одно из слагаемых нулевое, значит $n$ делит и $\alpha$, и $\beta$.\n\nЭто верно для каждого простого, поэтому все показатели в $a$ (и в $b$) кратны $n$, то есть каждое из чисел — точная $n$-я степень. $\blacksquare$',
            'en': r'Take any prime $p$ and let $\alpha$, $\beta$ be its exponents in $a$ and $b$. Since $\gcd(a,b)=1$, the prime $p$ cannot divide both, so one of $\alpha,\beta$ is zero.\n\nThe exponent of $p$ in the product is $\alpha+\beta$, and the product is a perfect $n$-th power, so $n\mid\alpha+\beta$. As one summand vanishes, $n$ divides both $\alpha$ and $\beta$.\n\nThis holds for every prime, so all exponents in $a$ (and in $b$) are multiples of $n$: each number is a perfect $n$-th power. $\blacksquare$'}},

  {'t': 'note',
   'text': {'ru': r'Это одна из самых частых «рабочих лошадок» олимпиадной теории чисел. Например, из $xy=z^{2}$ при $\gcd(x,y)=1$ сразу следует, что $x$ и $y$ — квадраты; именно так описывают все пифагоровы тройки.',
            'en': r'This is one of the great workhorses of olympiad number theory. From $xy=z^{2}$ with $\gcd(x,y)=1$ it follows at once that $x$ and $y$ are squares — precisely the step that describes all Pythagorean triples.'}},
 ],
}


LEGENDRE = {
 'h': {'ru': 'Простые внутри факториала',
       'en': 'Primes inside a factorial'},
 'blocks': [

  {'t': 'p',
   'text': {'ru': r'Факториал $n!$ — произведение всех чисел до $n$, и часто нужно знать не сам факториал, а **сколько раз** в него входит данное простое. Ответ даёт формула Лежандра.',
            'en': r'The factorial $n!$ multiplies everything up to $n$, and one often needs not the factorial itself but **how many times** a given prime sits inside it. Legendre’s formula answers that.'}},

  {'t': 'thm',
   'name': {'ru': 'Формула Лежандра', 'en': 'Legendre’s formula'},
   'text': {'ru': r'Показатель простого $p$ в разложении числа $n!$ равен $$v_p(n!)=\left\lfloor\frac np\right\rfloor+\left\lfloor\frac n{p^{2}}\right\rfloor+\left\lfloor\frac n{p^{3}}\right\rfloor+\cdots$$ (сумма конечна: слагаемые обращаются в нуль, как только $p^{k}>n$).',
            'en': r'The exponent of a prime $p$ in $n!$ equals $$v_p(n!)=\left\lfloor\frac np\right\rfloor+\left\lfloor\frac n{p^{2}}\right\rfloor+\left\lfloor\frac n{p^{3}}\right\rfloor+\cdots$$ (a finite sum: the terms vanish once $p^{k}>n$).'}},

  {'t': 'proof',
   'text': {'ru': r'Посчитаем вклад каждого сомножителя двумя способами — «по этажам».\n\nСреди чисел $1,2,\dots,n$ ровно $\left\lfloor\tfrac np\right\rfloor$ кратны $p$: это $p,2p,3p,\dots$ Каждое из них вносит в произведение хотя бы одну степень $p$.\n\nСреди тех же чисел ровно $\left\lfloor\tfrac n{p^{2}}\right\rfloor$ кратны $p^{2}$; каждое такое число вносит **ещё одну** степень сверх уже посчитанной.\n\nВообще, кратные $p^{k}$ вносят по одной дополнительной степени на $k$-м этаже, и их $\left\lfloor\tfrac n{p^{k}}\right\rfloor$ штук.\n\nСложив вклады всех этажей, получаем ровно объявленную сумму: число, делящееся на $p^{m}$ и не более, будет посчитано ровно $m$ раз — по разу на каждом из первых $m$ этажей. $\blacksquare$',
            'en': r'Count the contribution of each factor "floor by floor".\n\nAmong $1,2,\dots,n$ exactly $\left\lfloor\tfrac np\right\rfloor$ are multiples of $p$, namely $p,2p,3p,\dots$; each contributes at least one power of $p$.\n\nAmong the same numbers exactly $\left\lfloor\tfrac n{p^{2}}\right\rfloor$ are multiples of $p^{2}$; each of those contributes **one more** power beyond the one already counted.\n\nIn general the multiples of $p^{k}$ contribute one extra power each on the $k$-th floor, and there are $\left\lfloor\tfrac n{p^{k}}\right\rfloor$ of them.\n\nAdding the floors gives exactly the stated sum: a number divisible by $p^{m}$ and no further is counted exactly $m$ times, once on each of the first $m$ floors. $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Сколькими нулями оканчивается $100!$?',
         'en': r'In how many zeros does $100!$ end?'},
   'steps': {'ru': [r'Нуль на конце — это множитель $10=2\cdot5$, а двоек в факториале заведомо больше, чем пятёрок.',
                    r'Значит ответ равен $v_5(100!)$.',
                    r'$\left\lfloor\tfrac{100}{5}\right\rfloor=20$, $\left\lfloor\tfrac{100}{25}\right\rfloor=4$, $\left\lfloor\tfrac{100}{125}\right\rfloor=0$.',
                    r'Итого $20+4=24$.'],
             'en': [r'A trailing zero is a factor $10=2\cdot5$, and a factorial always has more twos than fives.',
                    r'So the answer is $v_5(100!)$.',
                    r'$\left\lfloor\tfrac{100}{5}\right\rfloor=20$, $\left\lfloor\tfrac{100}{25}\right\rfloor=4$, $\left\lfloor\tfrac{100}{125}\right\rfloor=0$.',
                    r'Total $20+4=24$.']},
   'ans': {'ru': r'$24$ нуля.', 'en': r'$24$ zeros.'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите наибольшее $k$, для которого $3^{k}$ делит $50!$.',
         'en': r'Find the largest $k$ with $3^{k}\mid50!$.'},
   'steps': {'ru': [r'$\left\lfloor\tfrac{50}{3}\right\rfloor=16$ — кратные трёх.',
                    r'$\left\lfloor\tfrac{50}{9}\right\rfloor=5$ — кратные девяти дают ещё по одной тройке.',
                    r'$\left\lfloor\tfrac{50}{27}\right\rfloor=1$, а $\left\lfloor\tfrac{50}{81}\right\rfloor=0$.',
                    r'Складываем: $16+5+1=22$.'],
             'en': [r'$\left\lfloor\tfrac{50}{3}\right\rfloor=16$ multiples of three.',
                    r'$\left\lfloor\tfrac{50}{9}\right\rfloor=5$ multiples of nine give one more three each.',
                    r'$\left\lfloor\tfrac{50}{27}\right\rfloor=1$, and $\left\lfloor\tfrac{50}{81}\right\rfloor=0$.',
                    r'Adding: $16+5+1=22$.']},
   'ans': {'ru': r'$k=22$.', 'en': r'$k=22$.'}},

  {'t': 'note',
   'text': {'ru': r'Отсюда же следует, что биномиальный коэффициент $\dbinom nk=\dfrac{n!}{k!\,(n-k)!}$ всегда целый: показатель каждого простого в знаменателе не превосходит показателя в числителе, потому что $$\left\lfloor x+y\right\rfloor\ \ge\ \left\lfloor x\right\rfloor+\left\lfloor y\right\rfloor .$$',
            'en': r'The same formula shows the binomial coefficient $\dbinom nk=\dfrac{n!}{k!\,(n-k)!}$ is always an integer: every prime’s exponent in the denominator is at most its exponent in the numerator, because $$\left\lfloor x+y\right\rfloor\ \ge\ \left\lfloor x\right\rfloor+\left\lfloor y\right\rfloor .$$'}},
 ],
}


SECTIONS = [(4, DIOPHANTINE), (4, FTA), (6, LEGENDRE)]


# ---------------------------------------------------- blocks added to sections

INTO = {

 # ---- 0: What divisibility means
 0: [
  {'t': 'thm',
   'name': {'ru': 'Делитель не больше числа', 'en': 'A divisor is no larger than the number'},
   'text': {'ru': r'Если $d\mid a$ и $a\ne0$, то $|d|\le|a|$. В частности, у всякого ненулевого числа **конечное** число делителей.',
            'en': r'If $d\mid a$ and $a\ne0$ then $|d|\le|a|$. In particular every non-zero number has **finitely many** divisors.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть $a=dk$. Число $a$ ненулевое, значит и $k\ne0$, а тогда $|k|\ge1$. Отсюда $$|a|=|d|\cdot|k|\ \ge\ |d| .$$\n\nЗначит все делители лежат в конечном промежутке от $-|a|$ до $|a|$, и их конечное число. $\blacksquare$',
            'en': r'Let $a=dk$. Since $a\ne0$ we have $k\ne0$, hence $|k|\ge1$ and $$|a|=|d|\cdot|k|\ \ge\ |d| .$$\n\nSo every divisor lies in the finite range from $-|a|$ to $|a|$, and there are finitely many. $\blacksquare$'}},
  {'t': 'warn',
   'text': {'ru': r'Оговорка $a\ne0$ существенна: у нуля делителей бесконечно много, ведь $d\mid0$ при любом $d\ne0$. Поэтому в задачах вида «найдите все $d$, делящие …» первым делом убеждаются, что делимое не обращается в нуль.',
            'en': r'The hypothesis $a\ne0$ matters: zero has infinitely many divisors, since $d\mid0$ for every $d\ne0$. So in problems of the form "find all $d$ dividing …" the first move is to make sure the dividend is not zero.'}},
  {'t': 'thm',
   'name': {'ru': 'У каждого числа есть простой делитель', 'en': 'Every number has a prime divisor'},
   'text': {'ru': r'Всякое целое $n>1$ имеет простой делитель; более того, его **наименьший** делитель, больший единицы, прост, и если $n$ составное, то этот делитель не превосходит $\sqrt n$.',
            'en': r'Every integer $n>1$ has a prime divisor; moreover its **least** divisor greater than one is prime, and if $n$ is composite that divisor is at most $\sqrt n$.'}},
  {'t': 'proof',
   'text': {'ru': r'Множество делителей числа $n$, больших единицы, непусто (в нём есть само $n$), значит в нём есть наименьший элемент $p$.\n\n**$p$ простое.** Если бы $p=ab$ с $1<a<p$, то $a$ делил бы $n$ и был бы меньше $p$ — противоречие с минимальностью.\n\n**Оценка для составного $n$.** Запишем $n=pm$. Если $n$ составное, то $m>1$, значит $m$ тоже делитель, больший единицы, и по минимальности $m\ge p$. Тогда $$n=pm\ \ge\ p^{2}\quad\Longrightarrow\quad p\le\sqrt n . \qquad\blacksquare$$',
            'en': r'The set of divisors of $n$ greater than one is non-empty (it contains $n$), so it has a least element $p$.\n\n**$p$ is prime.** If $p=ab$ with $1<a<p$, then $a$ would divide $n$ and be smaller than $p$, contradicting minimality.\n\n**The bound for composite $n$.** Write $n=pm$. If $n$ is composite then $m>1$, so $m$ is also a divisor greater than one and minimality gives $m\ge p$. Hence $$n=pm\ \ge\ p^{2}\quad\Longrightarrow\quad p\le\sqrt n . \qquad\blacksquare$$'}},
  {'t': 'idea',
   'text': {'ru': r'Отсюда берётся стандартная проверка на простоту: чтобы убедиться, что $n$ простое, достаточно перебрать простые делители до $\sqrt n$. Для $n=211$ хватает $2,3,5,7,11,13$, потому что $14^{2}=196<211<225=15^{2}$.',
            'en': r'This gives the standard primality check: to see that $n$ is prime it suffices to test prime divisors up to $\sqrt n$. For $n=211$ the primes $2,3,5,7,11,13$ suffice, since $14^{2}=196<211<225=15^{2}$.'}},
 ],

 # ---- 1: Division with remainder
 1: [
  {'t': 'thm',
   'name': {'ru': 'Частное — это целая часть', 'en': 'The quotient is a floor'},
   'text': {'ru': r'В записи $a=bq+r$ с $0\le r<b$ и $b>0$ частное и остаток выражаются явно: $$q=\left\lfloor\frac ab\right\rfloor,\qquad r=a-b\left\lfloor\frac ab\right\rfloor .$$',
            'en': r'In $a=bq+r$ with $0\le r<b$ and $b>0$, the quotient and remainder are given explicitly by $$q=\left\lfloor\frac ab\right\rfloor,\qquad r=a-b\left\lfloor\frac ab\right\rfloor .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Условие $0\le r<b$ равносильно $0\le a-bq<b$, то есть $$bq\le a<bq+b\quad\Longleftrightarrow\quad q\le\frac ab<q+1 .$$\n\nА последнее и означает по определению, что $q=\left\lfloor\tfrac ab\right\rfloor$. Формула для $r$ получается подстановкой. $\blacksquare$',
            'en': r'The condition $0\le r<b$ is equivalent to $0\le a-bq<b$, that is $$bq\le a<bq+b\quad\Longleftrightarrow\quad q\le\frac ab<q+1 ,$$ which by definition says $q=\left\lfloor\tfrac ab\right\rfloor$. The formula for $r$ follows by substitution. $\blacksquare$'}},
  {'t': 'def',
   'name': {'ru': 'Полная система вычетов', 'en': 'Complete residue system'},
   'text': {'ru': r'Набор из $n$ целых чисел называется **полной системой вычетов** по модулю $n$, если они дают попарно различные остатки при делении на $n$ — то есть покрывают все остатки $0,1,\dots,n-1$ ровно по разу.',
            'en': r'A set of $n$ integers is a **complete residue system** modulo $n$ if they leave pairwise different remainders on division by $n$ — that is, they cover each of $0,1,\dots,n-1$ exactly once.'}},
  {'t': 'note',
   'text': {'ru': r'Самый привычный пример — сами числа $0,1,\dots,n-1$. Но полезны и другие: например, $n$ подряд идущих целых чисел всегда образуют полную систему вычетов. Именно поэтому «среди любых $n$ подряд идущих чисел ровно одно делится на $n$».',
            'en': r'The familiar example is $0,1,\dots,n-1$ itself. Others are useful too: any $n$ consecutive integers form a complete residue system. That is exactly why "among any $n$ consecutive integers exactly one is divisible by $n$".'}},
  {'t': 'ex',
   'q': {'ru': r'Докажите, что произведение любых трёх подряд идущих целых чисел делится на $6$.',
         'en': r'Prove that the product of any three consecutive integers is divisible by $6$.'},
   'steps': {'ru': [r'Обозначим числа $n,\ n+1,\ n+2$.',
                    r'Три подряд идущих числа образуют полную систему вычетов по модулю $3$, значит ровно одно из них делится на $3$.',
                    r'Среди трёх подряд идущих есть хотя бы одно чётное (даже два, если $n$ чётно), значит произведение делится на $2$.',
                    r'Числа $2$ и $3$ взаимно просты, поэтому произведение делится на $6$.'],
             'en': [r'Call the numbers $n,\ n+1,\ n+2$.',
                    r'Three consecutive integers form a complete residue system modulo $3$, so exactly one of them is divisible by $3$.',
                    r'Among three consecutive integers at least one is even, so the product is divisible by $2$.',
                    r'As $2$ and $3$ are coprime, the product is divisible by $6$.']},
   'ans': {'ru': r'Делится, и это частный случай общего факта: произведение $k$ подряд идущих чисел делится на $k!$.',
           'en': r'It is divisible — a special case of the general fact that a product of $k$ consecutive integers is divisible by $k!$.'}},
 ],

 # ---- 2: Divisibility rules
 2: [
  {'t': 'thm',
   'name': {'ru': 'Правила по последним цифрам', 'en': 'Rules that read the last digits'},
   'text': {'ru': r'Для любого $k\ge1$ и любого числа $N$ с «хвостом» $T_k$ из последних $k$ цифр $$2^{k}\mid N\ \Longleftrightarrow\ 2^{k}\mid T_k ,\qquad 5^{k}\mid N\ \Longleftrightarrow\ 5^{k}\mid T_k .$$ В частности: на $2$ и на $5$ смотрит последняя цифра, на $4$ и на $25$ — две последние, на $8$ и на $125$ — три последние.',
            'en': r'For every $k\ge1$ and every number $N$ with tail $T_k$ formed by its last $k$ digits, $$2^{k}\mid N\ \Longleftrightarrow\ 2^{k}\mid T_k ,\qquad 5^{k}\mid N\ \Longleftrightarrow\ 5^{k}\mid T_k .$$ In particular $2$ and $5$ read the last digit, $4$ and $25$ the last two, $8$ and $125$ the last three.'}},
  {'t': 'proof',
   'text': {'ru': r'Запишем число, отделив хвост: $$N=10^{k}\,q+T_k ,$$ где $q$ — то, что осталось слева.\n\nКлючевое наблюдение: $$10^{k}=2^{k}\cdot5^{k} ,$$ поэтому $10^{k}$ делится и на $2^{k}$, и на $5^{k}$. Значит первое слагаемое кратно каждому из этих чисел, и $$N\equiv T_k \pmod{2^{k}},\qquad N\equiv T_k \pmod{5^{k}} .$$\n\nОтсюда обе равносильности. $\blacksquare$',
            'en': r'Split off the tail: $$N=10^{k}\,q+T_k ,$$ where $q$ is whatever stands to the left.\n\nThe key observation is $$10^{k}=2^{k}\cdot5^{k} ,$$ so $10^{k}$ is divisible by both $2^{k}$ and $5^{k}$. Hence the first term is a multiple of each, and $$N\equiv T_k \pmod{2^{k}},\qquad N\equiv T_k \pmod{5^{k}} .$$\n\nBoth equivalences follow. $\blacksquare$'}},
  {'t': 'ex',
   'q': {'ru': r'Делится ли $37\,516$ на $4$? А на $8$?',
         'en': r'Is $37\,516$ divisible by $4$? By $8$?'},
   'steps': {'ru': [r'Для четвёрки смотрим две последние цифры: $16=4\cdot4$ — делится ✓',
                    r'Для восьмёрки смотрим три последние: $516=8\cdot64+4$ — не делится ✗',
                    r'Проверка: $37\,516=4\cdot9379$, а $9379$ нечётно, значит на $8$ число действительно не делится.'],
             'en': [r'For $4$ read the last two digits: $16=4\cdot4$ — divisible ✓',
                    r'For $8$ read the last three: $516=8\cdot64+4$ — not divisible ✗',
                    r'Check: $37\,516=4\cdot9379$ and $9379$ is odd, so $8$ indeed does not divide it.']},
   'ans': {'ru': r'На $4$ делится, на $8$ — нет.', 'en': r'Divisible by $4$, not by $8$.'}},
  {'t': 'thm',
   'name': {'ru': 'Признак для 7, 11 и 13 сразу', 'en': 'One rule for 7, 11 and 13'},
   'text': {'ru': r'Разобьём десятичную запись на группы по три цифры справа налево и обозначим их значения $g_0,g_1,g_2,\dots$ Тогда для $m\in\{7,11,13\}$ $$m\mid N\quad\Longleftrightarrow\quad m\ \big|\ g_0-g_1+g_2-\cdots$$',
            'en': r'Split the decimal expansion into three-digit groups from the right, with values $g_0,g_1,g_2,\dots$ Then for $m\in\{7,11,13\}$ $$m\mid N\quad\Longleftrightarrow\quad m\ \big|\ g_0-g_1+g_2-\cdots$$'}},
  {'t': 'proof',
   'text': {'ru': r'По построению групп $$N=\sum_{j\ge0}g_j\cdot1000^{\,j} .$$\n\nКлючевое разложение: $$1001=7\cdot11\cdot13 ,$$ поэтому $1000\equiv-1$ по каждому из модулей $7$, $11$, $13$. Возводя в степень, $$1000^{\,j}\equiv(-1)^{j} ,$$ откуда $$N\equiv\sum_{j\ge0}(-1)^{j}g_j=g_0-g_1+g_2-\cdots$$ по каждому из трёх модулей. $\blacksquare$',
            'en': r'By construction $$N=\sum_{j\ge0}g_j\cdot1000^{\,j} .$$\n\nThe key factorisation is $$1001=7\cdot11\cdot13 ,$$ so $1000\equiv-1$ modulo each of $7$, $11$, $13$. Raising to powers, $$1000^{\,j}\equiv(-1)^{j} ,$$ hence $$N\equiv g_0-g_1+g_2-\cdots$$ modulo each of the three. $\blacksquare$'}},
  {'t': 'ex',
   'q': {'ru': r'Проверьте, делится ли $1\,234\,569$ на $7$, на $11$ и на $13$.',
         'en': r'Test whether $1\,234\,569$ is divisible by $7$, by $11$ and by $13$.'},
   'steps': {'ru': [r'Группы по три справа: $569$, $234$, $1$.',
                    r'Знакопеременная сумма: $569-234+1=336$.',
                    r'$336=7\cdot48$ — значит на $7$ делится ✓',
                    r'$336=11\cdot30+6$ — на $11$ не делится ✗',
                    r'$336=13\cdot25+11$ — на $13$ не делится ✗'],
             'en': [r'Groups of three from the right: $569$, $234$, $1$.',
                    r'Alternating sum: $569-234+1=336$.',
                    r'$336=7\cdot48$, so it is divisible by $7$ ✓',
                    r'$336=11\cdot30+6$, not divisible by $11$ ✗',
                    r'$336=13\cdot25+11$, not divisible by $13$ ✗']},
   'ans': {'ru': r'Делится на $7$; на $11$ и $13$ — нет.',
           'en': r'Divisible by $7$; not by $11$ or $13$.'}},
 ],

 # ---- 3: GCD and the Euclidean algorithm
 3: [
  {'t': 'thm',
   'name': {'ru': 'Свойства НОД', 'en': 'Properties of the gcd'},
   'text': {'ru': r'Для целых $a,b$ (не равных нулю одновременно) и натурального $m$: $\;$ (1) $\gcd(a,b)=\gcd(b,a)=\gcd(|a|,|b|)$; $\;$ (2) $\gcd(a+kb,\ b)=\gcd(a,b)$ при любом целом $k$; $\;$ (3) $\gcd(ma,mb)=m\gcd(a,b)$; $\;$ (4) если $d=\gcd(a,b)$, то $\gcd\!\left(\tfrac ad,\tfrac bd\right)=1$.',
            'en': r'For integers $a,b$ (not both zero) and a positive integer $m$: $\;$ (1) $\gcd(a,b)=\gcd(b,a)=\gcd(|a|,|b|)$; $\;$ (2) $\gcd(a+kb,\ b)=\gcd(a,b)$ for every integer $k$; $\;$ (3) $\gcd(ma,mb)=m\gcd(a,b)$; $\;$ (4) if $d=\gcd(a,b)$ then $\gcd\!\left(\tfrac ad,\tfrac bd\right)=1$.'}},
  {'t': 'proof',
   'text': {'ru': r'**(1)** Делители числа и его модуля совпадают, а определение НОД симметрично.\n\n**(2)** Это ключевая лемма в чистом виде: если $d\mid a$ и $d\mid b$, то $d\mid a+kb$; обратно, если $d\mid a+kb$ и $d\mid b$, то $d\mid(a+kb)-kb=a$. Значит пары $(a,b)$ и $(a+kb,\,b)$ имеют одни и те же общие делители, а с ними и один и тот же наибольший.\n\n**(3)** По соотношению Безу $\gcd(a,b)$ — наименьшее положительное число вида $ax+by$. Тогда наименьшее положительное число вида $(ma)x+(mb)y=m(ax+by)$ равно $m\gcd(a,b)$.\n\n**(4)** Применим (3) с $m=d$ к числам $\tfrac ad$ и $\tfrac bd$: $$d=\gcd(a,b)=\gcd\left(d\cdot\tfrac ad,\ d\cdot\tfrac bd\right)=d\cdot\gcd\left(\tfrac ad,\tfrac bd\right),$$ откуда $\gcd\left(\tfrac ad,\tfrac bd\right)=1$. $\blacksquare$',
            'en': r'**(1)** A number and its absolute value have the same divisors, and the definition is symmetric.\n\n**(2)** This is the key lemma in bare form: if $d\mid a$ and $d\mid b$ then $d\mid a+kb$; conversely if $d\mid a+kb$ and $d\mid b$ then $d\mid(a+kb)-kb=a$. So the pairs $(a,b)$ and $(a+kb,\,b)$ have exactly the same common divisors, hence the same greatest one.\n\n**(3)** By Bézout, $\gcd(a,b)$ is the least positive number of the form $ax+by$. The least positive number of the form $(ma)x+(mb)y=m(ax+by)$ is then $m\gcd(a,b)$.\n\n**(4)** Apply (3) with $m=d$ to $\tfrac ad$ and $\tfrac bd$: $$d=\gcd(a,b)=d\cdot\gcd\left(\tfrac ad,\tfrac bd\right),$$ so $\gcd\left(\tfrac ad,\tfrac bd\right)=1$. $\blacksquare$'}},
  {'t': 'thm',
   'name': {'ru': 'Универсальное свойство НОД', 'en': 'The universal property of the gcd'},
   'text': {'ru': r'Каждый общий делитель чисел $a$ и $b$ делит $\gcd(a,b)$. Иначе говоря, НОД — не просто самый большой из общих делителей, а тот, через который «проходят» все остальные.',
            'en': r'Every common divisor of $a$ and $b$ divides $\gcd(a,b)$. In other words the gcd is not merely the largest common divisor: it is the one all the others pass through.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть $c\mid a$ и $c\mid b$. По соотношению Безу $$\gcd(a,b)=ax+by $$ для некоторых целых $x,y$. Число $c$ делит оба слагаемых справа, значит делит и сумму, то есть $c\mid\gcd(a,b)$. $\blacksquare$',
            'en': r'Let $c\mid a$ and $c\mid b$. Bézout gives $$\gcd(a,b)=ax+by $$ for some integers $x,y$. Since $c$ divides both terms on the right, it divides the sum, i.e. $c\mid\gcd(a,b)$. $\blacksquare$'}},
  {'t': 'ex',
   'q': {'ru': r'Найдите $\gcd\left(n,\ n+6\right)$ для всех натуральных $n$.',
         'en': r'Find $\gcd\left(n,\ n+6\right)$ for every positive integer $n$.'},
   'steps': {'ru': [r'По свойству (2) $\gcd(n,\ n+6)=\gcd(n,\ 6)$.',
                    r'Значит ответ зависит только от остатка $n$ по модулю $6$.',
                    r'Если $6\mid n$, то НОД равен $6$; если $n$ кратно $3$, но не $2$ — равен $3$; если кратно $2$, но не $3$ — равен $2$; иначе равен $1$.',
                    r'Проверка: $\gcd(9,15)=3$ ✓ и $\gcd(8,14)=2$ ✓'],
             'en': [r'By property (2), $\gcd(n,\ n+6)=\gcd(n,\ 6)$.',
                    r'So the answer depends only on $n$ modulo $6$.',
                    r'If $6\mid n$ the gcd is $6$; if $n$ is a multiple of $3$ but not $2$, it is $3$; a multiple of $2$ but not $3$, it is $2$; otherwise $1$.',
                    r'Check: $\gcd(9,15)=3$ ✓ and $\gcd(8,14)=2$ ✓']},
   'ans': {'ru': r'$\gcd(n,n+6)=\gcd(n,6)\in\{1,2,3,6\}$.',
           'en': r'$\gcd(n,n+6)=\gcd(n,6)\in\{1,2,3,6\}$.'}},
  {'t': 'note',
   'text': {'ru': r'Приём «$\gcd(n,\ n+k)=\gcd(n,k)$» решает целый класс задач: разность двух чисел ограничивает их общий делитель. Например, соседние числа всегда взаимно просты, ведь $\gcd(n,n+1)=\gcd(n,1)=1$.',
            'en': r'The move "$\gcd(n,\ n+k)=\gcd(n,k)$" settles a whole class of problems: the difference of two numbers bounds their common divisor. Consecutive integers are always coprime, since $\gcd(n,n+1)=\gcd(n,1)=1$.'}},
 ],

 # ---- 4: LCM and its link with the GCD
 4: [
  {'t': 'thm',
   'name': {'ru': 'Универсальное свойство НОК', 'en': 'The universal property of the lcm'},
   'text': {'ru': r'Каждое общее кратное чисел $a$ и $b$ делится на $\operatorname{lcm}(a,b)$. Симметрично к НОД: наименьшее общее кратное — то, которое делит все остальные.',
            'en': r'Every common multiple of $a$ and $b$ is divisible by $\operatorname{lcm}(a,b)$. Symmetric to the gcd: the least common multiple is the one dividing all the others.'}},
  {'t': 'proof',
   'text': {'ru': r'Обозначим $L=\operatorname{lcm}(a,b)$ и пусть $M$ — произвольное общее кратное. Разделим с остатком: $$M=Lq+r,\qquad 0\le r<L .$$\n\nЧисло $a$ делит и $M$, и $L$, значит делит $r=M-Lq$; то же верно для $b$. Значит $r$ — общее кратное чисел $a$ и $b$, причём $0\le r<L$.\n\nНо $L$ — **наименьшее положительное** общее кратное, поэтому $r$ не может быть положительным. Значит $r=0$, то есть $L\mid M$. $\blacksquare$',
            'en': r'Write $L=\operatorname{lcm}(a,b)$ and let $M$ be any common multiple. Divide with remainder: $$M=Lq+r,\qquad 0\le r<L .$$\n\nThe number $a$ divides both $M$ and $L$, hence divides $r=M-Lq$; the same holds for $b$. So $r$ is a common multiple of $a$ and $b$ with $0\le r<L$.\n\nBut $L$ is the **least positive** common multiple, so $r$ cannot be positive. Hence $r=0$, i.e. $L\mid M$. $\blacksquare$'}},
  {'t': 'ex',
   'q': {'ru': r'Автобусы трёх маршрутов отходят от вокзала каждые $12$, $18$ и $30$ минут и вышли одновременно в $6{:}00$. Когда они снова отойдут вместе?',
         'en': r'Buses on three routes leave the station every $12$, $18$ and $30$ minutes and departed together at $6{:}00$. When do they next leave together?'},
   'steps': {'ru': [r'Момент совместного отправления — это общее кратное чисел $12$, $18$, $30$.',
                    r'По универсальному свойству все такие моменты кратны наименьшему, поэтому достаточно найти $\operatorname{lcm}(12,18,30)$.',
                    r'Разложим: $12=2^{2}\cdot3$, $18=2\cdot3^{2}$, $30=2\cdot3\cdot5$.',
                    r'Берём каждое простое в наибольшей степени: $2^{2}\cdot3^{2}\cdot5=180$.',
                    r'$180$ минут — это ровно три часа.'],
             'en': [r'A joint departure happens at a common multiple of $12$, $18$, $30$.',
                    r'By the universal property every such moment is a multiple of the least one, so we need $\operatorname{lcm}(12,18,30)$.',
                    r'Factor: $12=2^{2}\cdot3$, $18=2\cdot3^{2}$, $30=2\cdot3\cdot5$.',
                    r'Take each prime to its highest power: $2^{2}\cdot3^{2}\cdot5=180$.',
                    r'$180$ minutes is exactly three hours.']},
   'ans': {'ru': r'В $9{:}00$, и далее каждые три часа.',
           'en': r'At $9{:}00$, and every three hours after that.'}},
  {'t': 'note',
   'text': {'ru': r'Для трёх и более чисел формулы через показатели по-прежнему работают: $$\gcd=\prod p^{\min},\qquad \operatorname{lcm}=\prod p^{\max},$$ где минимум и максимум берутся по всем числам набора. А вот тождество $\gcd\cdot\operatorname{lcm}=$ произведение остаётся верным только для **двух** чисел.',
            'en': r'For three or more numbers the exponent formulas still hold: $$\gcd=\prod p^{\min},\qquad \operatorname{lcm}=\prod p^{\max},$$ with the minimum and maximum over the whole list. The identity $\gcd\cdot\operatorname{lcm}=$ product, however, survives only for **two** numbers.'}},
 ],

 # ---- 5: Counting divisors
 5: [
  {'t': 'def',
   'name': {'ru': 'Мультипликативная функция', 'en': 'Multiplicative function'},
   'text': {'ru': r'Функция $f$, определённая на натуральных числах, называется **мультипликативной**, если $f(1)=1$ и $$f(mn)=f(m)f(n)\quad\text{для всех взаимно простых } m,n .$$',
            'en': r'A function $f$ on the positive integers is **multiplicative** if $f(1)=1$ and $$f(mn)=f(m)f(n)\quad\text{for all coprime } m,n .$$'}},
  {'t': 'thm',
   'name': {'ru': 'Мультипликативность $d$ и $\sigma$', 'en': 'Multiplicativity of $d$ and $\sigma$'},
   'text': {'ru': r'Функции $d(n)$ (число делителей) и $\sigma(n)$ (их сумма) мультипликативны: при $\gcd(m,n)=1$ $$d(mn)=d(m)\,d(n),\qquad \sigma(mn)=\sigma(m)\,\sigma(n).$$',
            'en': r'The functions $d(n)$ (number of divisors) and $\sigma(n)$ (their sum) are multiplicative: for $\gcd(m,n)=1$ $$d(mn)=d(m)\,d(n),\qquad \sigma(mn)=\sigma(m)\,\sigma(n).$$'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть $\gcd(m,n)=1$. Ключевое наблюдение: делители произведения $mn$ находятся во взаимно однозначном соответствии с **парами** делителей $$e\mid m,\qquad f\mid n ,$$ причём соответствие задаётся произведением $e f$.\n\n**Почему это биекция.** Каждая пара даёт делитель $ef$ числа $mn$ — это очевидно. Обратно, пусть $g\mid mn$; положим $$e=\gcd(g,m),\qquad f=\gcd(g,n).$$ Из взаимной простоты $m$ и $n$ следует (сравнением показателей простых), что $g=ef$, и такое представление единственно: каждое простое числа $g$ делит ровно одно из чисел $m$, $n$ и потому попадает целиком либо в $e$, либо в $f$.\n\n**Считаем.** Число пар равно $d(m)d(n)$, откуда первая формула. Сумма всех произведений равна $$\sum_{e\mid m}\ \sum_{f\mid n} ef=\left(\sum_{e\mid m}e\right)\left(\sum_{f\mid n}f\right)=\sigma(m)\sigma(n),$$ откуда вторая. $\blacksquare$',
            'en': r'Let $\gcd(m,n)=1$. The key observation is that the divisors of $mn$ correspond one-to-one with **pairs** of divisors $$e\mid m,\qquad f\mid n ,$$ the correspondence being $(e,f)\mapsto ef$.\n\n**Why it is a bijection.** Each pair clearly gives a divisor $ef$ of $mn$. Conversely, given $g\mid mn$ put $$e=\gcd(g,m),\qquad f=\gcd(g,n).$$ Coprimality of $m$ and $n$ shows (by comparing prime exponents) that $g=ef$, and the representation is unique: every prime of $g$ divides exactly one of $m$, $n$ and so lands entirely in $e$ or entirely in $f$.\n\n**Counting.** The number of pairs is $d(m)d(n)$, giving the first formula. The sum of all the products is $$\sum_{e\mid m}\ \sum_{f\mid n} ef=\left(\sum_{e\mid m}e\right)\left(\sum_{f\mid n}f\right)=\sigma(m)\sigma(n),$$ giving the second. $\blacksquare$'}},
  {'t': 'idea',
   'text': {'ru': r'Мультипликативность — причина, по которой формулы для $d(n)$ и $\sigma(n)$ выглядят как **произведения по простым**: достаточно понять функцию на степенях простых, а дальше она собирается сама.',
            'en': r'Multiplicativity is why the formulas for $d(n)$ and $\sigma(n)$ look like **products over primes**: understand the function on prime powers and it assembles itself.'}},
  {'t': 'thm',
   'name': {'ru': 'Произведение всех делителей', 'en': 'The product of all divisors'},
   'text': {'ru': r'Произведение всех натуральных делителей числа $n>1$ равно $$\prod_{e\mid n}e=n^{\,d(n)/2} .$$',
            'en': r'The product of all positive divisors of $n>1$ equals $$\prod_{e\mid n}e=n^{\,d(n)/2} .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Обозначим искомое произведение через $P$ и запишем его дважды — в возрастающем и в убывающем порядке делителей. Делители разбиваются на пары $\left(e,\ \tfrac ne\right)$, и произведение в каждой паре равно $n$.\n\nФормально: $$P^{2}=\prod_{e\mid n}e\ \cdot\ \prod_{e\mid n}\frac ne=\prod_{e\mid n}\left(e\cdot\frac ne\right)=n^{\,d(n)} ,$$ где мы воспользовались тем, что при пробегании $e$ по всем делителям величина $\tfrac ne$ тоже пробегает все делители.\n\nИзвлекая корень, получаем $P=n^{\,d(n)/2}$. $\blacksquare$\n\n**Заметьте:** показатель $\tfrac{d(n)}2$ может быть полуцелым — это происходит ровно тогда, когда $n$ полный квадрат, и тогда «непарным» остаётся делитель $\sqrt n$.',
            'en': r'Call the product $P$ and write it twice, once in increasing and once in decreasing order of divisors. The divisors pair up as $\left(e,\ \tfrac ne\right)$, each pair multiplying to $n$.\n\nFormally $$P^{2}=\prod_{e\mid n}e\ \cdot\ \prod_{e\mid n}\frac ne=\prod_{e\mid n}\left(e\cdot\frac ne\right)=n^{\,d(n)} ,$$ using that as $e$ runs over all divisors so does $\tfrac ne$.\n\nTaking square roots, $P=n^{\,d(n)/2}$. $\blacksquare$\n\n**Note:** the exponent $\tfrac{d(n)}2$ may be a half-integer — exactly when $n$ is a perfect square, in which case the unpaired divisor is $\sqrt n$.'}},
  {'t': 'ex',
   'q': {'ru': r'Найдите наименьшее натуральное число, имеющее ровно $10$ делителей.',
         'en': r'Find the smallest positive integer with exactly $10$ divisors.'},
   'steps': {'ru': [r'Если $n=\prod p_i^{\alpha_i}$, то $d(n)=\prod\left(\alpha_i+1\right)$, значит надо разложить $10$ в произведение множителей, больших единицы.',
                    r'Варианты: $10$ и $5\cdot2$.',
                    r'Разложению $10$ отвечают показатели $(9)$: наименьшее такое число $2^{9}=512$.',
                    r'Разложению $5\cdot2$ отвечают показатели $(4,1)$; бо́льший показатель ставим к меньшему простому: $2^{4}\cdot3=48$.',
                    r'Сравниваем: $48<512$.'],
             'en': [r'If $n=\prod p_i^{\alpha_i}$ then $d(n)=\prod\left(\alpha_i+1\right)$, so write $10$ as a product of factors greater than one.',
                    r'The options are $10$ and $5\cdot2$.',
                    r'The factorisation $10$ gives exponents $(9)$: the smallest such number is $2^{9}=512$.',
                    r'The factorisation $5\cdot2$ gives exponents $(4,1)$; put the larger exponent on the smaller prime: $2^{4}\cdot3=48$.',
                    r'Compare: $48<512$.']},
   'ans': {'ru': r'$48$; его делители $1,2,3,4,6,8,12,16,24,48$ — ровно десять.',
           'en': r'$48$; its divisors are $1,2,3,4,6,8,12,16,24,48$ — exactly ten.'}},
  {'t': 'note',
   'text': {'ru': r'Функция $\sigma$ стоит за старинным понятием: число называют **совершенным**, если $\sigma(n)=2n$, то есть оно равно сумме своих собственных делителей. Первые совершенные числа — $6$, $28$, $496$, $8128$; все чётные совершенные числа имеют вид $2^{p-1}\left(2^{p}-1\right)$ с простым $2^{p}-1$, а существуют ли нечётные — не известно до сих пор.',
            'en': r'The function $\sigma$ sits behind an ancient notion: $n$ is **perfect** if $\sigma(n)=2n$, i.e. it equals the sum of its proper divisors. The first perfect numbers are $6$, $28$, $496$, $8128$; every even perfect number has the form $2^{p-1}\left(2^{p}-1\right)$ with $2^{p}-1$ prime, and whether an odd one exists is still unknown.'}},
 ],
}


# --------------------------------------------------------------- more sections

TOTIENT = {
 'h': {'ru': 'Функция Эйлера и три классические теоремы',
       'en': 'Euler’s totient and three classical theorems'},
 'blocks': [

  {'t': 'p',
   'text': {'ru': r'До сих пор мы считали делители. Теперь посчитаем числа, **взаимно простые** с данным, — и обнаружим, что этот счёт управляет степенями по модулю $n$.',
            'en': r'So far we have counted divisors. Now we count the numbers **coprime** to a given one — and find that this count governs how powers behave modulo $n$.'}},

  {'t': 'def',
   'name': {'ru': 'Функция Эйлера', 'en': 'Euler’s totient function'},
   'text': {'ru': r'$\varphi(n)$ — количество чисел из набора $1,2,\dots,n$, взаимно простых с $n$. Например, $$\varphi(1)=1,\quad\varphi(6)=2\ (\text{это } 1,5),\quad\varphi(7)=6,\quad\varphi(12)=4\ (\text{это } 1,5,7,11).$$',
            'en': r'$\varphi(n)$ counts the numbers among $1,2,\dots,n$ that are coprime to $n$. For instance $$\varphi(1)=1,\quad\varphi(6)=2\ (\text{namely } 1,5),\quad\varphi(7)=6,\quad\varphi(12)=4\ (\text{namely } 1,5,7,11).$$'}},

  {'t': 'thm',
   'name': {'ru': 'Формула Эйлера', 'en': 'Euler’s product formula'},
   'text': {'ru': r'Если $n=p_1^{\alpha_1}\cdots p_k^{\alpha_k}$, то $$\varphi(n)=n\prod_{i=1}^{k}\left(1-\frac1{p_i}\right)=\prod_{i=1}^{k}p_i^{\alpha_i-1}\left(p_i-1\right).$$ В частности $\varphi(p)=p-1$ и $\varphi\left(p^{\alpha}\right)=p^{\alpha}-p^{\alpha-1}$ для простого $p$.',
            'en': r'If $n=p_1^{\alpha_1}\cdots p_k^{\alpha_k}$ then $$\varphi(n)=n\prod_{i=1}^{k}\left(1-\frac1{p_i}\right)=\prod_{i=1}^{k}p_i^{\alpha_i-1}\left(p_i-1\right).$$ In particular $\varphi(p)=p-1$ and $\varphi\left(p^{\alpha}\right)=p^{\alpha}-p^{\alpha-1}$ for a prime $p$.'}},

  {'t': 'proof',
   'text': {'ru': r'**Шаг 1: степень простого.** Среди чисел $1,\dots,p^{\alpha}$ не взаимно просты с $p^{\alpha}$ ровно кратные $p$, а их $p^{\alpha-1}$ штук. Значит $$\varphi\left(p^{\alpha}\right)=p^{\alpha}-p^{\alpha-1}=p^{\alpha}\left(1-\frac1p\right) \quad\checkmark$$\n\n**Шаг 2: мультипликативность.** Пусть $\gcd(m,n)=1$; докажем $\varphi(mn)=\varphi(m)\varphi(n)$. Выпишем числа $1,\dots,mn$ в таблицу из $m$ строк и $n$ столбцов, поставив число $x$ в клетку с координатами $\left(x\bmod m,\ x\bmod n\right)$. По китайской теореме об остатках это соответствие взаимно однозначно: каждая пара остатков встречается ровно один раз.\n\nЧисло $x$ взаимно просто с $mn$ тогда и только тогда, когда оно взаимно просто и с $m$, и с $n$, то есть когда **обе** его координаты взаимно просты со своими модулями. Первых координат подходит $\varphi(m)$, вторых $\varphi(n)$, и выбираются они независимо: $$\varphi(mn)=\varphi(m)\varphi(n) \quad\checkmark$$\n\n**Шаг 3: сборка.** Степени разных простых попарно взаимно просты, поэтому $$\varphi(n)=\prod_i\varphi\left(p_i^{\alpha_i}\right)=\prod_i p_i^{\alpha_i}\left(1-\frac1{p_i}\right)=n\prod_i\left(1-\frac1{p_i}\right). \qquad\blacksquare$$',
            'en': r'**Step 1: a prime power.** Among $1,\dots,p^{\alpha}$ the numbers *not* coprime to $p^{\alpha}$ are exactly the multiples of $p$, and there are $p^{\alpha-1}$ of them. Hence $$\varphi\left(p^{\alpha}\right)=p^{\alpha}-p^{\alpha-1}=p^{\alpha}\left(1-\frac1p\right) \quad\checkmark$$\n\n**Step 2: multiplicativity.** Let $\gcd(m,n)=1$; we show $\varphi(mn)=\varphi(m)\varphi(n)$. Arrange $1,\dots,mn$ in a table of $m$ rows and $n$ columns, placing $x$ at the cell $\left(x\bmod m,\ x\bmod n\right)$. By the Chinese remainder theorem this is a bijection: each pair of residues occurs exactly once.\n\nNow $x$ is coprime to $mn$ exactly when it is coprime to both $m$ and $n$, i.e. when **both** coordinates are coprime to their moduli. There are $\varphi(m)$ admissible first coordinates and $\varphi(n)$ second ones, chosen independently: $$\varphi(mn)=\varphi(m)\varphi(n) \quad\checkmark$$\n\n**Step 3: assembling.** Powers of distinct primes are pairwise coprime, so $$\varphi(n)=\prod_i\varphi\left(p_i^{\alpha_i}\right)=n\prod_i\left(1-\frac1{p_i}\right). \qquad\blacksquare$$'}},

  {'t': 'ex',
   'q': {'ru': r'Вычислите $\varphi(360)$.',
         'en': r'Compute $\varphi(360)$.'},
   'steps': {'ru': [r'$360=2^{3}\cdot3^{2}\cdot5$.',
                    r'По формуле $\varphi(360)=360\left(1-\tfrac12\right)\left(1-\tfrac13\right)\left(1-\tfrac15\right)$.',
                    r'Считаем: $360\cdot\tfrac12=180$, затем $180\cdot\tfrac23=120$, затем $120\cdot\tfrac45=96$.',
                    r'Проверка вторым видом формулы: $2^{2}\cdot1\ \cdot\ 3^{1}\cdot2\ \cdot\ 5^{0}\cdot4=4\cdot6\cdot4=96$ ✓'],
             'en': [r'$360=2^{3}\cdot3^{2}\cdot5$.',
                    r'The formula gives $\varphi(360)=360\left(1-\tfrac12\right)\left(1-\tfrac13\right)\left(1-\tfrac15\right)$.',
                    r'Step by step: $360\cdot\tfrac12=180$, then $180\cdot\tfrac23=120$, then $120\cdot\tfrac45=96$.',
                    r'Check with the other form: $2^{2}\cdot1\ \cdot\ 3^{1}\cdot2\ \cdot\ 5^{0}\cdot4=4\cdot6\cdot4=96$ ✓']},
   'ans': {'ru': r'$\varphi(360)=96$.', 'en': r'$\varphi(360)=96$.'}},

  {'t': 'thm',
   'name': {'ru': 'Свойства функции Эйлера', 'en': 'Properties of the totient'},
   'text': {'ru': r'(1) $\varphi(n)$ чётно при всех $n>2$; $\;$ (2) $\displaystyle\sum_{d\mid n}\varphi(d)=n$; $\;$ (3) $\varphi(mn)=\varphi(m)\varphi(n)$ при $\gcd(m,n)=1$.',
            'en': r'(1) $\varphi(n)$ is even for every $n>2$; $\;$ (2) $\displaystyle\sum_{d\mid n}\varphi(d)=n$; $\;$ (3) $\varphi(mn)=\varphi(m)\varphi(n)$ whenever $\gcd(m,n)=1$.'}},

  {'t': 'proof',
   'text': {'ru': r'**(1)** Если $n$ имеет нечётный простой делитель $p$, то множитель $p-1$ в формуле чётен, значит чётно и произведение. Иначе $n=2^{\alpha}$ с $\alpha\ge2$ (случай $n>2$), и $\varphi(n)=2^{\alpha-1}$ чётно ✓\n\n**(2)** Разобьём числа $1,2,\dots,n$ по значению $\gcd$ с $n$. Числа с $\gcd(x,n)=d$ — это в точности $x=d\,y$, где $1\le y\le\tfrac nd$ и $\gcd\left(y,\tfrac nd\right)=1$; таких $y$ ровно $\varphi\left(\tfrac nd\right)$.\n\nЗначит $$n=\sum_{d\mid n}\varphi\!\left(\frac nd\right)=\sum_{d\mid n}\varphi(d),$$ поскольку при пробегании $d$ по всем делителям величина $\tfrac nd$ тоже пробегает все делители ✓\n\n**(3)** Доказано выше при выводе формулы. $\blacksquare$',
            'en': r'**(1)** If $n$ has an odd prime divisor $p$, the factor $p-1$ in the formula is even, hence so is the product. Otherwise $n=2^{\alpha}$ with $\alpha\ge2$ (as $n>2$), and $\varphi(n)=2^{\alpha-1}$ is even ✓\n\n**(2)** Sort $1,2,\dots,n$ by the value of $\gcd$ with $n$. The numbers with $\gcd(x,n)=d$ are exactly $x=d\,y$ with $1\le y\le\tfrac nd$ and $\gcd\left(y,\tfrac nd\right)=1$; there are $\varphi\left(\tfrac nd\right)$ such $y$.\n\nHence $$n=\sum_{d\mid n}\varphi\!\left(\frac nd\right)=\sum_{d\mid n}\varphi(d),$$ since as $d$ runs over the divisors so does $\tfrac nd$ ✓\n\n**(3)** Proved above while deriving the formula. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Малая теорема Ферма', 'en': 'Fermat’s little theorem'},
   'text': {'ru': r'Если $p$ простое и $p\nmid a$, то $$a^{\,p-1}\equiv1\pmod p .$$ Без условия $p\nmid a$ верна форма $a^{p}\equiv a\pmod p$, справедливая для **всех** целых $a$.',
            'en': r'If $p$ is prime and $p\nmid a$ then $$a^{\,p-1}\equiv1\pmod p .$$ Without the hypothesis $p\nmid a$ the form $a^{p}\equiv a\pmod p$ holds for **every** integer $a$.'}},

  {'t': 'proof',
   'text': {'ru': r'Рассмотрим ненулевые остатки $1,2,\dots,p-1$ и умножим каждый на $a$.\n\n**Шаг 1: получается тот же набор.** Числа $a\cdot1,\ a\cdot2,\ \dots,\ a(p-1)$ дают попарно различные ненулевые остатки: если $ai\equiv aj$, то $p\mid a(i-j)$, а так как $p\nmid a$, по лемме Евклида $p\mid i-j$, откуда $i=j$ (ведь $|i-j|<p$). Нулевых остатков нет, потому что $p\nmid a$ и $p\nmid i$.\n\nЗначит эти $p-1$ чисел — те же остатки $1,\dots,p-1$, лишь переставленные.\n\n**Шаг 2: перемножаем.** $$a^{\,p-1}(p-1)!\ \equiv\ (p-1)!\pmod p .$$\n\n**Шаг 3: сокращаем.** Число $(p-1)!$ не делится на $p$ (все множители меньше $p$), поэтому на него можно сократить: $$a^{\,p-1}\equiv1\pmod p . \qquad\blacksquare$$',
            'en': r'Consider the non-zero residues $1,2,\dots,p-1$ and multiply each by $a$.\n\n**Step 1: the same set comes back.** The numbers $a\cdot1,\dots,a(p-1)$ leave pairwise distinct non-zero residues: if $ai\equiv aj$ then $p\mid a(i-j)$, and since $p\nmid a$ Euclid’s lemma gives $p\mid i-j$, so $i=j$ (as $|i-j|<p$). None is zero because $p\nmid a$ and $p\nmid i$.\n\nSo these $p-1$ numbers are the residues $1,\dots,p-1$ in some order.\n\n**Step 2: multiply them all.** $$a^{\,p-1}(p-1)!\ \equiv\ (p-1)!\pmod p .$$\n\n**Step 3: cancel.** Since $(p-1)!$ is not divisible by $p$ (all its factors are smaller), we may cancel it: $$a^{\,p-1}\equiv1\pmod p . \qquad\blacksquare$$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите остаток от деления $2^{1000}$ на $13$.',
         'en': r'Find the remainder of $2^{1000}$ on division by $13$.'},
   'steps': {'ru': [r'$13$ простое и $13\nmid2$, значит $2^{12}\equiv1\pmod{13}$.',
                    r'Поделим показатель на $12$ с остатком: $1000=12\cdot83+4$.',
                    r'Тогда $2^{1000}=\left(2^{12}\right)^{83}\cdot2^{4}\equiv2^{4}=16\equiv3\pmod{13}$.'],
             'en': [r'$13$ is prime and $13\nmid2$, so $2^{12}\equiv1\pmod{13}$.',
                    r'Divide the exponent by $12$: $1000=12\cdot83+4$.',
                    r'Then $2^{1000}=\left(2^{12}\right)^{83}\cdot2^{4}\equiv16\equiv3\pmod{13}$.']},
   'ans': {'ru': r'Остаток $3$.', 'en': r'The remainder is $3$.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Эйлера', 'en': 'Euler’s theorem'},
   'text': {'ru': r'Если $\gcd(a,n)=1$, то $$a^{\varphi(n)}\equiv1\pmod n .$$ При простом $n=p$ это в точности малая теорема Ферма, ведь $\varphi(p)=p-1$.',
            'en': r'If $\gcd(a,n)=1$ then $$a^{\varphi(n)}\equiv1\pmod n .$$ For a prime $n=p$ this is exactly Fermat’s little theorem, since $\varphi(p)=p-1$.'}},

  {'t': 'proof',
   'text': {'ru': r'Пусть $r_1,\dots,r_{\varphi(n)}$ — все остатки от $1$ до $n$, взаимно простые с $n$.\n\n**Шаг 1: умножение на $a$ переставляет их.** Каждое $ar_i$ взаимно просто с $n$ (общий простой делитель делил бы $a$ или $r_i$), и они попарно различны по модулю $n$: из $ar_i\equiv ar_j$ следует $n\mid a\left(r_i-r_j\right)$, а при $\gcd(a,n)=1$ отсюда $n\mid r_i-r_j$, то есть $r_i=r_j$.\n\nЗначит набор $ar_1,\dots,ar_{\varphi(n)}$ — тот же самый набор остатков, лишь переставленный.\n\n**Шаг 2: перемножаем и сокращаем.** $$a^{\varphi(n)}\prod_i r_i\ \equiv\ \prod_i r_i\pmod n ,$$ а произведение $\prod_i r_i$ взаимно просто с $n$, поэтому на него можно сократить: $$a^{\varphi(n)}\equiv1\pmod n . \qquad\blacksquare$$',
            'en': r'Let $r_1,\dots,r_{\varphi(n)}$ be the residues from $1$ to $n$ coprime to $n$.\n\n**Step 1: multiplying by $a$ permutes them.** Each $ar_i$ is coprime to $n$ (a common prime divisor would divide $a$ or $r_i$), and they are pairwise distinct mod $n$: from $ar_i\equiv ar_j$ we get $n\mid a\left(r_i-r_j\right)$, and $\gcd(a,n)=1$ gives $n\mid r_i-r_j$, i.e. $r_i=r_j$.\n\nSo $ar_1,\dots,ar_{\varphi(n)}$ is the same set of residues, permuted.\n\n**Step 2: multiply and cancel.** $$a^{\varphi(n)}\prod_i r_i\ \equiv\ \prod_i r_i\pmod n ,$$ and $\prod_i r_i$ is coprime to $n$, so it cancels: $$a^{\varphi(n)}\equiv1\pmod n . \qquad\blacksquare$$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите две последние цифры числа $7^{2024}$.',
         'en': r'Find the last two digits of $7^{2024}$.'},
   'steps': {'ru': [r'Две последние цифры — это остаток по модулю $100$.',
                    r'$\gcd(7,100)=1$, и $\varphi(100)=100\left(1-\tfrac12\right)\left(1-\tfrac15\right)=40$.',
                    r'По теореме Эйлера $7^{40}\equiv1\pmod{100}$.',
                    r'$2024=40\cdot50+24$, значит $7^{2024}\equiv7^{24}$.',
                    r'Считаем: $7^{2}=49$, $7^{4}=49^{2}=2401\equiv1\pmod{100}$.',
                    r'Значит $7^{24}=\left(7^{4}\right)^{6}\equiv1$.'],
             'en': [r'The last two digits are the remainder modulo $100$.',
                    r'$\gcd(7,100)=1$ and $\varphi(100)=100\left(1-\tfrac12\right)\left(1-\tfrac15\right)=40$.',
                    r'Euler’s theorem gives $7^{40}\equiv1\pmod{100}$.',
                    r'$2024=40\cdot50+24$, so $7^{2024}\equiv7^{24}$.',
                    r'Compute: $7^{2}=49$ and $7^{4}=2401\equiv1\pmod{100}$.',
                    r'Hence $7^{24}=\left(7^{4}\right)^{6}\equiv1$.']},
   'ans': {'ru': r'Оканчивается на $01$.', 'en': r'It ends in $01$.'}},

  {'t': 'note',
   'text': {'ru': r'Заметьте: настоящий порядок семёрки по модулю $100$ равен $4$, а не $40$. Теорема Эйлера даёт **верхнюю** оценку показателя, после которой степень «зацикливается»; истинный период всегда делит $\varphi(n)$, но может быть заметно меньше.',
            'en': r'Note that the true order of $7$ modulo $100$ is $4$, not $40$. Euler’s theorem gives an **upper bound** for the exponent after which powers repeat; the real period always divides $\varphi(n)$ but may be much smaller.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Вильсона', 'en': 'Wilson’s theorem'},
   'text': {'ru': r'Целое число $p>1$ простое **тогда и только тогда**, когда $$(p-1)!\ \equiv\ -1\pmod p .$$',
            'en': r'An integer $p>1$ is prime **if and only if** $$(p-1)!\ \equiv\ -1\pmod p .$$'}},

  {'t': 'proof',
   'text': {'ru': r'**Пусть $p$ простое.** При $p=2$ проверяем прямо: $1!\equiv-1\pmod2$ ✓ Пусть $p$ нечётно.\n\nУ каждого $a\in\{1,\dots,p-1\}$ есть единственное обратное $a^{-1}$ в том же наборе: по Безу найдутся $u,v$ с $ua+vp=1$, то есть $ua\equiv1$.\n\nКакие числа обратны сами себе? Условие $a^{2}\equiv1$ означает $p\mid(a-1)(a+1)$, откуда по лемме Евклида $a\equiv1$ или $a\equiv-1$, то есть $a=1$ или $a=p-1$.\n\nОстальные $p-3$ чисел разбиваются на $\tfrac{p-3}{2}$ пар $\left\{a,a^{-1}\right\}$ с произведением $1$. Поэтому $$(p-1)!\equiv1\cdot(p-1)\equiv-1\pmod p \quad\checkmark$$\n\n**Пусть $p$ составное,** $p=ab$ с $1<a<p$. Тогда $a$ входит множителем в $(p-1)!$, значит $a\mid(p-1)!$. Если бы выполнялось $(p-1)!\equiv-1\pmod p$, то $a$ делило бы и $(p-1)!+1$, а значит делило бы разность — единицу ✗ (Отдельный случай $p=4$ проверяется прямо: $3!=6\equiv2\pmod4$.) $\blacksquare$',
            'en': r'**Suppose $p$ is prime.** For $p=2$ check directly: $1!\equiv-1\pmod2$ ✓ Let $p$ be odd.\n\nEvery $a\in\{1,\dots,p-1\}$ has a unique inverse $a^{-1}$ in the same range: Bézout gives $u,v$ with $ua+vp=1$, i.e. $ua\equiv1$.\n\nWhich numbers are their own inverse? The condition $a^{2}\equiv1$ means $p\mid(a-1)(a+1)$, so Euclid’s lemma gives $a\equiv1$ or $a\equiv-1$, i.e. $a=1$ or $a=p-1$.\n\nThe remaining $p-3$ numbers split into $\tfrac{p-3}{2}$ pairs $\left\{a,a^{-1}\right\}$ with product $1$. Hence $$(p-1)!\equiv1\cdot(p-1)\equiv-1\pmod p \quad\checkmark$$\n\n**Suppose $p$ is composite,** $p=ab$ with $1<a<p$. Then $a$ is one of the factors of $(p-1)!$, so $a\mid(p-1)!$. If $(p-1)!\equiv-1\pmod p$ held, then $a$ would divide $(p-1)!+1$ too, hence their difference $1$ ✗ (The case $p=4$ is checked directly: $3!=6\equiv2\pmod4$.) $\blacksquare$'}},

  {'t': 'note',
   'text': {'ru': r'Теорема Вильсона — единственный из школьных признаков простоты, который является **критерием**: он и необходим, и достаточен. Практической пользы для проверки больших чисел от него нет (считать $(p-1)!$ дороже, чем перебрать делители), зато в задачах он бывает решающим.\n\n**Следствие.** При простом $p>2$ произведение $(p-2)!\equiv1\pmod p$, ведь $(p-1)!=(p-1)\cdot(p-2)!\equiv-(p-2)!$.',
            'en': r'Wilson’s theorem is the one elementary primality statement that is a genuine **criterion**: necessary and sufficient. It is useless for testing large numbers (computing $(p-1)!$ costs more than trial division), but in problems it is sometimes decisive.\n\n**Corollary.** For a prime $p>2$ we get $(p-2)!\equiv1\pmod p$, since $(p-1)!=(p-1)\cdot(p-2)!\equiv-(p-2)!$.'}},
 ],
}


ADVGCD = {
 'h': {'ru': 'Тождества с НОД, которые стоит знать',
       'en': 'GCD identities worth knowing'},
 'blocks': [

  {'t': 'p',
   'text': {'ru': r'Алгоритм Евклида работает не только с числами. Если последовательность устроена «как повторное вычитание», её НОД тоже подчиняется алгоритму Евклида — но уже на уровне **индексов**.',
            'en': r'The Euclidean algorithm is not confined to plain numbers. When a sequence behaves like repeated subtraction, its gcd obeys the Euclidean algorithm too — but on the level of **indices**.'}},

  {'t': 'thm',
   'name': {'ru': 'НОД чисел Мерсенна', 'en': 'The gcd of Mersenne numbers'},
   'text': {'ru': r'Для любых натуральных $m,n$ и любого целого $a>1$ $$\gcd\left(a^{m}-1,\ a^{n}-1\right)=a^{\gcd(m,n)}-1 .$$',
            'en': r'For all positive integers $m,n$ and any integer $a>1$ $$\gcd\left(a^{m}-1,\ a^{n}-1\right)=a^{\gcd(m,n)}-1 .$$'}},

  {'t': 'proof',
   'text': {'ru': r'Пусть $m>n$ и $m=nq+r$ — деление с остатком. Ключевое тождество: $$a^{m}-1=a^{\,m-n}\left(a^{n}-1\right)+\left(a^{\,m-n}-1\right).$$\n\nОно означает, что при вычислении НОД показатель можно уменьшать на $n$, не меняя ответа: $$\gcd\left(a^{m}-1,\ a^{n}-1\right)=\gcd\left(a^{\,m-n}-1,\ a^{n}-1\right).$$\n\nПовторяя этот шаг $q$ раз, приходим к $$\gcd\left(a^{r}-1,\ a^{n}-1\right),$$ то есть показатели ведут себя ровно как числа в алгоритме Евклида: $(m,n)\to(n,r)$.\n\nАлгоритм заканчивается, когда один из показателей обращается в нуль, а второй равен $\gcd(m,n)$; при этом $a^{0}-1=0$, и $$\gcd\left(a^{\gcd(m,n)}-1,\ 0\right)=a^{\gcd(m,n)}-1 . \qquad\blacksquare$$',
            'en': r'Let $m>n$ and let $m=nq+r$ be division with remainder. The key identity is $$a^{m}-1=a^{\,m-n}\left(a^{n}-1\right)+\left(a^{\,m-n}-1\right).$$\n\nIt says the exponent may be lowered by $n$ without changing the gcd: $$\gcd\left(a^{m}-1,\ a^{n}-1\right)=\gcd\left(a^{\,m-n}-1,\ a^{n}-1\right).$$\n\nRepeating $q$ times leads to $$\gcd\left(a^{r}-1,\ a^{n}-1\right),$$ so the exponents behave exactly like the numbers in the Euclidean algorithm: $(m,n)\to(n,r)$.\n\nThe algorithm stops when one exponent hits zero and the other equals $\gcd(m,n)$; since $a^{0}-1=0$, $$\gcd\left(a^{\gcd(m,n)}-1,\ 0\right)=a^{\gcd(m,n)}-1 . \qquad\blacksquare$$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите $\gcd\left(2^{30}-1,\ 2^{24}-1\right)$.',
         'en': r'Find $\gcd\left(2^{30}-1,\ 2^{24}-1\right)$.'},
   'steps': {'ru': [r'По теореме ответ равен $2^{\gcd(30,24)}-1$.',
                    r'$\gcd(30,24)=6$.',
                    r'Значит $\gcd=2^{6}-1=63$.',
                    r'Проверка: $2^{30}-1=1\,073\,741\,823=63\cdot17\,043\,521$ ✓'],
             'en': [r'The theorem gives $2^{\gcd(30,24)}-1$.',
                    r'$\gcd(30,24)=6$.',
                    r'So the gcd is $2^{6}-1=63$.',
                    r'Check: $2^{30}-1=1\,073\,741\,823=63\cdot17\,043\,521$ ✓']},
   'ans': {'ru': r'$63$.', 'en': r'$63$.'}},

  {'t': 'thm',
   'name': {'ru': 'НОД чисел Фибоначчи', 'en': 'The gcd of Fibonacci numbers'},
   'text': {'ru': r'Для чисел Фибоначчи $F_1=F_2=1$, $F_{k+1}=F_k+F_{k-1}$ выполняется $$\gcd\left(F_m,F_n\right)=F_{\gcd(m,n)} .$$',
            'en': r'For the Fibonacci numbers $F_1=F_2=1$, $F_{k+1}=F_k+F_{k-1}$, $$\gcd\left(F_m,F_n\right)=F_{\gcd(m,n)} .$$'}},

  {'t': 'proof',
   'text': {'ru': r'**Шаг 1: соседние числа Фибоначчи взаимно просты.** Из $F_{k+1}=F_k+F_{k-1}$ следует $\gcd\left(F_{k+1},F_k\right)=\gcd\left(F_k,F_{k-1}\right)$, и спускаясь до начала, получаем $\gcd\left(F_2,F_1\right)=1$.\n\n**Шаг 2: формула сложения.** Индукцией по $n$ проверяется тождество $$F_{m+n}=F_mF_{n+1}+F_{m-1}F_n .$$\n\n**Шаг 3: шаг алгоритма Евклида.** Возьмём $m>n$ и применим формулу к $F_m=F_{(m-n)+n}$: $$F_m=F_{m-n}F_{n+1}+F_{m-n-1}F_n .$$\n\nВторое слагаемое кратно $F_n$, поэтому $$\gcd\left(F_m,F_n\right)=\gcd\left(F_{m-n}F_{n+1},\ F_n\right).$$\n\nПо шагу 1 числа $F_{n+1}$ и $F_n$ взаимно просты, значит множитель $F_{n+1}$ можно выбросить: $$\gcd\left(F_m,F_n\right)=\gcd\left(F_{m-n},\ F_n\right).$$\n\n**Шаг 4: спуск.** Индексы ведут себя как числа в алгоритме Евклида, поэтому процесс приводит к паре $\left(F_{\gcd(m,n)},\ F_0\right)$, где $F_0=0$, и ответ равен $F_{\gcd(m,n)}$. $\blacksquare$',
            'en': r'**Step 1: consecutive Fibonacci numbers are coprime.** From $F_{k+1}=F_k+F_{k-1}$ we get $\gcd\left(F_{k+1},F_k\right)=\gcd\left(F_k,F_{k-1}\right)$, and descending to the start gives $\gcd\left(F_2,F_1\right)=1$.\n\n**Step 2: the addition formula.** Induction on $n$ verifies $$F_{m+n}=F_mF_{n+1}+F_{m-1}F_n .$$\n\n**Step 3: one Euclidean step.** Take $m>n$ and apply the formula to $F_m=F_{(m-n)+n}$: $$F_m=F_{m-n}F_{n+1}+F_{m-n-1}F_n .$$\n\nThe second term is a multiple of $F_n$, so $$\gcd\left(F_m,F_n\right)=\gcd\left(F_{m-n}F_{n+1},\ F_n\right).$$\n\nBy Step 1 the numbers $F_{n+1}$ and $F_n$ are coprime, so the factor $F_{n+1}$ may be dropped: $$\gcd\left(F_m,F_n\right)=\gcd\left(F_{m-n},\ F_n\right).$$\n\n**Step 4: descent.** The indices now behave exactly like numbers in the Euclidean algorithm, so the process reaches the pair $\left(F_{\gcd(m,n)},\ F_0\right)$ with $F_0=0$, and the answer is $F_{\gcd(m,n)}$. $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите $\gcd\left(F_{12},F_{18}\right)$.',
         'en': r'Find $\gcd\left(F_{12},F_{18}\right)$.'},
   'steps': {'ru': [r'$\gcd(12,18)=6$, значит ответ равен $F_6$.',
                    r'Выпишем: $F_1=1$, $F_2=1$, $F_3=2$, $F_4=3$, $F_5=5$, $F_6=8$.',
                    r'Проверка: $F_{12}=144$, $F_{18}=2584$, и $\gcd(144,2584)=8$ ✓'],
             'en': [r'$\gcd(12,18)=6$, so the answer is $F_6$.',
                    r'List them: $F_1=1$, $F_2=1$, $F_3=2$, $F_4=3$, $F_5=5$, $F_6=8$.',
                    r'Check: $F_{12}=144$, $F_{18}=2584$, and $\gcd(144,2584)=8$ ✓']},
   'ans': {'ru': r'$F_6=8$.', 'en': r'$F_6=8$.'}},

  {'t': 'idea',
   'text': {'ru': r'Обе теоремы устроены одинаково: находим тождество, позволяющее заменить пару $(m,n)$ на $(m-n,\ n)$, и запускаем алгоритм Евклида по индексам. Этот приём переносится на многие последовательности — важно лишь, чтобы «соседние» члены были взаимно просты.',
            'en': r'Both theorems work the same way: find an identity that replaces the pair $(m,n)$ by $(m-n,\ n)$, then run the Euclidean algorithm on the indices. The trick transfers to many sequences — all that is needed is that neighbouring terms be coprime.'}},

  {'t': 'note',
   'text': {'ru': r'Из первой теоремы получается изящное следствие: **$a^{m}-1$ делится на $a^{n}-1$ тогда и только тогда, когда $m$ делится на $n$.** Именно поэтому число $2^{p}-1$ может быть простым только при простом $p$ — это первый шаг в теории чисел Мерсенна.',
            'en': r'The first theorem has an elegant corollary: **$a^{m}-1$ is divisible by $a^{n}-1$ exactly when $m$ is divisible by $n$.** That is why $2^{p}-1$ can be prime only for prime $p$ — the first step in the theory of Mersenne numbers.'}},
 ],
}

SECTIONS = SECTIONS + [(6, TOTIENT), (6, ADVGCD)]
