# -*- coding: utf-8 -*-
"""Topic 15 — deeper theory, woven into lesson_15.py by content/build.py."""

QUANTIFIERS = {
 'h': {'ru': 'Кванторы, обращение и противоположное',
       'en': 'Quantifiers, converses and contrapositives'},
 'blocks': [
  {'t': 'def',
   'name': {'ru': 'Кванторы', 'en': 'Quantifiers'},
   'text': {'ru': r'Запись $\forall x\ P(x)$ читается «для всех $x$ верно $P(x)$», а $\exists x\ P(x)$ — «существует $x$, для которого верно $P(x)$». Первое утверждение опровергается **одним** контрпримером; второе доказывается **одним** примером.',
            'en': r'The expression $\forall x\ P(x)$ reads "for every $x$, $P(x)$ holds", and $\exists x\ P(x)$ reads "there exists an $x$ with $P(x)$". The first is refuted by **one** counterexample; the second is proved by **one** example.'}},
  {'t': 'thm',
   'name': {'ru': 'Отрицание кванторов', 'en': 'Negating quantifiers'},
   'text': {'ru': r'$$\overline{\forall x\ P(x)}\ =\ \exists x\ \overline{P(x)},\qquad \overline{\exists x\ P(x)}\ =\ \forall x\ \overline{P(x)} .$$ При отрицании каждый квантор меняется на противоположный, а внутреннее утверждение отрицается.',
            'en': r'$$\overline{\forall x\ P(x)}\ =\ \exists x\ \overline{P(x)},\qquad \overline{\exists x\ P(x)}\ =\ \forall x\ \overline{P(x)} .$$ Under negation each quantifier flips and the inner statement is negated.'}},
  {'t': 'proof',
   'text': {'ru': r'Утверждение «$P(x)$ верно для всех $x$» ложно ровно тогда, когда хотя бы для одного $x$ оно нарушено — а это и есть $\exists x\ \overline{P(x)}$ ✓\n\nСимметрично: «существует $x$ с $P(x)$» ложно ровно тогда, когда ни для какого $x$ это не выполняется, то есть $P(x)$ ложно для всех $x$ ✓ $\blacksquare$\n\n**Пример разбора.** Отрицание фразы «в каждом классе есть отличник» — не «в каждом классе нет отличника», а «найдётся класс, в котором нет ни одного отличника». Ошибка в отрицании — самая частая причина неверного доказательства от противного.',
            'en': r'"$P(x)$ holds for every $x$" is false exactly when it fails for at least one $x$ — which is $\exists x\ \overline{P(x)}$ ✓\n\nSymmetrically, "there exists an $x$ with $P(x)$" is false exactly when no $x$ works, i.e. $P(x)$ is false for every $x$ ✓ $\blacksquare$\n\n**A worked negation.** The negation of "every class has a top pupil" is not "every class has no top pupil" but "there is a class with no top pupil at all". A botched negation is the commonest cause of a broken proof by contradiction.'}},

  {'t': 'thm',
   'name': {'ru': 'Обратное, противоположное и противоположное обратному',
            'en': 'Converse, inverse and contrapositive'},
   'text': {'ru': r'Пусть дана импликация $A\Rightarrow B$. Тогда\n\n- **обратная** к ней — это $B\Rightarrow A$;\n- **противоположная** — $\overline{A}\Rightarrow\overline{B}$;\n- **противоположная обратной** (контрапозиция) — $\overline{B}\Rightarrow\overline{A}$.\n\nИмпликация **равносильна** своей контрапозиции, но **не равносильна** ни обратной, ни противоположной.',
            'en': r'Given an implication $A\Rightarrow B$,\n\n- its **converse** is $B\Rightarrow A$;\n- its **inverse** is $\overline{A}\Rightarrow\overline{B}$;\n- its **contrapositive** is $\overline{B}\Rightarrow\overline{A}$.\n\nAn implication is **equivalent** to its contrapositive, but **not** to its converse or its inverse.'}},
  {'t': 'proof',
   'text': {'ru': r'Импликация $A\Rightarrow B$ ложна ровно в одном случае: когда $A$ истинно, а $B$ ложно. Контрапозиция $\overline{B}\Rightarrow\overline{A}$ ложна ровно тогда, когда $\overline{B}$ истинно, а $\overline{A}$ ложно — то есть когда $B$ ложно, а $A$ истинно. Условия ложности совпадают, значит совпадают и сами утверждения ✓\n\n**Почему обратная не равносильна.** Контрпример: «если число делится на $4$, то оно чётно» — верно; обратное «если число чётно, то оно делится на $4$» — неверно ($6$) ✓ $\blacksquare$',
            'en': r'The implication $A\Rightarrow B$ is false in exactly one case: $A$ true and $B$ false. The contrapositive $\overline{B}\Rightarrow\overline{A}$ is false exactly when $\overline{B}$ is true and $\overline{A}$ is false — that is, $B$ false and $A$ true. The falsity conditions agree, so the statements agree ✓\n\n**Why the converse differs.** "If a number is divisible by $4$ then it is even" is true; its converse "if a number is even then it is divisible by $4$" is false (take $6$) ✓ $\blacksquare$'}},
  {'t': 'table',
   'head': {'ru': ['Формулировка', 'Что означает'],
            'en': ['Phrasing', 'What it means']},
   'rows': {'ru': [['$A$ — достаточное условие для $B$', r'$A\Rightarrow B$'],
                   ['$A$ — необходимое условие для $B$', r'$B\Rightarrow A$'],
                   ['$A$ необходимо и достаточно для $B$', r'$A\Leftrightarrow B$'],
                   ['$A$ верно только если $B$', r'$A\Rightarrow B$'],
                   ['$A$ верно тогда и только тогда, когда $B$', r'$A\Leftrightarrow B$']],
            'en': [['$A$ is sufficient for $B$', r'$A\Rightarrow B$'],
                   ['$A$ is necessary for $B$', r'$B\Rightarrow A$'],
                   ['$A$ is necessary and sufficient for $B$', r'$A\Leftrightarrow B$'],
                   ['$A$ holds only if $B$', r'$A\Rightarrow B$'],
                   ['$A$ holds if and only if $B$', r'$A\Leftrightarrow B$']]}},
  {'t': 'warn',
   'text': {'ru': r'Доказательство равносильности $A\Leftrightarrow B$ — это **два** доказательства: $A\Rightarrow B$ и $B\Rightarrow A$. Пропуск одной из половин — самая частая потеря баллов на олимпиаде. Слова «очевидно, верно и обратное» баллов не приносят.',
            'en': r'Proving an equivalence $A\Leftrightarrow B$ means **two** proofs: $A\Rightarrow B$ and $B\Rightarrow A$. Omitting one half is the commonest way to lose marks. The phrase "the converse is obvious" earns nothing.'}},

  {'t': 'thm',
   'name': {'ru': 'Принцип наименьшего числа и бесконечный спуск',
            'en': 'The least element principle and infinite descent'},
   'text': {'ru': r'Всякое непустое множество натуральных чисел содержит наименьший элемент. Следствие (**метод бесконечного спуска**): если из существования решения в натуральных числах следует существование строго меньшего решения, то решений нет вовсе.',
            'en': r'Every non-empty set of positive integers has a least element. Consequence (**infinite descent**): if the existence of a solution in positive integers forces the existence of a strictly smaller one, then no solution exists at all.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть решения существуют. Тогда множество их «размеров» (например, значений одной из переменных) — непустое множество натуральных чисел, значит в нём есть наименьший элемент $m$.\n\nВозьмём решение размера $m$. По условию из него строится решение строго меньшего размера — но это противоречит минимальности $m$ ✓ Значит решений нет $\blacksquare$\n\n**Пример: иррациональность $\sqrt2$ спуском.** Пусть $\sqrt2=\dfrac{p}{q}$ с натуральными $p,q$, и пусть $q$ **наименьшее** возможное. Из $p^{2}=2q^{2}$ следует, что $p$ чётно, $p=2k$, тогда $q^{2}=2k^{2}$, значит и $q$ чётно. Но тогда $$\sqrt2=\frac{p/2}{q/2}$$ — представление с меньшим знаменателем, противоречие с минимальностью ✓',
            'en': r'Suppose solutions exist. Then the set of their "sizes" (say the values of one variable) is a non-empty set of positive integers and has a least element $m$.\n\nTake a solution of size $m$. By hypothesis it produces a solution of strictly smaller size — contradicting the minimality of $m$ ✓ So no solution exists $\blacksquare$\n\n**Example: the irrationality of $\sqrt2$ by descent.** Let $\sqrt2=\dfrac{p}{q}$ in positive integers with $q$ **as small as possible**. From $p^{2}=2q^{2}$ the number $p$ is even, $p=2k$, whence $q^{2}=2k^{2}$ and $q$ is even too. But then $$\sqrt2=\frac{p/2}{q/2}$$ has a smaller denominator, contradicting minimality ✓'}},
 ],
}

MONOVARIANT = {
 'h': {'ru': 'Монотонные величины и принцип крайнего',
       'en': 'Monovariants and the extremal principle'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Инвариант отвечает на вопрос «может ли процесс привести к такому состоянию». Монотонная величина отвечает на другой: «закончится ли процесс вообще». Это два разных инструмента, и их часто путают.',
            'en': r'An invariant answers "can the process reach this state". A monovariant answers a different question: "does the process end at all". They are two distinct tools and are often confused.'}},

  {'t': 'def',
   'name': {'ru': 'Монотонная величина (полуинвариант)',
            'en': 'A monovariant (semi-invariant)'},
   'text': {'ru': r'**Монотонной величиной** процесса называют функцию состояния, которая при каждом шаге строго убывает (или строго возрастает).',
            'en': r'A **monovariant** of a process is a function of the state that strictly decreases (or strictly increases) at every step.'}},
  {'t': 'thm',
   'name': {'ru': 'Принцип завершения процесса', 'en': 'The termination principle'},
   'text': {'ru': r'Если у процесса есть монотонная величина, принимающая только **натуральные** значения (или, шире, значения из множества, ограниченного снизу и не имеющего бесконечных убывающих цепочек), то процесс обрывается через конечное число шагов.',
            'en': r'If a process has a monovariant taking only **positive integer** values (or, more generally, values in a set bounded below with no infinite decreasing chains), then the process stops after finitely many steps.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть процесс бесконечен, и пусть $f_1>f_2>f_3>\dots$ — значения монотонной величины на его шагах. Это бесконечная строго убывающая последовательность натуральных чисел.\n\nМножество её членов непусто, значит по принципу наименьшего числа в нём есть минимальный элемент $f_m$. Но по условию $f_{m+1}<f_m$, и $f_{m+1}$ тоже принадлежит множеству — противоречие с минимальностью ✓ $\blacksquare$\n\nИначе говоря: спускаться по натуральным числам бесконечно нельзя, и в этом вся суть.',
            'en': r'Suppose the process never stops, and let $f_1>f_2>f_3>\dots$ be the values of the monovariant along it: an infinite strictly decreasing sequence of positive integers.\n\nThe set of its terms is non-empty, so by the least element principle it has a minimum $f_m$. But $f_{m+1}<f_m$ and $f_{m+1}$ is also in the set — contradicting minimality ✓ $\blacksquare$\n\nIn other words: you cannot descend through the positive integers forever, and that is the whole idea.'}},

  {'t': 'ex',
   'q': {'ru': r'На доске написаны числа $1,2,\dots,n$. За ход разрешается стереть любые два числа $a$ и $b$ и записать вместо них $\left|a-b\right|$. Докажите, что процесс закончится, и определите чётность последнего числа.',
         'en': r'The numbers $1,2,\dots,n$ are on a board. A move erases any two of them, $a$ and $b$, and writes $\left|a-b\right|$ instead. Prove that the process terminates and determine the parity of the final number.'},
   'steps': {'ru': [r'**Завершение.** Монотонная величина — количество чисел на доске: каждый ход уменьшает его ровно на $1$. Это натуральное число, значит через $n-1$ ход останется одно число ✓',
                    r'**Инвариант.** Рассмотрим чётность суммы всех чисел. Замена $a,b\to\left|a-b\right|$ меняет сумму на $$a+b-\left|a-b\right|=2\min\left(a,b\right),$$ то есть на чётное число. Значит чётность суммы — инвариант ✓',
                    r'Изначально сумма равна $\dfrac{n\left(n+1\right)}{2}$.',
                    r'Значит последнее число имеет ту же чётность, что и $\dfrac{n\left(n+1\right)}{2}$. Например, при $n=10$ сумма равна $55$ — нечётна, поэтому останется нечётное число.',
                    r'Обратите внимание: **две разные величины** ответили на два разных вопроса — одна на «закончится ли», другая на «чем закончится».'],
             'en': [r'**Termination.** The monovariant is the count of numbers on the board: each move lowers it by exactly $1$. It is a positive integer, so after $n-1$ moves one number remains ✓',
                    r'**The invariant.** Consider the parity of the total. Replacing $a,b$ by $\left|a-b\right|$ changes the total by $$a+b-\left|a-b\right|=2\min\left(a,b\right),$$ an even amount. So the parity of the total is invariant ✓',
                    r'Initially the total is $\dfrac{n\left(n+1\right)}{2}$.',
                    r'So the final number has the same parity as $\dfrac{n\left(n+1\right)}{2}$. For $n=10$ the total is $55$, odd, so an odd number remains.',
                    r'Note how **two different quantities** answered two different questions — one "does it end", the other "how does it end".']},
   'ans': {'ru': r'Процесс из $n-1$ хода; последнее число имеет чётность числа $\dfrac{n\left(n+1\right)}{2}$.',
           'en': r'The process takes $n-1$ moves; the last number has the parity of $\dfrac{n\left(n+1\right)}{2}$.'}},

  {'t': 'thm',
   'name': {'ru': 'Принцип крайнего', 'en': 'The extremal principle'},
   'text': {'ru': r'В любом конечном непустом множестве чисел (отрезков, треугольников, конфигураций) существует наибольший и наименьший элемент. Рассмотрение именно такого, крайнего, объекта часто мгновенно решает задачу.',
            'en': r'Every finite non-empty set of numbers (segments, triangles, configurations) has a largest and a smallest element. Looking at that extremal object often settles a problem at once.'}},
  {'t': 'ex',
   'q': {'ru': r'На плоскости отмечено конечное число точек, не все на одной прямой. Докажите, что найдётся прямая, проходящая ровно через две из них (теорема Сильвестра–Галлаи).',
         'en': r'Finitely many points in the plane are not all collinear. Prove that some line passes through exactly two of them (the theorem of Sylvester and Gallai).'},
   'steps': {'ru': [r'Рассмотрим все пары «точка $P$ и прямая $\ell$ через хотя бы две отмеченные точки», для которых $P$ **не** лежит на $\ell$. Таких пар конечное число, и хотя бы одна существует (точки не все на одной прямой).',
                    r'**Крайний объект.** Выберем пару $\left(P,\ell\right)$ с **наименьшим** расстоянием от $P$ до $\ell$.',
                    r'Докажем, что на $\ell$ ровно две отмеченные точки. Предположим, их хотя бы три: $A$, $B$, $C$.',
                    r'Опустим перпендикуляр $PH$ на $\ell$. Две из трёх точек лежат по одну сторону от $H$ (или одна совпадает с $H$) — скажем, $B$ и $C$, причём $B$ ближе к $H$.',
                    r'Рассмотрим новую пару: точку $B$ и прямую $PC$. Расстояние от $B$ до прямой $PC$ **строго меньше**, чем расстояние от $P$ до $\ell$: это видно из подобия треугольников, отсекаемых перпендикулярами, поскольку $B$ лежит внутри треугольника $PHC$ или на его стороне $HC$.',
                    r'Получено противоречие с минимальностью выбранной пары ✓ Значит на $\ell$ ровно две точки $\blacksquare$'],
             'en': [r'Consider all pairs "a point $P$ and a line $\ell$ through at least two marked points" with $P$ **not** on $\ell$. There are finitely many such pairs, and at least one exists (the points are not all collinear).',
                    r'**The extremal object.** Choose the pair $\left(P,\ell\right)$ with the **smallest** distance from $P$ to $\ell$.',
                    r'We claim $\ell$ carries exactly two marked points. Suppose it carries at least three: $A$, $B$, $C$.',
                    r'Drop the perpendicular $PH$ to $\ell$. Two of the three points lie on the same side of $H$ (or one coincides with $H$) — say $B$ and $C$, with $B$ nearer to $H$.',
                    r'Look at the new pair: the point $B$ and the line $PC$. The distance from $B$ to $PC$ is **strictly smaller** than that from $P$ to $\ell$, as the similar triangles cut off by the perpendiculars show, because $B$ lies inside the triangle $PHC$ or on its side $HC$.',
                    r'This contradicts the minimality of our pair ✓ So $\ell$ carries exactly two points $\blacksquare$']},
   'ans': {'ru': r'Прямая, реализующая минимальное расстояние, содержит ровно две точки.',
           'en': r'The line realising the minimal distance carries exactly two points.'}},
  {'t': 'idea',
   'text': {'ru': r'**Как искать крайний объект.** Спросите себя: какую величину в задаче можно измерить числом? Наибольшая сторона, наименьший угол, самая длинная цепочка, максимальное число рёбер, минимальный контрпример. Затем предположите, что искомого свойства нет, и постройте объект «ещё более крайний» — противоречие получено.',
            'en': r'**How to find the extremal object.** Ask what quantity in the problem can be measured by a number: the longest side, the smallest angle, the longest chain, the largest number of edges, the minimal counterexample. Then assume the desired property fails and build an object that is "even more extreme" — the contradiction is there.'}},

  {'t': 'thm',
   'name': {'ru': 'Раскраска как инвариант', 'en': 'Colouring as an invariant'},
   'text': {'ru': r'Если каждому объекту приписан «вес» (число или цвет) так, что любой разрешённый ход сохраняет суммарный вес, то состояния с разными суммарными весами недостижимы одно из другого.',
            'en': r'If each object carries a "weight" (a number or a colour) in such a way that every legal move preserves the total weight, then states with different total weights are unreachable from one another.'}},
  {'t': 'idea',
   'text': {'ru': r'**Как придумать раскраску.** Она должна быть согласована с формой хода.\n\n- Ход меняет позицию на соседнюю клетку → шахматная раскраска в два цвета.\n- Фигура покрывает $3$ клетки в ряд → раскраска в три цвета по диагоналям или по столбцам ($1,2,3,1,2,3,\dots$).\n- Фигура — прямоугольник $1\times k$ → раскраска в $k$ цветов.\n- Ход прибавляет одно и то же число → работает не цвет, а остаток.\n- Нужно доказать невозможность замощения → приписывайте клеткам **числа**, а не цвета: вес фигуры должен быть один и тот же, где бы она ни лежала, а вес всей доски — другим.\n\nПравило проверки: **каждая** фигура при **любом** положении должна накрывать один и тот же набор весов. Если это не так — раскраска подобрана неудачно.',
            'en': r'**How to invent a colouring.** It must match the shape of the move.\n\n- The move goes to an adjacent square → the two-colour chessboard pattern.\n- A piece covers $3$ squares in a row → three colours along diagonals or columns ($1,2,3,1,2,3,\dots$).\n- The piece is a $1\times k$ rectangle → $k$ colours.\n- The move adds a fixed number → not a colour but a remainder is what works.\n- To prove a tiling impossible → give the squares **numbers** rather than colours: every placement of a piece should have the same weight, while the whole board has a different one.\n\nThe test: **every** piece in **every** position must cover the same multiset of weights. If not, the colouring is the wrong one.'}},
 ],
}

SECTIONS = [(1, QUANTIFIERS), (4, MONOVARIANT)]

INTO = {
 2: [
  {'t': 'thm',
   'name': {'ru': 'Варианты индукции', 'en': 'Variants of induction'},
   'text': {'ru': r'Все три схемы ниже равносильны обычной индукции и часто удобнее её.\n\n- **Сильная индукция:** если $P(1)$ верно и из истинности $P(1),\dots,P(k)$ следует $P(k+1)$, то $P(n)$ верно всегда.\n- **Индукция с базой $n_0$:** если $P(n_0)$ верно и $P(k)\Rightarrow P(k+1)$ при $k\ge n_0$, то $P(n)$ верно при всех $n\ge n_0$.\n- **Индукция с шагом назад (индукция Коши):** если утверждение верно для бесконечно многих $n$ и из $P(k)$ следует $P(k-1)$, то оно верно для всех $n$.',
            'en': r'All three schemes below are equivalent to ordinary induction and are often more convenient.\n\n- **Strong induction:** if $P(1)$ holds and $P(1),\dots,P(k)$ together imply $P(k+1)$, then $P(n)$ holds for every $n$.\n- **Induction from a base $n_0$:** if $P(n_0)$ holds and $P(k)\Rightarrow P(k+1)$ for $k\ge n_0$, then $P(n)$ holds for all $n\ge n_0$.\n- **Backward induction (Cauchy induction):** if the statement holds for infinitely many $n$ and $P(k)$ implies $P(k-1)$, then it holds for every $n$.'}},
  {'t': 'proof',
   'text': {'ru': r'Достаточно вывести сильную индукцию из принципа наименьшего числа; остальные две получаются так же.\n\nПусть выполнены условия сильной индукции, но множество $$M=\left\{n:\ P(n)\ \text{ложно}\right\}$$ непусто. Возьмём его наименьший элемент $m$.\n\nПо условию $P(1)$ верно, значит $m\ge2$. Все числа $1,2,\dots,m-1$ меньше $m$, а $m$ — наименьшее в $M$, поэтому ни одно из них в $M$ не лежит: утверждения $P(1),\dots,P(m-1)$ истинны.\n\nНо тогда по условию шага истинно и $P(m)$ — противоречие ✓ $\blacksquare$',
            'en': r'It suffices to derive strong induction from the least element principle; the other two go the same way.\n\nAssume the hypotheses of strong induction but suppose $$M=\left\{n:\ P(n)\ \text{is false}\right\}$$ is non-empty, with least element $m$.\n\nSince $P(1)$ holds, $m\ge2$. Every number $1,2,\dots,m-1$ is smaller than $m$ and $m$ is least in $M$, so none of them lies in $M$: the statements $P(1),\dots,P(m-1)$ are all true.\n\nThe induction step then makes $P(m)$ true — a contradiction ✓ $\blacksquare$'}},
  {'t': 'warn',
   'text': {'ru': r'**Индукция по неправильному параметру.** Если в задаче два параметра, индукция по одному из них может «сломаться». Признак беды: в шаге приходится применять предположение к объекту, у которого этот параметр не уменьшился. Лекарство — индуцировать по сумме параметров или по их произведению.\n\n**Слишком слабое предположение.** Иногда доказать более сильное утверждение **легче**, потому что в шаге доступно больше. Не бойтесь усиливать формулировку — это стандартный приём, а не признак ошибки.',
            'en': r'**Inducting on the wrong parameter.** With two parameters, induction on one of them may break down. The warning sign: the step needs the hypothesis for an object whose parameter has not decreased. The remedy is to induct on the sum, or the product, of the parameters.\n\n**A hypothesis that is too weak.** Sometimes proving a *stronger* statement is *easier*, because the step then has more to work with. Do not hesitate to strengthen the claim — that is a standard technique, not a symptom of error.'}},
 ],
}
