# -*- coding: utf-8 -*-
"""Topic 12 — deeper theory, woven into lesson_12.py by content/build.py."""

LINES = {
 'h': {'ru': 'Прямая: все формы уравнения',
       'en': 'The line: every form of its equation'},
 'blocks': [
  {'t': 'thm',
   'name': {'ru': 'Общее уравнение прямой', 'en': 'The general equation of a line'},
   'text': {'ru': r'Всякая прямая на плоскости задаётся уравнением $$Ax+By+C=0,\qquad A^{2}+B^{2}\ne0 ,$$ и обратно, всякое такое уравнение задаёт прямую. Вектор $\vec{n}=\left(A,B\right)$ перпендикулярен этой прямой и называется её **нормалью**, а вектор $\vec{s}=\left(-B,A\right)$ — направляющим.',
            'en': r'Every line in the plane is given by an equation $$Ax+By+C=0,\qquad A^{2}+B^{2}\ne0 ,$$ and conversely every such equation describes a line. The vector $\vec{n}=\left(A,B\right)$ is perpendicular to it and is called the **normal**, while $\vec{s}=\left(-B,A\right)$ is a direction vector.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть прямая проходит через точку $M_0=\left(x_0,y_0\right)$ и перпендикулярна ненулевому вектору $\vec{n}=\left(A,B\right)$. Точка $M=\left(x,y\right)$ лежит на прямой тогда и только тогда, когда вектор $\overrightarrow{M_0M}=\left(x-x_0,\,y-y_0\right)$ перпендикулярен $\vec{n}$, то есть их скалярное произведение равно нулю: $$A\left(x-x_0\right)+B\left(y-y_0\right)=0 .$$\n\nРаскрыв скобки и обозначив $C=-Ax_0-By_0$, получаем требуемое ✓\n\n**Обратно.** Пусть дано уравнение $Ax+By+C=0$ с $A^{2}+B^{2}\ne0$. Найдём хотя бы одно его решение $\left(x_0,y_0\right)$ (если $A\ne0$, положим $y_0=0$, $x_0=-\tfrac{C}{A}$; иначе $B\ne0$ и поступим симметрично). Вычитая равенство $Ax_0+By_0+C=0$ из исходного, приходим к $A\left(x-x_0\right)+B\left(y-y_0\right)=0$ — то есть к множеству точек, для которых $\overrightarrow{M_0M}\perp\vec{n}$. Это в точности прямая ✓ $\blacksquare$',
            'en': r'Let the line pass through $M_0=\left(x_0,y_0\right)$ and be perpendicular to a non-zero vector $\vec{n}=\left(A,B\right)$. A point $M=\left(x,y\right)$ lies on it iff $\overrightarrow{M_0M}=\left(x-x_0,\,y-y_0\right)$ is perpendicular to $\vec{n}$, i.e. their dot product vanishes: $$A\left(x-x_0\right)+B\left(y-y_0\right)=0 .$$\n\nExpanding and setting $C=-Ax_0-By_0$ gives the claim ✓\n\n**Conversely,** given $Ax+By+C=0$ with $A^{2}+B^{2}\ne0$, find one solution $\left(x_0,y_0\right)$ (if $A\ne0$ take $y_0=0$, $x_0=-\tfrac{C}{A}$; otherwise $B\ne0$ and proceed symmetrically). Subtracting $Ax_0+By_0+C=0$ from the equation gives $A\left(x-x_0\right)+B\left(y-y_0\right)=0$, the set of points with $\overrightarrow{M_0M}\perp\vec{n}$ — exactly a line ✓ $\blacksquare$'}},

  {'t': 'table',
   'head': {'ru': ['Форма', 'Уравнение', 'Когда удобна'],
            'en': ['Form', 'Equation', 'When to use it']},
   'rows': {'ru': [['общая', r'$Ax+By+C=0$', 'всегда; видна нормаль'],
                   ['с угловым коэффициентом', r'$y=kx+b$', 'прямая не вертикальна'],
                   ['через точку с наклоном', r'$y-y_0=k\left(x-x_0\right)$', 'известны точка и наклон'],
                   ['через две точки', r'$\dfrac{x-x_1}{x_2-x_1}=\dfrac{y-y_1}{y_2-y_1}$', 'даны две точки'],
                   ['в отрезках', r'$\dfrac{x}{a}+\dfrac{y}{b}=1$', 'известны точки пересечения с осями'],
                   ['параметрическая', r'$\left(x,y\right)=\left(x_0,y_0\right)+t\,\vec{s}$', 'нужна точка по параметру'],
                   ['нормальная', r'$x\cos\varphi+y\sin\varphi-p=0$', 'нужны расстояния']],
            'en': [['general', r'$Ax+By+C=0$', 'always; the normal is visible'],
                   ['slope–intercept', r'$y=kx+b$', 'the line is not vertical'],
                   ['point–slope', r'$y-y_0=k\left(x-x_0\right)$', 'a point and the slope are known'],
                   ['two-point', r'$\dfrac{x-x_1}{x_2-x_1}=\dfrac{y-y_1}{y_2-y_1}$', 'two points are given'],
                   ['intercept', r'$\dfrac{x}{a}+\dfrac{y}{b}=1$', 'the axis intercepts are known'],
                   ['parametric', r'$\left(x,y\right)=\left(x_0,y_0\right)+t\,\vec{s}$', 'a point per parameter is needed'],
                   ['normal', r'$x\cos\varphi+y\sin\varphi-p=0$', 'distances are needed']]}},

  {'t': 'thm',
   'name': {'ru': 'Параллельность и перпендикулярность',
            'en': 'Parallel and perpendicular'},
   'text': {'ru': r'Прямые $A_1x+B_1y+C_1=0$ и $A_2x+B_2y+C_2=0$\n\n- **параллельны** ⟺ $A_1B_2-A_2B_1=0$;\n- **перпендикулярны** ⟺ $A_1A_2+B_1B_2=0$.\n\nВ терминах угловых коэффициентов: параллельность означает $k_1=k_2$, перпендикулярность — $k_1k_2=-1$.',
            'en': r'The lines $A_1x+B_1y+C_1=0$ and $A_2x+B_2y+C_2=0$ are\n\n- **parallel** ⟺ $A_1B_2-A_2B_1=0$;\n- **perpendicular** ⟺ $A_1A_2+B_1B_2=0$.\n\nIn terms of slopes: parallel means $k_1=k_2$, perpendicular means $k_1k_2=-1$.'}},
  {'t': 'proof',
   'text': {'ru': r'Прямые параллельны тогда и только тогда, когда их нормали коллинеарны, а условие коллинеарности векторов $\left(A_1,B_1\right)$ и $\left(A_2,B_2\right)$ — равенство нулю определителя $A_1B_2-A_2B_1$ ✓\n\nПрямые перпендикулярны тогда и только тогда, когда перпендикулярны их нормали, то есть их скалярное произведение равно нулю ✓\n\n**Перевод в угловые коэффициенты.** Для невертикальной прямой $y=kx+b$ общее уравнение имеет вид $kx-y+b=0$, то есть $\vec{n}=\left(k,-1\right)$. Тогда условие перпендикулярности $$k_1k_2+\left(-1\right)\left(-1\right)=0\quad\Longleftrightarrow\quad k_1k_2=-1 \quad\checkmark\qquad\blacksquare$$',
            'en': r'Two lines are parallel iff their normals are collinear, and collinearity of $\left(A_1,B_1\right)$ and $\left(A_2,B_2\right)$ means the determinant $A_1B_2-A_2B_1$ vanishes ✓\n\nThey are perpendicular iff their normals are, i.e. the dot product vanishes ✓\n\n**Translating to slopes.** For a non-vertical line $y=kx+b$ the general form is $kx-y+b=0$, so $\vec{n}=\left(k,-1\right)$. The perpendicularity condition becomes $$k_1k_2+\left(-1\right)\left(-1\right)=0\quad\Longleftrightarrow\quad k_1k_2=-1 \quad\checkmark\qquad\blacksquare$$'}},
  {'t': 'warn',
   'text': {'ru': r'Правило $k_1k_2=-1$ **не работает** для вертикальной и горизонтальной прямых: у вертикальной углового коэффициента нет. Общая форма $A_1A_2+B_1B_2=0$ свободна от этого исключения — ещё одна причина предпочитать её.',
            'en': r'The rule $k_1k_2=-1$ **fails** for a vertical and a horizontal line: the vertical one has no slope. The general condition $A_1A_2+B_1B_2=0$ has no such exception — one more reason to prefer it.'}},

  {'t': 'proof',
   'text': {'ru': r'**Доказательство формулы расстояния от точки до прямой.** Пусть дана прямая $\ell:\ Ax+By+C=0$ и точка $M_1=\left(x_1,y_1\right)$. Возьмём на прямой любую точку $M_0=\left(x_0,y_0\right)$, так что $Ax_0+By_0+C=0$.\n\nРасстояние от $M_1$ до $\ell$ — это длина проекции вектора $\overrightarrow{M_0M_1}$ на нормаль $\vec{n}=\left(A,B\right)$: $$d=\frac{\left|\overrightarrow{M_0M_1}\cdot\vec{n}\right|}{\left|\vec{n}\right|}.$$\n\nВычислим числитель: $$\overrightarrow{M_0M_1}\cdot\vec{n}=A\left(x_1-x_0\right)+B\left(y_1-y_0\right)=Ax_1+By_1-\left(Ax_0+By_0\right)=Ax_1+By_1+C ,$$ где на последнем шаге использовано, что $Ax_0+By_0=-C$.\n\nЗначит $$d=\frac{\left|Ax_1+By_1+C\right|}{\sqrt{A^{2}+B^{2}}} \quad\checkmark\qquad\blacksquare$$\n\nЗаметьте: ответ не зависит от выбора $M_0$ — как и должно быть.',
            'en': r'**Proof of the point-to-line distance formula.** Let $\ell:\ Ax+By+C=0$ and $M_1=\left(x_1,y_1\right)$. Pick any point $M_0=\left(x_0,y_0\right)$ on $\ell$, so $Ax_0+By_0+C=0$.\n\nThe distance from $M_1$ to $\ell$ is the length of the projection of $\overrightarrow{M_0M_1}$ onto the normal $\vec{n}=\left(A,B\right)$: $$d=\frac{\left|\overrightarrow{M_0M_1}\cdot\vec{n}\right|}{\left|\vec{n}\right|}.$$\n\nThe numerator is $$A\left(x_1-x_0\right)+B\left(y_1-y_0\right)=Ax_1+By_1+C ,$$ using $Ax_0+By_0=-C$ at the last step.\n\nHence $$d=\frac{\left|Ax_1+By_1+C\right|}{\sqrt{A^{2}+B^{2}}} \quad\checkmark\qquad\blacksquare$$\n\nNote that the answer does not depend on the choice of $M_0$ — as it must not.'}},
  {'t': 'note',
   'text': {'ru': r'**Знак выражения $Ax_1+By_1+C$** говорит, по какую сторону от прямой лежит точка. Две точки лежат по одну сторону тогда и только тогда, когда значения этого выражения в них одного знака. Этот приём заменяет длинные рассуждения «точка внутри треугольника».',
            'en': r'**The sign of $Ax_1+By_1+C$** tells which side of the line the point is on. Two points are on the same side iff the expression takes the same sign at both. This replaces long arguments about a point lying inside a triangle.'}},
 ],
}

VECTORS = {
 'h': {'ru': 'Векторы и скалярное произведение',
       'en': 'Vectors and the dot product'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Координаты хороши тем, что переводят геометрию в алгебру. Векторы делают то же самое, но **без выбора системы координат**: формулировки становятся короче, а вычисления — устойчивее к неудачному расположению осей.',
            'en': r'Coordinates are good because they turn geometry into algebra. Vectors do the same **without choosing axes at all**: statements get shorter and computations stop depending on a bad placement of the frame.'}},

  {'t': 'def',
   'name': {'ru': 'Скалярное произведение', 'en': 'The dot product'},
   'text': {'ru': r'Для векторов $\vec{a}$ и $\vec{b}$ полагают $$\vec{a}\cdot\vec{b}=\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi ,$$ где $\varphi$ — угол между ними. В координатах $\vec{a}=\left(a_1,a_2\right)$, $\vec{b}=\left(b_1,b_2\right)$ это $$\vec{a}\cdot\vec{b}=a_1b_1+a_2b_2 .$$',
            'en': r'For vectors $\vec{a}$ and $\vec{b}$ one sets $$\vec{a}\cdot\vec{b}=\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi ,$$ where $\varphi$ is the angle between them. In coordinates $\vec{a}=\left(a_1,a_2\right)$, $\vec{b}=\left(b_1,b_2\right)$ this is $$\vec{a}\cdot\vec{b}=a_1b_1+a_2b_2 .$$'}},
  {'t': 'proof',
   'text': {'ru': r'**Согласованность двух определений.** Отложим оба вектора от начала координат; их концы — точки $A\left(a_1,a_2\right)$ и $B\left(b_1,b_2\right)$. По теореме косинусов в треугольнике $OAB$ $$AB^{2}=OA^{2}+OB^{2}-2\cdot OA\cdot OB\cos\varphi .$$\n\nВыразим все длины через координаты: $$\left(a_1-b_1\right)^{2}+\left(a_2-b_2\right)^{2}=\left(a_1^{2}+a_2^{2}\right)+\left(b_1^{2}+b_2^{2}\right)-2\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi .$$\n\nРаскроем левую часть: $$a_1^{2}-2a_1b_1+b_1^{2}+a_2^{2}-2a_2b_2+b_2^{2}.$$ Все квадраты сокращаются с правой частью, остаётся $$-2\left(a_1b_1+a_2b_2\right)=-2\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi ,$$ то есть $a_1b_1+a_2b_2=\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi$ ✓ $\blacksquare$',
            'en': r'**The two definitions agree.** Place both vectors at the origin; their tips are $A\left(a_1,a_2\right)$ and $B\left(b_1,b_2\right)$. The law of cosines in the triangle $OAB$ reads $$AB^{2}=OA^{2}+OB^{2}-2\cdot OA\cdot OB\cos\varphi .$$\n\nIn coordinates: $$\left(a_1-b_1\right)^{2}+\left(a_2-b_2\right)^{2}=\left(a_1^{2}+a_2^{2}\right)+\left(b_1^{2}+b_2^{2}\right)-2\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi .$$\n\nExpanding the left side, all the squares cancel against the right, leaving $$-2\left(a_1b_1+a_2b_2\right)=-2\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi ,$$ i.e. $a_1b_1+a_2b_2=\left|\vec{a}\right|\left|\vec{b}\right|\cos\varphi$ ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Свойства скалярного произведения',
            'en': 'Properties of the dot product'},
   'text': {'ru': r'Для любых векторов и числа $\lambda$\n\n- $\vec{a}\cdot\vec{b}=\vec{b}\cdot\vec{a}$;\n- $\left(\lambda\vec{a}\right)\cdot\vec{b}=\lambda\left(\vec{a}\cdot\vec{b}\right)$;\n- $\vec{a}\cdot\left(\vec{b}+\vec{c}\right)=\vec{a}\cdot\vec{b}+\vec{a}\cdot\vec{c}$;\n- $\vec{a}\cdot\vec{a}=\left|\vec{a}\right|^{2}\ge0$, причём $=0$ только для нулевого вектора;\n- $\vec{a}\perp\vec{b}\iff\vec{a}\cdot\vec{b}=0$.',
            'en': r'For all vectors and every scalar $\lambda$\n\n- $\vec{a}\cdot\vec{b}=\vec{b}\cdot\vec{a}$;\n- $\left(\lambda\vec{a}\right)\cdot\vec{b}=\lambda\left(\vec{a}\cdot\vec{b}\right)$;\n- $\vec{a}\cdot\left(\vec{b}+\vec{c}\right)=\vec{a}\cdot\vec{b}+\vec{a}\cdot\vec{c}$;\n- $\vec{a}\cdot\vec{a}=\left|\vec{a}\right|^{2}\ge0$, and $=0$ only for the zero vector;\n- $\vec{a}\perp\vec{b}\iff\vec{a}\cdot\vec{b}=0$.'}},
  {'t': 'idea',
   'text': {'ru': r'Эти свойства означают, что **со скалярным произведением можно работать как с обычным умножением**: раскрывать скобки, возводить в квадрат, применять формулы сокращённого умножения. Отсюда основной приём: любое условие вида «отрезки равны» или «прямые перпендикулярны» записывается как равенство скалярных произведений и превращается в алгебру.\n\nОдин пример: $$\left|\vec{a}+\vec{b}\right|^{2}=\left(\vec{a}+\vec{b}\right)\cdot\left(\vec{a}+\vec{b}\right)=\left|\vec{a}\right|^{2}+2\vec{a}\cdot\vec{b}+\left|\vec{b}\right|^{2} .$$ Это и есть теорема косинусов, записанная в одну строку.',
            'en': r'These properties say that **the dot product may be handled like ordinary multiplication**: expand brackets, square, use the standard identities. Hence the main technique: any hypothesis "these segments are equal" or "these lines are perpendicular" becomes an equation between dot products, i.e. algebra.\n\nOne example: $$\left|\vec{a}+\vec{b}\right|^{2}=\left|\vec{a}\right|^{2}+2\vec{a}\cdot\vec{b}+\left|\vec{b}\right|^{2} ,$$ which is the law of cosines written in a single line.'}},

  {'t': 'ex',
   'q': {'ru': r'Докажите векторами, что диагонали ромба перпендикулярны.',
         'en': r'Prove with vectors that the diagonals of a rhombus are perpendicular.'},
   'steps': {'ru': [r'Пусть $\vec{a}=\overrightarrow{AB}$ и $\vec{b}=\overrightarrow{AD}$ — стороны ромба, выходящие из вершины $A$. Условие ромба: $\left|\vec{a}\right|=\left|\vec{b}\right|$.',
                    r'Диагонали равны $\overrightarrow{AC}=\vec{a}+\vec{b}$ и $\overrightarrow{DB}=\vec{a}-\vec{b}$.',
                    r'Найдём их скалярное произведение: $$\left(\vec{a}+\vec{b}\right)\cdot\left(\vec{a}-\vec{b}\right)=\left|\vec{a}\right|^{2}-\left|\vec{b}\right|^{2}=0 .$$',
                    r'Скалярное произведение ненулевых векторов равно нулю, значит они перпендикулярны ✓',
                    r'Заодно доказано обратное: если диагонали параллелограмма перпендикулярны, то $\left|\vec{a}\right|=\left|\vec{b}\right|$ и он — ромб.'],
             'en': [r'Let $\vec{a}=\overrightarrow{AB}$ and $\vec{b}=\overrightarrow{AD}$ be the sides at $A$. Being a rhombus means $\left|\vec{a}\right|=\left|\vec{b}\right|$.',
                    r'The diagonals are $\overrightarrow{AC}=\vec{a}+\vec{b}$ and $\overrightarrow{DB}=\vec{a}-\vec{b}$.',
                    r'Their dot product is $$\left(\vec{a}+\vec{b}\right)\cdot\left(\vec{a}-\vec{b}\right)=\left|\vec{a}\right|^{2}-\left|\vec{b}\right|^{2}=0 .$$',
                    r'A zero dot product of non-zero vectors means they are perpendicular ✓',
                    r'The converse comes free: if the diagonals of a parallelogram are perpendicular then $\left|\vec{a}\right|=\left|\vec{b}\right|$ and it is a rhombus.']},
   'ans': {'ru': r'$\left(\vec{a}+\vec{b}\right)\cdot\left(\vec{a}-\vec{b}\right)=\left|\vec{a}\right|^{2}-\left|\vec{b}\right|^{2}=0$.',
           'en': r'$\left(\vec{a}+\vec{b}\right)\cdot\left(\vec{a}-\vec{b}\right)=\left|\vec{a}\right|^{2}-\left|\vec{b}\right|^{2}=0$.'}},

  {'t': 'thm',
   'name': {'ru': 'Центроид в векторах', 'en': 'The centroid in vectors'},
   'text': {'ru': r'Для произвольной точки $O$ и треугольника $ABC$ точка $$G=\frac13\left(\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC}\right)$$ является точкой пересечения медиан, и для неё $$\overrightarrow{GA}+\overrightarrow{GB}+\overrightarrow{GC}=\vec{0}.$$',
            'en': r'For any origin $O$ and any triangle $ABC$, the point $$G=\frac13\left(\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC}\right)$$ is the intersection of the medians, and it satisfies $$\overrightarrow{GA}+\overrightarrow{GB}+\overrightarrow{GC}=\vec{0}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Обозначим через $M$ середину $BC$, тогда $\overrightarrow{OM}=\tfrac12\left(\overrightarrow{OB}+\overrightarrow{OC}\right)$.\n\nВычислим точку, делящую медиану $AM$ в отношении $2:1$ от вершины: $$\overrightarrow{OA}+\frac23\overrightarrow{AM}=\overrightarrow{OA}+\frac23\left(\overrightarrow{OM}-\overrightarrow{OA}\right)=\frac13\overrightarrow{OA}+\frac23\overrightarrow{OM}=\frac13\left(\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC}\right).$$\n\nВыражение симметрично относительно $A$, $B$, $C$ — значит все три медианы содержат эту точку ✓ Это доказательство конкурентности медиан в две строки.\n\nВторое равенство получается, если взять $O=G$: тогда $\overrightarrow{GA}+\overrightarrow{GB}+\overrightarrow{GC}=3\,\overrightarrow{GG}=\vec{0}$ ✓ $\blacksquare$',
            'en': r'Let $M$ be the midpoint of $BC$, so $\overrightarrow{OM}=\tfrac12\left(\overrightarrow{OB}+\overrightarrow{OC}\right)$.\n\nCompute the point dividing the median $AM$ in the ratio $2:1$ from the vertex: $$\overrightarrow{OA}+\frac23\left(\overrightarrow{OM}-\overrightarrow{OA}\right)=\frac13\overrightarrow{OA}+\frac23\overrightarrow{OM}=\frac13\left(\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC}\right).$$\n\nThe expression is symmetric in $A$, $B$, $C$, so all three medians contain this point ✓ That is a two-line proof of the concurrence of the medians.\n\nThe second identity follows by taking $O=G$: then $\overrightarrow{GA}+\overrightarrow{GB}+\overrightarrow{GC}=3\,\overrightarrow{GG}=\vec{0}$ ✓ $\blacksquare$'}},
  {'t': 'note',
   'text': {'ru': r'В той же технике доказывается и красивая формула для ортоцентра: если $O$ — центр описанной окружности, то $$\overrightarrow{OH}=\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC}.$$ Отсюда мгновенно следует прямая Эйлера: $\overrightarrow{OH}=3\,\overrightarrow{OG}$, значит точки $O$, $G$, $H$ коллинеарны и $HG=2GO$.',
            'en': r'The same technique gives the elegant formula for the orthocentre: if $O$ is the circumcentre then $$\overrightarrow{OH}=\overrightarrow{OA}+\overrightarrow{OB}+\overrightarrow{OC}.$$ The Euler line follows instantly: $\overrightarrow{OH}=3\,\overrightarrow{OG}$, so $O$, $G$, $H$ are collinear and $HG=2GO$.'}},
 ],
}

LOCI = {
 'h': {'ru': 'Геометрические места точек в координатах',
       'en': 'Loci in coordinates'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Координатный метод особенно силён там, где условие задачи — это **уравнение**: «найдите все точки, для которых…». Достаточно записать условие в координатах и упростить; полученное уравнение и есть ответ.',
            'en': r'The coordinate method is at its strongest where the hypothesis is an **equation**: "find all points such that…". Write the condition in coordinates, simplify, and the resulting equation is the answer.'}},

  {'t': 'thm',
   'name': {'ru': 'Окружность Аполлония', 'en': 'The circle of Apollonius'},
   'text': {'ru': r'Пусть $A$ и $B$ — две различные точки и $k>0$, $k\ne1$. Множество точек $M$, для которых $$\frac{MA}{MB}=k ,$$ есть окружность, центр которой лежит на прямой $AB$. При $k=1$ это множество — серединный перпендикуляр к $AB$.',
            'en': r'Let $A$ and $B$ be distinct points and $k>0$, $k\ne1$. The set of points $M$ with $$\frac{MA}{MB}=k$$ is a circle whose centre lies on the line $AB$. For $k=1$ the set is the perpendicular bisector of $AB$.'}},
  {'t': 'proof',
   'text': {'ru': r'Выберем координаты так, чтобы $A=\left(-a,0\right)$ и $B=\left(a,0\right)$, где $2a=AB$. Условие $MA=k\cdot MB$ после возведения в квадрат принимает вид $$\left(x+a\right)^{2}+y^{2}=k^{2}\left[\left(x-a\right)^{2}+y^{2}\right].$$\n\nРаскроем и соберём: $$\left(1-k^{2}\right)\left(x^{2}+y^{2}\right)+2ax\left(1+k^{2}\right)+a^{2}\left(1-k^{2}\right)=0 .$$\n\n**Если $k\ne1$,** можно разделить на $1-k^{2}\ne0$: $$x^{2}+y^{2}+2a\,\frac{1+k^{2}}{1-k^{2}}\,x+a^{2}=0 .$$ Это уравнение вида $x^{2}+y^{2}+Dx+F=0$ — то есть окружность (после выделения полного квадрата), центр которой лежит на оси $Ox$, то есть на прямой $AB$ ✓\n\n**Если $k=1$,** члены с квадратами исчезают, и остаётся $4ax=0$, то есть $x=0$ — серединный перпендикуляр ✓ $\blacksquare$\n\nПроверим, что окружность невырожденна: выделив полный квадрат, получаем радиус $$R=\left|\frac{2ak}{1-k^{2}}\right|>0 \quad\checkmark$$',
            'en': r'Choose coordinates with $A=\left(-a,0\right)$ and $B=\left(a,0\right)$, where $2a=AB$. Squaring $MA=k\cdot MB$ gives $$\left(x+a\right)^{2}+y^{2}=k^{2}\left[\left(x-a\right)^{2}+y^{2}\right].$$\n\nExpanding and collecting, $$\left(1-k^{2}\right)\left(x^{2}+y^{2}\right)+2ax\left(1+k^{2}\right)+a^{2}\left(1-k^{2}\right)=0 .$$\n\n**If $k\ne1$** divide by $1-k^{2}\ne0$: $$x^{2}+y^{2}+2a\,\frac{1+k^{2}}{1-k^{2}}\,x+a^{2}=0 ,$$ an equation of the form $x^{2}+y^{2}+Dx+F=0$ — a circle (complete the square) whose centre lies on the axis $Ox$, i.e. on the line $AB$ ✓\n\n**If $k=1$** the quadratic terms vanish and $4ax=0$ remains, i.e. $x=0$ — the perpendicular bisector ✓ $\blacksquare$\n\nThe circle is non-degenerate: completing the square gives the radius $$R=\left|\frac{2ak}{1-k^{2}}\right|>0 \quad\checkmark$$'}},
  {'t': 'note',
   'text': {'ru': r'Окружность Аполлония объясняет свойство биссектрис: внутренняя и внешняя биссектрисы угла $A$ треугольника пересекают прямую $BC$ в двух точках, делящих её в одном и том же отношении $\dfrac{AB}{AC}$ — но одна внутренним, другая внешним образом. Эти две точки и есть концы диаметра соответствующей окружности Аполлония.',
            'en': r'The circle of Apollonius explains the bisector picture: the internal and external bisectors of the angle $A$ meet the line $BC$ at two points dividing it in the same ratio $\dfrac{AB}{AC}$ — one internally, one externally. Those two points are the ends of a diameter of the corresponding Apollonius circle.'}},

  {'t': 'thm',
   'name': {'ru': 'Уравнение касательной к окружности',
            'en': 'The tangent line to a circle'},
   'text': {'ru': r'Касательная к окружности $\left(x-x_0\right)^{2}+\left(y-y_0\right)^{2}=R^{2}$ в её точке $M_1=\left(x_1,y_1\right)$ задаётся уравнением $$\left(x_1-x_0\right)\left(x-x_0\right)+\left(y_1-y_0\right)\left(y-y_0\right)=R^{2}.$$',
            'en': r'The tangent to the circle $\left(x-x_0\right)^{2}+\left(y-y_0\right)^{2}=R^{2}$ at a point $M_1=\left(x_1,y_1\right)$ of it is $$\left(x_1-x_0\right)\left(x-x_0\right)+\left(y_1-y_0\right)\left(y-y_0\right)=R^{2}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Касательная перпендикулярна радиусу $\overrightarrow{OM_1}=\left(x_1-x_0,\,y_1-y_0\right)$, значит этот вектор — её нормаль. Уравнение прямой через $M_1$ с такой нормалью: $$\left(x_1-x_0\right)\left(x-x_1\right)+\left(y_1-y_0\right)\left(y-y_1\right)=0 .$$\n\nПрибавим к обеим частям $\left(x_1-x_0\right)^{2}+\left(y_1-y_0\right)^{2}=R^{2}$ и сгруппируем: слева получится $$\left(x_1-x_0\right)\left(x-x_1+x_1-x_0\right)+\left(y_1-y_0\right)\left(y-y_1+y_1-y_0\right),$$ то есть в точности левая часть требуемого равенства ✓ $\blacksquare$',
            'en': r'The tangent is perpendicular to the radius $\overrightarrow{OM_1}=\left(x_1-x_0,\,y_1-y_0\right)$, so that vector is its normal. The line through $M_1$ with this normal is $$\left(x_1-x_0\right)\left(x-x_1\right)+\left(y_1-y_0\right)\left(y-y_1\right)=0 .$$\n\nAdd $\left(x_1-x_0\right)^{2}+\left(y_1-y_0\right)^{2}=R^{2}$ to both sides and regroup: the left side becomes $$\left(x_1-x_0\right)\left(x-x_0\right)+\left(y_1-y_0\right)\left(y-y_0\right) ,$$ exactly as claimed ✓ $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите множество точек $M$, для которых $MA=2\,MB$, если $A\left(-3,0\right)$ и $B\left(3,0\right)$.',
         'en': r'Find the set of points $M$ with $MA=2\,MB$, where $A\left(-3,0\right)$ and $B\left(3,0\right)$.'},
   'steps': {'ru': [r'Запишем условие в координатах и возведём в квадрат: $$\left(x+3\right)^{2}+y^{2}=4\left[\left(x-3\right)^{2}+y^{2}\right].$$',
                    r'Раскроем: $x^{2}+6x+9+y^{2}=4x^{2}-24x+36+4y^{2}$.',
                    r'Перенесём всё вправо: $3x^{2}+3y^{2}-30x+27=0$, то есть $x^{2}+y^{2}-10x+9=0$.',
                    r'Выделим полный квадрат: $\left(x-5\right)^{2}+y^{2}=16$.',
                    r'Это окружность с центром $\left(5,0\right)$ и радиусом $4$. Проверим точку $\left(1,0\right)$: $MA=4$, $MB=2$ ✓ И точку $\left(9,0\right)$: $MA=12$, $MB=6$ ✓'],
             'en': [r'Write the condition in coordinates and square: $$\left(x+3\right)^{2}+y^{2}=4\left[\left(x-3\right)^{2}+y^{2}\right].$$',
                    r'Expand: $x^{2}+6x+9+y^{2}=4x^{2}-24x+36+4y^{2}$.',
                    r'Collect: $3x^{2}+3y^{2}-30x+27=0$, i.e. $x^{2}+y^{2}-10x+9=0$.',
                    r'Complete the square: $\left(x-5\right)^{2}+y^{2}=16$.',
                    r'A circle of centre $\left(5,0\right)$ and radius $4$. Check $\left(1,0\right)$: $MA=4$, $MB=2$ ✓ And $\left(9,0\right)$: $MA=12$, $MB=6$ ✓']},
   'ans': {'ru': r'Окружность $\left(x-5\right)^{2}+y^{2}=16$.', 'en': r'The circle $\left(x-5\right)^{2}+y^{2}=16$.'}},

  {'t': 'idea',
   'text': {'ru': r'**Как выбрать систему координат.** Правильный выбор осей сокращает вычисления в разы:\n\n- начало координат — в вершине прямого угла или в центре симметрии;\n- ось $Ox$ — вдоль самой длинной стороны или вдоль оси симметрии;\n- используйте симметрию условия: если в задаче есть отрезок, ставьте его концы в $\left(-a,0\right)$ и $\left(a,0\right)$, а не в $\left(0,0\right)$ и $\left(2a,0\right)$;\n- если фигура задана с точностью до подобия, можно положить одну из длин равной $1$.',
            'en': r'**How to choose the frame.** A good choice of axes cuts the work several times over:\n\n- put the origin at a right-angle vertex or at a centre of symmetry;\n- align $Ox$ with the longest side or with an axis of symmetry;\n- exploit the symmetry of the hypothesis: given a segment, place its ends at $\left(-a,0\right)$ and $\left(a,0\right)$, not at $\left(0,0\right)$ and $\left(2a,0\right)$;\n- if the figure is only determined up to similarity, one length may be set equal to $1$.'}},
 ],
}

SECTIONS = [(2, LINES), (3, VECTORS), (4, LOCI)]

INTO = {
 0: [
  {'t': 'proof',
   'text': {'ru': r'**Доказательство формулы расстояния.** Пусть $A\left(x_1,y_1\right)$ и $B\left(x_2,y_2\right)$. Проведём через $A$ горизонтальную, а через $B$ вертикальную прямую; они пересекутся в точке $C\left(x_2,y_1\right)$.\n\nТреугольник $ACB$ прямоугольный с катетами $$AC=\left|x_2-x_1\right|,\qquad CB=\left|y_2-y_1\right| .$$\n\nПо теореме Пифагора $$AB^{2}=\left(x_2-x_1\right)^{2}+\left(y_2-y_1\right)^{2} \quad\checkmark$$ (модули исчезли, так как возводятся в квадрат).\n\nВырожденные случаи — когда точки лежат на одной горизонтали или вертикали — формула охватывает автоматически: одно из слагаемых обращается в нуль ✓ $\blacksquare$',
            'en': r'**Proof of the distance formula.** Let $A\left(x_1,y_1\right)$ and $B\left(x_2,y_2\right)$. Draw the horizontal line through $A$ and the vertical line through $B$; they meet at $C\left(x_2,y_1\right)$.\n\nThe triangle $ACB$ is right-angled with legs $$AC=\left|x_2-x_1\right|,\qquad CB=\left|y_2-y_1\right| .$$\n\nPythagoras gives $$AB^{2}=\left(x_2-x_1\right)^{2}+\left(y_2-y_1\right)^{2} \quad\checkmark$$ (the absolute values disappear under the squares).\n\nThe degenerate cases — points on a common horizontal or vertical line — are covered automatically: one term becomes zero ✓ $\blacksquare$'}},
  {'t': 'proof',
   'text': {'ru': r'**Доказательство формулы деления отрезка.** Пусть точка $M$ делит отрезок $AB$ в отношении $AM:MB=\lambda:\mu$. Утверждается, что $$M=\left(\frac{\mu x_1+\lambda x_2}{\lambda+\mu},\ \frac{\mu y_1+\lambda y_2}{\lambda+\mu}\right).$$\n\nСпроецируем всё на ось $Ox$. Проекции точек $A$, $M$, $B$ делят отрезок в том же отношении (по теореме Фалеса: параллельные прямые высекают на секущих пропорциональные отрезки). Значит $$\frac{x-x_1}{x_2-x}=\frac{\lambda}{\mu}.$$\n\nРешим относительно $x$: $$\mu\left(x-x_1\right)=\lambda\left(x_2-x\right)\ \Longrightarrow\ x\left(\lambda+\mu\right)=\mu x_1+\lambda x_2 \quad\checkmark$$\n\nДля $y$ проекция на ось $Oy$ даёт то же самое ✓ При $\lambda=\mu$ получается середина: среднее арифметическое координат $\blacksquare$',
            'en': r'**Proof of the section formula.** Let $M$ divide $AB$ so that $AM:MB=\lambda:\mu$. The claim is $$M=\left(\frac{\mu x_1+\lambda x_2}{\lambda+\mu},\ \frac{\mu y_1+\lambda y_2}{\lambda+\mu}\right).$$\n\nProject everything onto $Ox$. The projections of $A$, $M$, $B$ divide the segment in the same ratio (by Thales: parallel lines cut proportional segments on any transversal). Hence $$\frac{x-x_1}{x_2-x}=\frac{\lambda}{\mu}.$$\n\nSolving for $x$: $$\mu\left(x-x_1\right)=\lambda\left(x_2-x\right)\ \Longrightarrow\ x\left(\lambda+\mu\right)=\mu x_1+\lambda x_2 \quad\checkmark$$\n\nProjecting onto $Oy$ gives the same for $y$ ✓ With $\lambda=\mu$ this is the midpoint: the arithmetic mean of the coordinates $\blacksquare$'}},
 ],
 2: [
  {'t': 'proof',
   'text': {'ru': r'**Доказательство формулы площади («шнуровки»).** Пусть вершины треугольника — $A\left(x_1,y_1\right)$, $B\left(x_2,y_2\right)$, $C\left(x_3,y_3\right)$. Перенесём начало координат в точку $A$; площадь при параллельном переносе не меняется. Новые координаты: $$\vec{u}=\left(x_2-x_1,\ y_2-y_1\right),\qquad \vec{v}=\left(x_3-x_1,\ y_3-y_1\right).$$\n\nПлощадь треугольника равна половине площади параллелограмма, натянутого на $\vec{u}$ и $\vec{v}$, то есть $$S=\frac12\left|\vec{u}\right|\left|\vec{v}\right|\sin\varphi .$$\n\nВозведём в квадрат и воспользуемся $\sin^{2}\varphi=1-\cos^{2}\varphi$ вместе с определением скалярного произведения: $$4S^{2}=\left|\vec{u}\right|^{2}\left|\vec{v}\right|^{2}-\left(\vec{u}\cdot\vec{v}\right)^{2}.$$\n\nПо тождеству Лагранжа для двух векторов правая часть равна $\left(u_1v_2-u_2v_1\right)^{2}$. Значит $$S=\frac12\left|u_1v_2-u_2v_1\right|=\frac12\left|\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)\right| \quad\checkmark\qquad\blacksquare$$\n\nРаскрыв скобки, получаем симметричную запись $$S=\frac12\left|x_1y_2-x_2y_1+x_2y_3-x_3y_2+x_3y_1-x_1y_3\right| ,$$ которая обобщается на любой многоугольник: слагаемые $x_iy_{i+1}-x_{i+1}y_i$ выписываются по кругу.',
            'en': r'**Proof of the shoelace area formula.** Let the vertices be $A\left(x_1,y_1\right)$, $B\left(x_2,y_2\right)$, $C\left(x_3,y_3\right)$. Translate the origin to $A$; a translation does not change area. The new coordinates are $$\vec{u}=\left(x_2-x_1,\ y_2-y_1\right),\qquad \vec{v}=\left(x_3-x_1,\ y_3-y_1\right).$$\n\nThe area of the triangle is half that of the parallelogram spanned by $\vec{u}$ and $\vec{v}$: $$S=\frac12\left|\vec{u}\right|\left|\vec{v}\right|\sin\varphi .$$\n\nSquare it and use $\sin^{2}\varphi=1-\cos^{2}\varphi$ together with the definition of the dot product: $$4S^{2}=\left|\vec{u}\right|^{2}\left|\vec{v}\right|^{2}-\left(\vec{u}\cdot\vec{v}\right)^{2}.$$\n\nBy the identity of Lagrange for two vectors the right side equals $\left(u_1v_2-u_2v_1\right)^{2}$. Hence $$S=\frac12\left|\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)\right| \quad\checkmark\qquad\blacksquare$$\n\nExpanding gives the symmetric form $$S=\frac12\left|x_1y_2-x_2y_1+x_2y_3-x_3y_2+x_3y_1-x_1y_3\right| ,$$ which generalises to any polygon: the terms $x_iy_{i+1}-x_{i+1}y_i$ are written round the cycle.'}},
  {'t': 'thm',
   'name': {'ru': 'Признак коллинеарности трёх точек',
            'en': 'A collinearity test for three points'},
   'text': {'ru': r'Точки $A\left(x_1,y_1\right)$, $B\left(x_2,y_2\right)$, $C\left(x_3,y_3\right)$ лежат на одной прямой тогда и только тогда, когда $$\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)=0 .$$',
            'en': r'The points $A\left(x_1,y_1\right)$, $B\left(x_2,y_2\right)$, $C\left(x_3,y_3\right)$ are collinear if and only if $$\left(x_2-x_1\right)\left(y_3-y_1\right)-\left(x_3-x_1\right)\left(y_2-y_1\right)=0 .$$'}},
  {'t': 'note',
   'text': {'ru': r'Это ровно то же выражение, что и в формуле площади: три точки коллинеарны тогда и только тогда, когда «треугольник» на них имеет нулевую площадь. Так одна формула решает две разные задачи — и это типично для координатного метода.',
            'en': r'This is exactly the expression from the area formula: three points are collinear iff the "triangle" on them has zero area. One formula settles two different questions — which is typical of the coordinate method.'}},
 ],
}
