# -*- coding: utf-8 -*-
"""Topic 10 — deeper theory, woven into lesson_10.py by content/build.py."""

FORMULAS = {
 'h': {'ru': 'Откуда берутся формулы площади',
       'en': 'Where the area formulas come from'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Формулы площади не нужно заучивать списком: все они выводятся из одной — площади прямоугольника — за несколько шагов. Разберём цепочку целиком, а заодно получим формулы, которых нет в школьном учебнике.',
            'en': r'The area formulas do not have to be memorised as a list: they all follow from one — the area of a rectangle — in a few steps. Here is the whole chain, together with some formulas the school textbook omits.'}},

  {'t': 'thm',
   'name': {'ru': 'Площадь параллелограмма и треугольника',
            'en': 'The area of a parallelogram and of a triangle'},
   'text': {'ru': r'$$S_{\text{пар}}=a h_a ,\qquad S_{\triangle}=\frac12 a h_a .$$',
            'en': r'$$S_{\text{par}}=a h_a ,\qquad S_{\triangle}=\frac12 a h_a .$$'}},
  {'t': 'proof',
   'text': {'ru': r'**Параллелограмм.** Отрежем от параллелограмма $ABCD$ прямоугольный треугольник, отсекаемый высотой из вершины $A$, и приставим его к противоположной стороне. Получится прямоугольник с основанием $a$ и высотой $h_a$, площадь которого равна $ah_a$. Разрезание и перекладывание площадь не меняют ✓\n\n**Треугольник.** Достроим треугольник $ABC$ до параллелограмма, приложив к стороне $BC$ его копию, повёрнутую на $180^{\circ}$ вокруг середины $BC$. Параллелограмм состоит из двух равных треугольников, значит площадь каждого равна половине ✓ $\blacksquare$',
            'en': r'**Parallelogram.** Cut off the right triangle that the altitude from $A$ separates from $ABCD$ and reattach it at the opposite side. The result is a rectangle of base $a$ and height $h_a$, whose area is $ah_a$. Cutting and rearranging does not change area ✓\n\n**Triangle.** Complete $ABC$ to a parallelogram by attaching to the side $BC$ its own copy rotated by $180^{\circ}$ about the midpoint of $BC$. The parallelogram consists of two congruent triangles, so each has half the area ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Площадь через две стороны и угол',
            'en': 'Area from two sides and the included angle'},
   'text': {'ru': r'$$S=\frac12\,ab\sin C .$$',
            'en': r'$$S=\frac12\,ab\sin C .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Высота из вершины $A$ на прямую $BC$ равна $h_a=b\sin C$ — это определение синуса в прямоугольном треугольнике, отсекаемом высотой (при тупом $C$ синус смежного угла тот же, поэтому формула сохраняется).\n\nПодставим в $S=\tfrac12 a h_a$ ✓ $\blacksquare$\n\n**Следствие.** При фиксированных сторонах $a$ и $b$ площадь максимальна, когда $\sin C=1$, то есть при $C=90^{\circ}$. Это готовый ответ для целого класса задач на максимум.',
            'en': r'The altitude from $A$ to the line $BC$ equals $h_a=b\sin C$ — the definition of the sine in the right triangle cut off by the altitude (for obtuse $C$ the supplementary angle has the same sine, so the formula survives).\n\nSubstitute into $S=\tfrac12 a h_a$ ✓ $\blacksquare$\n\n**Corollary.** With $a$ and $b$ fixed the area is largest when $\sin C=1$, i.e. $C=90^{\circ}$. That answers a whole family of maximisation problems at once.'}},

  {'t': 'thm',
   'name': {'ru': 'Формула Герона', 'en': 'Heron formula'},
   'text': {'ru': r'Если $p=\dfrac{a+b+c}{2}$ — полупериметр, то $$S=\sqrt{p\left(p-a\right)\left(p-b\right)\left(p-c\right)} .$$',
            'en': r'If $p=\dfrac{a+b+c}{2}$ is the semiperimeter then $$S=\sqrt{p\left(p-a\right)\left(p-b\right)\left(p-c\right)} .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Начнём с $S=\tfrac12 ab\sin C$ и выразим синус через косинус: $$16S^{2}=4a^{2}b^{2}\sin^{2}C=4a^{2}b^{2}\left(1-\cos^{2}C\right)=\left(2ab\right)^{2}-\left(2ab\cos C\right)^{2}.$$\n\nПо теореме косинусов $2ab\cos C=a^{2}+b^{2}-c^{2}$, поэтому $$16S^{2}=\left(2ab\right)^{2}-\left(a^{2}+b^{2}-c^{2}\right)^{2}.$$\n\nЭто разность квадратов: $$16S^{2}=\left(2ab+a^{2}+b^{2}-c^{2}\right)\left(2ab-a^{2}-b^{2}+c^{2}\right)=\left[\left(a+b\right)^{2}-c^{2}\right]\left[c^{2}-\left(a-b\right)^{2}\right].$$\n\nКаждая скобка — снова разность квадратов: $$16S^{2}=\left(a+b+c\right)\left(a+b-c\right)\left(c+a-b\right)\left(c-a+b\right).$$\n\nОстаётся заметить, что эти четыре множителя равны $2p$, $2\left(p-c\right)$, $2\left(p-b\right)$, $2\left(p-a\right)$, а их произведение — $16\,p\left(p-a\right)\left(p-b\right)\left(p-c\right)$ ✓ $\blacksquare$',
            'en': r'Start from $S=\tfrac12 ab\sin C$ and turn the sine into a cosine: $$16S^{2}=4a^{2}b^{2}\left(1-\cos^{2}C\right)=\left(2ab\right)^{2}-\left(2ab\cos C\right)^{2}.$$\n\nThe law of cosines gives $2ab\cos C=a^{2}+b^{2}-c^{2}$, so $$16S^{2}=\left(2ab\right)^{2}-\left(a^{2}+b^{2}-c^{2}\right)^{2}.$$\n\nThat is a difference of squares: $$16S^{2}=\left[\left(a+b\right)^{2}-c^{2}\right]\left[c^{2}-\left(a-b\right)^{2}\right].$$\n\nEach bracket is again a difference of squares: $$16S^{2}=\left(a+b+c\right)\left(a+b-c\right)\left(c+a-b\right)\left(c-a+b\right).$$\n\nThe four factors are $2p$, $2\left(p-c\right)$, $2\left(p-b\right)$, $2\left(p-a\right)$, whose product is $16\,p\left(p-a\right)\left(p-b\right)\left(p-c\right)$ ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Площадь через радиусы окружностей',
            'en': 'Area from the two radii'},
   'text': {'ru': r'$$S=p\,r\qquad\text{и}\qquad S=\frac{abc}{4R},$$ где $r$ — радиус вписанной, $R$ — радиус описанной окружности.',
            'en': r'$$S=p\,r\qquad\text{and}\qquad S=\frac{abc}{4R},$$ where $r$ is the inradius and $R$ the circumradius.'}},
  {'t': 'proof',
   'text': {'ru': r'**Первая формула.** Соединим центр вписанной окружности $I$ с вершинами. Треугольник разбивается на три: $IBC$, $ICA$, $IAB$. Высота каждого из них, опущенная на соответствующую сторону, равна $r$ (радиус, проведённый в точку касания, перпендикулярен стороне). Значит $$S=\frac12 ar+\frac12 br+\frac12 cr=\frac{a+b+c}{2}\,r=pr \quad\checkmark$$\n\n**Вторая формула.** По теореме синусов $\dfrac{c}{\sin C}=2R$, то есть $\sin C=\dfrac{c}{2R}$. Подставим в $S=\tfrac12 ab\sin C$: $$S=\frac12 ab\cdot\frac{c}{2R}=\frac{abc}{4R} \quad\checkmark\qquad\blacksquare$$',
            'en': r'**The first.** Join the incentre $I$ to the vertices, splitting the triangle into $IBC$, $ICA$, $IAB$. The altitude of each to the corresponding side is $r$ (the radius to a point of tangency is perpendicular to the side). Hence $$S=\frac12 ar+\frac12 br+\frac12 cr=pr \quad\checkmark$$\n\n**The second.** The law of sines gives $\dfrac{c}{\sin C}=2R$, so $\sin C=\dfrac{c}{2R}$. Substituting into $S=\tfrac12 ab\sin C$, $$S=\frac{abc}{4R} \quad\checkmark\qquad\blacksquare$$'}},
  {'t': 'note',
   'text': {'ru': r'Формула $S=pr$ — рабочая лошадка задач про вписанную окружность: она мгновенно даёт $r=\dfrac{S}{p}$. Вместе с формулой Герона это позволяет найти $r$ и $R$ по трём сторонам, ничего не строя.',
            'en': r'The formula $S=pr$ is the workhorse of incircle problems: it gives $r=\dfrac{S}{p}$ at once. Together with Heron it yields $r$ and $R$ from the three sides with no construction at all.'}},

  {'t': 'ex',
   'q': {'ru': r'В треугольнике со сторонами $13$, $14$, $15$ найдите площадь, радиус вписанной и радиус описанной окружностей.',
         'en': r'For the triangle with sides $13$, $14$, $15$ find the area, the inradius and the circumradius.'},
   'steps': {'ru': [r'Полупериметр: $p=\dfrac{13+14+15}{2}=21$.',
                    r'Герон: $S=\sqrt{21\cdot8\cdot7\cdot6}=\sqrt{7056}=84$.',
                    r'Вписанная: $r=\dfrac{S}{p}=\dfrac{84}{21}=4$.',
                    r'Описанная: $R=\dfrac{abc}{4S}=\dfrac{13\cdot14\cdot15}{4\cdot84}=\dfrac{2730}{336}=\dfrac{65}{8}=8{,}125$.',
                    r'Проверка неравенством Эйлера $R\ge2r$: $8{,}125\ge8$ ✓'],
             'en': [r'Semiperimeter: $p=\dfrac{13+14+15}{2}=21$.',
                    r'Heron: $S=\sqrt{21\cdot8\cdot7\cdot6}=\sqrt{7056}=84$.',
                    r'Inradius: $r=\dfrac{S}{p}=\dfrac{84}{21}=4$.',
                    r'Circumradius: $R=\dfrac{abc}{4S}=\dfrac{2730}{336}=\dfrac{65}{8}=8.125$.',
                    r'Check with the inequality of Euler $R\ge2r$: $8.125\ge8$ ✓']},
   'ans': {'ru': r'$S=84$, $r=4$, $R=\dfrac{65}{8}$.', 'en': r'$S=84$, $r=4$, $R=\dfrac{65}{8}$.'}},

  {'t': 'table',
   'head': {'ru': ['Фигура', 'Формула', 'Когда удобна'],
            'en': ['Figure', 'Formula', 'When it helps']},
   'rows': {'ru': [['треугольник', r'$\tfrac12 a h_a$', 'известна высота'],
                   ['треугольник', r'$\tfrac12 ab\sin C$', 'известны две стороны и угол'],
                   ['треугольник', r'$\sqrt{p(p-a)(p-b)(p-c)}$', 'известны три стороны'],
                   ['треугольник', r'$pr$', 'речь о вписанной окружности'],
                   ['треугольник', r'$\tfrac{abc}{4R}$', 'речь об описанной окружности'],
                   ['трапеция', r'$\tfrac{a+b}{2}\,h$', 'средняя линия на высоту'],
                   ['ромб / любой четырёхугольник с $d_1\\perp d_2$', r'$\tfrac12 d_1d_2$', 'диагонали перпендикулярны'],
                   ['произвольный четырёхугольник', r'$\tfrac12 d_1d_2\sin\varphi$', 'известен угол между диагоналями']],
            'en': [['triangle', r'$\tfrac12 a h_a$', 'an altitude is known'],
                   ['triangle', r'$\tfrac12 ab\sin C$', 'two sides and the angle are known'],
                   ['triangle', r'$\sqrt{p(p-a)(p-b)(p-c)}$', 'the three sides are known'],
                   ['triangle', r'$pr$', 'the incircle is involved'],
                   ['triangle', r'$\tfrac{abc}{4R}$', 'the circumcircle is involved'],
                   ['trapezium', r'$\tfrac{a+b}{2}\,h$', 'midline times height'],
                   ['rhombus / any quadrilateral with $d_1\\perp d_2$', r'$\tfrac12 d_1d_2$', 'the diagonals are perpendicular'],
                   ['general quadrilateral', r'$\tfrac12 d_1d_2\sin\varphi$', 'the angle between the diagonals is known']]}},
 ],
}

MENELAUS = {
 'h': {'ru': 'Теорема Менелая и тригонометрическая Чева',
       'en': 'Menelaus and the trigonometric form of Ceva'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Теорема Чевы отвечает на вопрос «когда три чевианы пересекаются в одной точке». Её близнец — теорема Менелая — отвечает на вопрос «когда три точки лежат на одной прямой». Вместе они закрывают большинство задач про отношения отрезков.',
            'en': r'The theorem of Ceva answers "when do three cevians meet at one point". Its twin, the theorem of Menelaus, answers "when do three points lie on one line". Together they cover most problems about ratios of segments.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Менелая', 'en': 'Menelaus theorem'},
   'text': {'ru': r'Пусть прямая пересекает прямые $BC$, $CA$, $AB$ треугольника $ABC$ в точках $X$, $Y$, $Z$ соответственно (ни одна из них не совпадает с вершиной). Тогда $$\frac{BX}{XC}\cdot\frac{CY}{YA}\cdot\frac{AZ}{ZB}=1 ,$$ причём ровно одна или все три точки лежат вне отрезков-сторон. Верно и обратное: если произведение равно $1$ и число «внешних» точек нечётно, то $X$, $Y$, $Z$ лежат на одной прямой.',
            'en': r'Let a line meet the lines $BC$, $CA$, $AB$ of a triangle $ABC$ at $X$, $Y$, $Z$ respectively (none of them a vertex). Then $$\frac{BX}{XC}\cdot\frac{CY}{YA}\cdot\frac{AZ}{ZB}=1 ,$$ and either exactly one or all three points lie outside the corresponding sides. The converse holds: if the product is $1$ and the number of outside points is odd, then $X$, $Y$, $Z$ are collinear.'}},
  {'t': 'proof',
   'text': {'ru': r'Опустим на секущую прямую перпендикуляры из всех трёх вершин; обозначим их длины $h_A$, $h_B$, $h_C$.\n\nРассмотрим точку $X$ — пересечение секущей с прямой $BC$. Прямоугольные треугольники, образованные перпендикулярами из $B$ и из $C$, подобны (у них равны вертикальные или соответственные углы при вершине $X$), поэтому $$\frac{BX}{XC}=\frac{h_B}{h_C}.$$\n\nТочно так же $$\frac{CY}{YA}=\frac{h_C}{h_A},\qquad \frac{AZ}{ZB}=\frac{h_A}{h_B}.$$\n\nПеремножим три равенства: все высоты сокращаются, и произведение равно $1$ ✓ $\blacksquare$\n\n**Обратная теорема** доказывается стандартным приёмом: пусть прямая $XY$ пересекает $AB$ в точке $Z_1$. По прямой теореме произведение с $Z_1$ равно $1$, значит $\dfrac{AZ_1}{Z_1B}=\dfrac{AZ}{ZB}$. Но точка, делящая отрезок в данном отношении с данным знаком, единственна, поэтому $Z_1=Z$ ✓',
            'en': r'Drop perpendiculars to the transversal from all three vertices; call their lengths $h_A$, $h_B$, $h_C$.\n\nConsider $X$, where the transversal meets the line $BC$. The right triangles formed by the perpendiculars from $B$ and from $C$ are similar (equal vertical or corresponding angles at $X$), so $$\frac{BX}{XC}=\frac{h_B}{h_C}.$$\n\nIn the same way $$\frac{CY}{YA}=\frac{h_C}{h_A},\qquad \frac{AZ}{ZB}=\frac{h_A}{h_B}.$$\n\nMultiplying the three, every height cancels and the product is $1$ ✓ $\blacksquare$\n\n**The converse** uses the standard move: let the line $XY$ meet $AB$ at $Z_1$. The direct theorem makes the product with $Z_1$ equal to $1$, so $\dfrac{AZ_1}{Z_1B}=\dfrac{AZ}{ZB}$. A point dividing a segment in a given ratio with a given sign is unique, so $Z_1=Z$ ✓'}},
  {'t': 'note',
   'text': {'ru': r'Формулы Чевы и Менелая выглядят одинаково — произведение трёх отношений равно $1$. Различить их помогает знаковая запись: если отношения считать **ориентированными** (со знаком), то у Чевы произведение равно $+1$, а у Менелая $-1$. Отсюда и «нечётное число внешних точек» в формулировке.',
            'en': r'The formulas of Ceva and Menelaus look identical — a product of three ratios equal to $1$. Signs tell them apart: with **directed** ratios the product is $+1$ for Ceva and $-1$ for Menelaus. That is where "an odd number of outside points" comes from.'}},

  {'t': 'ex',
   'q': {'ru': r'На стороне $BC$ треугольника $ABC$ взята точка $X$ с $BX:XC=2:3$, а на стороне $AB$ — точка $Z$ с $AZ:ZB=1:2$. Прямая $XZ$ пересекает прямую $AC$ в точке $Y$. Найдите отношение $CY:YA$.',
         'en': r'On the side $BC$ of a triangle $ABC$ take $X$ with $BX:XC=2:3$, and on $AB$ take $Z$ with $AZ:ZB=1:2$. The line $XZ$ meets the line $AC$ at $Y$. Find the ratio $CY:YA$.'},
   'steps': {'ru': [r'Точки $X$, $Y$, $Z$ лежат на одной прямой, значит применима теорема Менелая: $$\frac{BX}{XC}\cdot\frac{CY}{YA}\cdot\frac{AZ}{ZB}=1 .$$',
                    r'Подставим известные отношения: $$\frac23\cdot\frac{CY}{YA}\cdot\frac12=1 .$$',
                    r'Значит $\dfrac{CY}{YA}=3$.',
                    r'Две из трёх точек ($X$ и $Z$) лежат **внутри** сторон, поэтому третья должна лежать снаружи: $Y$ находится на продолжении стороны $AC$ ✓'],
             'en': [r'The points $X$, $Y$, $Z$ are collinear, so Menelaus applies: $$\frac{BX}{XC}\cdot\frac{CY}{YA}\cdot\frac{AZ}{ZB}=1 .$$',
                    r'Substituting the known ratios, $$\frac23\cdot\frac{CY}{YA}\cdot\frac12=1 .$$',
                    r'Hence $\dfrac{CY}{YA}=3$.',
                    r'Two of the three points ($X$ and $Z$) lie **inside** their sides, so the third must lie outside: $Y$ is on the extension of $AC$ ✓']},
   'ans': {'ru': r'$CY:YA=3:1$, точка $Y$ вне отрезка $AC$.',
           'en': r'$CY:YA=3:1$, with $Y$ outside the segment $AC$.'}},

  {'t': 'thm',
   'name': {'ru': 'Тригонометрическая форма теоремы Чевы',
            'en': 'The trigonometric form of Ceva theorem'},
   'text': {'ru': r'Чевианы $AX$, $BY$, $CZ$ пересекаются в одной точке тогда и только тогда, когда $$\frac{\sin\angle BAX}{\sin\angle XAC}\cdot\frac{\sin\angle ACZ}{\sin\angle ZCB}\cdot\frac{\sin\angle CBY}{\sin\angle YBA}=1 .$$',
            'en': r'The cevians $AX$, $BY$, $CZ$ concur if and only if $$\frac{\sin\angle BAX}{\sin\angle XAC}\cdot\frac{\sin\angle ACZ}{\sin\angle ZCB}\cdot\frac{\sin\angle CBY}{\sin\angle YBA}=1 .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Достаточно выразить отношение $\dfrac{BX}{XC}$ через синусы и подставить в обычную теорему Чевы.\n\nСравним площади треугольников $ABX$ и $AXC$ двумя способами. У них общая высота из $A$, поэтому $$\frac{S_{ABX}}{S_{AXC}}=\frac{BX}{XC}.$$ С другой стороны, у них общая сторона $AX$, и по формуле $S=\tfrac12 xy\sin\varphi$ $$\frac{S_{ABX}}{S_{AXC}}=\frac{AB\cdot AX\sin\angle BAX}{AC\cdot AX\sin\angle XAC}=\frac{AB\sin\angle BAX}{AC\sin\angle XAC}.$$\n\nЗначит $$\frac{BX}{XC}=\frac{c\,\sin\angle BAX}{b\,\sin\angle XAC},$$ и аналогично для двух других отношений. Перемножив три равенства, длины $a,b,c$ сократятся (каждая войдёт один раз в числитель и один раз в знаменатель), и обычное условие Чевы превратится в тригонометрическое ✓ $\blacksquare$',
            'en': r'It suffices to express $\dfrac{BX}{XC}$ through sines and substitute into ordinary Ceva.\n\nCompare the areas of $ABX$ and $AXC$ two ways. They share the altitude from $A$, so $$\frac{S_{ABX}}{S_{AXC}}=\frac{BX}{XC}.$$ They also share the side $AX$, so by $S=\tfrac12 xy\sin\varphi$ $$\frac{S_{ABX}}{S_{AXC}}=\frac{AB\sin\angle BAX}{AC\sin\angle XAC}.$$\n\nHence $$\frac{BX}{XC}=\frac{c\,\sin\angle BAX}{b\,\sin\angle XAC},$$ and similarly for the other two ratios. Multiplying the three, the lengths $a,b,c$ cancel (each appears once above and once below), turning ordinary Ceva into the trigonometric form ✓ $\blacksquare$'}},
  {'t': 'idea',
   'text': {'ru': r'Тригонометрическая форма незаменима, когда чевианы заданы **углами**, а не отношениями: биссектрисы, высоты, чевианы, делящие углы в данном отношении, изогонали. Например, конкурентность высот получается мгновенно: $\dfrac{\sin\left(90^{\circ}-B\right)}{\sin\left(90^{\circ}-C\right)}$ и два аналогичных множителя дают в произведении $1$.',
            'en': r'The trigonometric form is indispensable when the cevians are given by **angles** rather than ratios: bisectors, altitudes, cevians splitting an angle in a given ratio, isogonals. For instance the concurrence of the altitudes drops out at once: $\dfrac{\sin\left(90^{\circ}-B\right)}{\sin\left(90^{\circ}-C\right)}$ and the two similar factors multiply to $1$.'}},
 ],
}

SECTIONS = [(1, FORMULAS), (4, MENELAUS)]

INTO = {
 2: [
  {'t': 'thm',
   'name': {'ru': 'Лемма об отношении на чевиане',
            'en': 'The ratio lemma on a cevian'},
   'text': {'ru': r'Пусть чевиана $AX$ проведена к стороне $BC$, а точка $P$ лежит на ней. Тогда $$\frac{AP}{PX}=\frac{S_{ABP}+S_{ACP}}{S_{BPC}}\qquad\text{и}\qquad \frac{BX}{XC}=\frac{S_{ABP}}{S_{ACP}} .$$',
            'en': r'Let $AX$ be a cevian to the side $BC$ and let $P$ lie on it. Then $$\frac{AP}{PX}=\frac{S_{ABP}+S_{ACP}}{S_{BPC}}\qquad\text{and}\qquad \frac{BX}{XC}=\frac{S_{ABP}}{S_{ACP}} .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Треугольники $ABP$ и $XBP$ имеют общее основание $BP$, а вершины $A$ и $X$ лежат на одной прямой, поэтому отношение их площадей равно отношению расстояний от $A$ и $X$ до прямой $BP$, то есть $\dfrac{AP}{PX}$. То же верно для пары $ACP$ и $XCP$.\n\nСложим числители и знаменатели двух равных дробей — отношение не изменится: $$\frac{AP}{PX}=\frac{S_{ABP}}{S_{XBP}}=\frac{S_{ACP}}{S_{XCP}}=\frac{S_{ABP}+S_{ACP}}{S_{XBP}+S_{XCP}}=\frac{S_{ABP}+S_{ACP}}{S_{BPC}} \quad\checkmark$$\n\nВторое равенство: треугольники $ABX$ и $AXC$ (общая высота из $A$) дают $\dfrac{BX}{XC}=\dfrac{S_{ABX}}{S_{AXC}}$, а треугольники $PBX$ и $PXC$ (общая высота из $P$) дают то же отношение. Вычитая площади, получаем $$\frac{BX}{XC}=\frac{S_{ABX}-S_{PBX}}{S_{AXC}-S_{PXC}}=\frac{S_{ABP}}{S_{ACP}} \quad\checkmark\qquad\blacksquare$$',
            'en': r'The triangles $ABP$ and $XBP$ share the base $BP$, and $A$, $X$ lie on one line, so the ratio of their areas equals the ratio of the distances from $A$ and $X$ to the line $BP$, namely $\dfrac{AP}{PX}$. The same holds for the pair $ACP$, $XCP$.\n\nAdding numerators and denominators of two equal fractions does not change their value: $$\frac{AP}{PX}=\frac{S_{ABP}}{S_{XBP}}=\frac{S_{ACP}}{S_{XCP}}=\frac{S_{ABP}+S_{ACP}}{S_{BPC}} \quad\checkmark$$\n\nFor the second: $ABX$ and $AXC$ (common altitude from $A$) give $\dfrac{BX}{XC}=\dfrac{S_{ABX}}{S_{AXC}}$, and $PBX$, $PXC$ (common altitude from $P$) give the same ratio. Subtracting areas, $$\frac{BX}{XC}=\frac{S_{ABX}-S_{PBX}}{S_{AXC}-S_{PXC}}=\frac{S_{ABP}}{S_{ACP}} \quad\checkmark\qquad\blacksquare$$'}},
  {'t': 'idea',
   'text': {'ru': r'Эта лемма превращает **любое** отношение отрезков в отношение площадей и обратно. Стандартная схема решения «методом площадей»: обозначьте площади трёх маленьких треугольников через $x$, $y$, $z$, выпишите данные условия как уравнения на них, решите систему — и переведите ответ обратно в отношение отрезков.',
            'en': r'This lemma converts **any** ratio of segments into a ratio of areas and back. The standard scheme of the area method: call the areas of the three small triangles $x$, $y$, $z$, write the hypotheses as equations in them, solve, then translate the answer back into a ratio of segments.'}},
  {'t': 'ex',
   'q': {'ru': r'Медианы треугольника пересекаются в точке $G$. Докажите методом площадей, что $AG:GM=2:1$, где $M$ — середина $BC$.',
         'en': r'The medians of a triangle meet at $G$. Use the area method to prove that $AG:GM=2:1$, where $M$ is the midpoint of $BC$.'},
   'steps': {'ru': [r'Обозначим $S_{BGC}=x$, $S_{CGA}=y$, $S_{AGB}=z$.',
                    r'Медиана $AM$ делит $BC$ пополам, значит по лемме $\dfrac{BM}{MC}=\dfrac{S_{ABG}}{S_{ACG}}=\dfrac{z}{y}=1$, то есть $y=z$.',
                    r'Медиана из $B$ даёт точно так же $x=y$. Значит $x=y=z$ — три площади равны.',
                    r'По первой части леммы $$\frac{AG}{GM}=\frac{S_{ABG}+S_{ACG}}{S_{BGC}}=\frac{z+y}{x}=\frac{2x}{x}=2 \quad\checkmark$$',
                    r'Попутно доказано, что медианы делят треугольник на три равновеликие части (а с учётом половинок — на шесть).'],
             'en': [r'Write $S_{BGC}=x$, $S_{CGA}=y$, $S_{AGB}=z$.',
                    r'The median $AM$ bisects $BC$, so the lemma gives $\dfrac{BM}{MC}=\dfrac{z}{y}=1$, i.e. $y=z$.',
                    r'The median from $B$ gives $x=y$ in the same way. So $x=y=z$ — the three areas are equal.',
                    r'The first part of the lemma now gives $$\frac{AG}{GM}=\frac{z+y}{x}=\frac{2x}{x}=2 \quad\checkmark$$',
                    r'On the way we proved that the medians cut the triangle into three pieces of equal area (and, halving each, into six).']},
   'ans': {'ru': r'$AG:GM=2:1$.', 'en': r'$AG:GM=2:1$.'}},
 ],
 4: [
  {'t': 'proof',
   'text': {'ru': r'**Идея доказательства формулы Пика.** Полное доказательство состоит из двух шагов.\n\n**Шаг 1: аддитивность.** Определим для многоугольника величину $$f(P)=B+\frac{\Gamma}{2}-1 ,$$ где $B$ — число внутренних, $\Gamma$ — число граничных узлов. Пусть многоугольник разрезан диагональю на два, $P=P_1\cup P_2$, и пусть на разрезе лежит $k$ узлов (включая оба конца). Те $k-2$ узла, что лежат строго внутри разреза, являются внутренними для $P$, но граничными для каждой из двух частей. Подсчёт даёт $$B=B_1+B_2+\left(k-2\right),\qquad \Gamma=\Gamma_1+\Gamma_2-2\left(k-2\right)-2 .$$ Подставив, получаем $f(P)=f(P_1)+f(P_2)$ — величина $f$ аддитивна, как и площадь.\n\n**Шаг 2: база.** Всякий многоугольник с вершинами в узлах разрезается диагоналями на треугольники, а любой такой треугольник — на «элементарные», не содержащие узлов ни внутри, ни на сторонах, кроме вершин. Для элементарного треугольника $B=0$, $\Gamma=3$, поэтому $f=\tfrac32-1=\tfrac12$. Его площадь тоже равна $\tfrac12$: два таких треугольника складываются в параллелограмм, порождённый двумя векторами базиса решётки, площадь которого равна $1$.\n\nВеличины $f$ и $S$ аддитивны и совпадают на элементарных треугольниках, значит совпадают всюду ✓ $\blacksquare$',
            'en': r'**How the formula of Pick is proved.** The proof has two steps.\n\n**Step 1: additivity.** For a lattice polygon define $$f(P)=B+\frac{\Gamma}{2}-1 ,$$ where $B$ counts interior and $\Gamma$ boundary lattice points. Cut $P$ by a diagonal into $P_1$ and $P_2$, and let the cut carry $k$ lattice points (both endpoints included). The $k-2$ interior points of the cut are interior to $P$ but boundary points of both pieces, so $$B=B_1+B_2+\left(k-2\right),\qquad \Gamma=\Gamma_1+\Gamma_2-2\left(k-2\right)-2 .$$ Substituting gives $f(P)=f(P_1)+f(P_2)$ — the quantity $f$ is additive, just like area.\n\n**Step 2: the base case.** Every lattice polygon can be cut by diagonals into triangles, and every lattice triangle into "elementary" ones containing no lattice points except their vertices. For an elementary triangle $B=0$, $\Gamma=3$, so $f=\tfrac32-1=\tfrac12$. Its area is also $\tfrac12$: two copies form a parallelogram spanned by a basis of the lattice, whose area is $1$.\n\nBoth $f$ and $S$ are additive and agree on elementary triangles, so they agree everywhere ✓ $\blacksquare$'}},
  {'t': 'warn',
   'text': {'ru': r'Формула Пика верна только для многоугольников **с вершинами в узлах решётки** и **без самопересечений**. Для многоугольника с дыркой она принимает вид $$S=B+\frac{\Gamma}{2}-1+\left(h-1\right)\cdot\left(-1\right)\ \Rightarrow\ S=B+\frac{\Gamma}{2}+h-2 ,$$ где $h$ — число дырок. И, разумеется, она ничего не говорит о фигурах с криволинейной границей.',
            'en': r'The formula of Pick holds only for polygons **with vertices at lattice points** and **without self-intersections**. For a polygon with holes it becomes $$S=B+\frac{\Gamma}{2}+h-2 ,$$ where $h$ is the number of holes. And of course it says nothing about regions with curved boundaries.'}},
 ],
}
