# -*- coding: utf-8 -*-
"""Topic 2 — deeper theory, woven into lesson_02.py by content/build.py."""

SPECIAL_FORMS = {
 'h': {'ru': 'Бесконечность простых особого вида',
       'en': 'Infinitely many primes of a special shape'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Теорема Евклида говорит, что простых бесконечно много. Естественный следующий вопрос: а бесконечно ли много простых **каждого** допустимого вида — $4k+1$, $4k+3$, $6k+5$? Для некоторых форм ответ получается тем же приёмом, что и у Евклида.',
            'en': r'Euclid’s theorem says the primes never run out. The natural next question: are there infinitely many primes of **each** admissible shape — $4k+1$, $4k+3$, $6k+5$? For some shapes Euclid’s own trick still works.'}},

  {'t': 'lemma',
   'name': {'ru': 'Произведение сохраняет форму', 'en': 'Products keep the shape'},
   'text': {'ru': r'Произведение чисел вида $4k+1$ снова имеет вид $4k+1$. То же верно для формы $6k+1$.',
            'en': r'A product of numbers of the form $4k+1$ is again of the form $4k+1$. The same holds for the form $6k+1$.'}},
  {'t': 'proof',
   'text': {'ru': r'Прямое вычисление: $$(4a+1)(4b+1)=16ab+4a+4b+1=4(4ab+a+b)+1 ,$$ $$(6a+1)(6b+1)=36ab+6a+6b+1=6(6ab+a+b)+1 .$$ Индукцией это распространяется на любое число сомножителей. $\blacksquare$',
            'en': r'Direct computation: $$(4a+1)(4b+1)=4(4ab+a+b)+1 ,$$ $$(6a+1)(6b+1)=6(6ab+a+b)+1 .$$ Induction extends this to any number of factors. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Простых вида $4k+3$ бесконечно много', 'en': 'There are infinitely many primes $4k+3$'},
   'text': {'ru': r'Множество простых, дающих остаток $3$ при делении на $4$, бесконечно.',
            'en': r'The set of primes leaving remainder $3$ on division by $4$ is infinite.'}},
  {'t': 'proof',
   'text': {'ru': r'Предположим противное: таких простых конечное число, $p_1=3,\ p_2,\ \dots,\ p_k$. Рассмотрим $$N=4p_1p_2\cdots p_k-1 .$$\n\nЧисло $N$ нечётно и $N\equiv-1\equiv3\pmod4$.\n\nВсе простые делители $N$ нечётны, то есть каждый имеет вид $4k+1$ или $4k+3$. Если бы все они были вида $4k+1$, то по лемме и само $N$ было бы вида $4k+1$ ✗ Значит у $N$ есть простой делитель $q$ вида $4k+3$.\n\nПо предположению $q$ — одно из $p_i$, но тогда $q$ делит и произведение $4p_1\cdots p_k$, и $N$, а значит делит их разность $$4p_1\cdots p_k-N=1 ,$$ что невозможно ✗ $\blacksquare$',
            'en': r'Suppose not: the primes of this form are $p_1=3,\ p_2,\ \dots,\ p_k$. Consider $$N=4p_1p_2\cdots p_k-1 .$$\n\nThen $N$ is odd and $N\equiv3\pmod4$.\n\nEvery prime divisor of $N$ is odd, hence of the form $4k+1$ or $4k+3$. If all were $4k+1$, the lemma would make $N$ itself $4k+1$ ✗ So $N$ has a prime divisor $q\equiv3\pmod4$.\n\nBy assumption $q$ is one of the $p_i$; then $q$ divides both $4p_1\cdots p_k$ and $N$, hence their difference $$4p_1\cdots p_k-N=1 ,$$ which is impossible ✗ $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Повторите рассуждение для формы $6k+5$ и проверьте его на первых простых.',
         'en': r'Repeat the argument for the shape $6k+5$ and test it on the first few primes.'},
   'steps': {'ru': [r'Возьмём $N=6p_1p_2\cdots p_k-1$, где $p_i$ — все простые вида $6k+5$.',
                    r'Тогда $N\equiv5\pmod6$; в частности $N$ нечётно и не делится на $3$.',
                    r'Значит все простые делители $N$ отличны от $2$ и $3$, то есть имеют вид $6k+1$ или $6k+5$.',
                    r'Если бы все были вида $6k+1$, то и $N$ было бы таким — противоречие с $N\equiv5$.',
                    r'Дальше — как в теореме: делитель вида $6k+5$ обязан делить единицу ✗',
                    r'Проверка на малых числах: $6\cdot5-1=29$ — простое вида $6k+5$ ✓'],
             'en': [r'Take $N=6p_1p_2\cdots p_k-1$ with $p_i$ all the primes of the form $6k+5$.',
                    r'Then $N\equiv5\pmod6$; in particular $N$ is odd and not divisible by $3$.',
                    r'So every prime divisor of $N$ is neither $2$ nor $3$, hence of the form $6k+1$ or $6k+5$.',
                    r'If all were $6k+1$, so would $N$ be — contradicting $N\equiv5$.',
                    r'The rest is as in the theorem: such a divisor would have to divide $1$ ✗',
                    r'A small check: $6\cdot5-1=29$ is prime and $\equiv5\pmod6$ ✓']},
   'ans': {'ru': r'Простых вида $6k+5$ тоже бесконечно много.',
           'en': r'There are infinitely many primes of the form $6k+5$ as well.'}},

  {'t': 'warn',
   'text': {'ru': r'Для формы $4k+1$ этот приём **не проходит**: произведение чисел вида $4k+3$ может дать как $4k+1$, так и $4k+3$, поэтому «лишний» делитель не выделяется. Бесконечность простых вида $4k+1$ доказывается иначе — через тот факт, что нечётный простой делитель числа $n^{2}+1$ всегда сравним с $1$ по модулю $4$.',
            'en': r'For the shape $4k+1$ this trick **fails**: a product of numbers $\equiv3\pmod4$ can be either $1$ or $3$ mod $4$, so no divisor is forced. Infinitude for $4k+1$ is proved differently — via the fact that every odd prime divisor of $n^{2}+1$ is $\equiv1\pmod4$.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Дирихле', 'en': 'Dirichlet’s theorem'},
   'text': {'ru': r'Если $\gcd(a,d)=1$, то в арифметической прогрессии $$a,\ a+d,\ a+2d,\ a+3d,\ \dots$$ содержится бесконечно много простых чисел.',
            'en': r'If $\gcd(a,d)=1$ then the arithmetic progression $$a,\ a+d,\ a+2d,\ a+3d,\ \dots$$ contains infinitely many primes.'}},
  {'t': 'note',
   'text': {'ru': r'Доказательство теоремы Дирихле выходит далеко за рамки школьной математики: оно использует аналитические методы (ряды Дирихле и $L$-функции). Но пользоваться формулировкой можно — она объясняет, почему отдельные случаи вроде $4k+3$ и $6k+5$ вообще имеют шанс быть верными.\n\n**Условие $\gcd(a,d)=1$ необходимо:** в прогрессии $2,4,6,8,\dots$ простое ровно одно.',
            'en': r'Proving Dirichlet’s theorem goes far beyond school mathematics: it uses analytic tools (Dirichlet series and $L$-functions). The statement is still worth knowing — it explains why special cases like $4k+3$ and $6k+5$ stand a chance at all.\n\n**The hypothesis $\gcd(a,d)=1$ is necessary:** the progression $2,4,6,8,\dots$ contains exactly one prime.'}},
 ],
}


DISTRIBUTION = {
 'h': {'ru': 'Как простые расположены среди чисел',
       'en': 'How the primes are spread out'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Простых бесконечно много — но насколько густо они расставлены? Оказывается, они и «редеют», и при этом никогда не исчезают надолго.',
            'en': r'The primes never run out — but how densely are they placed? They thin out, and yet they never disappear for long.'}},

  {'t': 'thm',
   'name': {'ru': 'Промежутки бывают сколь угодно длинными', 'en': 'Arbitrarily long prime-free gaps'},
   'text': {'ru': r'Для любого $n$ существуют $n$ подряд идущих составных чисел.',
            'en': r'For every $n$ there exist $n$ consecutive composite numbers.'}},
  {'t': 'proof',
   'text': {'ru': r'Положим $M=(n+1)!$ и рассмотрим числа $$M+2,\ M+3,\ \dots,\ M+(n+1).$$\n\nВозьмём любое $k$ с $2\le k\le n+1$. Тогда $k$ входит множителем в $(n+1)!$, значит $k\mid M$, а также $k\mid k$, поэтому $$k\ \big|\ M+k .$$\n\nПри этом $M+k>k>1$, значит у числа $M+k$ есть делитель, отличный от единицы и от него самого — оно составное.\n\nВсе $n$ чисел оказались составными. $\blacksquare$',
            'en': r'Put $M=(n+1)!$ and consider $$M+2,\ M+3,\ \dots,\ M+(n+1).$$\n\nTake any $k$ with $2\le k\le n+1$. Then $k$ is a factor of $(n+1)!$, so $k\mid M$ and $k\mid k$, hence $$k\ \big|\ M+k .$$\n\nSince $M+k>k>1$, the number $M+k$ has a divisor other than $1$ and itself — it is composite.\n\nAll $n$ numbers are composite. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Постулат Бертрана', 'en': 'Bertrand’s postulate'},
   'text': {'ru': r'Для любого целого $n\ge1$ между $n$ и $2n$ найдётся простое число: $$n<p\le2n .$$',
            'en': r'For every integer $n\ge1$ there is a prime between $n$ and $2n$: $$n<p\le2n .$$'}},
  {'t': 'note',
   'text': {'ru': r'Постулат высказан Бертраном в $1845$ году и доказан Чебышёвым в $1852$-м; изящное элементарное доказательство дал Эрдёш в $1932$-м, оценивая биномиальный коэффициент $\binom{2n}{n}$.\n\n**Как этим пользуются.** Утверждение «между $n$ и $2n$ всегда есть простое» позволяет строить нужные простые в задачах: например, доказать, что при $n>1$ число $n!$ не является точной степенью, или что сумма $1+\tfrac12+\dots+\tfrac1n$ не целая.',
            'en': r'Bertrand stated it in $1845$; Chebyshev proved it in $1852$, and Erdős gave an elegant elementary proof in $1932$ by estimating the binomial coefficient $\binom{2n}{n}$.\n\n**How it is used.** "There is always a prime between $n$ and $2n$" lets one manufacture a prime when a problem needs one: to show that $n!$ is never a perfect power for $n>1$, say, or that $1+\tfrac12+\dots+\tfrac1n$ is never an integer.'}},

  {'t': 'ex',
   'q': {'ru': r'Пользуясь постулатом Бертрана, докажите, что сумма $H_n=1+\tfrac12+\dots+\tfrac1n$ не является целым числом при $n\ge2$.',
         'en': r'Using Bertrand’s postulate, prove that $H_n=1+\tfrac12+\dots+\tfrac1n$ is never an integer for $n\ge2$.'},
   'steps': {'ru': [r'По постулату Бертрана существует простое $p$ с $\tfrac n2<p\le n$.',
                    r'Тогда $p\le n$, значит слагаемое $\tfrac1p$ в сумме присутствует.',
                    r'При этом $2p>n$, значит среди $1,2,\dots,n$ кратно $p$ только само $p$ — никакой другой знаменатель на $p$ не делится.',
                    r'Приведём сумму к общему знаменателю $L=\operatorname{lcm}(1,2,\dots,n)$. Показатель $p$ в $L$ равен единице.',
                    r'В числителе все слагаемые, кроме одного, содержат множитель $p$; слагаемое от $\tfrac1p$ его не содержит.',
                    r'Значит числитель не делится на $p$, а знаменатель делится — дробь не сокращается до целого ✗'],
             'en': [r'Bertrand gives a prime $p$ with $\tfrac n2<p\le n$.',
                    r'Since $p\le n$, the term $\tfrac1p$ appears in the sum.',
                    r'Since $2p>n$, the only multiple of $p$ among $1,\dots,n$ is $p$ itself — no other denominator is divisible by $p$.',
                    r'Put the sum over the common denominator $L=\operatorname{lcm}(1,\dots,n)$, in which $p$ appears to the first power.',
                    r'In the numerator every term except one carries a factor $p$; the term coming from $\tfrac1p$ does not.',
                    r'So the numerator is not divisible by $p$ while the denominator is — the fraction cannot be an integer ✗']},
   'ans': {'ru': r'$H_n$ не целое ни при каком $n\ge2$.',
           'en': r'$H_n$ is not an integer for any $n\ge2$.'}},

  {'t': 'thm',
   'name': {'ru': 'Закон распределения простых', 'en': 'The prime number theorem'},
   'text': {'ru': r'Обозначим через $\pi(x)$ количество простых, не превосходящих $x$. Тогда $$\pi(x)\ \sim\ \frac{x}{\ln x},$$ то есть отношение $\pi(x)\big/\dfrac{x}{\ln x}$ стремится к единице при $x\to\infty$.',
            'en': r'Write $\pi(x)$ for the number of primes up to $x$. Then $$\pi(x)\ \sim\ \frac{x}{\ln x},$$ meaning the ratio $\pi(x)\big/\dfrac{x}{\ln x}$ tends to one as $x\to\infty$.'}},
  {'t': 'table',
   'head': {'ru': ['$x$', '$\\pi(x)$', '$x/\\ln x$', 'отношение'],
            'en': ['$x$', '$\\pi(x)$', '$x/\\ln x$', 'ratio']},
   'rows': {'ru': [['$10^{2}$', '$25$', '$21{,}7$', '$1{,}15$'],
                   ['$10^{4}$', '$1229$', '$1086$', '$1{,}13$'],
                   ['$10^{6}$', '$78\\,498$', '$72\\,382$', '$1{,}08$'],
                   ['$10^{8}$', '$5\\,761\\,455$', '$5\\,428\\,681$', '$1{,}06$']],
            'en': [['$10^{2}$', '$25$', '$21.7$', '$1.15$'],
                   ['$10^{4}$', '$1229$', '$1086$', '$1.13$'],
                   ['$10^{6}$', '$78\\,498$', '$72\\,382$', '$1.08$'],
                   ['$10^{8}$', '$5\\,761\\,455$', '$5\\,428\\,681$', '$1.06$']]}},
  {'t': 'note',
   'text': {'ru': r'Теорема доказана в $1896$ году независимо Адамаром и Валле-Пуссеном; элементарное (но всё равно трудное) доказательство нашли Эрдёш и Сельберг в $1949$-м.\n\n**Что она означает на практике.** Вблизи числа $x$ доля простых примерно равна $\tfrac1{\ln x}$. Среди стозначных чисел простым оказывается примерно каждое $230$-е — именно поэтому криптографические ключи удаётся находить случайным перебором.',
            'en': r'The theorem was proved in $1896$ independently by Hadamard and de la Vallée Poussin; an elementary (though still hard) proof was found by Erdős and Selberg in $1949$.\n\n**What it means in practice.** Near $x$ the proportion of primes is about $\tfrac1{\ln x}$. Roughly one in $230$ hundred-digit numbers is prime — which is why cryptographic keys can be found by random search.'}},

  {'t': 'note',
   'text': {'ru': r'**Открытые вопросы.** Про простые известно гораздо меньше, чем кажется. До сих пор не доказаны: гипотеза о простых-близнецах (бесконечно ли много пар $p$, $p+2$), гипотеза Гольдбаха (всякое чётное число, большее двух, — сумма двух простых), бесконечность простых вида $n^{2}+1$. Все они проверены компьютером до колоссальных границ, но проверка — не доказательство.',
            'en': r'**Open questions.** Far less is known about primes than one might think. Still unproved: the twin prime conjecture (are there infinitely many pairs $p$, $p+2$), Goldbach’s conjecture (every even number above two is a sum of two primes), the infinitude of primes of the form $n^{2}+1$. All have been checked by computer to enormous bounds — but checking is not proving.'}},
 ],
}


SPECIAL_PRIMES = {
 'h': {'ru': 'Числа Мерсенна и Ферма',
       'en': 'Mersenne and Fermat numbers'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Два семейства чисел веками служат «охотничьими угодьями» для поиска больших простых. Оба устроены так, что показатель степени сильно ограничен — и это ограничение доказывается элементарно.',
            'en': r'Two families of numbers have been the hunting grounds for large primes for centuries. In both, the exponent is severely constrained — and the constraint has an elementary proof.'}},

  {'t': 'thm',
   'name': {'ru': 'Показатель числа Мерсенна прост', 'en': 'A Mersenne exponent must be prime'},
   'text': {'ru': r'Если число $2^{n}-1$ простое, то и $n$ простое.',
            'en': r'If $2^{n}-1$ is prime then $n$ is prime.'}},
  {'t': 'proof',
   'text': {'ru': r'Докажем противоположное: если $n$ составное, то и $2^{n}-1$ составное.\n\nПусть $n=ab$ с $1<a,b<n$. Воспользуемся тождеством $$x^{b}-1=(x-1)\left(x^{\,b-1}+x^{\,b-2}+\dots+x+1\right)$$ при $x=2^{a}$: $$2^{n}-1=\left(2^{a}\right)^{b}-1=\left(2^{a}-1\right)\left(2^{a(b-1)}+\dots+2^{a}+1\right).$$\n\nОстаётся проверить, что оба множителя больше единицы. Первый: $a\ge2$ даёт $2^{a}-1\ge3$. Второй — сумма $b\ge2$ положительных слагаемых, каждое не меньше единицы, значит он не меньше $2$.\n\nЗначит $2^{n}-1$ составное. $\blacksquare$',
            'en': r'We prove the contrapositive: if $n$ is composite then so is $2^{n}-1$.\n\nLet $n=ab$ with $1<a,b<n$. Use the identity $$x^{b}-1=(x-1)\left(x^{\,b-1}+\dots+x+1\right)$$ with $x=2^{a}$: $$2^{n}-1=\left(2^{a}-1\right)\left(2^{a(b-1)}+\dots+2^{a}+1\right).$$\n\nBoth factors exceed one: $a\ge2$ gives $2^{a}-1\ge3$, and the second is a sum of $b\ge2$ terms each at least $1$.\n\nSo $2^{n}-1$ is composite. $\blacksquare$'}},
  {'t': 'warn',
   'text': {'ru': r'Обратное **неверно**: простота $n$ не гарантирует простоты $2^{n}-1$. Наименьший контрпример — $$2^{11}-1=2047=23\cdot89 ,$$ хотя $11$ простое.',
            'en': r'The converse is **false**: $n$ prime does not make $2^{n}-1$ prime. The smallest counterexample is $$2^{11}-1=2047=23\cdot89 ,$$ although $11$ is prime.'}},

  {'t': 'thm',
   'name': {'ru': 'Показатель числа Ферма — степень двойки', 'en': 'A Fermat exponent must be a power of two'},
   'text': {'ru': r'Если число $2^{n}+1$ простое при $n\ge1$, то $n$ — степень двойки.',
            'en': r'If $2^{n}+1$ is prime for some $n\ge1$, then $n$ is a power of two.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть $n$ **не** степень двойки. Тогда у $n$ есть нечётный делитель $m>1$; запишем $n=km$.\n\nВоспользуемся тождеством для **нечётного** $m$: $$x^{m}+1=(x+1)\left(x^{\,m-1}-x^{\,m-2}+\dots-x+1\right)$$ (знаки чередуются, и последний член равен $+1$ именно потому, что $m$ нечётно). Подставим $x=2^{k}$: $$2^{n}+1=\left(2^{k}\right)^{m}+1=\left(2^{k}+1\right)\left(\dots\right).$$\n\nПервый множитель $2^{k}+1\ge3$, а второй равен $\dfrac{2^{n}+1}{2^{k}+1}$ и больше единицы, потому что $m>1$ означает $n>k$.\n\nЗначит $2^{n}+1$ составное — противоречие. $\blacksquare$',
            'en': r'Suppose $n$ is **not** a power of two. Then $n$ has an odd divisor $m>1$; write $n=km$.\n\nUse the identity for **odd** $m$: $$x^{m}+1=(x+1)\left(x^{\,m-1}-x^{\,m-2}+\dots-x+1\right)$$ (the signs alternate, and the last term is $+1$ precisely because $m$ is odd). Substitute $x=2^{k}$: $$2^{n}+1=\left(2^{k}+1\right)\left(\dots\right).$$\n\nThe first factor is $2^{k}+1\ge3$, and the second equals $\dfrac{2^{n}+1}{2^{k}+1}>1$ because $m>1$ means $n>k$.\n\nSo $2^{n}+1$ is composite — a contradiction. $\blacksquare$'}},

  {'t': 'def',
   'name': {'ru': 'Числа Ферма', 'en': 'Fermat numbers'},
   'text': {'ru': r'$F_n=2^{2^{n}}+1$. Первые из них $$F_0=3,\quad F_1=5,\quad F_2=17,\quad F_3=257,\quad F_4=65\,537 $$ — все простые. Ферма предположил, что простыми будут все, но Эйлер в $1732$ году нашёл, что $$F_5=4\,294\,967\,297=641\cdot6\,700\,417 .$$',
            'en': r'$F_n=2^{2^{n}}+1$. The first few, $$F_0=3,\quad F_1=5,\quad F_2=17,\quad F_3=257,\quad F_4=65\,537 ,$$ are all prime. Fermat conjectured they always would be, but in $1732$ Euler found $$F_5=4\,294\,967\,297=641\cdot6\,700\,417 .$$'}},

  {'t': 'thm',
   'name': {'ru': 'Числа Ферма попарно взаимно просты', 'en': 'Fermat numbers are pairwise coprime'},
   'text': {'ru': r'При $m\ne n$ выполняется $\gcd\left(F_m,F_n\right)=1$. Отсюда получается ещё одно доказательство бесконечности множества простых.',
            'en': r'For $m\ne n$ we have $\gcd\left(F_m,F_n\right)=1$. This yields yet another proof that there are infinitely many primes.'}},
  {'t': 'proof',
   'text': {'ru': r'**Шаг 1: тождество $F_0F_1\cdots F_{n-1}=F_n-2$.** Индукция по $n$. База $n=1$: слева $F_0=3$, справа $5-2=3$ ✓ Переход: если $F_0\cdots F_{n-1}=2^{2^{n}}-1$, то $$F_0\cdots F_{n-1}F_n=\left(2^{2^{n}}-1\right)\left(2^{2^{n}}+1\right)=2^{2^{n+1}}-1=F_{n+1}-2 \quad\checkmark$$\n\n**Шаг 2.** Пусть $m<n$ и $d$ делит и $F_m$, и $F_n$. По шагу 1 число $F_m$ входит множителем в произведение $F_0\cdots F_{n-1}=F_n-2$, значит $d\mid F_n-2$. Вместе с $d\mid F_n$ это даёт $d\mid2$.\n\nНо все числа Ферма нечётны, поэтому $d$ нечётно, откуда $d=1$. $\blacksquare$\n\n**Следствие.** У каждого $F_n$ есть простой делитель, и у разных $F_n$ эти делители различны — значит простых бесконечно много.',
            'en': r'**Step 1: the identity $F_0F_1\cdots F_{n-1}=F_n-2$.** Induction on $n$. Base $n=1$: the left side is $F_0=3$, the right $5-2=3$ ✓ Step: if $F_0\cdots F_{n-1}=2^{2^{n}}-1$ then $$F_0\cdots F_{n-1}F_n=\left(2^{2^{n}}-1\right)\left(2^{2^{n}}+1\right)=2^{2^{n+1}}-1=F_{n+1}-2 \quad\checkmark$$\n\n**Step 2.** Let $m<n$ and let $d$ divide both $F_m$ and $F_n$. By Step 1 the number $F_m$ is a factor of $F_0\cdots F_{n-1}=F_n-2$, so $d\mid F_n-2$. With $d\mid F_n$ this gives $d\mid2$.\n\nBut Fermat numbers are odd, so $d$ is odd and $d=1$. $\blacksquare$\n\n**Corollary.** Each $F_n$ has a prime divisor, and different $F_n$ have different ones — so there are infinitely many primes.'}},

  {'t': 'note',
   'text': {'ru': r'**Зачем это нужно.** Самые большие известные простые — числа Мерсенна: их простоту умеют проверять особенно быстро (тест Люка — Лемера). А числа Ферма связаны с классической геометрией: Гаусс доказал, что правильный $n$-угольник строится циркулем и линейкой ровно тогда, когда $n$ — произведение степени двойки и различных **простых** чисел Ферма. Поэтому строится правильный $17$-угольник, а $7$-угольник — нет.',
            'en': r'**Why they matter.** The largest known primes are Mersenne numbers: their primality can be tested unusually fast (the Lucas–Lehmer test). Fermat numbers connect to classical geometry: Gauss proved that a regular $n$-gon is constructible with ruler and compass exactly when $n$ is a power of two times distinct **prime** Fermat numbers. Hence the regular $17$-gon is constructible and the $7$-gon is not.'}},
 ],
}


SECTIONS = [(3, SPECIAL_FORMS), (5, DISTRIBUTION), (5, SPECIAL_PRIMES)]


INTO = {
 0: [
  {'t': 'thm',
   'name': {'ru': 'Проверка простоты перебором', 'en': 'Primality by trial division'},
   'text': {'ru': r'Число $n>1$ простое тогда и только тогда, когда оно не делится ни на одно простое $p\le\sqrt n$.',
            'en': r'An integer $n>1$ is prime if and only if it is divisible by no prime $p\le\sqrt n$.'}},
  {'t': 'proof',
   'text': {'ru': r'Если $n$ простое, то оно вообще не имеет делителей, кроме $1$ и $n$, и утверждение очевидно.\n\nОбратно, пусть $n$ составное; тогда $n=ab$ с $1<a\le b<n$. Если бы оба множителя превосходили $\sqrt n$, то $$n=ab>\sqrt n\cdot\sqrt n=n \quad ✗$$\n\nЗначит $a\le\sqrt n$. У числа $a>1$ есть простой делитель $p\le a\le\sqrt n$, и он делит $n$. $\blacksquare$',
            'en': r'If $n$ is prime it has no divisors besides $1$ and $n$, and the claim is clear.\n\nConversely let $n$ be composite, $n=ab$ with $1<a\le b<n$. If both factors exceeded $\sqrt n$ then $$n=ab>\sqrt n\cdot\sqrt n=n \quad ✗$$\n\nSo $a\le\sqrt n$. The number $a>1$ has a prime divisor $p\le a\le\sqrt n$, and it divides $n$. $\blacksquare$'}},
  {'t': 'ex',
   'q': {'ru': r'Простое ли число $211$?',
         'en': r'Is $211$ prime?'},
   'steps': {'ru': [r'$14^{2}=196<211<225=15^{2}$, значит достаточно проверить простые до $14$.',
                    r'Это $2,3,5,7,11,13$.',
                    r'$211$ нечётно; сумма цифр $4$ не делится на $3$; не оканчивается на $0$ или $5$.',
                    r'$211=7\cdot30+1$; $211=11\cdot19+2$; $211=13\cdot16+3$.',
                    r'Ни одно не подошло.'],
             'en': [r'$14^{2}=196<211<225=15^{2}$, so it suffices to test primes up to $14$.',
                    r'Those are $2,3,5,7,11,13$.',
                    r'$211$ is odd; its digit sum $4$ is not a multiple of $3$; it ends in neither $0$ nor $5$.',
                    r'$211=7\cdot30+1$; $211=11\cdot19+2$; $211=13\cdot16+3$.',
                    r'None divides it.']},
   'ans': {'ru': r'Да, $211$ простое.', 'en': r'Yes, $211$ is prime.'}},
  {'t': 'idea',
   'text': {'ru': r'Эта теорема — причина, по которой перебор делителей на практике вообще осуществим: чтобы проверить шестизначное число, хватает простых до $1000$, а их всего $168$.',
            'en': r'This theorem is why trial division is feasible at all: to test a six-digit number one needs the primes below $1000$, and there are only $168$ of them.'}},
 ],

 2: [
  {'t': 'note',
   'text': {'ru': r'**Другие доказательства бесконечности.** Приём Евклида — не единственный. Числа Ферма дают доказательство через попарную взаимную простоту (см. ниже). Эйлер получил гораздо более сильный результат: ряд $$\sum_{p\ \text{простое}}\frac1p$$ **расходится**, а это невозможно для конечного набора. Расходимость к тому же говорит, что простые встречаются «чаще», чем квадраты: сумма $\sum\tfrac1{n^{2}}$ сходится.',
            'en': r'**Other proofs of infinitude.** Euclid’s is not the only one. Fermat numbers give a proof via pairwise coprimality (below). Euler proved something far stronger: the series $$\sum_{p\ \text{prime}}\frac1p$$ **diverges**, which is impossible for a finite set. Divergence also says primes are "commoner" than squares, since $\sum\tfrac1{n^{2}}$ converges.'}},
 ],

 4: [
  {'t': 'thm',
   'name': {'ru': 'Почему решето останавливается на $\sqrt N$', 'en': 'Why the sieve stops at $\sqrt N$'},
   'text': {'ru': r'Чтобы найти все простые до $N$, достаточно вычеркнуть кратные простых $p\le\sqrt N$. После этого все невычеркнутые числа, большие единицы, — простые.',
            'en': r'To find all primes up to $N$ it suffices to cross out multiples of the primes $p\le\sqrt N$. Every surviving number greater than one is then prime.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть число $m\le N$ осталось невычеркнутым и $m>1$. Если бы $m$ было составным, у него был бы простой делитель $p\le\sqrt m\le\sqrt N$ (по теореме о проверке простоты). Но кратные всех таких $p$ мы вычеркнули, значит $m$ было бы вычеркнуто ✗\n\nЗначит $m$ простое. $\blacksquare$',
            'en': r'Let $m\le N$ survive and $m>1$. If $m$ were composite it would have a prime divisor $p\le\sqrt m\le\sqrt N$ (by the trial-division theorem). But we crossed out the multiples of every such $p$, so $m$ would have been crossed out ✗\n\nHence $m$ is prime. $\blacksquare$'}},
  {'t': 'idea',
   'text': {'ru': r'Ещё одно ускорение: вычёркивание кратных простого $p$ можно начинать не с $2p$, а сразу с $p^{2}$. Все меньшие кратные $p$ имеют вид $kp$ с $k<p$, а значит уже вычеркнуты как кратные меньшего простого делителя числа $k$.',
            'en': r'One more speed-up: when crossing out multiples of $p$, start at $p^{2}$ rather than $2p$. Every smaller multiple is $kp$ with $k<p$ and has already been crossed out as a multiple of some smaller prime factor of $k$.'}},
  {'t': 'ex',
   'q': {'ru': r'Сколько простых чисел не превосходит $100$, и где решето может остановиться?',
         'en': r'How many primes are there up to $100$, and where may the sieve stop?'},
   'steps': {'ru': [r'$\sqrt{100}=10$, значит вычёркиваем кратные $2,3,5,7$ — и всё.',
                    r'Кратные двойки начинаем с $4$, тройки — с $9$, пятёрки — с $25$, семёрки — с $49$.',
                    r'Остаются $2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97$.',
                    r'Пересчитываем: их $25$.'],
             'en': [r'$\sqrt{100}=10$, so we cross out multiples of $2,3,5,7$ and nothing else.',
                    r'Start the multiples of two at $4$, of three at $9$, of five at $25$, of seven at $49$.',
                    r'What survives is $2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97$.',
                    r'Counting: $25$ of them.']},
   'ans': {'ru': r'$25$ простых; решето останавливается после семёрки.',
           'en': r'$25$ primes; the sieve stops after seven.'}},
 ],
}
