# -*- coding: utf-8 -*-
"""Topic 14 — deeper theory, woven into lesson_14.py by content/build.py."""

CLASSICS = {
 'h': {'ru': 'Классические теоремы, доказанные принципом Дирихле',
       'en': 'Classical theorems proved by the pigeonhole principle'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Принцип Дирихле выглядит настолько простым, что трудно поверить в его силу. Три теоремы ниже — настоящие результаты, входящие в разные разделы математики, и каждая доказывается им в несколько строк.',
            'en': r'The pigeonhole principle looks so simple that its strength is hard to believe. The three theorems below are genuine results from different parts of mathematics, and each is proved by it in a few lines.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Дирихле о приближении',
            'en': 'The approximation theorem of Dirichlet'},
   'text': {'ru': r'Для любого вещественного $\alpha$ и любого натурального $N$ существуют целые $p$ и $q$ с $1\le q\le N$, для которых $$\left|\alpha-\frac{p}{q}\right|<\frac1{qN}\ \le\ \frac1{q^{2}} .$$ В частности, если $\alpha$ иррационально, таких дробей $\dfrac{p}{q}$ бесконечно много.',
            'en': r'For every real $\alpha$ and every positive integer $N$ there are integers $p$ and $q$ with $1\le q\le N$ such that $$\left|\alpha-\frac{p}{q}\right|<\frac1{qN}\ \le\ \frac1{q^{2}} .$$ In particular, if $\alpha$ is irrational there are infinitely many such fractions $\dfrac{p}{q}$.'}},
  {'t': 'proof',
   'text': {'ru': r'Обозначим через $\left\{x\right\}=x-\left\lfloor x\right\rfloor$ дробную часть числа; она всегда лежит в $\left[0,1\right)$.\n\n**Клетки.** Разобьём полуинтервал $\left[0,1\right)$ на $N$ равных частей: $$\left[0,\tfrac1N\right),\ \left[\tfrac1N,\tfrac2N\right),\ \dots,\ \left[\tfrac{N-1}{N},1\right).$$\n\n**Предметы.** Рассмотрим $N+1$ число $$\left\{0\cdot\alpha\right\},\ \left\{1\cdot\alpha\right\},\ \left\{2\cdot\alpha\right\},\ \dots,\ \left\{N\alpha\right\}.$$\n\nПредметов $N+1$, клеток $N$, значит два числа попали в одну клетку: найдутся $0\le i<j\le N$ с $$\left|\left\{j\alpha\right\}-\left\{i\alpha\right\}\right|<\frac1N .$$\n\nРаскроем дробные части: $\left\{j\alpha\right\}-\left\{i\alpha\right\}=\left(j-i\right)\alpha-\left(\left\lfloor j\alpha\right\rfloor-\left\lfloor i\alpha\right\rfloor\right)$. Положим $$q=j-i\in\left[1,N\right],\qquad p=\left\lfloor j\alpha\right\rfloor-\left\lfloor i\alpha\right\rfloor .$$\n\nТогда $\left|q\alpha-p\right|<\dfrac1N$, и после деления на $q>0$ $$\left|\alpha-\frac{p}{q}\right|<\frac1{qN} \quad\checkmark$$\n\nПоскольку $q\le N$, имеем $\dfrac1{qN}\le\dfrac1{q^{2}}$ ✓\n\n**Бесконечность.** Пусть $\alpha$ иррационально и найденных дробей конечное число. Тогда величина $\varepsilon=\min\left|\alpha-\tfrac{p}{q}\right|$ по этому конечному набору строго положительна (иррациональность гарантирует, что ни одна разность не равна нулю). Возьмём $N>\dfrac1\varepsilon$ и применим доказанное: получится дробь с $\left|\alpha-\tfrac{p}{q}\right|<\dfrac1N<\varepsilon$, то есть новая ✓ $\blacksquare$',
            'en': r'Write $\left\{x\right\}=x-\left\lfloor x\right\rfloor$ for the fractional part; it always lies in $\left[0,1\right)$.\n\n**The boxes.** Split $\left[0,1\right)$ into $N$ equal parts $$\left[0,\tfrac1N\right),\ \left[\tfrac1N,\tfrac2N\right),\ \dots,\ \left[\tfrac{N-1}{N},1\right).$$\n\n**The objects.** Consider the $N+1$ numbers $$\left\{0\cdot\alpha\right\},\ \left\{1\cdot\alpha\right\},\ \dots,\ \left\{N\alpha\right\}.$$\n\nThere are $N+1$ objects and $N$ boxes, so two of them share a box: for some $0\le i<j\le N$ $$\left|\left\{j\alpha\right\}-\left\{i\alpha\right\}\right|<\frac1N .$$\n\nExpanding the fractional parts, $\left\{j\alpha\right\}-\left\{i\alpha\right\}=\left(j-i\right)\alpha-\left(\left\lfloor j\alpha\right\rfloor-\left\lfloor i\alpha\right\rfloor\right)$. Put $$q=j-i\in\left[1,N\right],\qquad p=\left\lfloor j\alpha\right\rfloor-\left\lfloor i\alpha\right\rfloor .$$\n\nThen $\left|q\alpha-p\right|<\dfrac1N$, and dividing by $q>0$ $$\left|\alpha-\frac{p}{q}\right|<\frac1{qN} \quad\checkmark$$\n\nSince $q\le N$ we get $\dfrac1{qN}\le\dfrac1{q^{2}}$ ✓\n\n**Infinitude.** Let $\alpha$ be irrational and suppose only finitely many such fractions existed. Then $\varepsilon=\min\left|\alpha-\tfrac{p}{q}\right|$ over that finite list is strictly positive (irrationality guarantees no difference is zero). Take $N>\dfrac1\varepsilon$ and apply the above: it produces a fraction with $\left|\alpha-\tfrac{p}{q}\right|<\dfrac1N<\varepsilon$, hence a new one ✓ $\blacksquare$'}},
  {'t': 'note',
   'text': {'ru': r'Эта теорема объясняет, почему хорошие приближения существуют всегда: например, $\left|\pi-\dfrac{22}{7}\right|\approx0{,}00126<\dfrac1{49}$, а $\left|\pi-\dfrac{355}{113}\right|\approx2{,}7\cdot10^{-7}$, что заметно меньше $\dfrac1{113^{2}}\approx7{,}8\cdot10^{-5}$.',
            'en': r'The theorem explains why good approximations always exist: for instance $\left|\pi-\dfrac{22}{7}\right|\approx0.00126<\dfrac1{49}$, while $\left|\pi-\dfrac{355}{113}\right|\approx2.7\cdot10^{-7}$, comfortably below $\dfrac1{113^{2}}\approx7.8\cdot10^{-5}$.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Эрдёша–Секереша о монотонной подпоследовательности',
            'en': 'The monotone subsequence theorem of Erdos and Szekeres'},
   'text': {'ru': r'Всякая последовательность из $mn+1$ различных вещественных чисел содержит либо возрастающую подпоследовательность длины $m+1$, либо убывающую подпоследовательность длины $n+1$.',
            'en': r'Every sequence of $mn+1$ distinct reals contains either an increasing subsequence of length $m+1$ or a decreasing subsequence of length $n+1$.'}},
  {'t': 'proof',
   'text': {'ru': r'Каждому члену $a_k$ сопоставим **пару чисел** $\left(u_k,v_k\right)$, где $u_k$ — длина самой длинной возрастающей подпоследовательности, **заканчивающейся** на $a_k$, а $v_k$ — длина самой длинной убывающей, заканчивающейся на $a_k$.\n\nПредположим противное: пусть $u_k\le m$ и $v_k\le n$ для всех $k$. Тогда каждая пара $\left(u_k,v_k\right)$ принимает значения в множестве из $mn$ пар — это наши клетки, а $mn+1$ членов последовательности — предметы.\n\nПо принципу Дирихле найдутся два индекса $i<j$ с $$\left(u_i,v_i\right)=\left(u_j,v_j\right).$$\n\nНо это невозможно. Действительно, числа различны, значит либо $a_i<a_j$, либо $a_i>a_j$.\n\n- Если $a_i<a_j$, то возрастающую подпоследовательность, заканчивающуюся на $a_i$, можно продолжить членом $a_j$, поэтому $u_j\ge u_i+1>u_i$ — противоречие.\n- Если $a_i>a_j$, то точно так же $v_j>v_i$ — снова противоречие.\n\nЗначит предположение неверно ✓ $\blacksquare$\n\n**Оценка точна.** Последовательность из $mn$ чисел, разбитая на $n$ убывающих блоков по $m$ членов, каждый следующий блок целиком выше предыдущего, не содержит ни возрастающей длины $m+1$, ни убывающей длины $n+1$.',
            'en': r'To each term $a_k$ attach a **pair** $\left(u_k,v_k\right)$, where $u_k$ is the length of the longest increasing subsequence **ending** at $a_k$ and $v_k$ the length of the longest decreasing one ending at $a_k$.\n\nSuppose the conclusion fails, so $u_k\le m$ and $v_k\le n$ for every $k$. Then each pair $\left(u_k,v_k\right)$ takes one of $mn$ values — these are the boxes, and the $mn+1$ terms are the objects.\n\nPigeonhole gives two indices $i<j$ with $$\left(u_i,v_i\right)=\left(u_j,v_j\right).$$\n\nThat is impossible. The numbers are distinct, so either $a_i<a_j$ or $a_i>a_j$.\n\n- If $a_i<a_j$, an increasing subsequence ending at $a_i$ extends by $a_j$, so $u_j\ge u_i+1>u_i$ — a contradiction.\n- If $a_i>a_j$, the same argument gives $v_j>v_i$ — again a contradiction.\n\nSo the assumption was false ✓ $\blacksquare$\n\n**The bound is sharp.** A sequence of $mn$ numbers split into $n$ decreasing blocks of $m$ terms, each block entirely above the previous one, has no increasing subsequence of length $m+1$ and no decreasing one of length $n+1$.'}},
  {'t': 'ex',
   'q': {'ru': r'В ряд выстроены $101$ человек попарно различного роста. Докажите, что можно выбрать $11$ человек, стоящих подряд по номерам (но не обязательно рядом), рост которых монотонно возрастает или монотонно убывает.',
         'en': r'A line contains $101$ people of pairwise distinct heights. Prove that $11$ of them, in the order they stand (not necessarily adjacent), have monotonically increasing or monotonically decreasing heights.'},
   'steps': {'ru': [r'Возьмём $m=n=10$. Тогда $mn+1=101$ — ровно столько людей и стоит.',
                    r'По теореме Эрдёша–Секереша найдётся возрастающая подпоследовательность длины $m+1=11$ или убывающая длины $n+1=11$ ✓',
                    r'Оценка точна: из $100$ человек такой выбор может быть невозможен (десять убывающих блоков по десять человек, каждый следующий блок выше предыдущего).'],
             'en': [r'Take $m=n=10$; then $mn+1=101$, exactly the number of people.',
                    r'The theorem of Erdos and Szekeres gives an increasing subsequence of length $m+1=11$ or a decreasing one of length $n+1=11$ ✓',
                    r'The bound is sharp: with $100$ people it can fail (ten decreasing blocks of ten, each block above the previous).']},
   'ans': {'ru': r'Следует из теоремы при $m=n=10$.', 'en': r'It follows from the theorem with $m=n=10$.'}},

  {'t': 'thm',
   'name': {'ru': 'Числа Рамсея', 'en': 'Ramsey numbers'},
   'text': {'ru': r'Для любых $s,t\ge2$ существует наименьшее число $R(s,t)$ со свойством: если рёбра полного графа на $R(s,t)$ вершинах покрашены в два цвета, то найдётся либо $s$ вершин, попарно соединённых рёбрами первого цвета, либо $t$ вершин, попарно соединённых рёбрами второго. Известно $R(3,3)=6$ и $R(4,4)=18$; уже $R(5,5)$ не вычислено до сих пор.',
            'en': r'For all $s,t\ge2$ there is a least number $R(s,t)$ with the property: if the edges of the complete graph on $R(s,t)$ vertices are two-coloured, then either $s$ vertices are pairwise joined in the first colour or $t$ vertices are pairwise joined in the second. It is known that $R(3,3)=6$ and $R(4,4)=18$; even $R(5,5)$ is unknown to this day.'}},
  {'t': 'proof',
   'text': {'ru': r'**Существование** доказывается индукцией с оценкой $$R(s,t)\le R(s-1,t)+R(s,t-1).$$\n\nВозьмём граф на $N=R(s-1,t)+R(s,t-1)$ вершинах и выделим одну вершину $v$. Из неё выходит $N-1=R(s-1,t)+R(s,t-1)-1$ ребро, и каждое покрашено в один из двух цветов.\n\nЕсли бы красных рёбер из $v$ было не более $R(s-1,t)-1$, а синих не более $R(s,t-1)-1$, то всего их было бы не более $$R(s-1,t)+R(s,t-1)-2<N-1 ,$$ — противоречие. Значит красных хотя бы $R(s-1,t)$ или синих хотя бы $R(s,t-1)$.\n\nПусть, скажем, из $v$ выходит не менее $R(s-1,t)$ красных рёбер; обозначим через $M$ множество их концов. Внутри $M$ по определению $R(s-1,t)$ найдётся либо $t$ вершин, попарно синих (и мы закончили), либо $s-1$ вершина, попарно красная. Во втором случае добавим к ним $v$: все рёбра от $v$ до $M$ красные, значит получилось $s$ попарно красных вершин ✓ $\blacksquare$\n\n**Почему $R(3,3)=6$.** Оценка сверху — задача «о шести знакомых» из предыдущего раздела. Оценка снизу: на пяти вершинах покрасим в красный цвет рёбра пятиугольника, а в синий — его диагонали; тогда ни трёх попарно красных, ни трёх попарно синих вершин нет.',
            'en': r'**Existence** is proved by induction, with the bound $$R(s,t)\le R(s-1,t)+R(s,t-1).$$\n\nTake a graph on $N=R(s-1,t)+R(s,t-1)$ vertices and single out a vertex $v$. It has $N-1=R(s-1,t)+R(s,t-1)-1$ edges, each in one of the two colours.\n\nIf $v$ had at most $R(s-1,t)-1$ red edges and at most $R(s,t-1)-1$ blue ones, their total would be at most $$R(s-1,t)+R(s,t-1)-2<N-1 ,$$ a contradiction. So $v$ has at least $R(s-1,t)$ red edges or at least $R(s,t-1)$ blue ones.\n\nSay $v$ has at least $R(s-1,t)$ red edges, and let $M$ be the set of their other endpoints. Inside $M$, by the definition of $R(s-1,t)$, there are either $t$ pairwise blue vertices (and we are done) or $s-1$ pairwise red ones. In the second case add $v$: every edge from $v$ to $M$ is red, giving $s$ pairwise red vertices ✓ $\blacksquare$\n\n**Why $R(3,3)=6$.** The upper bound is the party-of-six problem from the previous section. The lower bound: on five vertices colour the edges of a pentagon red and its diagonals blue; then no three vertices are pairwise red and no three pairwise blue.'}},
  {'t': 'note',
   'text': {'ru': r'Теория Рамсея формулирует общий принцип: **полный беспорядок невозможен**. В любой достаточно большой структуре, как бы её ни «перемешивали», обязательно найдётся упорядоченный кусок. Принцип Дирихле — простейший случай этого утверждения.\n\nЭрдёш любил говорить: если бы инопланетяне потребовали вычислить $R(5,5)$ под угрозой уничтожения Земли, стоило бы собрать всех математиков мира; если бы они потребовали $R(6,6)$ — стоило бы попытаться уничтожить инопланетян.',
            'en': r'Ramsey theory states a general principle: **complete disorder is impossible**. In any sufficiently large structure, however it is shuffled, some ordered piece must appear. The pigeonhole principle is the simplest instance of this.\n\nErdos liked to say that if aliens demanded the value of $R(5,5)$ on pain of destroying the Earth, we should put every mathematician on it; if they demanded $R(6,6)$, we should try to destroy the aliens.'}},
 ],
}

TECHNIQUE = {
 'h': {'ru': 'Как выбирать клетки', 'en': 'How to choose the boxes'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Принцип Дирихле никогда не бывает трудным сам по себе. Вся работа — в выборе клеток. Ниже собраны стандартные конструкции клеток и признаки, по которым каждая узнаётся.',
            'en': r'The pigeonhole principle is never the hard part. All the work is in choosing the boxes. Below are the standard constructions and the signals that identify each.'}},
  {'t': 'table',
   'head': {'ru': ['Что дано в задаче', 'Клетки', 'Предметы'],
            'en': ['What the problem gives', 'The boxes', 'The objects']},
   'rows': {'ru': [['делимость на $n$', 'остатки $0,1,\\dots,n-1$', 'сами числа'],
                   ['две одинаковые цифры / суммы', 'возможные значения суммы', 'наборы'],
                   ['точки в фигуре', 'части разрезанной фигуры', 'точки'],
                   ['длинная десятичная запись', 'остатки от деления', 'числа $1,11,111,\\dots$'],
                   ['цвета и знакомства', 'цвета рёбер', 'пары вершин'],
                   ['чётность координат', '$4$ класса $\\left(\\text{чёт},\\text{нечёт}\\right)$', 'точки'],
                   ['сумма известна', 'среднее значение', 'слагаемые'],
                   ['подмножества набора чисел', 'возможные суммы подмножеств', 'подмножества']],
            'en': [['divisibility by $n$', 'the remainders $0,1,\\dots,n-1$', 'the numbers themselves'],
                   ['two equal digits or sums', 'the possible values of the sum', 'the tuples'],
                   ['points inside a figure', 'the pieces of a dissection', 'the points'],
                   ['a long decimal expansion', 'remainders on division', 'the numbers $1,11,111,\\dots$'],
                   ['colours and acquaintance', 'the edge colours', 'the pairs of vertices'],
                   ['parity of coordinates', 'the $4$ classes $\\left(\\text{even},\\text{odd}\\right)$', 'the points'],
                   ['a known total', 'the average value', 'the summands'],
                   ['subsets of a set of numbers', 'the possible subset sums', 'the subsets']]}},

  {'t': 'thm',
   'name': {'ru': 'Оценка через среднее', 'en': 'The averaging bound'},
   'text': {'ru': r'Если сумма $n$ чисел равна $S$, то хотя бы одно из них не меньше $\dfrac{S}{n}$ и хотя бы одно не больше $\dfrac{S}{n}$.',
            'en': r'If $n$ numbers add up to $S$ then at least one of them is at least $\dfrac{S}{n}$ and at least one is at most $\dfrac{S}{n}$.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть все числа строго меньше $\dfrac{S}{n}$. Тогда их сумма строго меньше $n\cdot\dfrac{S}{n}=S$ — противоречие ✓ Второе утверждение доказывается так же ✓ $\blacksquare$\n\nЭто и есть «непрерывный» вариант принципа Дирихле: клетки заменены весами, а утверждение «в какой-то клетке не меньше среднего» — тем же по смыслу.',
            'en': r'If every number were strictly less than $\dfrac{S}{n}$ their sum would be strictly less than $n\cdot\dfrac{S}{n}=S$ — a contradiction ✓ The second claim is identical ✓ $\blacksquare$\n\nThis is the "continuous" version of pigeonhole: boxes are replaced by weights, and "some box holds at least the average" says the same thing.'}},

  {'t': 'ex',
   'q': {'ru': r'Из чисел $1,2,\dots,2n$ выбрано $n+1$ число. Докажите, что среди выбранных найдутся два, одно из которых делится на другое.',
         'en': r'From $1,2,\dots,2n$ we pick $n+1$ numbers. Prove that one of the chosen numbers divides another.'},
   'steps': {'ru': [r'**Клетки.** Всякое натуральное число единственным образом записывается как $2^{s}\cdot q$ с нечётным $q$. Нечётных чисел в диапазоне $1,\dots,2n$ ровно $n$: это $1,3,5,\dots,2n-1$. Их и возьмём за клетки.',
                    r'**Предметы.** Каждое из $n+1$ выбранных чисел кладём в клетку своей нечётной части $q$.',
                    r'Предметов $n+1$, клеток $n$, значит два числа $a=2^{s}q$ и $b=2^{t}q$ имеют одну и ту же нечётную часть.',
                    r'Пусть $s<t$ (равенство невозможно: числа различны). Тогда $$\frac{b}{a}=2^{\,t-s}$$ — целое, то есть $a$ делит $b$ ✓',
                    r'Оценка точна: набор $n+1,n+2,\dots,2n$ состоит из $n$ чисел, среди которых ни одно не делит другое (отношение любых двух строго меньше $2$).'],
             'en': [r'**The boxes.** Every positive integer is uniquely $2^{s}\cdot q$ with $q$ odd. There are exactly $n$ odd numbers in $1,\dots,2n$, namely $1,3,5,\dots,2n-1$. Take these as the boxes.',
                    r'**The objects.** Put each of the $n+1$ chosen numbers into the box of its odd part $q$.',
                    r'With $n+1$ objects and $n$ boxes, two chosen numbers $a=2^{s}q$ and $b=2^{t}q$ share an odd part.',
                    r'Say $s<t$ (equality is impossible, the numbers being distinct). Then $$\frac{b}{a}=2^{\,t-s}$$ is an integer, so $a$ divides $b$ ✓',
                    r'The bound is sharp: the $n$ numbers $n+1,n+2,\dots,2n$ contain no such pair (the ratio of any two is strictly less than $2$).']},
   'ans': {'ru': r'Клетки — нечётные части чисел.', 'en': r'The boxes are the odd parts of the numbers.'}},

  {'t': 'thm',
   'name': {'ru': 'Бесконечный принцип Дирихле',
            'en': 'The infinite pigeonhole principle'},
   'text': {'ru': r'Если бесконечное множество разбито на конечное число классов, то хотя бы один класс бесконечен.',
            'en': r'If an infinite set is split into finitely many classes, at least one class is infinite.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть классов $k$ и каждый конечен, скажем класс с номером $i$ содержит $n_i$ элементов. Тогда всё множество содержит $n_1+\dots+n_k$ элементов — конечное число, что противоречит его бесконечности ✓ $\blacksquare$',
            'en': r'Suppose there are $k$ classes, all finite, the $i$-th with $n_i$ elements. Then the whole set has $n_1+\dots+n_k$ elements — a finite number, contradicting its infinitude ✓ $\blacksquare$'}},
  {'t': 'idea',
   'text': {'ru': r'Бесконечная версия — рабочий инструмент в задачах «докажите, что найдётся бесконечно много…». Типичная схема: разбейте бесконечный набор объектов по конечному числу признаков (остаток, цвет, тип), возьмите бесконечный класс и работайте уже внутри него, где все объекты «одинаковы».',
            'en': r'The infinite version is the working tool for problems asking to prove that infinitely many objects of some kind exist. The usual scheme: split an infinite family by finitely many features (a remainder, a colour, a type), take an infinite class, and work inside it where all objects "look the same".'}},

  {'t': 'warn',
   'text': {'ru': r'Формулируя решение, всегда **явно называйте предметы и клетки** и проверяйте два пункта: предметов строго больше, чем клеток, и каждый предмет попадает ровно в одну клетку. Решение, в котором написано только «по принципу Дирихле найдутся два одинаковых», не засчитывается — из него не видно, о каких клетках речь.',
            'en': r'When writing up, always **name the objects and the boxes explicitly** and check two things: there are strictly more objects than boxes, and every object goes into exactly one box. A solution that says only "by pigeonhole two of them coincide" earns no marks — it does not say what the boxes were.'}},
 ],
}

SECTIONS = [(4, CLASSICS), (5, TECHNIQUE)]

INTO = {
 0: [
  {'t': 'proof',
   'text': {'ru': r'**Доказательство обобщённого принципа.** Утверждение: если $n$ предметов разложены по $k$ клеткам, то в некоторой клетке лежит не менее $\left\lceil\dfrac{n}{k}\right\rceil$ предметов.\n\nПредположим противное: в каждой клетке не более $\left\lceil\dfrac{n}{k}\right\rceil-1$ предметов. Тогда всего предметов не более $$k\left(\left\lceil\frac{n}{k}\right\rceil-1\right).$$\n\nПо определению верхней целой части $\left\lceil\dfrac{n}{k}\right\rceil<\dfrac{n}{k}+1$, поэтому $$k\left(\left\lceil\frac{n}{k}\right\rceil-1\right)<k\cdot\frac{n}{k}=n .$$\n\nПолучилось, что предметов строго меньше $n$ — противоречие ✓ $\blacksquare$\n\nПри $k=n-1$ отсюда следует обычный принцип: $\left\lceil\dfrac{n}{n-1}\right\rceil=2$.',
            'en': r'**Proof of the generalised principle.** The claim: if $n$ objects are placed in $k$ boxes then some box holds at least $\left\lceil\dfrac{n}{k}\right\rceil$ of them.\n\nSuppose not: every box holds at most $\left\lceil\dfrac{n}{k}\right\rceil-1$ objects. Then there are at most $$k\left(\left\lceil\frac{n}{k}\right\rceil-1\right)$$ objects in all.\n\nBy the definition of the ceiling, $\left\lceil\dfrac{n}{k}\right\rceil<\dfrac{n}{k}+1$, so $$k\left(\left\lceil\frac{n}{k}\right\rceil-1\right)<k\cdot\frac{n}{k}=n .$$\n\nThat makes the number of objects strictly less than $n$ — a contradiction ✓ $\blacksquare$\n\nWith $k=n-1$ this gives the ordinary principle, since $\left\lceil\dfrac{n}{n-1}\right\rceil=2$.'}},
  {'t': 'note',
   'text': {'ru': r'**Двойственная форма.** В некоторой клетке лежит не более $\left\lfloor\dfrac{n}{k}\right\rfloor$ предметов. Она нужна, когда требуется доказать, что чего-то **мало**: например, что найдётся строка таблицы, в которой не более стольких-то единиц.',
            'en': r'**The dual form.** Some box holds at most $\left\lfloor\dfrac{n}{k}\right\rfloor$ objects. It is needed when the goal is to prove that something is **small**: that some row of a table has at most so many ones, say.'}},
 ],
}
