# -*- coding: utf-8 -*-
"""Topic 7 — deeper theory, woven into lesson_07.py by content/build.py."""

SUMS = {
 'h': {'ru': 'Классические суммы', 'en': 'The standard sums'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Четыре суммы ниже встречаются в задачах постоянно. Их стоит не только запомнить, но и уметь выводить: приём вывода важнее самой формулы, потому что он работает и для сумм, которых нет в справочнике.',
            'en': r'The four sums below appear constantly. They are worth not only memorising but being able to derive: the derivation matters more than the formula, because it also handles sums no reference book lists.'}},

  {'t': 'thm',
   'name': {'ru': 'Сумма первых $n$ натуральных чисел', 'en': 'Sum of the first $n$ integers'},
   'text': {'ru': r'$$1+2+3+\dots+n=\frac{n\left(n+1\right)}{2}.$$',
            'en': r'$$1+2+3+\dots+n=\frac{n\left(n+1\right)}{2}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Обозначим сумму через $S$ и выпишем её дважды — в прямом и в обратном порядке: $$\begin{aligned} S&=1+2+\dots+\left(n-1\right)+n,\\ S&=n+\left(n-1\right)+\dots+2+1. \end{aligned}$$\n\nСложим почленно. В каждом из $n$ столбцов сумма равна $n+1$, поэтому $$2S=n\left(n+1\right)\quad\Longrightarrow\quad S=\frac{n\left(n+1\right)}{2} \quad\checkmark\qquad\blacksquare$$\n\nЭто тот самый приём, которым, по легенде, девятилетний Гаусс сложил числа от $1$ до $100$ за несколько секунд: пятьдесят пар по $101$.',
            'en': r'Write the sum $S$ twice, forwards and backwards: $$\begin{aligned} S&=1+2+\dots+\left(n-1\right)+n,\\ S&=n+\left(n-1\right)+\dots+2+1. \end{aligned}$$\n\nAdd column by column. Each of the $n$ columns totals $n+1$, so $$2S=n\left(n+1\right)\quad\Longrightarrow\quad S=\frac{n\left(n+1\right)}{2} \quad\checkmark\qquad\blacksquare$$\n\nThis is the trick with which, according to the story, the nine-year-old Gauss added the numbers from $1$ to $100$ in seconds: fifty pairs of $101$.'}},

  {'t': 'thm',
   'name': {'ru': 'Сумма квадратов', 'en': 'Sum of squares'},
   'text': {'ru': r'$$1^{2}+2^{2}+\dots+n^{2}=\frac{n\left(n+1\right)\left(2n+1\right)}{6}.$$',
            'en': r'$$1^{2}+2^{2}+\dots+n^{2}=\frac{n\left(n+1\right)\left(2n+1\right)}{6}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Используем телескопирование. Раскроем куб разности соседних чисел: $$\left(k+1\right)^{3}-k^{3}=3k^{2}+3k+1 .$$\n\nПросуммируем это равенство по $k=1,2,\dots,n$. Слева получается телескопическая сумма, от которой остаются только крайние члены: $$\left(n+1\right)^{3}-1^{3}=3\sum_{k=1}^{n}k^{2}+3\sum_{k=1}^{n}k+n .$$\n\nВторую сумму мы уже знаем: $\sum k=\dfrac{n\left(n+1\right)}{2}$. Подставим и выразим искомое: $$3\sum k^{2}=\left(n+1\right)^{3}-1-\frac{3n\left(n+1\right)}{2}-n .$$\n\nПриведём правую часть к общему знаменателю $2$: $$3\sum k^{2}=\frac{2\left(n+1\right)^{3}-2-3n\left(n+1\right)-2n}{2}=\frac{2n^{3}+3n^{2}+n}{2}=\frac{n\left(n+1\right)\left(2n+1\right)}{2}.$$\n\nДелим на $3$ ✓ $\blacksquare$',
            'en': r'Use telescoping. Expand the cube of a step: $$\left(k+1\right)^{3}-k^{3}=3k^{2}+3k+1 .$$\n\nSum this over $k=1,2,\dots,n$. The left side telescopes, leaving only the endpoints: $$\left(n+1\right)^{3}-1^{3}=3\sum_{k=1}^{n}k^{2}+3\sum_{k=1}^{n}k+n .$$\n\nThe second sum is already known: $\sum k=\dfrac{n\left(n+1\right)}{2}$. Substitute and solve: $$3\sum k^{2}=\left(n+1\right)^{3}-1-\frac{3n\left(n+1\right)}{2}-n .$$\n\nOver the common denominator $2$ the right side becomes $$\frac{2n^{3}+3n^{2}+n}{2}=\frac{n\left(n+1\right)\left(2n+1\right)}{2}.$$\n\nDivide by $3$ ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Сумма кубов', 'en': 'Sum of cubes'},
   'text': {'ru': r'$$1^{3}+2^{3}+\dots+n^{3}=\left(\frac{n\left(n+1\right)}{2}\right)^{2}=\left(1+2+\dots+n\right)^{2}.$$',
            'en': r'$$1^{3}+2^{3}+\dots+n^{3}=\left(\frac{n\left(n+1\right)}{2}\right)^{2}=\left(1+2+\dots+n\right)^{2}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Индукция по $n$.\n\n**База $n=1$:** $1^{3}=1=\left(\tfrac{1\cdot2}{2}\right)^{2}$ ✓\n\n**Шаг.** Пусть $\sum_{k=1}^{n}k^{3}=\dfrac{n^{2}\left(n+1\right)^{2}}{4}$. Прибавим следующий куб: $$\sum_{k=1}^{n+1}k^{3}=\frac{n^{2}\left(n+1\right)^{2}}{4}+\left(n+1\right)^{3}=\left(n+1\right)^{2}\cdot\frac{n^{2}+4\left(n+1\right)}{4}.$$\n\nЧислитель равен $n^{2}+4n+4=\left(n+2\right)^{2}$, поэтому сумма равна $$\frac{\left(n+1\right)^{2}\left(n+2\right)^{2}}{4},$$ то есть формула для $n+1$ ✓ $\blacksquare$\n\nСовпадение с квадратом суммы не случайно: существует красивое доказательство «без слов», в котором куб $k^{3}$ разрезается на $k$ квадратов со стороной $k$, а все они укладываются в один большой квадрат со стороной $1+2+\dots+n$.',
            'en': r'Induction on $n$.\n\n**Base $n=1$:** $1^{3}=1=\left(\tfrac{1\cdot2}{2}\right)^{2}$ ✓\n\n**Step.** Suppose $\sum_{k=1}^{n}k^{3}=\dfrac{n^{2}\left(n+1\right)^{2}}{4}$. Add the next cube: $$\sum_{k=1}^{n+1}k^{3}=\frac{n^{2}\left(n+1\right)^{2}}{4}+\left(n+1\right)^{3}=\left(n+1\right)^{2}\cdot\frac{n^{2}+4\left(n+1\right)}{4}.$$\n\nThe numerator is $n^{2}+4n+4=\left(n+2\right)^{2}$, so the sum equals $$\frac{\left(n+1\right)^{2}\left(n+2\right)^{2}}{4},$$ which is the formula for $n+1$ ✓ $\blacksquare$\n\nThe coincidence with a square is not an accident: there is a lovely proof without words in which each cube $k^{3}$ is cut into $k$ squares of side $k$ and all of them tile one big square of side $1+2+\dots+n$.'}},

  {'t': 'thm',
   'name': {'ru': 'Арифметико-геометрическая сумма', 'en': 'An arithmetic–geometric sum'},
   'text': {'ru': r'Для $q\ne1$ $$\sum_{k=1}^{n}kq^{\,k-1}=\frac{1-\left(n+1\right)q^{\,n}+nq^{\,n+1}}{\left(1-q\right)^{2}}.$$',
            'en': r'For $q\ne1$ $$\sum_{k=1}^{n}kq^{\,k-1}=\frac{1-\left(n+1\right)q^{\,n}+nq^{\,n+1}}{\left(1-q\right)^{2}}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Приём тот же, что и для геометрической прогрессии: **умножить на знаменатель и вычесть**.\n\nПусть $S=1+2q+3q^{2}+\dots+nq^{\,n-1}$. Тогда $$qS=q+2q^{2}+\dots+\left(n-1\right)q^{\,n-1}+nq^{\,n}.$$\n\nВычтем: коэффициент при $q^{\,k}$ слева равен $\left(k+1\right)-k=1$ для $k=1,\dots,n-1$, поэтому $$S-qS=1+q+q^{2}+\dots+q^{\,n-1}-nq^{\,n}=\frac{1-q^{\,n}}{1-q}-nq^{\,n}.$$\n\nОстаётся разделить на $1-q$ и привести к общему знаменателю ✓ $\blacksquare$',
            'en': r'The trick is the one used for a geometric progression: **multiply by the ratio and subtract**.\n\nLet $S=1+2q+3q^{2}+\dots+nq^{\,n-1}$. Then $$qS=q+2q^{2}+\dots+\left(n-1\right)q^{\,n-1}+nq^{\,n}.$$\n\nSubtract: the coefficient of $q^{\,k}$ is $\left(k+1\right)-k=1$ for $k=1,\dots,n-1$, so $$S-qS=1+q+q^{2}+\dots+q^{\,n-1}-nq^{\,n}=\frac{1-q^{\,n}}{1-q}-nq^{\,n}.$$\n\nDivide by $1-q$ and combine over a common denominator ✓ $\blacksquare$'}},

  {'t': 'ex',
   'q': {'ru': r'Вычислите $\dfrac1{2}+\dfrac2{4}+\dfrac3{8}+\dots+\dfrac{n}{2^{n}}$ и найдите предел этой суммы при $n\to\infty$.',
         'en': r'Evaluate $\dfrac1{2}+\dfrac2{4}+\dfrac3{8}+\dots+\dfrac{n}{2^{n}}$ and find its limit as $n\to\infty$.'},
   'steps': {'ru': [r'Это $\dfrac12\sum_{k=1}^{n}k\left(\tfrac12\right)^{k-1}$, то есть предыдущая формула при $q=\tfrac12$.',
                    r'Подставим: $\left(1-q\right)^{2}=\tfrac14$, поэтому сумма равна $$\frac12\cdot4\left(1-\frac{n+1}{2^{n}}+\frac{n}{2^{n+1}}\right)=2-\frac{n+2}{2^{n}}.$$',
                    r'Проверим при $n=3$: формула даёт $2-\tfrac58=\tfrac{11}{8}$, а прямой счёт $\tfrac12+\tfrac12+\tfrac38=\tfrac{11}{8}$ ✓',
                    r'При $n\to\infty$ дробь $\dfrac{n+2}{2^{n}}\to0$, поскольку показательная функция растёт быстрее линейной. Предел равен $2$.'],
             'en': [r'This is $\dfrac12\sum_{k=1}^{n}k\left(\tfrac12\right)^{k-1}$, the previous formula with $q=\tfrac12$.',
                    r'Substituting, $\left(1-q\right)^{2}=\tfrac14$, so the sum equals $$\frac12\cdot4\left(1-\frac{n+1}{2^{n}}+\frac{n}{2^{n+1}}\right)=2-\frac{n+2}{2^{n}}.$$',
                    r'Check at $n=3$: the formula gives $2-\tfrac58=\tfrac{11}{8}$, and direct addition gives $\tfrac12+\tfrac12+\tfrac38=\tfrac{11}{8}$ ✓',
                    r'As $n\to\infty$ the fraction $\dfrac{n+2}{2^{n}}\to0$, since exponentials beat linear growth. The limit is $2$.']},
   'ans': {'ru': r'$2-\dfrac{n+2}{2^{n}}$; предел равен $2$.', 'en': r'$2-\dfrac{n+2}{2^{n}}$; the limit is $2$.'}},

  {'t': 'idea',
   'text': {'ru': r'**Метод конечных разностей.** Если $a_n$ задаётся многочленом степени $d$, то сумма $\sum_{k\le n}a_k$ — многочлен степени $d+1$. Отсюда быстрый способ найти формулу: предположить многочлен нужной степени с неизвестными коэффициентами, подставить $n=0,1,\dots,d+1$ и решить линейную систему. Доказательство всё равно потребуется — обычно индукцией.',
            'en': r'**The method of finite differences.** If $a_n$ is given by a polynomial of degree $d$ then $\sum_{k\le n}a_k$ is a polynomial of degree $d+1$. This gives a fast way to find the formula: assume a polynomial of that degree with unknown coefficients, plug in $n=0,1,\dots,d+1$ and solve the linear system. A proof is still needed — usually by induction.'}},
 ],
}

LINREC = {
 'h': {'ru': 'Линейные рекуррентные последовательности',
       'en': 'Linear recurrences'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Рекуррентное задание удобно для вычислений, но неудобно для рассуждений: чтобы узнать $a_{100}$, приходится пройти все предыдущие члены. Для целого класса последовательностей — линейных рекуррент — существует общий способ получить **явную формулу**.',
            'en': r'A recurrence is convenient for computing but awkward for reasoning: to learn $a_{100}$ you must walk through every earlier term. For a whole class of sequences — the linear recurrences — there is a general way to obtain an **explicit formula**.'}},

  {'t': 'def',
   'name': {'ru': 'Линейная рекуррента второго порядка', 'en': 'Second-order linear recurrence'},
   'text': {'ru': r'Последовательность задана **линейной рекуррентой второго порядка с постоянными коэффициентами**, если $$a_{n+2}=p\,a_{n+1}+q\,a_n\qquad\left(q\ne0\right)$$ для всех $n$, а $a_0,a_1$ заданы. Многочлен $$x^{2}-px-q$$ называется её **характеристическим многочленом**.',
            'en': r'A sequence satisfies a **second-order linear recurrence with constant coefficients** if $$a_{n+2}=p\,a_{n+1}+q\,a_n\qquad\left(q\ne0\right)$$ for all $n$, with $a_0,a_1$ given. The polynomial $$x^{2}-px-q$$ is its **characteristic polynomial**.'}},

  {'t': 'thm',
   'name': {'ru': 'Общий вид решения', 'en': 'The general solution'},
   'text': {'ru': r'Пусть $x_1,x_2$ — корни характеристического многочлена.\n\n**Если $x_1\ne x_2$,** то существуют константы $A,B$, для которых $$a_n=A\,x_1^{\,n}+B\,x_2^{\,n}\qquad\text{при всех }n\ge0 .$$\n\n**Если $x_1=x_2=x$,** то существуют $A,B$ с $$a_n=\left(A+Bn\right)x^{\,n}.$$\n\nКонстанты однозначно определяются двумя начальными условиями.',
            'en': r'Let $x_1,x_2$ be the roots of the characteristic polynomial.\n\n**If $x_1\ne x_2$** there are constants $A,B$ with $$a_n=A\,x_1^{\,n}+B\,x_2^{\,n}\qquad\text{for all }n\ge0 .$$\n\n**If $x_1=x_2=x$** there are $A,B$ with $$a_n=\left(A+Bn\right)x^{\,n}.$$\n\nThe constants are uniquely determined by the two initial values.'}},
  {'t': 'proof',
   'text': {'ru': r'**Шаг 1: геометрические прогрессии — решения.** Подставим $a_n=x^{\,n}$ в рекурренту: $$x^{\,n+2}=p\,x^{\,n+1}+q\,x^{\,n}.$$ Разделив на $x^{\,n}\ne0$, получаем ровно $x^{2}=px+q$. Значит $x^{\,n}$ удовлетворяет рекурренте тогда и только тогда, когда $x$ — корень характеристического многочлена ✓\n\n**Шаг 2: сумма решений — решение.** Рекуррента линейна: если последовательности $u_n$ и $v_n$ ей удовлетворяют, то и $Au_n+Bv_n$ удовлетворяет, потому что $$A u_{n+2}+B v_{n+2}=p\left(Au_{n+1}+Bv_{n+1}\right)+q\left(Au_n+Bv_n\right) \quad\checkmark$$\n\n**Шаг 3: подбор констант.** Нужно решить систему $$\begin{cases}A+B=a_0,\\ Ax_1+Bx_2=a_1.\end{cases}$$ Её определитель равен $x_2-x_1\ne0$, поэтому решение существует и единственно ✓\n\n**Шаг 4: единственность.** Два члена $a_0,a_1$ вместе с рекуррентой однозначно задают всю последовательность (индукция). Наша формула даёт правильные $a_0,a_1$ и удовлетворяет рекурренте, значит совпадает с $a_n$ при всех $n$ ✓\n\n**Случай кратного корня.** Здесь $x_1=x_2=x=\tfrac{p}{2}$ и $q=-x^{2}$. Проверим, что $n x^{\,n}$ — тоже решение: $$\left(n+2\right)x^{\,n+2}\ \overset{?}{=}\ p\left(n+1\right)x^{\,n+1}+q\,n x^{\,n}.$$ Подставим $p=2x$ и $q=-x^{2}$ и сократим $x^{\,n+2}$: справа получается $2\left(n+1\right)-n=n+2$ ✓ Дальше рассуждение то же самое, а система для $A,B$ принимает вид $A=a_0$, $\left(A+B\right)x=a_1$ и снова однозначно разрешима (напомним, $x\ne0$, так как $q\ne0$) ✓ $\blacksquare$',
            'en': r'**Step 1: geometric sequences are solutions.** Substitute $a_n=x^{\,n}$: $$x^{\,n+2}=p\,x^{\,n+1}+q\,x^{\,n}.$$ Dividing by $x^{\,n}\ne0$ gives exactly $x^{2}=px+q$. So $x^{\,n}$ satisfies the recurrence iff $x$ is a root of the characteristic polynomial ✓\n\n**Step 2: sums of solutions are solutions.** The recurrence is linear: if $u_n$ and $v_n$ satisfy it so does $Au_n+Bv_n$, since $$A u_{n+2}+B v_{n+2}=p\left(Au_{n+1}+Bv_{n+1}\right)+q\left(Au_n+Bv_n\right) \quad\checkmark$$\n\n**Step 3: fitting the constants.** Solve $$\begin{cases}A+B=a_0,\\ Ax_1+Bx_2=a_1.\end{cases}$$ Its determinant is $x_2-x_1\ne0$, so a unique solution exists ✓\n\n**Step 4: uniqueness.** The two values $a_0,a_1$ together with the recurrence determine the whole sequence (induction). Our formula reproduces $a_0,a_1$ and satisfies the recurrence, so it agrees with $a_n$ for every $n$ ✓\n\n**The repeated root.** Here $x_1=x_2=x=\tfrac{p}{2}$ and $q=-x^{2}$. Check that $n x^{\,n}$ is also a solution: $$\left(n+2\right)x^{\,n+2}\ \overset{?}{=}\ p\left(n+1\right)x^{\,n+1}+q\,n x^{\,n}.$$ Substituting $p=2x$, $q=-x^{2}$ and cancelling $x^{\,n+2}$, the right side is $2\left(n+1\right)-n=n+2$ ✓ The rest is identical, and the system becomes $A=a_0$, $\left(A+B\right)x=a_1$, again uniquely solvable since $x\ne0$ (because $q\ne0$) ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Формула Бине', 'en': 'Binet formula'},
   'text': {'ru': r'Для чисел Фибоначчи $F_1=F_2=1$, $F_{n+2}=F_{n+1}+F_n$ $$F_n=\frac1{\sqrt5}\left(\varphi^{\,n}-\psi^{\,n}\right),\qquad \varphi=\frac{1+\sqrt5}{2},\quad \psi=\frac{1-\sqrt5}{2}.$$',
            'en': r'For the Fibonacci numbers $F_1=F_2=1$, $F_{n+2}=F_{n+1}+F_n$ $$F_n=\frac1{\sqrt5}\left(\varphi^{\,n}-\psi^{\,n}\right),\qquad \varphi=\frac{1+\sqrt5}{2},\quad \psi=\frac{1-\sqrt5}{2}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Здесь $p=q=1$, характеристический многочлен равен $$x^{2}-x-1 ,$$ его корни — $\varphi$ и $\psi$ (это «золотое сечение» и сопряжённое к нему число). Они различны, поэтому $$F_n=A\varphi^{\,n}+B\psi^{\,n}.$$\n\nУдобно доопределить $F_0=0$ (рекуррента это позволяет: $F_2=F_1+F_0$ даёт $F_0=0$). Тогда система такова: $$\begin{cases}A+B=F_0=0,\\ A\varphi+B\psi=F_1=1.\end{cases}$$ Из первого уравнения $B=-A$, подставляем во второе: $$A\left(\varphi-\psi\right)=1 .$$ Но $\varphi-\psi=\sqrt5$, значит $A=\dfrac1{\sqrt5}$, $B=-\dfrac1{\sqrt5}$ ✓ $\blacksquare$',
            'en': r'Here $p=q=1$, so the characteristic polynomial is $$x^{2}-x-1 ,$$ whose roots are $\varphi$ and $\psi$ (the golden ratio and its conjugate). They are distinct, so $$F_n=A\varphi^{\,n}+B\psi^{\,n}.$$\n\nIt is convenient to set $F_0=0$ (the recurrence forces it: $F_2=F_1+F_0$). The system is then $$\begin{cases}A+B=F_0=0,\\ A\varphi+B\psi=F_1=1.\end{cases}$$ The first gives $B=-A$; substituting into the second, $$A\left(\varphi-\psi\right)=1 .$$ But $\varphi-\psi=\sqrt5$, so $A=\dfrac1{\sqrt5}$ and $B=-\dfrac1{\sqrt5}$ ✓ $\blacksquare$'}},
  {'t': 'note',
   'text': {'ru': r'Формула Бине выглядит парадоксально: справа стоят иррациональные числа, а слева — всегда целое. Иррациональности взаимно уничтожаются, потому что при раскрытии по формуле бинома все члены с нечётными степенями $\sqrt5$ входят дважды с противоположными знаками.\n\nПрактическое следствие: $\left|\psi\right|=\dfrac{\sqrt5-1}{2}\approx0{,}618<1$, поэтому $\psi^{\,n}\to0$, и $$F_n=\left[\frac{\varphi^{\,n}}{\sqrt5}\right]\ \text{(ближайшее целое)} .$$ Отсюда же видно, что отношение $\dfrac{F_{n+1}}{F_n}$ стремится к золотому сечению $\varphi\approx1{,}618$.',
            'en': r'Binet formula looks paradoxical: the right side is built from irrational numbers, the left side is always an integer. The irrational parts cancel, because on expanding by the binomial theorem every term with an odd power of $\sqrt5$ appears twice with opposite signs.\n\nA practical consequence: $\left|\psi\right|=\dfrac{\sqrt5-1}{2}\approx0.618<1$, so $\psi^{\,n}\to0$ and $$F_n=\left[\frac{\varphi^{\,n}}{\sqrt5}\right]\ \text{(nearest integer)} .$$ It also shows that the ratio $\dfrac{F_{n+1}}{F_n}$ tends to the golden ratio $\varphi\approx1.618$.'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите явную формулу для $a_0=0$, $a_1=1$, $a_{n+2}=4a_{n+1}-4a_n$.',
         'en': r'Find an explicit formula for $a_0=0$, $a_1=1$, $a_{n+2}=4a_{n+1}-4a_n$.'},
   'steps': {'ru': [r'Характеристический многочлен: $x^{2}-4x+4=\left(x-2\right)^{2}$ — корень $x=2$ кратный.',
                    r'Значит $a_n=\left(A+Bn\right)2^{\,n}$.',
                    r'Из $a_0=0$: $A=0$. Из $a_1=1$: $\left(0+B\right)\cdot2=1$, то есть $B=\tfrac12$.',
                    r'Итог: $a_n=\dfrac{n}{2}\cdot2^{\,n}=n\,2^{\,n-1}$.',
                    r'Проверка: $a_2=2\cdot2=4$, а рекуррента даёт $4\cdot1-4\cdot0=4$ ✓'],
             'en': [r'Characteristic polynomial: $x^{2}-4x+4=\left(x-2\right)^{2}$ — a repeated root $x=2$.',
                    r'So $a_n=\left(A+Bn\right)2^{\,n}$.',
                    r'From $a_0=0$: $A=0$. From $a_1=1$: $\left(0+B\right)\cdot2=1$, so $B=\tfrac12$.',
                    r'Hence $a_n=\dfrac{n}{2}\cdot2^{\,n}=n\,2^{\,n-1}$.',
                    r'Check: $a_2=2\cdot2=4$, and the recurrence gives $4\cdot1-4\cdot0=4$ ✓']},
   'ans': {'ru': r'$a_n=n\,2^{\,n-1}$.', 'en': r'$a_n=n\,2^{\,n-1}$.'}},

  {'t': 'thm',
   'name': {'ru': 'Неоднородная рекуррента', 'en': 'Inhomogeneous recurrences'},
   'text': {'ru': r'Для рекурренты вида $$a_{n+1}=c\,a_n+d\qquad\left(c\ne1\right)$$ существует **неподвижная точка** $t=\dfrac{d}{1-c}$, и последовательность $b_n=a_n-t$ является геометрической прогрессией со знаменателем $c$. Отсюда $$a_n=\left(a_0-t\right)c^{\,n}+t .$$',
            'en': r'For a recurrence of the form $$a_{n+1}=c\,a_n+d\qquad\left(c\ne1\right)$$ there is a **fixed point** $t=\dfrac{d}{1-c}$, and the sequence $b_n=a_n-t$ is a geometric progression with ratio $c$. Hence $$a_n=\left(a_0-t\right)c^{\,n}+t .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Неподвижная точка — это решение уравнения $t=ct+d$, откуда $t\left(1-c\right)=d$ и $t=\dfrac{d}{1-c}$ (здесь и нужно $c\ne1$).\n\nВычтем это равенство из рекурренты: $$a_{n+1}-t=c\,a_n+d-\left(ct+d\right)=c\left(a_n-t\right),$$ то есть $b_{n+1}=c\,b_n$ — геометрическая прогрессия ✓ Значит $b_n=b_0c^{\,n}$, и остаётся вернуться к $a_n=b_n+t$ ✓ $\blacksquare$',
            'en': r'The fixed point solves $t=ct+d$, giving $t\left(1-c\right)=d$ and $t=\dfrac{d}{1-c}$ (this is where $c\ne1$ is needed).\n\nSubtract that equation from the recurrence: $$a_{n+1}-t=c\,a_n+d-\left(ct+d\right)=c\left(a_n-t\right),$$ i.e. $b_{n+1}=c\,b_n$, a geometric progression ✓ So $b_n=b_0c^{\,n}$, and $a_n=b_n+t$ ✓ $\blacksquare$'}},
  {'t': 'idea',
   'text': {'ru': r'Приём с неподвижной точкой универсален: **сдвиньте начало отсчёта туда, где последовательность стояла бы на месте**, и останется чистая геометрическая прогрессия. Так задача про $a_{n+1}=2a_n+1$ из первого раздела решается в две строки: $t=-1$, значит $a_n+1=\left(a_1+1\right)2^{\,n-1}=2^{\,n}$, то есть $a_n=2^{\,n}-1$.',
            'en': r'The fixed-point trick is universal: **move the origin to where the sequence would stand still** and a pure geometric progression remains. The problem $a_{n+1}=2a_n+1$ from the first section then takes two lines: $t=-1$, so $a_n+1=\left(a_1+1\right)2^{\,n-1}=2^{\,n}$, that is $a_n=2^{\,n}-1$.'}},
 ],
}

LIMITS = {
 'h': {'ru': 'Пределы, монотонность и бесконечные суммы',
       'en': 'Limits, monotonicity and infinite sums'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Многие олимпиадные задачи спрашивают не про конкретный член, а про поведение последовательности «в конце концов». Для аккуратного ответа достаточно двух понятий и одной теоремы.',
            'en': r'Many olympiad problems ask not about a particular term but about what a sequence does in the long run. Two notions and one theorem are enough to answer carefully.'}},

  {'t': 'def',
   'name': {'ru': 'Ограниченность и монотонность', 'en': 'Boundedness and monotonicity'},
   'text': {'ru': r'Последовательность $\left(a_n\right)$ **возрастает**, если $a_{n+1}\ge a_n$ при всех $n$, и **убывает**, если $a_{n+1}\le a_n$. Она **ограничена сверху**, если существует число $M$ с $a_n\le M$ при всех $n$, и **ограничена снизу**, если существует $m$ с $a_n\ge m$.',
            'en': r'A sequence $\left(a_n\right)$ is **increasing** if $a_{n+1}\ge a_n$ for every $n$ and **decreasing** if $a_{n+1}\le a_n$. It is **bounded above** if some $M$ satisfies $a_n\le M$ for all $n$, and **bounded below** if some $m$ satisfies $a_n\ge m$.'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема о монотонной последовательности',
            'en': 'The monotone convergence theorem'},
   'text': {'ru': r'Возрастающая ограниченная сверху последовательность имеет предел, и этот предел равен её точной верхней грани. Симметрично для убывающей, ограниченной снизу.',
            'en': r'An increasing sequence that is bounded above has a limit, equal to its least upper bound. Symmetrically for a decreasing sequence bounded below.'}},
  {'t': 'note',
   'text': {'ru': r'Эта теорема — форма **полноты** множества вещественных чисел; она неверна в рациональных числах. Например, последовательность десятичных приближений $1;\ 1{,}4;\ 1{,}41;\ 1{,}414;\dots$ возрастает и ограничена, но её предел $\sqrt2$ не рационален.\n\nНа олимпиаде теорему обычно применяют как готовый инструмент: доказать монотонность (разностью или отношением соседних членов) и ограниченность (индукцией), после чего предел существует и находится из уравнения.',
            'en': r'This theorem is a form of the **completeness** of the reals; it fails inside the rationals. The decimal approximations $1;\ 1.4;\ 1.41;\ 1.414;\dots$ increase and are bounded, yet their limit $\sqrt2$ is not rational.\n\nAt an olympiad the theorem is used as a ready-made tool: prove monotonicity (from the difference or the ratio of consecutive terms) and boundedness (by induction); the limit then exists and is found from an equation.'}},

  {'t': 'ex',
   'q': {'ru': r'Пусть $a_1=\sqrt2$ и $a_{n+1}=\sqrt{2+a_n}$. Докажите, что предел существует, и найдите его.',
         'en': r'Let $a_1=\sqrt2$ and $a_{n+1}=\sqrt{2+a_n}$. Prove that the limit exists and find it.'},
   'steps': {'ru': [r'**Ограниченность.** Докажем индукцией, что $a_n<2$. База: $a_1=\sqrt2<2$ ✓ Шаг: если $a_n<2$, то $a_{n+1}=\sqrt{2+a_n}<\sqrt{4}=2$ ✓',
                    r'**Монотонность.** Сравним $a_{n+1}$ и $a_n$: неравенство $\sqrt{2+a_n}>a_n$ при $a_n>0$ равносильно $2+a_n>a_n^{2}$, то есть $a_n^{2}-a_n-2<0$, то есть $\left(a_n-2\right)\left(a_n+1\right)<0$. Это верно, поскольку $0<a_n<2$ ✓',
                    r'Последовательность возрастает и ограничена сверху, значит предел $L$ существует.',
                    r'**Уравнение на предел.** Перейдём к пределу в рекурренте: $L=\sqrt{2+L}$, откуда $L^{2}-L-2=0$ и $L\in\left\{2,-1\right\}$.',
                    r'Все члены положительны, поэтому $L=2$ ✓'],
             'en': [r'**Boundedness.** By induction $a_n<2$. Base: $a_1=\sqrt2<2$ ✓ Step: if $a_n<2$ then $a_{n+1}=\sqrt{2+a_n}<\sqrt{4}=2$ ✓',
                    r'**Monotonicity.** Compare $a_{n+1}$ with $a_n$: for $a_n>0$, $\sqrt{2+a_n}>a_n$ is equivalent to $2+a_n>a_n^{2}$, i.e. $\left(a_n-2\right)\left(a_n+1\right)<0$, which holds since $0<a_n<2$ ✓',
                    r'The sequence increases and is bounded above, so a limit $L$ exists.',
                    r'**Equation for the limit.** Pass to the limit in the recurrence: $L=\sqrt{2+L}$, hence $L^{2}-L-2=0$ and $L\in\left\{2,-1\right\}$.',
                    r'All terms are positive, so $L=2$ ✓']},
   'ans': {'ru': r'Предел равен $2$.', 'en': r'The limit is $2$.'}},
  {'t': 'warn',
   'text': {'ru': r'Порядок шагов принципиален. Уравнение $L=\sqrt{2+L}$ имеет смысл **только после того, как доказано существование предела**. Если написать его сразу, можно «найти предел» у расходящейся последовательности: например, для $a_{n+1}=2a_n$ уравнение $L=2L$ даёт $L=0$, хотя последовательность (при $a_1=1$) уходит в бесконечность.',
            'en': r'The order of the steps is essential. The equation $L=\sqrt{2+L}$ is meaningful **only after the limit is known to exist**. Writing it straight away lets you "find the limit" of a divergent sequence: for $a_{n+1}=2a_n$ the equation $L=2L$ gives $L=0$, although the sequence (with $a_1=1$) runs off to infinity.'}},

  {'t': 'thm',
   'name': {'ru': 'Сумма бесконечной геометрической прогрессии',
            'en': 'Sum of an infinite geometric progression'},
   'text': {'ru': r'Если $\left|q\right|<1$, то $$b_1+b_1q+b_1q^{2}+\dots=\frac{b_1}{1-q}.$$ При $\left|q\right|\ge1$ и $b_1\ne0$ сумма не существует.',
            'en': r'If $\left|q\right|<1$ then $$b_1+b_1q+b_1q^{2}+\dots=\frac{b_1}{1-q}.$$ For $\left|q\right|\ge1$ and $b_1\ne0$ the sum does not exist.'}},
  {'t': 'proof',
   'text': {'ru': r'Частичная сумма равна $$S_n=b_1\frac{1-q^{\,n}}{1-q}=\frac{b_1}{1-q}-\frac{b_1q^{\,n}}{1-q}.$$\n\nПри $\left|q\right|<1$ имеем $q^{\,n}\to0$, поэтому второе слагаемое стремится к нулю, и $S_n\to\dfrac{b_1}{1-q}$ ✓\n\nПри $\left|q\right|\ge1$ члены прогрессии не стремятся к нулю ($\left|b_1q^{\,n}\right|\ge\left|b_1\right|>0$), а это необходимое условие сходимости ряда: если ряд сходится, то $S_n$ и $S_{n-1}$ имеют один предел, значит их разность — очередной член — стремится к нулю ✓ $\blacksquare$',
            'en': r'The partial sum is $$S_n=b_1\frac{1-q^{\,n}}{1-q}=\frac{b_1}{1-q}-\frac{b_1q^{\,n}}{1-q}.$$\n\nIf $\left|q\right|<1$ then $q^{\,n}\to0$, the second term vanishes, and $S_n\to\dfrac{b_1}{1-q}$ ✓\n\nIf $\left|q\right|\ge1$ the terms do not tend to zero ($\left|b_1q^{\,n}\right|\ge\left|b_1\right|>0$), and that is a necessary condition for a series to converge: if it converges then $S_n$ and $S_{n-1}$ share a limit, so their difference — the next term — tends to zero ✓ $\blacksquare$'}},
  {'t': 'note',
   'text': {'ru': r'Условие «члены стремятся к нулю» необходимо, но **не достаточно**. Классический контрпример — гармонический ряд $$1+\frac12+\frac13+\frac14+\dots ,$$ который расходится, хотя его члены убывают к нулю. Доказательство Орема: сгруппируем члены по блокам длины $1,2,4,8,\dots$; каждый блок не меньше $\tfrac12$, поэтому сумма растёт неограниченно.',
            'en': r'The condition "terms tend to zero" is necessary but **not sufficient**. The classic counterexample is the harmonic series $$1+\frac12+\frac13+\frac14+\dots ,$$ which diverges although its terms shrink to zero. The proof of Oresme: group the terms into blocks of lengths $1,2,4,8,\dots$; every block is at least $\tfrac12$, so the sum grows without bound.'}},
 ],
}

SECTIONS = [(4, SUMS), (4, LINREC), (5, LIMITS)]

INTO = {
 0: [
  {'t': 'thm',
   'name': {'ru': 'Принцип математической индукции',
            'en': 'The principle of mathematical induction'},
   'text': {'ru': r'Пусть $P(n)$ — утверждение, зависящее от натурального $n$. Если\n\n1. $P(1)$ истинно, и\n2. из истинности $P(k)$ следует истинность $P(k+1)$ для любого $k\ge1$,\n\nто $P(n)$ истинно для всех натуральных $n$.',
            'en': r'Let $P(n)$ be a statement about a positive integer $n$. If\n\n1. $P(1)$ is true, and\n2. the truth of $P(k)$ implies the truth of $P(k+1)$ for every $k\ge1$,\n\nthen $P(n)$ is true for every positive integer $n$.'}},
  {'t': 'proof',
   'text': {'ru': r'Индукция равносильна **принципу наименьшего числа**: всякое непустое множество натуральных чисел имеет наименьший элемент.\n\nПредположим противное: пусть выполнены условия 1 и 2, но множество $$M=\left\{n:\ P(n)\ \text{ложно}\right\}$$ непусто. Тогда в $M$ есть наименьший элемент $m$.\n\nПо условию 1 имеем $m\ne1$, значит $m\ge2$ и число $m-1$ натуральное. Оно меньше $m$, а $m$ — наименьшее в $M$, поэтому $m-1\notin M$, то есть $P(m-1)$ истинно.\n\nНо тогда по условию 2 истинно и $P(m)$ — противоречие с $m\in M$ ✓ Значит $M$ пусто $\blacksquare$',
            'en': r'Induction is equivalent to the **least element principle**: every non-empty set of positive integers has a smallest member.\n\nSuppose not: conditions 1 and 2 hold but $$M=\left\{n:\ P(n)\ \text{is false}\right\}$$ is non-empty. Then $M$ has a least element $m$.\n\nBy condition 1, $m\ne1$, so $m\ge2$ and $m-1$ is a positive integer. It is smaller than $m$, and $m$ is least in $M$, so $m-1\notin M$, i.e. $P(m-1)$ is true.\n\nBut then condition 2 makes $P(m)$ true — contradicting $m\in M$ ✓ So $M$ is empty $\blacksquare$'}},
  {'t': 'note',
   'text': {'ru': r'**Сильная индукция.** Иногда шаг требует не только $P(k)$, но всех предыдущих утверждений сразу. Формулировка: если $P(1)$ истинно и из истинности $P(1),\dots,P(k)$ следует $P(k+1)$, то $P(n)$ истинно всегда. Доказательство то же самое. Сильная индукция незаменима для рекуррент, где $a_{n+2}$ зависит от двух предыдущих членов.',
            'en': r'**Strong induction.** Sometimes the step needs not just $P(k)$ but all earlier statements at once. The statement: if $P(1)$ holds and $P(1),\dots,P(k)$ together imply $P(k+1)$, then $P(n)$ holds for every $n$. The proof is identical. Strong induction is indispensable for recurrences where $a_{n+2}$ depends on two earlier terms.'}},
  {'t': 'warn',
   'text': {'ru': r'Две классические ошибки.\n\n**Забытая база.** Из «$P(k)\Rightarrow P(k+1)$» без базы не следует ничего: утверждение «$n=n+1$» прекрасно наследуется, но ложно.\n\n**Шаг, не работающий с малых значений.** В знаменитом «доказательстве», что все лошади одного цвета, переход от $k$ к $k+1$ опирается на пересечение двух групп по $k$ лошадей — а при $k=1$ это пересечение пусто. Всегда проверяйте, что шаг корректен уже при наименьшем $k$.',
            'en': r'Two classic mistakes.\n\n**A missing base.** From "$P(k)\Rightarrow P(k+1)$" alone nothing follows: the statement "$n=n+1$" is inherited perfectly and is false.\n\n**A step that fails at small values.** In the famous "proof" that all horses have the same colour, the passage from $k$ to $k+1$ uses the overlap of two groups of $k$ horses — and for $k=1$ that overlap is empty. Always check that the step is valid already at the smallest $k$.'}},
 ],
 2: [
  {'t': 'proof',
   'text': {'ru': r'**Вывод формулы суммы геометрической прогрессии.** Пусть $$S_n=b_1+b_1q+\dots+b_1q^{\,n-1}.$$ Умножим на $q$: $$qS_n=b_1q+b_1q^{2}+\dots+b_1q^{\,n}.$$\n\nВычтем второе равенство из первого. Все средние члены уничтожаются, остаются только крайние: $$S_n-qS_n=b_1-b_1q^{\,n}.$$\n\nПри $q\ne1$ делим на $1-q$: $$S_n=b_1\frac{1-q^{\,n}}{1-q} \quad\checkmark$$\n\nПри $q=1$ формула неприменима, но и не нужна: все члены равны $b_1$, поэтому $S_n=nb_1$ ✓ $\blacksquare$',
            'en': r'**Deriving the sum of a geometric progression.** Let $$S_n=b_1+b_1q+\dots+b_1q^{\,n-1}.$$ Multiply by $q$: $$qS_n=b_1q+b_1q^{2}+\dots+b_1q^{\,n}.$$\n\nSubtract the second from the first. Every middle term cancels and only the ends survive: $$S_n-qS_n=b_1-b_1q^{\,n}.$$\n\nFor $q\ne1$ divide by $1-q$: $$S_n=b_1\frac{1-q^{\,n}}{1-q} \quad\checkmark$$\n\nFor $q=1$ the formula does not apply and is not needed: all terms equal $b_1$, so $S_n=nb_1$ ✓ $\blacksquare$'}},
  {'t': 'thm',
   'name': {'ru': 'Характеристическое свойство', 'en': 'The characteristic property'},
   'text': {'ru': r'Последовательность ненулевых чисел является геометрической прогрессией тогда и только тогда, когда каждый её член, кроме крайних, равен по модулю среднему геометрическому соседей: $$b_n^{2}=b_{n-1}b_{n+1}.$$',
            'en': r'A sequence of non-zero numbers is a geometric progression if and only if every term other than the ends satisfies $$b_n^{2}=b_{n-1}b_{n+1}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'**Если прогрессия,** то $b_{n-1}=\dfrac{b_n}{q}$ и $b_{n+1}=b_nq$, значит их произведение равно $b_n^{2}$ ✓\n\n**Обратно.** Из $b_n^{2}=b_{n-1}b_{n+1}$ и $b_n\ne0$ следует $$\frac{b_{n+1}}{b_n}=\frac{b_n}{b_{n-1}},$$ то есть отношение соседних членов одно и то же на каждом шаге. Обозначив его через $q$, получаем прогрессию ✓ $\blacksquare$',
            'en': r'**If it is a progression** then $b_{n-1}=\dfrac{b_n}{q}$ and $b_{n+1}=b_nq$, so their product is $b_n^{2}$ ✓\n\n**Conversely,** from $b_n^{2}=b_{n-1}b_{n+1}$ with $b_n\ne0$ we get $$\frac{b_{n+1}}{b_n}=\frac{b_n}{b_{n-1}},$$ so the ratio of consecutive terms is the same at every step. Calling it $q$ gives a progression ✓ $\blacksquare$'}},
 ],
 4: [
  {'t': 'thm',
   'name': {'ru': 'Тождество Кассини', 'en': 'Cassini identity'},
   'text': {'ru': r'Для всех $n\ge1$ $$F_{n-1}F_{n+1}-F_n^{2}=\left(-1\right)^{n}.$$',
            'en': r'For all $n\ge1$ $$F_{n-1}F_{n+1}-F_n^{2}=\left(-1\right)^{n}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Индукция по $n$. Обозначим $D_n=F_{n-1}F_{n+1}-F_n^{2}$.\n\n**База $n=1$:** $F_0F_2-F_1^{2}=0\cdot1-1=-1=\left(-1\right)^{1}$ ✓\n\n**Шаг.** Подставим $F_{n+2}=F_{n+1}+F_n$: $$D_{n+1}=F_nF_{n+2}-F_{n+1}^{2}=F_n\left(F_{n+1}+F_n\right)-F_{n+1}^{2}.$$\n\nТеперь заменим один множитель $F_{n+1}$ во втором слагаемом на $F_n+F_{n-1}$: $$D_{n+1}=F_nF_{n+1}+F_n^{2}-F_{n+1}\left(F_n+F_{n-1}\right)=F_n^{2}-F_{n-1}F_{n+1}=-D_n .$$\n\nТак что знак меняется на каждом шаге, а по базе $D_1=-1$, значит $D_n=\left(-1\right)^{n}$ ✓ $\blacksquare$',
            'en': r'Induction on $n$. Write $D_n=F_{n-1}F_{n+1}-F_n^{2}$.\n\n**Base $n=1$:** $F_0F_2-F_1^{2}=0\cdot1-1=-1=\left(-1\right)^{1}$ ✓\n\n**Step.** Substitute $F_{n+2}=F_{n+1}+F_n$: $$D_{n+1}=F_nF_{n+2}-F_{n+1}^{2}=F_n\left(F_{n+1}+F_n\right)-F_{n+1}^{2}.$$\n\nNow replace one factor $F_{n+1}$ in the last term by $F_n+F_{n-1}$: $$D_{n+1}=F_nF_{n+1}+F_n^{2}-F_{n+1}\left(F_n+F_{n-1}\right)=F_n^{2}-F_{n-1}F_{n+1}=-D_n .$$\n\nSo the sign flips at every step, and $D_1=-1$ gives $D_n=\left(-1\right)^{n}$ ✓ $\blacksquare$'}},
  {'t': 'note',
   'text': {'ru': r'Тождество Кассини стоит за известной «геометрической иллюзией»: квадрат $8\times8$ разрезают на четыре части и складывают из них прямоугольник $5\times13$. Площади отличаются на $64-65=-1$ — ровно на $F_5F_7-F_6^{2}$. Недостающая площадь спрятана в тонкой щели вдоль диагонали.',
            'en': r'Cassini identity is behind the famous dissection paradox: an $8\times8$ square is cut into four pieces which reassemble into a $5\times13$ rectangle. The areas differ by $64-65=-1$ — exactly $F_5F_7-F_6^{2}$. The missing area hides in a thin sliver along the diagonal.'}},

  {'t': 'thm',
   'name': {'ru': 'Формула сложения', 'en': 'The addition formula'},
   'text': {'ru': r'Для всех $m,n\ge1$ $$F_{m+n}=F_mF_{n+1}+F_{m-1}F_n .$$ В частности, при $m=n$ получается $F_{2n}=F_n\left(F_{n+1}+F_{n-1}\right)$.',
            'en': r'For all $m,n\ge1$ $$F_{m+n}=F_mF_{n+1}+F_{m-1}F_n .$$ In particular $m=n$ gives $F_{2n}=F_n\left(F_{n+1}+F_{n-1}\right)$.'}},
  {'t': 'proof',
   'text': {'ru': r'Зафиксируем $m$ и проведём индукцию по $n$.\n\n**База $n=1$:** правая часть равна $F_mF_2+F_{m-1}F_1=F_m+F_{m-1}=F_{m+1}$ ✓\n\n**База $n=2$:** $F_mF_3+F_{m-1}F_2=2F_m+F_{m-1}=F_m+\left(F_m+F_{m-1}\right)=F_m+F_{m+1}=F_{m+2}$ ✓\n\n**Шаг.** Пусть формула верна для $n$ и $n+1$. Сложим два равенства: $$F_{m+n}+F_{m+n+1}=F_m\left(F_{n+1}+F_{n+2}\right)+F_{m-1}\left(F_n+F_{n+1}\right).$$ Слева стоит $F_{m+n+2}$, а в скобках справа — $F_{n+3}$ и $F_{n+2}$ ✓ Это формула для $n+2$ $\blacksquare$\n\n**Следствие.** При $m=n$ получаем $F_{2n}=F_nF_{n+1}+F_{n-1}F_n=F_n\left(F_{n+1}+F_{n-1}\right)$, значит $F_n\mid F_{2n}$. Индукцией отсюда следует $F_n\mid F_{kn}$ — ключевой шаг в доказательстве равенства $\gcd\left(F_m,F_n\right)=F_{\gcd\left(m,n\right)}$.',
            'en': r'Fix $m$ and induct on $n$.\n\n**Base $n=1$:** the right side is $F_mF_2+F_{m-1}F_1=F_m+F_{m-1}=F_{m+1}$ ✓\n\n**Base $n=2$:** $F_mF_3+F_{m-1}F_2=2F_m+F_{m-1}=F_m+F_{m+1}=F_{m+2}$ ✓\n\n**Step.** Assume the formula for $n$ and $n+1$ and add the two equalities: $$F_{m+n}+F_{m+n+1}=F_m\left(F_{n+1}+F_{n+2}\right)+F_{m-1}\left(F_n+F_{n+1}\right).$$ The left side is $F_{m+n+2}$, and the brackets on the right are $F_{n+3}$ and $F_{n+2}$ ✓ That is the formula for $n+2$ $\blacksquare$\n\n**Corollary.** With $m=n$ we get $F_{2n}=F_n\left(F_{n+1}+F_{n-1}\right)$, so $F_n\mid F_{2n}$. Induction then gives $F_n\mid F_{kn}$ — the key step towards $\gcd\left(F_m,F_n\right)=F_{\gcd\left(m,n\right)}$.'}},

  {'t': 'thm',
   'name': {'ru': 'Наибольший общий делитель чисел Фибоначчи',
            'en': 'The gcd of Fibonacci numbers'},
   'text': {'ru': r'$$\gcd\left(F_m,F_n\right)=F_{\gcd\left(m,n\right)}.$$',
            'en': r'$$\gcd\left(F_m,F_n\right)=F_{\gcd\left(m,n\right)}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть $m>n$ и $m=n+r$. По формуле сложения $$F_m=F_{n+r}=F_rF_{n+1}+F_{r-1}F_n .$$\n\nВторое слагаемое делится на $F_n$, поэтому $$\gcd\left(F_m,F_n\right)=\gcd\left(F_rF_{n+1},\,F_n\right).$$ Но соседние числа Фибоначчи взаимно просты, значит $\gcd\left(F_{n+1},F_n\right)=1$, и множитель $F_{n+1}$ можно отбросить: $$\gcd\left(F_m,F_n\right)=\gcd\left(F_r,F_n\right).$$\n\nПереход от пары $\left(m,n\right)$ к паре $\left(r,n\right)=\left(m-n,\,n\right)$ — это в точности шаг алгоритма Евклида на индексах. Повторяя его, придём к паре $\left(\gcd\left(m,n\right),0\right)$, а $F_0=0$, поэтому $$\gcd\left(F_m,F_n\right)=F_{\gcd\left(m,n\right)} \quad\checkmark\qquad\blacksquare$$',
            'en': r'Let $m>n$ and $m=n+r$. The addition formula gives $$F_m=F_{n+r}=F_rF_{n+1}+F_{r-1}F_n .$$\n\nThe second term is divisible by $F_n$, so $$\gcd\left(F_m,F_n\right)=\gcd\left(F_rF_{n+1},\,F_n\right).$$ But consecutive Fibonacci numbers are coprime, so $\gcd\left(F_{n+1},F_n\right)=1$ and the factor $F_{n+1}$ may be dropped: $$\gcd\left(F_m,F_n\right)=\gcd\left(F_r,F_n\right).$$\n\nPassing from $\left(m,n\right)$ to $\left(m-n,\,n\right)$ is exactly one step of the Euclidean algorithm on the indices. Repeating it reaches $\left(\gcd\left(m,n\right),0\right)$, and $F_0=0$, so $$\gcd\left(F_m,F_n\right)=F_{\gcd\left(m,n\right)} \quad\checkmark\qquad\blacksquare$$'}},

  {'t': 'ex',
   'q': {'ru': r'Докажите, что $\gcd\left(F_{100},F_{60}\right)=F_{20}$, и найдите $F_{20}$.',
         'en': r'Prove that $\gcd\left(F_{100},F_{60}\right)=F_{20}$ and compute $F_{20}$.'},
   'steps': {'ru': [r'По теореме достаточно найти $\gcd\left(100,60\right)$.',
                    r'Алгоритм Евклида: $100=1\cdot60+40$, $60=1\cdot40+20$, $40=2\cdot20$. Значит $\gcd=20$ ✓',
                    r'Выпишем числа Фибоначчи до двадцатого: $1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765$.',
                    r'Итак $\gcd\left(F_{100},F_{60}\right)=F_{20}=6765$.'],
             'en': [r'By the theorem it suffices to find $\gcd\left(100,60\right)$.',
                    r'Euclid: $100=1\cdot60+40$, $60=1\cdot40+20$, $40=2\cdot20$. So $\gcd=20$ ✓',
                    r'List the Fibonacci numbers up to the twentieth: $1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765$.',
                    r'Hence $\gcd\left(F_{100},F_{60}\right)=F_{20}=6765$.']},
   'ans': {'ru': r'$F_{20}=6765$.', 'en': r'$F_{20}=6765$.'}},

  {'t': 'note',
   'text': {'ru': r'**Теорема Цекендорфа.** Всякое натуральное число единственным образом представляется как сумма различных чисел Фибоначчи, среди которых нет двух соседних. Например, $$100=89+8+3=F_{11}+F_6+F_4 .$$ Представление находится жадным алгоритмом: каждый раз вычитаем наибольшее подходящее число Фибоначчи.',
            'en': r'**Zeckendorf theorem.** Every positive integer is uniquely a sum of distinct Fibonacci numbers no two of which are consecutive. For instance $$100=89+8+3=F_{11}+F_6+F_4 .$$ The representation is found greedily: repeatedly subtract the largest Fibonacci number that fits.'}},
 ],
}
