# -*- coding: utf-8 -*-
"""Topic 4 — deeper theory, woven into lesson_04.py by content/build.py."""

PYTHAG = {
 'h': {'ru': 'Пифагоровы тройки',
       'en': 'Pythagorean triples'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Уравнение $x^{2}+y^{2}=z^{2}$ — самое знаменитое диофантово уравнение. Его решения известны полностью, и вывод формулы — образец того, как разложение на множители и взаимная простота вместе решают задачу.',
            'en': r'The equation $x^{2}+y^{2}=z^{2}$ is the most famous Diophantine equation of all. Its solutions are known completely, and deriving them shows how factorisation and coprimality together finish a problem.'}},

  {'t': 'def',
   'name': {'ru': 'Примитивная тройка', 'en': 'Primitive triple'},
   'text': {'ru': r'Тройка натуральных чисел $(x,y,z)$ с $x^{2}+y^{2}=z^{2}$ называется **примитивной**, если $\gcd(x,y,z)=1$. Любая тройка получается из примитивной умножением на общий множитель, поэтому достаточно описать примитивные.',
            'en': r'A triple of positive integers $(x,y,z)$ with $x^{2}+y^{2}=z^{2}$ is **primitive** if $\gcd(x,y,z)=1$. Every triple is a primitive one scaled by a common factor, so it suffices to describe the primitive ones.'}},

  {'t': 'lemma',
   'name': {'ru': 'Чётности в примитивной тройке', 'en': 'Parities in a primitive triple'},
   'text': {'ru': r'В примитивной тройке ровно одно из чисел $x,y$ чётно, а $z$ нечётно.',
            'en': r'In a primitive triple exactly one of $x,y$ is even, and $z$ is odd.'}},
  {'t': 'proof',
   'text': {'ru': r'**Оба чётными быть не могут:** тогда $z^{2}=x^{2}+y^{2}$ было бы чётно, значит и $z$ чётно, и $\gcd(x,y,z)\ge2$ ✗\n\n**Оба нечётными тоже:** квадрат нечётного числа даёт остаток $1$ по модулю $4$, поэтому $$z^{2}=x^{2}+y^{2}\equiv1+1=2\pmod4 .$$ Но квадрат сравним с $0$ или $1$ по модулю $4$, а не с $2$ ✗\n\nЗначит ровно одно из $x,y$ чётно, и тогда $z^{2}\equiv0+1=1\pmod4$, то есть $z$ нечётно. $\blacksquare$',
            'en': r'**They cannot both be even:** then $z^{2}=x^{2}+y^{2}$ would be even, so $z$ would be even and $\gcd(x,y,z)\ge2$ ✗\n\n**Nor both odd:** the square of an odd number is $1$ mod $4$, so $$z^{2}=x^{2}+y^{2}\equiv2\pmod4 .$$ But a square is $0$ or $1$ mod $4$, never $2$ ✗\n\nSo exactly one of $x,y$ is even, and then $z^{2}\equiv1\pmod4$, making $z$ odd. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Описание всех примитивных троек', 'en': 'All primitive triples'},
   'text': {'ru': r'Примитивные тройки с чётным $x$ — это в точности $$x=2mn,\qquad y=m^{2}-n^{2},\qquad z=m^{2}+n^{2},$$ где $m>n>0$, $\gcd(m,n)=1$ и числа $m,n$ разной чётности. Разным парам $(m,n)$ отвечают разные тройки.',
            'en': r'The primitive triples with $x$ even are exactly $$x=2mn,\qquad y=m^{2}-n^{2},\qquad z=m^{2}+n^{2},$$ with $m>n>0$, $\gcd(m,n)=1$ and $m,n$ of opposite parity. Different pairs $(m,n)$ give different triples.'}},
  {'t': 'proof',
   'text': {'ru': r'**Эти тройки подходят.** Проверим прямо: $$(2mn)^{2}+\left(m^{2}-n^{2}\right)^{2}=4m^{2}n^{2}+m^{4}-2m^{2}n^{2}+n^{4}=m^{4}+2m^{2}n^{2}+n^{4}=\left(m^{2}+n^{2}\right)^{2} \quad\checkmark$$\n\n**Других нет.** Пусть $(x,y,z)$ примитивна и $x$ чётно. Перепишем уравнение: $$x^{2}=z^{2}-y^{2}=(z-y)(z+y).$$\n\nПо лемме $y$ и $z$ нечётны, значит $z-y$ и $z+y$ чётны. Положим $$u=\frac{z-y}{2},\qquad v=\frac{z+y}{2},\qquad\text{тогда}\qquad uv=\left(\frac x2\right)^{2} .$$\n\n**Числа $u$ и $v$ взаимно просты.** Общий делитель $d$ делит их сумму $z$ и разность $y$. Но $\gcd(y,z)=1$: общий делитель $y$ и $z$ делил бы и $x^{2}=z^{2}-y^{2}$, а значит и $x$, вопреки примитивности. Значит $d=1$.\n\n**Взаимно простые множители полного квадрата — сами квадраты.** Отсюда $$u=n^{2},\qquad v=m^{2}$$ для некоторых натуральных $m>n>0$ с $\gcd(m,n)=1$.\n\nВозвращаясь, $$z=v+u=m^{2}+n^{2},\qquad y=v-u=m^{2}-n^{2},\qquad x=2\sqrt{uv}=2mn .$$\n\nНаконец, нечётность $y=m^{2}-n^{2}$ требует, чтобы $m$ и $n$ имели разную чётность. $\blacksquare$',
            'en': r'**These triples work.** Check directly: $$(2mn)^{2}+\left(m^{2}-n^{2}\right)^{2}=m^{4}+2m^{2}n^{2}+n^{4}=\left(m^{2}+n^{2}\right)^{2} \quad\checkmark$$\n\n**There are no others.** Let $(x,y,z)$ be primitive with $x$ even. Rewrite the equation: $$x^{2}=z^{2}-y^{2}=(z-y)(z+y).$$\n\nBy the lemma $y$ and $z$ are odd, so $z-y$ and $z+y$ are even. Put $$u=\frac{z-y}{2},\qquad v=\frac{z+y}{2},\qquad\text{so}\qquad uv=\left(\frac x2\right)^{2} .$$\n\n**The numbers $u,v$ are coprime.** A common divisor $d$ divides their sum $z$ and difference $y$. But $\gcd(y,z)=1$: a common divisor of $y$ and $z$ would divide $x^{2}=z^{2}-y^{2}$, hence $x$, against primitivity. So $d=1$.\n\n**Coprime factors of a perfect square are themselves squares.** Hence $$u=n^{2},\qquad v=m^{2}$$ for some $m>n>0$ with $\gcd(m,n)=1$.\n\nGoing back, $$z=m^{2}+n^{2},\qquad y=m^{2}-n^{2},\qquad x=2mn .$$\n\nFinally, $y=m^{2}-n^{2}$ being odd forces $m$ and $n$ to have opposite parity. $\blacksquare$'}},

  {'t': 'table',
   'head': {'ru': ['$m$', '$n$', '$x=2mn$', '$y=m^2-n^2$', '$z=m^2+n^2$'],
            'en': ['$m$', '$n$', '$x=2mn$', '$y=m^2-n^2$', '$z=m^2+n^2$']},
   'rows': {'ru': [['$2$','$1$','$4$','$3$','$5$'],
                   ['$3$','$2$','$12$','$5$','$13$'],
                   ['$4$','$1$','$8$','$15$','$17$'],
                   ['$4$','$3$','$24$','$7$','$25$'],
                   ['$5$','$2$','$20$','$21$','$29$']],
            'en': [['$2$','$1$','$4$','$3$','$5$'],
                   ['$3$','$2$','$12$','$5$','$13$'],
                   ['$4$','$1$','$8$','$15$','$17$'],
                   ['$4$','$3$','$24$','$7$','$25$'],
                   ['$5$','$2$','$20$','$21$','$29$']]}},

  {'t': 'ex',
   'q': {'ru': r'Найдите все пифагоровы треугольники, у которых один из катетов равен $15$.',
         'en': r'Find all Pythagorean triangles with a leg equal to $15$.'},
   'steps': {'ru': [r'Катет $15$ нечётен, значит это «нечётный» катет; запишем $z^{2}-b^{2}=225$.',
                    r'Разложим: $(z-b)(z+b)=225$, причём оба множителя нечётны и $z-b<z+b$.',
                    r'Разложения $225=3^{2}\cdot5^{2}$ на такие пары: $1\cdot225$, $3\cdot75$, $5\cdot45$, $9\cdot25$.',
                    r'Считаем $z=\tfrac{(z-b)+(z+b)}2$ и $b=\tfrac{(z+b)-(z-b)}2$.',
                    r'Получаем $(b,z)=(112,113),\ (36,39),\ (20,25),\ (8,17)$.',
                    r'Проверка для $(8,15,17)$: $64+225=289=17^{2}$ ✓'],
             'en': [r'The leg $15$ is odd, so it is the "odd" leg; write $z^{2}-b^{2}=225$.',
                    r'Factor: $(z-b)(z+b)=225$ with both factors odd and $z-b<z+b$.',
                    r'The factorisations of $225=3^{2}\cdot5^{2}$ into such pairs are $1\cdot225$, $3\cdot75$, $5\cdot45$, $9\cdot25$.',
                    r'Compute $z=\tfrac{(z-b)+(z+b)}2$ and $b=\tfrac{(z+b)-(z-b)}2$.',
                    r'This gives $(b,z)=(112,113),\ (36,39),\ (20,25),\ (8,17)$.',
                    r'Check for $(8,15,17)$: $64+225=289=17^{2}$ ✓']},
   'ans': {'ru': r'Четыре треугольника: $(15,8,17)$, $(15,20,25)$, $(15,36,39)$, $(15,112,113)$.',
           'en': r'Four triangles: $(15,8,17)$, $(15,20,25)$, $(15,36,39)$, $(15,112,113)$.'}},

  {'t': 'note',
   'text': {'ru': r'**Великая теорема Ферма.** При показателе $2$ решений бесконечно много, а при $n\ge3$ уравнение $$x^{n}+y^{n}=z^{n}$$ не имеет решений в натуральных числах. Ферма записал это на полях книги в $1637$ году, добавив, что нашёл «поистине чудесное доказательство», для которого не хватило полей. Доказательство нашли лишь в $1995$ году (Эндрю Уайлс), и оно занимает более сотни страниц. Случай $n=4$ доступен школьными средствами — он разбирается методом спуска.',
            'en': r'**Fermat’s Last Theorem.** With exponent $2$ there are infinitely many solutions, but for $n\ge3$ the equation $$x^{n}+y^{n}=z^{n}$$ has no solutions in positive integers. Fermat wrote this in a book margin in $1637$, adding that he had a "truly marvellous proof" that the margin was too small to hold. A proof appeared only in $1995$ (Andrew Wiles) and runs to well over a hundred pages. The case $n=4$ is within reach of school methods — by infinite descent.'}},
 ],
}


TWOSQ = {
 'h': {'ru': 'Суммы двух квадратов',
       'en': 'Sums of two squares'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Какие числа представимы в виде $a^{2}+b^{2}$? Ответ красив и полностью известен, и главную роль в нём играют остатки простых по модулю $4$.',
            'en': r'Which numbers can be written as $a^{2}+b^{2}$? The answer is beautiful and completely known, and the leading role is played by the residues of primes modulo $4$.'}},

  {'t': 'thm',
   'name': {'ru': 'Тождество Брахмагупты — Фибоначчи', 'en': 'The Brahmagupta–Fibonacci identity'},
   'text': {'ru': r'$$\left(a^{2}+b^{2}\right)\left(c^{2}+d^{2}\right)=(ac+bd)^{2}+(ad-bc)^{2}=(ac-bd)^{2}+(ad+bc)^{2} .$$ Значит **произведение двух сумм двух квадратов снова является суммой двух квадратов**.',
            'en': r'$$\left(a^{2}+b^{2}\right)\left(c^{2}+d^{2}\right)=(ac+bd)^{2}+(ad-bc)^{2}=(ac-bd)^{2}+(ad+bc)^{2} .$$ So **a product of two sums of two squares is again a sum of two squares**.'}},
  {'t': 'proof',
   'text': {'ru': r'Раскроем правую часть первого равенства: $$(ac+bd)^{2}=a^{2}c^{2}+2abcd+b^{2}d^{2} ,$$ $$(ad-bc)^{2}=a^{2}d^{2}-2abcd+b^{2}c^{2} .$$\n\nСлагаемые $\pm2abcd$ уничтожаются, и остаётся $$a^{2}c^{2}+b^{2}d^{2}+a^{2}d^{2}+b^{2}c^{2}=a^{2}\left(c^{2}+d^{2}\right)+b^{2}\left(c^{2}+d^{2}\right)=\left(a^{2}+b^{2}\right)\left(c^{2}+d^{2}\right) \quad\checkmark$$\n\nВторое равенство получается заменой $d\to-d$. $\blacksquare$',
            'en': r'Expand the first right-hand side: $$(ac+bd)^{2}=a^{2}c^{2}+2abcd+b^{2}d^{2} ,$$ $$(ad-bc)^{2}=a^{2}d^{2}-2abcd+b^{2}c^{2} .$$\n\nThe terms $\pm2abcd$ cancel, leaving $$a^{2}c^{2}+b^{2}d^{2}+a^{2}d^{2}+b^{2}c^{2}=\left(a^{2}+b^{2}\right)\left(c^{2}+d^{2}\right) \quad\checkmark$$\n\nThe second identity comes from replacing $d$ by $-d$. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Препятствие по модулю 4', 'en': 'The obstruction modulo 4'},
   'text': {'ru': r'Сумма двух квадратов никогда не даёт остаток $3$ при делении на $4$. Значит ни одно число вида $4k+3$ не представимо в виде $a^{2}+b^{2}$.',
            'en': r'A sum of two squares never leaves remainder $3$ on division by $4$. So no number of the form $4k+3$ is a sum of two squares.'}},
  {'t': 'proof',
   'text': {'ru': r'Квадрат целого числа сравним с $0$ или $1$ по модулю $4$: чётное даёт $(2k)^{2}=4k^{2}\equiv0$, нечётное — $(2k+1)^{2}=4k(k+1)+1\equiv1$.\n\nЗначит сумма двух квадратов сравнима с одним из чисел $$0+0=0,\qquad 0+1=1,\qquad 1+1=2 ,$$ то есть с $0$, $1$ или $2$, но не с $3$. $\blacksquare$',
            'en': r'A square is $0$ or $1$ mod $4$: an even number gives $(2k)^{2}\equiv0$, an odd one $(2k+1)^{2}=4k(k+1)+1\equiv1$.\n\nSo a sum of two squares is congruent to one of $$0+0=0,\qquad 0+1=1,\qquad 1+1=2 ,$$ never to $3$. $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Ферма о двух квадратах', 'en': 'Fermat’s two-square theorem'},
   'text': {'ru': r'Нечётное простое $p$ представимо в виде $p=a^{2}+b^{2}$ **тогда и только тогда**, когда $p\equiv1\pmod4$. Такое представление единственно с точностью до порядка и знаков.',
            'en': r'An odd prime $p$ is a sum of two squares $p=a^{2}+b^{2}$ **if and only if** $p\equiv1\pmod4$, and the representation is unique up to order and signs.'}},
  {'t': 'proof',
   'text': {'ru': r'**Необходимость** — это предыдущая теорема: при $p\equiv3\pmod4$ представления нет.\n\n**Достаточность (набросок).** Пусть $p\equiv1\pmod4$. По критерию Эйлера сравнение $x^{2}\equiv-1\pmod p$ разрешимо; возьмём такое $x$, то есть $p\mid x^{2}+1$.\n\nДалее применяют **лемму Туэ**: если $p\mid x^{2}+1$, то найдутся целые $a,b$ с $0<|a|,|b|<\sqrt p$ и $a\equiv xb\pmod p$. (Лемма доказывается принципом Дирихле: пар $(u,v)$ с $0\le u,v<\sqrt p$ больше, чем $p$ вычетов, значит две пары дают одинаковое $u-xv$.)\n\nТогда $$a^{2}+b^{2}\equiv x^{2}b^{2}+b^{2}=b^{2}\left(x^{2}+1\right)\equiv0\pmod p ,$$ то есть $p\mid a^{2}+b^{2}$. Но $$0<a^{2}+b^{2}<p+p=2p ,$$ значит $a^{2}+b^{2}=p$ ✓ $\blacksquare$',
            'en': r'**Necessity** is the previous theorem: for $p\equiv3\pmod4$ no representation exists.\n\n**Sufficiency (sketch).** Let $p\equiv1\pmod4$. Euler’s criterion makes $x^{2}\equiv-1\pmod p$ solvable; take such an $x$, so $p\mid x^{2}+1$.\n\nNow apply **Thue’s lemma**: if $p\mid x^{2}+1$ there are integers $a,b$ with $0<|a|,|b|<\sqrt p$ and $a\equiv xb\pmod p$. (The lemma follows from the pigeonhole principle: there are more pairs $(u,v)$ with $0\le u,v<\sqrt p$ than there are $p$ residues, so two pairs give the same $u-xv$.)\n\nThen $$a^{2}+b^{2}\equiv x^{2}b^{2}+b^{2}=b^{2}\left(x^{2}+1\right)\equiv0\pmod p ,$$ so $p\mid a^{2}+b^{2}$. But $$0<a^{2}+b^{2}<2p ,$$ hence $a^{2}+b^{2}=p$ ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Какие числа вообще представимы', 'en': 'Which numbers are sums of two squares'},
   'text': {'ru': r'Натуральное число $n$ представимо в виде суммы двух квадратов **тогда и только тогда**, когда в его разложении каждое простое вида $4k+3$ входит в **чётной** степени.',
            'en': r'A positive integer $n$ is a sum of two squares **if and only if** every prime of the form $4k+3$ occurs in its factorisation to an **even** power.'}},
  {'t': 'ex',
   'q': {'ru': r'Представимы ли числа $45$, $2025$ и $2023$ в виде суммы двух квадратов?',
         'en': r'Are $45$, $2025$ and $2023$ sums of two squares?'},
   'steps': {'ru': [r'$45=3^{2}\cdot5$. Простое $3\equiv3\pmod4$ входит в чётной степени ✓ Значит представимо.',
                    r'Найдём явно: $5=1^{2}+2^{2}$, умножим на $9=3^{2}$: $45=3^{2}+6^{2}=9+36$ ✓',
                    r'$2025=3^{4}\cdot5^{2}$. Показатель тройки равен $4$ — чётный ✓ И действительно $2025=27^{2}+36^{2}=729+1296$.',
                    r'$2023=7\cdot17^{2}$. Простое $7\equiv3\pmod4$ входит в **первой** степени ✗ Значит не представимо.',
                    r'Проверка для $2023$ иначе: $2023=4\cdot505+3\equiv3\pmod4$ — уже этого достаточно.'],
             'en': [r'$45=3^{2}\cdot5$. The prime $3\equiv3\pmod4$ appears to an even power ✓ So it is representable.',
                    r'Explicitly: $5=1^{2}+2^{2}$, and multiplying by $9=3^{2}$ gives $45=3^{2}+6^{2}=9+36$ ✓',
                    r'$2025=3^{4}\cdot5^{2}$. The exponent of $3$ is $4$, even ✓ And indeed $2025=27^{2}+36^{2}$.',
                    r'$2023=7\cdot17^{2}$. The prime $7\equiv3\pmod4$ appears to the **first** power ✗ So it is not representable.',
                    r'A shortcut for $2023$: it is $\equiv3\pmod4$, which already settles it.']},
   'ans': {'ru': r'$45$ и $2025$ представимы, $2023$ — нет.',
           'en': r'$45$ and $2025$ are; $2023$ is not.'}},

  {'t': 'idea',
   'text': {'ru': r'В олимпиадных задачах чаще нужна **отрицательная** часть теории: чтобы доказать, что уравнение не имеет решений, достаточно найти простое $p\equiv3\pmod4$, входящее в нечётной степени, — или просто посмотреть на остаток по модулю $4$.',
            'en': r'In olympiad problems the **negative** half is what is usually needed: to show an equation has no solutions it is enough to find a prime $p\equiv3\pmod4$ occurring to an odd power — or simply to look at the residue mod $4$.'}},
 ],
}


PELL = {
 'h': {'ru': 'Уравнение Пелля',
       'en': 'The Pell equation'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Уравнение $x^{2}-Dy^{2}=1$ с неквадратным натуральным $D$ ведёт себя удивительно: у него либо нет нетривиальных решений, либо их сразу бесконечно много, и все они порождаются одним-единственным.',
            'en': r'The equation $x^{2}-Dy^{2}=1$ with $D$ a non-square positive integer behaves remarkably: it either has no non-trivial solution or infinitely many at once, all generated by a single one.'}},

  {'t': 'def',
   'name': {'ru': 'Уравнение Пелля', 'en': 'Pell’s equation'},
   'text': {'ru': r'$$x^{2}-Dy^{2}=1 ,$$ где $D$ — натуральное число, не являющееся полным квадратом. Решение $(x,y)=(1,0)$ называют тривиальным; наименьшее решение с $y>0$ — **фундаментальным**.',
            'en': r'$$x^{2}-Dy^{2}=1 ,$$ with $D$ a positive non-square integer. The solution $(x,y)=(1,0)$ is called trivial; the smallest solution with $y>0$ is the **fundamental** one.'}},
  {'t': 'warn',
   'text': {'ru': r'Условие «$D$ не квадрат» существенно. При $D=k^{2}$ уравнение превращается в $$(x-ky)(x+ky)=1 ,$$ откуда $x=\pm1$, $y=0$ — только тривиальные решения.',
            'en': r'The hypothesis that $D$ is not a square matters. For $D=k^{2}$ the equation becomes $$(x-ky)(x+ky)=1 ,$$ forcing $x=\pm1$, $y=0$ — only the trivial solutions.'}},

  {'t': 'thm',
   'name': {'ru': 'Из одного решения — бесконечно много', 'en': 'One solution breeds infinitely many'},
   'text': {'ru': r'Пусть $\left(x_1,y_1\right)$ — решение уравнения $x^{2}-Dy^{2}=1$ с $y_1>0$. Тогда пара $$x_{k+1}=x_1x_k+Dy_1y_k,\qquad y_{k+1}=x_1y_k+y_1x_k$$ тоже является решением, и все получаемые решения попарно различны.',
            'en': r'Let $\left(x_1,y_1\right)$ solve $x^{2}-Dy^{2}=1$ with $y_1>0$. Then $$x_{k+1}=x_1x_k+Dy_1y_k,\qquad y_{k+1}=x_1y_k+y_1x_k$$ is again a solution, and all the solutions produced are pairwise distinct.'}},
  {'t': 'proof',
   'text': {'ru': r'**Это решение.** Подставим и раскроем: $$x_{k+1}^{2}-Dy_{k+1}^{2}=\left(x_1x_k+Dy_1y_k\right)^{2}-D\left(x_1y_k+y_1x_k\right)^{2}.$$\n\nПервая скобка даёт $$x_1^{2}x_k^{2}+2Dx_1x_ky_1y_k+D^{2}y_1^{2}y_k^{2} ,$$ вторая, умноженная на $D$, — $$D x_1^{2}y_k^{2}+2Dx_1y_ky_1x_k+Dy_1^{2}x_k^{2} .$$\n\nСредние члены одинаковы и уничтожаются, остаётся $$x_1^{2}x_k^{2}+D^{2}y_1^{2}y_k^{2}-Dx_1^{2}y_k^{2}-Dy_1^{2}x_k^{2}=\left(x_1^{2}-Dy_1^{2}\right)\left(x_k^{2}-Dy_k^{2}\right)=1\cdot1=1 \quad\checkmark$$\n\n**Решения различны.** При $x_k,y_k>0$ имеем $y_{k+1}=x_1y_k+y_1x_k>y_k$, значит вторая координата строго растёт, и повторений нет. $\blacksquare$\n\n**Откуда взялась формула.** Она отвечает умножению в кольце $\mathbb{Z}\left[\sqrt D\right]$: если $x_k+y_k\sqrt D$ имеет норму $1$, то и произведение $$\left(x_1+y_1\sqrt D\right)\left(x_k+y_k\sqrt D\right)=\left(x_1x_k+Dy_1y_k\right)+\left(x_1y_k+y_1x_k\right)\sqrt D$$ имеет норму $1\cdot1=1$.',
            'en': r'**It is a solution.** Substitute and expand: $$x_{k+1}^{2}-Dy_{k+1}^{2}=\left(x_1x_k+Dy_1y_k\right)^{2}-D\left(x_1y_k+y_1x_k\right)^{2}.$$\n\nThe cross terms match and cancel, leaving $$\left(x_1^{2}-Dy_1^{2}\right)\left(x_k^{2}-Dy_k^{2}\right)=1\cdot1=1 \quad\checkmark$$\n\n**The solutions are distinct.** For $x_k,y_k>0$ we get $y_{k+1}=x_1y_k+y_1x_k>y_k$, so the second coordinate strictly increases and nothing repeats. $\blacksquare$\n\n**Where the formula comes from.** It is multiplication in the ring $\mathbb{Z}\left[\sqrt D\right]$: if $x_k+y_k\sqrt D$ has norm $1$, so does $$\left(x_1+y_1\sqrt D\right)\left(x_k+y_k\sqrt D\right)=\left(x_1x_k+Dy_1y_k\right)+\left(x_1y_k+y_1x_k\right)\sqrt D .$$'}},

  {'t': 'thm',
   'name': {'ru': 'Теорема Лагранжа', 'en': 'Lagrange’s theorem'},
   'text': {'ru': r'Для любого неквадратного натурального $D$ уравнение $x^{2}-Dy^{2}=1$ имеет решение с $y>0$. Более того, **все** решения в натуральных числах получаются из фундаментального по формуле $$x_k+y_k\sqrt D=\left(x_1+y_1\sqrt D\right)^{k},\qquad k=1,2,3,\dots$$',
            'en': r'For every non-square positive integer $D$ the equation $x^{2}-Dy^{2}=1$ has a solution with $y>0$. Moreover **every** solution in positive integers arises from the fundamental one as $$x_k+y_k\sqrt D=\left(x_1+y_1\sqrt D\right)^{k},\qquad k=1,2,3,\dots$$'}},
  {'t': 'note',
   'text': {'ru': r'Доказательство существования опирается на приближение иррационального числа $\sqrt D$ рациональными дробями (теорема Дирихле о приближениях) и на принцип Дирихле — оно вполне элементарно, но длиннее, чем уместно здесь. Фундаментальное решение находят разложением $\sqrt D$ в цепную дробь.\n\n**Осторожно:** фундаментальное решение может быть неожиданно огромным. Для $D=61$ это $$x_1=1\,766\,319\,049,\qquad y_1=226\,153\,980 .$$',
            'en': r'The existence proof rests on approximating the irrational $\sqrt D$ by rationals (Dirichlet’s approximation theorem) together with the pigeonhole principle — elementary, but longer than fits here. The fundamental solution is found from the continued fraction of $\sqrt D$.\n\n**Careful:** it can be startlingly large. For $D=61$ it is $$x_1=1\,766\,319\,049,\qquad y_1=226\,153\,980 .$$'}},

  {'t': 'ex',
   'q': {'ru': r'Найдите три наименьших решения уравнения $x^{2}-2y^{2}=1$ в натуральных числах.',
         'en': r'Find the three smallest positive solutions of $x^{2}-2y^{2}=1$.'},
   'steps': {'ru': [r'Подбираем фундаментальное: $y=1$ даёт $x^{2}=3$ ✗; $y=2$ даёт $x^{2}=9$, то есть $x=3$ ✓',
                    r'Значит $\left(x_1,y_1\right)=(3,2)$.',
                    r'Рекуррентность: $x_{k+1}=3x_k+4y_k$, $y_{k+1}=3y_k+2x_k$ (здесь $D=2$).',
                    r'$(3,2)\to(3\cdot3+4\cdot2,\ 3\cdot2+2\cdot3)=(17,12)$.',
                    r'$(17,12)\to(3\cdot17+4\cdot12,\ 3\cdot12+2\cdot17)=(99,70)$.',
                    r'Проверка: $17^{2}-2\cdot12^{2}=289-288=1$ ✓ и $99^{2}-2\cdot70^{2}=9801-9800=1$ ✓'],
             'en': [r'Search for the fundamental one: $y=1$ gives $x^{2}=3$ ✗; $y=2$ gives $x^{2}=9$, i.e. $x=3$ ✓',
                    r'So $\left(x_1,y_1\right)=(3,2)$.',
                    r'The recursion with $D=2$: $x_{k+1}=3x_k+4y_k$, $y_{k+1}=3y_k+2x_k$.',
                    r'$(3,2)\to(17,12)$.',
                    r'$(17,12)\to(99,70)$.',
                    r'Check: $17^{2}-2\cdot12^{2}=1$ ✓ and $99^{2}-2\cdot70^{2}=1$ ✓']},
   'ans': {'ru': r'$(3,2)$, $(17,12)$, $(99,70)$.', 'en': r'$(3,2)$, $(17,12)$, $(99,70)$.'}},

  {'t': 'note',
   'text': {'ru': r'**Откуда название.** Эйлер по ошибке приписал уравнение английскому математику Джону Пеллю, который к нему отношения почти не имел; впервые его систематически изучали индийские математики — Брахмагупта в VII веке и Бхаскара II в XII-м. Историческая несправедливость закрепилась в названии.\n\n**Где встречается.** Уравнение Пелля возникает всюду, где нужно «почти равенство» двух величин: треугольные числа, являющиеся квадратами; приближения $\sqrt2\approx\tfrac{99}{70}$; задача Архимеда о быках.',
            'en': r'**About the name.** Euler mistakenly attributed the equation to the English mathematician John Pell, who had little to do with it; it was studied systematically much earlier by Indian mathematicians — Brahmagupta in the seventh century and Bhāskara II in the twelfth. The historical injustice stuck.\n\n**Where it appears.** Pell’s equation turns up wherever two quantities must be "almost equal": triangular numbers that are squares, approximations such as $\sqrt2\approx\tfrac{99}{70}$, and Archimedes’ cattle problem.'}},
 ],
}


SECTIONS = [(5, PYTHAG), (5, TWOSQ), (5, PELL)]


INTO = {
 5: [
  {'t': 'thm',
   'name': {'ru': 'Принцип бесконечного спуска', 'en': 'The principle of infinite descent'},
   'text': {'ru': r'Пусть из каждого решения задачи в натуральных числах можно построить **строго меньшее** решение. Тогда решений нет вовсе.',
            'en': r'Suppose that from every solution in positive integers one can build a **strictly smaller** solution. Then there are no solutions at all.'}},
  {'t': 'proof',
   'text': {'ru': r'Предположим, что решение существует. Рассмотрим множество всех натуральных значений некоторой выбранной величины (например, $z$ или суммы $x+y+z$) по всем решениям. Это непустое множество натуральных чисел, значит по принципу наименьшего числа в нём есть наименьший элемент.\n\nВозьмём отвечающее ему решение. По условию из него строится решение со строго меньшим значением той же величины — противоречие с минимальностью ✗ $\blacksquare$',
            'en': r'Suppose a solution exists. Consider the set of positive values taken by some chosen quantity (say $z$, or the sum $x+y+z$) over all solutions. This is a non-empty set of positive integers, so by the least-number principle it has a smallest element.\n\nTake the corresponding solution. By hypothesis it yields a solution with a strictly smaller value of that quantity — contradicting minimality ✗ $\blacksquare$'}},
  {'t': 'idea',
   'text': {'ru': r'Спуск — это индукция, повёрнутая наоборот. Практически он выглядит так: показываем, что все неизвестные обязаны делиться на некоторое $d>1$, делим на $d$ и получаем решение поменьше. Если делимость выводится **всегда**, спуск не останавливается — значит решений нет.',
            'en': r'Descent is induction turned around. In practice it looks like this: show that every unknown must be divisible by some $d>1$, divide through by $d$ and obtain a smaller solution. If the divisibility follows **every** time, the descent never stops — so there is no solution.'}},
  {'t': 'ex',
   'q': {'ru': r'Докажите, что уравнение $x^{2}+y^{2}=3z^{2}$ не имеет решений в натуральных числах.',
         'en': r'Prove that $x^{2}+y^{2}=3z^{2}$ has no solutions in positive integers.'},
   'steps': {'ru': [r'Возьмём решение с наименьшим $z$.',
                    r'Квадраты по модулю $3$ дают только $0$ и $1$, поэтому $x^{2}+y^{2}\equiv0\pmod3$ возможно лишь при $x^{2}\equiv y^{2}\equiv0$.',
                    r'Значит $3\mid x$ и $3\mid y$; запишем $x=3a$, $y=3b$.',
                    r'Подставим: $9a^{2}+9b^{2}=3z^{2}$, то есть $3\left(a^{2}+b^{2}\right)=z^{2}$.',
                    r'Отсюда $3\mid z^{2}$, значит $3\mid z$; запишем $z=3c$ и сократим: $a^{2}+b^{2}=3c^{2}$.',
                    r'Получили решение с $c=\tfrac z3<z$ — противоречие с минимальностью ✗'],
             'en': [r'Take a solution with the smallest $z$.',
                    r'Squares mod $3$ are only $0$ and $1$, so $x^{2}+y^{2}\equiv0\pmod3$ forces $x^{2}\equiv y^{2}\equiv0$.',
                    r'Hence $3\mid x$ and $3\mid y$; write $x=3a$, $y=3b$.',
                    r'Substituting, $9a^{2}+9b^{2}=3z^{2}$, i.e. $3\left(a^{2}+b^{2}\right)=z^{2}$.',
                    r'So $3\mid z^{2}$ and $3\mid z$; write $z=3c$ and cancel: $a^{2}+b^{2}=3c^{2}$.',
                    r'This is a solution with $c=\tfrac z3<z$ — contradicting minimality ✗']},
   'ans': {'ru': r'Решений нет.', 'en': r'There are no solutions.'}},
 ],
}
