# -*- coding: utf-8 -*-
"""Topic 13 — deeper theory, woven into lesson_13.py by content/build.py."""

FORMAL = {
 'h': {'ru': 'Размещения, перестановки, сочетания: строгие формулы',
       'en': 'Arrangements, permutations, combinations: the formulas proved'},
 'blocks': [
  {'t': 'def',
   'name': {'ru': 'Три вопроса, три формулы', 'en': 'Three questions, three formulas'},
   'text': {'ru': r'Выбирая $k$ объектов из $n$ различных, надо ответить на два вопроса: **важен ли порядок** и **допускаются ли повторения**. Четыре ответа дают четыре формулы.',
            'en': r'When choosing $k$ objects out of $n$ distinct ones, two questions decide everything: **does order matter** and **are repetitions allowed**. Four answers give four formulas.'}},
  {'t': 'table',
   'head': {'ru': ['', 'Порядок важен', 'Порядок не важен'],
            'en': ['', 'Order matters', 'Order does not matter']},
   'rows': {'ru': [['без повторений', r'$A_n^{k}=\dfrac{n!}{\left(n-k\right)!}$', r'$C_n^{k}=\dfrac{n!}{k!\left(n-k\right)!}$'],
                   ['с повторениями', r'$n^{k}$', r'$C_{n+k-1}^{k}$']],
            'en': [['no repetition', r'$A_n^{k}=\dfrac{n!}{\left(n-k\right)!}$', r'$C_n^{k}=\dfrac{n!}{k!\left(n-k\right)!}$'],
                   ['repetition allowed', r'$n^{k}$', r'$C_{n+k-1}^{k}$']]}},

  {'t': 'thm',
   'name': {'ru': 'Число размещений', 'en': 'The number of arrangements'},
   'text': {'ru': r'Число способов выбрать $k$ объектов из $n$ различных **с учётом порядка и без повторений** равно $$A_n^{k}=n\left(n-1\right)\left(n-2\right)\cdots\left(n-k+1\right)=\frac{n!}{\left(n-k\right)!}.$$ В частности, число всех перестановок $n$ объектов равно $P_n=A_n^{n}=n!$.',
            'en': r'The number of ways to choose $k$ objects out of $n$ distinct ones **with order and without repetition** is $$A_n^{k}=n\left(n-1\right)\cdots\left(n-k+1\right)=\frac{n!}{\left(n-k\right)!}.$$ In particular the number of permutations of $n$ objects is $P_n=A_n^{n}=n!$.'}},
  {'t': 'proof',
   'text': {'ru': r'Заполняем $k$ позиций слева направо. На первую позицию есть $n$ кандидатов. Какой бы объект мы ни выбрали, на вторую позицию остаётся ровно $n-1$ кандидат — **число вариантов не зависит от сделанного выбора**, а это в точности условие применимости правила произведения.\n\nПродолжая, на $k$-ю позицию остаётся $n-k+1$ кандидат. По правилу произведения общее число способов равно $$n\left(n-1\right)\cdots\left(n-k+1\right) \quad\checkmark$$\n\nДомножив и разделив на $\left(n-k\right)!$, получаем компактную запись через факториалы ✓ $\blacksquare$',
            'en': r'Fill the $k$ positions from left to right. The first position has $n$ candidates. Whichever object we take, the second has exactly $n-1$ candidates — **the count does not depend on the earlier choice**, which is precisely what the product rule requires.\n\nContinuing, the $k$-th position has $n-k+1$ candidates. The product rule gives $$n\left(n-1\right)\cdots\left(n-k+1\right) \quad\checkmark$$\n\nMultiplying and dividing by $\left(n-k\right)!$ gives the compact factorial form ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Число сочетаний', 'en': 'The number of combinations'},
   'text': {'ru': r'Число способов выбрать $k$ объектов из $n$ **без учёта порядка и без повторений** равно $$C_n^{k}=\binom{n}{k}=\frac{n!}{k!\left(n-k\right)!}.$$',
            'en': r'The number of ways to choose $k$ objects out of $n$ **without order and without repetition** is $$C_n^{k}=\binom{n}{k}=\frac{n!}{k!\left(n-k\right)!}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Применим **правило деления**: посчитаем одно и то же двумя способами.\n\nКаждое размещение $k$ объектов получается в два шага: сначала выбирается сам набор из $k$ объектов ($C_n^{k}$ способов), затем этот набор упорядочивается ($k!$ способов). По правилу произведения $$A_n^{k}=C_n^{k}\cdot k! .$$\n\nВажно, что второй множитель $k!$ **один и тот же** для любого набора — только поэтому правило произведения применимо.\n\nОтсюда $$C_n^{k}=\frac{A_n^{k}}{k!}=\frac{n!}{k!\left(n-k\right)!} \quad\checkmark\qquad\blacksquare$$',
            'en': r'Use the **division rule**: count the same thing twice.\n\nEvery arrangement of $k$ objects arises in two steps: first choose the set of $k$ objects ($C_n^{k}$ ways), then order it ($k!$ ways). The product rule gives $$A_n^{k}=C_n^{k}\cdot k! .$$\n\nWhat matters is that the second factor $k!$ is **the same** for every set — only then does the product rule apply.\n\nHence $$C_n^{k}=\frac{A_n^{k}}{k!}=\frac{n!}{k!\left(n-k\right)!} \quad\checkmark\qquad\blacksquare$$'}},

  {'t': 'thm',
   'name': {'ru': 'Перестановки с повторениями', 'en': 'Permutations with repetition'},
   'text': {'ru': r'Число различных «слов», которые можно составить из $n$ букв, среди которых первая буква повторяется $k_1$ раз, вторая $k_2$ раз, …, $m$-я $k_m$ раз (и $k_1+\dots+k_m=n$), равно $$\frac{n!}{k_1!\,k_2!\cdots k_m!}.$$',
            'en': r'The number of distinct "words" formed from $n$ letters in which the first letter repeats $k_1$ times, the second $k_2$ times, …, the $m$-th $k_m$ times (with $k_1+\dots+k_m=n$) is $$\frac{n!}{k_1!\,k_2!\cdots k_m!}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Сделаем одинаковые буквы различными, пометив их номерами. Тогда всех перестановок ровно $n!$.\n\nТеперь сотрём пометки. Каждое «настоящее» слово получилось из ровно $$k_1!\,k_2!\cdots k_m!$$ помеченных — переставлять одинаковые буквы между собой можно как угодно, слово от этого не меняется. Число повторений одно и то же для каждого слова, поэтому применимо правило деления ✓ $\blacksquare$\n\n**Другой взгляд.** Выберем позиции для первой буквы ($C_n^{k_1}$ способов), затем из оставшихся — позиции для второй ($C_{n-k_1}^{k_2}$) и так далее. Произведение всех этих биномиальных коэффициентов после сокращения даёт ту же формулу.',
            'en': r'Make the identical letters distinguishable by labelling them. Then there are exactly $n!$ permutations.\n\nNow erase the labels. Each genuine word arose from exactly $$k_1!\,k_2!\cdots k_m!$$ labelled ones — the identical letters may be permuted among themselves without changing the word. The overcount is the same for every word, so the division rule applies ✓ $\blacksquare$\n\n**Another view.** Choose the positions of the first letter ($C_n^{k_1}$ ways), then from the rest the positions of the second ($C_{n-k_1}^{k_2}$), and so on. The product of these binomial coefficients telescopes to the same formula.'}},
  {'t': 'ex',
   'q': {'ru': r'Сколько различных слов можно получить перестановкой букв слова «МАТЕМАТИКА»?',
         'en': r'How many distinct words can be made by permuting the letters of MATHEMATICS?'},
   'steps': {'ru': [r'Всего $10$ букв: М — $2$, А — $3$, Т — $2$, Е — $1$, И — $1$, К — $1$.',
                    r'По формуле $$\frac{10!}{2!\cdot3!\cdot2!\cdot1!\cdot1!\cdot1!}=\frac{3\,628\,800}{2\cdot6\cdot2}=\frac{3\,628\,800}{24}=151\,200 .$$',
                    r'Проверка порядка величины: без повторений было бы $10!=3\,628\,800$, а повторения уменьшили ответ ровно в $24$ раза ✓'],
             'en': [r'There are $11$ letters: M — $2$, A — $2$, T — $2$, H, E, I, C, S — one each.',
                    r'The formula gives $$\frac{11!}{2!\cdot2!\cdot2!}=\frac{39\,916\,800}{8}=4\,989\,600 .$$',
                    r'A sanity check: without repetitions there would be $11!=39\,916\,800$, and the repetitions cut this by exactly a factor of $8$ ✓']},
   'ans': {'ru': r'$151\,200$ слов.', 'en': r'$4\,989\,600$ words.'}},

  {'t': 'warn',
   'text': {'ru': r'Самая частая ошибка — считать порядок там, где его нет, или наоборот. Проверочный вопрос: **«меняется ли результат, если поменять местами два выбранных объекта?»** Если да — это размещение, если нет — сочетание. «Выбрать команду из трёх человек» — сочетание; «выбрать капитана, вратаря и нападающего» — размещение.',
            'en': r'The commonest error is counting order where there is none, or the reverse. The test question: **"does swapping two chosen objects change the outcome?"** If yes it is an arrangement, if no a combination. "Pick a team of three" is a combination; "pick a captain, a keeper and a striker" is an arrangement.'}},
 ],
}

BINOMIAL = {
 'h': {'ru': 'Тождества с биномиальными коэффициентами',
       'en': 'Identities for binomial coefficients'},
 'blocks': [
  {'t': 'p',
   'text': {'ru': r'Биномиальные коэффициенты связаны десятками тождеств. Ниже — те, что действительно нужны, и главное — **метод**, которым все они доказываются: посчитать одно и то же множество двумя способами.',
            'en': r'Binomial coefficients satisfy dozens of identities. Below are the ones that actually matter, and more importantly the **method** that proves them all: count one set in two ways.'}},

  {'t': 'thm',
   'name': {'ru': 'Основные тождества', 'en': 'The basic identities'},
   'text': {'ru': r'$$\binom{n}{k}=\binom{n}{n-k},\qquad \binom{n}{k}=\binom{n-1}{k-1}+\binom{n-1}{k},$$ $$\sum_{k=0}^{n}\binom{n}{k}=2^{n},\qquad \sum_{k=0}^{n}\left(-1\right)^{k}\binom{n}{k}=0\ \ \left(n\ge1\right),$$ $$k\binom{n}{k}=n\binom{n-1}{k-1},\qquad \sum_{k=0}^{n}\binom{n}{k}^{2}=\binom{2n}{n}.$$',
            'en': r'$$\binom{n}{k}=\binom{n}{n-k},\qquad \binom{n}{k}=\binom{n-1}{k-1}+\binom{n-1}{k},$$ $$\sum_{k=0}^{n}\binom{n}{k}=2^{n},\qquad \sum_{k=0}^{n}\left(-1\right)^{k}\binom{n}{k}=0\ \ \left(n\ge1\right),$$ $$k\binom{n}{k}=n\binom{n-1}{k-1},\qquad \sum_{k=0}^{n}\binom{n}{k}^{2}=\binom{2n}{n}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Каждое тождество доказывается **двойным подсчётом**.\n\n**Симметрия.** Выбрать $k$ объектов — то же самое, что указать, какие $n-k$ объектов останутся. Соответствие взаимно однозначное ✓\n\n**Правило Паскаля.** Выделим один объект, скажем последний. Наборы из $k$ объектов делятся на два непересекающихся класса: содержащие его (нужно добрать $k-1$ из оставшихся $n-1$) и не содержащие ($k$ из $n-1$). По правилу суммы ✓\n\n**Сумма равна $2^{n}$.** Слева — число всех подмножеств $n$-элементного множества, разбитых по размеру; справа — то же число, посчитанное по правилу произведения: каждый из $n$ объектов независимо либо входит в подмножество, либо нет ✓\n\n**Знакопеременная сумма.** Она утверждает, что подмножеств чётного размера столько же, сколько нечётного. Построим биекцию: зафиксируем объект $x$ и сопоставим каждому подмножеству то, которое получается добавлением или удалением $x$. Это соответствие меняет чётность размера и обратно самому себе, значит оно взаимно однозначно ✓\n\n**Тождество $k\binom{n}{k}=n\binom{n-1}{k-1}$.** Обе части считают число способов выбрать из $n$ человек комитет из $k$ человек и назначить в нём председателя: слева сначала комитет, потом председатель; справа сначала председатель из всех $n$, потом остальные $k-1$ членов ✓\n\n**Тождество Вандермонда $\sum\binom{n}{k}^{2}=\binom{2n}{n}$.** Разделим $2n$ объектов на две группы по $n$. Выбирая $n$ объектов всего, мы берём $k$ из первой группы и $n-k$ из второй; число способов равно $\binom{n}{k}\binom{n}{n-k}=\binom{n}{k}^{2}$. Суммируя по $k$ и пользуясь правилом суммы, получаем $\binom{2n}{n}$ ✓ $\blacksquare$',
            'en': r'Every identity here is proved by **double counting**.\n\n**Symmetry.** Choosing $k$ objects is the same as naming the $n-k$ left behind; the correspondence is a bijection ✓\n\n**The rule of Pascal.** Single out one object, say the last. The $k$-subsets split into two disjoint classes: those containing it (choose $k-1$ from the other $n-1$) and those not (choose $k$ from $n-1$). Apply the sum rule ✓\n\n**The sum is $2^{n}$.** The left side counts all subsets of an $n$-set, grouped by size; the right counts the same by the product rule: each of the $n$ objects independently is in or out ✓\n\n**The alternating sum.** It says there are as many even subsets as odd ones. Build a bijection: fix an object $x$ and send each subset to the one obtained by adding or removing $x$. This flips the parity of the size and is its own inverse, hence a bijection ✓\n\n**The identity $k\binom{n}{k}=n\binom{n-1}{k-1}$.** Both sides count the ways to pick a committee of $k$ from $n$ people and name its chair: on the left the committee first, then the chair; on the right the chair from all $n$ first, then the remaining $k-1$ members ✓\n\n**The identity of Vandermonde $\sum\binom{n}{k}^{2}=\binom{2n}{n}$.** Split $2n$ objects into two groups of $n$. Choosing $n$ objects means taking $k$ from the first group and $n-k$ from the second, in $\binom{n}{k}\binom{n}{n-k}=\binom{n}{k}^{2}$ ways. Summing over $k$ by the sum rule gives $\binom{2n}{n}$ ✓ $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Тождество «хоккейной клюшки»', 'en': 'The hockey stick identity'},
   'text': {'ru': r'$$\binom{r}{r}+\binom{r+1}{r}+\binom{r+2}{r}+\dots+\binom{n}{r}=\binom{n+1}{r+1}.$$',
            'en': r'$$\binom{r}{r}+\binom{r+1}{r}+\binom{r+2}{r}+\dots+\binom{n}{r}=\binom{n+1}{r+1}.$$'}},
  {'t': 'proof',
   'text': {'ru': r'Посчитаем двумя способами число подмножеств размера $r+1$ множества $\left\{1,2,\dots,n+1\right\}$.\n\nСправа стоит ответ по определению: $\binom{n+1}{r+1}$.\n\nСлева разобьём эти подмножества по **наибольшему** элементу. Если наибольший элемент равен $m+1$, то остальные $r$ элементов выбираются из $\left\{1,\dots,m\right\}$, что можно сделать $\binom{m}{r}$ способами. Значение $m$ пробегает от $r$ до $n$ (меньше $r$ невозможно). По правилу суммы получаем левую часть ✓ $\blacksquare$\n\nНазвание объясняется видом этих клеток в треугольнике Паскаля: диагональ и одна клетка сбоку от неё образуют клюшку.',
            'en': r'Count in two ways the $\left(r+1\right)$-subsets of $\left\{1,2,\dots,n+1\right\}$.\n\nOn the right that is the definition: $\binom{n+1}{r+1}$.\n\nOn the left, sort those subsets by their **largest** element. If the largest is $m+1$, the other $r$ elements come from $\left\{1,\dots,m\right\}$, giving $\binom{m}{r}$ choices, and $m$ runs from $r$ to $n$ (anything smaller is impossible). The sum rule gives the left side ✓ $\blacksquare$\n\nThe name comes from the shape of those cells in the triangle of Pascal: a diagonal plus one cell beside it looks like a hockey stick.'}},
  {'t': 'ex',
   'q': {'ru': r'Вычислите $1+2+3+\dots+n$ и $1\cdot2+2\cdot3+\dots+\left(n-1\right)n$ с помощью тождества хоккейной клюшки.',
         'en': r'Use the hockey stick identity to evaluate $1+2+\dots+n$ and $1\cdot2+2\cdot3+\dots+\left(n-1\right)n$.'},
   'steps': {'ru': [r'Заметим, что $k=\binom{k}{1}$. Значит $$1+2+\dots+n=\sum_{k=1}^{n}\binom{k}{1}=\binom{n+1}{2}=\frac{n\left(n+1\right)}{2} \quad\checkmark$$',
                    r'Далее $\left(k-1\right)k=2\binom{k}{2}$, поэтому $$\sum_{k=2}^{n}\left(k-1\right)k=2\sum_{k=2}^{n}\binom{k}{2}=2\binom{n+1}{3}=\frac{\left(n-1\right)n\left(n+1\right)}{3} .$$',
                    r'Проверка при $n=3$: $1\cdot2+2\cdot3=8$, а формула даёт $\dfrac{2\cdot3\cdot4}{3}=8$ ✓',
                    r'Тот же приём даёт и $\sum k^{2}$: достаточно записать $k^{2}=2\binom{k}{2}+\binom{k}{1}$.'],
             'en': [r'Note $k=\binom{k}{1}$, so $$1+2+\dots+n=\sum_{k=1}^{n}\binom{k}{1}=\binom{n+1}{2}=\frac{n\left(n+1\right)}{2} \quad\checkmark$$',
                    r'Next $\left(k-1\right)k=2\binom{k}{2}$, hence $$\sum_{k=2}^{n}\left(k-1\right)k=2\binom{n+1}{3}=\frac{\left(n-1\right)n\left(n+1\right)}{3} .$$',
                    r'Check at $n=3$: $1\cdot2+2\cdot3=8$ and the formula gives $\dfrac{2\cdot3\cdot4}{3}=8$ ✓',
                    r'The same trick gives $\sum k^{2}$: just write $k^{2}=2\binom{k}{2}+\binom{k}{1}$.']},
   'ans': {'ru': r'$\dfrac{n\left(n+1\right)}{2}$ и $\dfrac{\left(n-1\right)n\left(n+1\right)}{3}$.',
           'en': r'$\dfrac{n\left(n+1\right)}{2}$ and $\dfrac{\left(n-1\right)n\left(n+1\right)}{3}$.'}},

  {'t': 'idea',
   'text': {'ru': r'**Как доказывать комбинаторные тождества.** Есть три пути.\n\n1. **Двойной подсчёт**: придумать множество, которое обе части считают по-разному. Самый красивый и самый надёжный способ.\n2. **Биекция**: построить взаимно однозначное соответствие между двумя множествами.\n3. **Алгебра**: расписать факториалы или сравнить коэффициенты в подходящем произведении многочленов.\n\nЕсли тождество выглядит так, будто оно «должно что-то означать», ищите первый путь.',
            'en': r'**How to prove a combinatorial identity.** There are three routes.\n\n1. **Double counting**: invent a set that both sides count differently. The prettiest and the most reliable.\n2. **Bijection**: build a one-to-one correspondence between two sets.\n3. **Algebra**: expand the factorials, or compare coefficients in a suitable product of polynomials.\n\nIf an identity looks as though it ought to *mean* something, look for the first route.'}},
 ],
}

ADVANCED = {
 'h': {'ru': 'Биекции, двойной подсчёт и рекуррентные схемы',
       'en': 'Bijections, double counting and recursive schemes'},
 'blocks': [
  {'t': 'thm',
   'name': {'ru': 'Принцип биекции', 'en': 'The bijection principle'},
   'text': {'ru': r'Если между конечными множествами $X$ и $Y$ существует взаимно однозначное соответствие, то $\left|X\right|=\left|Y\right|$. Поэтому трудную задачу подсчёта можно заменить лёгкой, если построить между ними биекцию.',
            'en': r'If there is a one-to-one correspondence between finite sets $X$ and $Y$ then $\left|X\right|=\left|Y\right|$. So a hard counting problem may be replaced by an easy one whenever a bijection between them is built.'}},
  {'t': 'proof',
   'text': {'ru': r'**Пример: вывод формулы «шаров и перегородок» биекцией.** Требуется найти число способов раздать $k$ одинаковых конфет $n$ детям (кому-то может не достаться).\n\nЗакодируем раздачу строкой из $k$ звёздочек и $n-1$ палочек: звёздочки — конфеты, палочки — границы между детьми. Например, при $n=3$, $k=4$ строка $\star\star\mid\ \mid\star\star$ означает «двое первому, ноль второму, двое третьему».\n\nСоответствие «раздача ↔ строка» взаимно однозначно: по строке раздача восстанавливается однозначно, и наоборот ✓\n\nОстаётся посчитать строки. Всего позиций $k+\left(n-1\right)$, и надо выбрать, какие $k$ из них займут звёздочки: $$\binom{n+k-1}{k} \quad\checkmark\qquad\blacksquare$$\n\nТрудная задача превратилась в стандартное сочетание — в этом и состоит сила биекций.',
            'en': r'**An example: stars and bars by a bijection.** We want the number of ways to hand $k$ identical sweets to $n$ children (some may get none).\n\nEncode a distribution as a string of $k$ stars and $n-1$ bars: stars are sweets, bars separate the children. For $n=3$, $k=4$ the string $\star\star\mid\ \mid\star\star$ means "two to the first, none to the second, two to the third".\n\nThe correspondence between distributions and strings is one-to-one: each string reconstructs its distribution and vice versa ✓\n\nIt remains to count strings. There are $k+\left(n-1\right)$ positions and we choose which $k$ hold stars: $$\binom{n+k-1}{k} \quad\checkmark\qquad\blacksquare$$\n\nA hard problem became a standard combination — that is the power of bijections.'}},

  {'t': 'thm',
   'name': {'ru': 'Формула включений и исключений',
            'en': 'The inclusion–exclusion formula'},
   'text': {'ru': r'Для конечных множеств $A_1,\dots,A_n$ $$\left|A_1\cup\dots\cup A_n\right|=\sum_i\left|A_i\right|-\sum_{i<j}\left|A_i\cap A_j\right|+\sum_{i<j<k}\left|A_i\cap A_j\cap A_k\right|-\dots+\left(-1\right)^{\,n-1}\left|A_1\cap\dots\cap A_n\right| .$$',
            'en': r'For finite sets $A_1,\dots,A_n$ $$\left|A_1\cup\dots\cup A_n\right|=\sum_i\left|A_i\right|-\sum_{i<j}\left|A_i\cap A_j\right|+\sum_{i<j<k}\left|A_i\cap A_j\cap A_k\right|-\dots+\left(-1\right)^{\,n-1}\left|A_1\cap\dots\cap A_n\right| .$$'}},
  {'t': 'proof',
   'text': {'ru': r'Проверим, что **каждый элемент** объединения посчитан справа ровно один раз.\n\nПусть элемент $x$ принадлежит ровно $m\ge1$ из множеств $A_i$. Тогда в сумме одиночных слагаемых он учтён $\binom{m}{1}$ раз, в сумме попарных пересечений — $\binom{m}{2}$ раз, и вообще в сумме $j$-кратных пересечений — $\binom{m}{j}$ раз.\n\nЗначит его суммарный вклад в правую часть равен $$\binom{m}{1}-\binom{m}{2}+\binom{m}{3}-\dots+\left(-1\right)^{\,m-1}\binom{m}{m}.$$\n\nПо знакопеременному тождеству $\sum_{j=0}^{m}\left(-1\right)^{j}\binom{m}{j}=0$, откуда $$\sum_{j=1}^{m}\left(-1\right)^{\,j-1}\binom{m}{j}=\binom{m}{0}=1 .$$\n\nИтак вклад равен $1$ — ровно столько, сколько нужно ✓ Элементы вне объединения не входят ни в одно слагаемое $\blacksquare$',
            'en': r'Check that **every element** of the union is counted exactly once on the right.\n\nSuppose $x$ lies in exactly $m\ge1$ of the sets. Then it is counted $\binom{m}{1}$ times among the single terms, $\binom{m}{2}$ times among the pairwise intersections, and generally $\binom{m}{j}$ times among the $j$-fold intersections.\n\nSo its total contribution to the right side is $$\binom{m}{1}-\binom{m}{2}+\dots+\left(-1\right)^{\,m-1}\binom{m}{m}.$$\n\nThe alternating identity $\sum_{j=0}^{m}\left(-1\right)^{j}\binom{m}{j}=0$ turns this into $$\sum_{j=1}^{m}\left(-1\right)^{\,j-1}\binom{m}{j}=\binom{m}{0}=1 .$$\n\nThe contribution is $1$ — exactly right ✓ Elements outside the union appear in no term at all $\blacksquare$'}},

  {'t': 'thm',
   'name': {'ru': 'Число беспорядков', 'en': 'The number of derangements'},
   'text': {'ru': r'Число перестановок $n$ объектов, при которых ни один объект не остаётся на своём месте, равно $$D_n=n!\left(1-\frac1{1!}+\frac1{2!}-\frac1{3!}+\dots+\frac{\left(-1\right)^{n}}{n!}\right).$$ При больших $n$ доля таких перестановок стремится к $\dfrac1e\approx0{,}368$.',
            'en': r'The number of permutations of $n$ objects leaving no object in its own place is $$D_n=n!\left(1-\frac1{1!}+\frac1{2!}-\frac1{3!}+\dots+\frac{\left(-1\right)^{n}}{n!}\right).$$ For large $n$ the proportion of such permutations tends to $\dfrac1e\approx0.368$.'}},
  {'t': 'proof',
   'text': {'ru': r'Пусть $A_i$ — множество перестановок, оставляющих объект $i$ на месте. Нас интересует число перестановок вне объединения всех $A_i$, то есть $$D_n=n!-\left|A_1\cup\dots\cup A_n\right| .$$\n\nПересечение любых $j$ множеств $A_i$ состоит из перестановок, фиксирующих $j$ выбранных объектов; остальные $n-j$ переставляются как угодно, значит его размер равен $\left(n-j\right)!$. Таких пересечений $\binom{n}{j}$.\n\nПо формуле включений и исключений $$\left|A_1\cup\dots\cup A_n\right|=\sum_{j=1}^{n}\left(-1\right)^{\,j-1}\binom{n}{j}\left(n-j\right)! .$$\n\nПодставим и перенесём знак: $$D_n=\sum_{j=0}^{n}\left(-1\right)^{j}\binom{n}{j}\left(n-j\right)! =\sum_{j=0}^{n}\left(-1\right)^{j}\frac{n!}{j!} ,$$ поскольку $\binom{n}{j}\left(n-j\right)!=\dfrac{n!}{j!}$. Вынеся $n!$, получаем требуемое ✓ $\blacksquare$\n\nСкобка — начальный отрезок ряда для $e^{-1}$, отсюда и предел.',
            'en': r'Let $A_i$ be the set of permutations fixing the object $i$. We want the permutations outside the union: $$D_n=n!-\left|A_1\cup\dots\cup A_n\right| .$$\n\nThe intersection of any $j$ of the $A_i$ consists of the permutations fixing $j$ chosen objects; the other $n-j$ move freely, so its size is $\left(n-j\right)!$, and there are $\binom{n}{j}$ such intersections.\n\nInclusion–exclusion gives $$\left|A_1\cup\dots\cup A_n\right|=\sum_{j=1}^{n}\left(-1\right)^{\,j-1}\binom{n}{j}\left(n-j\right)! .$$\n\nSubstituting and absorbing the sign, $$D_n=\sum_{j=0}^{n}\left(-1\right)^{j}\binom{n}{j}\left(n-j\right)! =\sum_{j=0}^{n}\left(-1\right)^{j}\frac{n!}{j!} ,$$ since $\binom{n}{j}\left(n-j\right)!=\dfrac{n!}{j!}$. Factoring out $n!$ gives the claim ✓ $\blacksquare$\n\nThe bracket is the beginning of the series for $e^{-1}$, whence the limit.'}},
  {'t': 'ex',
   'q': {'ru': r'Пять писем разложили по пяти конвертам наугад. Сколькими способами могло оказаться, что ни одно письмо не попало в свой конверт?',
         'en': r'Five letters are put into five envelopes at random. In how many ways can it happen that no letter is in its own envelope?'},
   'steps': {'ru': [r'Это в точности $D_5$.',
                    r'$$D_5=5!\left(1-1+\frac12-\frac16+\frac1{24}-\frac1{120}\right)=120\cdot\frac{44}{120}=44 .$$',
                    r'Полезно знать первые значения: $D_1=0$, $D_2=1$, $D_3=2$, $D_4=9$, $D_5=44$.',
                    r'Вероятность такого события равна $\dfrac{44}{120}\approx0{,}367$ — уже почти $\dfrac1e$ ✓'],
             'en': [r'This is exactly $D_5$.',
                    r'$$D_5=5!\left(1-1+\frac12-\frac16+\frac1{24}-\frac1{120}\right)=120\cdot\frac{44}{120}=44 .$$',
                    r'The first values are worth knowing: $D_1=0$, $D_2=1$, $D_3=2$, $D_4=9$, $D_5=44$.',
                    r'The probability of this event is $\dfrac{44}{120}\approx0.367$ — already almost $\dfrac1e$ ✓']},
   'ans': {'ru': r'$44$ способа.', 'en': r'$44$ ways.'}},

  {'t': 'thm',
   'name': {'ru': 'Числа Каталана', 'en': 'The Catalan numbers'},
   'text': {'ru': r'Число правильных скобочных последовательностей из $n$ пар скобок равно $$C_n=\frac1{n+1}\binom{2n}{n}.$$ Эти же числа считают: количество способов разбить выпуклый $\left(n+2\right)$-угольник диагоналями на треугольники, количество двоичных деревьев с $n$ вершинами, количество путей из $\left(0,0\right)$ в $\left(n,n\right)$ шагами вправо и вверх, не поднимающихся выше диагонали.',
            'en': r'The number of balanced strings of $n$ pairs of brackets is $$C_n=\frac1{n+1}\binom{2n}{n}.$$ The same numbers count: the triangulations of a convex $\left(n+2\right)$-gon by diagonals, the binary trees on $n$ nodes, and the lattice paths from $\left(0,0\right)$ to $\left(n,n\right)$ by unit right and up steps that never rise above the diagonal.'}},
  {'t': 'proof',
   'text': {'ru': r'Воспользуемся **принципом отражения**.\n\nЗакодируем скобочную последовательность путём: открывающая скобка — шаг вправо, закрывающая — шаг вверх. Всего путей из $\left(0,0\right)$ в $\left(n,n\right)$ ровно $\binom{2n}{n}$: надо выбрать, какие $n$ из $2n$ шагов идут вправо.\n\nПоследовательность **неправильна**, если в какой-то момент закрывающих скобок стало больше, чем открывающих, то есть путь пересёк диагональ и коснулся прямой $y=x+1$.\n\nВозьмём первый такой момент и **отразим** относительно прямой $y=x+1$ весь остаток пути. Конец $\left(n,n\right)$ перейдёт в точку $\left(n-1,n+1\right)$. Это соответствие обратимо: отразив обратно от первого касания, восстанавливаем исходный путь. Значит неправильных путей ровно столько, сколько всех путей в $\left(n-1,n+1\right)$, то есть $\binom{2n}{n-1}$.\n\nОтсюда $$C_n=\binom{2n}{n}-\binom{2n}{n-1}=\binom{2n}{n}\left(1-\frac{n}{n+1}\right)=\frac1{n+1}\binom{2n}{n} \quad\checkmark\qquad\blacksquare$$\n\n(Использовано $\binom{2n}{n-1}=\dfrac{n}{n+1}\binom{2n}{n}$, что проверяется прямо по формуле факториалов.)',
            'en': r'Use the **reflection principle**.\n\nEncode a bracket string as a path: an opening bracket is a step right, a closing one a step up. There are exactly $\binom{2n}{n}$ paths from $\left(0,0\right)$ to $\left(n,n\right)$: choose which $n$ of the $2n$ steps go right.\n\nA string is **unbalanced** if at some moment the closing brackets outnumber the opening ones, i.e. the path crosses the diagonal and touches the line $y=x+1$.\n\nTake the first such moment and **reflect** the rest of the path in the line $y=x+1$. The endpoint $\left(n,n\right)$ becomes $\left(n-1,n+1\right)$. The map is reversible: reflecting back from the first touch restores the original path. So the bad paths are exactly as many as all paths to $\left(n-1,n+1\right)$, namely $\binom{2n}{n-1}$.\n\nHence $$C_n=\binom{2n}{n}-\binom{2n}{n-1}=\binom{2n}{n}\left(1-\frac{n}{n+1}\right)=\frac1{n+1}\binom{2n}{n} \quad\checkmark\qquad\blacksquare$$\n\n(We used $\binom{2n}{n-1}=\dfrac{n}{n+1}\binom{2n}{n}$, immediate from the factorial formula.)'}},
  {'t': 'note',
   'text': {'ru': r'Первые числа Каталана: $1,1,2,5,14,42,132,429,1430,4862$. Если в олимпиадной задаче ответ на маленьких случаях выглядит как $1,2,5,14$ — почти наверняка перед вами числа Каталана, и стоит искать биекцию со скобочными последовательностями.',
            'en': r'The first Catalan numbers are $1,1,2,5,14,42,132,429,1430,4862$. If the small cases of an olympiad problem come out as $1,2,5,14$, you are almost certainly looking at Catalan numbers — go and find the bijection with bracket strings.'}},
 ],
}

SECTIONS = [(1, FORMAL), (3, BINOMIAL), (5, ADVANCED)]

INTO = {
 0: [
  {'t': 'warn',
   'text': {'ru': r'**Когда правило произведения не работает.** Оно требует, чтобы число вариантов на каждом шаге **не зависело** от того, что выбрано раньше. Классическая ловушка: «сколько двузначных чисел с различными цифрами?» — на первое место $9$ вариантов (не $0$), на второе тоже $9$ (любая из десяти, кроме уже использованной). Здесь число вариантов на втором шаге одно и то же ($9$) при любом первом выборе, поэтому правило применимо и ответ $81$.\n\nА вот в задаче «сколько двузначных чисел, у которых вторая цифра больше первой?» число вариантов на втором шаге **зависит** от первого выбора, и перемножать нельзя — надо суммировать.',
            'en': r'**When the product rule fails.** It requires the number of options at each step to be **independent** of the earlier choices. The classic trap: "how many two-digit numbers have distinct digits?" — nine options for the first place (not $0$) and nine for the second (any of ten except the one used). The second count is the same ($9$) whatever the first choice was, so the rule applies and the answer is $81$.\n\nBut in "how many two-digit numbers have the second digit larger than the first?" the number of options at the second step **depends** on the first, so multiplication is wrong — one must sum.'}},
  {'t': 'thm',
   'name': {'ru': 'Правило деления', 'en': 'The division rule'},
   'text': {'ru': r'Если каждый объект множества $Y$ получается ровно из $d$ объектов множества $X$ при некотором отображении $X\to Y$, то $$\left|Y\right|=\frac{\left|X\right|}{d}.$$',
            'en': r'If under some map $X\to Y$ every object of $Y$ comes from exactly $d$ objects of $X$, then $$\left|Y\right|=\frac{\left|X\right|}{d}.$$'}},
  {'t': 'idea',
   'text': {'ru': r'Правило деления — главный инструмент для задач «по кругу». Сколькими способами усадить $n$ человек за круглый стол, если рассадки, отличающиеся поворотом, считаются одинаковыми? Всего линейных расстановок $n!$, каждая круговая получается из ровно $n$ линейных (по числу поворотов), значит ответ $\dfrac{n!}{n}=\left(n-1\right)!$.\n\nЕсли одинаковыми считать ещё и отражения (например, для ожерелья), делим дополнительно на $2$.',
            'en': r'The division rule is the main tool for problems "around a circle". In how many ways can $n$ people sit at a round table if seatings differing by a rotation count as the same? There are $n!$ linear arrangements, each circular one comes from exactly $n$ of them (one per rotation), so the answer is $\dfrac{n!}{n}=\left(n-1\right)!$.\n\nIf reflections count as the same too (a necklace, say), divide by a further $2$.'}},
 ],
}
