# -*- coding: utf-8 -*-
"""Uzbek for topic 4.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Diofant tenglamalari',
 'sub':             'Javobi butun son boʻlishi shart tenglamalar: chiziqli hol, koʻpaytuvchilarga ajratish, baholash, qoldiqlar va cheksiz tushish.',
 'goals.0':         '$ax+by=c$ chiziqli tenglamasini butun sonlarda yechish va barcha yechimlarni yozish.',
 'goals.1':         'Tenglamani «koʻpaytma songa teng» koʻrinishiga keltirish va boʻluvchilarni saralash.',
 'goals.2':         'Oʻzgaruvchilarni shunday baholash kerakki, faqat chekli sondagi hol qolsin.',
 'goals.3':         'Qoldiqlar va cheksiz tushish usuli bilan yechim yoʻqligini isbotlash.',
 's0.h':            'Bu tenglamalar nima',
 's1.h':            '$ax+by=c$ chiziqli tenglamasi',
 's2.h':            'Koʻpaytuvchilarga ajratish',
 's3.h':            'Baholash: oʻzgaruvchilarni qamab qoʻyish',
 's4.h':            'Qoldiqlar elak sifatida',
 's5.h':            'Pifagor uchliklari',
 's6.h':            'Ikkita kvadrat yigʻindisi',
 's7.h':            'Pell tenglamasi',
 's8.h':            'Cheksiz tushish',
 's0.b0.text':      'Algebra darsida $2x+3y=12$ tenglamasining cheksiz koʻp yechimi bor: istalgan $x$ ni olib, $y$ ni topasiz. Ammo $x$ va $y$ dan **butun son** boʻlish talab qilinsa, masala butunlay boshqacha — va ancha qiziqarli — boʻlib qoladi. Aynan shunday masalalar olimpiada sonlar nazariyasining yarmini tashkil qiladi.',
 's0.b1.name':      'Diofant tenglamasi',
 's0.b1.text':      '**Diofant** tenglamasi (yoki sistemasi) — bu butun koeffitsiyentli, yechimlari **butun sonlar** orasidan, baʼzan esa musbat butun sonlar orasidan qidiriladigan tenglama. Tenglamaning oʻzi istalgan koʻrinishda boʻlishi mumkin; uni Diofant tenglamasi qiladigan narsa — javobga qoʻyilgan talab.',
 's0.b2.text':      'Nom uchinchi asrda yashagan Aleksandriyalik Diofant sharafiga qoʻyilgan. Uning «Arifmetika» asari bunday masalalarni tizimli koʻrib chiqqan birinchi kitob. Aynan oʻsha kitobning chekkasiga Ferma $x^n+y^n=z^n$ haqidagi mashhur qaydini yozgan.',
 's0.b3.text':      'Olimpiada masalasi uchta narsadan birini soʻraydi: **yechim bormi**, **nechta**, yoki **hammasini toping**. Uchinchisi eng talabchan: ball faqat yechimlarni koʻrsatib, boshqasi yoʻqligini ham isbotlasangiz beriladi.',
 's0.b4.text':      'Butun arsenal beshta usulga keladi va deyarli har bir masala ulardan biriga tushadi:\\n\\n**1)** chiziqli tenglama — EKUB nazariyasidan foydalaning;\\n**2)** koʻpaytuvchilarga ajrating va boʻluvchilarni saralang;\\n**3)** oʻzgaruvchilarni yuqoridan va quyidan baholang;\\n**4)** yaxshi tanlangan son boʻyicha qoldiqlarni oling va ziddiyatga keling;\\n**5)** cheksiz tushish.\\n\\nRoʻyxatning tartibi — bu ularni sinash tartibi hamdir.',
 's1.b0.text':      'Bu — toʻliq yechilgan yagona sinf: yechiluvchanlik mezoni ham, har bir yechim uchun formula ham bor. Hammasi EKUB mavzusidagi bitta faktga tayanadi: $ax+by$ koʻrinishidagi sonlar aynan $\\gcd(a,b)$ ning karralilari.',
 's1.b1.name':      'Yechiluvchanlik mezoni',
 's1.b1.text':      '$a,b$ ikkalasi ham nol boʻlmasin va $d=\\gcd(a,b)$ boʻlsin. $ax+by=c$ tenglamasining butun yechimi boʻlishi uchun $d\\mid c$ boʻlishi **zarur va yetarli**.',
 's1.b2.text':      '**Zarurligi.** Agar $ax+by=c$ boʻlsa, $d$ soni $a$ ni ham, $b$ ni ham boʻladi, demak $ax+by=c$ ni ham.\\n\\n**Yetarliligi.** Bezuga koʻra $au+bv=d$ boʻladigan butun $u,v$ bor. $c=dk$ deb yozamiz va $k$ ga koʻpaytiramiz: $$a(uk)+b(vk)=dk=c,$$ demak $x=uk$, $y=vk$ — yechim. $\\blacksquare$',
 's1.b3.name':      'Barcha yechimlar birdaniga',
 's1.b3.text':      '$d=\\gcd(a,b)$ soni $c$ ni boʻlsin va $(x_0,y_0)$ — istalgan bitta yechim boʻlsin. U holda har bir butun yechim $$x=x_0+\\frac{b}{d}\\,t,\\qquad y=y_0-\\frac{a}{d}\\,t,\\qquad t\\in\\mathbb{Z}$$ koʻrinishida beriladi va $t$ ning turli qiymatlari turli yechim beradi.',
 's1.b4.text':      'Oʻrniga qoʻyish har bir bunday juftlik yechim ekanini koʻrsatadi: $$a\\Big(x_0+\\frac{b}{d}t\\Big)+b\\Big(y_0-\\frac{a}{d}t\\Big)=ax_0+by_0+\\frac{abt}{d}-\\frac{abt}{d}=c.$$ Aksincha, $(x,y)$ yechim boʻlsin. $ax+by=c$ dan $ax_0+by_0=c$ ni ayiramiz: $$a(x-x_0)=-b(y-y_0).$$ $d$ ga boʻlamiz va $a_1=a/d$, $b_1=b/d$ deb belgilaymiz; u holda $\\gcd(a_1,b_1)=1$ va $a_1(x-x_0)=-b_1(y-y_0)$. Demak $b_1$ soni $a_1(x-x_0)$ ni boʻladi, $b_1$ esa $a_1$ ga oʻzaro tub boʻlgani uchun $b_1\\mid x-x_0$. $x-x_0=b_1t$ deb yozamiz; oʻrniga qoʻysak $y-y_0=-a_1t$ chiqadi, bu esa oʻsha formula. $\\blacksquare$',
 's1.b5.text':      'Musobaqada Yevklid algoritmi kamdan-kam kerak boʻladi: bitta yechimni qoldiqlar yordamida topish tezroq. $ax+by=c$ dan $ax\\equiv c\\pmod{b}$ chiqadi — bitta nomaʼlumli bitta tenglama, kichik modul boʻyicha.',
 's1.b6.q':         '$7x+11y=100$ ning barcha butun yechimlarini, soʻng manfiy boʻlmagan butun yechimlarini toping.',
 's1.b6.steps.0':   '$\\gcd(7,11)=1$ va $1\\mid100$, demak yechimlar bor.',
 's1.b6.steps.1':   'Bitta yechimni modul $7$ boʻyicha topamiz: $11y\\equiv100\\pmod 7$, yaʼni $4y\\equiv2\\pmod7$. $2$ ga koʻpaytiramiz: $8y\\equiv4$, $8\\equiv1$, demak $y\\equiv4\\pmod7$.',
 's1.b6.steps.2':   '$y_0=4$ olamiz: u holda $7x=100-44=56$, demak $x_0=8$. Tekshirish: $56+44=100$ ✓',
 's1.b6.steps.3':   'Teoremaga koʻra har bir yechim $x=8+11t$, $y=4-7t$, bunda $t\\in\\mathbb{Z}$.',
 's1.b6.steps.4':   '$x\\ge0$ va $y\\ge0$ ni talab qilamiz: $8+11t\\ge0$ dan $t\\ge-\\tfrac{8}{11}$, yaʼni $t\\ge0$; $4-7t\\ge0$ dan $t\\le\\tfrac47$, yaʼni $t\\le0$.',
 's1.b6.steps.5':   'Faqat $t=0$ qoladi.',
 's1.b6.ans':       'Barcha butun yechimlar: $(8+11t,\\;4-7t)$, $t\\in\\mathbb{Z}$. Manfiy boʻlmagan butun sonlarda yechim yagona: $(8,4)$.',
 's1.b7.text':      'Javobning koʻrinishiga eʼtibor bering: butun yechimlar cheksiz koʻp, $x$ boʻyicha $11$, $y$ boʻyicha $-7$ qadam bilan joylashgan; manfiy emaslik sharti esa oʻsha progressiyadan qisqa boʻlakni kesib oladi. «Tanga va qaytim» haqidagi deyarli har bir masala aynan shunday ishlaydi.',
 's2.b0.text':      'Butun mavzuning markaziy usuli. Agar tenglamani $$(\\text{butun son})\\cdot(\\text{butun son})=N$$ koʻrinishiga keltirish mumkin boʻlsa, arifmetika ishni oʻz qoʻliga oladi: koʻpaytuvchilar $N$ ning boʻluvchilari, $N$ ning esa chekli sondagi boʻluvchisi bor. Masala chekli tekshiruvga aylanadi.',
 's2.b1.text':      'Agar tenglamada $xy$ hadi chiziqli hadlar bilan birga uchrasa, ishni **doimiy son qoʻshish** bitiradi. Yodlashga arzigulik ayniyat:',
 's2.b3.text':      'Qavslarni ochib tekshiring: $(x+b)(y+a)=xy+ax+by+ab$. Demak chap tomonni ajratish uchun tenglamaning ikkala tomoniga $ab$ qoʻshish yetarli.',
 's2.b4.q':         '$xy+2x-3y=17$ boʻladigan barcha butun sonlar juftligini toping.',
 's2.b4.steps.0':   'Bu yerda $a=2$, $b=-3$, demak $ab=-6$ va $xy+2x-3y=(x-3)(y+2)+6$.',
 's2.b4.steps.1':   'Tenglama $(x-3)(y+2)=11$ koʻrinishiga keladi.',
 's2.b4.steps.2':   '$11$ tub boʻlgani uchun koʻpaytuvchilar juftligi toʻrttadan biri: $(1,11),(11,1),(-1,-11),(-11,-1)$.',
 's2.b4.steps.5':   'Bitta juftlikni tekshiramiz: $x=14,y=-1$ da $-14+28+3=17$ ✓',
 's2.b5.text':      'Bu yerda ball yoʻqotishning eng koʻp uchraydigan yoʻli: masalada «butun sonlarda» deyilganda faqat **musbat** boʻluvchilarni saralash. $11$ sonining ikkita emas, toʻrtta boʻluvchisi bor: $\\pm1,\\pm11$. Agar masalada «musbat butun sonlarda» deyilgan boʻlsa, manfiy hollarni tashlab yuborish kerak — ammo sababini ayting.',
 's2.b6.text':      'Xuddi shu usul $\\dfrac1x+\\dfrac1y=\\dfrac1n$ koʻrinishidagi har bir kasrli tenglamani hal qiladi. Maxrajlardan qutulamiz: $n(x+y)=xy$, yaʼni $xy-nx-ny=0$. $n^2$ qoʻshamiz:',
 's2.b8.q':         '$\\dfrac1x+\\dfrac1y=\\dfrac1{12}$ ni qanoatlantiruvchi nechta musbat butun $(x,y)$ juftlik bor?',
 's2.b8.steps.0':   'Yuqoridagi formulaga koʻra $(x-12)(y-12)=144$.',
 's2.b8.steps.1':   'Agar $x\\le12$ boʻlsa, $\\tfrac1x\\ge\\tfrac1{12}$ va $\\tfrac1y>0$ uchun joy qolmaydi. Demak $x>12$ va $y>12$, yaʼni ikkala koʻpaytuvchi ham musbat.',
 's2.b8.steps.2':   '$144$ ning har bir musbat $d$ boʻluvchisi roppa-rosa bitta juftlik beradi: $x=12+d$, $y=12+\\tfrac{144}{d}$.',
 's2.b8.steps.3':   '$144=2^4\\cdot3^2$, demak boʻluvchilar soni $(4+1)(2+1)=15$.',
 's2.b8.steps.4':   'Masalan, $d=1$ da $(13,156)$, $d=12$ da esa «kvadrat» juftlik $(24,24)$ chiqadi.',
 's2.b8.ans':       '$15$ ta juftlik ($(x,y)$ va $(y,x)$ turli deb hisoblanganda).',
 's3.b0.text':      'Agar oʻzgaruvchilar simmetrik boʻlsa, tartib kiriting — masalan $x\\le y\\le z$ — va **eng kichigini** baholang. Unga bir necha qiymatgina qoladi, har biri alohida koʻriladi. Bu cheksiz saralashni chekliga aylantirishning eng ishonchli yoʻli.',
 's3.b1.q':         '$\\dfrac1x+\\dfrac1y+\\dfrac1z=1$ boʻladigan barcha musbat butun uchliklarni toping.',
 's3.b1.steps.0':   'Tenglama simmetrik, shuning uchun $x\\le y\\le z$ deb faraz qilamiz va oxirida oʻrin almashtirishlarni qoʻshamiz.',
 's3.b1.steps.1':   'U holda $\\tfrac1x$ — uchala kasrning eng kattasi, demak $1=\\tfrac1x+\\tfrac1y+\\tfrac1z\\le\\tfrac3x$, bundan $x\\le3$.',
 's3.b1.steps.2':   'Boshqa tomondan $\\tfrac1x<1$, demak $x\\ge2$. Faqat $x=2$ va $x=3$ qoladi.',
 's3.b1.steps.3':   '**$x=3$:** u holda $\\tfrac1y+\\tfrac1z=\\tfrac23$ va $\\tfrac23\\le\\tfrac2y$, demak $y\\le3$; ammo $y\\ge x=3$, shuning uchun $y=3$ va $z=3$. $(3,3,3)$ uchligi.',
 's3.b1.steps.4':   '**$x=2$:** u holda $\\tfrac1y+\\tfrac1z=\\tfrac12$, ajratish formulasiga koʻra esa $(y-2)(z-2)=4$.',
 's3.b1.steps.5':   '$4$ ning $y\\le z$ boʻlgan musbat boʻluvchilari juftliklari $(1,4)$ va $(2,2)$, ular $(y,z)=(3,6)$ va $(4,4)$ ni beradi.',
 's3.b1.steps.6':   'Demak tartibdan qatʼi nazar uchta uchlik bor.',
 's3.b1.ans':       '$(3,3,3)$, $(2,4,4)$, $(2,3,6)$ va ularning oʻrin almashtirishlari.',
 's3.b2.name':      'Qoʻshni kvadratlar orasiga qisish',
 's3.b2.text':      'Baholashning ikkinchi turi. Agar biror $f(n)$ ifodadan toʻliq kvadrat boʻlish talab qilinsa, katta $n$ larda uning **ikkita qoʻshni kvadrat orasida** qatʼiy yotishini koʻrsatishga urining: $$k^2<f(n)<(k+1)^2 .$$ Ular orasida kvadrat yoʻq, demak katta $n$ lar mumkin emas — tekshirishga faqat bir necha kichik qiymat qoladi.',
 's3.b3.q':         'Qaysi musbat butun $n$ larda $n^{2}+2n+4$ toʻliq kvadrat boʻladi?',
 's3.b3.steps.0':   'Quyidagi eng yaqin kvadrat $(n+1)^2=n^2+2n+1$. Ayirma $3>0$, demak $n^2+2n+4>(n+1)^2$.',
 's3.b3.steps.1':   'Yuqoridagi eng yaqini $(n+2)^2=n^2+4n+4$. Ayirma $n\\ge1$ da $2n>0$, demak $n^2+2n+4<(n+2)^2$.',
 's3.b3.steps.2':   'Shunday qilib, har bir $n\\ge1$ uchun $(n+1)^2<n^2+2n+4<(n+2)^2$.',
 's3.b3.steps.3':   '$(n+1)^2$ va $(n+2)^2$ qoʻshni kvadratlari orasida qatʼiy yotgan toʻliq kvadrat yoʻq.',
 's3.b3.ans':       'Hech bir musbat butun $n$ da. ($n=0$ da u $4=2^2$ ga teng.)',
 's4.b0.text':      'Yechim **yoʻq**ligini isbotlash uchun odatdagi qurol — qoldiqlar. Gʻoya oddiy: agar tenglik butun sonlarda oʻrinli boʻlsa, u istalgan modul boʻyicha ham oʻrinli. Ikkala tomon hech qachon mos tushmaydigan modulni topish yetarli.',
 's4.b1.text':      'Bu ishlaydi, chunki darajalar juda kam sondagi qoldiq oladi. Mana boshda saqlashga arzigulik jadval:',
 's4.b2.head.0':    'Ifoda',
 's4.b2.head.1':    'Modul',
 's4.b2.head.2':    'Mumkin boʻlgan qoldiqlar',
 's4.b3.text':      'Har bir satrni tekshirish bir daqiqa oladi: $0,1,\\dots,m-1$ ni kerakli darajaga koʻtaring. Modul $8$ boʻyicha $n^2$ uchun: $0,1,4,9\\equiv1,16\\equiv0,25\\equiv1,36\\equiv4,49\\equiv1$ — faqat uchta qiymat $0,1,4$.',
 's4.b4.q':         '$x^{2}-3y^{2}=5$ ning butun yechimlari yoʻqligini isbotlang.',
 's4.b4.steps.0':   'Modul $3$ ni olamiz: $3y^2$ hadi yoʻqoladi va $x^2\\equiv5\\pmod3$ qoladi.',
 's4.b4.steps.1':   '$5=3+2$, demak bizga $x^2\\equiv2\\pmod3$ kerak.',
 's4.b4.steps.2':   'Ammo modul $3$ boʻyicha kvadrat faqat $0$ yoki $1$ (jadvalga qarang).',
 's4.b4.steps.3':   'Kvadrat hech qachon $2$ qoldiq bera olmaydi — ziddiyat.',
 's4.b4.ans':       'Yechim yoʻq. $\\blacksquare$',
 's4.b5.q':         '$2023$ ikkita toʻliq kvadrat yigʻindisi emasligini isbotlang.',
 's4.b5.steps.0':   '$x^2+y^2=2023$ deb faraz qilamiz va modul $4$ ni olamiz.',
 's4.b5.steps.1':   'Har bir kvadrat modul $4$ boʻyicha $0$ yoki $1$, demak ikkita kvadrat yigʻindisi $0$, $1$ yoki $2$.',
 's4.b5.steps.2':   'Modul $4$ boʻyicha $3$ qoldiq erishib boʻlmaydigan joyda.',
 's4.b5.steps.3':   'Ammo $2023=4\\cdot505+3$, yaʼni $2023\\equiv3\\pmod4$.',
 's4.b5.ans':       'Bunday tasvir mavjud emas. $\\blacksquare$',
 's4.b6.text':      'Qoldiqlar faqat yechimlar **yoʻq**ligini isbotlay oladi. Agar hech bir modul ziddiyat bermasa, bu oʻzi hech narsani isbotlamaydi: $x^2-2y^2=7$ tenglamasi har qanday modul sinovidan oʻtadi — va uning yechimi bor ($x=3,y=1$). Hech qachon «ziddiyat topilmadi, demak yechim bor» deb yozmang — bu isbot emas.',
 's5.b0.text':      '$x^{2}+y^{2}=z^{2}$ tenglamasi — barcha Diofant tenglamalari ichida eng mashhuri. Uning yechimlari toʻliq maʼlum, ularni keltirib chiqarish esa koʻpaytuvchilarga ajratish va oʻzaro tublik birgalikda masalani qanday tugatishini koʻrsatadi.',
 's5.b1.name':      'Boshlangʻich uchlik',
 's5.b1.text':      '$x^{2}+y^{2}=z^{2}$ boʻlgan musbat butun $(x,y,z)$ uchlik, agar $\\gcd(x,y,z)=1$ boʻlsa, **boshlangʻich** deyiladi. Har bir uchlik boshlangʻichning umumiy koʻpaytuvchiga koʻpaytirilgani, demak boshlangʻichlarini tavsiflash yetarli.',
 's5.b2.name':      'Boshlangʻich uchlikdagi juftliklar',
 's5.b2.text':      'Boshlangʻich uchlikda $x,y$ dan roppa-rosa bittasi juft, $z$ esa toq.',
 's5.b3.text':      '**Ikkalasi ham juft boʻla olmaydi:** u holda $z^{2}=x^{2}+y^{2}$ juft boʻlar, demak $z$ juft boʻlar va $\\gcd(x,y,z)\\ge2$ boʻlar edi ✗\\n\\n**Ikkalasi ham toq boʻla olmaydi:** toq sonning kvadrati modul $4$ boʻyicha $1$, demak $$z^{2}=x^{2}+y^{2}\\equiv2\\pmod4 .$$ Ammo kvadrat modul $4$ boʻyicha $0$ yoki $1$, hech qachon $2$ emas ✗\\n\\nDemak $x,y$ dan roppa-rosa bittasi juft, u holda $z^{2}\\equiv1\\pmod4$ va $z$ toq. $\\blacksquare$',
 's5.b4.name':      'Barcha boshlangʻich uchliklar',
 's5.b4.text':      '$x$ juft boʻlgan boshlangʻich uchliklar aynan $$x=2mn,\\qquad y=m^{2}-n^{2},\\qquad z=m^{2}+n^{2}$$ koʻrinishida, bunda $m>n>0$, $\\gcd(m,n)=1$ va $m,n$ turli juftlikda. Turli $(m,n)$ juftliklar turli uchlik beradi.',
 's5.b5.text':      '**Bu uchliklar mos keladi.** Bevosita tekshiramiz: $$(2mn)^{2}+\\left(m^{2}-n^{2}\\right)^{2}=m^{4}+2m^{2}n^{2}+n^{4}=\\left(m^{2}+n^{2}\\right)^{2} \\quad\\checkmark$$\\n\\n**Boshqasi yoʻq.** $(x,y,z)$ boshlangʻich va $x$ juft boʻlsin. Tenglamani qayta yozamiz: $$x^{2}=z^{2}-y^{2}=(z-y)(z+y).$$\\n\\nLemmaga koʻra $y$ va $z$ toq, demak $z-y$ va $z+y$ juft. $$u=\\frac{z-y}{2},\\qquad v=\\frac{z+y}{2},\\qquad\\text{demak}\\qquad uv=\\left(\\frac x2\\right)^{2} .$$\\n\\n**$u,v$ sonlari oʻzaro tub.** Umumiy boʻluvchi $d$ ularning yigʻindisi $z$ ni va ayirmasi $y$ ni boʻladi. Ammo $\\gcd(y,z)=1$: $y$ va $z$ ning umumiy boʻluvchisi $x^{2}=z^{2}-y^{2}$ ni, demak $x$ ni ham boʻlar edi, bu esa boshlangʻichlikka zid. Demak $d=1$.\\n\\n**Toʻliq kvadratning oʻzaro tub koʻpaytuvchilari oʻzlari ham kvadrat.** Demak biror $m>n>0$ va $\\gcd(m,n)=1$ uchun $$u=n^{2},\\qquad v=m^{2} .$$\\n\\nOrqaga qaytsak, $$z=m^{2}+n^{2},\\qquad y=m^{2}-n^{2},\\qquad x=2mn .$$\\n\\nNihoyat, $y=m^{2}-n^{2}$ ning toqligi $m$ va $n$ ni turli juftlikda boʻlishga majbur qiladi. $\\blacksquare$',
 's5.b7.q':         'Katetlaridan biri $15$ ga teng boʻlgan barcha Pifagor uchburchaklarini toping.',
 's5.b7.steps.0':   '$15$ kateti toq, demak u «toq» katet; $z^{2}-b^{2}=225$ deb yozamiz.',
 's5.b7.steps.1':   'Ajratamiz: $(z-b)(z+b)=225$, ikkala koʻpaytuvchi toq va $z-b<z+b$.',
 's5.b7.steps.2':   '$225=3^{2}\\cdot5^{2}$ ni shunday juftliklarga ajratishlar: $1\\cdot225$, $3\\cdot75$, $5\\cdot45$, $9\\cdot25$.',
 's5.b7.steps.3':   '$z=\\tfrac{(z-b)+(z+b)}2$ va $b=\\tfrac{(z+b)-(z-b)}2$ ni hisoblaymiz.',
 's5.b7.steps.4':   'Bu $(b,z)=(112,113),\\ (36,39),\\ (20,25),\\ (8,17)$ ni beradi.',
 's5.b7.steps.5':   '$(8,15,17)$ uchun tekshirish: $64+225=289=17^{2}$ ✓',
 's5.b7.ans':       'Toʻrtta uchburchak: $(15,8,17)$, $(15,20,25)$, $(15,36,39)$, $(15,112,113)$.',
 's5.b8.text':      '**Fermaning katta teoremasi.** Koʻrsatkich $2$ boʻlganda yechimlar cheksiz koʻp, ammo $n\\ge3$ da $$x^{n}+y^{n}=z^{n}$$ tenglamasining musbat butun yechimlari yoʻq. Ferma buni $1637$-yilda kitob chekkasiga yozgan va «haqiqatan ajoyib isbot» topganini, ammo chekka uni sigʻdira olmasligini qoʻshib qoʻygan. Isbot faqat $1995$-yilda paydo boʻldi (Endryu Uayls) va yuz betdan oshadi. $n=4$ holi maktab usullari bilan yechiladi — cheksiz tushish orqali.',
 's6.b0.text':      'Qaysi sonlarni $a^{2}+b^{2}$ koʻrinishida yozish mumkin? Javob goʻzal va toʻliq maʼlum, bosh rolni esa tub sonlarning modul $4$ boʻyicha qoldiqlari oʻynaydi.',
 's6.b1.name':      'Brahmagupta–Fibonachchi ayniyati',
 's6.b1.text':      '$$\\left(a^{2}+b^{2}\\right)\\left(c^{2}+d^{2}\\right)=(ac+bd)^{2}+(ad-bc)^{2}=(ac-bd)^{2}+(ad+bc)^{2} .$$ Demak **ikkita kvadrat yigʻindisi boʻlgan ikki sonning koʻpaytmasi yana ikkita kvadrat yigʻindisi**.',
 's6.b2.text':      'Birinchi oʻng tomonni ochamiz: $$(ac+bd)^{2}=a^{2}c^{2}+2abcd+b^{2}d^{2} ,$$ $$(ad-bc)^{2}=a^{2}d^{2}-2abcd+b^{2}c^{2} .$$\\n\\n$\\pm2abcd$ hadlari qisqaradi va $$a^{2}c^{2}+b^{2}d^{2}+a^{2}d^{2}+b^{2}c^{2}=\\left(a^{2}+b^{2}\\right)\\left(c^{2}+d^{2}\\right) \\quad\\checkmark$$ qoladi.\\n\\nIkkinchi ayniyat $d$ ni $-d$ ga almashtirishdan chiqadi. $\\blacksquare$',
 's6.b3.name':      'Modul $4$ boʻyicha toʻsiq',
 's6.b3.text':      'Ikkita kvadrat yigʻindisi $4$ ga boʻlganda hech qachon $3$ qoldiq bermaydi. Demak $4k+3$ koʻrinishidagi hech bir son ikkita kvadrat yigʻindisi emas.',
 's6.b4.text':      'Kvadrat modul $4$ boʻyicha $0$ yoki $1$: juft son $(2k)^{2}\\equiv0$, toq son esa $(2k+1)^{2}=4k(k+1)+1\\equiv1$ beradi.\\n\\nDemak ikkita kvadrat yigʻindisi $$0+0=0,\\qquad 0+1=1,\\qquad 1+1=2$$ dan biriga taqqoslanadi, hech qachon $3$ ga emas. $\\blacksquare$',
 's6.b5.name':      'Fermaning ikki kvadrat haqidagi teoremasi',
 's6.b5.text':      'Toq tub $p$ son $p=a^{2}+b^{2}$ koʻrinishida ikkita kvadrat yigʻindisi boʻlishi uchun $p\\equiv1\\pmod4$ boʻlishi **zarur va yetarli**, tasvir esa tartib va ishoralardan qatʼi nazar yagona.',
 's6.b6.text':      '**Zarurligi** — oldingi teorema: $p\\equiv3\\pmod4$ uchun tasvir mavjud emas.\\n\\n**Yetarliligi (sxema).** $p\\equiv1\\pmod4$ boʻlsin. Eyler mezoni $x^{2}\\equiv-1\\pmod p$ ni yechiladigan qiladi; shunday $x$ ni olamiz, demak $p\\mid x^{2}+1$.\\n\\nEndi **Tue lemmasini** qoʻllaymiz: agar $p\\mid x^{2}+1$ boʻlsa, $0<|a|,|b|<\\sqrt p$ va $a\\equiv xb\\pmod p$ boʻladigan butun $a,b$ mavjud. (Lemma Dirixle prinsipidan chiqadi: $0\\le u,v<\\sqrt p$ boʻlgan $(u,v)$ juftliklar $p$ ta qoldiqdan koʻp, demak ikkita juftlik bir xil $u-xv$ beradi.)\\n\\nU holda $$a^{2}+b^{2}\\equiv x^{2}b^{2}+b^{2}=b^{2}\\left(x^{2}+1\\right)\\equiv0\\pmod p ,$$ demak $p\\mid a^{2}+b^{2}$. Ammo $$0<a^{2}+b^{2}<2p ,$$ shuning uchun $a^{2}+b^{2}=p$ ✓ $\\blacksquare$',
 's6.b7.name':      'Qaysi sonlar ikkita kvadrat yigʻindisi',
 's6.b7.text':      'Musbat butun $n$ son ikkita kvadrat yigʻindisi boʻlishi uchun uning ajratmasida $4k+3$ koʻrinishidagi har bir tub son **juft** darajada qatnashishi zarur va yetarli.',
 's6.b8.q':         '$45$, $2025$ va $2023$ ikkita kvadrat yigʻindisimi?',
 's6.b8.steps.0':   '$45=3^{2}\\cdot5$. $3\\equiv3\\pmod4$ tub soni juft darajada qatnashadi ✓ Demak tasvirlanadi.',
 's6.b8.steps.1':   'Oshkor koʻrinishda: $5=1^{2}+2^{2}$, buni $9=3^{2}$ ga koʻpaytirsak $45=3^{2}+6^{2}=9+36$ ✓',
 's6.b8.steps.2':   '$2025=3^{4}\\cdot5^{2}$. $3$ ning darajasi $4$ — juft ✓ Va haqiqatan $2025=27^{2}+36^{2}$.',
 's6.b8.steps.3':   '$2023=7\\cdot17^{2}$. $7\\equiv3\\pmod4$ tub soni **birinchi** darajada qatnashadi ✗ Demak tasvirlanmaydi.',
 's6.b8.steps.4':   '$2023$ uchun qisqa yoʻl: u $\\equiv3\\pmod4$, bu allaqachon masalani hal qiladi.',
 's6.b8.ans':       '$45$ va $2025$ — ha; $2023$ — yoʻq.',
 's6.b9.text':      'Olimpiada masalalarida odatda **salbiy** yarmi kerak boʻladi: tenglamaning yechimi yoʻqligini koʻrsatish uchun toq darajada qatnashuvchi $p\\equiv3\\pmod4$ tub sonni topish — yoki shunchaki modul $4$ boʻyicha qoldiqqa qarash — yetarli.',
 's7.b0.text':      '$D$ toʻliq kvadrat boʻlmagan musbat butun son boʻlganda $x^{2}-Dy^{2}=1$ tenglamasi ajoyib tutadi: uning yo notrivial yechimi umuman yoʻq, yo birdaniga cheksiz koʻp, va ularning hammasi bittasidan hosil qilinadi.',
 's7.b1.name':      'Pell tenglamasi',
 's7.b1.text':      '$$x^{2}-Dy^{2}=1 ,$$ bunda $D$ — toʻliq kvadrat boʻlmagan musbat butun son. $(x,y)=(1,0)$ yechim trivial deyiladi; $y>0$ boʻlgan eng kichik yechim **asosiy** deyiladi.',
 's7.b2.text':      '$D$ ning kvadrat emasligi sharti muhim. $D=k^{2}$ da tenglama $$(x-ky)(x+ky)=1$$ koʻrinishiga keladi va $x=\\pm1$, $y=0$ ni majbur qiladi — faqat trivial yechimlar.',
 's7.b3.name':      'Bitta yechim cheksiz koʻpini tugʻadi',
 's7.b3.text':      '$\\left(x_1,y_1\\right)$ — $y_1>0$ boʻlgan $x^{2}-Dy^{2}=1$ ning yechimi boʻlsin. U holda $$x_{k+1}=x_1x_k+Dy_1y_k,\\qquad y_{k+1}=x_1y_k+y_1x_k$$ yana yechim boʻladi va hosil qilingan barcha yechimlar juft-jufti bilan turli.',
 's7.b4.text':      '**Bu yechim.** Oʻrniga qoʻyib ochamiz: $$x_{k+1}^{2}-Dy_{k+1}^{2}=\\left(x_1x_k+Dy_1y_k\\right)^{2}-D\\left(x_1y_k+y_1x_k\\right)^{2}.$$\\n\\nAralash hadlar mos tushib qisqaradi va $$\\left(x_1^{2}-Dy_1^{2}\\right)\\left(x_k^{2}-Dy_k^{2}\\right)=1\\cdot1=1 \\quad\\checkmark$$ qoladi.\\n\\n**Yechimlar turli.** $x_k,y_k>0$ da $y_{k+1}=x_1y_k+y_1x_k>y_k$, demak ikkinchi koordinata qatʼiy oʻsadi va hech narsa takrorlanmaydi. $\\blacksquare$\\n\\n**Formula qayerdan kelgan.** Bu $\\mathbb{Z}\\left[\\sqrt D\\right]$ halqasidagi koʻpaytirish: agar $x_k+y_k\\sqrt D$ ning normasi $1$ boʻlsa, $$\\left(x_1+y_1\\sqrt D\\right)\\left(x_k+y_k\\sqrt D\\right)=\\left(x_1x_k+Dy_1y_k\\right)+\\left(x_1y_k+y_1x_k\\right)\\sqrt D$$ ning normasi ham $1$.',
 's7.b5.name':      'Lagranj teoremasi',
 's7.b5.text':      'Toʻliq kvadrat boʻlmagan har bir musbat butun $D$ uchun $x^{2}-Dy^{2}=1$ tenglamasining $y>0$ boʻlgan yechimi bor. Bundan tashqari musbat butun sonlardagi **har bir** yechim asosiysidan $$x_k+y_k\\sqrt D=\\left(x_1+y_1\\sqrt D\\right)^{k},\\qquad k=1,2,3,\\dots$$ koʻrinishida hosil boʻladi.',
 's7.b6.text':      'Mavjudlik isboti irratsional $\\sqrt D$ ni ratsional sonlar bilan yaqinlashtirishga (Dirixlening yaqinlashtirish teoremasi) va Dirixle prinsipiga tayanadi — elementar, ammo bu yerga sigʻmaydigan darajada uzun. Asosiy yechim $\\sqrt D$ ning uzluksiz kasridan topiladi.\\n\\n**Ehtiyot boʻling:** u hayratlanarli darajada katta boʻlishi mumkin. $D=61$ uchun u $$x_1=1\\,766\\,319\\,049,\\qquad y_1=226\\,153\\,980 .$$',
 's7.b7.q':         '$x^{2}-2y^{2}=1$ ning eng kichik uchta musbat yechimini toping.',
 's7.b7.steps.0':   'Asosiysini qidiramiz: $y=1$ da $x^{2}=3$ ✗; $y=2$ da $x^{2}=9$, yaʼni $x=3$ ✓',
 's7.b7.steps.1':   'Demak $\\left(x_1,y_1\\right)=(3,2)$.',
 's7.b7.steps.2':   '$D=2$ bilan rekurrensiya: $x_{k+1}=3x_k+4y_k$, $y_{k+1}=3y_k+2x_k$.',
 's7.b7.steps.5':   'Tekshirish: $17^{2}-2\\cdot12^{2}=1$ ✓ va $99^{2}-2\\cdot70^{2}=1$ ✓',
 's7.b8.text':      '**Nom haqida.** Eyler tenglamani xato ravishda ingliz matematigi Jon Pellga bogʻlagan, u esa bunga deyarli aloqador emas edi; tenglamani ancha oldin hind matematiklari — yettinchi asrda Brahmagupta va oʻn ikkinchi asrda Bhaskara II — tizimli oʻrgangan. Tarixiy adolatsizlik saqlanib qoldi.\\n\\n**Qayerda uchraydi.** Pell tenglamasi ikkita kattalik «deyarli teng» boʻlishi kerak boʻlgan hamma joyda paydo boʻladi: kvadrat boʻlgan uchburchakli sonlar, $\\sqrt2\\approx\\tfrac{99}{70}$ kabi yaqinlashtirishlar va Arximedning buqalar haqidagi masalasi.',
 's8.b0.text':      'Fermaning usuli va mavzudagi eng goʻzali. Yechim bor deb faraz qiling. Undan **eskisidan kichikroq yangi yechim** yasang. Buni takrorlash musbat butun sonlarning cheksiz qatʼiy kamayuvchi ketma-ketligini beradi — bunday ketma-ketlik esa mavjud emas. Demak dastlabki faraz notoʻgʻri edi.',
 's8.b1.text':      'Amalda shunday aytish tozaroq: biror musbat kattalikning (masalan $z$ ning) **eng kichik** qiymatiga ega yechimni oling va undan kichikrogʻini yasang. Bu minimallikka zid, isbot esa tugadi.',
 's8.b2.name':      'Namunaviy tushish',
 's8.b2.text':      '$x^{2}+y^{2}=3z^{2}$ tenglamasining butun sonlarda roppa-rosa bitta yechimi bor: $x=y=z=0$.',
 's8.b3.text':      '$z\\ne0$ boʻlgan yechim bor deb faraz qilamiz va ular orasidan $|z|$ **eng kichik** boʻlganini tanlaymiz.\\n\\n**1-qadam.** Modul $3$ boʻyicha $x^2+y^2\\equiv0$. Kvadrat modul $3$ boʻyicha $0$ yoki $1$, demak ikkita kvadrat yigʻindisi $0,1$ yoki $2$. U **faqat** ikkala had ham nol boʻlgandagina nolga teng, yaʼni $x\\equiv y\\equiv0\\pmod3$.\\n\\n**2-qadam.** $x=3a$, $y=3b$ deb yozamiz. U holda $$9a^{2}+9b^{2}=3z^{2}\\quad\\Longrightarrow\\quad 3(a^{2}+b^{2})=z^{2}.$$\\n\\n**3-qadam.** Demak $3\\mid z^{2}$, $3$ tub boʻlgani uchun esa $3\\mid z$. $z=3c$ deb yozamiz: $$3(a^{2}+b^{2})=9c^{2}\\quad\\Longrightarrow\\quad a^{2}+b^{2}=3c^{2}.$$\\n\\n**4-qadam.** Biz xuddi shu tenglamaning yangi $(a,b,c)$ yechimini yasadik, bunda $|c|=|z|/3<|z|$ va $c\\ne0$ (aks holda $z=0$ boʻlar edi). Bu $|z|$ ning minimalligiga zid.\\n\\nDemak $z\\ne0$ boʻlgan yechim yoʻq; $z=0$ boʻlganda esa $x^2+y^2=0$ dan $x=y=0$. $\\blacksquare$',
 's8.b4.text':      'Xuddi shu tushish bilan Ferma $x^{4}+y^{4}=z^{2}$ ning musbat butun yechimlari yoʻqligini isbotlagan — bundan darhol uning katta teoremasi $4$ koʻrsatkich uchun kelib chiqadi. Bu masala quyidagi roʻyxatda sizni kutmoqda.',
 's8.b5.name':      'Tushish kerakligini qanday sezish mumkin',
 's8.b5.text':      'Belgilari: tenglama **bir jinsli** (barcha hadlar bir xil darajada, $x^2+y^2=3z^2$ dagidek), yoki oʻzgaruvchilar simmetrik kiradi, yoki qoldiqlar mulohazasi har bir oʻzgaruvchi bir xil tub songa boʻlinishini koʻrsatadi. Oxirgisi deyarli aniq signal: boʻling va takrorlang.',
 's8.b6.name':      'Cheksiz tushish prinsipi',
 's8.b6.text':      'Musbat butun sonlardagi har bir yechimdan **qatʼiy kichikroq** yechim yasash mumkin deb faraz qilaylik. U holda yechim umuman yoʻq.',
 's8.b7.text':      'Yechim bor deb faraz qilaylik. Barcha yechimlar boʻyicha tanlangan biror kattalik (masalan $z$ yoki $x+y+z$ yigʻindisi) qabul qiladigan musbat qiymatlar toʻplamini koʻramiz. Bu musbat butun sonlarning boʻsh boʻlmagan toʻplami, demak eng kichik son prinsipiga koʻra unda eng kichik element bor.\\n\\nUnga mos yechimni olamiz. Farazga koʻra u oʻsha kattalikning qatʼiy kichikroq qiymatiga ega yechim beradi — bu minimallikka zid ✗ $\\blacksquare$',
 's8.b8.text':      'Tushish — bu teskariga burilgan induksiya. Amalda u shunday koʻrinadi: har bir nomaʼlum biror $d>1$ ga boʻlinishini koʻrsating, $d$ ga boʻling va kichikroq yechim oling. Agar boʻlinuvchanlik **har safar** kelib chiqsa, tushish hech qachon toʻxtamaydi — demak yechim yoʻq.',
 's8.b9.q':         '$x^{2}+y^{2}=3z^{2}$ ning musbat butun yechimlari yoʻqligini isbotlang.',
 's8.b9.steps.0':   '$z$ eng kichik boʻlgan yechimni olamiz.',
 's8.b9.steps.1':   'Modul $3$ boʻyicha kvadratlar faqat $0$ va $1$, demak $x^{2}+y^{2}\\equiv0\\pmod3$ dan $x^{2}\\equiv y^{2}\\equiv0$.',
 's8.b9.steps.2':   'Shuning uchun $3\\mid x$ va $3\\mid y$; $x=3a$, $y=3b$ deb yozamiz.',
 's8.b9.steps.3':   'Oʻrniga qoʻysak, $9a^{2}+9b^{2}=3z^{2}$, yaʼni $3\\left(a^{2}+b^{2}\\right)=z^{2}$.',
 's8.b9.steps.4':   'Demak $3\\mid z^{2}$ va $3\\mid z$; $z=3c$ deb yozib qisqartiramiz: $a^{2}+b^{2}=3c^{2}$.',
 's8.b9.steps.5':   'Bu $c=\\tfrac z3<z$ boʻlgan yechim — minimallikka zid ✗',
 's8.b9.ans':       'Yechim yoʻq.',
}
