# -*- coding: utf-8 -*-
"""Uzbek for topic 6.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Tengsizliklar',
 'sub':             '«Kvadrat manfiy emas» dan Koshi–Bunyakovskiygacha: tengsizlikni taxmin qilish emas, isbotlash yoʻli.',
 'goals.0':         'Tengsizliklar qoidalaridan foydalanish va koʻpaytirishda ishorani hech qachon yoʻqotmaslik.',
 'goals.1':         'Hamma narsani chapga oʻtkazib, kvadratlar yigʻib tengsizlikni isbotlash.',
 'goals.2':         'Oʻrta arifmetik va oʻrta geometrik tengsizligini ikki, uch va $n$ ta son uchun ishonch bilan qoʻllash.',
 'goals.3':         'Koshi–Bunyakovskiy tengsizligini va uning Engel shaklini bilish, tenglik qachon boʻlishini koʻrish.',
 's0.h':            'Oʻyin qoidalari',
 's1.h':            'Oʻrta arifmetik va oʻrta geometrik tengsizligi',
 's2.h':            'Oʻrta qiymatlar zanjiri',
 's3.h':            'Darajali oʻrtalar',
 's4.h':            'Koshi–Bunyakovskiy tengsizligi',
 's5.h':            'Qayta tartiblash va Chebishyov tengsizliklari',
 's6.h':            'Qavariqlik va Yensen tengsizligi',
 's7.h':            'Masalani yakunlaydigan usullar',
 's8.h':            'Murakkabroq usullar',
 's0.b0.text':      'Tengsizlikni isbotlash — bu uni maʼlum tengsizliklardan ruxsat etilgan usullar bilan keltirib chiqarish. Ruxsat etilgan usullar kam, ulardan birida esa tuzoq bor.',
 's0.b1.items.0':   '**Qoʻshish.** Agar $a>b$ boʻlsa, istalgan $c$ uchun $a+c>b+c$.',
 's0.b1.items.1':   '**Bir xil yoʻnalishdagi tengsizliklarni qoʻshish.** $a>b$ va $c>d$ dan $a+c>b+d$ kelib chiqadi.',
 's0.b1.items.2':   '**Musbat songa koʻpaytirish.** Agar $a>b$ va $c>0$ boʻlsa, $ac>bc$.',
 's0.b1.items.3':   '**Manfiy songa koʻpaytirish ishorani almashtiradi.** Agar $a>b$ va $c<0$ boʻlsa, $ac<bc$.',
 's0.b1.items.4':   '**Tranzitivlik.** $a>b$ va $b>c$ dan $a>c$ kelib chiqadi.',
 's0.b1.items.5':   '**Kvadratga koʻtarish — faqat manfiy boʻlmagan sonlar uchun.** Agar $a>b\\ge0$ boʻlsa, $a^{2}>b^{2}$.',
 's0.b2.text':      '**Tengsizliklarni ayirish mumkin emas.** $5>3$ va $10>1$ dan $5-10>3-1$ kelib chiqmaydi. Ayirish kerak boʻlsa, ikkinchisini agʻdaring va qoʻshing: $c>d$ dan $-c<-d$, soʻng $a-d>b-c$. Xuddi shunday, bir tengsizlikni ikkinchisiga boʻlish ham mumkin emas.',
 's0.b3.name':      'Hamma narsa ortidagi yagona usul',
 's0.b3.text':      '$A\\ge B$ ni isbotlash uchun hamma narsani bir tomonga oʻtkazing va $A-B\\ge0$ ekanini koʻrsating. Ifodaning manfiy emasligini koʻrsatish uchun esa uni **kvadratlar yigʻindisi** koʻrinishida — ehtimol biror musbat songa koʻpaytirilgan holda — yozing. Maktab darajasidagi deyarli har bir tengsizlik aynan shunday isbotlanadi.',
 's0.b4.name':      'Asosiy tengsizlik',
 's0.b4.text':      'Barcha haqiqiy $a$ va $b$ uchun $$a^{2}+b^{2}\\ge2ab,$$ tenglik esa faqat $a=b$ boʻlganda.',
 's0.b5.text':      'Hamma narsani chapga oʻtkazamiz: $a^{2}-2ab+b^{2}\\ge0$, yaʼni $(a-b)^{2}\\ge0$. Haqiqiy sonning kvadrati manfiy emas, demak tengsizlik oʻrinli. Tenglik aynan $(a-b)^{2}=0$, yaʼni $a=b$ boʻlganda. $\\blacksquare$',
 's0.b6.text':      'Shu bittasidan oʻnlab boshqa tengsizlik chiqadi. $x,y\\ge0$ uchun $a=\\sqrt{x}$, $b=\\sqrt{y}$ qoʻysak $x+y\\ge2\\sqrt{xy}$ chiqadi. $a=\\sqrt{x}$, $b=\\tfrac1{\\sqrt{x}}$ qoʻysak $x>0$ uchun $x+\\tfrac1x\\ge2$ chiqadi. Ikkala tomonni $ab>0$ ga boʻlsak $\\tfrac ab+\\tfrac ba\\ge2$ chiqadi.',
 's0.b7.q':         'Barcha haqiqiy $a,b,c$ uchun $a^{2}+b^{2}+c^{2}\\ge ab+bc+ca$ ekanini isbotlang.',
 's0.b7.steps.0':   'Hamma narsani chapga oʻtkazamiz va $2$ ga koʻpaytiramiz (bu yoʻnalishni oʻzgartirmaydi): $$2a^{2}+2b^{2}+2c^{2}-2ab-2bc-2ca\\ge0 .$$',
 's0.b7.steps.1':   'Har bir kvadratni ikki qoʻshnisi oʻrtasida teng taqsimlaymiz: $$\\left(a^{2}-2ab+b^{2}\\right)+\\left(b^{2}-2bc+c^{2}\\right)+\\left(c^{2}-2ca+a^{2}\\right).$$',
 's0.b7.steps.2':   'Bu aynan $(a-b)^{2}+(b-c)^{2}+(c-a)^{2}\\ge0$.',
 's0.b7.steps.3':   'Tenglik uchala kvadrat ham nolga aylanganda, yaʼni $a=b=c$ boʻlganda.',
 's0.b7.ans':       'Isbotlandi; tenglik $a=b=c$ boʻlganda. $\\blacksquare$',
 's0.b8.name':      'Modullar uchun uchburchak tengsizligi',
 's0.b8.text':      'Barcha haqiqiy $a,b$ uchun $$\\left|a+b\\right|\\ \\le\\ \\left|a\\right|+\\left|b\\right| ,$$ demak $$\\bigl|\\,\\left|a\\right|-\\left|b\\right|\\,\\bigr|\\ \\le\\ \\left|a-b\\right| .$$',
 's0.b9.text':      'Ikkala tomon ham manfiy emas, demak tengsizlik kvadratlar orasidagi tengsizlikka teng kuchli: $$\\left(a+b\\right)^{2}\\ \\le\\ \\left(\\left|a\\right|+\\left|b\\right|\\right)^{2}.$$\\n\\nChap tomon $a^{2}+2ab+b^{2}$, oʻng tomon $a^{2}+2\\left|a\\right|\\left|b\\right|+b^{2}$. Qisqartirgach $$ab\\ \\le\\ \\left|a\\right|\\left|b\\right|=\\left|ab\\right|$$ qoladi, bu esa har doim oʻrinli: son oʻz moduli dan oshmaydi ✓\\n\\nIkkinchi tengsizlik uchun birinchisini $a=\\left(a-b\\right)+b$ ga qoʻllaymiz, bu $\\left|a\\right|\\le\\left|a-b\\right|+\\left|b\\right|$, yaʼni $\\left|a\\right|-\\left|b\\right|\\le\\left|a-b\\right|$ ni beradi. $a$ va $b$ ni almashtirsak $\\left|b\\right|-\\left|a\\right|$ uchun shu baho chiqadi ✓ $\\blacksquare$',
 's0.b10.text':     'Tenglik aynan $a$ va $b$ **bir xil ishorali** boʻlganda (yoki ulardan biri nol boʻlganda) — aynan $ab=\\left|ab\\right|$ boʻlgan holda — oʻrinli.',
 's0.b11.text':     '**$X\\ge Y$ ni isbotlashning uchta yoʻli.**\\n\\n1. Hamma narsani bir tomonga oʻtkazib ajrating: $X-Y=\\left(\\dots\\right)^{2}$ yoki manfiy boʻlmagan koʻpaytuvchilar koʻpaytmasi.\\n2. Nomli tengsizlikka keltiring (oʻrta qiymatlar, Koshi–Bunyakovskiy, Yensen).\\n3. Oraliq kattalik orqali $X\\ge Z\\ge Y$ zanjirini isbotlang.\\n\\nBirinchi yoʻl deyarli har bir maktab masalasida ishlaydi va hech qanday havolani talab qilmaydi.',
 's1.b0.name':      'Ikki son uchun oʻrta arifmetik va oʻrta geometrik tengsizligi',
 's1.b0.text':      'Manfiy boʻlmagan $x,y$ uchun $$\\frac{x+y}{2}\\ \\ge\\ \\sqrt{xy},$$ tenglik esa faqat $x=y$ boʻlganda.',
 's1.b1.text':      '$a=\\sqrt{x}$, $b=\\sqrt{y}$ qoʻyamiz ($x,y\\ge0$ boʻlgani uchun bu oʻrinli). U holda $(a-b)^{2}\\ge0$ dan $a^{2}+b^{2}\\ge2ab$, yaʼni $x+y\\ge2\\sqrt{xy}$ chiqadi. $2$ ga boʻlamiz. $\\blacksquare$',
 's1.b2.name':      'Uch son uchun oʻrta arifmetik va oʻrta geometrik tengsizligi',
 's1.b2.text':      'Manfiy boʻlmagan $x,y,z$ uchun $$\\frac{x+y+z}{3}\\ \\ge\\ \\sqrt[3]{xyz},$$ tenglik esa faqat $x=y=z$ boʻlganda.',
 's1.b3.text':      'Ajratish mavzusidagi ayniyatdan foydalanamiz: $$a^{3}+b^{3}+c^{3}-3abc=(a+b+c)\\left(a^{2}+b^{2}+c^{2}-ab-bc-ca\\right)=\\tfrac12(a+b+c)\\left[(a-b)^{2}+(b-c)^{2}+(c-a)^{2}\\right].$$ Agar $a,b,c\\ge0$ boʻlsa, oʻngdagi ikkala koʻpaytuvchi ham manfiy emas, demak $$a^{3}+b^{3}+c^{3}\\ge3abc .$$ Endi $a=\\sqrt[3]{x}$, $b=\\sqrt[3]{y}$, $c=\\sqrt[3]{z}$ qoʻysak $x+y+z\\ge3\\sqrt[3]{xyz}$ chiqadi. Tenglik uchun $a=b=c$, yaʼni $x=y=z$ kerak. $\\blacksquare$',
 's1.b4.name':      '$n$ ta son uchun oʻrta arifmetik va oʻrta geometrik tengsizligi',
 's1.b4.text':      'Manfiy boʻlmagan $x_1,\\dots,x_n$ uchun $$\\frac{x_1+x_2+\\dots+x_n}{n}\\ \\ge\\ \\sqrt[n]{x_1x_2\\cdots x_n},$$ tenglik esa faqat barcha sonlar teng boʻlganda.',
 's1.b5.name':      'Qanday ishlatiladi',
 's1.b5.text':      'Bu tengsizlik **yigʻindini** **koʻpaytmaga** va aksincha aylantiradi. Shuning uchun u koʻpaytma oʻzgarmas boʻlganda eng yaxshi ishlaydi. Masalan, agar $xy=16$ boʻlsa, $x+y\\ge2\\sqrt{16}=8$: yigʻindi $x=y=4$ da eng kichik.\\n\\nVa aksincha: yigʻindi qatʼiy boʻlganda koʻpaytma hadlar teng boʻlganda eng katta. Shuning uchun berilgan perimetrli barcha toʻgʻri toʻrtburchaklar ichida kvadratning yuzasi eng katta.',
 's1.b6.q':         'Har bir $x>0$ uchun $x^{2}+\\dfrac{2}{x}\\ge3$ ekanini isbotlang va tenglik qachon boʻlishini toping.',
 's1.b6.steps.0':   'Usul: koʻpaytma toza chiqishi uchun $\\tfrac2x$ ni ikkita teng hadga ajrating.',
 's1.b6.steps.2':   'Uchta musbat songa tengsizlikni qoʻllaymiz: $$x^{2}+\\frac1x+\\frac1x\\ \\ge\\ 3\\sqrt[3]{x^{2}\\cdot\\frac1x\\cdot\\frac1x}=3\\sqrt[3]{1}=3 .$$',
 's1.b6.steps.3':   'Tenglik uchun uchala had teng boʻlishi kerak: $x^{2}=\\tfrac1x$, yaʼni $x^{3}=1$ va $x=1$.',
 's1.b6.steps.4':   'Tekshirish: $x=1$ da chap tomon $1+2=3$ ✓',
 's1.b6.ans':       'Isbotlandi; tenglik faqat $x=1$ da. $\\blacksquare$',
 's1.b7.text':      'Ajratish **koʻpaytmani oʻzgarmas** qilishi kerak. Tengsizlikni $x^{2}$ va $\\tfrac2x$ hadlariga qoʻllash $2\\sqrt{2x}$ ni berar edi — hanuz oʻzgaruvchi qatnashgan ifoda, undan esa hech narsa kelib chiqmaydi. Toʻgʻri ajratishni tanlash bu yerdagi haqiqiy mahorat.',
 's1.b8.name':      'Tengsizlikning isboti (Koshi induksiyasi)',
 's1.b8.text':      'Har bir $n$ va barcha $a_1,\\dots,a_n\\ge0$ uchun $$\\frac{a_1+a_2+\\dots+a_n}{n}\\ \\ge\\ \\sqrt[n]{a_1a_2\\cdots a_n},$$ tenglik esa faqat barcha sonlar teng boʻlganda.',
 's1.b9.text':      'Koshining klassik isboti «ikkining darajalari boʻyicha oldinga, bittalab orqaga» tarzida boradi.\\n\\n**1-qadam: $n=2$ holi.** $$\\frac{a+b}{2}-\\sqrt{ab}=\\frac{\\left(\\sqrt{a}-\\sqrt{b}\\right)^{2}}{2}\\ \\ge\\ 0 \\quad\\checkmark$$\\n\\n**2-qadam: $n$ dan $2n$ ga.** Tengsizlik $n$ ta son uchun oʻrinli deb faraz qilamiz. $2n$ ta sonni olamiz va ikki yarmiga ajratamiz: $$\\frac{a_1+\\dots+a_{2n}}{2n}=\\frac12\\left(\\frac{a_1+\\dots+a_n}{n}+\\frac{a_{n+1}+\\dots+a_{2n}}{n}\\right)\\ \\ge\\ \\frac12\\left(G_1+G_2\\right),$$ bunda $G_1,G_2$ — yarmlarning oʻrta geometriklari. $n=2$ holiga koʻra $$\\frac{G_1+G_2}{2}\\ \\ge\\ \\sqrt{G_1G_2}=\\sqrt[2n]{a_1\\cdots a_{2n}} \\quad\\checkmark$$\\n\\nDemak tengsizlik $n=2,4,8,16,\\dots$ — ikkining har bir darajasi uchun oʻrinli.\\n\\n**3-qadam: $n$ dan $n-1$ ga.** Tengsizlik $n$ ta son uchun oʻrinli boʻlsin va $a_1,\\dots,a_{n-1}$ berilgan boʻlsin. Ularning oʻrta arifmetigini $$A=\\frac{a_1+\\dots+a_{n-1}}{n-1}$$ deb yozamiz va $n$ ta son uchun tengsizlikni $a_1,\\dots,a_{n-1},A$ roʻyxatiga qoʻllaymiz: $$\\frac{a_1+\\dots+a_{n-1}+A}{n}\\ \\ge\\ \\sqrt[n]{a_1\\cdots a_{n-1}A}.$$ Surat $\\left(n-1\\right)A+A=nA$, demak chap tomon shunchaki $A$. $n$-darajaga koʻtaramiz: $$A^{n}\\ \\ge\\ a_1\\cdots a_{n-1}A .$$ Agar $A=0$ boʻlsa, barcha sonlar nol va tasdiq ravshan; aks holda $A$ ga boʻlamiz: $$A^{\\,n-1}\\ \\ge\\ a_1\\cdots a_{n-1} ,$$ yaʼni $A\\ge\\sqrt[n-1]{a_1\\cdots a_{n-1}}$ ✓\\n\\n**Xulosa.** Har bir $n$ biror $2^{k}$ darajadan oshmaydi; $2^{k}$ uchun tengsizlik 2-qadamga koʻra oʻrinli va 3-qadamni takrorlash bilan $n$ gacha tushadi ✓ $\\blacksquare$',
 's1.b10.text':     'Bu sxema — ikkining darajalari uchun isbotlab, soʻng tushish — **Koshi induksiyasi** deyiladi va tengsizliklardan ancha nariga foydali.',
 's2.b0.text':      'Musbat sonlar toʻplamining toʻrtta klassik «oʻrtasi» bor. Ikkita $a,b>0$ son uchun ular shunday koʻrinadi:',
 's2.b1.head.0':    'Oʻrta',
 's2.b1.head.1':    'Belgi',
 's2.b1.head.2':    'Ikki son uchun formula',
 's2.b1.rows.0.0':  'kvadratik',
 's2.b1.rows.1.0':  'arifmetik',
 's2.b1.rows.2.0':  'geometrik',
 's2.b1.rows.3.0':  'garmonik',
 's2.b2.name':      'Zanjir',
 's2.b2.text':      'Musbat sonlar uchun har doim $$\\mathrm{QM}\\ \\ge\\ \\mathrm{AM}\\ \\ge\\ \\mathrm{GM}\\ \\ge\\ \\mathrm{HM},$$ toʻrtalasi esa faqat barcha sonlar teng boʻlgandagina ustma-ust tushadi.',
 's2.b3.text':      'Ikki son uchun isbotlaymiz; umumiy holda xuddi shu usullar ishlatiladi.\\n\\n**QM $\\ge$ AM.** Ikkala tomon ham musbat, demak kvadratga koʻtarish mumkin: $\\tfrac{a^{2}+b^{2}}{2}\\ge\\tfrac{(a+b)^{2}}{4}$, yaʼni $2(a^{2}+b^{2})\\ge(a+b)^{2}$, yaʼni $a^{2}-2ab+b^{2}\\ge0$ — yana $(a-b)^{2}\\ge0$.\\n\\n**AM $\\ge$ GM.** Yuqorida isbotlandi.\\n\\n**GM $\\ge$ HM.** $\\mathrm{HM}=\\dfrac{ab}{\\mathrm{AM}}$ va $\\mathrm{GM}^{2}=ab$ ekanini eʼtiborga olsak, $$\\frac{\\mathrm{GM}}{\\mathrm{HM}}=\\frac{\\mathrm{GM}\\cdot\\mathrm{AM}}{ab}=\\frac{\\mathrm{AM}}{\\mathrm{GM}}\\ \\ge\\ 1 .$$ $\\blacksquare$',
 's2.b4.text':      '$n$ ta son uchun AM $\\ge$ HM tengsizligini $$(x_1+\\dots+x_n)\\left(\\frac1{x_1}+\\dots+\\frac1{x_n}\\right)\\ \\ge\\ n^{2}$$ koʻrinishida eslash osonroq. $n=2$ da bu $(a+b)\\left(\\tfrac1a+\\tfrac1b\\right)\\ge4$, $n=3$ da esa $\\ge9$. U doimo uchrab turadi.',
 's3.b0.text':      'Oʻrta arifmetik, oʻrta geometrik, oʻrta kvadratik va oʻrta garmonik — bu toʻrtta alohida qurilma emas, balki bitta uzluksiz shkalaning toʻrtta nuqtasi. Bu shkalani bir marta koʻrsangiz, tengsizliklar zanjirini yodlashni bas qilasiz: u oʻz-oʻzidan ravshan boʻlib qoladi.',
 's3.b1.name':      'Darajali oʻrta',
 's3.b1.text':      '$a_1,\\dots,a_n>0$ va $t\\ne0$ haqiqiy son boʻlsin. **$t$-tartibli darajali oʻrta** — bu $$M_t=\\left(\\frac{a_1^{\\,t}+a_2^{\\,t}+\\dots+a_n^{\\,t}}{n}\\right)^{1/t}.$$ $t=0$ uchun taʼrif uzluksizlik boʻyicha kengaytiriladi: $$M_0=\\sqrt[n]{a_1a_2\\cdots a_n}.$$',
 's3.b2.head.1':    'Nomi',
 's3.b2.head.2':    'Formula',
 's3.b2.rows.0.1':  'garmonik $H$',
 's3.b2.rows.1.1':  'geometrik $G$',
 's3.b2.rows.2.1':  'arifmetik $A$',
 's3.b2.rows.3.1':  'kvadratik $Q$',
 's3.b2.rows.4.1':  'maksimum',
 's3.b2.rows.5.1':  'minimum',
 's3.b3.name':      'Darajali oʻrtalar tengsizligi',
 's3.b3.text':      'Agar $s<t$ boʻlsa, barcha musbat $a_1,\\dots,a_n$ uchun $$M_s\\le M_t,$$ tenglik esa faqat $a_1=a_2=\\dots=a_n$ boʻlganda.',
 's3.b4.text':      'Umumiy hol Yensen tengsizligidan chiqadi (keyingi boʻlim): $t/s>1$ boʻlganda $x\\mapsto x^{t/s}$ akslantirish qavariq. Bu yerda deyarli hamma narsani qamrab oladigan uchta maktab holini isbotlaymiz.\\n\\n**$Q\\ge A$.** $(a_1,\\dots,a_n)$ va $(1,\\dots,1)$ vektorlari bilan Koshi–Bunyakovskiy $$\\left(a_1+\\dots+a_n\\right)^{2}\\le n\\left(a_1^{2}+\\dots+a_n^{2}\\right)$$ ni beradi. $n^{2}$ ga boʻlib kvadrat ildiz olamiz ✓\\n\\n**$A\\ge G$.** Bu yuqorida isbotlangan tengsizlik ✓\\n\\n**$G\\ge H$.** $A\\ge G$ ni $\\frac1{a_1},\\dots,\\frac1{a_n}$ sonlariga qoʻllaymiz: $$\\frac{\\frac1{a_1}+\\dots+\\frac1{a_n}}{n}\\ \\ge\\ \\sqrt[n]{\\frac1{a_1\\cdots a_n}}=\\frac1{G}.$$ Ikkala tomonni agʻdaramiz (ular musbat, demak ishora almashadi): $$H=\\frac{n}{\\frac1{a_1}+\\dots+\\frac1{a_n}}\\le G \\quad\\checkmark$$\\n\\nUchala holda ham ishlatilgan qurolda tenglik barcha $a_i$ larning tengligiga teng kuchli. $\\blacksquare$',
 's3.b5.q':         '$a,b,c>0$ va $a+b+c=3$ boʻlsin. $a^{2}+b^{2}+c^{2}\\ge3$ va $\\dfrac1a+\\dfrac1b+\\dfrac1c\\ge3$ ekanini isbotlang.',
 's3.b5.steps.0':   'Shart $A=\\dfrac{a+b+c}{3}=1$ ekanini bildiradi.',
 's3.b5.steps.1':   'Birinchi tengsizlik — bu $Q\\ge A$: $\\sqrt{\\dfrac{a^{2}+b^{2}+c^{2}}{3}}\\ge1$, demak $a^{2}+b^{2}+c^{2}\\ge3$ ✓',
 's3.b5.steps.2':   'Ikkinchisi — $A\\ge H$: $1\\ge\\dfrac{3}{\\frac1a+\\frac1b+\\frac1c}$, yaʼni $\\dfrac1a+\\dfrac1b+\\dfrac1c\\ge3$ ✓',
 's3.b5.steps.3':   'Ikkala holda ham tenglik $a=b=c=1$ da.',
 's3.b5.ans':       'Ikkalasi ham $A=1$ boʻlgan oʻrtalar shkalasidan kelib chiqadi.',
 's3.b6.name':      'Vaznli oʻrta qiymatlar tengsizligi',
 's3.b6.text':      '$w_1,\\dots,w_n>0$ va $w_1+\\dots+w_n=1$ boʻlsin. U holda musbat $a_i$ lar uchun $$w_1a_1+w_2a_2+\\dots+w_na_n\\ \\ge\\ a_1^{\\,w_1}a_2^{\\,w_2}\\cdots a_n^{\\,w_n},$$ tenglik esa faqat $a_1=\\dots=a_n$ boʻlganda.',
 's3.b7.text':      'Ratsional vaznlar uchun isbot elementar. $w_i=\\dfrac{k_i}{N}$ deb yozamiz, bunda $k_i$ butun va yigʻindisi $N$. Oddiy tengsizlikni $a_1$ $k_1$ marta, $a_2$ $k_2$ marta va hokazo takrorlangan $N$ ta songa qoʻllaymiz: $$\\frac{k_1a_1+\\dots+k_na_n}{N}\\ \\ge\\ \\sqrt[N]{a_1^{\\,k_1}\\cdots a_n^{\\,k_n}}=a_1^{\\,k_1/N}\\cdots a_n^{\\,k_n/N}.$$ Bu aynan talab qilingani ✓\\n\\nIxtiyoriy haqiqiy vaznlar limit orqali chiqadi: har bir haqiqiy son ratsionallar bilan yaqinlashtiriladi, ikkala tomon esa $w_i$ boʻyicha uzluksiz. $\\blacksquare$',
 's3.b8.text':      'Vaznli koʻrinish — bu **kerakli tenglik nuqtasiga moʻljal olish** usuli. Oddiy tengsizlik tenglikni faqat sonlar teng boʻlganda beradi; agar masalada tenglik, aytaylik, $a=2b$ da kerak boʻlsa, shunga olib keladigan vaznlarni tanlang.',
 's4.b0.name':      'Koshi–Bunyakovskiy',
 's4.b0.text':      'Barcha haqiqiy sonlar uchun $$\\left(a_1^{2}+\\dots+a_n^{2}\\right)\\left(b_1^{2}+\\dots+b_n^{2}\\right)\\ \\ge\\ \\left(a_1b_1+\\dots+a_nb_n\\right)^{2},$$ tenglik esa faqat ikkala roʻyxat proporsional boʻlganda.',
 's4.b1.text':      '$$f(t)=\\sum_{i=1}^{n}\\left(a_i t-b_i\\right)^{2}\\ \\ge\\ 0\\qquad\\text{har bir }t \\text{ uchun}$$ funksiyani koʻramiz. Ochsak, $$f(t)=\\left(\\sum a_i^{2}\\right)t^{2}-2\\left(\\sum a_ib_i\\right)t+\\sum b_i^{2}=At^{2}-2Bt+C .$$ Bu $A\\ge0$ boʻlgan, barcha $t$ larda manfiy boʻlmagan kvadrat uchhad. Agar $A>0$ boʻlsa, uning diskriminanti musbat emas: $$4B^{2}-4AC\\le0\\quad\\Longrightarrow\\quad B^{2}\\le AC,$$ bu esa talab qilingani. Agar $A=0$ boʻlsa, har bir $a_i=0$ va ikkala tomon ham nolga aylanadi.\\n\\nTenglik diskriminant nolga teng ekanini bildiradi, demak $f$ ning $t_0$ ildizi bor; u holda barcha $i$ uchun $a_it_0=b_i$ — roʻyxatlar proporsional. $\\blacksquare$',
 's4.b2.name':      'Engel shakli (kasrlar lemmasi)',
 's4.b2.text':      'Haqiqiy $x_i$ va **musbat** $p_i$ lar uchun $$\\frac{x_1^{2}}{p_1}+\\frac{x_2^{2}}{p_2}+\\dots+\\frac{x_n^{2}}{p_n}\\ \\ge\\ \\frac{\\left(x_1+x_2+\\dots+x_n\\right)^{2}}{p_1+p_2+\\dots+p_n}.$$',
 's4.b3.text':      'Avval $n=2$ holi. Bizga $$\\frac{x^{2}}{p}+\\frac{y^{2}}{q}\\ \\ge\\ \\frac{(x+y)^{2}}{p+q}$$ kerak. Ikkala tomonni musbat $pq(p+q)$ songa koʻpaytiramiz: $$x^{2}q(p+q)+y^{2}p(p+q)\\ \\ge\\ pq(x+y)^{2}.$$ Ochamiz va hamma narsani chapga oʻtkazamiz: $$x^{2}pq+x^{2}q^{2}+y^{2}p^{2}+y^{2}pq-pqx^{2}-2pqxy-pqy^{2}=x^{2}q^{2}-2pqxy+y^{2}p^{2}=(xq-yp)^{2}\\ \\ge\\ 0 .$$\\n\\nUmumiy hol induksiya bilan chiqadi: ikki hadli holni dastlabki ikkita kasrni birlashtirish uchun qoʻllang, soʻng natijani uchinchisi bilan birlashtiring va hokazo. $\\blacksquare$',
 's4.b4.q':         'Musbat $a,b,c$ uchun $$\\frac{a}{b+c}+\\frac{b}{c+a}+\\frac{c}{a+b}\\ \\ge\\ \\frac32$$ ekanini isbotlang.',
 's4.b4.steps.0':   'Har bir kasrni $\\tfrac{a}{a}$ ga koʻpaytiramiz, shunda suratda kvadrat paydo boʻladi: $$\\frac{a}{b+c}=\\frac{a^{2}}{a(b+c)} .$$',
 's4.b4.steps.1':   'Engel shaklini qoʻllaymiz: $$\\sum\\frac{a^{2}}{a(b+c)}\\ \\ge\\ \\frac{(a+b+c)^{2}}{a(b+c)+b(c+a)+c(a+b)} .$$',
 's4.b4.steps.2':   'Maxraj $2(ab+bc+ca)$ ga teng.',
 's4.b4.steps.3':   '$(a+b+c)^{2}\\ge3(ab+bc+ca)$ ni tekshirish qoladi: ochsak, bu $a^{2}+b^{2}+c^{2}\\ge ab+bc+ca$, u esa allaqachon isbotlangan.',
 's4.b4.steps.4':   'Shuning uchun $$\\frac{(a+b+c)^{2}}{2(ab+bc+ca)}\\ \\ge\\ \\frac{3(ab+bc+ca)}{2(ab+bc+ca)}=\\frac32 .$$',
 's4.b4.ans':       'Nesbitt tengsizligi isbotlandi; tenglik $a=b=c$ da. $\\blacksquare$',
 's4.b5.text':      '**Koshi–Bunyakovskiyning diskriminant orqali isboti.** $t$ oʻzgaruvchiga nisbatan kvadrat uchhadni koʻramiz: $$P(t)=\\sum_{i=1}^{n}\\left(a_it-b_i\\right)^{2}=\\left(\\sum a_i^{2}\\right)t^{2}-2\\left(\\sum a_ib_i\\right)t+\\left(\\sum b_i^{2}\\right).$$\\n\\nKvadratlar yigʻindisi boʻlgani uchun har bir haqiqiy $t$ da $P(t)\\ge0$. Agar bosh koeffitsiyent $\\sum a_i^{2}$ nolga teng boʻlsa, barcha $a_i=0$ va isbotlashga hech narsa yoʻq. Aks holda parabola oʻqdan pastga tushmaydi, demak uning diskriminanti musbat emas: $$4\\left(\\sum a_ib_i\\right)^{2}-4\\left(\\sum a_i^{2}\\right)\\left(\\sum b_i^{2}\\right)\\ \\le\\ 0 ,$$ yaʼni $$\\left(\\sum a_ib_i\\right)^{2}\\ \\le\\ \\left(\\sum a_i^{2}\\right)\\left(\\sum b_i^{2}\\right) \\quad\\checkmark$$\\n\\nTenglik diskriminant nolga aylanishini bildiradi, demak biror $t_0$ uchun $P(t_0)=0$, shuning uchun barcha $i$ uchun $b_i=t_0a_i$ — ikkala roʻyxat proporsional ✓ $\\blacksquare$',
 's4.b6.name':      'Lagranj ayniyati',
 's4.b7.text':      'Lagranj ayniyati Koshi–Bunyakovskiyni bir zumda beradi: oʻng tomon kvadratlar yigʻindisi, demak manfiy emas. Bundan ham yaxshisi, u **zaxiraning aniq kattaligini** koʻrsatadi, tenglik esa barcha juftliklar uchun $a_ib_j=a_jb_i$, yaʼni proporsionallik sifatida oʻqiladi. $n=2$ da bu tanish ayniyat: $$\\left(a^{2}+b^{2}\\right)\\left(c^{2}+d^{2}\\right)=\\left(ac+bd\\right)^{2}+\\left(ad-bc\\right)^{2}.$$',
 's4.b8.text':      '**Engel shaklining isboti.** Ikkita kasrni koʻrish yetarli; qolganini induksiya qiladi.\\n\\n$x,y\\in\\mathbb{R}$ va $p,q>0$ uchun tasdiq: $$\\frac{x^{2}}{p}+\\frac{y^{2}}{q}\\ \\ge\\ \\frac{\\left(x+y\\right)^{2}}{p+q}.$$ Musbat $pq\\left(p+q\\right)$ songa koʻpaytiramiz: $$qx^{2}\\left(p+q\\right)+py^{2}\\left(p+q\\right)\\ \\ge\\ pq\\left(x+y\\right)^{2}.$$ Ochamiz va umumiy $pqx^{2}+pqy^{2}$ ni qisqartiramiz: chap tomonda $q^{2}x^{2}+p^{2}y^{2}$, oʻngda $2pqxy$ qoladi. Bu esa $$\\left(qx-py\\right)^{2}\\ \\ge\\ 0 \\quad\\checkmark$$\\n\\n**Induksiya.** $n$ ta kasr uchun dastlabki ikkitasini yuqoridagidek birlashtiring, $n-1$ ta kasr qoladi, va takrorlang. Har bir qadamda tenglik uchun $\\dfrac{x}{p}=\\dfrac{y}{q}$ kerak, demak umumiy holda tenglik $$\\frac{x_1}{p_1}=\\frac{x_2}{p_2}=\\dots=\\frac{x_n}{p_n} \\quad\\checkmark\\qquad\\blacksquare$$ ga teng kuchli.',
 's5.b0.text':      'Keyingi tengsizlik maktab darsliklarida deyarli uchramaydi, ammo olimpiadalarda u kalit kabi ishlaydi: u bir xil tartiblangan roʻyxatlar nega «doʻstlashishini», qarama-qarshi tartiblanganlari esa nega «janjallashishini» tushuntiradi.',
 's5.b1.name':      'Qayta tartiblash tengsizligi',
 's5.b1.text':      '$a_1\\le a_2\\le\\dots\\le a_n$ va $b_1\\le b_2\\le\\dots\\le b_n$ — haqiqiy sonlarning ikkita tartiblangan roʻyxati, $\\sigma$ esa indekslarning istalgan oʻrin almashtirishi boʻlsin. U holda $$\\underbrace{a_1b_n+a_2b_{n-1}+\\dots+a_nb_1}_{\\text{teskari tartib}}\\ \\le\\ \\sum_{i=1}^{n}a_ib_{\\sigma(i)}\\ \\le\\ \\underbrace{a_1b_1+a_2b_2+\\dots+a_nb_n}_{\\text{bir xil tartib}}.$$',
 's5.b2.text':      'Yuqori bahoni isbotlaymiz; quyidagisi $b_i$ ni $-b_i$ bilan almashtirish orqali chiqadi.\\n\\nOʻrin almashtirishlar chekli sonda, demak $S(\\sigma)=\\sum a_ib_{\\sigma(i)}$ biror $\\sigma$ da maksimumga erishadi. Shunday $\\sigma$ ni olamiz va u tartiblangan tartib **emas** deb faraz qilamiz. U holda $\\sigma(i)>\\sigma(j)$ boʻlgan $i<j$ indekslar bor, yaʼni $$b_{\\sigma(i)}\\ge b_{\\sigma(j)}\\quad\\text{va shu bilan birga}\\quad a_i\\le a_j .$$\\n\\nIkkala qiymatni almashtiramiz: $\\tau$ $\\sigma$ bilan $\\tau(i)=\\sigma(j)$, $\\tau(j)=\\sigma(i)$ dan tashqari mos tushsin. Yigʻindilar ayirmasi $$S(\\tau)-S(\\sigma)=\\left(a_j-a_i\\right)\\left(b_{\\sigma(i)}-b_{\\sigma(j)}\\right)\\ \\ge\\ 0 ,$$ chunki ikkala koʻpaytuvchi ham manfiy emas.\\n\\nDemak $\\tau$ yomonroq emas, u esa tartiblangan tartibga yaqinroq (inversiyalar soni bittaga kamaydi). Bunday almashtirishlarni chekli marta takrorlab, yigʻindini hech qachon kamaytirmasdan tartiblangan tartibga yetamiz ✓ $\\blacksquare$',
 's5.b3.q':         'Musbat $a,b,c$ uchun $$\\frac{a}{b}+\\frac{b}{c}+\\frac{c}{a}\\ \\ge\\ 3$$ ekanini isbotlang.',
 's5.b3.steps.0':   'Umumiylikni buzmagan holda $a\\ge b\\ge c>0$ deb faraz qilamiz.',
 's5.b3.steps.1':   '$\\left(a,b,c\\right)$ va $\\left(\\dfrac1c,\\dfrac1b,\\dfrac1a\\right)$ roʻyxatlarini olamiz: ular bir xil tartiblangan, chunki $a\\ge b\\ge c$ dan $\\dfrac1c\\ge\\dfrac1b\\ge\\dfrac1a$.',
 's5.b3.steps.2':   'Tartiblangan juftlash $\\dfrac{a}{c}+1+\\dfrac{c}{a}$ ni beradi; boshqa har qanday juftlash, jumladan bizning yigʻindimiz, undan katta emas — demak qayta tartiblash yigʻindini yuqoridan chegaralaydi, quyidan emas.',
 's5.b3.steps.3':   'Toza yoʻl — tengsizlikni bevosita qoʻllash: $$\\frac{a}{b}+\\frac{b}{c}+\\frac{c}{a}\\ \\ge\\ 3\\sqrt[3]{\\frac{a}{b}\\cdot\\frac{b}{c}\\cdot\\frac{c}{a}}=3\\sqrt[3]{1}=3 .$$',
 's5.b3.steps.4':   'Tenglik $\\dfrac{a}{b}=\\dfrac{b}{c}=\\dfrac{c}{a}$, yaʼni $a=b=c$ da ✓',
 's5.b3.ans':       '$\\ge3$, tenglik $a=b=c$ da.',
 's5.b4.text':      'Uchinchi qadamga eʼtibor bering: qayta tartiblash aralashtirilgan yigʻindini **yuqoridan** chegaralaydi, bizga esa quyidan baho kerak edi. Qurolga havola qilishdan oldin har doim u qaysi tomonga ishlashini tekshiring.',
 's5.b5.name':      'Chebishyovning yigʻindilar tengsizligi',
 's5.b5.text':      'Agar $a_1\\le\\dots\\le a_n$ va $b_1\\le\\dots\\le b_n$ (bir xil tartiblangan) boʻlsa, u holda $$\\frac1n\\sum_{i=1}^{n}a_ib_i\\ \\ge\\ \\left(\\frac1n\\sum_{i=1}^{n}a_i\\right)\\left(\\frac1n\\sum_{i=1}^{n}b_i\\right).$$ Qarama-qarshi tartiblangan roʻyxatlar uchun tengsizlik ishorasi almashadi.',
 's5.b6.text':      'Oldingi teorema beradigan $n$ ta tengsizlikni yozamiz — ikkinchi roʻyxatning har bir siklik siljishi uchun bittadan: $$\\begin{aligned} a_1b_1+\\dots+a_nb_n&\\ \\ge\\ a_1b_1+a_2b_2+\\dots+a_nb_n,\\\\ a_1b_1+\\dots+a_nb_n&\\ \\ge\\ a_1b_2+a_2b_3+\\dots+a_nb_1,\\\\ &\\ \\ \\vdots\\\\ a_1b_1+\\dots+a_nb_n&\\ \\ge\\ a_1b_n+a_2b_1+\\dots+a_nb_{n-1}. \\end{aligned}$$\\n\\nBarcha $n$ ta satrni qoʻshamiz. Chap tomon $n\\sum a_ib_i$ boʻladi. Oʻngda har bir $a_ib_j$ koʻpaytma roppa-rosa bir marta uchraydi (siljishlar barcha juftliklardan bir martadan oʻtadi), demak oʻng tomon $$\\left(\\sum_i a_i\\right)\\left(\\sum_j b_j\\right)$$ ga teng.\\n\\nDemak $n\\sum a_ib_i\\ \\ge\\ \\left(\\sum a_i\\right)\\left(\\sum b_i\\right)$; $n^{2}$ ga boʻlamiz ✓ $\\blacksquare$',
 's5.b7.q':         'Musbat $a,b,c$ uchun $$\\frac{a^{3}+b^{3}+c^{3}}{3}\\ \\ge\\ \\frac{a+b+c}{3}\\cdot\\frac{a^{2}+b^{2}+c^{2}}{3}$$ ekanini isbotlang.',
 's5.b7.steps.0':   '$a\\le b\\le c$ deb faraz qilamiz (tasdiq simmetrik).',
 's5.b7.steps.1':   'U holda $(a,b,c)$ va $(a^{2},b^{2},c^{2})$ bir xil tartiblangan: kvadratga koʻtarish musbat sonlarning tartibini saqlaydi.',
 's5.b7.steps.2':   'Chebishyov $$\\frac{a\\cdot a^{2}+b\\cdot b^{2}+c\\cdot c^{2}}{3}\\ \\ge\\ \\frac{a+b+c}{3}\\cdot\\frac{a^{2}+b^{2}+c^{2}}{3}$$ ni beradi.',
 's5.b7.steps.3':   'Chap tomon $\\dfrac{a^{3}+b^{3}+c^{3}}{3}$ ✓ Tenglik $a=b=c$ da.',
 's5.b7.ans':       'Chebishyovni $(a,b,c)$ va $(a^{2},b^{2},c^{2})$ ga bevosita qoʻllash.',
 's5.b8.text':      '**Chebishyov masalasini tanish.** Bir tomonda ikkita yigʻindining koʻpaytmasi, ikkinchisida esa birga oʻsadigan kattaliklar koʻpaytmalarining yigʻindisi paydo boʻladi. Odatdagi belgilar: bitta ifodada $a^{k}$ va $a^{m}$ darajalari, yoki surati toʻldiruvchi maxraji kichrayganda oʻsadigan $\\dfrac{a}{b+c}$ kasrlari.',
 's6.b0.text':      'Oʻrtalar orasidagi har bir tengsizlik bitta geometrik faktning xususiy holi: **qavariq funksiya grafigining vatari grafikdan pastda yotmaydi**. Buni koʻrish alohida formulalar uyumini bitta gʻoyaga aylantiradi.',
 's6.b1.name':      'Qavariq funksiya',
 's6.b1.text':      '$I$ oraliqda aniqlangan $f$ funksiya, agar barcha $x,y\\in I$ va har bir $\\lambda\\in[0,1]$ uchun $$f\\left(\\lambda x+(1-\\lambda)y\\right)\\ \\le\\ \\lambda f(x)+(1-\\lambda)f(y)$$ boʻlsa, **qavariq** deyiladi. Agar $x\\ne y$ va $0<\\lambda<1$ da tengsizlik qatʼiy boʻlsa, funksiya **qatʼiy qavariq** deyiladi. Ishora teskari boʻlganda funksiya **botiq** deyiladi.',
 's6.b2.text':      'Geometrik maʼnoda: $\\lambda x+(1-\\lambda)y$ nuqtasi $x$ dan $y$ gacha kesmadan oʻtadi, chap tomon — grafikning oʻsha yerdagi balandligi, oʻng tomon — vatarning balandligi. Qavariqlik grafik vatar ostiga botishini bildiradi.\\n\\nAgar $f$ ikki marta differensiallanuvchi boʻlsa, mezon oddiy: $f$ $I$ da qavariq ⟺ u yerda $f^{\\prime\\prime}(x)\\ge0$. Demak $x^{2}$, $e^{x}$, $-\\ln x$ va $\\dfrac1x$ ($x>0$ da) qavariq, $\\ln x$, $\\sqrt{x}$ va $\\sin x$ ($[0,\\pi]$ da) esa botiq.',
 's6.b3.cap':       'Qavariq funksiya: vatar grafikdan yuqorida yotadi, shuning uchun qiymatlarning oʻrtasi oʻrtadagi qiymatdan kam emas.',
 's6.b4.name':      'Yensen tengsizligi',
 's6.b4.text':      '$f$ $I$ da qavariq, $x_1,\\dots,x_n\\in I$ va $w_1,\\dots,w_n\\ge0$ yigʻindisi $1$ boʻlsin. U holda $$f\\left(\\sum_{i=1}^{n}w_ix_i\\right)\\ \\le\\ \\sum_{i=1}^{n}w_if(x_i).$$ Teng vaznlar $w_i=\\frac1n$ da bu $$f\\left(\\frac{x_1+\\dots+x_n}{n}\\right)\\ \\le\\ \\frac{f(x_1)+\\dots+f(x_n)}{n}$$ koʻrinishini oladi. Botiq $f$ uchun ikkala ishora ham almashadi.',
 's6.b5.text':      '$n$ boʻyicha induksiya.\\n\\n**Baza $n=2$** — bu aynan qavariqlik taʼrifi ✓\\n\\n**Qadam.** Tasdiq $n-1$ nuqta uchun oʻrinli boʻlsin. Vaznlari $w_i$ boʻlgan $n$ ta nuqtani olamiz; $w_n<1$ deb faraz qilishimiz mumkin (aks holda hammasi trivial). $W=w_1+\\dots+w_{n-1}=1-w_n>0$ va $$z=\\frac{w_1x_1+\\dots+w_{n-1}x_{n-1}}{W}\\in I$$ deb olamiz, u $I$ nuqtalarining vaznli oʻrtasi sifatida $I$ da yotadi.\\n\\nU holda $\\sum_{i=1}^{n}w_ix_i=Wz+w_nx_n$, ikki nuqtali taʼrif esa $$f\\left(Wz+w_nx_n\\right)\\ \\le\\ W f(z)+w_nf(x_n)$$ ni beradi.\\n\\nYigʻindisi $1$ boʻlgan $\\dfrac{w_i}{W}$ vaznlar bilan $f(z)$ ga induksiya farazini qoʻllaymiz: $$f(z)\\ \\le\\ \\sum_{i=1}^{n-1}\\frac{w_i}{W}f(x_i).$$\\n\\nOʻrniga qoʻysak, $$f\\left(\\sum w_ix_i\\right)\\le W\\sum_{i=1}^{n-1}\\frac{w_i}{W}f(x_i)+w_nf(x_n)=\\sum_{i=1}^{n}w_if(x_i) \\quad\\checkmark\\qquad\\blacksquare$$\\n\\n$f$ qatʼiy qavariq boʻlganda tenglik nolga teng boʻlmagan vaznli barcha $x_i$ larning ustma-ust tushishini majbur qiladi.',
 's6.b6.q':         'Yensen tengsizligidan $\\dfrac{a_1+\\dots+a_n}{n}\\ge\\sqrt[n]{a_1\\cdots a_n}$ tengsizligini keltirib chiqaring.',
 's6.b6.steps.0':   '$(0,+\\infty)$ da $f(x)=\\ln x$ ni olamiz. U **botiq**: $f^{\\prime\\prime}(x)=-\\dfrac1{x^{2}}<0$.',
 's6.b6.steps.1':   'Botiq funksiya uchun teng vaznli Yensen: $$\\ln\\!\\left(\\frac{a_1+\\dots+a_n}{n}\\right)\\ \\ge\\ \\frac{\\ln a_1+\\dots+\\ln a_n}{n}.$$',
 's6.b6.steps.2':   'Logarifm xossalariga koʻra oʻng tomon $\\ln\\sqrt[n]{a_1\\cdots a_n}$ ga teng.',
 's6.b6.steps.3':   'Logarifm qatʼiy oʻsuvchi, demak $\\ln A\\ge\\ln G$ dan $A\\ge G$ ✓',
 's6.b6.steps.4':   'Qatʼiy botiqlik tenglikni faqat $a_1=\\dots=a_n$ da mumkin qiladi.',
 's6.b6.ans':       '$\\ln x$ uchun Yensen — bu aynan $A\\ge G$.',
 's6.b7.q':         'Uchburchakda $\\sin A+\\sin B+\\sin C\\le\\dfrac{3\\sqrt3}{2}$ ekanini isbotlang.',
 's6.b7.steps.0':   'Burchaklar $(0,\\pi)$ da yotadi, u yerda $\\sin$ botiq: $(\\sin x)^{\\prime\\prime}=-\\sin x\\le0$.',
 's6.b7.steps.1':   'Botiq funksiya uchun Yensen: $$\\frac{\\sin A+\\sin B+\\sin C}{3}\\ \\le\\ \\sin\\!\\left(\\frac{A+B+C}{3}\\right).$$',
 's6.b7.steps.2':   'Uchburchakda $A+B+C=\\pi$, demak oʻng tomon $\\sin\\dfrac{\\pi}{3}=\\dfrac{\\sqrt3}{2}$.',
 's6.b7.steps.3':   '$3$ ga koʻpaytiramiz: yigʻindi $\\dfrac{3\\sqrt3}{2}$ dan oshmaydi ✓ Tenglik teng tomonli uchburchakda.',
 's6.b7.ans':       '$\\le\\dfrac{3\\sqrt3}{2}$, tenglik $A=B=C=60^{\\circ}$ da.',
 's6.b8.name':      'Urinma orqali baholash',
 's6.b8.text':      'Agar $f$ $I$ da qavariq va differensiallanuvchi boʻlsa, uning grafigi **har bir urinmadan pastda yotmaydi**: $$f(x)\\ \\ge\\ f(t)+f^{\\prime}(t)\\left(x-t\\right)\\qquad\\text{barcha }x,t\\in I \\text{ uchun}.$$',
 's6.b9.text':      'Bu butun mavzudagi eng amaliy usul. Aytaylik, $\\sum x_i=S$ sharti ostida $\\sum f(x_i)\\ge C$ ni isbotlash kerak. Tenglik nuqtasini $t=\\dfrac{S}{n}$ deb taxmin qiling, oʻsha yerda urinma oʻtkazing va oddiy algebra bilan nuqtaviy bahoni $$f(x)\\ \\ge\\ \\alpha x+\\beta$$ isbotlang. Uni $i$ boʻyicha yigʻsak $\\sum f(x_i)\\ge\\alpha S+n\\beta$ chiqadi va masala bir qatorda tugaydi.',
 's7.b0.name':      '1-usul: tenglik nuqtasini taxmin qiling',
 's7.b0.text':      'Biror narsani isbotlashdan oldin tenglik qayerda erishilishini toping. Odatda bu $a=b=c$ yoki shartdan kelib chiqadigan qiymatlar. Tenglik nuqtasi **qaysi** tengsizlikni ishlatish kerakligini aytadi: har bir oraliq qadam xuddi shu nuqtada tenglikka aylanishi kerak, aks holda baho juda kuchsiz boʻladi.',
 's7.b1.name':      '2-usul: shartni sarflang',
 's7.b1.text':      '$abc=1$ yoki $a+b+c=1$ kabi shart bezak emas, qurol. $a+b+c=1$ sharti istalgan joyda $1$ ni $a+b+c$ bilan — va aksincha — almashtirishga imkon beradi. $abc=1$ sharti esa $\\tfrac1a=bc$ deb yozishga imkon beradi.',
 's7.b2.name':      '3-usul: parallel tengsizliklarni qoʻshing',
 's7.b2.text':      'Simmetrik tengsizlik koʻpincha uchta bir xil boʻlakka ajraladi. $a^{2}+b^{2}\\ge2ab$, $b^{2}+c^{2}\\ge2bc$, $c^{2}+a^{2}\\ge2ca$ ni qoʻshsak $2(a^{2}+b^{2}+c^{2})\\ge2(ab+bc+ca)$ chiqadi — birinchi boʻlimdagi tengsizlik, bir qatorda.',
 's7.b3.q':         'Musbat $a,b,c$ uchun $(a+b)(b+c)(c+a)\\ge8abc$ ekanini isbotlang.',
 's7.b3.steps.0':   'Tenglikni $a=b=c$ da kutamiz — tekshiring: $2a\\cdot2a\\cdot2a=8a^{3}$ ✓',
 's7.b3.steps.1':   'Ikki son uchun tengsizlikka koʻra: $a+b\\ge2\\sqrt{ab}$, $b+c\\ge2\\sqrt{bc}$, $c+a\\ge2\\sqrt{ca}$.',
 's7.b3.steps.2':   'Barcha qismlar musbat, demak uchtasini koʻpaytirish mumkin: $$(a+b)(b+c)(c+a)\\ \\ge\\ 8\\sqrt{ab}\\cdot\\sqrt{bc}\\cdot\\sqrt{ca}=8\\sqrt{a^{2}b^{2}c^{2}}=8abc .$$',
 's7.b3.steps.3':   'Tenglik uchun bir vaqtda $a=b$, $b=c$ va $c=a$, yaʼni $a=b=c$ kerak.',
 's7.b3.ans':       'Isbotlandi; tenglik $a=b=c$ da. $\\blacksquare$',
 's7.b4.text':      'Tengsizliklarni **faqat barcha qismlar musbat boʻlgandagina** koʻpaytirish mumkin. $-5>-7$ va $2>1$ ni koʻpaytirsak $-10>-7$ chiqar edi, bu esa notoʻgʻri. Olimpiada masalalarida deyarli har doim «musbat $a,b,c$ uchun» deyiladi, ammo «barcha qismlar musbat, demak koʻpaytirishimiz mumkin» deb yozing — bu ballga arzigulik qator.',
 's8.b0.text':      'Quyidagi usullar olimpiada tengsizligining ishonchli yechimini uzoq qidiruvdan ajratadi. Har birini bir marta oxirigacha koʻrib chiqishga arziydi; keyin siz ularni bir zumda tanib olasiz.',
 's8.b1.name':      'SOS (kvadratlar yigʻindisi) usuli',
 's8.b1.text':      'Uch oʻzgaruvchili koʻp simmetrik tengsizlikni $$S_a\\left(b-c\\right)^{2}+S_b\\left(c-a\\right)^{2}+S_c\\left(a-b\\right)^{2}\\ \\ge\\ 0$$ koʻrinishiga keltirish mumkin, bunda $S_a,S_b,S_c$ — $a,b,c$ ga bogʻliq ifodalar. Agar uchala koeffitsiyent ham manfiy boʻlmasa, tengsizlik isbotlangan.',
 's8.b2.q':         '$a^{2}+b^{2}+c^{2}\\ge ab+bc+ca$ ekanini isbotlang va zaxiraning aniq kattaligini aniqlang.',
 's8.b2.steps.0':   '$2$ ga koʻpaytiramiz va hamma narsani chapga oʻtkazamiz: $$2a^{2}+2b^{2}+2c^{2}-2ab-2bc-2ca\\ \\ge\\ 0 .$$',
 's8.b2.steps.1':   'Juftlab guruhlaymiz: $$\\left(a^{2}-2ab+b^{2}\\right)+\\left(b^{2}-2bc+c^{2}\\right)+\\left(c^{2}-2ca+a^{2}\\right).$$',
 's8.b2.steps.2':   'Bu aynan $\\left(a-b\\right)^{2}+\\left(b-c\\right)^{2}+\\left(c-a\\right)^{2}\\ \\ge\\ 0$ ✓',
 's8.b2.steps.3':   'Demak zaxira $\\tfrac12\\left[\\left(a-b\\right)^{2}+\\left(b-c\\right)^{2}+\\left(c-a\\right)^{2}\\right]$ ga teng — bu $S_a=S_b=S_c=\\tfrac12$ boʻlgan SOS shakli.',
 's8.b2.ans':       'Zaxira $\\tfrac12\\sum\\left(a-b\\right)^{2}$ ga teng.',
 's8.b3.name':      'Shur tengsizligi',
 's8.b3.text':      'Manfiy boʻlmagan $a,b,c$ va istalgan $t>0$ uchun $$a^{t}\\left(a-b\\right)\\left(a-c\\right)+b^{t}\\left(b-a\\right)\\left(b-c\\right)+c^{t}\\left(c-a\\right)\\left(c-b\\right)\\ \\ge\\ 0 .$$ $t=1$ holi ochilganda $$a^{3}+b^{3}+c^{3}+3abc\\ \\ge\\ a^{2}b+a^{2}c+b^{2}a+b^{2}c+c^{2}a+c^{2}b$$ ni beradi.',
 's8.b4.text':      'Ifoda simmetrik, shuning uchun $a\\ge b\\ge c\\ge0$ deb faraz qilamiz. Dastlabki ikki hadni guruhlab $\\left(a-b\\right)$ ni chiqaramiz: $$a^{t}\\left(a-b\\right)\\left(a-c\\right)+b^{t}\\left(b-a\\right)\\left(b-c\\right)=\\left(a-b\\right)\\left[a^{t}\\left(a-c\\right)-b^{t}\\left(b-c\\right)\\right].$$\\n\\n$a\\ge b$ dan $a^{t}\\ge b^{t}$ va $a-c\\ge b-c\\ge0$, demak kvadrat qavs manfiy emas, $\\left(a-b\\right)\\ge0$ ham. Shuning uchun dastlabki ikki had birgalikda $\\ge0$.\\n\\nUchinchi had $c^{t}\\left(c-a\\right)\\left(c-b\\right)$; $\\left(c-a\\right)$ va $\\left(c-b\\right)$ koʻpaytuvchilarining ikkalasi ham musbat emas, demak ularning koʻpaytmasi manfiy emas va had $\\ge0$.\\n\\nIkkita manfiy boʻlmagan kattalikning yigʻindisi manfiy emas ✓ $\\blacksquare$',
 's8.b5.name':      'Ravi almashtirishi',
 's8.b5.text':      '$a,b,c$ sonlari uchburchak tomonlari boʻlishi uchun $$a=y+z,\\qquad b=z+x,\\qquad c=x+y$$ boʻladigan $x,y,z>0$ mavjud boʻlishi zarur va yetarli.',
 's8.b6.text':      '**Agar shunday $x,y,z$ mavjud boʻlsa,** $$b+c=\\left(z+x\\right)+\\left(x+y\\right)=a+2x>a ,$$ qolgan ikkita uchburchak tengsizligi uchun ham shunday ✓\\n\\n**Aksincha,** agar $a,b,c$ uchburchak tomonlari boʻlsa, $$x=\\frac{b+c-a}{2},\\qquad y=\\frac{c+a-b}{2},\\qquad z=\\frac{a+b-c}{2}$$ deb olamiz. Uchalasi ham aynan uchburchak tengsizliklari tufayli musbat, bevosita tekshirish esa $y+z=a$, $z+x=b$, $x+y=c$ ni beradi ✓ $\\blacksquare$\\n\\n(Geometrik maʼnoda $x,y,z$ — uchlardan ichki chizilgan aylanaga urinma kesmalar.)',
 's8.b7.text':      'Ravi almashtirishi **uchburchak shartini olib tashlaydi**: noqulay «$a,b,c$ — uchburchak tomonlari» sharti qulay «$x,y,z>0$» ga aylanadi, shundan keyin odatdagi oʻrta qiymatlar va Koshi–Bunyakovskiy tengsizliklari ishlaydi.',
 's8.b8.q':         '$a,b,c$ — uchburchak tomonlari boʻlsin. $$a^{2}+b^{2}+c^{2}\\ <\\ 2\\left(ab+bc+ca\\right)$$ ekanini isbotlang.',
 's8.b8.steps.0':   '$x,y,z>0$ bilan $a=y+z$, $b=z+x$, $c=x+y$ qoʻyamiz.',
 's8.b8.steps.1':   'Chap tomon: $$\\sum\\left(y+z\\right)^{2}=2\\left(x^{2}+y^{2}+z^{2}\\right)+2\\left(xy+yz+zx\\right).$$',
 's8.b8.steps.2':   'Oʻng tomon: $ab+bc+ca=\\left(x^{2}+y^{2}+z^{2}\\right)+3\\left(xy+yz+zx\\right)$, demak uning ikki barobari $2\\left(x^{2}+y^{2}+z^{2}\\right)+6\\left(xy+yz+zx\\right)$.',
 's8.b8.steps.3':   'Ayirma $4\\left(xy+yz+zx\\right)>0$, chunki $x,y,z>0$ ✓',
 's8.b8.steps.4':   'Tengsizlik qatʼiy: $x,y,z>0$ sharti aynigan uchburchaklarni istisno qiladi.',
 's8.b8.ans':       'Zaxira $4\\left(xy+yz+zx\\right)>0$ ga teng.',
 's8.b9.name':      'Bir jinslilashtirish va normallashtirish',
 's8.b9.text':      'Agar $\\left(a,b,c\\right)$ ni $\\left(ta,tb,tc\\right)$ bilan almashtirish ikkala tomonni ham $t^{d}$ ga koʻpaytirsa, tengsizlik **$d$-darajali bir jinsli** deyiladi. Bir jinsli tengsizlikni $a+b+c=3$ yoki $abc=1$ kabi istalgan qulay qoʻshimcha shart ostida isbotlash mumkin: masshtablash umumiy holni shunga keltiradi.\\n\\nAksincha, agar shart $a+b+c=1$ boʻlib, tengsizlik bir jinsli boʻlmasa, hadlarni $\\left(a+b+c\\right)$ ning mos darajalariga koʻpaytirib uni **bir jinslilashtirish** mumkin.',
 's8.b10.text':     '**Myurxed tengsizligi.** Bir hadlarning simmetrik yigʻindilari uchun umumiy mezon bor: agar $\\left(p_1,\\dots,p_n\\right)$ koʻrsatkichlar ketma-ketligi $\\left(q_1,\\dots,q_n\\right)$ ni mayoratsiya qilsa (kamayish tartibida saralanganda birinchisining qismiy yigʻindilari ikkinchisinikidan kam emas, toʻliq yigʻindilari esa teng), u holda mos simmetrik yigʻindi ham kam emas. Shunday qilib $\\sum_{\\text{sym}}a^{3}\\ \\ge\\ \\sum_{\\text{sym}}a^{2}b\\ \\ge\\ \\sum_{\\text{sym}}abc$. Olimpiadada Myurxedga havolani bevosita oʻrta qiymatlar mulohazasi bilan mustahkamlagan maʼqul.',
 's8.b11.head.0':   'Nima koʻrinadi',
 's8.b11.head.1':   'Nimani sinash kerak',
 's8.b11.rows.0.0': '$\\frac{x_i^{2}}{y_i}$ kasrlar yigʻindisi',
 's8.b11.rows.0.1': 'Koshi, Engel shaklida',
 's8.b11.rows.1.0': 'qatʼiy koʻpaytma yoki qatʼiy yigʻindi',
 's8.b11.rows.1.1': 'oʻrta qiymatlar, normallashtirish',
 's8.b11.rows.2.0': 'simmetriya, tenglik $a=b=c$ da',
 's8.b11.rows.2.1': 'SOS, Shur',
 's8.b11.rows.3.0': '$a,b,c$ — uchburchak tomonlari',
 's8.b11.rows.3.1': 'Ravi almashtirishi',
 's8.b11.rows.4.0': 'har bir oʻzgaruvchidan bitta funksiya',
 's8.b11.rows.4.1': 'Yensen yoki urinma',
 's8.b11.rows.5.0': 'bir xil tartiblangan ikkita yigʻindi',
 's8.b11.rows.5.1': 'Chebishyov, qayta tartiblash',
 's8.b11.rows.6.0': 'bitta oʻzgaruvchining turli darajalari',
 's8.b11.rows.6.1': 'darajali oʻrtalar',
}
