# -*- coding: utf-8 -*-
"""Uzbek for topic 3.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Qoldiqlar arifmetikasi',
 'sub':             'Taqqoslamalar ogʻir hisoblarni qisqartiradi: oxirgi raqamlar, darajalar sikli va Ferma kichik teoremasi.',
 'goals.0':         '$a\\equiv b\\pmod m$ belgisini tushunish va taqqoslamalarni erkin qoʻshish, ayirish, koʻpaytirish.',
 'goals.1':         'Taqqoslamani shunchaki boʻlib boʻlmasligini bilish va bu qiyinchilikni qanday aylanib oʻtishni bilish.',
 'goals.2':         'Sikllar yordamida katta darajalarning oxirgi raqamlarini topish.',
 'goals.3':         'Ferma kichik teoremasini qoʻllash va modulni ongli ravishda tanlash.',
 's0.h':            'Taqqoslamalar',
 's1.h':            'Chiziqli taqqoslamalar va teskari elementlar',
 's2.h':            'Oxirgi raqamlar va darajalar sikli',
 's3.h':            'Ferma kichik teoremasi',
 's4.h':            'Xitoy qoldiqlar teoremasi',
 's5.h':            'Qoldiqning tartibi: darajalar nega takrorlanadi',
 's6.h':            'Tub modul boʻyicha kvadratlar',
 's7.h':            'Modulni tanlash',
 's0.b0.name':      'Modul $m$ boʻyicha taqqoslama',
 's0.b0.text':      '$m>0$ butun son boʻlsin. Agar $m\\mid(a-b)$ boʻlsa — yaʼni $a$ va $b$ ni $m$ ga boʻlganda bir xil qoldiq qolsa — $$a\\equiv b \\pmod m$$ deb yozamiz va «$a$ modul $m$ boʻyicha $b$ ga taqqoslanadi» deymiz.',
 's0.b1.text':      'Misollar: $17\\equiv2\\pmod5$, $-3\\equiv4\\pmod 7$, $100\\equiv0\\pmod{25}$. Taqqoslama — «menga faqat qoldiq muhim» deyishning usuli, aynan shuning uchun u juda qulay.',
 's0.b2.name':      'Taqqoslamalar bilan nima qilish mumkin',
 's0.b2.text':      'Agar modul $m$ boʻyicha $a\\equiv b$ va $c\\equiv d$ boʻlsa, u holda $$a+c\\equiv b+d,\\qquad a-c\\equiv b-d,\\qquad ac\\equiv bd \\pmod m,$$ demak har bir musbat butun $k$ uchun $a^{k}\\equiv b^{k}\\pmod m$.',
 's0.b3.text':      'Shartga koʻra $m\\mid a-b$ va $m\\mid c-d$. U holda $m$ soni $(a-b)+(c-d)=(a+c)-(b+d)$ yigʻindini boʻladi — bu birinchi tasdiq; ayirma ham shunday. Koʻpaytma uchun $$ac-bd=ac-bc+bc-bd=c(a-b)+b(c-d)$$ deb yozamiz, ikkala had ham $m$ ga boʻlinadi. Darajalar koʻpaytma qoidasini takror qoʻllash bilan chiqadi. $\\blacksquare$',
 's0.b4.text':      '**Taqqoslamani boʻlish mumkin emas.** $6\\equiv 0\\pmod 6$ va $2\\not\\equiv0\\pmod 6$ dan koʻrinadiki, $2\\cdot3\\equiv2\\cdot0$ dan $3\\equiv0$ kelib chiqmaydi. $c$ ni qisqartirish faqat $\\gcd(c,m)=1$ boʻlgandagina mumkin; u holda $ca\\equiv cb$ haqiqatan $a\\equiv b$ ni beradi.',
 's0.b5.q':         '$2^{100}$ ni $7$ ga boʻlgandagi qoldiqni toping.',
 's0.b5.steps.0':   '$2^3=8\\equiv1\\pmod 7$ — qisqa sikl.',
 's0.b5.steps.1':   '$100=3\\cdot33+1$, demak $2^{100}=\\left(2^{3}\\right)^{33}\\cdot2$.',
 's0.b5.steps.2':   '$\\left(2^{3}\\right)^{33}\\equiv1^{33}=1$, demak $2^{100}\\equiv2\\pmod 7$.',
 's0.b5.ans':       'Qoldiq $2$ ga teng',
 's0.b6.name':      'Taqqoslamalar arifmetikaga boʻysunadi',
 's0.b6.text':      'Agar modul $m$ boʻyicha $a\\equiv b$ va $c\\equiv d$ boʻlsa, u holda $$a+c\\equiv b+d,\\qquad a-c\\equiv b-d,\\qquad ac\\equiv bd\\pmod m .$$ Demak har bir musbat butun $n$ uchun $a^{n}\\equiv b^{n}$, umumiyroq aytganda, butun koeffitsiyentli istalgan $P$ koʻphad uchun $P(a)\\equiv P(b)$.',
 's0.b7.text':      'Taʼrifga koʻra $m\\mid a-b$ va $m\\mid c-d$.\\n\\n**Qoʻshish.** $$(a+c)-(b+d)=(a-b)+(c-d)$$ — $m$ ning ikkita karralisining yigʻindisi ✓ Ayirish ham shunday.\\n\\n**Koʻpaytirish.** Usul — ayirmani boʻlaklash: $$ac-bd=ac-bc+bc-bd=c(a-b)+b(c-d),$$ ikkala had ham $m$ ga karrali ✓\\n\\n**Darajalar.** Induksiya: $a^{n}\\equiv b^{n}$ va $a\\equiv b$ ni koʻpaytirsak $a^{n+1}\\equiv b^{n+1}$ ✓\\n\\n**Koʻphadlar.** Yuqoridagiga koʻra har bir $c_ka^{k}$ had $c_kb^{k}$ ga taqqoslanadi; ularni qoʻshamiz. $\\blacksquare$',
 's0.b8.text':      'Oxirgi nuqta taqqoslamalarni shunchalik kuchli qiladi: koʻphadga oid tasdiqni **barcha** butun sonlar uchun tekshirish oʻrniga $m$ ta qoldiq uchun tekshirish yetarli. Cheksiz ish chekliga aylanadi.',
 's1.b0.text':      'Modul $m$ boʻyicha qoʻshish va koʻpaytirish hal boʻldi. Ammo **boʻlish** nimani anglatadi? Javob — chiziqli taqqoslamalar nazariyasi, u esa $ax+by=c$ tenglamasi hikoyasini soʻzma-soʻz takrorlaydi.',
 's1.b1.name':      'Chiziqli taqqoslama qachon yechiladi',
 's1.b1.text':      '$d=\\gcd(a,m)$ boʻlsin. $$ax\\equiv b\\pmod m$$ taqqoslamasi yechimga ega boʻlishi uchun $d\\mid b$ boʻlishi **zarur va yetarli**. Bu holda uning modul $m$ boʻyicha roppa-rosa $d$ ta yechimi bor, ular modul $\\tfrac md$ boʻyicha bitta sinf tashkil qiladi.',
 's1.b2.text':      'Taʼrifga koʻra $ax\\equiv b\\pmod m$ degani $m\\mid ax-b$, yaʼni biror butun $y$ uchun $$ax-b=my\\quad\\Longleftrightarrow\\quad ax-my=b .$$\\n\\nBu butun sonlardagi chiziqli tenglama, u aynan $\\gcd(a,m)\\mid b$ boʻlganda yechiladi ✓\\n\\n**Yechimlar soni.** $x_0$ ulardan biri boʻlsin. Tenglamaning barcha yechimlari $$x=x_0+\\frac md\\,t,\\qquad t\\in\\mathbb{Z} .$$ Modul $m$ boʻyicha turlilari $t=0,1,\\dots,d-1$ dan chiqadi: undan nari qiymatlar takrorlanadi, chunki $d\\cdot\\tfrac md=m$ ga siljish hech narsani oʻzgartirmaydi.\\n\\nDemak roppa-rosa $d$ ta yechim bor, ularning hammasi bir-biriga modul $\\tfrac md$ boʻyicha taqqoslanadi. $\\blacksquare$',
 's1.b3.name':      'Modul boʻyicha teskari element',
 's1.b3.text':      'Agar $$a\\cdot a^{-1}\\equiv1\\pmod m$$ boʻlsa, $a^{-1}$ soni $a$ ning modul $m$ boʻyicha **teskari elementi** deyiladi.',
 's1.b4.name':      'Teskari element qachon mavjud',
 's1.b4.text':      '$a$ ning modul $m$ boʻyicha teskari elementi mavjud boʻlishi uchun $\\gcd(a,m)=1$ boʻlishi **zarur va yetarli**, u holda u modul $m$ boʻyicha yagona.',
 's1.b5.text':      '**Mavjudligi.** Bu oldingi teoremaning $b=1$ dagi xususiy holi: $ax\\equiv1$ taqqoslamasi aynan $\\gcd(a,m)\\mid1$, yaʼni $\\gcd(a,m)=1$ boʻlganda yechiladi.\\n\\n**Yagonaligi.** $au\\equiv1$ va $av\\equiv1$ boʻlsin. Birinchisini $v$ ga koʻpaytiramiz: $$v\\equiv v(au)=(av)u\\equiv u\\pmod m . \\qquad\\blacksquare$$',
 's1.b6.name':      'Qisqartirish qonuni',
 's1.b6.text':      'Agar $\\gcd(c,m)=1$ boʻlsa, $ca\\equiv cb\\pmod m$ dan $a\\equiv b\\pmod m$ kelib chiqadi. Umumiy holda $ca\\equiv cb\\pmod m$ faqat $$a\\equiv b\\ \\left(\\bmod\\ \\frac m{\\gcd(c,m)}\\right)$$ ni beradi.',
 's1.b7.text':      '$ca\\equiv cb$ sharti $m\\mid c(a-b)$ degani. $d=\\gcd(c,m)$ deb olamiz va $c=dc_1$, $m=dm_1$ deb yozamiz, bunda $\\gcd\\left(c_1,m_1\\right)=1$.\\n\\nU holda $dm_1\\mid dc_1(a-b)$, yaʼni $m_1\\mid c_1(a-b)$. $\\gcd\\left(c_1,m_1\\right)=1$ boʻlgani uchun $c_1$ koʻpaytuvchi tushib qoladi: $$m_1\\mid a-b ,$$ yaʼni $m_1=\\tfrac md$ bilan $a\\equiv b\\pmod{m_1}$.\\n\\n$d=1$ da bu $m_1=m$ ni, yaʼni birinchi tasdiqni beradi. $\\blacksquare$',
 's1.b8.text':      'Klassik tuzoq: $$6\\equiv16\\pmod{10} ,$$ ammo $2$ ni qisqartirish **mumkin emas**: $3\\not\\equiv8\\pmod{10}$. Modul kichrayishi kerak: $3\\equiv8\\pmod5$ ✓ Taqqoslamani «boʻlishdan» oldin har doim modul bilan EKUB ni tekshiring.',
 's1.b9.q':         '$14x\\equiv30\\pmod{100}$ ni yeching.',
 's1.b9.steps.0':   '$d=\\gcd(14,100)=2$ va $2\\mid30$, demak yechimlar bor — modul $100$ boʻyicha roppa-rosa $2$ ta.',
 's1.b9.steps.1':   'Butun taqqoslamani, moduli bilan birga, $2$ ga qisqartiramiz: $\\ 7x\\equiv15\\pmod{50}$.',
 's1.b9.steps.2':   'Endi $\\gcd(7,50)=1$, demak teskari element bor: $7\\cdot43=301=6\\cdot50+1$, shuning uchun $7^{-1}\\equiv43\\pmod{50}$.',
 's1.b9.steps.3':   'Koʻpaytiramiz: $x\\equiv43\\cdot15=645\\equiv45\\pmod{50}$.',
 's1.b9.steps.4':   'Modul $100$ boʻyicha bu ikkita yechim beradi: $x\\equiv45$ va $x\\equiv95$.',
 's1.b9.steps.5':   'Tekshirish: $14\\cdot45=630=6\\cdot100+30$ ✓ va $14\\cdot95=1330=13\\cdot100+30$ ✓',
 's1.b9.ans':       '$x\\equiv45$ va $x\\equiv95\\pmod{100}$.',
 's1.b10.text':     'Teskari elementni topishning ikki yoʻli bor: **Yevklid algoritmini teskari yurgizish** (har doim ishlaydi) yoki **Eyler teoremasi**: $$a^{-1}\\equiv a^{\\varphi(m)-1}\\pmod m ,$$ chunki $a\\cdot a^{\\varphi(m)-1}=a^{\\varphi(m)}\\equiv1$. Ikkinchisini yozish qisqa, birinchisini hisoblash tez.',
 's2.b0.text':      'Sonning oxirgi raqami — uning modul $10$ boʻyicha qoldigʻi; oxirgi ikki raqam — modul $100$ boʻyicha qoldiq. Istalgan sonning darajalari qatʼiy modul boʻyicha ertami-kechmi takrorlana boshlaydi — odatda juda tez.',
 's2.b1.head.0':    'Asos',
 's2.b1.head.1':    'Oxirgi raqamlar sikli',
 's2.b1.head.2':    'Uzunligi',
 's2.b2.name':      'Sikldan qanday foydalanish kerak',
 's2.b2.text':      'Agar siklning uzunligi $L$ boʻlsa, faqat koʻrsatkichning **$L$ boʻyicha qoldigʻi** muhim. Nol qoldiqqa eʼtibor bering: agar koʻrsatkich $L$ ga karrali boʻlsa, siklning birinchi emas, **oxirgi** elementini oling.',
 's2.b3.q':         '$7^{2025}$ ning oxirgi raqamini toping.',
 's2.b3.steps.0':   '$7$ uchun sikl $7,9,3,1$ — uzunligi $4$.',
 's2.b3.steps.1':   '$2025=4\\cdot506+1$, qoldiq $1$.',
 's2.b3.steps.2':   'Demak oxirgi raqam siklning birinchi elementi: $7$.',
 's2.b4.q':         '$3^{2025}$ ning oxirgi ikki raqamini toping.',
 's2.b4.steps.0':   'Modul $100$ boʻyicha ishlaymiz. $3^4=81$ va $3^5=243\\equiv43$ ni hisoblaymiz.',
 's2.b4.steps.1':   '$3^{10}\\equiv43^2=1849\\equiv49$, demak $3^{20}\\equiv49^2=2401\\equiv1\\pmod{100}$.',
 's2.b4.steps.2':   '$2025=20\\cdot101+5$, shuning uchun $3^{2025}\\equiv3^{5}\\equiv43\\pmod{100}$.',
 's3.b0.name':      'Ferma kichik teoremasi',
 's3.b0.text':      '$p$ tub va $p\\nmid a$ boʻlsin. U holda $$a^{p-1}\\equiv1\\pmod p.$$ $p\\nmid a$ sharti boʻlmasa, $a^{p}\\equiv a\\pmod p$ koʻrinishi **har qanday** butun $a$ uchun oʻrinli.',
 's3.b1.text':      '$a,2a,3a,\\ldots,(p-1)a$ sonlarini va ularning modul $p$ boʻyicha qoldiqlarini koʻramiz. Hech bir qoldiq nol emas (aks holda $p\\mid ka$, ammo $p\\nmid a$ va $p\\nmid k$). Ular juft-jufti bilan turli: agar $ia\\equiv ja$ boʻlsa, $p\\mid a(i-j)$, demak $p\\mid i-j$, $|i-j|<p$ esa $i=j$ ni majbur qiladi. Demak bizdagi $p-1$ ta qoldiq aynan $1,2,\\ldots,p-1$, faqat boshqa tartibda. Ularni koʻpaytiramiz: $$a\\cdot2a\\cdots(p-1)a\\equiv1\\cdot2\\cdots(p-1)\\pmod p,$$ yaʼni $a^{p-1}(p-1)!\\equiv(p-1)!$. $(p-1)!$ soni $p$ ga oʻzaro tub boʻlgani uchun uni qisqartirishimiz mumkin: $a^{p-1}\\equiv1$. $\\blacksquare$',
 's3.b2.q':         '$3^{100}$ ni $7$ ga boʻlgandagi qoldiqni toping.',
 's3.b2.steps.0':   '$7$ tub va $7\\nmid3$, demak $3^{6}\\equiv1\\pmod 7$.',
 's3.b2.steps.1':   '$100=6\\cdot16+4$, shuning uchun $3^{100}\\equiv3^{4}$.',
 's3.b2.ans':       'Qoldiq $4$ ga teng',
 's3.b3.text':      'Ferma $p-1$ koʻrsatkichini beradi, ammo haqiqiy davr **qisqaroq** boʻlishi mumkin: u har doim $p-1$ ni boʻladi. Masalan, $2^3\\equiv1\\pmod 7$, garchi Ferma faqat $2^6\\equiv1$ ni vaʼda qilsa ham. Qisqa siklni qoʻlda qidiring — hisob yengillashadi.',
 's3.b4.name':      'Eyler teoremasi',
 's3.b4.text':      'Agar $\\gcd(a,m)=1$ boʻlsa, u holda $$a^{\\varphi(m)}\\equiv1\\pmod m ,$$ bunda $\\varphi(m)$ — $1$ dan $m$ gacha boʻlgan, $m$ ga oʻzaro tub sonlar soni.',
 's3.b5.text':      '$r_1,\\dots,r_{\\varphi(m)}$ — $m$ ga oʻzaro tub qoldiqlar boʻlsin. $a$ ga koʻpaytirish ularni oʻrin almashtiradi: har bir $ar_i$ soni $m$ ga oʻzaro tub, $ar_i\\equiv ar_j$ esa qisqartirish qonuniga koʻra $r_i=r_j$ ni majbur qiladi.\\n\\nButun toʻplamni koʻpaytirsak, $$a^{\\varphi(m)}\\prod_i r_i\\equiv\\prod_i r_i\\pmod m ,$$ va $\\prod r_i$ soni $m$ ga oʻzaro tub, demak qisqaradi: $$a^{\\varphi(m)}\\equiv1\\pmod m . \\qquad\\blacksquare$$',
 's3.b6.text':      'Ferma kichik teoremasi — bu $m=p$ tub boʻlgandagi xususiy hol, unda $\\varphi(p)=p-1$. Eyler koʻrinishi murakkab modullar bilan ham ishlaydi — «oxirgi raqamlar» masalalariga aynan shu kerak ($m=10$, $100$, $1000$).',
 's3.b7.q':         '$7^{7^{7}}$ ning oxirgi raqamini toping.',
 's3.b7.steps.0':   'Bizga modul $10$ boʻyicha qoldiq kerak; $\\varphi(10)=4$ va $\\gcd(7,10)=1$, demak $7^{4}\\equiv1\\pmod{10}$.',
 's3.b7.steps.1':   'Shuning uchun $7^{7}$ koʻrsatkichini modul $4$ boʻyicha bilish yetarli.',
 's3.b7.steps.2':   '$7\\equiv-1\\pmod4$, demak $7^{7}\\equiv-1\\equiv3\\pmod4$.',
 's3.b7.steps.3':   'Shuning uchun $7^{7^{7}}\\equiv7^{3}\\pmod{10}$.',
 's3.b7.steps.4':   '$7^{3}=343$, uning oxirgi raqami $3$.',
 's3.b7.ans':       'Oxirgi raqam $3$.',
 's3.b8.text':      'Darajalar minorasida koʻrsatkich modul $m$ boʻyicha emas, $\\varphi(m)$ boʻyicha kamaytiriladi. Bunday masalalardagi eng koʻp uchraydigan xato shu. Va bu usul faqat $\\gcd(a,m)=1$ boʻlgandagina oʻrinli: masalan, modul $10$ boʻyicha $2^{2^{n}}$ uchun u qoʻllanmaydi.',
 's4.b0.text':      'Koʻpincha sonning bir vaqtda bir necha modul boʻyicha qoldiqlari maʼlum boʻladi. Xitoy qoldiqlar teoremasi aytadiki, agar modullar juft-jufti bilan oʻzaro tub boʻlsa, bu maʼlumot sonni ularning koʻpaytmasi boʻyicha **toʻliq** aniqlaydi — va qoldiqlarning har qanday kombinatsiyasi uchraydi.',
 's4.b1.name':      'Xitoy qoldiqlar teoremasi',
 's4.b1.text':      '$m_1,\\dots,m_k$ juft-jufti bilan oʻzaro tub va $M=m_1\\cdots m_k$ boʻlsin. U holda istalgan $a_1,\\dots,a_k$ uchun $$x\\equiv a_1\\pmod{m_1},\\quad \\dots,\\quad x\\equiv a_k\\pmod{m_k}$$ sistemasining yechimi bor va u modul $M$ boʻyicha yagona.',
 's4.b2.text':      '**Yagonaligi.** $x,y$ ikkita yechim boʻlsin. U holda har bir $i$ uchun $m_i\\mid x-y$. Modullar juft-jufti bilan oʻzaro tub, demak ularning koʻpaytmasi ham ayirmani boʻladi: $M\\mid x-y$, yaʼni $x\\equiv y\\pmod M$ ✓\\n\\n**Mavjudligi (oshkor formula).** Har bir $i$ uchun $$M_i=\\frac M{m_i}=\\prod_{j\\ne i}m_j$$ deb olamiz. $M_i$ soni $m_i$ ga oʻzaro tub: umumiy tub boʻluvchi $m_i$ ni va biror $m_j$ ni boʻlar edi, bu esa juft-jufti bilan oʻzaro tublikka zid. Demak $$M_iN_i\\equiv1\\pmod{m_i}$$ boʻladigan $N_i$ teskari element bor.\\n\\n$$x=\\sum_{i=1}^{k}a_i M_i N_i$$ deb olamiz.\\n\\n$i$-taqqoslamani tekshiramiz. $j\\ne i$ boʻlgan har bir had $m_i$ koʻpaytuvchisini oʻz ichiga oladi (u $M_j$ ichida), demak modul $m_i$ boʻyicha yoʻqoladi. Qolgani $$x\\equiv a_iM_iN_i\\equiv a_i\\pmod{m_i} \\quad\\checkmark$$\\n\\nYechim qurildi. $\\blacksquare$',
 's4.b3.q':         '$x\\equiv2\\pmod3$, $x\\equiv3\\pmod5$, $x\\equiv2\\pmod7$ boʻladigan eng kichik musbat $x$ ni toping.',
 's4.b3.steps.0':   '$3,5,7$ modullari juft-jufti bilan oʻzaro tub, $M=105$; yechim modul $105$ boʻyicha yagona.',
 's4.b3.steps.1':   '**Qisqa yoʻl.** Birinchi va uchinchi shartlar $3\\mid x-2$ va $7\\mid x-2$ ni beradi, demak $21\\mid x-2$, yaʼni $x\\equiv2\\pmod{21}$.',
 's4.b3.steps.2':   '$2,\\ 23,\\ 44,\\ 65,\\ 86$ orasidan modul $5$ boʻyicha $3$ qoldiq beradiganini qidiramiz.',
 's4.b3.steps.3':   'Ularning qoldiqlari $2,\\ 3,\\ 4,\\ 0,\\ 1$ — demak $x=23$.',
 's4.b3.steps.4':   'Tekshirish: $23=3\\cdot7+2$ ✓, $23=5\\cdot4+3$ ✓, $23=7\\cdot3+2$ ✓',
 's4.b3.ans':       '$x=23$; barcha yechimlar $x\\equiv23\\pmod{105}$.',
 's4.b4.q':         '$100$ modulni $4$ va $25$ ga ajratib, $3^{1000}$ ning oxirgi ikki raqamini toping.',
 's4.b4.steps.0':   '$100=4\\cdot25$ va $\\gcd(4,25)=1$, demak teorema qoʻllanadi.',
 's4.b4.steps.1':   '**Modul $4$:** $3\\equiv-1$, demak $3^{1000}\\equiv(-1)^{1000}=1$.',
 's4.b4.steps.2':   '**Modul $25$:** $\\varphi(25)=20$, Eyler $3^{20}\\equiv1$ ni beradi; $20\\mid1000$ boʻlgani uchun $3^{1000}\\equiv1$.',
 's4.b4.steps.3':   'Bizga $x\\equiv1\\pmod4$ va $x\\equiv1\\pmod{25}$ kerak.',
 's4.b4.steps.4':   'Ikkalasi ham $x\\equiv1\\pmod{100}$ da bajariladi, yagonalikka koʻra boshqasi yoʻq.',
 's4.b4.ans':       'U $01$ bilan tugaydi.',
 's4.b5.text':      'Xitoy qoldiqlar teoremasi — bu **boʻlib tashla va yeng** strategiyasi: murakkab son boʻyicha qiyin savol tub darajalar boʻyicha oson savollarga ajraladi, ular alohida yechiladi va qayta yigʻiladi. Oxirgi raqamlar shu yoʻl bilan hisoblanadi va katta sonlar arifmetikasi shu tarzda tez ishlaydi.',
 's4.b6.text':      '**Juft-jufti bilan oʻzaro tublik muhim.** $$x\\equiv1\\pmod2,\\qquad x\\equiv0\\pmod4$$ sistemasining yechimi yoʻq: birinchisi toq sonni, ikkinchisi juft sonni talab qiladi. Oʻzaro tub boʻlmagan modullar uchun sistema aynan har bir juftlik uchun $\\gcd\\left(m_i,m_j\\right)\\mid a_i-a_j$ moslik sharti bajarilganda yechiladi.',
 's5.b0.text':      'Darajalarning oxirgi raqamlari biror davr bilan takrorlanishini koʻrdik. Eyler teoremasi davr **nega** borligini tushuntiradi. Tartib tushunchasi esa uning **nimaga teng** ekanini tushuntiradi.',
 's5.b1.name':      'Qoldiqning tartibi',
 's5.b1.text':      '$\\gcd(a,m)=1$ boʻlsin. $a$ ning modul $m$ boʻyicha **tartibi** — bu $$a^{k}\\equiv1\\pmod m$$ boʻladigan eng kichik musbat $k$, u $\\operatorname{ord}_m(a)$ deb belgilanadi.',
 's5.b2.text':      'Tartib mavjud: Eyler teoremasi $\\varphi(m)$ koʻrsatkichi allaqachon ishlashini koʻrsatadi, demak mos koʻrsatkichlarning boʻsh boʻlmagan toʻplamida eng kichik element bor.',
 's5.b3.name':      'Tartib har bir mos koʻrsatkichni boʻladi',
 's5.b3.text':      '$d=\\operatorname{ord}_m(a)$ boʻlsin. U holda $$a^{n}\\equiv1\\pmod m\\quad\\Longleftrightarrow\\quad d\\mid n .$$ Xususan $d\\mid\\varphi(m)$, tub modul $p$ uchun esa $d\\mid p-1$.',
 's5.b4.text':      '**Agar $d\\mid n$ boʻlsa,** masalan $n=dq$, u holda $$a^{n}=\\left(a^{d}\\right)^{q}\\equiv1 \\quad\\checkmark$$\\n\\n**Aksincha,** $a^{n}\\equiv1$ boʻlsin. Qoldiqli boʻlamiz: $n=dq+r$, bunda $0\\le r<d$. U holda $$1\\equiv a^{n}=\\left(a^{d}\\right)^{q}a^{r}\\equiv a^{r}\\pmod m .$$\\n\\nAmmo $d$ — shu xossaga ega **eng kichik** musbat koʻrsatkich va $0\\le r<d$, demak $r$ musbat boʻla olmaydi: $r=0$ va $d\\mid n$ ✓\\n\\nOxirgi tasdiq $n=\\varphi(m)$ olish bilan chiqadi: Eyler $a^{\\varphi(m)}\\equiv1$ ni beradi, demak $d\\mid\\varphi(m)$. $\\blacksquare$',
 's5.b5.text':      'Bu teorema «$p$ soni … ni boʻlishini isbotlang» turidagi masalalardagi eng oʻtkir qurol. Sxema: $a^{n}\\equiv1\\pmod p$ ekanini koʻrsating va $d\\mid n$ degan xulosaga keling; alohida Ferma $d\\mid p-1$ ni beradi. Demak $d$ soni $\\gcd(n,\\ p-1)$ ni boʻladi — bu koʻpincha $d=1$ yoki $d=2$ ni majbur qiladi, javob esa shundan chiqadi.',
 's5.b6.q':         '$2$ ning modul $7$ va modul $15$ boʻyicha tartibini toping.',
 's5.b6.steps.0':   '**Modul $7$:** $\\varphi(7)=6$, demak tartib $6$ ni boʻladi, yaʼni $1,2,3$ yoki $6$.',
 's5.b6.steps.1':   '$2^{1}=2$, $2^{2}=4$, $2^{3}=8\\equiv1$ — tartib $3$.',
 's5.b6.steps.2':   '**Modul $15$:** $\\varphi(15)=8$, demak tartib $8$ ni boʻladi.',
 's5.b6.steps.3':   '$2^{1}=2$, $2^{2}=4$, $2^{4}=16\\equiv1$ — tartib $4$.',
 's5.b6.steps.4':   'Eʼtibor bering, ikkala holda ham tartib $\\varphi(m)$ dan qatʼiy kichik.',
 's5.b7.q':         '$n$ tub boʻlganda $2^{n}-1$ ning har bir tub boʻluvchisi $2nk+1$ koʻrinishida boʻlishini isbotlang.',
 's5.b7.steps.0':   '$p\\mid2^{n}-1$ boʻlsin, yaʼni $2^{n}\\equiv1\\pmod p$, va $d=\\operatorname{ord}_p(2)$ deb olamiz.',
 's5.b7.steps.1':   'Teorema $d\\mid n$ ni beradi. $n$ tub boʻlgani uchun $d=1$ yoki $d=n$.',
 's5.b7.steps.2':   'Agar $d=1$ boʻlsa, $2\\equiv1\\pmod p$, demak $p\\mid1$ ✗ Shuning uchun $d=n$.',
 's5.b7.steps.3':   'Ferma $d\\mid p-1$ ni beradi, demak $n\\mid p-1$.',
 's5.b7.steps.4':   'Bundan tashqari $p$ toq ($2^{n}-1$ toq boʻlgani uchun), demak $p-1$ juft.',
 's5.b7.steps.5':   'Demak $p-1$ soni $n$ ga ham, $2$ ga ham boʻlinadi, $n$ esa toq, shuning uchun $2n\\mid p-1$.',
 's5.b7.ans':       '$p=2nk+1$. Masalan, $2^{11}-1=2047$ ning boʻluvchilari $23,\\ 67,\\ 89,\\dots$ orasidan qidiriladi — va haqiqatan $2047=23\\cdot89$.',
 's5.b8.text':      '**Boshlangʻich ildizlar.** Baʼzan tartib mumkin boʻlgan eng katta qiymatga teng: $\\operatorname{ord}_m(a)=\\varphi(m)$. Bunday $a$ modul $m$ boʻyicha **boshlangʻich ildiz** deyiladi va uning darajalari har bir teskarilanuvchi qoldiqdan oʻtadi. Boshlangʻich ildizlar aynan $m=1,2,4,p^{k},2p^{k}$ uchun mavjud, bunda $p$ — toq tub son. Masalan, $3$ soni modul $7$ boʻyicha boshlangʻich ildiz: uning darajalari $3,2,6,4,5,1$ — barcha oltita noldan farqli qoldiq.',
 's6.b0.text':      '«Kvadratlarni modul $m$ boʻyicha koʻrish» usulidan bir necha marta foydalandik. Endi kvadratlar umuman nechta ekanini va sonning kvadrat ekanini hammasini tekshirmasdan qanday aniqlashni bilib olish vaqti keldi.',
 's6.b1.name':      'Kvadratik chegirma',
 's6.b1.text':      '$p$ — toq tub son va $p\\nmid a$ boʻlsin. Agar $$x^{2}\\equiv a\\pmod p$$ yechimga ega boʻlsa, $a$ soni modul $p$ boʻyicha **kvadratik chegirma**, aks holda **kvadratik chegirmamas** deyiladi.',
 's6.b2.name':      'Roppa-rosa yarmi chegirma',
 's6.b2.text':      'Noldan farqli $1,2,\\dots,p-1$ qoldiqlar orasida roppa-rosa $\\dfrac{p-1}{2}$ tasi kvadratik chegirma va shunchasi chegirmamas. Bundan tashqari $x^{2}\\equiv a$ ning yo ikkita yechimi bor, yo umuman yoʻq.',
 's6.b3.text':      '$\\{1,2,\\dots,p-1\\}$ da $x\\mapsto x^{2}$ akslantirishni koʻramiz.\\n\\n**Har bir qiymat ikki marta erishiladi.** Agar $x^{2}\\equiv y^{2}$ boʻlsa, $p\\mid(x-y)(x+y)$, demak Yevklid lemmasi $x\\equiv y$ yoki $x\\equiv-y$ ni beradi. Demak $x$ va $p-x$ bir xil kvadrat beradi, boshqa mos tushishlar yoʻq.\\n\\n**Bu ikkitasi turli.** $x\\equiv-x$ degani $p\\mid2x$ boʻlar edi, toq $p$ va $p\\nmid x$ da bu mumkin emas.\\n\\nDemak $p-1$ ta son $\\tfrac{p-1}2$ ta juftlikka ajraladi, har biri oʻz kvadratini beradi, hammasi turli. Shuning uchun roppa-rosa $\\tfrac{p-1}2$ ta chegirma bor, qolgan $\\tfrac{p-1}2$ tasi esa chegirmamas. $\\blacksquare$',
 's6.b4.q':         'Modul $11$ boʻyicha barcha kvadratik chegirmalarni roʻyxatlang.',
 's6.b4.steps.0':   '$1,\\dots,5$ ni kvadratga koʻtarish yetarli — undan nari kvadratlar takrorlanadi.',
 's6.b4.steps.2':   'Bu $\\tfrac{11-1}{2}=5$ ta chegirma ✓',
 's6.b4.steps.3':   'Chegirmamaslar — qolganlari: $2,\\ 6,\\ 7,\\ 8,\\ 10$.',
 's6.b4.ans':       'Chegirmalar: $1,3,4,5,9$.',
 's6.b5.name':      'Eyler mezoni',
 's6.b5.text':      '$p$ — toq tub son va $p\\nmid a$ boʻlsin. U holda $$a^{\\frac{p-1}{2}}\\equiv\\begin{cases}\\ \\ 1\\pmod p, & \\text{agar } a\\ \\text{kvadratik chegirma boʻlsa},\\\\[2pt] -1\\pmod p, & \\text{agar } a\\ \\text{chegirmamas boʻlsa}.\\end{cases}$$',
 's6.b6.text':      '**1-qadam: qiymat har doim $\\pm1$.** Ferma $$\\left(a^{\\frac{p-1}{2}}\\right)^{2}=a^{\\,p-1}\\equiv1\\pmod p$$ ni beradi, demak $p$ soni $\\left(a^{\\frac{p-1}{2}}-1\\right)\\left(a^{\\frac{p-1}{2}}+1\\right)$ ni boʻladi, Yevklid lemmasi esa $p$ ni koʻpaytuvchilardan biriga joylaydi.\\n\\n**2-qadam: chegirmalar $+1$ beradi.** Agar $a\\equiv x^{2}$ boʻlsa, $$a^{\\frac{p-1}{2}}\\equiv x^{\\,p-1}\\equiv1\\pmod p \\quad\\checkmark$$\\n\\n**3-qadam: chegirmamaslar $-1$ beradi.** $t^{\\frac{p-1}{2}}-1$ koʻphadining tub $p$ modul boʻyicha koʻpi bilan $\\tfrac{p-1}2$ ta ildizi bor. 2-qadamga koʻra barcha $\\tfrac{p-1}2$ ta kvadratik chegirma allaqachon ildiz, demak boshqasi yoʻq. Shuning uchun chegirmamas $a$ uchun $a^{\\frac{p-1}{2}}$ qiymati $1$ emas, 1-qadamga koʻra esa u $-1$. $\\blacksquare$',
 's6.b7.name':      '$-1$ qachon kvadrat boʻladi',
 's6.b7.text':      'Toq tub $p$ uchun $x^{2}\\equiv-1\\pmod p$ taqqoslamasi yechimga ega boʻlishi uchun $p\\equiv1\\pmod4$ boʻlishi **zarur va yetarli**.',
 's6.b8.text':      'Eyler mezoniga koʻra yechiluvchanlik $$(-1)^{\\frac{p-1}{2}}\\equiv1\\pmod p$$ ga teng kuchli.\\n\\nChap tomon $\\tfrac{p-1}2$ juft boʻlganda $+1$, toq boʻlganda $-1$ ga teng, $p>2$ uchun esa $-1\\not\\equiv1$.\\n\\nDemak yechiluvchanlik $\\tfrac{p-1}2$ ning juftligiga, yaʼni $4\\mid p-1$ ga teng kuchli. $\\blacksquare$\\n\\n**Tekshirish.** $p=5$ uchun: $2^{2}=4\\equiv-1$ ✓ $p=7$ uchun: modul $7$ boʻyicha kvadratlar $1,4,2$, $6\\equiv-1$ esa ular orasida yoʻq ✓',
 's6.b9.text':      'Koʻp «imkonsizlik» natijalari darhol kelib chiqadi. $x^{2}+1=7y$ tenglamasining yechimi yoʻq, chunki $7\\equiv3\\pmod4$. Ikkita kvadrat yigʻindisi esa $p\\equiv3\\pmod4$ tub songa toq darajada hech qachon boʻlinmaydi — sonni ikkita kvadrat yigʻindisi sifatida tasvirlash nazariyasining hammasi shunga tayanadi.',
 's6.b10.text':     '**Kvadratik oʻzarolik qonuni** (Gauss, $1796$) yanada uzoqqa boradi va $x^{2}\\equiv q\\pmod p$ ning yechiluvchanligini $x^{2}\\equiv p\\pmod q$ niki bilan bogʻlaydi: turli toq tub sonlar uchun $$\\left(\\frac pq\\right)\\left(\\frac qp\\right)=(-1)^{\\frac{p-1}2\\cdot\\frac{q-1}2} .$$ Gauss uni «oltin teorema» deb atagan va sakkizta turli isbot bergan.',
 's7.b0.text':      '«Yechim yoʻqligini isbotlang» turidagi har qanday masaladagi markaziy savol — **qaysi modulga qarash kerak**. Tanlov tasodifiy emas: tenglamaning bir tomoni kam sondagi qoldiq beradigan, ikkinchi tomoni esa ularga hech qachon tushmaydigan modulni tanlang.',
 's7.b1.head.0':    'Nima uchraydi',
 's7.b1.head.1':    'Modul',
 's7.b1.head.2':    'Nega',
 's7.b1.rows.0.0':  'kvadratlar',
 's7.b1.rows.0.1':  '$4$ yoki $8$',
 's7.b1.rows.0.2':  '$n^2\\equiv0,1\\pmod4$; toq sonning kvadrati $\\equiv1\\pmod8$',
 's7.b1.rows.1.0':  'ikkita kvadrat yigʻindisi',
 's7.b1.rows.1.2':  'faqat $0,1,2$ beradi — hech qachon $3$ emas',
 's7.b1.rows.2.0':  'kublar',
 's7.b1.rows.3.0':  'ikkining darajalari',
 's7.b1.rows.3.1':  '$3$ yoki $7$',
 's7.b1.rows.3.2':  'uzunligi $2$ va $3$ boʻlgan qisqa sikllar',
 's7.b1.rows.4.0':  'oʻnlik raqamlar',
 's7.b1.rows.4.1':  '$9$ yoki $11$',
 's7.b1.rows.4.2':  'raqamlar yigʻindisi, ishorali yigʻindi',
 's7.b1.rows.5.0':  'koʻrsatkichdagi tub $p$',
 's7.b1.rows.5.2':  'Ferma kichik teoremasi',
 's7.b2.q':         '$x^2+y^2=2023$ tenglamasining butun yechimlari yoʻqligini isbotlang.',
 's7.b2.steps.0':   'Kvadrat modul $4$ boʻyicha $0$ yoki $1$ qoldiq beradi.',
 's7.b2.steps.1':   'Demak ikkita kvadrat yigʻindisi $0$, $1$ yoki $2$ beradi — hech qachon $3$ emas.',
 's7.b2.steps.2':   '$2023=4\\cdot505+3$, yaʼni $2023\\equiv3\\pmod 4$. Yechim yoʻq.',
 's7.b2.ans':       'Yechim yoʻq',
 's7.b3.name':      'Usul: katta sonni kichigiga almashtiring',
 's7.b3.text':      'Darajaga koʻtarishdan oldin asosni uning qoldigʻi bilan almashtiring. $15^{15}\\pmod{13}$ oʻrniga $2^{15}\\pmod{13}$ ni hisoblang — arifmetika ogʻzaki bajariladigan boʻlib qoladi.',
}
