# -*- coding: utf-8 -*-
"""Uzbek for topic 1.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Boʻlinuvchanlik, EKUB va EKUK',
 'sub':             'Butun sonlar nazariyasining poydevori: qoldiqli boʻlish, boʻlinish alomatlari va Yevklid algoritmi.',
 'goals.0':         'Boʻlinuvchanlik taʼrifini tushunish va uning xossalaridan ishonch bilan foydalanish.',
 'goals.1':         'Qoldiqli boʻlishni va $2,3,4,5,8,9,11$ ga boʻlinish alomatlarini qoʻllash.',
 'goals.2':         'Yevklid algoritmi bilan EKUB topish va uni $ax+by$ koʻrinishida yozish.',
 'goals.3':         '$\\gcd(a,b)\\cdot\\operatorname{lcm}(a,b)=ab$ ayniyatidan foydalanish va boʻluvchilar sonini sanash.',
 's0.h':            'Boʻlinuvchanlik nima degani',
 's1.h':            'Qoldiqli boʻlish',
 's2.h':            'Boʻlinish alomatlari',
 's3.h':            'EKUB va Yevklid algoritmi',
 's4.h':            'Butun sonlardagi chiziqli tenglamalar',
 's5.h':            'Arifmetikaning asosiy teoremasi',
 's6.h':            'EKUK va uning EKUB bilan bogʻliqligi',
 's7.h':            'Boʻluvchilarni sanash',
 's8.h':            'Faktorial ichidagi tub sonlar',
 's9.h':            'Eyler funksiyasi va uchta klassik teorema',
 's10.h':           'Bilish kerak boʻlgan EKUB ayniyatlari',
 's11.h':           'Masalani yechadigan usullar',
 's0.b0.text':      'Boʻlinuvchanlik — bu «kalkulyatorsiz boʻlish» emas, balki maʼlum bir butun son mavjudligi haqidagi tasdiq. Sonlar nazariyasidagi qolgan hamma narsa shu bitta taʼrifga tayanadi.',
 's0.b1.name':      'Boʻlinuvchanlik',
 's0.b1.text':      '$a$ va $b$ butun sonlar, $a\\ne 0$ boʻlsin. Agar $b=ak$ boʻladigan butun $k$ mavjud boʻlsa, **$a$ soni $b$ ni boʻladi** deymiz va $a\\mid b$ deb yozamiz. Bunda $a$ — $b$ ning **boʻluvchisi**, $b$ esa $a$ ning **karralisi**.',
 's0.b2.text':      'Misollar: $3\\mid 12$, chunki $12=3\\cdot 4$; $7\\mid 0$, chunki $0=7\\cdot 0$; ammo $5\\nmid 17$. Eʼtibor bering: **nol hamma songa boʻlinadi** (noldan tashqari), nolga esa hech narsa boʻlinmaydi.',
 's0.b3.name':      'Asosiy xossalar',
 's0.b3.text':      '$a,b,c$ butun sonlar uchun: $\\;$ (1) agar $a\\mid b$ va $a\\mid c$ boʻlsa, $a\\mid(b\\pm c)$; $\\;$ (2) agar $a\\mid b$ boʻlsa, istalgan butun $c$ uchun $a\\mid bc$; $\\;$ (3) agar $a\\mid b$ va $b\\mid c$ boʻlsa, $a\\mid c$; $\\;$ (4) agar $a\\mid b$ va $b\\mid a$ boʻlsa, $a=\\pm b$.',
 's0.b4.text':      '(1) Taʼrifga koʻra $b=ak$ va $c=am$. U holda $b\\pm c=a(k\\pm m)$, va $k\\pm m$ butun son. $\\;$ (2) $bc=(ak)c=a(kc)$. $\\;$ (3) $b=ak$ va $c=bm=(ak)m=a(km)$. $\\;$ (4) $b=ak$ va $a=bm$ dan $a=akm$, demak $km=1$, $k,m$ butun boʻlgani uchun $k=m=\\pm1$.',
 's0.b5.name':      'Chiziqli kombinatsiyalar — asosiy usul',
 's0.b5.text':      '(1) va (2) xossalar birgalikda mavzudagi eng foydali faktni beradi: agar $d\\mid a$ va $d\\mid b$ boʻlsa, u holda $$d\\mid (ax+by)\\quad\\text{barcha butun } x,y \\text{ uchun.}$$ Olimpiadadagi boʻlinuvchanlikka oid deyarli har bir masala shu yoʻl bilan yechiladi: berilgan ikkita ifodani nomaʼlum qisqaradigan qilib birlashtiring.',
 's0.b6.q':         'Agar $d\\mid (5n+3)$ va $d\\mid (3n+2)$ boʻlsa, $d=\\pm1$ ekanini isbotlang.',
 's0.b6.steps.0':   '$n$ ni yoʻqotadigan koeffitsiyentlarni tanlang: $3\\cdot(5n+3)-5\\cdot(3n+2)$ ni oling.',
 's0.b6.steps.1':   '$3(5n+3)-5(3n+2)=15n+9-15n-10=-1$.',
 's0.b6.steps.2':   'Chiziqli kombinatsiya xossasiga koʻra $d\\mid -1$, demak $d=\\pm1$.',
 's0.b6.ans':       '$d=\\pm1$',
 's0.b7.name':      'Boʻluvchi sondan katta emas',
 's0.b7.text':      'Agar $d\\mid a$ va $a\\ne0$ boʻlsa, $|d|\\le|a|$. Xususan, har bir noldan farqli sonning **chekli sondagi** boʻluvchisi bor.',
 's0.b8.text':      '$a=dk$ boʻlsin. $a\\ne0$ boʻlgani uchun $k\\ne0$, demak $|k|\\ge1$ va $$|a|=|d|\\cdot|k|\\ \\ge\\ |d| .$$\\n\\nDemak har bir boʻluvchi $-|a|$ dan $|a|$ gacha boʻlgan chekli oraliqda yotadi, ular esa chekli sonda. $\\blacksquare$',
 's0.b9.text':      '$a\\ne0$ sharti muhim: nolning boʻluvchilari cheksiz koʻp, chunki har qanday $d\\ne0$ uchun $d\\mid0$. Shuning uchun «… ni boʻluvchi barcha $d$ larni toping» turidagi masalalarda birinchi qadam — boʻlinuvchi nolga teng emasligiga ishonch hosil qilish.',
 's0.b10.name':     'Har bir sonning tub boʻluvchisi bor',
 's0.b10.text':     '$n>1$ boʻlgan har bir butun sonning tub boʻluvchisi bor; bundan tashqari uning birdan katta **eng kichik** boʻluvchisi tub son, agar $n$ murakkab boʻlsa, bu boʻluvchi $\\sqrt n$ dan oshmaydi.',
 's0.b11.text':     '$n$ ning birdan katta boʻluvchilari toʻplami boʻsh emas (unda $n$ ning oʻzi bor), demak unda eng kichik element $p$ bor.\\n\\n**$p$ tub son.** Agar $p=ab$ va $1<a<p$ boʻlsa, $a$ ham $n$ ni boʻlar va $p$ dan kichik boʻlar edi — bu minimallikka zid.\\n\\n**Murakkab $n$ uchun baho.** $n=pm$ deb yozamiz. Agar $n$ murakkab boʻlsa, $m>1$, demak $m$ ham birdan katta boʻluvchi va minimallikdan $m\\ge p$. Demak $$n=pm\\ \\ge\\ p^{2}\\quad\\Longrightarrow\\quad p\\le\\sqrt n . \\qquad\\blacksquare$$',
 's0.b12.text':     'Bu standart tublik tekshiruvini beradi: $n$ tub ekanini koʻrish uchun $\\sqrt n$ gacha boʻlgan tub boʻluvchilarni sinash yetarli. $n=211$ uchun $2,3,5,7,11,13$ tub sonlari yetarli, chunki $14^{2}=196<211<225=15^{2}$.',
 's1.b0.name':      'Qoldiqli boʻlish teoremasi',
 's1.b0.text':      'Istalgan $a$ butun son va $b>0$ uchun $$a=bq+r,\\qquad 0\\le r<b$$ shartlarni qanoatlantiruvchi **yagona** $q$ (toʻliqsiz boʻlinma) va $r$ (qoldiq) butun sonlar juftligi mavjud.',
 's1.b1.text':      '*Mavjudligi.* $bq\\le a$ shartni qanoatlantiruvchi eng katta butun $q$ ni olamiz (u mavjud, chunki $b$ ning karralilari ikki tomonga ham cheksiz ketadi). $r=a-bq\\ge 0$ deymiz. Agar $r\\ge b$ boʻlsa, $b(q+1)=bq+b\\le a$ boʻlar edi — bu $q$ ning tanlanishiga zid. Demak $r<b$. $\\;$ *Yagonaligi.* $a=bq_1+r_1=bq_2+r_2$ va $0\\le r_1,r_2<b$ boʻlsin. U holda $b(q_1-q_2)=r_2-r_1$ va $|r_2-r_1|<b$. Absolyut qiymati $b$ dan kichik boʻlgan $b$ ning karralisi nolga teng, demak $r_1=r_2$ va $q_1=q_2$.',
 's1.b2.text':      'Qoldiq har doim **manfiy emas**. Masalan, $-17=5\\cdot(-4)+3$, demak qoldiq $3$ ga teng, $-2$ ga emas. Bu kichik nuqta mavzudagi boshqa hamma narsadan koʻra koʻproq yechimni buzadi.',
 's1.b3.name':      'Qoldiq boʻyicha hollarga ajratish',
 's1.b3.text':      'Har bir butun $n$ sonni $n=3k$, $n=3k+1$ yoki $n=3k+2$ koʻrinishida yozish mumkin. Uchta hol boʻladi va tasdiq har birida tekshiriladi. Hech qanday aqlli usul koʻrinmaganda boʻlinuvchanlikka oid tasdiqni isbotlashning eng sodda yoʻli shu.',
 's1.b4.q':         '$n^2$ ni $4$ ga boʻlganda qoldiq $0$ yoki $1$ boʻlishini isbotlang.',
 's1.b4.steps.0':   'Agar $n=2k$ boʻlsa, $n^2=4k^2$ — qoldiq $0$.',
 's1.b4.steps.1':   'Agar $n=2k+1$ boʻlsa, $n^2=4k^2+4k+1=4(k^2+k)+1$ — qoldiq $1$.',
 's1.b4.steps.2':   'Boshqa hol yoʻq, demak qoldiq har doim $0$ yoki $1$.',
 's1.b4.ans':       'Qoldiq $0$ yoki $1$',
 's1.b5.text':      'Bu kichkina kuzatish ishchi qurol. Ikkita kvadrat yigʻindisi $4$ ga boʻlinganda $0,1$ yoki $2$ qoldiq beradi, hech qachon $3$ emas: demak, masalan, $n^2+m^2=2023$ tenglamasining yechimi yoʻq, chunki $2023=4\\cdot505+3$.',
 's1.b6.name':      'Toʻliqsiz boʻlinma — butun qism',
 's1.b6.text':      '$a=bq+r$ da $0\\le r<b$ va $b>0$ boʻlsa, boʻlinma va qoldiq oshkor koʻrinishda $$q=\\left\\lfloor\\frac ab\\right\\rfloor,\\qquad r=a-b\\left\\lfloor\\frac ab\\right\\rfloor$$ formulalar bilan beriladi.',
 's1.b7.text':      '$0\\le r<b$ sharti $0\\le a-bq<b$ ga, yaʼni $$bq\\le a<bq+b\\quad\\Longleftrightarrow\\quad q\\le\\frac ab<q+1$$ ga teng kuchli, bu esa taʼrifga koʻra $q=\\left\\lfloor\\tfrac ab\\right\\rfloor$ degani. $r$ uchun formula oʻrniga qoʻyishdan kelib chiqadi. $\\blacksquare$',
 's1.b8.name':      'Chegirmalarning toʻliq sistemasi',
 's1.b8.text':      '$n$ ta butun sondan iborat toʻplam, agar ular $n$ ga boʻlinganda juft-jufti bilan turli qoldiq bersa — yaʼni $0,1,\\dots,n-1$ qoldiqlarning har birini roppa-rosa bir marta qamrasa — modul $n$ boʻyicha **chegirmalarning toʻliq sistemasi** deyiladi.',
 's1.b9.text':      'Tanish misol — $0,1,\\dots,n-1$ ning oʻzi. Boshqalari ham foydali: ketma-ket kelgan istalgan $n$ ta butun son toʻliq sistema hosil qiladi. Aynan shuning uchun «ketma-ket kelgan $n$ ta butun son orasida roppa-rosa bittasi $n$ ga boʻlinadi».',
 's1.b10.q':        'Ketma-ket kelgan istalgan uchta butun sonning koʻpaytmasi $6$ ga boʻlinishini isbotlang.',
 's1.b10.steps.0':  'Sonlarni $n,\\ n+1,\\ n+2$ deb belgilaymiz.',
 's1.b10.steps.1':  'Ketma-ket kelgan uchta son modul $3$ boʻyicha toʻliq sistema hosil qiladi, demak ulardan roppa-rosa bittasi $3$ ga boʻlinadi.',
 's1.b10.steps.2':  'Ketma-ket kelgan uchta son orasida kamida bittasi juft, demak koʻpaytma $2$ ga boʻlinadi.',
 's1.b10.steps.3':  '$2$ va $3$ oʻzaro tub boʻlgani uchun koʻpaytma $6$ ga boʻlinadi.',
 's1.b10.ans':      'Boʻlinadi — bu ketma-ket kelgan $k$ ta sonning koʻpaytmasi $k!$ ga boʻlinishi haqidagi umumiy faktning xususiy holi.',
 's2.b0.text':      '$N=\\overline{a_k a_{k-1}\\ldots a_1 a_0}$ oʻnlik yozuv boʻlsin, yaʼni $N=a_k10^k+\\cdots+a_1\\cdot10+a_0$. Raqamlar yigʻindisini $S(N)=a_k+\\cdots+a_0$ deb belgilaymiz.',
 's2.b1.head.0':    'Boʻluvchi',
 's2.b1.head.1':    'Alomat',
 's2.b1.head.2':    'Misol',
 's2.b1.rows.0.1':  'oxirgi raqam juft',
 's2.b1.rows.1.1':  'oxirgi ikki raqam $4$ ga karrali son hosil qiladi',
 's2.b1.rows.2.1':  'oxirgi uch raqam $8$ ga karrali son hosil qiladi',
 's2.b1.rows.3.1':  'oxirgi raqam $0$ yoki $5$',
 's2.b1.rows.6.1':  '$11$ raqamlarning ishorali yigʻindisini boʻladi',
 's2.b1.rows.7.1':  'ham $2$ ga, ham $3$ ga boʻlinadi',
 's2.b2.name':      '$9$ ga (va $3$ ga) boʻlinish alomati',
 's2.b2.text':      '$9\\mid N$ boʻlishi uchun $9\\mid S(N)$ boʻlishi zarur va yetarli. $3$ uchun ham xuddi shunday.',
 's2.b3.text':      'Har bir $j\\ge1$ uchun $10^j-1=\\underbrace{99\\ldots9}_{j}=9\\cdot\\underbrace{11\\ldots1}_{j}$ soni $9$ ga boʻlinishini kuzatamiz. U holda $$N-S(N)=\\sum_{j\\ge1} a_j\\left(10^{j}-1\\right),$$ va oʻng tomondagi har bir had $9$ ga boʻlinadi. Demak $9\\mid N-S(N)$, shuning uchun $9\\mid N$ va $9\\mid S(N)$ teng kuchli. $3$ uchun mulohaza aynan shunday, chunki $3\\mid 10^j-1$.',
 's2.b4.name':      '$11$ ga boʻlinish alomati',
 's2.b4.text':      '$11\\mid N$ boʻlishi uchun $11$ soni $A(N)=a_0-a_1+a_2-\\cdots$ ni boʻlishi zarur va yetarli.',
 's2.b5.text':      '$x^j-y^j=(x-y)\\left(x^{j-1}+x^{j-2}y+\\cdots+y^{j-1}\\right)$ ayniyatidan foydalanamiz; u $x-y$ har doim $x^j-y^j$ ni boʻlishini koʻrsatadi. $x=10$, $y=-1$ olamiz: u holda $x-y=11$ soni $10^{j}-(-1)^{j}$ ni boʻladi. Demak $$N-A(N)=\\sum_{j\\ge0}a_j\\left(10^{j}-(-1)^{j}\\right)$$ soni $11$ ga boʻlinadi, tasdiq esa shundan kelib chiqadi.',
 's2.b6.text':      'Xuddi shu gʻoya $7$, $11$ va $13$ uchun bir vaqtda alomat beradi: $1001=7\\cdot11\\cdot13$, demak son $7$, $11$ yoki $13$ ga aynan oʻngdan boshlab olingan uch xonali guruhlarining ishorali yigʻindisi shu songa boʻlinganda boʻlinadi.',
 's2.b7.name':      'Oxirgi raqamlarni oʻqiydigan alomatlar',
 's2.b7.text':      'Har bir $k\\ge1$ va oxirgi $k$ ta raqamidan tuzilgan $T_k$ dumga ega har bir $N$ son uchun $$2^{k}\\mid N\\ \\Longleftrightarrow\\ 2^{k}\\mid T_k ,\\qquad 5^{k}\\mid N\\ \\Longleftrightarrow\\ 5^{k}\\mid T_k .$$ Xususan, $2$ va $5$ oxirgi bitta raqamni, $4$ va $25$ oxirgi ikkitasini, $8$ va $125$ oxirgi uchtasini oʻqiydi.',
 's2.b8.text':      'Dumni ajratamiz: $$N=10^{k}\\,q+T_k ,$$ bu yerda $q$ — chapda turgan qism.\\n\\nAsosiy kuzatish: $$10^{k}=2^{k}\\cdot5^{k} ,$$ demak $10^{k}$ ham $2^{k}$ ga, ham $5^{k}$ ga boʻlinadi. Shuning uchun birinchi had ularning har biriga karrali va $$N\\equiv T_k \\pmod{2^{k}},\\qquad N\\equiv T_k \\pmod{5^{k}} .$$\\n\\nIkkala teng kuchlilik ham shundan kelib chiqadi. $\\blacksquare$',
 's2.b9.q':         '$37\\,516$ soni $4$ ga boʻlinadimi? $8$ ga-chi?',
 's2.b9.steps.0':   '$4$ uchun oxirgi ikki raqamni oʻqiymiz: $16=4\\cdot4$ — boʻlinadi ✓',
 's2.b9.steps.1':   '$8$ uchun oxirgi uchtasini: $516=8\\cdot64+4$ — boʻlinmaydi ✗',
 's2.b9.steps.2':   'Tekshirish: $37\\,516=4\\cdot9379$, $9379$ esa toq, demak $8$ haqiqatan ham uni boʻlmaydi.',
 's2.b9.ans':       '$4$ ga boʻlinadi, $8$ ga boʻlinmaydi.',
 's2.b10.name':     '$7$, $11$ va $13$ uchun yagona alomat',
 's2.b10.text':     'Oʻnlik yozuvni oʻngdan boshlab uch xonali guruhlarga ajratamiz, ularning qiymatlari $g_0,g_1,g_2,\\dots$ boʻlsin. U holda $m\\in\\{7,11,13\\}$ uchun $$m\\mid N\\quad\\Longleftrightarrow\\quad m\\ \\big|\\ g_0-g_1+g_2-\\cdots$$',
 's2.b11.text':     'Tuzilishiga koʻra $$N=\\sum_{j\\ge0}g_j\\cdot1000^{\\,j} .$$\\n\\nAsosiy ajratma: $$1001=7\\cdot11\\cdot13 ,$$ demak $7$, $11$, $13$ modullarining har biri boʻyicha $1000\\equiv-1$. Darajaga koʻtarib, $$1000^{\\,j}\\equiv(-1)^{j} ,$$ shuning uchun uchala modul boʻyicha ham $$N\\equiv g_0-g_1+g_2-\\cdots$$ $\\blacksquare$',
 's2.b12.q':        '$1\\,234\\,569$ soni $7$ ga, $11$ ga va $13$ ga boʻlinishini tekshiring.',
 's2.b12.steps.0':  'Oʻngdan uchtalab guruhlar: $569$, $234$, $1$.',
 's2.b12.steps.1':  'Ishorali yigʻindi: $569-234+1=336$.',
 's2.b12.steps.2':  '$336=7\\cdot48$, demak $7$ ga boʻlinadi ✓',
 's2.b12.steps.3':  '$336=11\\cdot30+6$, $11$ ga boʻlinmaydi ✗',
 's2.b12.steps.4':  '$336=13\\cdot25+11$, $13$ ga boʻlinmaydi ✗',
 's2.b12.ans':      '$7$ ga boʻlinadi; $11$ va $13$ ga boʻlinmaydi.',
 's3.b0.name':      'Eng katta umumiy boʻluvchi',
 's3.b0.text':      '$\\gcd(a,b)$ — bu $a$ ni ham, $b$ ni ham boʻladigan eng katta butun son ($a,b$ ikkalasi ham nol emas). Agar $\\gcd(a,b)=1$ boʻlsa, sonlar **oʻzaro tub** deyiladi.',
 's3.b1.name':      'Asosiy lemma',
 's3.b1.text':      'Agar $a=bq+r$ boʻlsa, $\\gcd(a,b)=\\gcd(b,r)$.',
 's3.b2.text':      '$(a,b)$ va $(b,r)$ juftliklarining umumiy boʻluvchilari **aynan bir xil** ekanini koʻrsatamiz. $d\\mid a$ va $d\\mid b$ boʻlsin. U holda $d\\mid a-bq=r$, demak $d$ — $b$ va $r$ ning umumiy boʻluvchisi. Aksincha, $d\\mid b$ va $d\\mid r$ boʻlsin. U holda $d\\mid bq+r=a$, demak $d$ — $a$ va $b$ ning umumiy boʻluvchisi. Umumiy boʻluvchilar toʻplamlari ustma-ust tushadi, demak ularning eng katta elementlari ham.',
 's3.b3.name':      'Yevklid algoritmi',
 's3.b3.text':      'Lemma algoritmga aylanadi: $(a,b)$ juftlikni $(b,\\,a\\bmod b)$ bilan almashtiring va ikkinchi son nolga aylanguncha takrorlang. Oxirgi noldan farqli son — EKUB. Qoldiqlar qatʼiy kamayadi, demak jarayon tugaydi.',
 's3.b4.q':         '$\\gcd(1071,462)$ ni toping.',
 's3.b4.steps.0':   '$1071=2\\cdot462+147$',
 's3.b4.steps.1':   '$462=3\\cdot147+21$',
 's3.b4.steps.2':   '$147=7\\cdot21+0$ — qoldiq nol, toʻxtaymiz.',
 's3.b4.ans':       '$\\gcd(1071,462)=21$',
 's3.b5.name':      'Bezu ayniyati',
 's3.b5.text':      'Istalgan $a,b$ butun sonlar uchun (ikkalasi ham nol emas) $$ax+by=\\gcd(a,b)$$ boʻladigan butun $x,y$ mavjud. Bundan tashqari $\\gcd(a,b)$ — $ax+by$ koʻrinishidagi **eng kichik** musbat son.',
 's3.b6.text':      '$d$ — $ax+by$ koʻrinishidagi eng kichik musbat son boʻlsin, $d=ax_0+by_0$. $a$ ni $d$ ga qoldiqli boʻlamiz: $a=dq+r$, $0\\le r<d$. U holda $$r=a-dq=a-(ax_0+by_0)q=a(1-x_0q)+b(-y_0q),$$ demak $r$ ham $ax+by$ koʻrinishida. Ammo $0\\le r<d$ va $d$ — shunday koʻrinishdagi eng kichik **musbat** son, demak $r=0$ va $d\\mid a$. Xuddi shunday $d\\mid b$. Demak $d$ — umumiy boʻluvchi. Aksincha, $a,b$ ning istalgan umumiy boʻluvchisi $c$ soni $ax_0+by_0=d$ ni boʻladi, demak $c\\le d$. Shuning uchun $d=\\gcd(a,b)$.',
 's3.b7.q':         '$\\gcd(1071,462)$ ni $1071x+462y$ koʻrinishida yozing.',
 's3.b7.steps.0':   'Algoritmning birinchi qadamidan: $147=1071-2\\cdot462$.',
 's3.b7.steps.1':   'Ikkinchi qadamdan: $21=462-3\\cdot147$.',
 's3.b7.steps.2':   'Oʻrniga qoʻyamiz: $21=462-3(1071-2\\cdot462)=7\\cdot462-3\\cdot1071$.',
 's3.b7.steps.3':   'Tekshirish: $7\\cdot462=3234$, $3\\cdot1071=3213$, ayirma $21$ ✓',
 's3.b7.ans':       '$21=1071\\cdot(-3)+462\\cdot 7$',
 's3.b8.text':      'Bezu darhol **Yevklid lemmasini** beradi: agar $p$ tub boʻlsa va $p\\mid ab$ boʻlsa, u holda $p\\mid a$ yoki $p\\mid b$. Haqiqatan, agar $p\\nmid a$ boʻlsa, $\\gcd(p,a)=1$, demak $px+ay=1$; buni $b$ ga koʻpaytirsak $pbx+aby=b$, chapdagi ikkala had ham $p$ ga boʻlinadi.',
 's3.b9.name':      'EKUB xossalari',
 's3.b9.text':      '$a,b$ butun sonlar (ikkalasi ham nol emas) va musbat butun $m$ uchun: $\\;$ (1) $\\gcd(a,b)=\\gcd(b,a)=\\gcd(|a|,|b|)$; $\\;$ (2) har bir butun $k$ uchun $\\gcd(a+kb,\\ b)=\\gcd(a,b)$; $\\;$ (3) $\\gcd(ma,mb)=m\\gcd(a,b)$; $\\;$ (4) agar $d=\\gcd(a,b)$ boʻlsa, $\\gcd\\!\\left(\\tfrac ad,\\tfrac bd\\right)=1$.',
 's3.b10.text':     '**(1)** Son va uning absolyut qiymati bir xil boʻluvchilarga ega, taʼrif esa simmetrik.\\n\\n**(2)** Bu asosiy lemmaning yalangʻoch koʻrinishi: agar $d\\mid a$ va $d\\mid b$ boʻlsa, $d\\mid a+kb$; aksincha, agar $d\\mid a+kb$ va $d\\mid b$ boʻlsa, $d\\mid(a+kb)-kb=a$. Demak $(a,b)$ va $(a+kb,\\,b)$ juftliklari aynan bir xil umumiy boʻluvchilarga, demak bir xil eng kattasiga ega.\\n\\n**(3)** Bezuga koʻra $\\gcd(a,b)$ — $ax+by$ koʻrinishidagi eng kichik musbat son. U holda $(ma)x+(mb)y=m(ax+by)$ koʻrinishidagi eng kichik musbat son $m\\gcd(a,b)$ boʻladi.\\n\\n**(4)** (3) ni $m=d$ bilan $\\tfrac ad$ va $\\tfrac bd$ ga qoʻllaymiz: $$d=\\gcd(a,b)=d\\cdot\\gcd\\left(\\tfrac ad,\\tfrac bd\\right),$$ demak $\\gcd\\left(\\tfrac ad,\\tfrac bd\\right)=1$. $\\blacksquare$',
 's3.b11.name':     'EKUB ning universal xossasi',
 's3.b11.text':     '$a$ va $b$ ning har bir umumiy boʻluvchisi $\\gcd(a,b)$ ni boʻladi. Boshqacha aytganda, EKUB shunchaki eng katta umumiy boʻluvchi emas: u qolgan hammasi oʻtadigan boʻluvchi.',
 's3.b12.text':     '$c\\mid a$ va $c\\mid b$ boʻlsin. Bezu baʼzi butun $x,y$ lar uchun $$\\gcd(a,b)=ax+by $$ ni beradi. $c$ oʻngdagi ikkala hadni ham boʻlgani uchun yigʻindini ham boʻladi, yaʼni $c\\mid\\gcd(a,b)$. $\\blacksquare$',
 's3.b13.q':        'Har bir musbat butun $n$ uchun $\\gcd\\left(n,\\ n+6\\right)$ ni toping.',
 's3.b13.steps.0':  '(2) xossaga koʻra $\\gcd(n,\\ n+6)=\\gcd(n,\\ 6)$.',
 's3.b13.steps.1':  'Demak javob faqat $n$ ning $6$ ga boʻlgandagi qoldigʻiga bogʻliq.',
 's3.b13.steps.2':  'Agar $6\\mid n$ boʻlsa, EKUB $6$ ga teng; agar $n$ $3$ ga karrali boʻlib $2$ ga karrali boʻlmasa — $3$; $2$ ga karrali boʻlib $3$ ga karrali boʻlmasa — $2$; aks holda $1$.',
 's3.b13.steps.3':  'Tekshirish: $\\gcd(9,15)=3$ ✓ va $\\gcd(8,14)=2$ ✓',
 's3.b13.ans':      '$\\gcd(n,n+6)=\\gcd(n,6)\\in\\{1,2,3,6\\}$.',
 's3.b14.text':     '«$\\gcd(n,\\ n+k)=\\gcd(n,k)$» usuli butun bir sinf masalani hal qiladi: ikki sonning ayirmasi ularning umumiy boʻluvchisini chegaralaydi. Ketma-ket kelgan butun sonlar har doim oʻzaro tub, chunki $\\gcd(n,n+1)=\\gcd(n,1)=1$.',
 's4.b0.text':      'Bezu ayniyati shunchaki chiroyli fakt emas: u $ax+by=c$ tenglamasining butun yechimi qachon borligini toʻliq hal qiladi va ularning barchasini yozib berishga imkon yaratadi.',
 's4.b1.name':      'Yechim qachon mavjud',
 's4.b1.text':      '$a,b$ — ikkalasi ham nol boʻlmagan butun sonlar va $d=\\gcd(a,b)$ boʻlsin. $$ax+by=c$$ tenglamasining butun yechimi mavjud boʻlishi uchun $d\\mid c$ boʻlishi **zarur va yetarli**.',
 's4.b2.text':      '**Zarurligi.** Baʼzi butun $x,y$ lar uchun $ax+by=c$ boʻlsin. $d$ soni $a$ ni ham, $b$ ni ham boʻladi, demak ularning istalgan butun kombinatsiyasini, jumladan $ax+by=c$ ni ham.\\n\\n**Yetarliligi.** $d\\mid c$ boʻlsin, $c=dk$. Bezu $ax_0+by_0=d$ boʻladigan $x_0,y_0$ ni beradi. Buni $k$ ga koʻpaytirsak, $$a\\left(kx_0\\right)+b\\left(ky_0\\right)=dk=c ,$$ demak $\\left(kx_0,\\ ky_0\\right)$ juftlik yechim. $\\blacksquare$',
 's4.b3.name':      'Yechimlarning butun oilasi',
 's4.b3.text':      '$d=\\gcd(a,b)$ soni $c$ ni boʻlsin va $\\left(x_0,y_0\\right)$ — $ax+by=c$ ning bitta yechimi boʻlsin. U holda **barcha** butun yechimlar $$x=x_0+\\frac bd\\,t,\\qquad y=y_0-\\frac ad\\,t,\\qquad t\\in\\mathbb{Z}$$ formulalar bilan beriladi va turli $t$ lar turli yechim beradi.',
 's4.b4.text':      '**Bu juftliklar yechim.** Oʻrniga qoʻyamiz: $$a\\left(x_0+\\frac bd t\\right)+b\\left(y_0-\\frac ad t\\right)=ax_0+by_0+\\frac{ab}{d}t-\\frac{ab}{d}t=c \\quad\\checkmark$$\\n\\n**Boshqa yechim yoʻq.** $(x,y)$ istalgan yechim boʻlsin va undan berilganini ayiramiz: $$a\\left(x-x_0\\right)+b\\left(y-y_0\\right)=0\\quad\\Longrightarrow\\quad a\\left(x-x_0\\right)=-b\\left(y-y_0\\right).$$\\n\\n$d$ ga boʻlib, $a=d\\alpha$, $b=d\\beta$ deb yozamiz, bunda $\\gcd(\\alpha,\\beta)=1$: $$\\alpha\\left(x-x_0\\right)=-\\beta\\left(y-y_0\\right).$$\\n\\nOʻng tomon $\\beta$ ga karrali, demak chap tomon ham; $\\gcd(\\alpha,\\beta)=1$ boʻlgani uchun oʻzaro tublik $\\beta\\mid x-x_0$ ni majbur qiladi. $x-x_0=\\beta t$ deb yozamiz; oʻrniga qoʻysak $\\alpha\\beta t=-\\beta\\left(y-y_0\\right)$, demak $y-y_0=-\\alpha t$.\\n\\nBular aynan keltirilgan formulalar, chunki $\\beta=\\tfrac bd$ va $\\alpha=\\tfrac ad$. $\\blacksquare$',
 's4.b5.q':         '$6x+15y=27$ tenglamasini butun sonlarda yeching.',
 's4.b5.steps.0':   '$\\gcd(6,15)=3$ va $3\\mid27$, demak yechim bor.',
 's4.b5.steps.1':   'Butun tenglamani $3$ ga boʻlamiz: $\\ 2x+5y=9$.',
 's4.b5.steps.2':   'Bitta yechim koʻrinib turibdi: $x_0=2$, $y_0=1$ (chunki $4+5=9$).',
 's4.b5.steps.3':   'Teoremaga koʻra barcha yechimlar $x=2+5t$, $y=1-2t$.',
 's4.b5.steps.4':   '$t=1$ da tekshirish: $x=7$, $y=-1$ va $6\\cdot7+15\\cdot(-1)=27$ ✓',
 's4.b5.ans':       '$t\\in\\mathbb{Z}$ uchun $x=2+5t$, $y=1-2t$.',
 's4.b6.q':         '$7x+11y=100$ tenglamasining **musbat** butun yechimlari nechta?',
 's4.b6.steps.0':   '$\\gcd(7,11)=1$ soni $100$ ni boʻladi, demak butun yechimlar bor.',
 's4.b6.steps.1':   'Bittasini topamiz: $y=4$ da $7x=56$, yaʼni $x=8$.',
 's4.b6.steps.2':   'Barcha butun yechimlar: $x=8+11t$, $y=4-7t$.',
 's4.b6.steps.3':   '$x\\ge1$ sharti $t\\ge0$ ni, $y\\ge1$ sharti esa $t\\le0$ ni beradi.',
 's4.b6.steps.4':   'Faqat $t=0$ qoladi.',
 's4.b6.ans':       'Roppa-rosa bitta yechim: $(x,y)=(8,4)$.',
 's4.b7.text':      'Tartib hech qachon oʻzgarmaydi: $\\gcd(a,b)\\mid c$ ekanini **tekshiring**, bitta yechimni **toping** (koʻz bilan yoki Yevklid algoritmini teskari yurgizib), **oilani yozing**, va faqat shundan keyin musbatlik kabi qoʻshimcha shartlarni qoʻying — ular $t$ parametrga nisbatan tengsizliklarga aylanadi.',
 's5.b0.text':      'Biz tub koʻpaytuvchilarga ajratishdan allaqachon foydalandik — endi uning mavjudligi va yagonaligini isbotlash vaqti keldi. Aynan yagonalik ajratishni qurolga aylantiradi: u darajalarni solishtirish va boʻlinuvchanlikni oʻqish imkonini beradi.',
 's5.b1.name':      'Yevklid lemmasi',
 's5.b1.text':      'Agar tub $p$ son $ab$ koʻpaytmani boʻlsa, u holda $p\\mid a$ yoki $p\\mid b$.',
 's5.b2.text':      '$p\\mid ab$ va $p\\nmid a$ boʻlsin. Tub $p$ sonning yagona boʻluvchilari $1$ va $p$, demak $\\gcd(p,a)$ yo $1$, yo $p$; ikkinchisi $p\\mid a$ degani boʻlar edi, bu esa istisno qilingan. Demak $\\gcd(p,a)=1$.\\n\\nBezu $$up+va=1$$ boʻladigan butun $u,v$ ni beradi. Buni $b$ ga koʻpaytiramiz: $$upb+v\\,ab=b .$$ Birinchi had koʻrinib turganidek $p$ ga karrali, ikkinchisi esa $p\\mid ab$ boʻlgani uchun. Demak $p$ ularning yigʻindisini boʻladi, yaʼni $p\\mid b$. $\\blacksquare$',
 's5.b3.text':      'Bu yerda tublik shart. $6$ soni $4\\cdot9=36$ ni boʻladi, ammo na $4$ ni, na $9$ ni boʻlmaydi. Aynan shuning uchun Yevklid lemmasi umuman boʻluvchilar haqida emas, **tub sonlar** haqidagi tasdiqdir.',
 's5.b4.name':      'Arifmetikaning asosiy teoremasi',
 's5.b4.text':      '$n>1$ boʻlgan har bir butun son tub sonlarning koʻpaytmasi boʻladi va bu ajratish koʻpaytuvchilar tartibidan qatʼi nazar **yagona**: $$n=p_1^{\\alpha_1}p_2^{\\alpha_2}\\cdots p_k^{\\alpha_k},\\qquad p_1<p_2<\\dots<p_k,\\quad \\alpha_i\\ge1 .$$',
 's5.b5.text':      '**Mavjudligi (kuchli induksiya).** Tasdiq $n$ dan kichik barcha sonlar uchun oʻrinli deb faraz qilamiz. Agar $n$ tub boʻlsa, ajratma bitta koʻpaytuvchidan iborat. Aks holda $n=ab$, bunda $1<a,b<n$; induksiya farazi boʻyicha $a$ va $b$ tub koʻpaytuvchilarga ajraladi, ikkala ajratmani koʻpaytirsak $n$ uchun ajratma chiqadi ✓\\n\\n**Yagonaligi (induksiya va Yevklid lemmasi).** $$n=p_1p_2\\cdots p_s=q_1q_2\\cdots q_t $$ ikkita tub ajratma boʻlsin. Tub $p_1$ son oʻng tomonni boʻladi, demak Yevklid lemmasiga koʻra u biror $q_j$ ni boʻladi; $q_j$ tub boʻlgani uchun $p_1=q_j$. $p_1$ ni ikkala tomondan qisqartirsak, kichikroq $n/p_1$ sonining ikkita ajratmasi chiqadi. Induksiya boʻyicha ular tartibdan qatʼi nazar bir xil, demak dastlabkilari ham. $\\blacksquare$',
 's5.b6.name':      'Boʻlinuvchanlik — darajalar tilida',
 's5.b6.text':      'Bir xil tub sonlar roʻyxati boʻyicha, nol darajalarga ruxsat berilgan holda $$a=\\prod_i p_i^{\\alpha_i},\\qquad b=\\prod_i p_i^{\\beta_i}$$ boʻlsin. U holda $$a\\mid b\\quad\\Longleftrightarrow\\quad \\text{har bir } i \\text{ uchun } \\alpha_i\\le\\beta_i ,$$ $$\\gcd(a,b)=\\prod_i p_i^{\\min\\left(\\alpha_i,\\beta_i\\right)},\\qquad \\operatorname{lcm}(a,b)=\\prod_i p_i^{\\max\\left(\\alpha_i,\\beta_i\\right)} .$$',
 's5.b7.text':      '**Boʻlinuvchanlik alomati.** Agar barcha $i$ uchun $\\alpha_i\\le\\beta_i$ boʻlsa, $b=a\\cdot\\prod_i p_i^{\\beta_i-\\alpha_i}$ va ikkinchi koʻpaytuvchi butun son, demak $a\\mid b$. Aksincha, $b=ac$ boʻlsin va $c$ ni ajratamiz; yagonalikka koʻra oʻngda $p_i$ ning darajasi $\\alpha_i+(c \\text{ dagi darajasi})\\ge\\alpha_i$, chapda esa $\\beta_i$. Demak $\\beta_i\\ge\\alpha_i$ ✓\\n\\n**EKUB formulasi.** $d=\\prod p_i^{\\gamma_i}$ soni $a$ ni ham, $b$ ni ham aynan $\\gamma_i\\le\\alpha_i$ va $\\gamma_i\\le\\beta_i$, yaʼni $\\gamma_i\\le\\min\\left(\\alpha_i,\\beta_i\\right)$ boʻlganda boʻladi. Eng kattasi $\\gamma_i=\\min\\left(\\alpha_i,\\beta_i\\right)$ da erishiladi ✓\\n\\n**EKUK formulasi** simmetrik: umumiy karralilar — darajalari $\\alpha_i$ dan ham, $\\beta_i$ dan ham kam boʻlmagan sonlar. $\\blacksquare$',
 's5.b8.q':         '$600$ va $540$ ning EKUB va EKUK ini ularning ajratmalaridan toping.',
 's5.b8.steps.0':   '$600=2^{3}\\cdot3\\cdot5^{2}$ va $540=2^{2}\\cdot3^{3}\\cdot5$.',
 's5.b8.steps.1':   'Eng kichik darajalar: $2^{\\min(3,2)}=2^{2}$, $3^{\\min(1,3)}=3$, $5^{\\min(2,1)}=5$.',
 's5.b8.steps.2':   'Demak $\\gcd=4\\cdot3\\cdot5=60$.',
 's5.b8.steps.3':   'Eng kattalari: $2^{3}\\cdot3^{3}\\cdot5^{2}=8\\cdot27\\cdot25=5400$.',
 's5.b8.steps.4':   'Ayniyat boʻyicha tekshirish: $60\\cdot5400=324\\,000=600\\cdot540$ ✓',
 's5.b8.ans':       '$\\gcd=60$, $\\operatorname{lcm}=5400$.',
 's5.b9.name':      'Darajalar boʻlinuvchanlikni meros qiladi',
 's5.b9.text':      'Agar $\\gcd(a,b)=1$ boʻlsa va $ab$ toʻliq $n$-daraja boʻlsa, u holda $a$ va $b$ ning har biri ham toʻliq $n$-daraja boʻladi ($n$ juft boʻlganda ishorasi aniqmas).',
 's5.b10.text':     'Istalgan tub $p$ ni olamiz va uning $a$ va $b$ dagi darajalarini $\\alpha$, $\\beta$ deb belgilaymiz. $\\gcd(a,b)=1$ boʻlgani uchun $p$ ikkalasini ham boʻla olmaydi, demak $\\alpha,\\beta$ dan biri nolga teng.\\n\\nKoʻpaytmadagi $p$ ning darajasi $\\alpha+\\beta$, koʻpaytma esa toʻliq $n$-daraja, demak $n\\mid\\alpha+\\beta$. Bitta qoʻshiluvchi nol boʻlgani uchun $n$ ham $\\alpha$ ni, ham $\\beta$ ni boʻladi.\\n\\nBu har bir tub son uchun oʻrinli, demak $a$ dagi (va $b$ dagi) barcha darajalar $n$ ga karrali: har bir son toʻliq $n$-daraja. $\\blacksquare$',
 's5.b11.text':     'Bu — olimpiada sonlar nazariyasining eng ishonchli ish otlaridan biri. $\\gcd(x,y)=1$ boʻlganda $xy=z^{2}$ dan darhol $x$ va $y$ kvadrat ekani kelib chiqadi — bu aynan barcha Pifagor uchliklarini tavsiflaydigan qadam.',
 's6.b0.name':      'Eng kichik umumiy karrali',
 's6.b0.text':      '$\\operatorname{lcm}(a,b)$ — bu $a$ ga ham, $b$ ga ham boʻlinadigan eng kichik musbat son.',
 's6.b1.name':      'Asosiy ayniyat',
 's6.b1.text':      'Musbat butun $a,b$ sonlar uchun: $$\\gcd(a,b)\\cdot\\operatorname{lcm}(a,b)=ab.$$',
 's6.b2.text':      'Ikkala sonni ham nol darajalarga ruxsat bergan holda tub koʻpaytuvchilarga ajratamiz: $a=\\prod p_i^{\\alpha_i}$, $b=\\prod p_i^{\\beta_i}$. U holda $$\\gcd(a,b)=\\prod p_i^{\\min(\\alpha_i,\\beta_i)},\\qquad \\operatorname{lcm}(a,b)=\\prod p_i^{\\max(\\alpha_i,\\beta_i)}.$$ Endi istalgan sonlar uchun $\\min(\\alpha,\\beta)+\\max(\\alpha,\\beta)=\\alpha+\\beta$ ekanini eslash qoladi, demak $\\gcd\\cdot\\operatorname{lcm}$ dagi darajalar $ab$ dagilari bilan mos tushadi.',
 's6.b3.text':      'Uchta son uchun ayniyat **oʻrinli emas**: umumiy holda $\\gcd(a,b,c)\\cdot\\operatorname{lcm}(a,b,c)\\ne abc$. Masalan, $a=b=c=2$ da chap tomon $2\\cdot2=4$, oʻng tomon esa $8$.',
 's6.b4.name':      'Standart almashtirish',
 's6.b4.text':      'Agar $\\gcd(a,b)=d$ boʻlsa, $a=dx$, $b=dy$ deb yozamiz, bunda $\\gcd(x,y)=1$. U holda $\\operatorname{lcm}(a,b)=dxy$. Bu almashtirish «EKUB va EKUK berilgan» turidagi deyarli har qanday masalani oʻzaro tub $x,y$ ga nisbatan oddiy tenglamaga aylantiradi.',
 's6.b5.name':      'EKUK ning universal xossasi',
 's6.b5.text':      '$a$ va $b$ ning har bir umumiy karralisi $\\operatorname{lcm}(a,b)$ ga boʻlinadi. EKUB ga simmetrik: eng kichik umumiy karrali — qolgan hammasini boʻladigan son.',
 's6.b6.text':      '$L=\\operatorname{lcm}(a,b)$ deb belgilaymiz va $M$ istalgan umumiy karrali boʻlsin. Qoldiqli boʻlamiz: $$M=Lq+r,\\qquad 0\\le r<L .$$\\n\\n$a$ soni $M$ ni ham, $L$ ni ham boʻladi, demak $r=M-Lq$ ni ham; $b$ uchun ham shunday. Demak $r$ — $a$ va $b$ ning umumiy karralisi va $0\\le r<L$.\\n\\nAmmo $L$ — **eng kichik musbat** umumiy karrali, demak $r$ musbat boʻla olmaydi. Shuning uchun $r=0$, yaʼni $L\\mid M$. $\\blacksquare$',
 's6.b7.q':         'Uchta yoʻnalishdagi avtobuslar bekatdan har $12$, $18$ va $30$ daqiqada joʻnaydi va $6{:}00$ da birga joʻnab ketishdi. Ular keyingi marta qachon birga joʻnaydi?',
 's6.b7.steps.0':   'Birgalikdagi joʻnash $12$, $18$, $30$ ning umumiy karralisida sodir boʻladi.',
 's6.b7.steps.1':   'Universal xossaga koʻra har bir shunday moment eng kichigining karralisi, demak bizga $\\operatorname{lcm}(12,18,30)$ kerak.',
 's6.b7.steps.2':   'Ajratamiz: $12=2^{2}\\cdot3$, $18=2\\cdot3^{2}$, $30=2\\cdot3\\cdot5$.',
 's6.b7.steps.3':   'Har bir tub sonni eng yuqori darajasida olamiz: $2^{2}\\cdot3^{2}\\cdot5=180$.',
 's6.b7.steps.4':   '$180$ daqiqa — roppa-rosa uch soat.',
 's6.b7.ans':       '$9{:}00$ da va undan keyin har uch soatda.',
 's6.b8.text':      'Uch va undan ortiq son uchun daraja formulalari oʻrinli qoladi: $$\\gcd=\\prod p^{\\min},\\qquad \\operatorname{lcm}=\\prod p^{\\max},$$ minimum va maksimum butun roʻyxat boʻyicha olinadi. $\\gcd\\cdot\\operatorname{lcm}=$ koʻpaytma ayniyati esa faqat **ikkita** son uchun saqlanadi.',
 's7.b0.name':      'Boʻluvchilar soni va yigʻindisi',
 's7.b0.text':      '$n=p_1^{\\alpha_1}p_2^{\\alpha_2}\\cdots p_k^{\\alpha_k}$ boʻlsin. U holda boʻluvchilar soni va ularning yigʻindisi $$d(n)=\\prod_{i=1}^{k}(\\alpha_i+1),\\qquad \\sigma(n)=\\prod_{i=1}^{k}\\frac{p_i^{\\alpha_i+1}-1}{p_i-1}.$$',
 's7.b1.text':      '$n$ ning har bir boʻluvchisi $p_1^{c_1}\\cdots p_k^{c_k}$ koʻrinishida, bunda $0\\le c_i\\le \\alpha_i$, va turli daraja toʻplamlari turli boʻluvchi beradi. Demak ular roppa-rosa $(\\alpha_1+1)\\cdots(\\alpha_k+1)$ ta. Yigʻindi uchun $$\\left(1+p_1+\\cdots+p_1^{\\alpha_1}\\right)\\cdots\\left(1+p_k+\\cdots+p_k^{\\alpha_k}\\right)$$ koʻpaytmani ochamiz: ochilgandan keyingi har bir had aynan bitta boʻluvchi, va har bir boʻluvchi aynan bir marta uchraydi. Geometrik progressiyalarni yigʻish qoladi.',
 's7.b2.q':         '$360$ ning nechta boʻluvchisi bor va ularning yigʻindisi nimaga teng?',
 's7.b2.steps.0':   '$360=2^3\\cdot3^2\\cdot5$.',
 's7.b2.steps.1':   '$d(360)=(3+1)(2+1)(1+1)=4\\cdot3\\cdot2=24$.',
 's7.b2.steps.2':   '$\\sigma(360)=(1+2+4+8)(1+3+9)(1+5)=15\\cdot13\\cdot6=1170$.',
 's7.b2.ans':       '$d(360)=24$, $\\sigma(360)=1170$',
 's7.b3.text':      'Foydali natija: $d(n)$ toq boʻlishi uchun $n$ toʻliq kvadrat boʻlishi zarur va yetarli. Boʻluvchilar $(e,\\,n/e)$ juftliklarga birlashadi va juftsiz qoladigan yagona boʻluvchi $e=\\sqrt{n}$.',
 's7.b4.name':      'Multiplikativ funksiya',
 's7.b4.text':      'Musbat butun sonlarda aniqlangan $f$ funksiya, agar $f(1)=1$ boʻlsa va $$\\text{barcha oʻzaro tub } m,n \\text{ uchun } f(mn)=f(m)f(n)$$ boʻlsa, **multiplikativ** deyiladi.',
 's7.b5.name':      '$d$ va $\\sigma$ ning multiplikativligi',
 's7.b5.text':      '$d(n)$ (boʻluvchilar soni) va $\\sigma(n)$ (ularning yigʻindisi) funksiyalari multiplikativ: $\\gcd(m,n)=1$ boʻlganda $$d(mn)=d(m)\\,d(n),\\qquad \\sigma(mn)=\\sigma(m)\\,\\sigma(n).$$',
 's7.b6.text':      '$\\gcd(m,n)=1$ boʻlsin. Asosiy kuzatish shuki, $mn$ ning boʻluvchilari $$e\\mid m,\\qquad f\\mid n$$ boʻluvchilar **juftliklari** bilan oʻzaro bir qiymatli mos tushadi, moslik esa $(e,f)\\mapsto ef$.\\n\\n**Nega bu biyeksiya.** Har bir juftlik aniqki $mn$ ning $ef$ boʻluvchisini beradi. Aksincha, $g\\mid mn$ berilgan boʻlsa, $$e=\\gcd(g,m),\\qquad f=\\gcd(g,n)$$ deymiz. $m$ va $n$ ning oʻzaro tubligi (tub darajalarni solishtirish orqali) $g=ef$ ekanini koʻrsatadi va bu tasvir yagona: $g$ ning har bir tub boʻluvchisi $m$ va $n$ dan aynan bittasini boʻladi, demak butunlay $e$ ga yoki butunlay $f$ ga tushadi.\\n\\n**Sanash.** Juftliklar soni $d(m)d(n)$, bu birinchi formulani beradi. Barcha koʻpaytmalar yigʻindisi esa $$\\sum_{e\\mid m}\\ \\sum_{f\\mid n} ef=\\left(\\sum_{e\\mid m}e\\right)\\left(\\sum_{f\\mid n}f\\right)=\\sigma(m)\\sigma(n),$$ bu ikkinchisini beradi. $\\blacksquare$',
 's7.b7.text':      'Multiplikativlik aynan $d(n)$ va $\\sigma(n)$ formulalarining nega **tub sonlar boʻyicha koʻpaytma** koʻrinishida boʻlishini tushuntiradi: funksiyani tub darajalarda tushunsangiz, u oʻzi yigʻiladi.',
 's7.b8.name':      'Barcha boʻluvchilarning koʻpaytmasi',
 's7.b8.text':      '$n>1$ ning barcha musbat boʻluvchilari koʻpaytmasi $$\\prod_{e\\mid n}e=n^{\\,d(n)/2}$$ ga teng.',
 's7.b9.text':      'Koʻpaytmani $P$ deb belgilaymiz va uni ikki marta — boʻluvchilarning oʻsish va kamayish tartibida yozamiz. Boʻluvchilar $\\left(e,\\ \\tfrac ne\\right)$ juftliklarga birlashadi, har bir juftlikning koʻpaytmasi $n$.\\n\\nRasmiy ravishda $$P^{2}=\\prod_{e\\mid n}e\\ \\cdot\\ \\prod_{e\\mid n}\\frac ne=\\prod_{e\\mid n}\\left(e\\cdot\\frac ne\\right)=n^{\\,d(n)} ,$$ chunki $e$ barcha boʻluvchilardan oʻtganda $\\tfrac ne$ ham shunday qiladi.\\n\\nKvadrat ildiz olib, $P=n^{\\,d(n)/2}$. $\\blacksquare$\\n\\n**Izoh:** $\\tfrac{d(n)}2$ darajasi yarim butun boʻlishi mumkin — bu aynan $n$ toʻliq kvadrat boʻlganda sodir boʻladi, bunda juftsiz boʻluvchi $\\sqrt n$.',
 's7.b10.q':        'Roppa-rosa $10$ ta boʻluvchiga ega eng kichik musbat butun sonni toping.',
 's7.b10.steps.0':  'Agar $n=\\prod p_i^{\\alpha_i}$ boʻlsa, $d(n)=\\prod\\left(\\alpha_i+1\\right)$, demak $10$ ni birdan katta koʻpaytuvchilar koʻpaytmasi sifatida yozamiz.',
 's7.b10.steps.1':  'Variantlar: $10$ va $5\\cdot2$.',
 's7.b10.steps.2':  '$10$ ajratmasi $(9)$ darajalarni beradi: bunday sonlarning eng kichigi $2^{9}=512$.',
 's7.b10.steps.3':  '$5\\cdot2$ ajratmasi $(4,1)$ darajalarni beradi; kattaroq darajani kichikroq tub songa qoʻyamiz: $2^{4}\\cdot3=48$.',
 's7.b10.steps.4':  'Solishtiramiz: $48<512$.',
 's7.b10.ans':      '$48$; uning boʻluvchilari $1,2,3,4,6,8,12,16,24,48$ — roppa-rosa oʻnta.',
 's7.b11.text':     '$\\sigma$ funksiyasi ortida qadimiy tushuncha turadi: agar $\\sigma(n)=2n$ boʻlsa, yaʼni $n$ oʻzining xos boʻluvchilari yigʻindisiga teng boʻlsa, u **mukammal** son deyiladi. Dastlabki mukammal sonlar $6$, $28$, $496$, $8128$; har bir juft mukammal son $2^{p-1}\\left(2^{p}-1\\right)$ koʻrinishida, bunda $2^{p}-1$ tub, toq mukammal son mavjudmi degan savol esa hanuz ochiq.',
 's8.b0.text':      '$n!$ faktorial $n$ gacha boʻlgan hamma narsani koʻpaytiradi va koʻpincha faktorialning oʻzi emas, berilgan tub son uning ichida **necha marta** turgani kerak boʻladi. Lejandr formulasi shunga javob beradi.',
 's8.b1.name':      'Lejandr formulasi',
 's8.b1.text':      '$n!$ dagi tub $p$ sonning darajasi $$v_p(n!)=\\left\\lfloor\\frac np\\right\\rfloor+\\left\\lfloor\\frac n{p^{2}}\\right\\rfloor+\\left\\lfloor\\frac n{p^{3}}\\right\\rfloor+\\cdots$$ ga teng (yigʻindi chekli: $p^{k}>n$ boʻlgach hadlar nolga aylanadi).',
 's8.b2.text':      'Har bir koʻpaytuvchining hissasini «qavat-qavat» sanaymiz.\\n\\n$1,2,\\dots,n$ orasida roppa-rosa $\\left\\lfloor\\tfrac np\\right\\rfloor$ tasi $p$ ga karrali, yaʼni $p,2p,3p,\\dots$; ularning har biri kamida bitta $p$ darajasini beradi.\\n\\nXuddi shu sonlar orasida roppa-rosa $\\left\\lfloor\\tfrac n{p^{2}}\\right\\rfloor$ tasi $p^{2}$ ga karrali; ularning har biri allaqachon sanalganidan **yana bitta** daraja qoʻshadi.\\n\\nUmuman, $p^{k}$ ga karralilar $k$-qavatda bittadan qoʻshimcha daraja beradi, ular esa $\\left\\lfloor\\tfrac n{p^{k}}\\right\\rfloor$ ta.\\n\\nQavatlarni qoʻshsak aynan keltirilgan yigʻindi chiqadi: $p^{m}$ ga boʻlinadigan va undan nariga bormaydigan son roppa-rosa $m$ marta, dastlabki $m$ ta qavatning har birida bir martadan sanaladi. $\\blacksquare$',
 's8.b3.q':         '$100!$ nechta nol bilan tugaydi?',
 's8.b3.steps.0':   'Oxiridagi nol — bu $10=2\\cdot5$ koʻpaytuvchi, faktorialda esa ikkilar beshlardan doim koʻp.',
 's8.b3.steps.1':   'Demak javob $v_5(100!)$.',
 's8.b3.steps.2':   '$\\left\\lfloor\\tfrac{100}{5}\\right\\rfloor=20$, $\\left\\lfloor\\tfrac{100}{25}\\right\\rfloor=4$, $\\left\\lfloor\\tfrac{100}{125}\\right\\rfloor=0$.',
 's8.b3.steps.3':   'Jami $20+4=24$.',
 's8.b3.ans':       '$24$ ta nol.',
 's8.b4.q':         '$3^{k}\\mid50!$ boʻladigan eng katta $k$ ni toping.',
 's8.b4.steps.0':   '$\\left\\lfloor\\tfrac{50}{3}\\right\\rfloor=16$ ta uchga karrali son.',
 's8.b4.steps.1':   '$\\left\\lfloor\\tfrac{50}{9}\\right\\rfloor=5$ ta toʻqqizga karrali son yana bittadan uch beradi.',
 's8.b4.steps.2':   '$\\left\\lfloor\\tfrac{50}{27}\\right\\rfloor=1$, va $\\left\\lfloor\\tfrac{50}{81}\\right\\rfloor=0$.',
 's8.b4.steps.3':   'Qoʻshamiz: $16+5+1=22$.',
 's8.b4.ans':       '$k=22$.',
 's8.b5.text':      'Xuddi shu formula $\\dbinom nk=\\dfrac{n!}{k!\\,(n-k)!}$ binomial koeffitsiyenti har doim butun son ekanini koʻrsatadi: maxrajdagi har bir tub sonning darajasi suratdagisidan oshmaydi, chunki $$\\left\\lfloor x+y\\right\\rfloor\\ \\ge\\ \\left\\lfloor x\\right\\rfloor+\\left\\lfloor y\\right\\rfloor .$$',
 's9.b0.text':      'Shu paytgacha biz boʻluvchilarni sanadik. Endi berilgan songa **oʻzaro tub** boʻlgan sonlarni sanaymiz — va bu sanoq darajalarning modul boʻyicha qanday tutishini boshqarishini koʻramiz.',
 's9.b1.name':      'Eyler funksiyasi',
 's9.b1.text':      '$\\varphi(n)$ — $1,2,\\dots,n$ orasidagi $n$ ga oʻzaro tub sonlar soni. Masalan, $$\\varphi(1)=1,\\quad\\varphi(6)=2\\ (\\text{yaʼni } 1,5),\\quad\\varphi(7)=6,\\quad\\varphi(12)=4\\ (\\text{yaʼni } 1,5,7,11).$$',
 's9.b2.name':      'Eylerning koʻpaytma formulasi',
 's9.b2.text':      'Agar $n=p_1^{\\alpha_1}\\cdots p_k^{\\alpha_k}$ boʻlsa, u holda $$\\varphi(n)=n\\prod_{i=1}^{k}\\left(1-\\frac1{p_i}\\right)=\\prod_{i=1}^{k}p_i^{\\alpha_i-1}\\left(p_i-1\\right).$$ Xususan, tub $p$ uchun $\\varphi(p)=p-1$ va $\\varphi\\left(p^{\\alpha}\\right)=p^{\\alpha}-p^{\\alpha-1}$.',
 's9.b3.text':      '**1-qadam: tub daraja.** $1,\\dots,p^{\\alpha}$ orasida $p^{\\alpha}$ ga oʻzaro tub *boʻlmagan* sonlar aynan $p$ ga karralilar, ular esa $p^{\\alpha-1}$ ta. Demak $$\\varphi\\left(p^{\\alpha}\\right)=p^{\\alpha}-p^{\\alpha-1}=p^{\\alpha}\\left(1-\\frac1p\\right) \\quad\\checkmark$$\\n\\n**2-qadam: multiplikativlik.** $\\gcd(m,n)=1$ boʻlsin; $\\varphi(mn)=\\varphi(m)\\varphi(n)$ ekanini koʻrsatamiz. $1,\\dots,mn$ sonlarni $m$ satr va $n$ ustundan iborat jadvalga joylaymiz, $x$ ni $\\left(x\\bmod m,\\ x\\bmod n\\right)$ katakka qoʻyamiz. Xitoy qoldiqlar teoremasiga koʻra bu biyeksiya: qoldiqlarning har bir juftligi roppa-rosa bir marta uchraydi.\\n\\nEndi $x$ soni $mn$ ga oʻzaro tub boʻlishi uchun u $m$ ga ham, $n$ ga ham oʻzaro tub boʻlishi, yaʼni **ikkala** koordinata oʻz moduliga oʻzaro tub boʻlishi kerak. Birinchi koordinata uchun $\\varphi(m)$ ta, ikkinchisi uchun $\\varphi(n)$ ta imkoniyat bor va ular mustaqil tanlanadi: $$\\varphi(mn)=\\varphi(m)\\varphi(n) \\quad\\checkmark$$\\n\\n**3-qadam: yigʻish.** Turli tub sonlarning darajalari juft-jufti bilan oʻzaro tub, demak $$\\varphi(n)=\\prod_i\\varphi\\left(p_i^{\\alpha_i}\\right)=n\\prod_i\\left(1-\\frac1{p_i}\\right). \\qquad\\blacksquare$$',
 's9.b4.q':         '$\\varphi(360)$ ni hisoblang.',
 's9.b4.steps.0':   '$360=2^{3}\\cdot3^{2}\\cdot5$.',
 's9.b4.steps.1':   'Formula $\\varphi(360)=360\\left(1-\\tfrac12\\right)\\left(1-\\tfrac13\\right)\\left(1-\\tfrac15\\right)$ ni beradi.',
 's9.b4.steps.2':   'Qadamma-qadam: $360\\cdot\\tfrac12=180$, soʻng $180\\cdot\\tfrac23=120$, soʻng $120\\cdot\\tfrac45=96$.',
 's9.b4.steps.3':   'Ikkinchi koʻrinish bilan tekshirish: $2^{2}\\cdot1\\ \\cdot\\ 3^{1}\\cdot2\\ \\cdot\\ 5^{0}\\cdot4=4\\cdot6\\cdot4=96$ ✓',
 's9.b4.ans':       '$\\varphi(360)=96$.',
 's9.b5.name':      'Eyler funksiyasining xossalari',
 's9.b5.text':      '(1) Har bir $n>2$ uchun $\\varphi(n)$ juft; $\\;$ (2) $\\displaystyle\\sum_{d\\mid n}\\varphi(d)=n$; $\\;$ (3) $\\gcd(m,n)=1$ boʻlganda $\\varphi(mn)=\\varphi(m)\\varphi(n)$.',
 's9.b6.text':      '**(1)** Agar $n$ ning toq tub boʻluvchisi $p$ boʻlsa, formuladagi $p-1$ koʻpaytuvchi juft, demak koʻpaytma ham. Aks holda $n=2^{\\alpha}$ va $\\alpha\\ge2$ ($n>2$ boʻlgani uchun), $\\varphi(n)=2^{\\alpha-1}$ esa juft ✓\\n\\n**(2)** $1,2,\\dots,n$ sonlarni $n$ bilan EKUB qiymati boʻyicha saralaymiz. $\\gcd(x,n)=d$ boʻlgan sonlar aynan $x=d\\,y$ koʻrinishida, bunda $1\\le y\\le\\tfrac nd$ va $\\gcd\\left(y,\\tfrac nd\\right)=1$; bunday $y$ lar $\\varphi\\left(\\tfrac nd\\right)$ ta.\\n\\nDemak $$n=\\sum_{d\\mid n}\\varphi\\!\\left(\\frac nd\\right)=\\sum_{d\\mid n}\\varphi(d),$$ chunki $d$ boʻluvchilardan oʻtganda $\\tfrac nd$ ham shunday qiladi ✓\\n\\n**(3)** Formulani keltirib chiqarishda yuqorida isbotlandi. $\\blacksquare$',
 's9.b7.name':      'Ferma kichik teoremasi',
 's9.b7.text':      'Agar $p$ tub boʻlsa va $p\\nmid a$ boʻlsa, u holda $$a^{\\,p-1}\\equiv1\\pmod p .$$ $p\\nmid a$ sharti boʻlmasa, $a^{p}\\equiv a\\pmod p$ koʻrinishi **har qanday** butun $a$ uchun oʻrinli.',
 's9.b8.text':      'Noldan farqli $1,2,\\dots,p-1$ qoldiqlarni olamiz va har birini $a$ ga koʻpaytiramiz.\\n\\n**1-qadam: xuddi shu toʻplam qaytadi.** $a\\cdot1,\\dots,a(p-1)$ sonlari juft-jufti bilan turli, noldan farqli qoldiq beradi: agar $ai\\equiv aj$ boʻlsa, $p\\mid a(i-j)$, va $p\\nmid a$ boʻlgani uchun Yevklid lemmasi $p\\mid i-j$ ni beradi, demak $i=j$ (chunki $|i-j|<p$). Hech biri nol emas, chunki $p\\nmid a$ va $p\\nmid i$.\\n\\nDemak bu $p-1$ ta son $1,\\dots,p-1$ qoldiqlarning oʻzi, faqat boshqa tartibda.\\n\\n**2-qadam: hammasini koʻpaytiramiz.** $$a^{\\,p-1}(p-1)!\\ \\equiv\\ (p-1)!\\pmod p .$$\\n\\n**3-qadam: qisqartiramiz.** $(p-1)!$ soni $p$ ga boʻlinmaydi (uning barcha koʻpaytuvchilari kichikroq), demak uni qisqartirish mumkin: $$a^{\\,p-1}\\equiv1\\pmod p . \\qquad\\blacksquare$$',
 's9.b9.q':         '$2^{1000}$ ni $13$ ga boʻlgandagi qoldiqni toping.',
 's9.b9.steps.0':   '$13$ tub va $13\\nmid2$, demak $2^{12}\\equiv1\\pmod{13}$.',
 's9.b9.steps.1':   'Koʻrsatkichni $12$ ga boʻlamiz: $1000=12\\cdot83+4$.',
 's9.b9.steps.2':   'U holda $2^{1000}=\\left(2^{12}\\right)^{83}\\cdot2^{4}\\equiv16\\equiv3\\pmod{13}$.',
 's9.b9.ans':       'Qoldiq $3$ ga teng.',
 's9.b10.name':     'Eyler teoremasi',
 's9.b10.text':     'Agar $\\gcd(a,n)=1$ boʻlsa, u holda $$a^{\\varphi(n)}\\equiv1\\pmod n .$$ Tub $n=p$ uchun bu aynan Ferma kichik teoremasi, chunki $\\varphi(p)=p-1$.',
 's9.b11.text':     '$r_1,\\dots,r_{\\varphi(n)}$ — $1$ dan $n$ gacha boʻlgan, $n$ ga oʻzaro tub qoldiqlar boʻlsin.\\n\\n**1-qadam: $a$ ga koʻpaytirish ularni oʻrin almashtiradi.** Har bir $ar_i$ soni $n$ ga oʻzaro tub (umumiy tub boʻluvchi $a$ ni yoki $r_i$ ni boʻlar edi) va ular modul $n$ boʻyicha juft-jufti bilan turli: $ar_i\\equiv ar_j$ dan $n\\mid a\\left(r_i-r_j\\right)$, $\\gcd(a,n)=1$ esa $n\\mid r_i-r_j$ ni, yaʼni $r_i=r_j$ ni beradi.\\n\\nDemak $ar_1,\\dots,ar_{\\varphi(n)}$ — xuddi shu qoldiqlar toʻplami, faqat oʻrin almashtirilgan.\\n\\n**2-qadam: koʻpaytiramiz va qisqartiramiz.** $$a^{\\varphi(n)}\\prod_i r_i\\ \\equiv\\ \\prod_i r_i\\pmod n ,$$ va $\\prod_i r_i$ soni $n$ ga oʻzaro tub, demak u qisqaradi: $$a^{\\varphi(n)}\\equiv1\\pmod n . \\qquad\\blacksquare$$',
 's9.b12.q':        '$7^{2024}$ ning oxirgi ikki raqamini toping.',
 's9.b12.steps.0':  'Oxirgi ikki raqam — bu modul $100$ boʻyicha qoldiq.',
 's9.b12.steps.1':  '$\\gcd(7,100)=1$ va $\\varphi(100)=100\\left(1-\\tfrac12\\right)\\left(1-\\tfrac15\\right)=40$.',
 's9.b12.steps.2':  'Eyler teoremasi $7^{40}\\equiv1\\pmod{100}$ ni beradi.',
 's9.b12.steps.3':  '$2024=40\\cdot50+24$, demak $7^{2024}\\equiv7^{24}$.',
 's9.b12.steps.4':  'Hisoblaymiz: $7^{2}=49$ va $7^{4}=2401\\equiv1\\pmod{100}$.',
 's9.b12.steps.5':  'Demak $7^{24}=\\left(7^{4}\\right)^{6}\\equiv1$.',
 's9.b12.ans':      'U $01$ bilan tugaydi.',
 's9.b13.text':     'Eʼtibor bering: $7$ ning modul $100$ boʻyicha haqiqiy tartibi $4$, $40$ emas. Eyler teoremasi darajalar takrorlana boshlaydigan koʻrsatkich uchun **yuqoridan baho** beradi; haqiqiy davr har doim $\\varphi(n)$ ni boʻladi, ammo ancha kichik boʻlishi mumkin.',
 's9.b14.name':     'Vilson teoremasi',
 's9.b14.text':     '$p>1$ butun son tub boʻlishi uchun $$(p-1)!\\ \\equiv\\ -1\\pmod p$$ boʻlishi **zarur va yetarli**.',
 's9.b15.text':     '**$p$ tub boʻlsin.** $p=2$ uchun bevosita tekshiramiz: $1!\\equiv-1\\pmod2$ ✓ Endi $p$ toq boʻlsin.\\n\\nHar bir $a\\in\\{1,\\dots,p-1\\}$ shu oraliqda yagona teskari element $a^{-1}$ ga ega: Bezu $ua+vp=1$ boʻladigan $u,v$ ni beradi, yaʼni $ua\\equiv1$.\\n\\nQaysi sonlar oʻziga oʻzi teskari? $a^{2}\\equiv1$ sharti $p\\mid(a-1)(a+1)$ degani, demak Yevklid lemmasi $a\\equiv1$ yoki $a\\equiv-1$ ni, yaʼni $a=1$ yoki $a=p-1$ ni beradi.\\n\\nQolgan $p-3$ ta son koʻpaytmasi $1$ ga teng boʻlgan $\\tfrac{p-3}{2}$ ta $\\left\\{a,a^{-1}\\right\\}$ juftlikka ajraladi. Demak $$(p-1)!\\equiv1\\cdot(p-1)\\equiv-1\\pmod p \\quad\\checkmark$$\\n\\n**$p$ murakkab boʻlsin,** $p=ab$ va $1<a<p$. U holda $a$ — $(p-1)!$ koʻpaytuvchilaridan biri, demak $a\\mid(p-1)!$. Agar $(p-1)!\\equiv-1\\pmod p$ oʻrinli boʻlganda, $a$ soni $(p-1)!+1$ ni ham boʻlar, demak ularning ayirmasi $1$ ni ham boʻlar edi ✗ ($p=4$ holi bevosita tekshiriladi: $3!=6\\equiv2\\pmod4$.) $\\blacksquare$',
 's9.b16.text':     'Vilson teoremasi — tublik haqidagi yagona elementar tasdiq boʻlib, u haqiqiy **mezon**: zarur va yetarli. Katta sonlarni tekshirish uchun u foydasiz ($(p-1)!$ ni hisoblash boʻluvchilarni saralashdan qimmatroq), ammo masalalarda baʼzan hal qiluvchi boʻladi.\\n\\n**Natija.** Tub $p>2$ uchun $(p-2)!\\equiv1\\pmod p$, chunki $(p-1)!=(p-1)\\cdot(p-2)!\\equiv-(p-2)!$.',
 's10.b0.text':     'Yevklid algoritmi oddiy sonlar bilan cheklanmaydi. Ketma-ketlik takroriy ayirishdek tutsa, uning EKUB i ham Yevklid algoritmiga boʻysunadi — ammo **indekslar** darajasida.',
 's10.b1.name':     'Mersenn sonlarining EKUB i',
 's10.b1.text':     'Barcha musbat butun $m,n$ va istalgan butun $a>1$ uchun $$\\gcd\\left(a^{m}-1,\\ a^{n}-1\\right)=a^{\\gcd(m,n)}-1 .$$',
 's10.b2.text':     '$m>n$ boʻlsin va $m=nq+r$ qoldiqli boʻlish boʻlsin. Asosiy ayniyat: $$a^{m}-1=a^{\\,m-n}\\left(a^{n}-1\\right)+\\left(a^{\\,m-n}-1\\right).$$\\n\\nU koʻrsatadiki, koʻrsatkichni EKUB ni oʻzgartirmagan holda $n$ ga kamaytirish mumkin: $$\\gcd\\left(a^{m}-1,\\ a^{n}-1\\right)=\\gcd\\left(a^{\\,m-n}-1,\\ a^{n}-1\\right).$$\\n\\nBuni $q$ marta takrorlasak $$\\gcd\\left(a^{r}-1,\\ a^{n}-1\\right)$$ ga kelamiz, demak koʻrsatkichlar aynan Yevklid algoritmidagi sonlar kabi tutadi: $(m,n)\\to(n,r)$.\\n\\nAlgoritm koʻrsatkichlardan biri nolga aylanganda, ikkinchisi esa $\\gcd(m,n)$ ga teng boʻlganda toʻxtaydi; $a^{0}-1=0$ boʻlgani uchun $$\\gcd\\left(a^{\\gcd(m,n)}-1,\\ 0\\right)=a^{\\gcd(m,n)}-1 . \\qquad\\blacksquare$$',
 's10.b3.q':        '$\\gcd\\left(2^{30}-1,\\ 2^{24}-1\\right)$ ni toping.',
 's10.b3.steps.0':  'Teorema $2^{\\gcd(30,24)}-1$ ni beradi.',
 's10.b3.steps.1':  '$\\gcd(30,24)=6$.',
 's10.b3.steps.2':  'Demak EKUB $2^{6}-1=63$.',
 's10.b3.steps.3':  'Tekshirish: $2^{30}-1=1\\,073\\,741\\,823=63\\cdot17\\,043\\,521$ ✓',
 's10.b3.ans':      '$63$.',
 's10.b4.name':     'Fibonachchi sonlarining EKUB i',
 's10.b4.text':     '$F_1=F_2=1$, $F_{k+1}=F_k+F_{k-1}$ Fibonachchi sonlari uchun $$\\gcd\\left(F_m,F_n\\right)=F_{\\gcd(m,n)} .$$',
 's10.b5.text':     '**1-qadam: qoʻshni Fibonachchi sonlari oʻzaro tub.** $F_{k+1}=F_k+F_{k-1}$ dan $\\gcd\\left(F_{k+1},F_k\\right)=\\gcd\\left(F_k,F_{k-1}\\right)$, boshigacha tushsak $\\gcd\\left(F_2,F_1\\right)=1$.\\n\\n**2-qadam: qoʻshish formulasi.** $n$ boʻyicha induksiya $$F_{m+n}=F_mF_{n+1}+F_{m-1}F_n$$ ni tasdiqlaydi.\\n\\n**3-qadam: bitta Yevklid qadami.** $m>n$ olamiz va formulani $F_m=F_{(m-n)+n}$ ga qoʻllaymiz: $$F_m=F_{m-n}F_{n+1}+F_{m-n-1}F_n .$$\\n\\nIkkinchi had $F_n$ ga karrali, demak $$\\gcd\\left(F_m,F_n\\right)=\\gcd\\left(F_{m-n}F_{n+1},\\ F_n\\right).$$\\n\\n1-qadamga koʻra $F_{n+1}$ va $F_n$ oʻzaro tub, demak $F_{n+1}$ koʻpaytuvchini tashlab yuborish mumkin: $$\\gcd\\left(F_m,F_n\\right)=\\gcd\\left(F_{m-n},\\ F_n\\right).$$\\n\\n**4-qadam: tushish.** Endi indekslar aynan Yevklid algoritmidagi sonlar kabi tutadi, demak jarayon $\\left(F_{\\gcd(m,n)},\\ F_0\\right)$ juftlikka yetadi, $F_0=0$, javob esa $F_{\\gcd(m,n)}$. $\\blacksquare$',
 's10.b6.q':        '$\\gcd\\left(F_{12},F_{18}\\right)$ ni toping.',
 's10.b6.steps.0':  '$\\gcd(12,18)=6$, demak javob $F_6$.',
 's10.b6.steps.1':  'Roʻyxat: $F_1=1$, $F_2=1$, $F_3=2$, $F_4=3$, $F_5=5$, $F_6=8$.',
 's10.b6.steps.2':  'Tekshirish: $F_{12}=144$, $F_{18}=2584$ va $\\gcd(144,2584)=8$ ✓',
 's10.b6.ans':      '$F_6=8$.',
 's10.b7.text':     'Ikkala teorema ham bir xil ishlaydi: $(m,n)$ juftlikni $(m-n,\\ n)$ bilan almashtiradigan ayniyat toping, soʻng indekslarda Yevklid algoritmini yurgizing. Bu usul koʻp ketma-ketliklarga koʻchadi — faqat qoʻshni hadlar oʻzaro tub boʻlishi kerak.',
 's10.b8.text':     'Birinchi teoremaning nafis natijasi bor: **$a^{m}-1$ soni $a^{n}-1$ ga aynan $m$ soni $n$ ga boʻlinganda boʻlinadi.** Aynan shuning uchun $2^{p}-1$ faqat tub $p$ da tub boʻlishi mumkin — bu Mersenn sonlari nazariyasidagi birinchi qadam.',
 's11.b0.items.0':  '**Nomaʼlumni chiziqli kombinatsiya bilan yoʻqoting.** Agar $d$ soni $n$ ga bogʻliq ikkita ifodani boʻlsa, koeffitsiyentlarni $n$ qisqaradigan qilib tanlang. «Bu kasr qisqarmasligini isbotlang» turidagi masalalarning uchdan ikki qismi shunga tushadi.',
 's11.b0.items.1':  '**Butun qismni ajrating.** $\\dfrac{n^2+1}{n+1}$ dan $n-1+\\dfrac{2}{n+1}$ chiqadi, demak $n+1\\mid 2$. Bu usul boʻlinuvchanlikni chekli saralashga aylantiradi.',
 's11.b0.items.2':  '**Qoldiq boʻyicha hollarga ajrating.** $m$ ga boʻlinishni isbotlash uchun $n=mk, mk+1,\\ldots,mk+(m-1)$ hollarni koʻring.',
 's11.b0.items.3':  '**Ketma-ket sonlardan foydalaning.** Ketma-ket kelgan istalgan $k$ ta son orasida roppa-rosa bittasi $k$ ga boʻlinadi; ketma-ket kelgan $k$ ta sonning koʻpaytmasi $k!$ ga boʻlinadi.',
 's11.b0.items.4':  '**Tub ajratmalarga oʻting.** «Kvadrat», «kub», «EKUB», «EKUK» soʻzlari qatnashgan masalalar deyarli har doim tub darajalar tilida eng toza koʻrinadi.',
 's11.b0.items.5':  '**Kattalikni baholang.** Agar $d\\mid N$ va $d>\\sqrt{N}$ boʻlsa, $N/d<\\sqrt{N}$ — bu koʻpincha saralashni deyarli yoʻqqa chiqaradi.',
}
