# -*- coding: utf-8 -*-
"""Uzbek for topic 5.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Ayniyatlar va koʻpaytuvchilarga ajratish',
 'sub':             'Standart ayniyatlar, guruhlash, simmetrik yigʻindilar va Bezu teoremasi — ifodani koʻpaytmaga aylantiradigan qurollar.',
 'goals.0':         'Asosiy ayniyatlarni yoddan bilish va ularni yashiringan koʻrinishda ham tanish.',
 'goals.1':         'Koʻphadlarni guruhlash va «qoʻshib-ayirish» usuli bilan ajratish.',
 'goals.2':         'Faqat $a+b$ va $ab$ ni bilgan holda $a^2+b^2$, $a^3+b^3$ va shunga oʻxshashlarni hisoblash.',
 'goals.3':         'Koʻphadning ildizlarini topish va Bezu teoremasi yordamida uni ajratish.',
 's0.h':            'Nega koʻpaytuvchilarga ajratish hamma narsani hal qiladi',
 's1.h':            'Yoddan bilish kerak boʻlgan ayniyatlar',
 's2.h':            '$a^{n}\\pm b^{n}$ ni ajratish',
 's3.h':            'Guruhlash va qoʻshib-ayirish usuli',
 's4.h':            'Simmetrik yigʻindilar: hammasi $a+b$ va $ab$ dan',
 's5.h':            'Bezu teoremasi: ildizlarni qidirish',
 's6.h':            'Nyuton binomi',
 's7.h':            'Simmetrik koʻphadlar va Nyuton ayniyatlari',
 's8.h':            'Butun boshli masalani yechadigan uchta usul',
 's0.b0.text':      'Yigʻindi son haqida deyarli hech narsa aytmaydi. Koʻpaytma esa hamma narsani aytadi. $N=7\\cdot13$ ekanini bilsangiz, $N$ ning boʻluvchilarini darhol bilasiz, $N$ murakkab ekanini bilasiz va ifoda qachon nolga aylanishini aniq bilasiz. Shuning uchun har qanday ifoda bilan qilinadigan birinchi ish — uni koʻpaytuvchilarga ajratishga urinish.',
 's0.b1.text':      'Koʻpaytuvchilarga ajratish hal qiladigan uch xil masala:\\n\\n**Boʻlinuvchanlik.** «$n^{3}-n$ soni $6$ ga boʻlinishini isbotlang» — ajrating: $n^{3}-n=(n-1)n(n+1)$, ketma-ket kelgan uchta sonning koʻpaytmasi.\\n\\n**Tublik.** «$n>1$ da $n^{4}+4$ murakkab ekanini isbotlang» — uni har biri birdan katta ikkita koʻpaytuvchiga ajrating.\\n\\n**Tenglamalar.** «$x^{3}=x$ ni yeching» — hamma narsani chapga oʻtkazing: $x(x-1)(x+1)=0$, ildizlar koʻrinib turadi.',
 's0.b2.text':      'Olimpiada masalasida ajratma deyarli hech qachon koʻrinib turmaydi. Shuning uchun quyida usullarning toʻliq toʻplami keltirilgan — eng oddiy ayniyatlardan Bezu teoremasigacha.',
 's1.b0.text':      'Bularni bir zumda va ikkala yoʻnalishda ham — chapdan oʻngga va oʻngdan chapga — tanish kerak. Oʻngdan chapga oʻqish aynan koʻpaytuvchilarga ajratish degani.',
 's1.b1.head.0':    'Ayniyat',
 's1.b1.head.1':    'Qayerda uchraydi',
 's1.b1.rows.0.1':  'hamma joyda',
 's1.b1.rows.1.1':  'sonlar nazariyasidagi eng foydali yagona formula',
 's1.b1.rows.2.1':  'kublar, binom',
 's1.b1.rows.3.1':  'darajalar yigʻindisining boʻlinuvchanligi',
 's1.b1.rows.4.1':  'xuddi shu',
 's1.b1.rows.5.1':  '$a-b$ har doim $a^n-b^n$ ni boʻladi',
 's1.b1.rows.6.0':  'toq $n$ uchun $a^{n}+b^{n}=(a+b)(a^{n-1}-a^{n-2}b+\\dots+b^{n-1})$',
 's1.b1.rows.6.1':  '$a+b$ soni $a^n+b^n$ ni boʻladi',
 's1.b1.rows.7.1':  'simmetrik masalalar',
 's1.b1.rows.8.1':  '$a+b+c=0$ sharti',
 's1.b1.rows.9.1':  'Sofi Jermen ayniyati',
 's1.b2.text':      '$a^{n}\\pm b^{n}$ qatnashgan ikkita satrni **boʻlinuvchanlik tasdiqlari** sifatida oʻqigan maʼqul: $a-b$ har bir $n$ uchun $a^{n}-b^{n}$ ni boʻladi, $a+b$ esa toq $n$ uchun $a^{n}+b^{n}$ ni boʻladi. Bundan darhol $10^{k}-1$ ning $9$ ga va $3^{105}+4^{105}$ ning $7$ ga boʻlinishi kelib chiqadi.',
 's1.b3.q':         'Kalkulyatorsiz $\\dfrac{2024^{3}+1}{2024^{2}-2023}$ ni hisoblang.',
 's1.b3.steps.0':   '$a=2024$ deb olamiz. U holda $2023=a-1$.',
 's1.b3.steps.1':   'Surat: $a^{3}+1=(a+1)(a^{2}-a+1)$.',
 's1.b3.steps.2':   'Maxraj: $a^{2}-(a-1)=a^{2}-a+1$.',
 's1.b3.steps.3':   'Umumiy $a^{2}-a+1$ koʻpaytuvchi qisqaradi (u musbat, demak noldan farqli).',
 's1.b3.steps.4':   'Qolgani $a+1=2025$.',
 's1.b4.name':      'Noqulay sonni qayta nomlang',
 's1.b4.text':      'Misolning eng birinchi qadamiga eʼtibor bering: noqulay son harf bilan qayta nomlandi. Masalada katta son qoʻshnilari bilan birga uchrasa, **har doim** shunday qiling: $2023,2024,2025$ — bu $a-1,a,a+1$. Qayta nomlashdan keyin masala odatda odatiy boʻlib qoladi.',
 's1.b5.name':      'Sofi Jermen ayniyati',
 's1.b6.text':      '$4a^{2}b^{2}$ ni qoʻshib va ayirib toʻliq kvadratga toʻldiramiz: $$a^{4}+4b^{4}=\\left(a^{2}+2b^{2}\\right)^{2}-(2ab)^{2} ,$$ bu kvadratlar ayirmasi, demak $$\\left(a^{2}+2b^{2}-2ab\\right)\\left(a^{2}+2b^{2}+2ab\\right). \\qquad\\blacksquare$$',
 's1.b7.text':      '**Qoʻshib-ayirish** usuli — bu boʻlimning yuragi. Ifoda ajralmayaptimi? Toʻliq kvadratga yetishmaydigan hadni qoʻshing va darhol qaytarib ayiring: koʻpincha kvadratlar ayirmasi paydo boʻladi.\\n\\n$b=1$ holi $a^{4}+4$ ni beradi va $a>1$ da bu son nega murakkab ekanini tushuntiradi.',
 's1.b8.name':      'Uchta kub ayniyati',
 's1.b9.text':      'Oʻng tomonni birinchi qavsning har bir hadini ikkinchisiga koʻpaytirib ochamiz.\\n\\n$a$ qatnashgan hadlar: $$a^{3}+ab^{2}+ac^{2}-a^{2}b-abc-a^{2}c ,$$ $b$ va $c$ uchun ham shunday. Toʻqqizala guruhni qoʻshamiz.\\n\\nKublar $a^{3}+b^{3}+c^{3}$ ni beradi. $a^{2}b$ kabi aralash hadlar qarama-qarshi ishoralar bilan ikki marta uchraydi (bir marta $a$ guruhidan, bir marta $b$ guruhidan) va qisqaradi — oltala shunday had uchun ham shunday. Qoladigani $-abc$ ning uchta nusxasi: $$-3abc .$$\\n\\nDemak oʻng tomon $a^{3}+b^{3}+c^{3}-3abc$ ga teng ✓ $\\blacksquare$\\n\\n**Ikkita muhim natija.** Agar $a+b+c=0$ boʻlsa, $a^{3}+b^{3}+c^{3}=3abc$. Ikkinchi qavs esa $\\tfrac12\\left[(a-b)^{2}+(b-c)^{2}+(c-a)^{2}\\right]\\ge0$ ga teng boʻlgani uchun, manfiy boʻlmagan $a,b,c$ da $a^{3}+b^{3}+c^{3}\\ge3abc$ chiqadi — bu uchta son uchun oʻrta arifmetik va oʻrta geometrik tengsizligi.',
 's2.b0.text':      'Kvadratlar ayirmasi va kublar yigʻindisi — ikkita umumiy formulaning xususiy hollari. Ularni toʻliq koʻrinishda oʻrganishga arziydi: aynan ular katta darajalarning boʻlinuvchanligi haqidagi savollarni bir qatorlik qiladi.',
 's2.b1.name':      'Bir xil darajalar ayirmasi',
 's2.b1.text':      'Har bir musbat butun $n$ uchun $$a^{n}-b^{n}=(a-b)\\left(a^{\\,n-1}+a^{\\,n-2}b+\\dots+ab^{\\,n-2}+b^{\\,n-1}\\right).$$ Xususan, $a-b$ **har doim** $a^{n}-b^{n}$ ni boʻladi.',
 's2.b2.text':      'Ikkinchi qavsni $S=\\sum_{k=0}^{n-1}a^{\\,n-1-k}b^{k}$ deb belgilaymiz va koʻpaytmani ochamiz.\\n\\n$a$ ga koʻpaytirish: $$aS=a^{n}+a^{\\,n-1}b+\\dots+ab^{\\,n-1} .$$\\n\\n$-b$ ga koʻpaytirish: $$-bS=-a^{\\,n-1}b-\\dots-ab^{\\,n-1}-b^{n} .$$\\n\\nQoʻshamiz: har bir oʻrta had qarama-qarshi ishoralar bilan ikki marta uchraydi va qisqaradi, $$aS-bS=a^{n}-b^{n}$$ qoladi. $\\blacksquare$\\n\\nBu «teleskopik» qisqarish — teleskopik yigʻindilardagi bilan bir xil gʻoya.',
 's2.b3.name':      'Toq darajalar yigʻindisi',
 's2.b3.text':      'Agar $n$ **toq** boʻlsa, $$a^{n}+b^{n}=(a+b)\\left(a^{\\,n-1}-a^{\\,n-2}b+\\dots-ab^{\\,n-2}+b^{\\,n-1}\\right),$$ demak $a+b$ soni $a^{n}+b^{n}$ ni boʻladi. **Juft** $n$ uchun bu oʻrinli emas.',
 's2.b4.text':      'Oldingi formulada $b$ ni $-b$ bilan almashtiramiz: $$a^{n}-(-b)^{n}=\\left(a+b\\right)\\left(a^{\\,n-1}-a^{\\,n-2}b+\\dots+(-b)^{\\,n-1}\\right).$$\\n\\nToq $n$ uchun $(-b)^{n}=-b^{n}$, demak chap tomon $a^{n}+b^{n}$, birinchi qavs esa $a+b$. Ishoralar almashinadi, oxirgi had $(-b)^{\\,n-1}=b^{\\,n-1}$ esa musbat, chunki $n-1$ juft ✓\\n\\n**Juft $n$ nega ishlamaydi.** Juft $n$ da almashtirish yigʻindini emas, $a^{n}-b^{n}$ ni beradi. Va haqiqatan $a+b$ odatda $a^{n}+b^{n}$ ni boʻlmaydi: $2+1=3$ soni $2^{2}+1^{2}=5$ ni boʻlmaydi. $\\blacksquare$',
 's2.b5.head.0':    'Ifoda',
 's2.b5.head.1':    'Nimaga boʻlinadi',
 's2.b5.head.2':    'Shart',
 's2.b5.rows.0.2':  'har doim',
 's2.b5.rows.1.2':  '$n$ juft',
 's2.b5.rows.2.2':  '$n$ toq',
 's2.b5.rows.3.2':  'hech qachon ($a\\ne b$ da)',
 's2.b6.q':         '$3^{105}+4^{105}$ soni $7$ ga boʻlinishini isbotlang.',
 's2.b6.steps.0':   '$105$ koʻrsatkichi toq, demak toq darajalar yigʻindisi formulasi qoʻllanadi.',
 's2.b6.steps.1':   'U $a+b=3+4=7$ ga boʻlinishni beradi ✓',
 's2.b6.steps.2':   'Kichik tekshirish: $3^{3}+4^{3}=27+64=91=7\\cdot13$ ✓',
 's2.b6.ans':       'Boʻlinadi, chunki $7=3+4$.',
 's2.b7.name':      'Bir daraja ayirmasi ikkinchisini qachon boʻladi',
 's2.b7.text':      'Butun $a>1$ va musbat butun $m,n$ uchun $$\\left(a^{n}-1\\right)\\ \\big|\\ \\left(a^{m}-1\\right)\\quad\\Longleftrightarrow\\quad n\\mid m .$$',
 's2.b8.text':      '**Agar $n\\mid m$ boʻlsa,** masalan $m=nq$, ayirma formulasini $x=a^{n}$ asos bilan qoʻllaymiz: $$a^{m}-1=\\left(a^{n}\\right)^{q}-1=\\left(a^{n}-1\\right)\\left(\\dots\\right) \\quad\\checkmark$$\\n\\n**Aksincha.** Qoldiqli boʻlamiz: $m=nq+r$, $0\\le r<n$. U holda $$a^{m}-1=a^{r}\\left(a^{nq}-1\\right)+\\left(a^{r}-1\\right),$$ birinchi had esa yuqoridagiga koʻra $a^{n}-1$ ga boʻlinadi. Demak $\\left(a^{n}-1\\right)\\mid\\left(a^{m}-1\\right)$ dan $$\\left(a^{n}-1\\right)\\ \\big|\\ \\left(a^{r}-1\\right)$$ kelib chiqadi. Ammo $0\\le a^{r}-1<a^{n}-1$, bu esa faqat $a^{r}-1=0$, yaʼni $r=0$ boʻlgandagina mumkin ✓ $\\blacksquare$',
 's2.b9.text':      'Bundan darhol koʻrinadiki, $2^{k}-1$ faqat tub $k$ da tub boʻlishi mumkin: murakkab $k=mn$ $2^{m}-1$ boʻluvchini hosil qilar edi. Bu Mersenn tub sonlarini ovlashdagi birinchi qadam.',
 's3.b0.text':      '**Guruhlash** — eng oddiy usul: hadlarni har bir guruhda umumiy koʻpaytuvchi boʻladigan qilib guruhlarga ajrating, ularni qavsdan tashqariga chiqargandan keyin qavsning oʻzi umumiy koʻpaytuvchiga aylanadi.',
 's3.b1.q':         '$x^{3}-4x^{2}-x+4$ ni koʻpaytuvchilarga ajrating.',
 's3.b1.steps.0':   'Juftlab guruhlaymiz: $(x^{3}-4x^{2})-(x-4)$.',
 's3.b1.steps.1':   'Birinchi qavsdan $x^{2}$ ni chiqaramiz: $x^{2}(x-4)-(x-4)$.',
 's3.b1.steps.2':   'Endi $(x-4)$ umumiy: bu $(x-4)(x^{2}-1)$ ni beradi.',
 's3.b1.steps.3':   'Va kvadratlar ayirmasi qoladi: $x^{2}-1=(x-1)(x+1)$.',
 's3.b2.name':      'Qoʻshib-ayirish',
 's3.b2.text':      'Agar guruhlash toʻxtab qolsa, toʻliq kvadrat paydo boʻladigan qilib bir xil hadni **qoʻshib, darhol ayirishga** urining. Ifoda oʻzgarmaydi, ammo uning koʻrinishi foydali boʻladi. Klassik hol: $$x^{4}+x^{2}+1=\\underbrace{x^{4}+2x^{2}+1}_{(x^{2}+1)^{2}}-x^{2}=(x^{2}+1)^{2}-x^{2}.$$ Keyin kvadratlar ayirmasi ishni bitiradi.',
 's3.b3.q':         '$x^{4}+x^{2}+1$ ni ajrating va bundan har bir butun $n>1$ uchun $n^{4}+n^{2}+1$ murakkab ekanini keltirib chiqaring.',
 's3.b3.steps.1':   'Kvadratlar ayirmasi: $=(x^{2}+1-x)(x^{2}+1+x)$.',
 's3.b3.steps.2':   'Demak $x^{4}+x^{2}+1=(x^{2}-x+1)(x^{2}+x+1)$.',
 's3.b3.steps.3':   '$n>1$ da birinchi koʻpaytuvchi $n(n-1)+1\\ge3$, ikkinchisi esa undan ham katta.',
 's3.b3.steps.4':   'Ikkala koʻpaytuvchi ham $1$ dan katta, demak son murakkab.',
 's3.b3.ans':       '$(x^{2}-x+1)(x^{2}+x+1)$; $n>1$ da son murakkab. $\\blacksquare$',
 's3.b4.text':      'Xuddi shu usul Sofi Jermen ayniyatini beradi — $4a^{2}b^{2}$ ni qoʻshib-ayiring:',
 's3.b6.text':      'Birinchi tenglikni ochib tekshiring: $(a^{2}+2b^{2})^{2}=a^{4}+4a^{2}b^{2}+4b^{4}$, undan $4a^{2}b^{2}$ ni ayirsak $a^{4}+4b^{4}$ qaytadi. Bu ayniyat «bu son murakkab ekanini isbotlang» turidagi butun bir oila masalalarga tayyor javob.',
 's4.b0.text':      '$s=a+b$ va $p=ab$ deb olamiz. U holda $a$ va $b$ ga nisbatan **har bir** simmetrik ifodani $s$ va $p$ orqali yozish mumkin — odatda ikki qatorda. Mana ishchi toʻplam:',
 's4.b2.text':      'Birinchi qator: $(a+b)^{2}=a^{2}+2ab+b^{2}$, $2ab$ ni ayiring. Ikkinchisi: $(a+b)^{3}=a^{3}+3a^{2}b+3ab^{2}+b^{3}=a^{3}+b^{3}+3ab(a+b)$, oʻrnini almashtiring. Uchinchisi: $a^{4}+b^{4}=(a^{2}+b^{2})^{2}-2a^{2}b^{2}$, birinchi qatorni qoʻying. Toʻrtinchisi: $(a-b)^{2}=(a+b)^{2}-4ab$. $\\blacksquare$',
 's4.b3.q':         '$a$ va $b$ sonlari $a+b=4$ va $ab=3$ ni qanoatlantiradi. $a$ va $b$ ni topmasdan $a^{3}+b^{3}$ va $a^{4}+b^{4}$ ni toping.',
 's4.b3.steps.4':   '*Tekshirish:* $t^{2}-4t+3=0$ ning ildizlari $1$ va $3$; haqiqatan $1+27=28$ va $1+81=82$ ✓',
 's4.b4.name':      'Viyet teoremasi',
 's4.b4.text':      'Agar $t_1,t_2$ — $t^{2}+pt+q=0$ ning ildizlari boʻlsa, $t_1+t_2=-p$ va $t_1t_2=q$. Aksincha, yigʻindisi $s$ va koʻpaytmasi $m$ boʻlgan ikkita son aynan $t^{2}-st+m=0$ ning ildizlari.',
 's4.b5.text':      'Teskarisi ishchi usul. $$x+y=5,\\qquad x^{3}+y^{3}=35$$ sistemasini yechish uchun $x^{3}+y^{3}=s^{3}-3ps$ deb yozamiz, demak $125-15p=35$ va $p=6$. Shuning uchun $x$ va $y$ — $t^{2}-5t+6=0$ ning ildizlari, yaʼni $2$ va $3$.',
 's4.b6.text':      'Uchta oʻzgaruvchi uchun $s$ va $p$ ning rolini $$\\sigma_1=a+b+c,\\qquad\\sigma_2=ab+bc+ca,\\qquad\\sigma_3=abc$$ oʻynaydi va yana har bir simmetrik ifoda ulardan quriladi. Sizga eng koʻp kerak boʻladigan formula: $$a^{2}+b^{2}+c^{2}=\\sigma_1^{2}-2\\sigma_2 .$$',
 's5.b0.name':      'Bezu teoremasi',
 's5.b0.text':      '$f(x)$ koʻphadni $x-c$ ga boʻlgandagi qoldiq $f(c)$ ga teng. Xususan, $$(x-c)\\mid f(x)\\quad\\Longleftrightarrow\\quad f(c)=0 .$$',
 's5.b1.text':      '$f$ ni $x-c$ ga qoldiqli boʻlamiz: $f(x)=(x-c)q(x)+r$, bunda $r$ — oʻzgarmas, chunki qoldiqning darajasi boʻluvchinikidan kichik, boʻluvchining darajasi esa bir. $x=c$ qoʻyamiz: oʻng tomon $0\\cdot q(c)+r=r$ ga aylanadi, demak $r=f(c)$. Agar $f(c)=0$ boʻlsa, qoldiq yoʻqoladi va $x-c$ soni $f$ ni boʻladi; teskarisi ravshan. $\\blacksquare$',
 's5.b2.name':      'Ratsional ildiz haqidagi teorema',
 's5.b2.text':      '$f(x)=a_nx^{n}+\\dots+a_1x+a_0$ butun koeffitsiyentli boʻlsin va $\\dfrac{u}{v}$ — uning qisqarmas koʻrinishdagi ildizi boʻlsin. U holda $u\\mid a_0$ va $v\\mid a_n$. Xususan, keltirilgan koʻphadning butun ildizlari uning ozod hadining boʻluvchilari.',
 's5.b3.text':      'Demak tartib shunday: butun koeffitsiyentli koʻphadni ajratish uchun **ozod hadning boʻluvchilarini saralang**. Ular kam, har birini tekshirish esa bir soniya.',
 's5.b4.q':         '$x^{3}-4x^{2}+x+6$ ni koʻpaytuvchilarga ajrating.',
 's5.b4.steps.0':   'Ozod had $6$, demak butun ildizlarni $\\pm1,\\pm2,\\pm3,\\pm6$ orasidan qidiramiz.',
 's5.b4.steps.1':   '$f(1)=1-4+1+6=4\\ne0$. $f(-1)=-1-4-1+6=0$ — ildiz!',
 's5.b4.steps.2':   'Bezu teoremasiga koʻra $f(x)=(x+1)\\,q(x)$. Ustun boʻlish $x^{3}-4x^{2}+x+6=(x+1)(x^{2}-5x+6)$ ni beradi.',
 's5.b4.steps.3':   'Kvadrat uchhadni Viyet boʻyicha ajratamiz: ildizlarning yigʻindisi $5$, koʻpaytmasi $6$, demak ular $2$ va $3$.',
 's5.b5.text':      'Ratsional ildiz haqidagi teorema faqat **ratsional** ildizlarni topadi. $x^{2}-2$ koʻphadining ratsional ildizi umuman yoʻq, bu esa u «ajralmaydi» degani emas — faqat ratsional sonlar ustida ajralmaydi. Javob butun son boʻlishi kerak boʻlgan olimpiada masalalarida aynan shu kerak.',
 's6.b0.text':      '$(a+b)^{2}$ va $(a+b)^{3}$ formulalari cheksiz roʻyxatni boshlaydi. Umumiy formula yodlashdan qutqaradi va koeffitsiyentlar nega Paskal uchburchagini hosil qilishini tushuntiradi.',
 's6.b1.name':      'Binomial koeffitsiyent',
 's6.b1.text':      '$$\\binom nk=\\frac{n!}{k!\\,(n-k)!}=\\frac{n(n-1)\\cdots(n-k+1)}{k!}$$ — $n$ ta obyektdan tartibga eʼtibor bermay $k$ tasini tanlash usullari soni. Kelishuvga koʻra $\\binom n0=\\binom nn=1$.',
 's6.b2.name':      'Paskal qoidasi',
 's6.b3.text':      '**Kombinator isbot.** Bitta obyektni — masalan birinchisini — ajratamiz. $n$ tadan $k$ ta obyektni har qanday tanlash yo uni oʻz ichiga oladi, yo olmaydi.\\n\\nAgar olsa, qolgan $n-1$ tadan yana $k-1$ tasini tanlaymiz: bu $\\binom{n-1}{k-1}$ usul.\\n\\nAgar olmasa, qolgan $n-1$ tadan barcha $k$ tasini tanlaymiz: bu $\\binom{n-1}{k}$ usul.\\n\\nHollar kesishmaydi va hammasini qamraydi, demak sonlar qoʻshiladi. $\\blacksquare$\\n\\n**Aynan shu qoida** Paskal uchburchagini hosil qiladi: har bir katak ustidagi ikkita katakning yigʻindisi.',
 's6.b4.name':      'Nyuton binomi',
 's6.b5.text':      '**Kombinator isbot.** $$(a+b)^{n}=\\underbrace{(a+b)(a+b)\\cdots(a+b)}_{n\\ \\text{qavs}}$$ deb yozamiz.\\n\\nOchganda har bir qavsdan yo $a$ ni, yo $b$ ni olib koʻpaytiramiz. Har bir tanlov $a^{\\,n-k}b^{k}$ bir hadni beradi, bunda $k$ — $b$ bergan qavslar soni.\\n\\n**$a^{\\,n-k}b^{k}$ necha marta paydo boʻladi?** $n$ ta qavsdan $k$ tasini tanlash mumkin boʻlgan marta, yaʼni $\\binom nk$ marta. Oʻxshash hadlarni birlashtirsak formula chiqadi. $\\blacksquare$\\n\\n**Induksiya bilan** ham qisqa: $(a+b)^{n}$ ni $(a+b)$ ga koʻpaytirib $a^{\\,n+1-k}b^{k}$ oldidagi koeffitsiyentni yigʻsak, $\\binom nk+\\binom n{k-1}=\\binom{n+1}{k}$ chiqadi — aynan Paskal qoidasi.',
 's6.b6.name':      'Uchta natija',
 's6.b6.text':      '(1) $\\displaystyle\\sum_{k=0}^{n}\\binom nk=2^{n}$; $\\;$ (2) $n\\ge1$ uchun $\\displaystyle\\sum_{k=0}^{n}(-1)^{k}\\binom nk=0$; $\\;$ (3) $n\\ge1$ uchun $\\displaystyle\\sum_{k\\ \\text{juft}}\\binom nk=\\sum_{k\\ \\text{toq}}\\binom nk=2^{\\,n-1}$.',
 's6.b7.text':      '**(1)** $a=b=1$ qoʻyamiz: chap tomon $2^{n}$, oʻng tomon esa koeffitsiyentlar yigʻindisi ✓ (Kombinator maʼnoda: $n$ elementli toʻplamning $2^{n}$ ta qism toʻplami bor.)\\n\\n**(2)** $a=1$, $b=-1$ qoʻyamiz: chap tomon $n\\ge1$ da $(1-1)^{n}=0$ ✓\\n\\n**(3)** (1) va (2) ni qoʻshsak juft $k$ boʻyicha yigʻindining ikki barobari, yaʼni $2^{n}$ chiqadi; demak u yigʻindi $2^{\\,n-1}$. Ayirsak toq $k$ uchun shu natija chiqadi. $\\blacksquare$',
 's6.b8.q':         '$\\left(2x-3\\right)^{8}$ yoyilmasida $x^{5}$ oldidagi koeffitsiyentni toping.',
 's6.b8.steps.0':   'Umumiy had $\\binom8k(2x)^{\\,8-k}(-3)^{k}$.',
 's6.b8.steps.1':   '$x$ ning darajasi $8-k$, demak bizga $8-k=5$, yaʼni $k=3$ kerak.',
 's6.b8.steps.2':   'Koeffitsiyent $\\binom83\\cdot2^{5}\\cdot(-3)^{3}$.',
 's6.b8.steps.4':   'Jami $56\\cdot32\\cdot(-27)=-48\\,384$.',
 's6.b9.q':         '$0<k<p$ uchun $\\binom pk$ tub $p$ ga boʻlinishini isbotlang va bundan Ferma kichik teoremasini keltirib chiqaring.',
 's6.b9.steps.0':   'Taʼrifdan $k!\\,(p-k)!\\cdot\\binom pk=p!$, oʻng tomon esa $p$ ga boʻlinadi.',
 's6.b9.steps.1':   '$k!$ va $(p-k)!$ dagi barcha koʻpaytuvchilar $p$ dan qatʼiy kichik, demak $p$ ularning koʻpaytmasini boʻlmaydi (Yevklid lemmasi).',
 's6.b9.steps.2':   'Shuning uchun $p$ soni $\\binom pk$ ni boʻlishi kerak ✓',
 's6.b9.steps.3':   '**Natija.** $(a+1)^{p}$ ni ochamiz: har bir oʻrta had $p$ ga karrali, demak $(a+1)^{p}\\equiv a^{p}+1\\pmod p$.',
 's6.b9.steps.4':   '$a$ boʻyicha induksiya ($a=0$ bazasi ravshan) barcha butun $a\\ge0$ uchun $a^{p}\\equiv a\\pmod p$ ni beradi.',
 's6.b9.ans':       '$p\\mid\\binom pk$, demak $a^{p}\\equiv a\\pmod p$.',
 's7.b0.text':      '$a^{5}+b^{5}+c^{5}$ kabi ifoda qoʻrqinchli koʻrinadi — u **simmetrik** ekanini sezmaguningizcha. Har bir simmetrik ifodani uchta asosiy ifoda orqali yozish mumkin, rekurrensiya esa ishni avtomatik bajaradi.',
 's7.b1.name':      'Elementar simmetrik koʻphadlar',
 's7.b1.text':      'Uchta oʻzgaruvchi uchun $$e_1=a+b+c,\\qquad e_2=ab+bc+ca,\\qquad e_3=abc ,$$ daraja yigʻindilari esa $$p_k=a^{k}+b^{k}+c^{k} .$$',
 's7.b2.name':      'Kub tenglama uchun Viyet',
 's7.b2.text':      'Agar $a,b,c$ — $t^{3}+pt^{2}+qt+r$ ning ildizlari boʻlsa, u holda $$e_1=-p,\\qquad e_2=q,\\qquad e_3=-r .$$ Aksincha, istalgan $e_1,e_2,e_3$ dan koʻphad $$t^{3}-e_1t^{2}+e_2t-e_3$$ koʻrinishida tiklanadi.',
 's7.b3.text':      'Ildizlari $a,b,c$ boʻlgan keltirilgan koʻphad $$(t-a)(t-b)(t-c)$$ koʻrinishida ajraladi.\\n\\nQadamma-qadam ochamiz: $$(t-a)(t-b)=t^{2}-(a+b)t+ab ,$$ buni $(t-c)$ ga koʻpaytirib darajalar boʻyicha yigʻsak, $$t^{3}-(a+b+c)t^{2}+(ab+bc+ca)t-abc=t^{3}-e_1t^{2}+e_2t-e_3 .$$\\n\\n$t^{3}+pt^{2}+qt+r$ bilan solishtirish keltirilgan ayniyatlarni beradi. $\\blacksquare$',
 's7.b4.name':      'Nyuton ayniyatlari',
 's7.b4.text':      'Uchta oʻzgaruvchi uchun daraja yigʻindilari $$p_k=e_1p_{k-1}-e_2p_{k-2}+e_3p_{k-3}\\qquad(k\\ge3)$$ rekurrensiyasini qanoatlantiradi, boshlangʻich qiymatlar esa $$p_0=3,\\qquad p_1=e_1,\\qquad p_2=e_1^{2}-2e_2 .$$',
 's7.b5.text':      '**Rekurrensiya.** $a,b,c$ sonlari $t^{3}-e_1t^{2}+e_2t-e_3$ ning ildizlari, demak ularning har biri $$t^{3}=e_1t^{2}-e_2t+e_3$$ ni qanoatlantiradi.\\n\\n$t^{\\,k-3}$ ga koʻpaytiramiz: $$t^{k}=e_1t^{\\,k-1}-e_2t^{\\,k-2}+e_3t^{\\,k-3} .$$\\n\\nNavbat bilan $t=a$, $t=b$, $t=c$ qoʻyamiz va uchalasini qoʻshamiz. Chap tomon $p_k$ ni, oʻng tomon $e_1p_{k-1}-e_2p_{k-2}+e_3p_{k-3}$ ni beradi ✓\\n\\n**Boshlangʻich qiymatlar.** $p_0=3$ va $p_1=e_1$ ravshan. $p_2$ uchun $e_1$ ni kvadratga koʻtaramiz: $$e_1^{2}=p_2+2e_2 ,$$ demak $p_2=e_1^{2}-2e_2$. $\\blacksquare$',
 's7.b6.q':         '$a,b,c$ sonlari $a+b+c=2$, $ab+bc+ca=-1$, $abc=-2$ ni qanoatlantiradi. $a^{4}+b^{4}+c^{4}$ ni toping.',
 's7.b6.steps.0':   'Bu yerda $e_1=2$, $e_2=-1$, $e_3=-2$.',
 's7.b6.steps.4':   '**Tekshirish.** $t^{3}-2t^{2}-t+2=(t-1)(t+1)(t-2)$ koʻphadining ildizlari $1,-1,2$.',
 's7.b6.steps.5':   'Va haqiqatan $1+1+16=18$ ✓',
 's7.b7.text':      '**$a+b+c=0$ boʻlganda** rekurrensiya soddalashadi: $e_1=0$, demak $$p_k=-e_2p_{k-2}+e_3p_{k-3} .$$ Mashhur ayniyatlar darhol kelib chiqadi: $$p_3=3abc,\\qquad \\frac{p_5}{5}=\\frac{p_2}{2}\\cdot\\frac{p_3}{3},\\qquad \\frac{p_7}{7}=\\frac{p_2}{2}\\cdot\\frac{p_5}{5} .$$ Agar masala sizga $a+b+c=0$ ni bersa, Nyuton ayniyatlari deyarli aniq kerakli qurol.',
 's7.b8.text':      '**Simmetrik koʻphadlar haqidagi asosiy teorema** aytadi: $a,b,c$ ga nisbatan butun koeffitsiyentli har bir simmetrik koʻphad $e_1,e_2,e_3$ ning koʻphadi sifatida yagona tarzda — yana butun koeffitsiyentlar bilan — yoziladi. Shuning uchun qoʻrqinchli simmetrik ifodalar har doim taslim boʻladi: ular uchta asosiy kattalikning niqoblangan kombinatsiyasi.',
 's8.b0.name':      '1-usul: $a+b+c=0$ sharti',
 's8.b0.text':      'Agar masala sizga $a+b+c=0$ ni bersa, darhol $$a^{3}+b^{3}+c^{3}-3abc=(a+b+c)(a^{2}+b^{2}+c^{2}-ab-bc-ca)$$ ayniyatini eslang. Oʻng tomon nolga aylanadi va $a^{3}+b^{3}+c^{3}=3abc$ qoladi — kuchli va juda foydali tenglik.',
 's8.b1.name':      '2-usul: kvadratlar yigʻindisi nolga teng',
 's8.b1.text':      '$$2\\left(a^{2}+b^{2}+c^{2}-ab-bc-ca\\right)=(a-b)^{2}+(b-c)^{2}+(c-a)^{2}$$ ayniyati algebraik shartni qatʼiy shartga aylantiradi. Kvadratlar yigʻindisi faqat har bir had nol boʻlgandagina nolga teng, demak $a^{2}+b^{2}+c^{2}=ab+bc+ca$ darhol $a=b=c$ ni majbur qiladi.',
 's8.b2.name':      '3-usul: hamma narsani bir tomonga oʻtkazing',
 's8.b2.text':      '$A=B$ tenglamasi deyarli foydasiz; $(\\dots)(\\dots)=0$ tenglamasi esa oʻzini oʻzi yechadi. Shuning uchun tenglamaga oid har qanday masaladagi birinchi harakat — hamma narsani bir tomonga oʻtkazib, koʻpaytuvchilarga ajratishga urinish.',
 's8.b3.q':         'Noldan farqli $a,b,c$ va $a+b+c\\ne0$ uchun $\\dfrac1a+\\dfrac1b+\\dfrac1c=\\dfrac1{a+b+c}$ boʻlsin. Ulardan ikkitasi qarama-qarshi ekanini isbotlang.',
 's8.b3.steps.0':   'Hamma narsani chapga oʻtkazamiz: $\\dfrac1a+\\dfrac1b+\\dfrac1c-\\dfrac1{a+b+c}=0$.',
 's8.b3.steps.1':   'Dastlabki ikkita kasrni, soʻng oxirgi ikkitasini qoʻshamiz: $$\\frac{a+b}{ab}+\\frac{(a+b+c)-c}{c(a+b+c)}=\\frac{a+b}{ab}+\\frac{a+b}{c(a+b+c)}=0.$$',
 's8.b3.steps.2':   '$a+b$ ni qavsdan chiqaramiz: $$(a+b)\\left(\\frac1{ab}+\\frac1{c(a+b+c)}\\right)=0.$$',
 's8.b3.steps.3':   'Qavsni umumiy maxrajga keltiramiz: $$\\frac{c(a+b+c)+ab}{ab\\,c(a+b+c)}=\\frac{ca+cb+c^{2}+ab}{ab\\,c(a+b+c)}=\\frac{(c+a)(c+b)}{ab\\,c(a+b+c)}.$$',
 's8.b3.steps.4':   'Demak $(a+b)(b+c)(c+a)=0$ va qavslardan biri nolga aylanadi.',
 's8.b3.ans':       '$a=-b$, yoki $b=-c$, yoki $c=-a$. $\\blacksquare$',
}
