# -*- coding: utf-8 -*-
"""Uzbek for topic 2.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Tub sonlar',
 'sub':             'Har bir butun son quriladigan gʻishtlar: koʻpaytuvchilarga ajratish, tub sonlarning cheksizligi va «$p>3$ boʻlsa $p=6k\\pm1$» usuli.',
 'goals.0':         'Arifmetikaning asosiy teoremasini tushunish va tub darajalar bilan ishlash.',
 'goals.1':         'Sonni $\\sqrt{n}$ gacha boʻlish orqali tublikka tekshirish va elak qurish.',
 'goals.2':         'Tub sonlar cheksiz koʻp ekanining Yevklid isbotini bilish va bu usuldan qayta foydalanish.',
 'goals.3':         'Masalalarda hollarni yoʻqotish uchun $6k\\pm1$ koʻrinishi va kichik modullardan foydalanish.',
 's0.h':            'Taʼrif va dastlabki kuzatishlar',
 's1.h':            'Arifmetikaning asosiy teoremasi',
 's2.h':            'Tub sonlar cheksiz koʻp',
 's3.h':            'Maxsus koʻrinishdagi tub sonlar ham cheksiz koʻp',
 's4.h':            '$6k\\pm1$ koʻrinishi va kichik modullar',
 's5.h':            'Eratosfen elagi',
 's6.h':            'Tub sonlar qanday taqsimlangan',
 's7.h':            'Mersenn va Ferma sonlari',
 's0.b0.name':      'Tub va murakkab sonlar',
 's0.b0.text':      'Musbat butun $p>1$ soni, agar uning yagona musbat boʻluvchilari $1$ va $p$ boʻlsa, **tub** deyiladi. Tub boʻlmagan $n>1$ butun son **murakkab** deyiladi. $1$ soni na tub, na murakkab.',
 's0.b1.text':      '$1$ nega chiqarib tashlanadi? Tub koʻpaytuvchilarga ajratish **yagona** boʻlishi uchun. Aks holda $6=2\\cdot3=1\\cdot2\\cdot3=1\\cdot1\\cdot2\\cdot3$ boʻlar va yagonalik yoʻqolar edi.',
 's0.b2.name':      'Eng kichik boʻluvchi',
 's0.b2.text':      'Murakkab $n$ sonining $d>1$ boʻlgan eng kichik boʻluvchisi tub son va $d\\le\\sqrt{n}$.',
 's0.b3.text':      'Agar $d$ murakkab boʻlganda, uning $1<e<d$ boʻluvchisi boʻlar, u esa $n$ ni ham boʻlar edi — bu $d$ ning minimalligiga zid. Demak $d$ tub. Keyin $n=d\\cdot m$, bunda $m\\ge d$ (aks holda $m$ kichikroq boʻluvchi boʻlar edi). U holda $n=dm\\ge d^2$, yaʼni $d\\le\\sqrt{n}$.',
 's0.b4.name':      'Tublikni qanday tekshirish kerak',
 's0.b4.text':      'Teorema amaliy tartib beradi: $n$ ni tekshirish uchun $\\sqrt{n}$ gacha boʻlgan tub sonlarni sinash yetarli. $n=323$ uchun $17$ gacha boʻlgan tub sonlar yetarli: $2,3,5,7,11,13,17$. Topamiz: $323=17\\cdot19$ — murakkab.',
 's0.b5.q':         '$221$ tubmi?',
 's0.b5.steps.0':   '$\\sqrt{221}\\approx14.9$, demak $2,3,5,7,11,13$ ni sinash yetarli.',
 's0.b5.steps.1':   '$221$ toq, raqamlari yigʻindisi $5$ — $3$ ga boʻlinmaydi — va $0$ yoki $5$ bilan tugamaydi.',
 's0.b5.steps.2':   '$221=7\\cdot31+4$; $221=11\\cdot20+1$; $221=13\\cdot17$ — boʻlinadi!',
 's0.b5.ans':       'Murakkab: $221=13\\cdot17$',
 's0.b6.name':      'Boʻluvchilarni saralash orqali tublik',
 's0.b6.text':      '$n>1$ butun son tub boʻlishi uchun u $\\sqrt n$ dan oshmaydigan hech bir tub $p$ ga boʻlinmasligi zarur va yetarli.',
 's0.b7.text':      'Agar $n$ tub boʻlsa, uning $1$ va $n$ dan boshqa boʻluvchisi yoʻq, tasdiq ravshan.\\n\\nAksincha, $n$ murakkab boʻlsin, $n=ab$, bunda $1<a\\le b<n$. Agar ikkala koʻpaytuvchi ham $\\sqrt n$ dan katta boʻlsa, $$n=ab>\\sqrt n\\cdot\\sqrt n=n \\quad ✗$$\\n\\nDemak $a\\le\\sqrt n$. $a>1$ sonining $p\\le a\\le\\sqrt n$ tub boʻluvchisi bor va u $n$ ni boʻladi. $\\blacksquare$',
 's0.b8.q':         '$211$ tubmi?',
 's0.b8.steps.0':   '$14^{2}=196<211<225=15^{2}$, demak $14$ gacha boʻlgan tub sonlarni sinash yetarli.',
 's0.b8.steps.1':   'Ular $2,3,5,7,11,13$.',
 's0.b8.steps.2':   '$211$ toq; raqamlari yigʻindisi $4$ — $3$ ga karrali emas; $0$ ham, $5$ ham bilan tugamaydi.',
 's0.b8.steps.4':   'Hech biri uni boʻlmaydi.',
 's0.b8.ans':       'Ha, $211$ tub son.',
 's0.b9.text':      'Bu teorema boʻluvchilarni saralash umuman amalga oshadigan boʻlishining sababi: olti xonali sonni tekshirish uchun $1000$ gacha boʻlgan tub sonlar kerak, ular esa atigi $168$ ta.',
 's1.b0.name':      'Ajratmaning yagonaligi',
 's1.b0.text':      '$n>1$ boʻlgan har bir butun sonni koʻpaytuvchilar tartibidan qatʼi nazar roppa-rosa bir usulda $$n=p_1^{\\alpha_1}p_2^{\\alpha_2}\\cdots p_k^{\\alpha_k}$$ koʻrinishida yozish mumkin, bunda $p_1<p_2<\\cdots<p_k$ — tub sonlar va $\\alpha_i\\ge1$.',
 's1.b1.text':      '*Mavjudligi* induksiya bilan: agar $n$ tub boʻlsa, tugadi; aks holda $n=ab$, bunda $1<a,b<n$, va induksiya farazi boʻyicha ikkala koʻpaytuvchi ham ajraladi. *Yagonaligi* Yevklid lemmasiga tayanadi (1-mavzu): agar $p$ tub va $p\\mid ab$ boʻlsa, $p\\mid a$ yoki $p\\mid b$. $n$ ning ikkita ajratmasi bor deb faraz qilamiz. Birinchisidagi $p_1$ tub son ikkinchisidagi koʻpaytmani boʻladi, demak uning biror koʻpaytuvchisini boʻladi, u esa tub — shuning uchun oʻsha koʻpaytuvchi $p_1$ ga teng. $p_1$ ni qisqartiramiz va takrorlaymiz.',
 's1.b2.name':      'Darajalar tili',
 's1.b2.text':      '$n$ dagi tub $p$ sonning darajasini $v_p(n)$ deb belgilaymiz. Hamma narsa darajalar arifmetikasiga aylanadi: $$v_p(ab)=v_p(a)+v_p(b),\\qquad a\\mid b\\iff \\text{har bir } p \\text{ uchun } v_p(a)\\le v_p(b).$$ Son toʻliq kvadrat boʻlishi uchun barcha $v_p$ juft boʻlishi, toʻliq kub boʻlishi uchun esa barcha $v_p$ $3$ ga karrali boʻlishi zarur va yetarli.',
 's1.b3.q':         '$2^5\\cdot3^3\\cdot5\\cdot k$ toʻliq kvadrat boʻladigan eng kichik musbat butun $k$ ni toping.',
 's1.b3.steps.0':   'Hozirgi darajalar: $v_2=5$, $v_3=3$, $v_5=1$ — hammasi toq.',
 's1.b3.steps.1':   'Ularni juft qilish uchun har bir tub sondan yana bittadan kerak.',
 's1.b3.steps.2':   '$k=2\\cdot3\\cdot5=30$. Tekshirish: $2^6\\cdot3^4\\cdot5^2=(2^3\\cdot3^2\\cdot5)^2=360^2$.',
 's2.b0.name':      'Yevklid teoremasi',
 's2.b0.text':      'Tub sonlar cheksiz koʻp.',
 's2.b1.text':      'Teskarisini faraz qilamiz: tub sonlar chekli sonda, ular $p_1,p_2,\\ldots,p_k$ va boshqasi yoʻq. $$N=p_1p_2\\cdots p_k+1$$ sonini koʻramiz. $N>1$ boʻlgani uchun uning tub $p$ boʻluvchisi bor. Ammo $p$ — $p_i$ lardan biri, demak $p$ ham $p_1\\cdots p_k$ koʻpaytmani, ham $N$ ni boʻladi, demak ularning ayirmasi $1$ ni ham. Ziddiyat. $\\blacksquare$',
 's2.b2.text':      'Koʻp uchraydigan xato — $p_1p_2\\cdots p_k+1$ ning **oʻzi** tub deb oʻylash. Bu shart emas: $$2\\cdot3\\cdot5\\cdot7\\cdot11\\cdot13+1=30031=59\\cdot509.$$ Isbot faqat bu sonning roʻyxatdan tashqaridagi tub boʻluvchisi borligini daʼvo qiladi.',
 's2.b3.text':      'Xuddi shu usul, biroz oʻzgartirilgan holda, koʻproq narsa beradi. $4k+3$ koʻrinishidagi tub sonlar cheksiz koʻpligini isbotlash uchun $N=4p_1p_2\\cdots p_k-1$ olamiz: bu $N$ modul $4$ boʻyicha $3$ qoldiq beradi, $4k+1$ koʻrinishidagi tub sonlarning koʻpaytmasi esa yana $4k+1$ koʻrinishida boʻladi — demak $N$ ning $4k+3$ koʻrinishidagi tub boʻluvchisi bor va u roʻyxatda yoʻq.',
 's2.b4.name':      'Istalgancha uzun tubsiz oraliqlar',
 's2.b4.text':      '$$n!+2,\\;n!+3,\\;\\ldots,\\;n!+n$$ sonlarining hammasi murakkab: $2\\le k\\le n$ uchun $k$ soni $n!+k$ ni boʻladi. Demak ketma-ket kelgan $n-1$ ta son orasida birorta ham tub son boʻlmasligi mumkin — tub sonlar juda notekis joylashgan.',
 's2.b5.text':      '**Cheksizlikning boshqa isbotlari.** Yevklidniki yagona emas. Ferma sonlari juft-jufti bilan oʻzaro tublik orqali isbot beradi (quyida). Eyler ancha kuchliroq narsani isbotladi: $$\\sum_{p\\ \\text{tub}}\\frac1p$$ qatori **uzoqlashadi**, chekli toʻplam uchun esa bu mumkin emas. Uzoqlashish yana shuni bildiradiki, tub sonlar kvadratlardan «koʻproq», chunki $\\sum\\tfrac1{n^{2}}$ yaqinlashadi.',
 's3.b0.text':      'Yevklid teoremasi tub sonlar tugamasligini aytadi. Tabiiy keyingi savol: **har bir** mumkin boʻlgan koʻrinishdagi — $4k+1$, $4k+3$, $6k+5$ — tub sonlar cheksiz koʻpmi? Baʼzi koʻrinishlar uchun Yevklidning oʻz usuli hamon ishlaydi.',
 's3.b1.name':      'Koʻpaytma koʻrinishni saqlaydi',
 's3.b1.text':      '$4k+1$ koʻrinishidagi sonlarning koʻpaytmasi yana $4k+1$ koʻrinishida boʻladi. $6k+1$ koʻrinishi uchun ham shunday.',
 's3.b2.text':      'Bevosita hisoblash: $$(4a+1)(4b+1)=4(4ab+a+b)+1 ,$$ $$(6a+1)(6b+1)=6(6ab+a+b)+1 .$$ Induksiya buni istalgan sondagi koʻpaytuvchiga kengaytiradi. $\\blacksquare$',
 's3.b3.name':      '$4k+3$ koʻrinishidagi tub sonlar cheksiz koʻp',
 's3.b3.text':      '$4$ ga boʻlganda $3$ qoldiq beradigan tub sonlar toʻplami cheksiz.',
 's3.b4.text':      'Teskarisini faraz qilamiz: bu koʻrinishdagi tub sonlar $p_1=3,\\ p_2,\\ \\dots,\\ p_k$. $$N=4p_1p_2\\cdots p_k-1$$ sonini koʻramiz.\\n\\nU holda $N$ toq va $N\\equiv3\\pmod4$.\\n\\n$N$ ning har bir tub boʻluvchisi toq, demak $4k+1$ yoki $4k+3$ koʻrinishida. Agar hammasi $4k+1$ boʻlsa, lemma $N$ ning oʻzini ham $4k+1$ qilar edi ✗ Demak $N$ ning $q\\equiv3\\pmod4$ tub boʻluvchisi bor.\\n\\nFarazga koʻra $q$ — $p_i$ lardan biri; u holda $q$ ham $4p_1\\cdots p_k$ ni, ham $N$ ni boʻladi, demak ularning ayirmasini $$4p_1\\cdots p_k-N=1 ,$$ bu esa mumkin emas ✗ $\\blacksquare$',
 's3.b5.q':         'Mulohazani $6k+5$ koʻrinishi uchun takrorlang va uni dastlabki bir necha tub sonda tekshiring.',
 's3.b5.steps.0':   '$N=6p_1p_2\\cdots p_k-1$ ni olamiz, bunda $p_i$ — $6k+5$ koʻrinishidagi barcha tub sonlar.',
 's3.b5.steps.1':   'U holda $N\\equiv5\\pmod6$; xususan $N$ toq va $3$ ga boʻlinmaydi.',
 's3.b5.steps.2':   'Demak $N$ ning har bir tub boʻluvchisi na $2$, na $3$, yaʼni $6k+1$ yoki $6k+5$ koʻrinishida.',
 's3.b5.steps.3':   'Agar hammasi $6k+1$ boʻlsa, $N$ ham shunday boʻlar edi — bu $N\\equiv5$ ga zid.',
 's3.b5.steps.4':   'Qolgani teoremadagidek: bunday boʻluvchi $1$ ni boʻlishi kerak boʻlar edi ✗',
 's3.b5.steps.5':   'Kichik tekshirish: $6\\cdot5-1=29$ tub va $\\equiv5\\pmod6$ ✓',
 's3.b5.ans':       '$6k+5$ koʻrinishidagi tub sonlar ham cheksiz koʻp.',
 's3.b6.text':      '$4k+1$ koʻrinishi uchun bu usul **ishlamaydi**: $\\equiv3\\pmod4$ boʻlgan sonlarning koʻpaytmasi modul $4$ boʻyicha $1$ ham, $3$ ham boʻlishi mumkin, demak hech qanday boʻluvchi majburlanmaydi. $4k+1$ uchun cheksizlik boshqacha isbotlanadi — $n^{2}+1$ ning har bir toq tub boʻluvchisi $\\equiv1\\pmod4$ ekani orqali.',
 's3.b7.name':      'Dirixle teoremasi',
 's3.b7.text':      'Agar $\\gcd(a,d)=1$ boʻlsa, $$a,\\ a+d,\\ a+2d,\\ a+3d,\\ \\dots$$ arifmetik progressiyasida cheksiz koʻp tub son bor.',
 's3.b8.text':      'Dirixle teoremasini isbotlash maktab matematikasidan ancha uzoqqa ketadi: unda analitik qurollar (Dirixle qatorlari va $L$-funksiyalar) ishlatiladi. Tasdiqning oʻzini bilish baribir foydali — u $4k+3$ va $6k+5$ kabi xususiy hollar nega umuman imkoniyatga ega ekanini tushuntiradi.\\n\\n**$\\gcd(a,d)=1$ sharti zarur:** $2,4,6,8,\\dots$ progressiyasida roppa-rosa bitta tub son bor.',
 's4.b0.name':      'Tub sonning koʻrinishi',
 's4.b0.text':      '$p>3$ boʻlgan har bir tub son $6k+1$ yoki $6k-1$ koʻrinishida boʻladi.',
 's4.b1.text':      'Har bir butun son $6k,6k\\pm1,6k\\pm2,6k+3$ koʻrinishlardan birida. $6k$ va $6k\\pm2$ juft, $6k+3$ esa $3$ ga boʻlinadi; $p>3$ uchun bularning hech biri mumkin emas. Faqat $6k\\pm1$ qoladi. $\\blacksquare$',
 's4.b2.name':      'Mavzuning asosiy usuli',
 's4.b2.text':      'Masalada tub $p$ paydo boʻlsa, soʻrang: **$p$ kichik boʻlsa-chi?** Odatda $p=2$ va $p=3$ qoʻlda koʻriladi, $p>3$ uchun esa yo $p^2\\equiv1\\pmod{24}$, yo modul $3$ boʻyicha taqqoslama ishni bitiradi. «Shunday barcha tub $p$ larni toping…» turidagi juda koʻp masala aynan shunga tushadi.',
 's4.b3.q':         '$p^2+2$ ham tub boʻladigan barcha tub $p$ larni toping.',
 's4.b3.steps.0':   'Kichiklarini sinaymiz: $p=2$ da $6$ chiqadi — murakkab; $p=3$ da $11$ — tub.',
 's4.b3.steps.1':   'Endi $p>3$ boʻlsin. U holda $3\\nmid p$, demak $p^2$ ni $3$ ga boʻlganda qoldiq $1$.',
 's4.b3.steps.2':   'Demak $p^2+2$ soni $3$ ga boʻlinadi va $3$ dan katta — murakkab.',
 's4.b3.ans':       'Faqat $p=3$',
 's4.b4.head.0':    'Modul',
 's4.b4.head.1':    'Nima beradi',
 's4.b4.head.2':    'Qachon ishlatiladi',
 's4.b4.rows.0.1':  'juftlik',
 's4.b4.rows.0.2':  'yigʻindilar, koʻpaytmalar, «ikkitadan biri»',
 's4.b4.rows.1.1':  '$3\\nmid p$ boʻlganda $p^2\\equiv1$',
 's4.b4.rows.1.2':  '$p^2$ qatnashgan ifodalar',
 's4.b4.rows.2.2':  'kvadratlar yigʻindisi',
 's4.b4.rows.3.1':  'toq sonning kvadrati $\\equiv1$',
 's4.b4.rows.3.2':  '$2q^2$ qatnashgan tenglamalar',
 's4.b4.rows.4.1':  'raqamlar yigʻindisi',
 's4.b4.rows.4.2':  'oʻnlik yozuv',
 's5.b0.text':      '$N$ gacha boʻlgan barcha tub sonlarni roʻyxatlash uchun $2$ dan $N$ gacha sonlarni yozing va har bir yangi oʻchirilmagan sonning karralilarini uning kvadratidan boshlab oʻchiring. Joriy tub son $\\sqrt{N}$ dan oshishi bilan toʻxtash mumkin.',
 's5.b1.items.0':   '$2$ ning karralilarini $4$ dan boshlab oʻchiring.',
 's5.b1.items.1':   'Keyingi oʻchirilmagan son — $3$; $9$ dan boshlab oʻchiring.',
 's5.b1.items.2':   'Soʻng $5$ ($25$ dan) va $7$ ($49$ dan). $N=100$ uchun shu yetarli, chunki $11^2=121>100$.',
 's5.b1.items.3':   'Qolgani tub: $100$ dan kichik $25$ ta tub son bor.',
 's5.b2.text':      'Dastlabki tub sonlarni yoddan bilish foydali: $2,3,5,7,11,13,17,19,23,29,31,37,41,43,47$. Musobaqada bu daqiqalarni tejaydi.',
 's5.b3.name':      'Elak nega $\\sqrt N$ da toʻxtaydi',
 's5.b3.text':      '$N$ gacha boʻlgan barcha tub sonlarni topish uchun $p\\le\\sqrt N$ tub sonlarning karralilarini oʻchirish yetarli. Shundan keyin birdan katta omon qolgan har bir son tub boʻladi.',
 's5.b4.text':      '$m\\le N$ omon qolgan va $m>1$ boʻlsin. Agar $m$ murakkab boʻlsa, uning $p\\le\\sqrt m\\le\\sqrt N$ tub boʻluvchisi boʻlar edi (boʻluvchilarni saralash teoremasiga koʻra). Ammo biz har bir shunday $p$ ning karralilarini oʻchirgan edik, demak $m$ ham oʻchirilgan boʻlar edi ✗\\n\\nDemak $m$ tub. $\\blacksquare$',
 's5.b5.text':      'Yana bitta tezlashtirish: $p$ ning karralilarini oʻchirganda $2p$ dan emas, $p^{2}$ dan boshlang. Undan kichik har bir karrali $kp$ koʻrinishida, bunda $k<p$, va u $k$ ning biror kichikroq tub koʻpaytuvchisining karralisi sifatida allaqachon oʻchirilgan.',
 's5.b6.q':         '$100$ gacha nechta tub son bor va elak qayerda toʻxtashi mumkin?',
 's5.b6.steps.0':   '$\\sqrt{100}=10$, demak $2,3,5,7$ ning karralilarini oʻchiramiz, boshqa hech narsani emas.',
 's5.b6.steps.1':   'Ikkining karralilarini $4$ dan, uchniki $9$ dan, beshniki $25$ dan, yettiniki $49$ dan boshlaymiz.',
 's5.b6.steps.2':   'Omon qolganlari: $2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97$.',
 's5.b6.steps.3':   'Sanaymiz: $25$ ta.',
 's5.b6.ans':       '$25$ ta tub son; elak yettidan keyin toʻxtaydi.',
 's6.b0.text':      'Tub sonlar tugamaydi — ammo ular qanchalik zich joylashgan? Ular siyraklashadi, lekin hech qachon uzoq vaqtga yoʻqolmaydi.',
 's6.b1.name':      'Istalgancha uzun tubsiz oraliqlar',
 's6.b1.text':      'Har bir $n$ uchun ketma-ket kelgan $n$ ta murakkab son mavjud.',
 's6.b2.text':      '$M=(n+1)!$ deb olamiz va $$M+2,\\ M+3,\\ \\dots,\\ M+(n+1)$$ sonlarini koʻramiz.\\n\\n$2\\le k\\le n+1$ boʻlgan istalgan $k$ ni olamiz. U holda $k$ — $(n+1)!$ ning koʻpaytuvchisi, demak $k\\mid M$ va $k\\mid k$, shuning uchun $$k\\ \\big|\\ M+k .$$\\n\\n$M+k>k>1$ boʻlgani uchun $M+k$ sonining $1$ va oʻzidan boshqa boʻluvchisi bor — u murakkab.\\n\\nBarcha $n$ ta son murakkab. $\\blacksquare$',
 's6.b3.name':      'Bertran postulati',
 's6.b3.text':      'Har bir $n\\ge1$ butun son uchun $n$ va $2n$ orasida tub son bor: $$n<p\\le2n .$$',
 's6.b4.text':      'Bertran buni $1845$-yilda taʼriflagan; Chebishyov $1852$-yilda isbotlagan, Erdyosh esa $1932$-yilda $\\binom{2n}{n}$ binomial koeffitsiyentini baholash orqali nafis elementar isbot bergan.\\n\\n**Qanday ishlatiladi.** «$n$ va $2n$ orasida har doim tub son bor» degani masalaga tub son kerak boʻlganda uni ishlab chiqarishga imkon beradi: masalan, $n>1$ da $n!$ hech qachon toʻliq daraja boʻlmasligini yoki $1+\\tfrac12+\\dots+\\tfrac1n$ hech qachon butun son boʻlmasligini koʻrsatish uchun.',
 's6.b5.q':         'Bertran postulatidan foydalanib, $n\\ge2$ da $H_n=1+\\tfrac12+\\dots+\\tfrac1n$ hech qachon butun son boʻlmasligini isbotlang.',
 's6.b5.steps.0':   'Bertran $\\tfrac n2<p\\le n$ boʻladigan tub $p$ ni beradi.',
 's6.b5.steps.1':   '$p\\le n$ boʻlgani uchun yigʻindida $\\tfrac1p$ hadi bor.',
 's6.b5.steps.2':   '$2p>n$ boʻlgani uchun $1,\\dots,n$ orasida $p$ ning yagona karralisi $p$ ning oʻzi — boshqa hech bir maxraj $p$ ga boʻlinmaydi.',
 's6.b5.steps.3':   'Yigʻindini $L=\\operatorname{lcm}(1,\\dots,n)$ umumiy maxrajga keltiramiz; unda $p$ birinchi darajada qatnashadi.',
 's6.b5.steps.4':   'Suratdagi bitta haddan tashqari hammasi $p$ koʻpaytuvchisini oladi; $\\tfrac1p$ dan kelgan had esa olmaydi.',
 's6.b5.steps.5':   'Demak surat $p$ ga boʻlinmaydi, maxraj esa boʻlinadi — kasr butun son boʻla olmaydi ✗',
 's6.b5.ans':       'Hech bir $n\\ge2$ uchun $H_n$ butun son emas.',
 's6.b6.name':      'Tub sonlar taqsimoti teoremasi',
 's6.b6.text':      '$x$ gacha boʻlgan tub sonlar sonini $\\pi(x)$ deb belgilaymiz. U holda $$\\pi(x)\\ \\sim\\ \\frac{x}{\\ln x},$$ yaʼni $x\\to\\infty$ da $\\pi(x)\\big/\\dfrac{x}{\\ln x}$ nisbati birga intiladi.',
 's6.b7.head.3':    'nisbat',
 's6.b8.text':      'Teorema $1896$-yilda Adamar va de la Valle-Pussen tomonidan mustaqil ravishda isbotlangan; elementar (lekin baribir qiyin) isbotni $1949$-yilda Erdyosh va Selberg topgan.\\n\\n**Amalda bu nimani bildiradi.** $x$ atrofida tub sonlarning ulushi taxminan $\\tfrac1{\\ln x}$. Taxminan har $230$ ta yuz xonali sondan bittasi tub — aynan shuning uchun kriptografik kalitlarni tasodifiy qidiruv bilan topish mumkin.',
 's6.b9.text':      '**Ochiq savollar.** Tub sonlar haqida oʻylanganidan ancha kam narsa maʼlum. Hanuz isbotlanmagan: egizak tub sonlar gipotezasi ($p$, $p+2$ juftliklari cheksiz koʻpmi), Goldbax gipotezasi (ikkidan katta har bir juft son ikkita tub son yigʻindisimi), $n^{2}+1$ koʻrinishidagi tub sonlarning cheksizligi. Bularning hammasi kompyuterda juda katta chegaralargacha tekshirilgan — ammo tekshirish isbot emas.',
 's7.b0.text':      'Ikki oila sonlar asrlar davomida katta tub sonlarni ovlash maydoni boʻlib kelgan. Ikkalasida ham koʻrsatkich qatʼiy cheklangan — va bu cheklovning elementar isboti bor.',
 's7.b1.name':      'Mersenn koʻrsatkichi tub boʻlishi shart',
 's7.b1.text':      'Agar $2^{n}-1$ tub boʻlsa, $n$ ham tub.',
 's7.b2.text':      'Kontrapozitsiyani isbotlaymiz: agar $n$ murakkab boʻlsa, $2^{n}-1$ ham murakkab.\\n\\n$n=ab$ boʻlsin, bunda $1<a,b<n$. $x=2^{a}$ bilan $$x^{b}-1=(x-1)\\left(x^{\\,b-1}+\\dots+x+1\\right)$$ ayniyatidan foydalanamiz: $$2^{n}-1=\\left(2^{a}-1\\right)\\left(2^{a(b-1)}+\\dots+2^{a}+1\\right).$$\\n\\nIkkala koʻpaytuvchi ham birdan katta: $a\\ge2$ dan $2^{a}-1\\ge3$, ikkinchisi esa har biri kamida $1$ boʻlgan $b\\ge2$ ta hadning yigʻindisi.\\n\\nDemak $2^{n}-1$ murakkab. $\\blacksquare$',
 's7.b3.text':      'Teskarisi **notoʻgʻri**: $n$ tub boʻlgani $2^{n}-1$ ni tub qilmaydi. Eng kichik qarshi misol $$2^{11}-1=2047=23\\cdot89 ,$$ garchi $11$ tub boʻlsa ham.',
 's7.b4.name':      'Ferma koʻrsatkichi ikkining darajasi boʻlishi shart',
 's7.b4.text':      'Agar biror $n\\ge1$ uchun $2^{n}+1$ tub boʻlsa, u holda $n$ — ikkining darajasi.',
 's7.b5.text':      '$n$ ikkining darajasi **emas** deb faraz qilamiz. U holda $n$ ning $m>1$ toq boʻluvchisi bor; $n=km$ deb yozamiz.\\n\\n**Toq** $m$ uchun ayniyatdan foydalanamiz: $$x^{m}+1=(x+1)\\left(x^{\\,m-1}-x^{\\,m-2}+\\dots-x+1\\right)$$ (ishoralar almashinadi, oxirgi had esa aynan $m$ toq boʻlgani uchun $+1$). $x=2^{k}$ ni qoʻyamiz: $$2^{n}+1=\\left(2^{k}+1\\right)\\left(\\dots\\right).$$\\n\\nBirinchi koʻpaytuvchi $2^{k}+1\\ge3$, ikkinchisi esa $\\dfrac{2^{n}+1}{2^{k}+1}>1$, chunki $m>1$ boʻlgani $n>k$ ni bildiradi.\\n\\nDemak $2^{n}+1$ murakkab — ziddiyat. $\\blacksquare$',
 's7.b6.name':      'Ferma sonlari',
 's7.b6.text':      '$F_n=2^{2^{n}}+1$. Dastlabki bir nechtasi, $$F_0=3,\\quad F_1=5,\\quad F_2=17,\\quad F_3=257,\\quad F_4=65\\,537 ,$$ hammasi tub. Ferma ular har doim tub boʻladi deb taxmin qilgan, ammo $1732$-yilda Eyler $$F_5=4\\,294\\,967\\,297=641\\cdot6\\,700\\,417$$ ekanini topdi.',
 's7.b7.name':      'Ferma sonlari juft-jufti bilan oʻzaro tub',
 's7.b7.text':      '$m\\ne n$ uchun $\\gcd\\left(F_m,F_n\\right)=1$. Bu tub sonlar cheksiz koʻpligining yana bir isbotini beradi.',
 's7.b8.text':      '**1-qadam: $F_0F_1\\cdots F_{n-1}=F_n-2$ ayniyati.** $n$ boʻyicha induksiya. Baza $n=1$: chap tomon $F_0=3$, oʻng tomon $5-2=3$ ✓ Qadam: agar $F_0\\cdots F_{n-1}=2^{2^{n}}-1$ boʻlsa, $$F_0\\cdots F_{n-1}F_n=\\left(2^{2^{n}}-1\\right)\\left(2^{2^{n}}+1\\right)=2^{2^{n+1}}-1=F_{n+1}-2 \\quad\\checkmark$$\\n\\n**2-qadam.** $m<n$ boʻlsin va $d$ soni $F_m$ ni ham, $F_n$ ni ham boʻlsin. 1-qadamga koʻra $F_m$ — $F_0\\cdots F_{n-1}=F_n-2$ ning koʻpaytuvchisi, demak $d\\mid F_n-2$. $d\\mid F_n$ bilan birga bu $d\\mid2$ ni beradi.\\n\\nAmmo Ferma sonlari toq, demak $d$ toq va $d=1$. $\\blacksquare$\\n\\n**Natija.** Har bir $F_n$ ning tub boʻluvchisi bor va turli $F_n$ lar turli boʻluvchiga ega — demak tub sonlar cheksiz koʻp.',
 's7.b9.text':      '**Nega ular muhim.** Maʼlum boʻlgan eng katta tub sonlar — Mersenn sonlari: ularning tubligini gʻayrioddiy tez tekshirish mumkin (Lukas–Lemer testi). Ferma sonlari klassik geometriya bilan bogʻlanadi: Gauss isbotladiki, muntazam $n$-burchakni sirkul va chizgʻich bilan yasash mumkin boʻlishi uchun $n$ ikkining darajasi va turli **tub** Ferma sonlari koʻpaytmasi boʻlishi zarur va yetarli. Shuning uchun muntazam $17$-burchak yasaladi, $7$-burchak esa yasalmaydi.',
}
