# -*- coding: utf-8 -*-
"""Uzbek for topic 7.

Keyed by the addresses that content/uz/extract.py prints.  Anything missing
here falls back to English on the page, so the file may grow a piece at a time.
Modern Uzbek Latin script; the marks are U+02BB (oʻ, gʻ) and U+02BC."""

UZ = {
 'title':           'Ketma-ketliklar va yigʻindilar',
 'sub':             'Arifmetik va geometrik progressiyalar, teleskopik yigʻindilar, rekurrent munosabatlar va Fibonachchi sonlari.',
 'goals.0':         'Ikkala progressiya uchun $n$-had va yigʻindi formulalaridan erkin foydalanish.',
 'goals.1':         'Har bir hadni ayirmaga ajratib, yigʻindilarni teleskoplash bilan hisoblash.',
 'goals.2':         'Yigʻindi formulalarini matematik induksiya bilan isbotlash.',
 'goals.3':         'Rekurrent munosabatlar bilan, jumladan Fibonachchi sonlari bilan ishlash.',
 's0.h':            'Ketma-ketlikni berishning ikki usuli',
 's1.h':            'Arifmetik progressiyalar',
 's2.h':            'Geometrik progressiyalar',
 's3.h':            'Teleskopik yigʻindilar',
 's4.h':            'Klassik yigʻindilar',
 's5.h':            'Chiziqli rekurrent ketma-ketliklar',
 's6.h':            'Fibonachchi sonlari',
 's7.h':            'Limitlar, monotonlik va cheksiz yigʻindilar',
 's0.b0.name':      'Ketma-ketlik',
 's0.b0.text':      '**Ketma-ketlik** — bu nomerlangan sonlar roʻyxati $a_1,a_2,a_3,\\dots$ Uni ikki usulda berish mumkin: **yopiq formula** bilan (masalan, $a_n=n^{2}$) yoki **rekurrent** usulda — dastlabki hadlarni va har bir keyingi hadni oldingilaridan hosil qiluvchi qoidani koʻrsatib (masalan, $a_1=1$, $a_{n+1}=2a_n+1$).',
 's0.b1.text':      'Rekurrent taʼrif bilan hisoblash oson, lekin u noqulay: $a_{100}$ ga yetish uchun yuz qadam qilish kerak. Shuning uchun odatdagi masala shunday yangraydi: **rekurrent munosabat berilgan, yopiq formulani toping**. Koʻpincha uni dastlabki bir necha haddan taxmin qilib, soʻng induksiya bilan isbotlash mumkin.',
 's0.b2.q':         'Ketma-ketlik $a_1=1$ va $a_{n+1}=2a_n+1$ bilan berilgan. Yopiq formulani toping.',
 's0.b2.steps.0':   'Dastlabki hadlarni yozamiz: $1,\\ 3,\\ 7,\\ 15,\\ 31,\\ 63,\\dots$',
 's0.b2.steps.1':   'Har biri ikkining darajasidan bir kam: $2-1,\\ 4-1,\\ 8-1,\\ 16-1,\\dots$',
 's0.b2.steps.2':   'Taxmin: $a_n=2^{n}-1$.',
 's0.b2.steps.3':   '**Baza.** $a_1=2^{1}-1=1$ ✓',
 's0.b2.steps.4':   '**Qadam.** $a_n=2^{n}-1$ deb faraz qilamiz. Unda $$a_{n+1}=2\\left(2^{n}-1\\right)+1=2^{n+1}-2+1=2^{n+1}-1,$$ yaʼni formula $n+1$ uchun ham toʻgʻri.',
 's0.b2.steps.5':   'Induksiya boʻyicha u har bir $n$ uchun bajariladi.',
 's0.b3.name':      'Induksiyaning tuzilishi',
 's0.b3.text':      'Induksion isbot har doim aynan ikki qismdan iborat.\\n\\n**Baza.** Tasdiqni eng kichik $n$ da (odatda $n=1$) tekshiramiz.\\n\\n**Qadam.** U $n$ uchun toʻgʻri deb faraz qilib, $n+1$ uchun **keltirib chiqaramiz**.\\n\\nIkkala qism bajarilgach, tasdiq har bir $n$ uchun toʻgʻri boʻladi. Bazani tashlab ketish — eng koʻp uchraydigan xato: usiz mutlaqo yolgʻon narsani ham «isbotlash» mumkin.',
 's0.b4.name':      'Matematik induksiya prinsipi',
 's0.b4.text':      '$P(n)$ — natural $n$ haqidagi tasdiq boʻlsin. Agar\\n\\n1. $P(1)$ toʻgʻri boʻlsa va\\n2. har bir $k\\ge1$ uchun $P(k)$ ning toʻgʻriligi $P(k+1)$ ning toʻgʻriligini keltirib chiqarsa,\\n\\nu holda $P(n)$ har bir natural $n$ uchun toʻgʻri.',
 's0.b5.text':      'Induksiya **eng kichik element prinsipi** bilan teng kuchli: natural sonlarning har bir boʻsh boʻlmagan toʻplamida eng kichik element bor.\\n\\nTeskarisini faraz qilamiz: 1 va 2 shartlar bajariladi, lekin $P(n)$ yolgʻon boʻlgan $n$ larning $M$ toʻplami boʻsh emas. Unda $M$ da eng kichik element $m$ bor.\\n\\n1-shartga koʻra $m\\ne1$, demak $m\\ge2$ va $m-1$ natural son. U $m$ dan kichik, $m$ esa $M$ da eng kichik, shuning uchun $m-1\\notin M$, yaʼni $P(m-1)$ toʻgʻri.\\n\\nLekin unda 2-shart $P(m)$ ni toʻgʻri qiladi — bu $m\\in M$ ga qarama-qarshi ✓ Demak $M$ boʻsh $\\blacksquare$',
 's0.b6.text':      '**Kuchli induksiya.** Baʼzan qadamda faqat $P(k)$ emas, balki barcha oldingi tasdiqlar birdan kerak boʻladi. Tasdiq: agar $P(1)$ bajarilsa va $P(1),\\dots,P(k)$ birgalikda $P(k+1)$ ni keltirib chiqarsa, u holda $P(n)$ har bir $n$ uchun bajariladi. Isbot aynan shunday. Kuchli induksiya $a_{n+2}$ ikki oldingi hadga bogʻliq boʻlgan rekurrent munosabatlar uchun almashtirib boʻlmaydigan vositadir.',
 's0.b7.text':      'Ikkita klassik xato.\\n\\n**Baza yoʻqolgani.** Faqat «$P(k)\\Rightarrow P(k+1)$» dan hech narsa kelib chiqmaydi: «$n=n+1$» tasdiqi mukammal irsiylanadi, lekin yolgʻon.\\n\\n**Kichik qiymatlarda buziladigan qadam.** Barcha otlar bir rangda ekani haqidagi mashhur «isbot»da $k$ dan $k+1$ ga oʻtish $k$ ta otdan iborat ikki guruhning kesishmasidan foydalanadi — $k=1$ da esa bu kesishma boʻsh. Qadam eng kichik $k$ da ham oʻrinli ekanini har doim tekshiring.',
 's1.b0.name':      'Arifmetik progressiya',
 's1.b0.text':      'Har bir hadi oldingisiga bir xil $d$ sonini — **ayirmani** — qoʻshish bilan hosil qilinadigan ketma-ketlik: $$a_{n+1}=a_n+d .$$',
 's1.b1.name':      'Progressiya formulalari',
 's1.b2.text':      'Birinchi formula tushunarli: $a_1$ dan $a_n$ ga yetish uchun $d$ oʻlchamli $n-1$ qadam kerak.\\n\\nIkkinchisi Gauss usuli bilan isbotlanadi: yigʻindini ikki marta, ikkinchi marta teskari tartibda yozib, ustunlar boʻyicha qoʻshamiz: $$\\begin{aligned} S_n&=a_1+a_2+\\dots+a_{n-1}+a_n\\\\ S_n&=a_n+a_{n-1}+\\dots+a_2+a_1 \\end{aligned}$$ Har bir ustun $a_k+a_{n+1-k}$ juftligidir. Lekin $$a_k+a_{n+1-k}=\\bigl(a_1+(k-1)d\\bigr)+\\bigl(a_1+(n-k)d\\bigr)=2a_1+(n-1)d=a_1+a_n$$ — har bir ustunda bir xil son. Ustunlar $n$ ta, shuning uchun $2S_n=n(a_1+a_n)$. $\\blacksquare$',
 's1.b3.text':      'Eng koʻp foydalanadigan holat: $a_1=1$, $d=1$ boʻlganda $$1+2+3+\\dots+n=\\frac{n(n+1)}{2}.$$ Buni koʻpaytirish jadvali kabi mustahkam bilish kerak.',
 's1.b4.name':      'Xarakteristik xossa',
 's1.b4.text':      'Ketma-ketlik arifmetik progressiya boʻlishi uchun har bir hadi (chetkilaridan tashqari) qoʻshnilarining oʻrta arifmetigiga teng boʻlishi zarur va yetarli: $$a_n=\\frac{a_{n-1}+a_{n+1}}{2}.$$',
 's1.b5.q':         '$7$ ga boʻlinadigan uch xonali sonlar nechta va ularning yigʻindisi qancha?',
 's1.b5.steps.0':   'Yettiga boʻlinadigan eng kichik uch xonali son: $100=7\\cdot14+2$, demak u $7\\cdot15=105$.',
 's1.b5.steps.1':   'Eng kattasi: $999=7\\cdot142+5$, demak u $7\\cdot142=994$.',
 's1.b5.steps.2':   '$105,112,\\dots,994$ sonlari $d=7$ ayirmali arifmetik progressiya tashkil qiladi.',
 's1.b5.steps.3':   'Sonini topamiz: $994=105+(n-1)\\cdot7$ dan $n-1=\\tfrac{889}{7}=127$, demak $n=128$.',
 's1.b5.steps.4':   'Yigʻindi: $S=\\dfrac{105+994}{2}\\cdot128=\\dfrac{1099}{2}\\cdot128=1099\\cdot64=70\\,336$.',
 's1.b5.ans':       '$128$ ta son, yigʻindisi $70\\,336$.',
 's2.b0.name':      'Geometrik progressiya',
 's2.b0.text':      'Har bir hadi oldingisini bir xil $q\\ne0$ soniga — **maxrajga** — koʻpaytirish bilan hosil qilinadigan ketma-ketlik: $$b_{n+1}=b_n\\cdot q .$$',
 's2.b1.name':      'Progressiya formulalari',
 's2.b1.text':      '$$b_n=b_1q^{\\,n-1},\\qquad S_n=b_1\\cdot\\frac{q^{n}-1}{q-1}\\quad(q\\ne1),$$ va $|q|<1$ boʻlganda butun cheksiz progressiyaning yigʻindisi $$S=\\frac{b_1}{1-q}.$$',
 's2.b2.text':      'Yigʻindini $q$ ga koʻpaytirib, ayiramiz: $$\\begin{aligned} S_n&=b_1+b_1q+b_1q^{2}+\\dots+b_1q^{\\,n-1},\\\\ qS_n&=\\hphantom{b_1+{}}b_1q+b_1q^{2}+\\dots+b_1q^{\\,n-1}+b_1q^{n}. \\end{aligned}$$ Deyarli har bir had mos tushadi, shuning uchun $$qS_n-S_n=b_1q^{n}-b_1,\\qquad S_n(q-1)=b_1\\left(q^{n}-1\\right),$$ bu esa formulani beradi. $|q|<1$ boʻlganda $n$ oʻsishi bilan $q^{n}$ miqdori xohlagancha kichik boʻladi va yigʻindi $\\dfrac{b_1}{1-q}$ ga intiladi. $\\blacksquare$',
 's2.b3.q':         '$0.(27)=0.272727\\dots$ davriy oʻnli kasrni oddiy kasrga aylantiring.',
 's2.b3.steps.0':   'Kasrni yigʻindi shaklida yozamiz: $$0.272727\\dots=\\frac{27}{100}+\\frac{27}{100^{2}}+\\frac{27}{100^{3}}+\\dots$$',
 's2.b3.steps.1':   'Bu $b_1=\\tfrac{27}{100}$ va $q=\\tfrac1{100}$ boʻlgan cheksiz geometrik progressiya, hamda $|q|<1$.',
 's2.b3.steps.3':   'Boʻlish bilan tekshiramiz: $3:11=0.2727\\dots$ ✓',
 's2.b4.text':      'Xuddi shu hisob mashhur $0.(9)=1$ tenglikni tushuntiradi: bu $b_1=\\tfrac9{10}$ va $q=\\tfrac1{10}$ boʻlgan progressiya, uning yigʻindisi $\\tfrac{9/10}{9/10}=1$.',
 's2.b5.text':      '**Geometrik progressiya yigʻindisini keltirib chiqarish.** $$S_n=b_1+b_1q+\\dots+b_1q^{\\,n-1}$$ boʻlsin. $q$ ga koʻpaytiramiz: $$qS_n=b_1q+b_1q^{2}+\\dots+b_1q^{\\,n}.$$\\n\\nIkkinchisini birinchisidan ayiramiz. Barcha oʻrta hadlar qisqaradi va faqat chetlari qoladi: $$S_n-qS_n=b_1-b_1q^{\\,n}.$$\\n\\n$q\\ne1$ boʻlganda $1-q$ ga boʻlamiz: $$S_n=b_1\\frac{1-q^{\\,n}}{1-q} \\quad\\checkmark$$\\n\\n$q=1$ boʻlganda formula qoʻllanmaydi va kerak ham emas: barcha hadlar $b_1$ ga teng, shuning uchun $S_n=nb_1$ ✓ $\\blacksquare$',
 's2.b6.name':      'Xarakteristik xossa',
 's2.b6.text':      'Nolga teng boʻlmagan sonlar ketma-ketligi geometrik progressiya boʻlishi uchun chetkilaridan tashqari har bir hadi $$b_n^{2}=b_{n-1}b_{n+1}$$ shartini qanoatlantirishi zarur va yetarli.',
 's2.b7.text':      '**Agar bu progressiya boʻlsa,** $b_{n-1}=\\dfrac{b_n}{q}$ va $b_{n+1}=b_nq$, demak ularning koʻpaytmasi $b_n^{2}$ ✓\\n\\n**Teskarisi,** $b_n\\ne0$ boʻlganda $b_n^{2}=b_{n-1}b_{n+1}$ dan $$\\frac{b_{n+1}}{b_n}=\\frac{b_n}{b_{n-1}},$$ yaʼni ketma-ket hadlarning nisbati har bir qadamda bir xil. Uni $q$ deb belgilash progressiyani beradi ✓ $\\blacksquare$',
 's3.b0.text':      'Yigʻindilar uchun eng kuchli usul. Agar har bir hadni bitta miqdorning qoʻshni qiymatlari **ayirmasi** shaklida yozish mumkin boʻlsa, $$c_k=f(k)-f(k+1),$$ u holda qoʻshishda oʻrtadagi hamma narsa qisqaradi: $$\\sum_{k=1}^{n}c_k=f(1)-f(n+1).$$ $n$ hadli yigʻindi bitta satrga siqiladi.',
 's3.b1.q':         '$\\dfrac1{1\\cdot2}+\\dfrac1{2\\cdot3}+\\dots+\\dfrac1{n(n+1)}$ ni hisoblang.',
 's3.b1.steps.0':   'Umumiy hadni ajratamiz: $$\\frac1{k(k+1)}=\\frac{(k+1)-k}{k(k+1)}=\\frac1k-\\frac1{k+1}.$$',
 's3.b1.steps.1':   'Ularni qoʻshamiz: $$\\left(\\frac11-\\frac12\\right)+\\left(\\frac12-\\frac13\\right)+\\dots+\\left(\\frac1n-\\frac1{n+1}\\right).$$',
 's3.b1.steps.2':   'Har bir ichki had qarama-qarshi ishoralar bilan ikki marta kelib, qisqaradi.',
 's3.b1.steps.3':   'Faqat chetlari qoladi: $1-\\dfrac1{n+1}=\\dfrac{n}{n+1}$.',
 's3.b2.text':      'Uchta darajalar yigʻindisini yodda saqlash foydali. Hammasi induksiya bilan (yoki mos ifodani teleskoplash bilan) isbotlanadi:',
 's3.b4.text':      'Uchinchisi goʻzal fakt: **kublar yigʻindisi — yigʻindining kvadrati**. Masalan, $1+8+27+64=100=(1+2+3+4)^{2}$.',
 's3.b5.name':      'Ajratishni qanday topish kerak',
 's3.b5.text':      'Agar had $\\dfrac{1}{k(k+m)}$ kasri boʻlsa, $$\\frac1{k(k+m)}=\\frac1m\\left(\\frac1k-\\frac1{k+m}\\right)$$ dan foydalanamiz. Agar hadda ildizlar boʻlsa, qoʻshmasiga koʻpaytiramiz: $$\\frac1{\\sqrt{k}+\\sqrt{k+1}}=\\frac{\\sqrt{k+1}-\\sqrt{k}}{\\left(\\sqrt{k+1}+\\sqrt k\\right)\\left(\\sqrt{k+1}-\\sqrt k\\right)}=\\sqrt{k+1}-\\sqrt{k}.$$',
 's4.b0.text':      'Quyidagi toʻrt yigʻindi doimo uchraydi. Ularni nafaqat yodlash, balki keltirib chiqarishni bilish kerak: keltirib chiqarish formuladan koʻra muhimroq, chunki u hech bir maʼlumotnomada yoʻq yigʻindilarni ham hal qiladi.',
 's4.b1.name':      'Birinchi $n$ ta natural son yigʻindisi',
 's4.b2.text':      '$S$ yigʻindini ikki marta — toʻgʻri va teskari tartibda — yozamiz: $$\\begin{aligned} S&=1+2+\\dots+\\left(n-1\\right)+n,\\\\ S&=n+\\left(n-1\\right)+\\dots+2+1. \\end{aligned}$$\\n\\nUstunlar boʻyicha qoʻshamiz. $n$ ta ustunning har biri $n+1$ ni beradi, shuning uchun $$2S=n\\left(n+1\\right)\\quad\\Longrightarrow\\quad S=\\frac{n\\left(n+1\\right)}{2} \\quad\\checkmark\\qquad\\blacksquare$$\\n\\nRivoyatga koʻra, toʻqqiz yashar Gauss $1$ dan $100$ gacha sonlarni bir necha soniyada shu usul bilan qoʻshgan: $101$ ning ellik juftligi.',
 's4.b3.name':      'Kvadratlar yigʻindisi',
 's4.b4.text':      'Teleskoplashdan foydalanamiz. Qadamning kubini yoyamiz: $$\\left(k+1\\right)^{3}-k^{3}=3k^{2}+3k+1 .$$\\n\\nBuni $k=1,2,\\dots,n$ boʻyicha qoʻshamiz. Chap tomon teleskoplanadi va faqat chetki qiymatlar qoladi: $$\\left(n+1\\right)^{3}-1^{3}=3\\sum_{k=1}^{n}k^{2}+3\\sum_{k=1}^{n}k+n .$$\\n\\nIkkinchi yigʻindi allaqachon maʼlum: $\\sum k=\\dfrac{n\\left(n+1\\right)}{2}$. Oʻrniga qoʻyib, yechamiz: $$3\\sum k^{2}=\\left(n+1\\right)^{3}-1-\\frac{3n\\left(n+1\\right)}{2}-n .$$\\n\\nUmumiy maxraj $2$ da oʻng tomon $$\\frac{2n^{3}+3n^{2}+n}{2}=\\frac{n\\left(n+1\\right)\\left(2n+1\\right)}{2}$$ ga aylanadi.\\n\\n$3$ ga boʻlamiz ✓ $\\blacksquare$',
 's4.b5.name':      'Kublar yigʻindisi',
 's4.b6.text':      '$n$ boʻyicha induksiya.\\n\\n**Baza $n=1$:** $1^{3}=1=\\left(\\tfrac{1\\cdot2}{2}\\right)^{2}$ ✓\\n\\n**Qadam.** $\\sum_{k=1}^{n}k^{3}=\\dfrac{n^{2}\\left(n+1\\right)^{2}}{4}$ deb faraz qilamiz. Keyingi kubni qoʻshamiz: $$\\sum_{k=1}^{n+1}k^{3}=\\frac{n^{2}\\left(n+1\\right)^{2}}{4}+\\left(n+1\\right)^{3}=\\left(n+1\\right)^{2}\\cdot\\frac{n^{2}+4\\left(n+1\\right)}{4}.$$\\n\\nSuratda $n^{2}+4n+4=\\left(n+2\\right)^{2}$, shuning uchun yigʻindi $$\\frac{\\left(n+1\\right)^{2}\\left(n+2\\right)^{2}}{4}$$ ga teng, bu esa $n+1$ uchun formula ✓ $\\blacksquare$\\n\\nKvadrat bilan mos tushish tasodif emas: soʻzsiz goʻzal isbot bor — unda har bir $k^{3}$ kub tomoni $k$ boʻlgan $k$ ta kvadratga kesiladi va hammasi tomoni $1+2+\\dots+n$ boʻlgan bitta katta kvadratni qoplaydi.',
 's4.b7.name':      'Arifmetik-geometrik yigʻindi',
 's4.b7.text':      '$q\\ne1$ boʻlganda $$\\sum_{k=1}^{n}kq^{\\,k-1}=\\frac{1-\\left(n+1\\right)q^{\\,n}+nq^{\\,n+1}}{\\left(1-q\\right)^{2}}.$$',
 's4.b8.text':      'Usul geometrik progressiya uchun ishlatilgani bilan bir xil: **maxrajga koʻpaytirib, ayirish**.\\n\\n$S=1+2q+3q^{2}+\\dots+nq^{\\,n-1}$ boʻlsin. Unda $$qS=q+2q^{2}+\\dots+\\left(n-1\\right)q^{\\,n-1}+nq^{\\,n}.$$\\n\\nAyiramiz: $k=1,\\dots,n-1$ uchun $q^{\\,k}$ ning koeffitsiyenti $\\left(k+1\\right)-k=1$, shuning uchun $$S-qS=1+q+q^{2}+\\dots+q^{\\,n-1}-nq^{\\,n}=\\frac{1-q^{\\,n}}{1-q}-nq^{\\,n}.$$\\n\\n$1-q$ ga boʻlib, umumiy maxrajga keltiramiz ✓ $\\blacksquare$',
 's4.b9.q':         '$\\dfrac1{2}+\\dfrac2{4}+\\dfrac3{8}+\\dots+\\dfrac{n}{2^{n}}$ ni hisoblang va $n\\to\\infty$ da limitini toping.',
 's4.b9.steps.0':   'Bu $\\dfrac12\\sum_{k=1}^{n}k\\left(\\tfrac12\\right)^{k-1}$, yaʼni oldingi formula $q=\\tfrac12$ da.',
 's4.b9.steps.1':   'Oʻrniga qoʻysak, $\\left(1-q\\right)^{2}=\\tfrac14$, shuning uchun yigʻindi $$\\frac12\\cdot4\\left(1-\\frac{n+1}{2^{n}}+\\frac{n}{2^{n+1}}\\right)=2-\\frac{n+2}{2^{n}}$$ ga teng.',
 's4.b9.steps.2':   '$n=3$ da tekshiramiz: formula $2-\\tfrac58=\\tfrac{11}{8}$ ni beradi, bevosita qoʻshish esa $\\tfrac12+\\tfrac12+\\tfrac38=\\tfrac{11}{8}$ ✓',
 's4.b9.steps.3':   '$n\\to\\infty$ da $\\dfrac{n+2}{2^{n}}\\to0$, chunki koʻrsatkichli oʻsish chiziqlisidan tez. Limit $2$ ga teng.',
 's4.b9.ans':       '$2-\\dfrac{n+2}{2^{n}}$; limiti $2$.',
 's4.b10.text':     '**Chekli ayirmalar usuli.** Agar $a_n$ darajasi $d$ boʻlgan koʻphad bilan berilgan boʻlsa, $\\sum_{k\\le n}a_k$ darajasi $d+1$ boʻlgan koʻphad boʻladi. Bu formulani tez topish yoʻlini beradi: shu darajali koʻphadni nomaʼlum koeffitsiyentlar bilan olib, $n=0,1,\\dots,d+1$ ni qoʻyamiz va chiziqli tenglamalar sistemasini yechamiz. Isbot baribir kerak — odatda induksiya bilan.',
 's5.b0.text':      'Rekurrent munosabat hisoblash uchun qulay, lekin fikrlash uchun noqulay: $a_{100}$ ni bilish uchun barcha oldingi hadlarni bosib oʻtish kerak. Ketma-ketliklarning butun bir sinfi — chiziqli rekurrent munosabatlar — uchun **oshkor formula** olishning umumiy yoʻli bor.',
 's5.b1.name':      'Ikkinchi tartibli chiziqli rekurrent munosabat',
 's5.b1.text':      'Agar barcha $n$ uchun $$a_{n+2}=p\\,a_{n+1}+q\\,a_n\\qquad\\left(q\\ne0\\right)$$ bajarilsa va $a_0,a_1$ berilgan boʻlsa, ketma-ketlik **oʻzgarmas koeffitsiyentli ikkinchi tartibli chiziqli rekurrent munosabatni** qanoatlantiradi deyiladi. $$x^{2}-px-q$$ koʻphadi uning **xarakteristik koʻphadi** deyiladi.',
 's5.b2.name':      'Umumiy yechim',
 's5.b2.text':      '$x_1,x_2$ — xarakteristik koʻphadning ildizlari boʻlsin.\\n\\n**Agar $x_1\\ne x_2$** boʻlsa, shunday $A,B$ oʻzgarmaslar bor: $$a_n=A\\,x_1^{\\,n}+B\\,x_2^{\\,n}\\qquad\\text{barcha }n\\ge0\\text{ uchun} .$$\\n\\n**Agar $x_1=x_2=x$** boʻlsa, shunday $A,B$ bor: $$a_n=\\left(A+Bn\\right)x^{\\,n}.$$\\n\\nOʻzgarmaslar ikkita boshlangʻich qiymat bilan yagona tarzda aniqlanadi.',
 's5.b3.text':      '**1-qadam: geometrik ketma-ketliklar yechim boʻladi.** $a_n=x^{\\,n}$ ni qoʻyamiz: $$x^{\\,n+2}=p\\,x^{\\,n+1}+q\\,x^{\\,n}.$$ $x^{\\,n}\\ne0$ ga boʻlish aynan $x^{2}=px+q$ ni beradi. Demak $x^{\\,n}$ rekurrent munosabatni qanoatlantirishi uchun $x$ xarakteristik koʻphadning ildizi boʻlishi zarur va yetarli ✓\\n\\n**2-qadam: yechimlar yigʻindisi ham yechim.** Munosabat chiziqli: agar $u_n$ va $v_n$ uni qanoatlantirsa, $Au_n+Bv_n$ ham qanoatlantiradi, chunki $$A u_{n+2}+B v_{n+2}=p\\left(Au_{n+1}+Bv_{n+1}\\right)+q\\left(Au_n+Bv_n\\right) \\quad\\checkmark$$\\n\\n**3-qadam: oʻzgarmaslarni moslash.** $$\\begin{cases}A+B=a_0,\\\\ Ax_1+Bx_2=a_1.\\end{cases}$$ sistemasini yechamiz. Uning determinanti $x_2-x_1\\ne0$, shuning uchun yagona yechim mavjud ✓\\n\\n**4-qadam: yagonalik.** $a_0,a_1$ qiymatlari rekurrent munosabat bilan birga butun ketma-ketlikni aniqlaydi (induksiya). Bizning formula $a_0,a_1$ ni qayta hosil qiladi va munosabatni qanoatlantiradi, demak u har bir $n$ uchun $a_n$ bilan mos tushadi ✓\\n\\n**Karrali ildiz.** Bu holda $x_1=x_2=x=\\tfrac{p}{2}$ va $q=-x^{2}$. $n x^{\\,n}$ ham yechim ekanini tekshiramiz: $$\\left(n+2\\right)x^{\\,n+2}\\ \\overset{?}{=}\\ p\\left(n+1\\right)x^{\\,n+1}+q\\,n x^{\\,n}.$$ $p=2x$, $q=-x^{2}$ ni qoʻyib, $x^{\\,n+2}$ ni qisqartirsak, oʻng tomon $2\\left(n+1\\right)-n=n+2$ boʻladi ✓ Qolgani aynan shunday, sistema esa $A=a_0$, $\\left(A+B\\right)x=a_1$ ga aylanadi va $x\\ne0$ ($q\\ne0$ boʻlgani uchun) sababli yana yagona yechimga ega ✓ $\\blacksquare$',
 's5.b4.name':      'Bine formulasi',
 's5.b4.text':      '$F_1=F_2=1$, $F_{n+2}=F_{n+1}+F_n$ Fibonachchi sonlari uchun $$F_n=\\frac1{\\sqrt5}\\left(\\varphi^{\\,n}-\\psi^{\\,n}\\right),\\qquad \\varphi=\\frac{1+\\sqrt5}{2},\\quad \\psi=\\frac{1-\\sqrt5}{2}.$$',
 's5.b5.text':      'Bu yerda $p=q=1$, shuning uchun xarakteristik koʻphad $$x^{2}-x-1 ,$$ uning ildizlari $\\varphi$ va $\\psi$ (oltin nisbat va uning qoʻshmasi). Ular turlicha, shuning uchun $$F_n=A\\varphi^{\\,n}+B\\psi^{\\,n}.$$\\n\\n$F_0=0$ deb olish qulay (rekurrent munosabat buni majbur qiladi: $F_2=F_1+F_0$). Unda sistema $$\\begin{cases}A+B=F_0=0,\\\\ A\\varphi+B\\psi=F_1=1.\\end{cases}$$ Birinchisi $B=-A$ ni beradi; ikkinchisiga qoʻysak, $$A\\left(\\varphi-\\psi\\right)=1 .$$ Lekin $\\varphi-\\psi=\\sqrt5$, shuning uchun $A=\\dfrac1{\\sqrt5}$ va $B=-\\dfrac1{\\sqrt5}$ ✓ $\\blacksquare$',
 's5.b6.text':      'Bine formulasi paradoksal koʻrinadi: oʻng tomon irratsional sonlardan tuzilgan, chap tomon esa har doim butun son. Irratsional qismlar qisqaradi, chunki Nyuton binomi boʻyicha yoyganda $\\sqrt5$ ning toq darajasi bor har bir had qarama-qarshi ishoralar bilan ikki marta paydo boʻladi.\\n\\nAmaliy natija: $\\left|\\psi\\right|=\\dfrac{\\sqrt5-1}{2}\\approx0.618<1$, shuning uchun $\\psi^{\\,n}\\to0$ va $$F_n=\\left[\\frac{\\varphi^{\\,n}}{\\sqrt5}\\right]\\ \\text{(eng yaqin butun son)} .$$ Shu bilan birga $\\dfrac{F_{n+1}}{F_n}$ nisbati oltin nisbat $\\varphi\\approx1.618$ ga intilishi ham koʻrinadi.',
 's5.b7.q':         '$a_0=0$, $a_1=1$, $a_{n+2}=4a_{n+1}-4a_n$ uchun oshkor formulani toping.',
 's5.b7.steps.0':   'Xarakteristik koʻphad: $x^{2}-4x+4=\\left(x-2\\right)^{2}$ — $x=2$ karrali ildiz.',
 's5.b7.steps.1':   'Demak $a_n=\\left(A+Bn\\right)2^{\\,n}$.',
 's5.b7.steps.2':   '$a_0=0$ dan: $A=0$. $a_1=1$ dan: $\\left(0+B\\right)\\cdot2=1$, demak $B=\\tfrac12$.',
 's5.b7.steps.3':   'Shunday qilib, $a_n=\\dfrac{n}{2}\\cdot2^{\\,n}=n\\,2^{\\,n-1}$.',
 's5.b7.steps.4':   'Tekshiramiz: $a_2=2\\cdot2=4$, rekurrent munosabat esa $4\\cdot1-4\\cdot0=4$ ni beradi ✓',
 's5.b8.name':      'Bir jinsli boʻlmagan rekurrent munosabatlar',
 's5.b8.text':      '$$a_{n+1}=c\\,a_n+d\\qquad\\left(c\\ne1\\right)$$ koʻrinishidagi munosabat uchun **qoʻzgʻalmas nuqta** $t=\\dfrac{d}{1-c}$ mavjud va $b_n=a_n-t$ ketma-ketligi $c$ maxrajli geometrik progressiya boʻladi. Demak $$a_n=\\left(a_0-t\\right)c^{\\,n}+t .$$',
 's5.b9.text':      'Qoʻzgʻalmas nuqta $t=ct+d$ tenglamasini yechadi, bundan $t\\left(1-c\\right)=d$ va $t=\\dfrac{d}{1-c}$ (aynan shu yerda $c\\ne1$ kerak).\\n\\nBu tenglamani rekurrent munosabatdan ayiramiz: $$a_{n+1}-t=c\\,a_n+d-\\left(ct+d\\right)=c\\left(a_n-t\\right),$$ yaʼni $b_{n+1}=c\\,b_n$ — geometrik progressiya ✓ Demak $b_n=b_0c^{\\,n}$ va $a_n=b_n+t$ ✓ $\\blacksquare$',
 's5.b10.text':     'Qoʻzgʻalmas nuqta usuli universal: **koordinata boshini ketma-ketlik joyida turib qoladigan nuqtaga koʻchirsak**, sof geometrik progressiya qoladi. Birinchi boʻlimdagi $a_{n+1}=2a_n+1$ masalasi shunda ikki satrga sigʻadi: $t=-1$, demak $a_n+1=\\left(a_1+1\\right)2^{\\,n-1}=2^{\\,n}$, yaʼni $a_n=2^{\\,n}-1$.',
 's6.b0.name':      'Fibonachchi sonlari',
 's6.b0.text':      '$$F_0=0,\\qquad F_1=1,\\qquad F_{n+1}=F_n+F_{n-1}.$$ Dastlabki hadlar: $0,1,1,2,3,5,8,13,21,34,55,89,144,\\dots$',
 's6.b1.text':      'Bu sonlar olimpiadalarda doimo uchraydi — qoplashlar, toʻrdagi yoʻllar va boʻlinish haqidagi masalalarda. Ularning bir necha xossasini bilish foydali.',
 's6.b2.name':      'Dastlabki Fibonachchi sonlari yigʻindisi',
 's6.b3.text':      'Teleskoplash. $F_{k+2}=F_{k+1}+F_k$ munosabati $$F_k=F_{k+2}-F_{k+1}$$ ni beradi. $k$ ni $1$ dan $n$ gacha qoʻshamiz: $$\\sum_{k=1}^{n}F_k=\\sum_{k=1}^{n}\\left(F_{k+2}-F_{k+1}\\right)=F_{n+2}-F_{2}=F_{n+2}-1 . \\qquad\\blacksquare$$',
 's6.b4.name':      'Qoʻshni Fibonachchi sonlari oʻzaro tub',
 's6.b4.text':      'Har bir $n\\ge1$ uchun $\\gcd\\left(F_n,F_{n+1}\\right)=1$.',
 's6.b5.text':      '$d$ ham $F_n$ ni, ham $F_{n+1}$ ni boʻlsin. Unda $d$ ularning $F_{n+1}-F_n=F_{n-1}$ ayirmasini ham boʻladi. Takrorlasak, $d$ soni $F_{n-2}$ ni, keyin $F_{n-3}$ ni va shu tarzda $F_1=1$ gacha boʻladi. Demak $d=1$. $\\blacksquare$\\n\\nEʼtibor bering, bu aynan qoʻshni Fibonachchi sonlari juftligiga qoʻllangan Yevklid algoritmidir. Bunday juftliklarda u **eng uzun** ishlaydi — ular uning eng yomon holatidir.',
 's6.b6.q':         'Agar har bir qadamda bir yoki ikki pogʻona yuqoriga chiqilsa, $n$ pogʻonali zinapoyaga necha xil usulda chiqish mumkin?',
 's6.b6.steps.0':   'Javobni $c_n$ deb belgilaymiz.',
 's6.b6.steps.1':   'Oxirgi qadam yo bir pogʻona boʻlgan — unda biz $n-1$ pogʻonada turgan edik, yoki ikki pogʻona — unda $n-2$ da.',
 's6.b6.steps.2':   'Ikki hol kesishmaydi va hammasini qamrab oladi, shuning uchun $c_n=c_{n-1}+c_{n-2}$.',
 's6.b6.steps.3':   'Boshlangʻich qiymatlar: $c_1=1$ (bitta qadam), $c_2=2$ (ikki bittalik yoki bitta ikkilik).',
 's6.b6.steps.4':   'Demak $c_n$ — surilgan Fibonachchi ketma-ketligi: $c_n=F_{n+1}$.',
 's6.b6.steps.5':   'Tekshiramiz: $c_3=3$, $c_4=5$, $c_5=8$ — haqiqatan $F_4=3$, $F_5=5$, $F_6=8$ ✓',
 's6.b6.ans':       '$c_n=F_{n+1}$ usul.',
 's6.b7.text':      'Misolda ishlatilgan usul — **oxirgi qadam boʻyicha ajratish** — rekurrent munosabat tuzishning universal yoʻlidir. Soʻrang: «oxirgi qadam nima boʻlishi mumkin edi va undan oldin nima qolgan edi?» Javob — rekurrent munosabat.',
 's6.b8.name':      'Kassini ayniyati',
 's6.b8.text':      'Barcha $n\\ge1$ uchun $$F_{n-1}F_{n+1}-F_n^{2}=\\left(-1\\right)^{n}.$$',
 's6.b9.text':      '$n$ boʻyicha induksiya. $D_n=F_{n-1}F_{n+1}-F_n^{2}$ deb yozamiz.\\n\\n**Baza $n=1$:** $F_0F_2-F_1^{2}=0\\cdot1-1=-1=\\left(-1\\right)^{1}$ ✓\\n\\n**Qadam.** $F_{n+2}=F_{n+1}+F_n$ ni qoʻyamiz: $$D_{n+1}=F_nF_{n+2}-F_{n+1}^{2}=F_n\\left(F_{n+1}+F_n\\right)-F_{n+1}^{2}.$$\\n\\nEndi oxirgi haddagi bitta $F_{n+1}$ koʻpaytuvchini $F_n+F_{n-1}$ ga almashtiramiz: $$D_{n+1}=F_nF_{n+1}+F_n^{2}-F_{n+1}\\left(F_n+F_{n-1}\\right)=F_n^{2}-F_{n-1}F_{n+1}=-D_n .$$\\n\\nDemak har bir qadamda ishora almashadi va $D_1=-1$ dan $D_n=\\left(-1\\right)^{n}$ ✓ $\\blacksquare$',
 's6.b10.text':     'Kassini ayniyati mashhur kesish paradoksi ortida turadi: $8\\times8$ kvadrat toʻrt boʻlakka kesiladi va ular $5\\times13$ toʻrtburchakka yigʻiladi. Yuzlar $64-65=-1$ ga farq qiladi — aynan $F_5F_7-F_6^{2}$. Yoʻqolgan yuza diagonal boʻylab ingichka yoriqda yashiringan.',
 's6.b11.name':     'Qoʻshish formulasi',
 's6.b11.text':     'Barcha $m,n\\ge1$ uchun $$F_{m+n}=F_mF_{n+1}+F_{m-1}F_n .$$ Xususan, $m=n$ boʻlganda $F_{2n}=F_n\\left(F_{n+1}+F_{n-1}\\right)$.',
 's6.b12.text':     '$m$ ni qatʼiy olib, $n$ boʻyicha induksiya qilamiz.\\n\\n**Baza $n=1$:** oʻng tomon $F_mF_2+F_{m-1}F_1=F_m+F_{m-1}=F_{m+1}$ ✓\\n\\n**Baza $n=2$:** $F_mF_3+F_{m-1}F_2=2F_m+F_{m-1}=F_m+F_{m+1}=F_{m+2}$ ✓\\n\\n**Qadam.** Formulani $n$ va $n+1$ uchun faraz qilib, ikki tenglikni qoʻshamiz: $$F_{m+n}+F_{m+n+1}=F_m\\left(F_{n+1}+F_{n+2}\\right)+F_{m-1}\\left(F_n+F_{n+1}\\right).$$ Chap tomon $F_{m+n+2}$, oʻngdagi qavslar esa $F_{n+3}$ va $F_{n+2}$ ✓ Bu $n+2$ uchun formula $\\blacksquare$\\n\\n**Natija.** $m=n$ da $F_{2n}=F_n\\left(F_{n+1}+F_{n-1}\\right)$, demak $F_n\\mid F_{2n}$. Induksiya keyin $F_n\\mid F_{kn}$ ni beradi — bu $\\gcd\\left(F_m,F_n\\right)=F_{\\gcd\\left(m,n\\right)}$ ga qaratilgan asosiy qadam.',
 's6.b13.name':     'Fibonachchi sonlarining EKUBi',
 's6.b14.text':     '$m>n$ va $m=n+r$ boʻlsin. Qoʻshish formulasi $$F_m=F_{n+r}=F_rF_{n+1}+F_{r-1}F_n$$ ni beradi.\\n\\nIkkinchi had $F_n$ ga boʻlinadi, shuning uchun $$\\gcd\\left(F_m,F_n\\right)=\\gcd\\left(F_rF_{n+1},\\,F_n\\right).$$ Lekin ketma-ket Fibonachchi sonlari oʻzaro tub, yaʼni $\\gcd\\left(F_{n+1},F_n\\right)=1$ va $F_{n+1}$ koʻpaytuvchini tashlab yuborish mumkin: $$\\gcd\\left(F_m,F_n\\right)=\\gcd\\left(F_r,F_n\\right).$$\\n\\n$\\left(m,n\\right)$ dan $\\left(m-n,\\,n\\right)$ ga oʻtish — bu indekslarga qoʻllangan Yevklid algoritmining aynan bitta qadami. Uni takrorlab, $\\left(\\gcd\\left(m,n\\right),0\\right)$ ga yetamiz, $F_0=0$ boʻlgani uchun $$\\gcd\\left(F_m,F_n\\right)=F_{\\gcd\\left(m,n\\right)} \\quad\\checkmark\\qquad\\blacksquare$$',
 's6.b15.q':        '$\\gcd\\left(F_{100},F_{60}\\right)=F_{20}$ ekanini isbotlang va $F_{20}$ ni hisoblang.',
 's6.b15.steps.0':  'Teoremaga koʻra $\\gcd\\left(100,60\\right)$ ni topish kifoya.',
 's6.b15.steps.1':  'Yevklid: $100=1\\cdot60+40$, $60=1\\cdot40+20$, $40=2\\cdot20$. Demak $\\gcd=20$ ✓',
 's6.b15.steps.2':  'Yigirmanchisigacha Fibonachchi sonlarini yozamiz: $1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765$.',
 's6.b15.steps.3':  'Demak $\\gcd\\left(F_{100},F_{60}\\right)=F_{20}=6765$.',
 's6.b16.text':     '**Zekendorf teoremasi.** Har bir natural son hech ikkitasi ketma-ket boʻlmagan turli Fibonachchi sonlari yigʻindisi shaklida yagona tarzda yoziladi. Masalan, $$100=89+8+3=F_{11}+F_6+F_4 .$$ Bu yoyilma jadal usulda topiladi: sigʻadigan eng katta Fibonachchi sonini ketma-ket ayirib boramiz.',
 's7.b0.text':      'Koʻp olimpiada masalalari alohida had haqida emas, balki ketma-ketlik uzoq muddatda nima qilishi haqida soʻraydi. Ehtiyotkorlik bilan javob berish uchun ikki tushuncha va bitta teorema kifoya.',
 's7.b1.name':      'Chegaralanganlik va monotonlik',
 's7.b1.text':      '$\\left(a_n\\right)$ ketma-ketlik har bir $n$ uchun $a_{n+1}\\ge a_n$ boʻlsa **oʻsuvchi**, $a_{n+1}\\le a_n$ boʻlsa **kamayuvchi** deyiladi. Agar biror $M$ uchun barcha $n$ da $a_n\\le M$ boʻlsa, u **yuqoridan chegaralangan**, agar biror $m$ uchun $a_n\\ge m$ boʻlsa, **pastdan chegaralangan** deyiladi.',
 's7.b2.name':      'Monoton ketma-ketlik haqidagi teorema',
 's7.b2.text':      'Yuqoridan chegaralangan oʻsuvchi ketma-ketlik limitga ega va u oʻzining aniq yuqori chegarasiga teng. Pastdan chegaralangan kamayuvchi ketma-ketlik uchun ham shunday.',
 's7.b3.text':      'Bu teorema haqiqiy sonlarning **toʻliqligi**ning bir shakli; ratsional sonlar ichida u bajarilmaydi. $1;\\ 1.4;\\ 1.41;\\ 1.414;\\dots$ oʻnli yaqinlashishlar oʻsadi va chegaralangan, lekin ularning limiti $\\sqrt2$ ratsional emas.\\n\\nOlimpiadada teorema tayyor vosita sifatida ishlatiladi: monotonlikni (ketma-ket hadlarning ayirmasi yoki nisbatidan) va chegaralanganlikni (induksiya bilan) isbotlaymiz; shundan keyin limit mavjud boʻladi va tenglamadan topiladi.',
 's7.b4.q':         '$a_1=\\sqrt2$ va $a_{n+1}=\\sqrt{2+a_n}$ boʻlsin. Limit mavjudligini isbotlang va uni toping.',
 's7.b4.steps.0':   '**Chegaralanganlik.** Induksiya bilan $a_n<2$. Baza: $a_1=\\sqrt2<2$ ✓ Qadam: agar $a_n<2$ boʻlsa, $a_{n+1}=\\sqrt{2+a_n}<\\sqrt{4}=2$ ✓',
 's7.b4.steps.1':   '**Monotonlik.** $a_{n+1}$ ni $a_n$ bilan solishtiramiz: $a_n>0$ boʻlganda $\\sqrt{2+a_n}>a_n$ tengsizligi $2+a_n>a_n^{2}$ ga, yaʼni $\\left(a_n-2\\right)\\left(a_n+1\\right)<0$ ga teng kuchli, bu esa $0<a_n<2$ boʻlgani uchun bajariladi ✓',
 's7.b4.steps.2':   'Ketma-ketlik oʻsadi va yuqoridan chegaralangan, demak $L$ limiti mavjud.',
 's7.b4.steps.3':   '**Limit uchun tenglama.** Rekurrent munosabatda limitga oʻtamiz: $L=\\sqrt{2+L}$, bundan $L^{2}-L-2=0$ va $L\\in\\left\\{2,-1\\right\\}$.',
 's7.b4.steps.4':   'Barcha hadlar musbat, shuning uchun $L=2$ ✓',
 's7.b4.ans':       'Limit $2$ ga teng.',
 's7.b5.text':      'Qadamlarning tartibi juda muhim. $L=\\sqrt{2+L}$ tenglamasi **faqat limit mavjudligi maʼlum boʻlgandan keyin** maʼnoga ega. Uni darhol yozish uzoqlashuvchi ketma-ketlikning ham «limitini topish» ga imkon beradi: $a_{n+1}=2a_n$ uchun $L=2L$ tenglamasi $L=0$ ni beradi, holbuki ketma-ketlik ($a_1=1$ da) cheksizlikka ketadi.',
 's7.b6.name':      'Cheksiz geometrik progressiya yigʻindisi',
 's7.b6.text':      'Agar $\\left|q\\right|<1$ boʻlsa, $$b_1+b_1q+b_1q^{2}+\\dots=\\frac{b_1}{1-q}.$$ $\\left|q\\right|\\ge1$ va $b_1\\ne0$ boʻlganda yigʻindi mavjud emas.',
 's7.b7.text':      'Xususiy yigʻindi $$S_n=b_1\\frac{1-q^{\\,n}}{1-q}=\\frac{b_1}{1-q}-\\frac{b_1q^{\\,n}}{1-q}.$$\\n\\nAgar $\\left|q\\right|<1$ boʻlsa, $q^{\\,n}\\to0$, ikkinchi had yoʻqoladi va $S_n\\to\\dfrac{b_1}{1-q}$ ✓\\n\\nAgar $\\left|q\\right|\\ge1$ boʻlsa, hadlar nolga intilmaydi ($\\left|b_1q^{\\,n}\\right|\\ge\\left|b_1\\right|>0$), bu esa qator yaqinlashishi uchun zaruriy shart: agar qator yaqinlashsa, $S_n$ va $S_{n-1}$ bir xil limitga ega boʻladi, demak ularning ayirmasi — keyingi had — nolga intiladi ✓ $\\blacksquare$',
 's7.b8.text':      '«Hadlar nolga intiladi» sharti zaruriy, lekin **yetarli emas**. Klassik qarshi misol — garmonik qator $$1+\\frac12+\\frac13+\\frac14+\\dots ,$$ u hadlari nolga kichrayishiga qaramay uzoqlashadi. Oremning isboti: hadlarni uzunliklari $1,2,4,8,\\dots$ boʻlgan bloklarga guruhlaymiz; har bir blok kamida $\\tfrac12$, shuning uchun yigʻindi chegarasiz oʻsadi.',
}
